### ISSUE TITLE
startup_mode: Maximized now open windows of only half the height of the screen

### ISSUE THREAD

**Issue by Porkepix** [alacritty/alacritty#6397] opened 2022-10-14 07:19 UTC
Opening a new terminal window with `startup_mode: Maximized` in the configuration file open a window using the full width, but only around half the height of the screen, regressing from version 0.10.1 which didn't have such issue.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Wayland

### Logs

```$ alacritty -vv
Created log file at "/tmp/Alacritty-1481489.log"
[0.000003659s] [INFO ] [alacritty] Welcome to Alacritty
[0.000451191s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000552679s] [INFO ] [alacritty] Running on Wayland
[0.006323637s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/clement/.config/alacritty/alacritty.yml"
[0.008678269s] [DEBUG] [alacritty] Loading "Deja Vu Sans Mono" font
[0.045552357s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.055255922s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.064578277s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.074162543s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.076997716s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.077028508s] [DEBUG] [alacritty] Estimated window size: None
[0.077045916s] [DEBUG] [alacritty] Estimated cell size: 6 x 13
[0.083977259s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.160106736s] [INFO ] [alacritty] Running on Mesa Intel(R) HD Graphics 520 (SKL GT2)
[0.160168855s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.172451144s] [INFO ] [alacritty] Display scale factor: 1
[0.172486868s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.190532053s] [INFO ] [alacritty] Cell size: 6 x 13
[0.190588839s] [INFO ] [alacritty] Padding: 0 x 0
[0.190600787s] [INFO ] [alacritty] Width: 800, Height: 600
[0.191691412s] [INFO ] [alacritty] PTY dimensions: 46 x 133
[0.195551436s] [INFO ] [alacritty] Initialisation complete
[0.197231599s] [DEBUG] [alacritty_terminal] New num_cols is 320 and num_lines is 77
[0.202646189s] [INFO ] [alacritty] Padding: 0 x 0
[0.202706719s] [INFO ] [alacritty] Width: 1920, Height: 1013
[0.223974488s] [DEBUG] [alacritty_terminal] New num_cols is 320 and num_lines is 46
[0.224036097s] [INFO ] [alacritty] Padding: 0 x 0
[0.224057400s] [INFO ] [alacritty] Width: 1920, Height: 600
[3.451812956s] [DEBUG] [alacritty_terminal] New num_cols is 320 and num_lines is 77
[3.459509384s] [INFO ] [alacritty] Padding: 0 x 0
[3.459577671s] [INFO ] [alacritty] Width: 1920, Height: 1013
[3.480475556s] [DEBUG] [alacritty_terminal] New num_cols is 133 and num_lines is 46
[3.492609985s] [INFO ] [alacritty] Padding: 0 x 0
[3.492721301s] [INFO ] [alacritty] Width: 800, Height: 600
```

**Comment by chrisduerr** [comment] 2022-11-08 07:31
Which compositor are you using?

**Comment by Porkepix** [comment] 2022-11-08 09:58
> Which compositor are you using?

Standard Gnome Wayland, so I guess the answer is mutter?

**Comment by kchibisov** [comment] 2023-03-07 20:10
Duplicate of #6184

**Closed by kchibisov** 2023-03-07 20:10 UTC
Labels: B - bug, DS - Wayland

**Comment by Porkepix** [comment] 2023-03-07 20:16
Dunno if that's the same issue though @kchibisov ; people in the issue you mention talks about the problem starting on version 0.10.1 already. Here, I re-tested again, that's a regression in 0.11.0 for me: 0.10.1 isn't affected here and the same config opens a maximized window with version 0.10.1.

**Comment by kchibisov** [comment] 2023-03-07 20:27
@Porkepix it's the same, I figured out the root cause of it and fixed in my tree. It wasn't the issue before due to some luck, I'd assume.

If you're into running dev branches you can try https://github.com/alacritty/alacritty/pull/6758.

**Comment by Porkepix** [comment] 2023-04-03 22:45
@kchibisov should probably be rebased after 0.12 release; I might try to give a look at a build (never built yet).

Though release 0.12 made things even worse. On my work computer (that I'll soon need to return), now opening Alacritty from Gnome programs' list (Activities) now open it fullscreen with an instant loss of focus, the focus going back to the window that had the focus before opening Alacritty. Then switching focus back to Alacritty, either with alt + tab or with a mouse click resize the window to the size that of the issue I reported here.

Even worse, while my work computer seems to have a reproduction rate of 100% of the problem I just described, my personal computer running the same distro (Arch Linux) with the same environment seems to reproduce this issue randomly. Sometimes I get the issue described above, sometimes I get the issue originally described here.

**Comment by kchibisov** [comment] 2023-04-03 22:58
>@kchibisov should probably be rebased after 0.12 release; I might try to give a look at a build (never built yet).

I've rebased the branch. If you can run it that would be nice, since it really needs some testing on anything outside the sway.

**Comment by Porkepix** [comment] 2023-04-03 23:06
> > @kchibisov should probably be rebased after 0.12 release; I might try to give a look at a build (never built yet).
> 
> I've rebased the branch. If you can run it that would be nice, since it really needs some testing on anything outside the sway.

So, I've just tested: the window not opened in maximized mode as it should and as it used to be in the past in fixed with this branch. However this does nothing for this new "loss of focus" issue when opened from Gnome's activities that appeared with 0.12. But that's maybe yet another issue.

**Comment by kchibisov** [comment] 2023-04-03 23:08
So is maximized window fixed for you?

**Comment by Porkepix** [comment] 2023-04-03 23:11
> So is maximized window fixed for you?

On Gnome at least, yes (I didn't gave a try on other stacking environments such as XFCE or KDE, but I don't even know if those were affected by this issue).

**Comment by kchibisov** [comment] 2023-04-03 23:12
>However this does nothing for this new "loss of focus" issue when opened from Gnome's activities that appeared with 0.12. But that's maybe yet another issue.

If you can somehow demonstrate how it looks like maybe I can see what happens.

Could you provide me `WAYLAND_DEBUG=1 alacritty --print-events` log when reproducing this focused issue? You can likely edit the desktop file to redirect such log somewhere.

**Comment by Porkepix** [comment] 2023-04-04 00:26
For the focus issue, we discussed it on IRC, and this is a regression in Mutter.
