### ISSUE TITLE
alacritty crashed with freetype-2.12.1 on gentoo

### ISSUE THREAD

**Issue by yuqiancn** [alacritty/alacritty#6432] opened 2022-10-21 14:15 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

My alacritty cannot run as usually after update freetype-2.12.1 in my laptop, it run and crashed every times.

### System

OS: 
Linux Amazing 5.15.52-gentoo-dist #1 SMP Fri Jul 22 04:01:28 -00 2022 x86_64 Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz GenuineIntel GNU/Linux
Version: alacritty 0.10.1 ()
Linux/BSD: Xorg-X11 7.4-r3, i3wm with picom

### Logs

Crashes: 
"thread 'main' panicked at 'attempt to subtract with overflow', alacritty/src/renderer/builtin_font.rs:369:38"

Font/Terminal size: 
```
[0.000116528s] [INFO ] [alacritty] Welcome to Alacritty
[0.000440072s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000544217s] [INFO ] [alacritty] Running on X11
[0.022857802s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/#######/.config/alacritty/alacritty.yml"
[0.033847103s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.034869103s] [DEBUG] [alacritty] Estimated DPR: 1.5
[0.034927458s] [DEBUG] [alacritty] Estimated window size: None
[0.034947830s] [DEBUG] [alacritty] Estimated cell size: 9 x 1
[0.094439711s] [INFO ] [alacritty] Device pixel ratio: 1.5
[0.113482055s] [INFO ] [alacritty] Initializing glyph cache...
[0.116513419s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.120327461s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.124201798s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.128940257s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.161396068s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.047813075s
[0.161686761s] [INFO ] [alacritty] Cell size: 9 x 1
[0.161733105s] [INFO ] [alacritty] Padding: 0 x 0
[0.161783885s] [INFO ] [alacritty] Width: 800, Height: 600
[0.167248179s] [INFO ] [alacritty] PTY dimensions: 600 x 88
[0.178553617s] [INFO ] [alacritty] Initialisation complete
[0.185569036s] [DEBUG] [alacritty_terminal] New num_cols is 211 and num_lines is 2105
[0.254415884s] [INFO ] [alacritty] Padding: 0 x 0
[0.254486844s] [INFO ] [alacritty] Width: 1901, Height: 2105
[0.680101612s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.680875755s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
```

Keyboard and bindings: 
```
[0.150140402s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.150610193s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[0.151257310s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(46137348))), event: Resized(PhysicalSize { width: 1901, height: 2105 }) }
[0.151356902s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(46137348))), event: Moved(PhysicalPosition { x: 1927, y: 43 }) }
[0.151596469s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(46137348))), event: Focused(true) }
[0.151673430s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(46137348))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: -685.0, y: 1429.0 }, modifiers: (empty) } }
[0.151847955s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(46137348)))), payload: Terminal(Wakeup) })
[0.151892740s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.151976987s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(X(WindowId(46137348))))
[0.152017708s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.204005321s] [INFO ] [alacritty] Padding: 0 x 0
[0.204096753s] [INFO ] [alacritty] Width: 1901, Height: 2105
```

**Comment by kchibisov** [comment] 2022-10-21 18:37
While the crash you're seeing is due to you building alacritty in debug mode(debug flag on rust packages is to build without opitimizations). The issue is that your font height is just `1`, so even if it'll work for you it means that you won't see font anyway...

**Comment by kchibisov** [comment] 2022-10-21 18:52
I've opened a patch to fix the crash, but you should likely check why freetype is telling that your font height is 1.

**Comment by yuqiancn** [comment] 2022-10-22 08:14
I have asked freetype and this is the [issue page with their answer](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1188).

maybe it's useful for improve.

**Comment by kchibisov** [comment] 2022-10-22 08:48
We do multiply, etc. I also use freetype 2.12.1 and don't have any issues. Try different font.

**Comment by yuqiancn** [comment] 2022-10-22 11:43
I have tried. There are some problem with Source Code Pro font.

**Comment by kchibisov** [comment] 2022-10-22 12:02
Try updating your font, I think that one had issues with svg's in it.

**Comment by apodtele** [comment] 2022-10-22 17:08
The [OT-SVG support](https://freetype.org/freetype2/docs/reference/ft2-svg_fonts.html) is new to FreeType and relies on external SVG libraries, which you might be missing. Setting this up is not trivial. I suggest asking on freetype@nongnu.org. If you really needed. Even if you want a more graceful fallback, other than size 1, you should ask or make suggestion there.

**Comment by kchibisov** [comment] 2022-10-22 17:29
@apodtele Can't we opt-out from OT-SVG thing? We don't use it and it's optional from what I can see why it started to break random fonts? Do we have to say freetype that we don't support that?

I mean rendering SVG's is not an issue, especially with rust infra, the problem is that we don't support them now and all old versions won't support them as well meaning that freetype did a breaking change? Like old alacritty won't work anymore if freetype built with svg support?

That all looks like a freetype bug to me, since you do a minor bump breaking fonts for all old clients.

The problem is not that we can use `librsvg` to handle `OT-SVG` with freetype, the problem is that all old versions of alacritty can't do that, since only new one get a patch. I'd guess we're not the only application affected by that.

**Comment by apodtele** [comment] 2022-10-22 19:41
Affected by what? So far we have not received any coherent bug reports or a problem description. We would appreciate a comparison between the old and and new behaviors that annoys you so much, or something that would qualify as a regression.

**Comment by yuqiancn** [comment] 2022-10-23 01:05
@kchibisov I find an [old issue](https://github.com/alacritty/alacritty/issues/6048) about similar problem.

**Comment by kchibisov** [comment] 2022-10-23 07:07
@apodtele the problem is that font is not really an svg font, it has some svg glyphs in it, but not all of them. So for example with freetyp `2.11` this font has a normal height, but with the freetype `2.12` it's not, because now freetype detects `svg` glyphs inside of it and uses the height 1. If the font was purely made of svgs it would make some sense, but this particular one is not.

>new behaviors that annoys you so much

It annoys me because this font works with freetype 2.11 and not with freetype 2.12 indicating that we need to add extra handling for freetype 2.12, but that handling won't be there for old versions of alacritty. It's not like I do care about old versions that much, I just don't like when something like that breaks.

@yuqiancn 
This particular font got patched to not contain them or something like that from what I remember and if you read through the issue #6048 you may notice that it got solved with a font update, since newer versions of the font don't have svg's in it.

**Comment by apodtele** [comment] 2022-10-23 13:03
That font is [SanSourceCodePro-Regular version 2.030](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it). It contains an SVG table. Is that correct? It shows Ok in [ftview](https://gitlab.freedesktop.org/freetype/freetype-demos) with current FreeType master.  A few fails, I assume, come from SVG, which I do not have on Windows.

What you mean by "uses height 1"? Which FreeType API returns that? I would really appreciate if you filed an issue with FreeType with that information. Keep in mind that this might have been fixed [already](https://gitlab.freedesktop.org/freetype/freetype/-/commits/master?search=SVG).

**Comment by kchibisov** [comment] 2022-10-23 14:24
@apodtele It seems like our issue was that we assumed that colored fonts are not scalable, but this one is colored scalable font. At least freetype tells us that this font has color.

**Comment by kchibisov** [comment] 2022-10-23 14:27
@yuqiancn this should fix your issue https://github.com/alacritty/crossfont/pull/49

**Comment by apodtele** [comment] 2022-10-23 14:33
Yes, there are two kinds of colored scalable fonts now: SVG and COLR. FreeType can render solid colored COLR v0. Gradients and other fancy coloring of SVG and COLRv1 require external rendering.

**Comment by kchibisov** [comment] 2022-10-23 14:51
Aye, I just forgot that `Source Code Pro` is a **colored** font, so that why it broke. Anyway, it'll be fixed with the next alacritty patch version.

Alternatively @yuqiancn you can use the same font from the gentoo repo, it's not having that issues for example.

**Comment by yuqiancn** [comment] 2022-10-24 12:39
May be the phenomenon is the same as #6048 , and the crush phenomenon may because the default behavier of i3wm to kill the terminal.

**Comment by kchibisov** [comment] 2022-10-24 12:53
The crash is already fixed and the height thing is also fixed, but not pulled yet.

**Comment by yuqiancn** [comment] 2022-10-25 08:03
okey.

**Closed** 2022-10-25 22:32 UTC
