### ISSUE TITLE
Xorg Clipboard paste's content is "lagged behind"

### ISSUE THREAD

**Issue by da-x** [alacritty/alacritty#3601] opened 2020-04-17 18:03 UTC
After a day or two of Alacritty instance uptime, I notice that clipboard updates (usually copies) from other programs get "lagged behind". When performing a paste action, the old (i.e. wrong) content gets emitted. I have to wait a second between a copy from one program, until I paste in Alacritty. A new Alacritty instance being spawn does not exhibit this behavior, and sees updated clipboard content without a lag.

This might be a copypaste issue or a x11-clipboard issue, but I'm not sure how to debug this.

### System

OS: Linux
Version: alacritty 0.4.2 (f68de375b67d)
Linux/BSD: X11

**Comment by kchibisov** [comment] 2020-04-17 18:09
Maybe there's something with our X11 clipboard and it has a lot of events to care and lags behind, and new instance has nothing to process and works just fine.

**Comment by da-x** [comment] 2020-04-17 19:58
That sounds about right - I'll look into that code.

**Comment by da-x** [comment] 2020-04-17 21:50
Experimenting with the following program running in the background:

```rust
use copypasta::ClipboardProvider;
use copypasta::ClipboardContext;

fn main() {
    let mut ctx = ClipboardContext::new().unwrap();

    loop {
        println!("{:?}", ctx.get_contents());

        std::thread::sleep(std::time::Duration::from_millis(100));
    }
}
```

After a few hours of uptime, I don't see a lag yet, but I do see occasional errors:

```
Ok("Maybe there\'s something with")
Ok("Maybe there\'s something with")
Err(UnexpectedType(0))
Ok("Maybe there\'s something with")
Ok("Maybe there\'s something with")
Err(UnexpectedType(0))
Ok("Maybe there\'s something with")
Ok("Maybe there\'s something with")
Err(UnexpectedType(0))
Ok("Maybe there\'s something with")
Ok("Maybe there\'s something with")
Err(UnexpectedType(0))
Ok("Maybe there\'s something with")
```
These errors don't appear in a fresh invocation of the program.

It's only a clue for now.

**Comment by da-x** [comment] 2020-04-18 08:55
Pinging @quininer as this may be an issue in `x11-clipboard`.

**Comment by quininer** [comment] 2020-04-18 10:04
Interesting, I will try to reproduce it.

**Comment by quininer** [comment] 2020-04-19 10:03
I have been running for a while, and it seems that no errors appear.

**Comment by quininer** [comment] 2020-04-19 10:04
I have been running for a while, and it seems that no errors appear.

**Comment by expipiplus1** [comment] 2021-06-13 04:05
FWIW I can confirm that this definitely still happens, although given that it *seems* to happen only on long sessions repro is quite challenging.

**Comment by NiklausHofer** [comment] 2021-11-03 16:22
I am also seeing this issue with Alacritty 0.9.0 on Wayland / river.

It would seem that this was also discussed in other places: https://githubmemory.com/repo/alacritty/copypasta/issues/32

**Comment by alipio** [comment] 2021-11-22 20:54
Same thing here, I have to paste twice in order to get the new content from the clipboard. When I open a new `alacritty` instance, everything works as expected. I'm running it for about 5 days or so.

version: alacritty 0.9.0
os: Ubuntu 20.04

**Comment by awused** [comment] 2023-07-21 00:55
I started noticing this just over the last couple of days when I'd never seen it before. I can't think of anything relevant I've changed. I have one particular terminal open, right now, that has been routinely dropping pastes (I can paste small bits of plain text multiple times in a row and some are just dropped, sometimes up to 50% of them) or lagging behind and pasting old content. The other two alacritty siblings it has, which are about the same age, don't exhibit this at all. No other program is doing this.

**Comment by awused** [comment] 2023-07-21 01:58
Here is code to reliably (so far, 100%) reproduce the problem, using gtk because I already knew how to handle it. This is certainly a bug somewhere in the alacritty application, not an X11/wayland bug.

To reproduce:
1. Run this program
2. As soon as the window appears, paste into an alacritty terminal. You have a 7 second grace period since alacritty, internally, uses a 3 second timeout.
4. Wait until it prints "timeout-done"
5. That alacritty window is now stuck in this buggy state, permanently.

Someone mentioned it was using sync::mpsc channels, and my best guess is that something is using a channel to send loads from the clipboard, but stops reading it after the timeout. If setting the clipboard succeeds within 3 seconds it's fine, if it fails it's fine, but if it succeeds after 3 seconds then the stale value is being sent on a channel that no one is listening to. The next time a load is requested it starts a load but receives the stale value on that channel.

```rust
use std::thread;
use std::time::Duration;

use gtk::prelude::{ApplicationExt, ApplicationExtManual, DisplayExt};
use gtk::traits::WidgetExt;
use gtk::{glib, Application, ApplicationWindow};

fn main() -> glib::ExitCode {
    let app = Application::builder().application_id("org.example.HelloWorld").build();

    app.connect_activate(|app| {

        let window = ApplicationWindow::builder()
            .application(app)
            .default_width(320)
            .default_height(200)
            .title("Hello, World!")
            .build();

        let clip = window.display().clipboard();

        clip.set_text("some-text");
        println!("paste now");
        thread::sleep(Duration::from_secs(10));
        println!("timeout done");
    });

    app.run()
}

```

**Comment by da-x** [comment] 2023-07-21 05:50
@awused you've got it! Glad my hunch around copypasta was correct 😄 .

**Comment by awused** [comment] 2023-07-21 17:59
@kchibisov this should be fixed by x11-clipboard [0.8.1](https://github.com/quininer/x11-clipboard/commit/c7fd2a93c93a7690478953db87de849d47ce9f2a) if you could pull that through into a new version of copypasta and into the next release of alacritty.

**Comment by kchibisov** [comment] 2023-07-22 13:57
@chrisduerr could you test it? On XWayland it's still sort of broken, but it could be just xwayland being xwayland...

**Comment by awused** [comment] 2023-07-22 14:51
I haven't touched any wayland code, but I assume xwayland is using the x11 path. The fix is very simple and it at least fully solves stale pasted values, so if there is still something wrong on xwayland specifically it's a different bug. My reproduction is 100% with git head alacritty, but it's completely fixed when I replace copypasta with my local copy using the patched x11-clipboard.

**Comment by kchibisov** [comment] 2023-07-22 14:57
XWayland is basically X11, but it could have inner conversions inside compositor, so I can't say whether it really matters. In general, I don't care how XWayland works, I've just said that I can't verify the fix because I don't have native X11 session.

**Comment by chrisduerr** [comment] 2023-07-22 17:53
> @chrisduerr could you test it? On XWayland it's still sort of broken, but it could be just xwayland being xwayland...

Test what? I was never able to reproduce this issue. Or do you mean just testing that 0.8.1 works in general?

**Comment by kchibisov** [comment] 2023-07-22 17:59
@chrisduerr hm, I thought for a moment that this issue is related to paste on repeat, but maybe it's not?

**Comment by chrisduerr** [comment] 2023-07-22 18:11
I wasn't aware of the paste on repeat issue, but that one I can reproduce.

This issue is about actually pasting *incorrect* clipboard content though, which I can **not** reproduce.

**Comment by kchibisov** [comment] 2023-07-22 18:15
Ah, ok. If someone here could verify the fix I can apply it.

**Comment by awused** [comment] 2023-07-22 19:06
@chrisduerr @kchibisov  I have a 100% reliable reproduction in https://github.com/alacritty/alacritty/issues/3601#issuecomment-1644882779 which is just a few comments up, have you tried that? It also explains what the issue is: Alacritty has a 3 second timeout on reading pastes, and if that timeout is hit but the paste later succeeds, x11-clipboard without my fix will return old values (which it sometimes misinterprets, causing skipped pastes).

**Comment by kchibisov** [comment] 2023-07-22 19:09
@awused I mean your fix will automatically apply eventually due to dependency update, it's a matter of how fast it'll apply.

**Comment by awused** [comment] 2023-07-22 19:13
Yeah, but I did post a reproduction that is reliable at least on X11. I pinged you because you appeared to be the primary maintainer of copypasta which only updates to bump dependencies so I thought it was a reasonable to ask for a new version of it. I wasn't asking for a new alacritty to be cut right now, just making sure that the patched x11-clipboard is in the next regular release.

**Comment by kchibisov** [comment] 2023-07-22 19:15
@awused I'll bump copypasta once I update smithay-clipboard, so it'll be somewhere before the alacritty release.

**Closed** 2023-10-21 18:56 UTC
Labels: B - bug, DS - X11

**Comment by kchibisov** [comment] 2023-12-29 21:10
@awused seems like it broke a clipboard for a bunch of people: https://github.com/alacritty/alacritty/issues/7501 and probably this https://github.com/alacritty/alacritty/issues/7500

**Comment by awused** [comment] 2023-12-29 21:40
I'd be very surprised if it was caused by [my fix](https://github.com/quininer/x11-clipboard/pull/39), which is a very straightforward change that only discards stale values from the X server. It certainly cannot cause stale values to be read where they wouldn't have been before, which is what https://github.com/alacritty/alacritty/issues/7501 looks to be. Most likely it's caused by something else in copypasta 10. Given how many months it has been and I've been running a locally patched version of alacritty with my fix all that time - without any issues around copying and pasting - I think you should be looking elsewhere for the cause of the bug.


Try copying and pasting into the demo program from https://github.com/alacritty/alacritty/issues/3601#issuecomment-615479746 (possibly against new and old copypasta) to try and figure out if it's a copypasta issue or an alacritty issue.

**Comment by kchibisov** [comment] 2023-12-29 21:43
copypasta just bumped the dependency to `0.8.1` which is the latest, nothing else in it changes anything and as you can see nothing was contributed to copypasta on X11 besides the requested update.

Like clearly lowering x11-clipboard dependency fixes the issue.

**Comment by awused** [comment] 2023-12-29 21:47
x11-clipboard also bumped x11rb up two major versions between 0.7.1 and 0.8.0 (from 0.10 to 0.12), which wasn't included in copypasta before. My change to x11-clipboard is easy to roll back locally to test, and you're welcome to do that and report if it changes things, but I would be very surprised if discarding stale values that weren't discarded before results in new stale values being read. Either way, I can't reproduce that shift-insert bug.

**Comment by kchibisov** [comment] 2023-12-29 21:49
Yeah, probably, I just know that if it's not it I'd have to revert the entire bump, since you asked to bump the dependency, and maybe your fix was not the one breaking it, but that's basically the same issue...

**Comment by awused** [comment] 2023-12-29 22:10
I switched to alacritty 0.13.0 from (cargo install) and tried to reproduce https://github.com/alacritty/alacritty/issues/7501#issuecomment-1872323353 after a reboot, following what I think had to have been the exact steps involved (start terminal immediately after login with keyboard shortcut, `echo testing`, highlight "testing", and paste with `shift+insert`). I wasn't able to reproduce that bug and got the expected highlighted text.

**Comment by awused** [comment] 2023-12-29 22:45
I'm a lot more confident in saying this is probably unrelated to my fix. I installed copyq to test https://github.com/alacritty/alacritty/issues/7500 and found that it's broken on 0.13.0 even with copypasta 0.8.0, and copyq works as expected on alacritty 0.12.3 even with copypasta 0.10.0.

**Comment by kchibisov** [comment] 2023-12-29 22:54
That would be really strange that clipboard is broken from a clipboard, and clipboard in alacritty was not changed since 0.10 I think. Maybe copyq speculates with input, but I guess its issue is different issue.

we still have shift + insert to figure out, but I don't quite understand what user even wants in it.
