### ISSUE TITLE
how enable ligatures on archlinux

### ISSUE THREAD

**Issue by huwqchn** [alacritty/alacritty#6544] opened 2022-12-03 10:10 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment] 2022-12-03 11:15
Duplicate of #50

**Closed by kchibisov** 2022-12-03 11:15 UTC
