### ISSUE TITLE
Font icons dont appear

### ISSUE THREAD

**Issue by ChrisTsou** [alacritty/alacritty#3643] opened 2020-04-26 12:08 UTC
### System
OS: Windows
Windows: ConPTY

![Capture](https://user-images.githubusercontent.com/25465975/80306900-96215100-87ce-11ea-9c36-46039f802325.PNG)
![Capture1](https://user-images.githubusercontent.com/25465975/80306901-99b4d800-87ce-11ea-9328-3594c816f736.PNG)

config: https://pastebin.com/rMWniiLS

i don't know what other info is needed here, i'm a rookie at ... everything.
edit:  img on the left is wsltty, i'm running zsh with starship.

**Comment by chrisduerr** [comment] 2020-04-26 13:20
Have you tried the latest master? Font fallback is not yet available on Windows with version 0.4.2, but it was recently added upstream.

**Comment by ChrisTsou** [comment] 2020-04-26 13:55
No i just got the installer from releases, but the font i'm using is Fira Code from nerd fonts, isn't it supposed to have those symbols in it?

**Comment by kchibisov** [comment] 2020-04-26 14:03
I guess no, but you can figure that out by trying master branch and see if fallbacks are working for you. From what I can see 2 monochrome emoji glyphs are from system windows font.

**Comment by ChrisTsou** [comment] 2020-04-26 14:07
I guessed "trying master" means clone and build right? i'm in the process of figuring how to do that atm

**Comment by kchibisov** [comment] 2020-04-26 14:10
>I guessed "trying master" means clone and build right?

Yeah, it's just `git clone https://github.com/alacritty/alacritty` and running `cargo build --release`, you'll need rust toolchain and also clang.

https://github.com/alacritty/alacritty/blob/master/INSTALL.md#windows

**Comment by ChrisTsou** [comment] 2020-04-26 14:47
I was trying to figure some stuff out it took some time. Is it possible to cross-compile from linux for windows? from what i found for msvc is a bit hard to do? do i need msvc target for alacritty? I'm just avoiding to install rust on windows here and just keep it in wsl, if there is no way to do the above i'll just install it on windows.

**Comment by kchibisov** [comment] 2020-04-26 15:06
>Is it possible to cross-compile from linux for windows? from what i found for msvc is a bit hard to do? do i need msvc target for alacritty? I'm just avoiding to install rust on windows here and just keep it in wsl, if there is no way to do the above i'll just install it on windows.

I know very little on cross compiling for windows, sorry, it should likely be under wine or something like that + you should have all required toolchains. It's not about just having rust-msvc, it's also about having all required system libs we're linking to on windows, so you should have windows env, which is why wine is required for such things. So I guess it's simpler to install toolchains right on windows and compile code on it. It's pretty simple from what I remember, you should just always add to system path on install(clang/rust). I'm not entirely sure if clang is really required here, but you can start by just installing rust toolchain and tring to build code with `cargo`.

**Comment by ChrisTsou** [comment] 2020-04-26 15:57
Yeah, i was trying to figure out how to compile, i was getting a linker error inside  wsl, which i had no idea what it is, do i did some searching, thought maybe installing llvm would fix it, then i had to figure how to install llvm XD .... which i did, still couldnt compile for msvc. So, i just installed rust for windows.
After  a while i managed to compile alacritty. compilation needed llvm for windows and visual studio build tools.

It works!
![Capture](https://user-images.githubusercontent.com/25465975/80312718-6a629300-87ef-11ea-9c78-a21a40820f4a.PNG)

But i still cant understand why fallback is needed. I know for sure fira code nerd font has that arrow symbol in it.

**Comment by kchibisov** [comment] 2020-04-26 16:04
Well, it doesn't have it then I guess.

**Comment by kchibisov** [comment] 2020-04-26 16:04
Anyway, the issue seems like solved.

**Comment by kchibisov** [comment] 2020-04-26 16:04
duplicate of #3127

**Closed by kchibisov** 2020-04-26 16:04 UTC
Labels: C - waiting on author, H - windows, S - font

**Comment by Southclaws** [comment] 2020-06-30 13:18
Still seeing this on 0.4.3

![image](https://user-images.githubusercontent.com/1636971/86130580-4156cb00-badc-11ea-985c-20f6da74a537.png)

Config:

```yml
font:
  normal:
    family: Fira Code
```

**Comment by chrisduerr** [comment] 2020-06-30 14:51
@Southclaws It should be fixed on master, not 0.4.3.
