### ISSUE TITLE
win10 error

### ISSUE THREAD

**Issue by zerols** [alacritty/alacritty#3605] opened 2020-04-18 09:14 UTC
i have intsall by scoop ，when i open it in cmder show:
>>> alacritty
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
thread panicked while processing panic. aborting.

**Comment by zerols** [comment] 2020-04-18 10:20
>>> alacritty.exe -vv
Created log file at "C:\Users\zero\AppData\Local\Temp\Alacritty-18364.log"
[2020-04-18 18:00:27.102421900] [INFO] Welcome to Alacritty
[2020-04-18 18:00:27.104315600] [INFO] No configuration file found
[2020-04-18 18:00:27.108315700] [DEBUG] Estimated DPR: 1.1458333333333333
[2020-04-18 18:00:27.108315700] [DEBUG] Estimated Cell Size: 9 x 19
[2020-04-18 18:00:27.108315700] [DEBUG] Estimated Dimensions: None
[2020-04-18 18:00:27.177549700] [INFO] Device pixel ratio: 1.1458333333333333 [2020-04-18 18:00:27.204511200] [INFO] Initializing glyph cache...
[2020-04-18 18:00:27.232771900] [INFO] ... finished initializing glyph cache in 0.0275415s
[2020-04-18 18:00:27.232771900] [INFO] Cell Size: 9 x 19
[2020-04-18 18:00:27.237078200] [INFO] Padding: 0 x 0
[2020-04-18 18:00:27.238093300] [INFO] Width: 1024, Height: 768
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
thread panicked while processing panic. aborting.
%APPDATA%\alacritty\alacritty.yml  
i found three file in appdate 
local locallow roaming which one should i creat alacritty.yml

**Comment by chrisduerr** [comment] 2020-04-18 14:35
Duplicate of https://github.com/alacritty/alacritty/issues/3590.

**Closed by chrisduerr** 2020-04-18 14:35 UTC
