### ISSUE TITLE
macOS DPI scaling incorrect

### ISSUE THREAD

**Issue by aergonaut** [alacritty/alacritty#1631] opened 2018-10-06 07:41 UTC
Which operating system does the issue occur on? **macOS High Sierra 10.13.6**

The DPI scaling seems to be locked to the scale of the built-in display when using `window.decorations` set to either `transparent` or `buttonless` on macOS.

I have a MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) running macOS High Sierra 10.13.6. When I choose either `transparent` or `buttonless`, it seems like Alacritty renders the terminal with the DPI scale of my MacBook's built-in display, even if I have the window on my external monitor.

![Screenshot showing Alacritty with transparent window decorations on external monitor](https://cl.ly/1544ea84465a/Screen%20Shot%202018-10-06%20at%2000.38.44.png)

**Comment by chrisduerr** [comment] 2018-10-06 12:33
Can you test if #1403 fixes this?

**Comment by aergonaut** [comment] 2018-10-07 01:17
@chrisduerr I compiled #1403, but I still see the same weird behavior with `transparent` and `buttonless`. The DPI scaling works great when in `full` mode, though!

**Comment by chrisduerr** [comment] 2018-10-07 17:35
Hmm that's interesting, maybe @sodiumjoe has an idea?

**Comment by sodiumjoe** [comment] 2018-10-07 20:01
There are some previous discussions [here](https://github.com/jwilm/alacritty/pull/1241#issuecomment-382753938) and [here](https://github.com/jwilm/alacritty/pull/947#issuecomment-360908642).

I was experiencing this too at first, and I did some investigation at the time, but never got to the bottom of it. Since then, I think one of the `winit` upgrades fixed it for me, and I haven't been able to reproduce. I use `buttonless` daily on a build from #1403 with a non-hidpi external monitor.

I think it's good that we have a tracking issue for it though.

@aergonaut some diagnostic questions:
1. Are you starting the window on the laptop display or the external display? Does it affect anything if you switch?
2. Does resizing the window do anything?
3. is the external monitor hidpi?

It might be worth doing a `cargo clean`, and making sure you're building from #1403 fresh.

**Comment by dannydulai** [comment] 2018-12-05 17:54
`full` and `none` work fine. `transparent` and `buttonless` do not. Same result as in the above screenshot.

I git pulled master just now, `cargo clean && cargo build --release` -- no luck :-(

**Comment by discreet** [comment] 2019-01-10 01:57
In seeing this same issue but `full` and `bottonless` don't seem to fix the issue for me. I'm running a compiled version of v0.2.5 on Mac OS X High Sierra.

**Comment by chrisduerr** [comment] 2019-09-17 14:45
Can someone check if #2438 fixes this issue? I can't reproduce it myself, but this PR might help.

**Comment by nixpulvis** [comment] 2019-09-19 21:38
FWIW, I tried to replicate this on a mac I have access to ATM, and was unable. It's running an older version of macOS, 10.13.6. I tried all 4 options for the `window.decorations` configuration.

@chrisduerr this was also true for #2438.

**Comment by noritada** [comment] 2020-10-28 14:30
I saw this issue on High Sierra (10.13.6) (#4327), but after upgrading my macOS to Mojave (10.14.6), I got a correct display with the same binary as what I used to see incorrect display on 10.13.6. So, confirmed that this is only an issue on 10.13, which is now 3 years old. Thanks!

**Comment by chrisduerr** [comment] 2020-10-28 20:20
Closing this issue with the recommendation for people to update their systems if they want things to work correctly.

**Closed by chrisduerr** 2020-10-28 20:20 UTC
Labels: A - deps, A - needs repro, H - macos, P - high, S - winit/glutin
