### ISSUE TITLE
[Feature request] Special handling of Block Elements (U+2580 - U+259F)

### ISSUE THREAD

**Issue by oxalica** [alacritty/alacritty#5485] opened 2021-09-11 11:14 UTC
### Intro

Block element characters are used for terminal fill and shading. 
https://unicode-table.com/en/blocks/block-elements/

The most common characters are:
- `█` (U+2588) Full Block
- `▄` (U+2584) Lower Half Block
- `▀` (U+2580) Upper Half Block
- `▗▘▙▚▛▜▝▞▟` (U+2596 - U+259F) Terminal graphic characters

Currently, they simply use the font's glygh for rendering, which cannot accurately fill a whole cell (or some borders) and instead leave a thin 0.5-1px border.
The following code *should* print a 2x2 full block, but currently it doesn't. There's a thin gap between adjacent cell (both between columns and rows)
`printf '██\n██\n'`

![blocks](https://user-images.githubusercontent.com/14816024/132945334-34e6f28e-40b7-47ea-9037-29119dbf7663.png)

I tried all installed FreeType fonts including `Noto Sans Mono`, `Free Mono` and `Sarasa Mono` but none of them work. So I think it's not an issue of individual fonts, but some limitations of FreeType itself.

### Proposal 

Specially handle these block-like characters to make them *accurately fully* fill cell (or borders). There are also many terminals did so, including:
- GNOME vte: https://github.com/GNOME/vte/commit/154abade902850afb44115cccf8fcac51fc082f0
- Kitty: https://github.com/kovidgoyal/kitty/commit/e95c789d4bf6e52587b39ff10f419dd4442e92dd
- Konsole: Enabled special treatment by default. Can be disabled by a setting `Use line characters contained in font` in `Appearance` (then it behaves the same as current `alacritty`).

### Affected programs

Programs using these characters to print ASCII art, graphics, or indicators. Some users also use them in shell prompts.

`neofetch`:
![nixos](https://user-images.githubusercontent.com/14816024/132945876-b2c9a706-1b21-4144-9531-1d60762d6eb5.png)

### System

OS: Linux
Version: Current master cf35a2019162c6055e4a4c152976a424ba10869d
Linux: X11, KDE

**Comment by kchibisov** [comment] 2021-09-11 12:15
I'm aware of this, and I'd also prefer special handling of those and other line drawing chars. However you should provide a way to use font line drawing glyphs instead of builtin ones.

**Comment by chrisduerr** [comment] 2021-09-11 13:48
> I'm aware of this, and I'd also prefer special handling of those and other line drawing chars. However you should provide a way to use font line drawing glyphs instead of builtin ones.

Since it has been long confirmed that custom handling is the only way to solve these issues reliably, I'm not completely against custom handling these anymore. I still hate it, but it makes sense. An option to disable this should definitely be present though.

**Comment by tiosgz** [comment] 2021-10-31 08:14
For comparison, [foot](https://codeberg.org/dnkl/foot/src/commit/9a04c741a094b97f4502d4c098fca8c19cb3647b/terminal.h#L343-L356) handles these ranges:

- 2500..259f (box drawing)
- 2800..28ff (braille)
- 1fb00..1fb9b (legacy computing)

**Comment by christianparpart** [comment] 2021-12-15 06:11
> > I'm aware of this, and I'd also prefer special handling of those and other line drawing chars. However you should provide a way to use font line drawing glyphs instead of builtin ones.
> 
> Since it has been long confirmed that custom handling is the only way to solve these issues reliably, I'm not completely against custom handling these anymore. I still hate it, but it makes sense. An option to disable this should definitely be present though.

Why do you hate it, @chrisduerr ?

**Comment by chrisduerr** [comment] 2021-12-15 09:40
Because it completely goes against font configuration to ignore the font **explicitly chosen** by the user in favor of shipping your own shitty bitmap font (or whatever it might be). It's completely backwards.

**Comment by christianparpart** [comment] 2021-12-15 10:12
> Because it completely goes against font configuration to ignore the font **explicitly chosen** by the user 

Sure, just provide a boolean config that toggles this behavior. Also, mind, all major TEs I tested (Kitty, Konsole, Gnome-Terminal, iTerm2) are in fact even having that feature and even enabled by d fault. So my point is, the user might even have expect this behavior. Otherwise, click the toggle. :)

> in favor of shipping your own shitty bitmap font (or whatever it might be).

No need to get personal, @chrisduerr. I was expecting some respectful communication here. ;)

>  It's completely backwards.

I hoped I have made my point clear in the top that this is not backwards. 
But I agree, this would be yet another if-condition within the rendering hot path that may potentially be a threat over performance. I hope though that would be neglectable.

**Comment by chrisduerr** [comment] 2021-12-15 12:00
> Sure, just provide a boolean config that toggles this behavior. Also, mind, all major TEs I tested (Kitty, Konsole, Gnome-Terminal, iTerm2) are in fact even having that feature and even enabled by d fault. So my point is, the user might even have expect this behavior. Otherwise, click the toggle. :)

A boolean option toggling between two broken behaviors doesn't make any of them less broken.

> No need to get personal, @chrisduerr. I was expecting some respectful communication here. ;)

I'm not, I was speaking in general. Alacritty will do the same in the future and it will still by our own shitty bitmap font.

> I hoped I have made my point clear in the top that this is not backwards.

You have not. This is completely backwards and I doubt anyone would be able to change my mind on that. I'd say it would be pretty much objectively superior if terminals could use the font's glyphs without rendering artifacts.

> But I agree, this would be yet another if-condition within the rendering hot path that may potentially be a threat over performance. I hope though that would be neglectable.

This shouldn't have any impact on performance really, those glyphs can be cached at startup and don't ever need to be updated unless the font size is changed.

**Comment by christianparpart** [comment] 2021-12-16 12:24
> A boolean option toggling between two broken behaviors doesn't make any of them less broken.

It's the font providing not so optimal block elements. One could say that this is broken indeed. At least as much as fixed size grid systems are concerned.
But why the other system, making sure block elements are rendered as specified in the terminal is broken you have to tell me. I do not understand.
But even so, let's assume both **are** broken, then having a toggle isn't that bad after all, don't you think so? The user has the choice to decide what looks best to him, which, by definition should be the latter, and if one opts to get the former, just do so. 

In my opinion, that's usability. :)

> and it will still by our own shitty bitmap font

Okay, this is your words then. Maybe you need to help me understand what you mean by "by our own shitty bitmap font"? What's so shitty about being pixel-perfect?
Are all other terminal emulators doing it wrong then?



> >  I hoped I have made my point clear in the top that this is not backwards.

> You have not. 

lol. okay. Let's call it language barrier then. ;)

> This is completely backwards

?

> and I doubt anyone would be able to change my mind on that. I'd say it would be pretty much objectively superior if terminals could use the font's glyphs without rendering artifacts.

Okay, granted. No problem with that, but then please close this and *all* the tickets related to that. This at least would make it very clear to the users that you simply don't want that. And nobody will be waiting hopelessly. Probably the same for the Sixel discussion then. 

Cheers.

**Comment by chrisduerr** [comment] 2021-12-16 13:27
> But even so, let's assume both are broken, then having a toggle isn't that bad after all, don't you think so? The user has the choice to decide what looks best to him, which, by definition should be the latter, and if one opts to get the former, just do so.

Well it is *that* bad, because it's still broken. It might still be the best choice, but that doesn't make it **good**. That's why this issue is still open and planned to be implemented. It sucks, but it's still the best choice available.

**Comment by christianparpart** [comment] 2021-12-16 14:17
i lag definition of broken in this context. I'd really like that to be clarified. Okay, nice to keep it open, really, but how do you think this can be implemented in an "unbroken" way then?

**Comment by bluz71** [comment] 2022-01-05 05:25
Just stumbled my way here (by accident), and boy am I glad I did.

Thank you @kchibisov, this will be an absolutely brilliant enhancement.

**Closed** 2022-01-05 21:45 UTC
Labels: enhancement, help wanted, S - font

**Comment by doums** [comment] 2022-01-28 17:13
https://github.com/alacritty/alacritty/issues/5809#issuecomment-1024424190
