### ISSUE TITLE
Unicode support in tmux

### ISSUE THREAD

**Issue by benknoble** [alacritty/alacritty#3358] opened 2020-02-19 14:43 UTC
My prompt string uses some unicode characters (`Knoble @ macaroon ∈ ~ 
+λ `). In Alacritty, these render just fine (assuming the font supports them).

However, in `tmux` in Alacritty, the render as `_`—vim and others know that these are the correct characters (as a quick `ga` confirms), but they render completely wrong.

Not sure if this relates to #306 

### System

OS: macOS
Version: `alacritty --version` output
```
alacritty 0.4.1 (4d9253b)
```

**Comment by kchibisov** [comment] 2020-02-19 15:05
it seems like a dup of #2837 , so you end up with a bad locale in tmux.

**Comment by benknoble** [comment] 2020-02-19 16:01
@kchibisov yeah, it's definitely the locale. Unfortunate that macOS sets this well in Terminal.app and Alacritty doesn't, but I've set it manually for now

**Comment by kchibisov** [comment] 2020-02-19 16:05
Closing as duplicate of #2566

**Closed by kchibisov** 2020-02-19 16:05 UTC
