### ISSUE TITLE
Alt modifier not working on MacOS + bépo (french dvorak) keyboard mapping

### ISSUE THREAD

**Issue by paulfariello** [alacritty/alacritty#6596] opened 2022-12-30 11:58 UTC
alt modifier not working on MacOS + bépo keyboard mapping.

For exemple, when using another term (iTerm) alt+y gives `{` but it doesn’t output anything on alacritty.
Logs given bellow.

Bépo is installed with the following bundle:
https://download.tuxfamily.org/dvorak/macosx/fr-dvorak-bepo-macosx-1.1rc2.dmg

### System

OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)

### Logs

Font/Terminal size:
```
[0.000007055s] [INFO ] [alacritty] Welcome to Alacritty
[0.000377424s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0b)
[0.000673980s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.002368130s] [DEBUG] [alacritty] Using environment locale: fr_FR.UTF-8
[0.050731105s] [DEBUG] [alacritty] Loading "Menlo" font
[0.265835985s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.265895583s] [DEBUG] [alacritty] Estimated window size: None
[0.265918811s] [DEBUG] [alacritty] Estimated cell size: 13 x 26
[0.329068764s] [INFO ] [alacritty] Running on Intel(R) Iris(TM) Plus Graphics 650
[0.329118583s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.334012938s] [INFO ] [alacritty] Display scale factor: 2
[0.334070815s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.354260746s] [INFO ] [alacritty] Cell size: 13 x 26
[0.354332975s] [INFO ] [alacritty] Padding: 0 x 0
[0.354351905s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.354476353s] [INFO ] [alacritty] PTY dimensions: 46 x 123
[0.359006417s] [INFO ] [alacritty] Initialisation complete
[0.418559083s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.418906524s] [INFO ] [alacritty] Padding: 0 x 0
[0.418940819s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.785647882s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1'],['~'],] at line 963
[4.370629227s] [INFO ] [alacritty] Goodbye
```
Keyboard and bindings: when hitting left alt + y
```
[2.452486386s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140683600084288)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 61, state: Pressed, virtual_keycode: Some(RAlt), modifiers: ALT }, is_synthetic: false } }
[2.820239811s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140683600084288)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 7, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
[2.880899757s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140683600084288)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 7, state: Released, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
[2.957537555s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(140683600084288)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 61, state: Released, virtual_keycode: Some(RAlt), modifiers: (empty) }, is_synthetic: false } }
```

I’m available for more tests on my setup but currently have no idea where to start.

**Comment by chrisduerr** [comment] 2022-12-30 12:07
Duplicate of https://github.com/alacritty/alacritty/issues/62.

**Closed by chrisduerr** 2022-12-30 12:07 UTC
