### ISSUE TITLE
Need meta modifier key setting

### ISSUE THREAD

**Issue by aparkerlue** [alacritty/alacritty#2593] opened 2019-06-25 19:19 UTC
Is there a way to configure which key functions as the meta modifier?

(Popular choices include alt, meta, hyper, and super.)

`alacritty.yml` contains a variable called `alt_send_esc`, which when set to `true`, makes `alt-b` and `alt-f` move the cursor backward and forward by one word. Many [i3](https://i3wm.org/) users who use alt as their i3 modifier key will want to use super as their meta modifier in the terminal.

As an example, URxvt has a setting for the meta modifier. From urxvt(1):

```
       -mod modifier
           Override detection of Meta modifier with specified key: alt, meta,
           hyper, super, mod1, mod2, mod3, mod4, mod5; resource modifier.
```

One could, for example, set Super as the Meta modifier in URxvt by adding the following line to `~/.Xresources`:

```
URxvt.modifier: super
```

### Platform questions

Which operating system does the issue occur on?

Linux

If on linux, are you using X11 or Wayland?

X11

**Comment by chrisduerr** [comment] 2019-06-25 20:40
Usually I'd recommend using super as the i3 mod, since that's the OS-level escape modifier usually. The terminal isn't aware of this key and that usually cause the least amount of trouble.

As far as I'm aware, there's not really any concept as generic 'mod' the way there is in i3. The only option would be to report super as alt or control, which I'd assume is what URxvt is doing (reporting super as alt specifically).

**Comment by nixpulvis** [comment] 2019-07-15 20:28
I too use "super" (aka `i3`'s `Mod4`) as my WM meta key. This works pretty well, if only Apple and other keyboards would agree with where to put these keys!

However, I'm not opposed to supporting custom modifier key remapping in Alacritty.

**Comment by danikron** [comment] 2021-02-23 13:31
This is the one missing feature that keeps me from switching to Alacritty from urxvt right now. For reasons that probably only make sense to me I move my alt key to caps lock and bind the actual alt key to mod3, but I still want to use it normally in the terminal. In some cases I could solve this by rebinding shortcuts, but for example in vim this can be a problem. Better if mod3 can just be seen as the meta key in the entire terminal.

**Comment by chrisduerr** [comment] 2021-04-13 09:27
Duplicate of #62.

**Closed by chrisduerr** 2021-04-13 09:27 UTC
Labels: enhancement
