### ISSUE TITLE
macos: alacritty lag when change input source to my language

### ISSUE THREAD

**Issue by babygau** [alacritty/alacritty#4204] opened 2020-09-06 03:43 UTC
### System

OS: macOS 10.15.6
Version: alacritty 0.5.0 (a6681e3)

### Logs
[2020-09-06 13:22:33.816945000] [DEBUG] Using environment locale: en_AU.UTF-8
[2020-09-06 13:22:33.817109000] [INFO] Welcome to Alacritty
[2020-09-06 13:22:33.817132000] [INFO] Configuration loaded from "/Users/babygau/.config/alacritty/alacritty.yml"
[2020-09-06 13:22:33.852556000] [DEBUG] Estimated DPR: 2
[2020-09-06 13:22:33.852617000] [DEBUG] Estimated Cell Size: 25 x 40
[2020-09-06 13:22:33.852641000] [DEBUG] Estimated Dimensions: None
[2020-09-06 13:22:33.889671000] [INFO] Device pixel ratio: 2
[2020-09-06 13:22:33.892647000] [INFO] Initializing glyph cache...
[2020-09-06 13:22:33.930899000] [INFO] ... finished initializing glyph cache in 0.038158037s
[2020-09-06 13:22:33.930981000] [INFO] Cell Size: 25 x 40
[2020-09-06 13:22:33.931020000] [INFO] Padding: 50 x 60
[2020-09-06 13:22:33.931059000] [INFO] Width: 1600, Height: 1200
[2020-09-06 13:22:33.931996000] [INFO] PTY dimensions: Line(27) x Column(60)
[2020-09-06 13:22:33.934806000] [INFO] Initialisation complete
[2020-09-06 13:22:34.091359000] [DEBUG] New num_cols is 97 and num_lines is 32
[2020-09-06 13:22:34.092692000] [INFO] Width: 2530, Height: 1388
[2020-09-06 13:23:05.034541000] [INFO] Goodbye

### Description

alacritty working ok with _us_ input source. when i changed to _vietnamese_ input source, alacritty was laggy and slow so that i couldn't type. this behaviour doesn't happen in _iterm2_. 
![alacritty](https://user-images.githubusercontent.com/1514823/92317674-f52d8700-f046-11ea-97bd-b03a83d4450a.gif)

**Comment by chrisduerr** [comment] 2020-09-06 13:58
I don't see anything lagging more in the gif? Are you maybe talking about #1613?

**Comment by kchibisov** [comment] 2020-09-06 14:04
I feel like it lost focus when you've switched layout for whatever reason? Is it correct that the hollow block cursor appeared right when you do a layout switch?

**Comment by babygau** [comment] 2020-09-06 16:02
if you look carefully, why i typed using my language, words were rendered _character by character_ in **iterm2** (the left side). in contrast, in **alacritty** (the right side), words were rendered _word by word_. i don't even know if words are type correctly until i hit space bar and word showed up. moreover, it's really laggy. the demo only showed a few words, it's simple not feasible to type a whole sentence cause of lag.

**Comment by kchibisov** [comment] 2020-09-06 16:09
It doesn't lag, it's a duplicate of #1613 then. You don't have IME window, so that's why it's laggy for you since IME editing is done behind the scenes, and you get a word when you 'confirm' the change.

**Closed by kchibisov** 2020-09-06 16:09 UTC
Labels: H - macos
