### ISSUE TITLE
alt-keys don't always generate the right keycode when xmodmap is used

### ISSUE THREAD

**Issue by doy** [alacritty/alacritty#1225] opened 2018-04-03 04:12 UTC
Which operating system does the issue occur on?
linux

If on linux, are you using X11 or Wayland?
x11

in the normal case, both alt+num and alt+shift+num work properly (they send an escape character before inserting the character itself). i have a .Xmodmap which swaps the shifted state of the number row (so for instance `keycode 10 = exclam 1`), though, and with it, alt+shift+1 still sends `\e1` but alt+1 sends just `!`. alt+2 does send `\e@` though, and it looks like this is because the glutin library contains a keycode for `At`, while it doesn't for any of the other shifted num-row characters - the key event that is being processed contains `Some(At)` in this case, while it contains `None` as the `VirtualKeyCode` for the other cases. i'm not sure if this is a thing that would need to be fixed in glutin or if it can be worked around in alacritty directly, but it'd be nice if it could be made to work (all of the other terminals i've tried have handled it correctly).

**Comment by doy** [comment] 2018-04-04 03:48
looks related to #55

**Comment by chrisduerr** [comment] 2020-12-29 19:06
Closing as duplicate of #55.

**Closed by chrisduerr** 2020-12-29 19:06 UTC
