### ISSUE TITLE
Country flag emojis are not displayed correctly

### ISSUE THREAD

**Issue by dashezup** [alacritty/alacritty#4025] opened 2020-07-24 11:42 UTC
### System

OS: Void Linux
Version: alacritty 0.4.3
Linux/BSD: Wayland, Swaywm
Font: Fira Code, [Apple Color Emoji](https://github.com/samuelngs/apple-emoji-linux)

### fontconfig

~/.config/fontconfig/fonts.conf

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>foobar</family>
    <prefer>
      <family>Fira Code</family>
      <family>Apple Color Emoji</family>
     </prefer>
  </alias>
</fontconfig>
```

I have set font family to foobar in alacritty.yml, most of other emojis are displayed correctly except country flags emoji, I have also tried with Liberation Mono / DejaVu Sans + Noto Color Emoji, both can't display country flag character correctly.

Seems country flags has two characters, I guess this could be related, some flags such like Crossed Flags are rendered correctly.

List of flags emoji on [Emojipedia](https://emojipedia.org/flags/)

### Screenshots

![image_2020-07-24_11-13-04](https://user-images.githubusercontent.com/67376103/88386413-da0cfd80-cd9f-11ea-8e55-b67315cc3d93.png)

I have also tried alacritty on macOS Catalina, installed by using brew, got similar result.

![tg_image_929287869](https://user-images.githubusercontent.com/67376103/88386417-db3e2a80-cd9f-11ea-9123-c8e240119e14.jpeg)

**Comment by chrisduerr** [comment] 2020-07-24 11:44
This is basically a duplicate of https://github.com/alacritty/alacritty/issues/50. Though I think the interest for grapheme clusters is even lower than that for ligatures.

**Closed by chrisduerr** 2020-07-24 11:44 UTC
