### ISSUE TITLE
CTRL+L could be triggered unexpectly on macOS

### ISSUE THREAD

**Issue by eyeplum** [alacritty/alacritty#3297] opened 2020-02-06 03:19 UTC
### System

OS: macOS 10.15.2 (bug also observed on macOS 10.13)
Version: alacritty 0.4.1 (4d9253b)

### Logs

Keyboard and bindings: [events.log](https://github.com/alacritty/alacritty/files/4163029/events.log)

#### Reproduction Steps

0. Make sure there are more than one active desktop spaces (e.g. by making a window full screen before launching Alacritty)
1. Launch Alacritty
2. Use `CTRL` + `Right` to switch to the space on the right
3. Use `CTRL` + `Left` to switch back to the desktop space (where Alacritty is running in)
4. Press `L`

#### Expected

- Alacritty receives input of character `l`

#### Actual

- Alacritty clears the screen as if `CTRL` + `L` was pressed
- Also, inputs of character `l` are ignored

#### Notes

- `git bisect` shows the issue was first introduced by commit 1cfb0740bc530da3162292bbf682a234240f26a3

**Comment by cole-h** [comment] 2020-02-06 03:23
Dupe of https://github.com/alacritty/alacritty/issues/3188 AFAICT

**Closed** 2020-02-06 03:25 UTC
Labels: F - duplicate
