### ISSUE TITLE
In fullscreen mode cannot access menu bar

### ISSUE THREAD

**Issue by rustiever** [alacritty/alacritty#4318] opened 2020-10-18 10:10 UTC
### System
OS: macOS
Version: alacritty 0.5.0 (a6681e3)

in fullscreen mode when i move trackpad/mouse to top of the screen i cannot access the menu bar

**Comment by chrisduerr** [comment] 2020-10-18 15:45
Duplicate of https://github.com/alacritty/alacritty/issues/4105.

**Closed by chrisduerr** 2020-10-18 15:45 UTC
