### ISSUE TITLE
Big performance hit while using trucolor in neovim/vim

### ISSUE THREAD

**Issue by spamwax** [alacritty/alacritty#2136] opened 2019-02-28 07:06 UTC
Which operating system does the issue occur on?
macOS 10.13.6

Hardware: MacBook Pro (15-inch, Early 2011)
Graphics card: Intel HD Graphics 3000 512 MB graphics with built-in display. The laptop has a dedicated GPU which I believe only kicks in when an external device is connected, I may be wrong on this.

Alacritty built in release mode from `8d5e122`
neovim  v0.4.0-50-g5a11e5535
vim 8.1

Enabling a truecolor scheme in nvim/vim causes serious lag/performance.
I didn't have this issue previously, however since I use nightly releases of both Alacritty and neovim I can't easily pinpoint when this started happening.

Even just trying to move the cursor around in `neovim` is slow and I have to wait close to a second to see the cursor move!!!

I also tried using `neovim` in `iTerm` and the performance & key-press responsive was better than Alacritty.

(I am using [gruvbox](https://github.com/morhetz/gruvbox) as a truecolor in nvim/vim)

Please let me know if I can provide more information.

**Comment by chrisduerr** [comment] 2019-02-28 09:56
Would be good to have information on when this regression was introduced when it previously worked.

**Comment by spamwax** [comment] 2019-02-28 22:25
I believe I found the culprit.
After checking out multiple tag versions of Alacritty and building them, I didn't run into any performance issue.
However I was launching Alacritty directly from `target/release/alacritty` rather using the macOS bundle (`Alacritty.app`) that make file creates. 
And as I guessed launching Alacritty from the `Alacritty.app` bundle causes the issue with truecolor in nvim/vim

So I looked at the `Info.plist` file in the bundle and changed `NSHighResolutionCapable` from `true` to `false`, and that fixed the performance issue when Alacritty is started from bundle. 
I don't know what exactly `NSHighResolutionCapable` does and how its value affects the performance of the Alacritty, and how changing that setting from `true` to `false` will affect other Mac users with different resolution and retinal displays.

So I guess for now the solution for me would be to manually adjust that value in `Info.plist` file

**Comment by spamwax** [comment] 2019-02-28 22:33
Since the `Info.plist` has had that setting for a long time now and I didn't have issues with performance, I still believe at some point changes made to Alacritty caused the issue. I will investigate further and report back.

**Comment by chrisduerr** [comment] 2019-03-01 00:17
From what I can see `NSHighResolutionCapable` should just indicate support for high resolution displays, which Alacritty does indeed support.

It's possible that this just activates the dedicated GPU though, so I'd test explicitly enabling it for Alacritty first.

**Comment by spamwax** [comment] 2019-03-01 01:26
> It's possible that this just activates the dedicated GPU though, so I'd test explicitly enabling it for Alacritty first.

not sure what exactly you mean by this? enabling it causes the performance hit and I am testing on builtin monitor. I'll try to compile different version while this is enabled and see which one starts the issue

**Comment by threkk** [comment] 2019-03-17 23:02
I am having a similar issue: since the update to the latest version, neovim has become unusable due to the lag. I am running it on a MacBook Pro (13-inch, Late 2011) with OS X 10.13.6

I tried to change the `NSHighResolutionCapable` but it did not solve it for me.

**Comment by spamwax** [comment] 2019-03-18 00:30
does running alacritty binary directly solve the issue for you?

**Comment by threkk** [comment] 2019-03-18 01:26
It seems that running the binary solves the issue. I have currently the version 0.2.0 and 0.2.9 running simultaneously. Typing in neovim feels similar.

**Comment by chrisduerr** [comment] 2019-03-18 16:20
Does `253f1ce2018f1599259f1459133497002fdcce7d` fix these issues? That was before the last major glutin update and I'm curious if downgrading to that fixes things.

**Comment by threkk** [comment] 2019-03-19 09:06
Hi, I need to compile that concrete version and currently I am not able to do it. I will come back with results tonight.

**Comment by threkk** [comment] 2019-03-19 23:46
The app version of the commit `253f1ce2018f1599259f1459133497002fdcce7d` works well for me 👍

**Comment by chrisduerr** [comment] 2019-03-20 19:37
Does this also get fixed when deleting the following line?

https://github.com/jwilm/alacritty/blob/master/src/window.rs#L124

**Comment by spamwax** [comment] 2019-03-22 21:01
> Does `253f1ce2018f1599259f1459133497002fdcce7d` fix these issues?

@chrisduerr Is that a commit in `glutin` I can't find that in alacritty's git history?

**Comment by chrisduerr** [comment] 2019-03-22 23:51
It's in Alacritty's history. Though trying the change I've suggested (see link) might also help.

**Comment by spamwax** [comment] 2019-03-23 02:47
I'll try that link but this is very strange:

```
git show 253f1ce2018f1599259f1459133497002fdcce7d
fatal: bad object 253f1ce2018f1599259f1459133497002fdcce7d
```

**Comment by spamwax** [comment] 2019-03-23 03:04
removing that lines fixes the issue!

**Comment by chrisduerr** [comment] 2019-03-23 11:31
> not sure what exactly you mean by this? enabling it causes the performance hit and I am testing on builtin monitor. I'll try to compile different version while this is enabled and see which one starts the issue

You've said that enabling the dedicated GPU creates this issue, but the setting should be there to disable the high performance graphics by default.

Does the latest master perform the same way both with dedicated GPU enabled and disabled?

**Comment by RobertAudi** [comment] 2020-01-14 12:15
@chrisduerr After a quick google search I stumble upon WeAreROLI/JUCE#483.

I don't know if this could be a similar problem though – my uneducated guess says it looks similar 🤔

**Comment by chrisduerr** [comment] 2020-01-15 20:15
@RobertAudi Thanks for bumping this issue, I'm not entirely sure why it has been stale for so long to be honest.

It seems like a trivial change to remove the `with_hardware_acceleration(None)` option. Though I'd imagine it could have some negative side effects.

@mkeeler if you're still around, could you explain your reasoning behind adding this? Did you have any machines that did not support hardware acceleration which required this setting?

On macOS the option `None` is equal to `Some(false)`, which will lead to `NSOpenGLPFAAccelerated` not being set. Based on my understanding of the documentation on this however, it seems like even without this option the accelerated renderer should be preferred.

So I suppose this must have been why I asked the question if it performs equally with dedicated GPU enabled and disabled and left it there, which unfortunately did not get any answer.

@RobertAudi Can you actually reproduce the issue and does the suggested change fix it for you? If so I'd be curious to do some more debugging to get to the bottom of this. Otherwise it seems like the evidence suggests that this should be fixable through system settings.

**Comment by mkeeler** [comment] 2020-01-15 20:32
@chrisduerr When the value is not `None` or `Some(false)`, `alacritty` gets run with hardware acceleration required and on a dual gpu mac this will cause the discrete GPU to be enabled even when not plugged in.

Essentially setting this to `Some(true)` would disable automatic graphics switching in macOS.

**Comment by chrisduerr** [comment] 2020-01-15 20:36
> @chrisduerr When the value is not None or Some(false), alacritty gets run with hardware acceleration required and on a dual gpu mac this will cause the discrete GPU to be enabled **even when not plugged in**.

By this you mean that it would be enabled even if the laptop is running on battery? Or if the GPU is not plugged in (which I don't think is possible on a dual gpu mac?)?

Since Alacritty's goal is performance, I'm not sure how much sense it makes to run without graphics acceleration. I feel like with the OpenGL renderer, the iGPU might struggle?

However this does sound like my previous assumptions are correct and it is possible to force Alacritty to always run on the dedicated GPU using the system configuration?

**Comment by mkeeler** [comment] 2020-01-15 20:39
Thats right. Even when on battery power, running alacritty alone would cause macOS to power up the dedicated GPU and use it.

Also, if there are other apps running that would cause the dedicated GPU to be in use, are not running on battery power or you have disabled automatic graphics switching all together, then alacritty will be using the dedicated gpu.

**Comment by chrisduerr** [comment] 2020-01-15 20:42
> Thats right. Even when on battery power, running alacritty alone would cause macOS to power up the dedicated GPU and use it.

Fair enough, that makes sense and mostly falls in line with what I had guessed so far.

Can you confirm or deny if there's an option to override this on macOS? If there's not, I feel like it would be difficult for Alacritty to argue that we shouldn't choose whatever gives better performance.

**Comment by mkeeler** [comment] 2020-01-15 20:57
You can disable automatic graphics switching: http://osxdaily.com/2017/01/08/disable-gpu-switching-macbook-pro/

This will **always** use the dedicated GPU and will eat through your battery insanely quick regardless of whether you are using alacritty at the time.

IMO if you really want the discrete GPU on battery power then you should disable that setting. Realistically you cannot use your system for more than an hour or so before you will need to go plug in.

The original issue that we fixed was: https://github.com/alacritty/alacritty/issues/210

FWIW I use alacritty on battery power often with the integrated GPU (Intel HD Graphics 630 1536 MB) and the performance does not change in any noticeable way for me.

**Comment by chrisduerr** [comment] 2020-01-15 21:10
> You can disable automatic graphics switching: http://osxdaily.com/2017/01/08/disable-gpu-switching-macbook-pro/

Thanks, that's all I wanted to know. So it seems like there's absolutely no need for us to force this to be enabled, since users can easily opt-in through their settings.

I don't see any issues on my work macbook either, even inside of vim (which I use for almost everything). However that's quite a modern one, so it probably is a bit different.

I'll probably play around with things a bit myself, but as far as I can tell, Alacritty is behaving the way it should and potential performance issues can be resolved by forcing Alacritty to use the dedicated gpu.

**Closed by chrisduerr** 2020-01-15 21:10 UTC
Labels: B - performance, C - waiting on author, H - macos
