### ISSUE TITLE
alacritty sometimes doesn't react to input until the next input event

### ISSUE THREAD

**Issue by magicgoose** [alacritty/alacritty#5116] opened 2021-05-13 08:20 UTC
alacritty sometimes doesn't react to input (simple things like typing a letter, deleting a letter, or moving cursor).
If I make another input, then the previous input is also processed and it immediately catches up. If I wait, it may not refresh the image on screen indefinitely.

It happens approximately with every Nth keypress (3 < N < 25).

Interesting observation: this problem doesn't reproduce if I launch alacritty with option `--print-events` from another terminal (and don't redirect the output to a file). But this option doesn't change anything if I launch alacritty from a .desktop entry. Probably the action of printing something to a real terminal triggers the necessary redraw.

If I login using Wayland instead of X11 (no other changes to anything), the bug also doesn't reproduce. Unfortunately Wayland breaks a whole lot of other stuff currently, so it's not an easy workaround.

I would think that it's not an alacritty bug, but I used a lot of software on this system, and only alacritty has this problem.

### System

OS: Linux
Version: alacritty 0.7.2 (5ac8060b)
X11, GNOME 40.0.0
GPU: AMD Radeon RX 5xx series, using free driver (amdgpu)

### Logs

Result of running `alacritty --print-events > ~/Downloads/alacritty_print_events.txt 2>&1` and reproducing the problem twice by repeatedly typing a letter:
[alacritty_print_events.txt](https://github.com/alacritty/alacritty/files/6471369/alacritty_print_events.txt)
Note: if I don't redirect the output to file, but simply run `alacritty --print-events` from another terminal, then the bug doesn't reproduce.

**Comment by chrisduerr** [comment] 2021-05-13 14:32
> I would think that it's not an alacritty bug, but I used a lot of software on this system, and only alacritty has this problem.

Sounds almost like an issue with GPU driver.

Has this always been a problem, or is this a regression? Can you maybe try the latest master?

**Comment by magicgoose** [comment] 2021-05-13 14:40
> > I would think that it's not an alacritty bug, but I used a lot of software on this system, and only alacritty has this problem.
> 
> Sounds almost like an issue with GPU driver.
> 
> Has this always been a problem, or is this a regression? Can you maybe try the latest master?

I only recently tried alacritty for the first time ever, so I don't know.
I'll try latest master soon when I have a moment.

**Comment by magicgoose** [comment] 2021-05-13 17:14
Checked on alacritty 0.9.0-dev (6d8db6b9) (installed using [AUR](https://aur.archlinux.org/packages/alacritty-git/)). No difference, same problem.

**Comment by chrisduerr** [comment] 2021-05-13 17:15
Do you have different hardware running a similar system you could verify this behavior on?

**Comment by magicgoose** [comment] 2021-05-13 17:18
> Do you have different hardware running a similar system you could verify this behavior on?

Unfortunately no. Besides this PC, I only have access to some macbooks, and installing Linux on them would be a big hassle...

**Comment by magicgoose** [comment] 2021-05-13 17:20
I can however try testing different distros, and/or proprietary AMD GPU driver, do you think that could possibly help?

**Comment by chrisduerr** [comment] 2021-05-13 17:21
> I can however try testing different distros, and/or proprietary AMD GPU driver, do you think that could possibly help?

Yeah, I've been considering that. I think your best choice would be to test the proprietary AMD GPU driver. Including the OpenGL one though, because chances are if there's an issue it's in the OpenGL driver (mesa).

**Comment by magicgoose** [comment] 2021-05-13 19:16
Did some more testing:
1. proprietary OpenGL implementation (https://aur.archlinux.org/packages/amdgpu-pro-libgl/) doesn't make any difference
2. I also noticed that this problem reproduces only on 240 Hz refresh rate. (more precisely, it's reported as 239.76 Hz.) If I set it to anything lower than that (the next highest available is 144 Hz), the bug no longer reproduces.

So, it seems to happen only on X11 and 240Hz.
Maybe it should be reported as X11 bug, do you think it's worth it? Also can you think of any possible workarounds on alacritty side? (btw I know a little Rust, maybe I could try implementing&testing some ideas, I just don't know where to start)

**Comment by chrisduerr** [comment] 2021-05-13 19:26
I'm not aware of any parts of Alacritty that might cause such behavior.

**Comment by klauer** [comment] 2021-06-02 17:14
Though not as frequent as the issue reporter, I run into this at least a few times a day with alacritty 0.8.0 (a1b13e6) running on macOS Big Sur/2019 macbook pro. That said, I'm almost exclusively using tmux, so I suppose it could be the source of the issue and not alacritty.

**Comment by daniel-bencic** [comment] 2021-07-26 13:11
Same problem since I updated to GNOME 40
OS: Linux
Version: alacritty 0.8.0
X11, GNOME 40.0.0
GPU: NVIDIA GeForce 940M (driver 460.84)

**Comment by rusty-electron** [comment] 2021-08-23 21:13
I am facing the same issue on:
OS: Linux
Version: alacritty 0.9.0
X11, i3-gaps
GPU: Intel UHD Graphics - CometLake

**Comment by KellanMebane** [comment] 2021-09-03 19:51
Same issue
OS: Linux, Pop_OS 21.04
Version: alacritty 0.9.0
X11, Pop Shell
GPU: Mesa Intel Xe Graphics

**Comment by nelsontkq** [comment] 2021-09-20 20:24
Same issue
OS: Solus 4.3
Kernel: 5.13.12-193.current
DE: X11 (Budgie)
GPU: GTX 1080ti with 470.63.01 drivers

**Comment by rafapolo** [comment] 2021-10-12 07:30
I also confirm allacritty freezes on X11 on since updated GNOME 40, but works fine on Wayland.

**Comment by invidian** [comment] 2021-11-12 10:48
Oddly enough, I just got affected by this, which is super annoying. On Arch Linux with latest updates, kernel 5.15.1-arch1-2, X11, xfce4. If anyone has idea how to debug this, I'm willing to help. Trying the print events workaround right now. Also using tmux, tried both version 3.2 and 3.2a. Alacritty version 0.9.0 (fed349aa).

**Comment by marcelo-r** [comment] 2021-12-09 12:49
Can confirm, its happening to me too when the system wakes up from suspend mode, input only appears after next input. I run alacritty + tmux.
OS: Fedora 35
Kernel: 5.15.6
DE/WM: X11 + i3wm
GPU: GTX 1050ti with 495.44 drivers
Alacritty: 0.9.0
Tmux: 3.2a

**Comment by chrisduerr** [comment] 2021-12-10 03:20
This seems to be a duplicate of https://github.com/alacritty/alacritty/issues/824. It's an X11 issue that has been causing problems for a long time, I'd suspect something related to vsync? The best solution *right now* is probably Wayland, some form of X11 frame scheduling might help in the future though.

**Closed by chrisduerr** 2021-12-10 03:20 UTC

**Comment by userom11** [comment] 2024-12-08 18:33
I can confirm it happens to me as well.
Fedora Linux 40
SwayWM (Wlroots, Wayland)
Intel Tigerlake UHD graphics.
Linux 6.11.10
Also for some reason its using EGL.
