### ISSUE TITLE
ubuntu 20.10 Screen fails to redraw until subsequent key press

### ISSUE THREAD

**Issue by drewbailey** [alacritty/alacritty#4362] opened 2020-10-29 14:05 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

I just recently updated to ubuntu 20.10 and built alacritty from master, I'm getting issues where my input isn't rendering until I press a subsequent key, If I paste in a line, I'll have to hit right arrow or space for the rest of the input to render.

### System

OS: ubuntu
Version: 0.5.0 master 
Linux/BSD: X11

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
```
Created log file at "/tmp/Alacritty-36041.log"
[2020-10-29 10:02:31.931332034] [INFO] Welcome to Alacritty
[2020-10-29 10:02:31.931416740] [INFO] Configuration loaded from "/home/drew/.config/alacritty/alacritty.yml"
[2020-10-29 10:02:31.946076467] [DEBUG] Estimated DPR: 1
[2020-10-29 10:02:31.946101872] [DEBUG] Estimated Cell Size: 8 x 17
[2020-10-29 10:02:31.946109730] [DEBUG] Estimated Dimensions: None
[2020-10-29 10:02:31.976644901] [INFO] Device pixel ratio: 1
[2020-10-29 10:02:31.982256712] [INFO] Initializing glyph cache...
[2020-10-29 10:02:32.009225497] [INFO] ... finished initializing glyph cache in 0.026928949s
[2020-10-29 10:02:32.009255681] [INFO] Cell Size: 8 x 17
[2020-10-29 10:02:32.009263924] [INFO] Padding: 0 x 0
[2020-10-29 10:02:32.009274493] [INFO] Width: 800, Height: 600
[2020-10-29 10:02:32.011150775] [INFO] PTY dimensions: Line(35) x Column(100)
[2020-10-29 10:02:32.016299963] [INFO] Initialisation complete
[2020-10-29 10:02:32.022341233] [DEBUG] Term::resize dimensions unchanged
[2020-10-29 10:02:32.022387032] [INFO] Width: 800, Height: 600
[2020-10-29 10:02:35.623135927] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-36041.log"```

Keyboard and bindings: `alacritty --print-events`

**Comment by nixpulvis** [comment] 2020-10-29 15:40
Sounds a lot like #3828 

Also, you say you built from master but then list 0.5.0 as the version. 0.5.0 is not the latest **master** in git, but instead the latest **release**. I'd be curious if you can reproduce on `master` as well.

**Comment by drewbailey** [comment] 2020-10-30 13:05
You are right, I had assumed running `cargo build --release` on master would use HEAD but I guess not. Here's a gif of the issue

![alacritty](https://user-images.githubusercontent.com/2614075/97708333-03b87d80-1a8f-11eb-811e-b870f4280bf8.gif)

**Comment by nixpulvis** [comment] 2020-10-30 14:00
> You are right, I had assumed running cargo `build --release` on master would use HEAD but I guess not.

@drewbailey `cargo build` (with or without `--release`) will build whatever is checked out locally, meaning whatever files you have in your working directories. If you are building 0.5.0, that means your HEAD is pointing to that version. To be sure of the built version please pass the `--version` flag to Alacritty, it will print the commit hash as well.

> Eventually pasting in the lines instantly rendered but clearly not the first few times. This also happens when switching between tmux panes. Let me know what other info I can provide. The rest of the line renders after a subsequent key press (right arrow in this case)

Something definitely seems wrong here, but I personally have never been able to reproduce this as reliably as you seem to be able to, and frankly I haven't noticed anything in over a year now.

**Comment by drewbailey** [comment] 2020-10-30 14:12
Yeah I have been using alacritty for about 2 years now and this is the first time it's happened. It was right after upgrading to Ubuntu 20.10 from 20.04. I've switched from xorg to wayland and it's working fine but I'd be curious to see if others run into this.

**Comment by drewbailey** [comment] 2020-10-30 19:05
Correct it works fine on wayland

**Comment by chrisduerr** [comment] 2020-10-30 19:08
Then this is a duplicate of #824. It has been around for a long time but unfortunately I have never been able to reproduce it, making debugging quite difficult.

**Closed by chrisduerr** 2020-10-30 19:08 UTC
