### ISSUE TITLE
Shift Insert Paste ??

### ISSUE THREAD

**Issue by dualfade** [alacritty/alacritty#7501] opened 2023-12-29 18:27 UTC
Where did highlight text; Shift Insert == paste go ?? I cannot seam to find this.

I just sifted through open issues and do not see this ? Also I do not even see "insert" in the documentation ? Maybe This is a simple fix and I am not seeing it ?

Thanks in advance.

**Comment by kchibisov** [comment] 2023-12-29 18:30
Shift insert paste works the same it was working before, could you want more specific?

We don't control any of the highlights though, it's up to your shell for that.

**Comment by kchibisov** [comment] 2023-12-29 18:30
![image](https://github.com/alacritty/alacritty/assets/27620401/2e5b416d-6d51-4f02-858a-3b2fcfe804f7)

**Comment by dualfade** [comment] 2023-12-29 18:33
I see. Let me try this. Ping you back in a min. Appreciate it.

**Comment by dualfade** [comment] 2023-12-29 18:43
Ok. Looks like TMUX may actually be causing this behavior. Let me do some digging. 

Thanks !

**Comment by dualfade** [comment] 2023-12-29 19:04
Just fyi. Not tmux. Anyway.... You closed this before waiting on a response.

**Comment by kchibisov** [comment] 2023-12-29 19:08
I mean, what should I do with issue that doesn't even say what's the problem. I answered that we don't highlight anything, it's usually done by e.g. your shell in your prompt.

Like no point to keep it open, it's not like you can't write on it.

**Comment by kchibisov** [comment] 2023-12-29 19:09
That's zsh does for me automatically when bracketed paste mode is in use and I paste things.

![image](https://github.com/alacritty/alacritty/assets/27620401/5fca59aa-0cd2-4750-9177-8d55a5e0e65f)

**Comment by dualfade** [comment] 2023-12-29 19:14
hahahhaha I know you don't highlight stuff. Im saying there is some odd behavior here and I was trying to ping it down so I could give you more information. That is all. 

![image](https://github.com/alacritty/alacritty/assets/2522757/36a92b07-0cd0-4be3-a643-46f146a30916)

Anyway. Just keep it closed. Ill find the issue. Something is different between prior alacritty and this newest version. Aka toml; and I dont know what the diff is. Never had this issue prior.

Thanks.

**Comment by kchibisov** [comment] 2023-12-29 19:19
If you can show me the gif of what was before and what you have now I can probably help, long with what you press. I can't really guess.

**Comment by dualfade** [comment] 2023-12-29 19:27
I get it and understand. Difficult to show honestly. Once you reload the term, highlight some text; shift ins starts working again. Otherwise shift ins paste only pastes  "~" to the term from the prior highlighted text.

I don't know. Def kinda odd. Is what it is for right now. Not a deal breaker. If I find something useful Ill come back. Until then. Much appreciated.

**Comment by kchibisov** [comment] 2023-12-29 19:35
`Shift + Insert` by default pastes the selection clipboard (not regular paste clipboard) so when you highlight something it'll paste from it, because it's getting yanked. It's a copy paste, the same as `Ctrl + Shift + V`, just different source.

**Comment by dualfade** [comment] 2023-12-29 20:29
Rebooted; So clean start -
Tmux Disabled to rule that out --
Fresh terminal launched. No other terminals running --

Highlight --
![image](https://github.com/alacritty/alacritty/assets/2522757/eb8aa6ab-971c-43db-887c-d4eaded3b99a)

Shift Ins --
![image](https://github.com/alacritty/alacritty/assets/2522757/06b0bfb3-82d0-44f8-bc22-255aa459939e)

Kill that terminal and open a new one --
Shift Ctl x
Mod enter

Highlight --
![image](https://github.com/alacritty/alacritty/assets/2522757/457b739c-4d4d-40e6-8fd9-77d5c0b41f3b)

Shift Ins paste ( works ) --
![image](https://github.com/alacritty/alacritty/assets/2522757/0e0326b3-4905-404f-85c7-af522955c5c2)

Highlight; shift ins paste works on all new terminals from this point forward.

![image](https://github.com/alacritty/alacritty/assets/2522757/9eb7d161-16b9-47b5-a664-0194f0c0e61a)

Config --

```zsh
shell = "/usr/bin/zsh"

[keyboard]
bindings = [
  {key = "Insert",mods = "Shift",action = "PasteSelection"}
]

[colors.bright]
black = "#666666"
blue = "#48c6ff"
cyan = "#63e7f0"
green = "#ccff00"
magenta = "#be67e1"
red = "#ff00a0"
white = "#f3f3f3"
yellow = "#ff9f00"

[colors.cursor]
cursor = "#c5c5c5"
text = "#1c1c1c"

[colors.normal]
black = "#1c1c1c"
blue = "#048ac7"
cyan = "#0ac1cd"
green = "#cee318"
magenta = "#833c9f"
red = "#ff005b"
white = "#e5e5e5"
yellow = "#ffe755"

[colors.primary]
background = "#1c1c1c"
foreground = "#c5c5c5"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 8

[font.bold]
family = "mono"
style = "Bold"

[font.bold_italic]
family = "mono"
style = "Bold Italic"

[font.italic]
family = "mono"
style = "Italic"

[font.normal]
family = "mono"
style = "Regular"

[scrolling]
history = 5000

[window.dimensions]
columns = 130
lines = 30

[window.padding]
x = 4
y = 4

```

Maybe this helps ? Its odd. Anyway. I am not sure what it is an hard to demonstrate.

Thanks !

**Comment by kchibisov** [comment] 2023-12-29 20:34
So your issue is that the content you select is not pasted straight away and the old contents is being pasted instead until you select a bunch of times?

Like the content you select is not copied immediately?

**Comment by kchibisov** [comment] 2023-12-29 20:35
Could you try this patch  https://github.com/alacritty/alacritty/issues/7500#issuecomment-1872295185

**Comment by dualfade** [comment] 2023-12-29 20:44
No there is no prior content. Its a fresh new terminal first run. Once you close that terminal and open a new one shift insert paste starts working. 

Sure let me try it.

**Comment by dualfade** [comment] 2023-12-29 21:04
Seams to work. I patched and rebuilt --

![image](https://github.com/alacritty/alacritty/assets/2522757/a85331aa-97f7-4704-a45d-7418ba402b07)

You can see it here.

**Comment by dualfade** [comment] 2023-12-29 21:13
Thanks !!!

**Comment by kchibisov** [comment] 2023-12-29 22:16
Could you try this

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 0783e44e..88bf3949 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -469,8 +469,7 @@ dependencies = [
 [[package]]
 name = "copypasta"
 version = "0.10.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "6d35364349bf9e9e1c3a035ddcb00d188d23a3c40c50244c03c27a99fc6a65ae"
+source = "git+https://github.com/alacritty/copypasta?branch=x11-clipboard-bisect#80eb5388f2657a5f86f438c08f93b3751498fd56"
 dependencies = [
  "clipboard-win",
  "objc",
@@ -2386,9 +2385,9 @@ dependencies = [

 [[package]]
 name = "x11-clipboard"
-version = "0.8.1"
+version = "0.8.0"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "b41aca1115b1f195f21c541c5efb423470848d48143127d0f07f8b90c27440df"
+checksum = "4e6a68ba9a98933993a0b17042dc4b1737d11c0c8a8de93855c9516b2921972c"
 dependencies = [
  "x11rb 0.12.0",
 ]
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index ad732cfd..a5665e49 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -25,7 +25,7 @@ version = "0.1.3-dev"
 ahash = { version = "0.8.6", features = ["no-rng"] }
 bitflags = "2.2.1"
 clap = { version = "4.2.7", features = ["derive", "env"] }
-copypasta = { version = "0.10.0", default-features = false }
+copypasta = { git = "https://github.com/alacritty/copypasta", branch = "x11-clipboard-bisect", default-features = false }
 crossfont = { version = "0.7.0", features = ["force_system_fontconfig"] }
 glutin = { version = "0.31.1", default-features = false, features = ["egl", "wgl"] }
 home = "0.5.5"
```

**Comment by awused** [comment] 2023-12-29 22:22
I attempted to reproduce this bug on alacritty 0.13 and was unable to. Can you be more clear about the reproduction steps in https://github.com/alacritty/alacritty/issues/7501#issuecomment-1872323353? Do you have a display manager? How are you starting alacritty after the reboot? Does it reproduce 100% of the time after a reboot and can you reproduce it without a full reboot?

Does it reproduce with the default alacritty config?

**Comment by dualfade** [comment] 2023-12-29 23:41
To answer those --

I'm running Spectrwm ( also pasted above )--
![image](https://github.com/alacritty/alacritty/assets/2522757/3984b7b9-27dd-4589-8eef-5a95bbad8f2e)

```zsh
~ % yalocs alacritty$
local/alacritty 0.13.0-2
    A cross-platform, GPU-accelerated terminal emulator
~ %
```

I start Alacritty with Mod Enter as this is a tiing window manager.

```zsh
~ % cat ~/.config/spectrwm/spectrwm.conf | ag alacritty
program[term]   = alacritty
program[alacritty]    = alacritty
bind[alacritty]             = MOD+Return
~ %
```
It ONLY happens on the first time an Alacritty terminal is launched.. If you close it and open a new one. highlight; Shift insert will paste as it should. 

It happens with or without tmux enabled.

More then happy to patch, however in order to test I really should do a clean boot and launch an initial terminal. That is when it happens. So hard to show as I stated earlier. 

Thank you.

**Comment by dualfade** [comment] 2023-12-29 23:45
> Could you try this
> 
> ```diff
> diff --git a/Cargo.lock b/Cargo.lock
> index 0783e44e..88bf3949 100644
> --- a/Cargo.lock
> +++ b/Cargo.lock
> @@ -469,8 +469,7 @@ dependencies = [
>  [[package]]
>  name = "copypasta"
>  version = "0.10.0"
> -source = "registry+https://github.com/rust-lang/crates.io-index"
> -checksum = "6d35364349bf9e9e1c3a035ddcb00d188d23a3c40c50244c03c27a99fc6a65ae"
> +source = "git+https://github.com/alacritty/copypasta?branch=x11-clipboard-bisect#80eb5388f2657a5f86f438c08f93b3751498fd56"
>  dependencies = [
>   "clipboard-win",
>   "objc",
> @@ -2386,9 +2385,9 @@ dependencies = [
> 
>  [[package]]
>  name = "x11-clipboard"
> -version = "0.8.1"
> +version = "0.8.0"
>  source = "registry+https://github.com/rust-lang/crates.io-index"
> -checksum = "b41aca1115b1f195f21c541c5efb423470848d48143127d0f07f8b90c27440df"
> +checksum = "4e6a68ba9a98933993a0b17042dc4b1737d11c0c8a8de93855c9516b2921972c"
>  dependencies = [
>   "x11rb 0.12.0",
>  ]
> diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
> index ad732cfd..a5665e49 100644
> --- a/alacritty/Cargo.toml
> +++ b/alacritty/Cargo.toml
> @@ -25,7 +25,7 @@ version = "0.1.3-dev"
>  ahash = { version = "0.8.6", features = ["no-rng"] }
>  bitflags = "2.2.1"
>  clap = { version = "4.2.7", features = ["derive", "env"] }
> -copypasta = { version = "0.10.0", default-features = false }
> +copypasta = { git = "https://github.com/alacritty/copypasta", branch = "x11-clipboard-bisect", default-features = false }
>  crossfont = { version = "0.7.0", features = ["force_system_fontconfig"] }
>  glutin = { version = "0.31.1", default-features = false, features = ["egl", "wgl"] }
>  home = "0.5.5"
> ```

Would it be possible to get patch files ?

**Comment by kchibisov** [comment] 2023-12-29 23:48
>Would it be possible to get patch files ?

What do you mean? Just paste it to `git apply -3` running on a clean alacritty tree, it's a `diff` suitable for git diff.

**Comment by dualfade** [comment] 2023-12-30 00:04
> ```diff
> "0.8.0"
> ```

Ah my bad. Patched and recompiling now. It's been one of those days hahahaha. I'm ready for it to be done ;)

**Comment by dualfade** [comment] 2023-12-30 00:18
Ok done. rebooted. Clean launch of Alacritty. Terminal one is the first terminal launched and you can see it's not copy pasting. Terminal 2 is the second terminal launched and is copy pasting. Now all new terminals from this point forward will be fine.

![image](https://github.com/alacritty/alacritty/assets/2522757/10c97d96-fc3d-4580-a52f-7a90b8615580)

```zsh
~ % z github 'z#/home/dualfade/Workspace/src/github.com'
github.com % cd alacritty/alacritty/target/release
release[master*] % sha512sum alacritty /usr/bin/alacritty
6b223678bbc814e04f73d79f0804c114a2335aaa770319b6d42a523039a39ee372b9b0709267b0d145effd68cd6fa4511c24aa61e7b2f1e9684f40fb3d7b8a68  alacritty
6b223678bbc814e04f73d79f0804c114a2335aaa770319b6d42a523039a39ee372b9b0709267b0d145effd68cd6fa4511c24aa61e7b2f1e9684f40fb3d7b8a68  /usr/bin/alacritty
release[master*] %
```

If I am the only person with this issue then it's gotta be something else.

Thank you.

**Comment by dualfade** [comment] 2023-12-30 02:26
I would say just close this. It has to be a one off issue and not a deal breaker. I've been using Alacritty for years and will continue to do so ;) 

Really appreciate you guys looking into it.

**Comment by kchibisov** [comment] 2023-12-30 02:30
All just keep it open around, it's a change in the end of the day...

**Comment by dualfade** [comment] 2023-12-30 02:33
Appreciate it.

**Comment by yusufaktepe** [comment] 2024-01-01 22:39
I'm not sure if this is related, but sending the <kbd>Shift</kbd>+<kbd>Insert</kbd> key combination with an external tool (`xdotool`) doesn't work with v0.13, even though it worked before.
```sh
xdotool key --clearmodifiers Shift+Insert
```

**Comment by kchibisov** [comment] 2024-01-01 22:52
@yusufaktepe your issue is fixed on master.

**Comment by yusufaktepe** [comment] 2024-01-01 22:56
> @yusufaktepe your issue is fixed on master.

Thank you, I'll switch to latest git build.

**Comment by dualfade** [comment] 2024-01-01 22:57
That would be awesome. Will try / do the same. Thanks !

**Comment by kchibisov** [comment] 2024-01-01 23:00
@dualfade not your issue though.

**Comment by dualfade** [comment] 2024-01-01 23:01
> @dualfade not your issue though.

Gotcha ! Thanks.

**Comment by dualfade** [comment] 2024-01-01 23:11
Are you sure ? I just tried it and everything is working !!!

```zsh
/tmp % z github 'z#/home/dualfade/Workspace/src/github.com'
github.com % cd alacritty/alacritty/target/release
release[master] % b2sum alacritty
168794c870dcc827ec41a6e1ff241c7f93938ebedad1500bc522709243f98cf3cf46a16d4a7060f7ab43a6a11e841b602037e5bba07508eb01141eb4ca4b6a55  alacritty
release[master] % alacritty --version
alacritty 0.14.0-dev (659550ee)
release[master] %

```

**Comment by kchibisov** [comment] 2024-01-01 23:16
I mean, giving how obscure your bug report is if you think that it's fixed then I'll close it.

**Comment by dualfade** [comment] 2024-01-01 23:16
awesome. Mucho Thanks !

**Closed by kchibisov** 2024-01-01 23:16 UTC
Labels: A - needs repro, P - low, DS - X11, B - regression
