### ISSUE TITLE
SearchBackward key binding not working in 0.5.0-rc2 vi mode

### ISSUE THREAD

**Issue by markstos** [alacritty/alacritty#4012] opened 2020-07-22 02:09 UTC
In `alacritty.yml`, Shift-/ is documented as key to start a backwards search in Vi mode, but it seems to do nothing for me. The ForwardSearch key binding works for me. 

I tried explicitly adding the keybinding from the samle `alacritty.yml` to my own file, but that didn't help. 

I tested multiple times to see if it might be user error but I couldn't get it to work. 

### System

OS: Linux
Version:alacritty 0.5.0-rc2 (714bbb7)
Linux/BSD: X11

**Comment by chrisduerr** [comment] 2020-07-22 02:20
This is a duplicate of https://github.com/alacritty/alacritty/issues/3460.

Unfortunately on some backends the default binding does not work. So you have to make it work yourself using the keysyms instead of the virtual keycodes.

**Closed by chrisduerr** 2020-07-22 02:20 UTC
