### ISSUE TITLE
VIM Scroll issue (ConPTY)

### ISSUE THREAD

**Issue by codehz** [alacritty/alacritty#3783] opened 2020-05-28 13:42 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Windows 10 19619
Version: alacritty 0.4.3-rc1 (04114e7)
Windows: ConPTY

### Logs

![image](https://user-images.githubusercontent.com/13158903/83148501-a01ad480-a12b-11ea-98cc-7697200b32ff.png)

see first line, only the first line and last two lines was updated when I press `down` / `j` key (that will cause screen to scroll down)
and `up` / `k` won't trigger this bug
(no issue with winpty)

**Comment by kchibisov** [comment] 2020-05-28 13:48
>(no issue with winpty)

Seems like a conpty bug then, since both are just pipes(with tons of filters to filter escapes) and it's purely up to them what to send us. Not sure what we can do here.

>I press down / j key (that will cause screen to scroll down)

The key to scroll in vim is `ctrl + e` / `ctrl + y`. `j`/`down` moves the cursor, and scroll when you reach bounds.

**Comment by codehz** [comment] 2020-05-28 14:11
> The key to scroll in vim is `ctrl + e` / `ctrl + y`. `j`/`down` moves the cursor, and scroll when you reach bounds.

yes, `ctrl+e` can also cause this bug...

> Seems like a conpty bug then

but it works with the official windows terminal

**Comment by kchibisov** [comment] 2020-05-28 14:14
>but it works with the official windows terminal (the UWP one)

They bundle their own version of ConPty, so it's not representative. We're using the one, which is on your system, which is not the one windows terminal is using.

**Comment by chrisduerr** [comment] 2020-05-28 14:17
Getting the output of `alacritty -vvv | grep "scrolling region"` might be useful. I'd assume that ConPTY is just setting an incorrect scrolling region.

**Comment by codehz** [comment] 2020-05-28 14:25
> scrolling region

actually I don't found the keyword in the log... (yes, the command output nothing)
there is part of the log
```
[2020-05-28 22:20:54.591095700] [DEBUG] [Unhandled CSI] action='l', args=[25], intermediates=[]
[2020-05-28 22:20:54.591095700] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=39, col=164
[2020-05-28 22:20:54.591095700] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=39, col=164
[2020-05-28 22:20:54.606732200] [TRACE] [alacritty_terminal\src\term\mod.rs:1911] Setting attribute: Foreground(Spec(Rgb { r: 175, g: 95, b: 0 }))
[2020-05-28 22:20:54.606732200] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=0, col=0
[2020-05-28 22:20:54.646991800] [TRACE] [alacritty_terminal\src\term\mod.rs:1911] Setting attribute: Foreground(Named(Red))
[2020-05-28 22:20:54.648031800] [TRACE] [alacritty_terminal\src\term\mod.rs:1724] Clearing line: Right
[2020-05-28 22:20:54.674995900] [TRACE] [alacritty_terminal\src\term\mod.rs:1911] Setting attribute: Foreground(Spec(Rgb { r: 175, g: 95, b: 0 }))
[2020-05-28 22:20:54.676037800] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=38, col=0
[2020-05-28 22:20:54.696514000] [TRACE] [alacritty_terminal\src\term\mod.rs:1911] Setting attribute: Foreground(Named(Cyan))
[2020-05-28 22:20:54.697426300] [TRACE] [alacritty_terminal\src\term\mod.rs:1724] Clearing line: Right
[2020-05-28 22:20:54.706558000] [TRACE] [alacritty_terminal\src\term\mod.rs:1911] Setting attribute: Reset
[2020-05-28 22:20:54.707581300] [TRACE] [alacritty_terminal\src\term\mod.rs:1541] Carriage return
[2020-05-28 22:20:54.718029700] [TRACE] [alacritty_terminal\src\term\mod.rs:1549] Linefeed
[2020-05-28 22:20:54.719061000] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=5, col=0
[2020-05-28 22:20:54.731059400] [TRACE] [alacritty_terminal\src\term\mod.rs:1942] Setting mode: ShowCursor
[2020-05-28 22:21:15.475865200] [DEBUG] [Unhandled CSI] action='l', args=[25], intermediates=[]
[2020-05-28 22:21:15.475865200] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=39, col=164
[2020-05-28 22:21:15.475865200] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=39, col=164
[2020-05-28 22:21:15.491516600] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=0, col=0
[2020-05-28 22:21:15.491516600] [TRACE] [alacritty_terminal\src\term\mod.rs:1724] Clearing line: Right
[2020-05-28 22:21:15.529953600] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=38, col=0
[2020-05-28 22:21:15.529953600] [TRACE] [alacritty_terminal\src\term\mod.rs:1724] Clearing line: Right
[2020-05-28 22:21:15.529953600] [TRACE] [alacritty_terminal\src\term\mod.rs:1541] Carriage return
[2020-05-28 22:21:15.562186100] [TRACE] [alacritty_terminal\src\term\mod.rs:1549] Linefeed
[2020-05-28 22:21:15.562186100] [TRACE] [alacritty_terminal\src\term\mod.rs:1383] Going to: line=5, col=0
[2020-05-28 22:21:15.563194300] [TRACE] [alacritty_terminal\src\term\mod.rs:1942] Setting mode: ShowCursor
```

**Comment by codehz** [comment] 2020-05-28 14:26
> your system

hmmm, I'm using insider version of the win 10, maybe they just break something...

**Comment by chrisduerr** [comment] 2020-05-28 14:32
> actually I don't found the keyword in the log

Have you opened vim and actually scrolled in vim, or just started Alacritty and closed it? Scrolling regions aren't set until you scroll in vim.

**Comment by codehz** [comment] 2020-05-28 14:33
> Have you opened vim and actually scrolled in vim

of course, the log I paste is I use ctrl+e in vim

**Comment by kchibisov** [comment] 2020-05-28 14:36
Do you see those something from this grep on WinPTY backend?

**Comment by codehz** [comment] 2020-05-28 14:44
> Do you see those something from this grep on WinPTY backend?

nope, there is the full log (-vvv)
[log.txt](https://github.com/alacritty/alacritty/files/4696237/log.txt)

**Comment by kchibisov** [comment] 2020-05-28 14:49
Seems like nothing we can do about then? Like they both decided to manage scrolling for us and we just render things.

**Comment by codehz** [comment] 2020-05-28 14:59
btw, the `Unhandled CSI` may indicated something

https://github.com/alacritty/alacritty/blob/81ce93574f62d4b117fdd79af65391f30316a457/alacritty_terminal/src/ansi.rs#L427-L450

https://github.com/alacritty/alacritty/blob/81ce93574f62d4b117fdd79af65391f30316a457/alacritty_terminal/src/ansi.rs#L1026-L1033

it seems `CSI 25 l` has been handled... why it still report not handdled..

**Comment by chrisduerr** [comment] 2020-05-28 15:02
@codehz Could you give me your `alacritty --version` output?

**Comment by kchibisov** [comment] 2020-05-28 15:04
And also, from where did you install the version?

**Comment by codehz** [comment] 2020-05-29 01:25
> @codehz Could you give me your `alacritty --version` output?

in top, alacritty 0.4.3-rc1 (04114e7)

> And also, from where did you install the version?

Github release: the portable version

**Comment by chrisduerr** [comment] 2020-05-29 02:12
Oh, the `CSI` isn't recognized because it's not correct. It's using `\e[25l` instead of `\e[?25l`.

Which shell are you using? Powershell? Could you try starting Alacritty with one of the following commands, to see if any of these help?

 - `TERM=alacritty vim`
 - `TERM=xterm vim`
 - `TERM=xterm-256color vim`
 - `TERM=cygwin vim`

**Comment by codehz** [comment] 2020-05-29 07:00
> Which shell are you using

bash in wsl

> to see if any of these help

nope, the Unhandled CSI still exists
ps: /usr/share/terminfo/a/alacritty is exists

**Comment by chrisduerr** [comment] 2020-05-29 17:07
Can you reproduce this outside of WSL? Also which version of WSL are you using?

**Comment by codehz** [comment] 2020-05-30 02:32
> reproduce this outside of WSL

nope, only happens in WSL

> which version of WSL

WSL2

**Comment by chrisduerr** [comment] 2020-05-30 14:41
What is the default `TERM` value for you? This sounds like it might be a WSL2 issue.

Could you record a ref-test to see which escape sequences are emitted?

You can do so by running `alacritty --ref-test` which will generate a few files in the directory it was started from. I'm interested in the `alacritty.recording` file which should emit all escapes during this recording.

**Comment by codehz** [comment] 2020-06-01 02:53
> What is the default `TERM` value for you

xterm-256color

(but manually set as alacritty has no effect



> I'm interested in the `alacritty.recording` file

[alacritty.recording.txt](https://github.com/alacritty/alacritty/files/4709131/alacritty.recording.txt)

(rename to txt so I can upload directly

**Comment by chrisduerr** [comment] 2020-06-02 19:42
Your vim isn't even using scrolling regions, something's really messed up with it.

Could you try WSL1?

**Comment by orcasauce** [comment] 2020-06-04 17:45
Seeing similar behavior. This occurs for me in WSL1/2 Ubuntu 20.04 both in and out of a fresh (no config) tmux session. I've experienced this on both `0.4.2` and `0.4.3`. This started on a previous Windows version, but currently I'm on `Windows 10 Pro Build 19640.mn_release.200530-1731`. 

Here's a...
video clip of what I'm experiencing: https://www.youtube.com/watch?v=ppT6DEv1S_I
recording of the session: [alacritty.recording.txt](https://github.com/alacritty/alacritty/files/4731782/alacritty.recording.txt)
my config: [alacritty.yml.txt](https://github.com/alacritty/alacritty/files/4731794/alacritty.yml.txt)
env vars (omitting PATH, PWD,  and NIX_* that contain semi-private/unrelated info): ```SHELL=/bin/bash
WSL_DISTRO_NAME=Ubuntu-20.04
NAME=juice
LOGNAME=whitney
HOME=/home/whitney
LANG=C.UTF-8
WSL_INTEROP=/run/WSL/6_interop
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=whitney
SHLVL=0
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
HOSTTYPE=x86_64
_=/usr/bin/env```
bash version: GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)


While I'm demonstrating the issue using vim, the issue is not limited to vim; I have experienced identical behavior at a command prompt.

**Comment by chrisduerr** [comment] 2020-06-04 17:47
Does this issue occur outside of tmux for you @orcasauce?

**Comment by orcasauce** [comment] 2020-06-04 17:57
> Does this issue occur outside of tmux for you @orcasauce?

> both in and out of a fresh (no config) tmux session.

**Comment by chrisduerr** [comment] 2020-06-04 18:10
Would be nice to see if someone can reproduce this on the latest stable release of Windows 10.

**Comment by vitpekarek** [comment] 2020-06-06 19:49
I am using Windows 10 2004 build and have same issue :/

**Comment by chrisduerr** [comment] 2020-06-06 21:19
@vitpekarek Using which backend and shell?

**Comment by vitpekarek** [comment] 2020-06-07 14:27
I am on wsl ubuntu using zsh and conpty backend

**Comment by chrisduerr** [comment] 2020-06-07 20:11
@davidhewitt Can you reproduce this?

**Comment by cole-h** [comment] 2020-06-08 00:09
I can't reproduce using ConPTY  or WinPTY on Windows 10 v1909 (I haven't been offered the v2004 update yet) on `alacritty 0.4.2 (f68de37)`. Maybe a new Windows-based regression?

**Comment by chrisduerr** [comment] 2020-06-08 00:14
Looks like ConPTY doesn't send through the escapes anymore then. So not an Alacritty bug. Thanks for testing @cole-h.

**Closed by chrisduerr** 2020-06-08 00:14 UTC
Labels: A - needs repro, H - windows, W - ConPTY

**Comment by davidhewitt** [comment] 2020-06-08 18:46
Sorry to be late to the party. I'm on Windows 10 2004 (installed it manually using the [update assistant](https://www.microsoft.com/en-gb/software-download/windows10) FYI @cole-h)

I can't reproduce this issue on either alacritty `0.4.2` or `master`.
