### ISSUE TITLE
Key repeat lag on Ubuntu/X11

### ISSUE THREAD

**Issue by glostis** [alacritty/alacritty#3655] opened 2020-04-29 16:49 UTC
### System

OS: Linux
Version: 0.4.1 installed through `ppa:mmstick76/alacritty`
Linux/BSD: X11 with Gnome 3.8.24 DE

Here's some information about my system, from the `neofetch` command:
```
OS: Ubuntu 18.04.4 LTS x86_64
Host: XPS 13 9370
Kernel: 5.3.0-46-generic
Shell: zsh 5.4.2
Resolution: 1920x1080, 1920x1080
DE: GNOME 3.28.4
WM: GNOME Shell
WM Theme: Adwaita
Theme: Ambiance [GTK2/3]
Icons: Ubuntu-mono-dark [GTK2/3]
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: Intel UHD Graphics 620
Memory: 6369MiB / 15729MiB
```

### Issue

Following up on https://github.com/alacritty/alacritty/issues/2876#issuecomment-620508260, I'm opening a new issue as my problem seems to be different from OP, since we are on different systems.

When "scrolling" in Vim by keeping `j/k` pressed down, it seems that Vim keeps scrolling for a few lines after I've physically released the key.

I've found a way to demonstrate the issue using [xdotool](https://github.com/jordansissel/xdotool) to send keys to the terminal in a controlled manner.

Running the following snippet in the terminal sends keys 0 through 9 ten times:
```bash
xdotool key --delay 0 $(for i in $(seq 1 10); do for j in $(seq 0 9); do echo -n "$j "; done; done)
```

Which looks like this in `alacritty` - you can see a significant lag before all keys are displayed:

![alac](https://user-images.githubusercontent.com/25295717/80474413-b7597d00-8947-11ea-89a3-6e0ad4a6cf15.gif)

And looks like this in `terminator` - all keys are displayed instantly (I've also tried it on GNOME terminal and XTerm and got the same result):

![terminator](https://user-images.githubusercontent.com/25295717/80474628-f8519180-8947-11ea-9088-1206cec98276.gif)

As pointed out in https://github.com/alacritty/alacritty/issues/2876#issuecomment-620831330, this issue is apparent when using X11, but disappears when switching to Wayland.

I totally understand that it is very hard for anyone to solve this issue if you cannot reproduce it yourselves. I would love to be able to contribute, but this is way out of my league...

Besides this minor usability pain point, I really love this terminal, thanks for the awesome work!

**Comment by glostis** [comment] 2020-04-29 17:18
Here's a screen recording with three terminal windows open:
1. `alacritty` on the left, showing a `git diff`
2. The log of `alacritty --print-events` in the lower right
2. The log of `showkey` in the upper right.

I'm scrolling the output of `git diff` by pressing `j` for a while, releasing it, then pressing `k` for a while.

The log of `showkey` instantly reacts to my key releases, so `keycode ... release` get printed out in the upper right as soon as I release the key. You can see in the recording that the scrolling continues a bit after the key is being released, and `--print-events` continues showing a few lines of log.

![g](https://user-images.githubusercontent.com/25295717/80625724-e9550700-8a4d-11ea-9da9-be934d8355fe.gif)

(I've slightly slowed down the GIF so that the delay is easily visible).

**Comment by chrisduerr** [comment] 2020-04-29 20:46
@glostis Could you perform the same test you did with `alacritty --print-events` but instead run the example of [winit](https://github.com/rust-windowing/winit)?

If the events keep coming in even after the button was released, you should see identical behavior in those example apps which would mean it would need to be patched in winit.

You can run examples in rust using `cargo run --example window` for example.

**Comment by glostis** [comment] 2020-04-30 08:12
@chrisduerr thanks for looking into this, I appreciate it!

I've run `cargo run --example window` (from a terminal other than `alacritty`) and I see no lag between key releases and the logged events, the logs stop as soon as I release the key.

**Comment by kchibisov** [comment] 2020-04-30 08:24
@glostis could you try https://github.com/alacritty/alacritty/pull/3660

**Comment by glostis** [comment] 2020-04-30 09:31
@kchibisov I've compiled from your branch and tried it out, but unfortunately it doesn't seem to change the behavior I observe.

**Comment by chrisduerr** [comment] 2020-04-30 16:52
Are you testing while your laptop is plugged into power, or with it disconnected?

Also do you have any 'lighter' X11 WMs installed for testing? Like openbox/i3?

**Comment by glostis** [comment] 2020-05-01 09:18
@chrisduerr the issue occurs both with the laptop plugged into power and while disconnected.

I've just installed i3 to try it out, and the issue does not happen in i3 as far as I can tell.
It must therefore have something to do with X11/Gnome DE specifically.

**Comment by kchibisov** [comment] 2020-05-01 09:23
It could be related to mutter aka compositor GNOME is using then, but the lag seems very strange and knowing that it doesn't happen on i3 it's just strange now.

**Comment by glostis** [comment] 2020-06-25 13:42
FYI I've entirely dropped Gnome DE and switched to i3 WM instead, so I don't experience the issue I described anymore.

Feel free to close the issue if you think that it clutters the repository's issues!

**Comment by chrisduerr** [comment] 2020-06-25 15:19
I'm going to close this for now since the only user I'm aware of does not run GNOME anymore. I think in general this is not an issue on GNOME from what I have heard.

If someone else can reproduce this issue, please let me know.

**Closed by chrisduerr** 2020-06-25 15:19 UTC
Labels: A - needs repro, DS - X11, H - linux, S - input
