### ISSUE TITLE
alacritty won't start on my windows 10 host

### ISSUE THREAD

**Issue by jasonwbarnett** [alacritty/alacritty#6970] opened 2023-05-31 20:26 UTC
### System

OS: Windows
Version: `alacritty 0.12.1 (5fdfd47)`

#### Windows Event Viewer

```text
Faulting application name: Alacritty-v0.12.1-portable.exe, version: 0.0.0.0, time stamp: 0x646a9b49
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000005
Fault offset: 0x0000000000025f31
Faulting process id: 0x5cb0
Faulting application start time: 0x01d993fc9aab7ae3
Faulting application path: C:\Users\Jason.Barnett\Desktop\Alacritty-v0.12.1-portable.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 44aeeee1-07bc-4f2e-9206-76963862a7ab
Faulting package full name: 
Faulting package-relative application ID: 
```

#### Alacritty

```
[0.000005600s] [INFO ] [alacritty] Welcome to Alacritty
[0.001356300s] [INFO ] [alacritty] Version 0.12.1 (5fdfd47)
[0.005881800s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.025038400s] [INFO ] [alacritty] Window scale factor: 1
[0.030862600s] [INFO ] [alacritty] Using WGL
[0.033859100s] [DEBUG] [alacritty] Loading "Consolas" font
```

If there is anything additionally I can provide that you think would be helpful, just let me know.

**Comment by kchibisov** [comment] 2023-05-31 20:28
Try the `msi` installer one.

**Comment by kchibisov** [comment] 2023-05-31 20:32
Maybe windows prevents running executables from download folder, because the error doesn't look like alacritty thrown, but some windows library.

**Comment by jasonwbarnett** [comment] 2023-05-31 20:33
> Maybe windows prevents running executables from download folder, because the error doesn't look like alacritty thrown, but some windows library.

Agreed. This doesn't look like anything directly related to Alacritty itself. I'm going to use the MSI installer on another host and see if that works.

**Comment by jasonwbarnett** [comment] 2023-05-31 20:50
I tried installing it and the exact same error, just a different path obviously.

```text
Faulting application name: alacritty.exe, version: 0.0.0.0, time stamp: 0x646aabd1
Faulting module name: ucrtbase.dll, version: 10.0.17763.1490, time stamp: 0x48ac8393
Exception code: 0xc0000005
Fault offset: 0x0000000000025301
Faulting process id: 0x1504
Faulting application start time: 0x01d994015bc09115
Faulting application path: C:\Program Files\Alacritty\alacritty.exe
Faulting module path: C:\windows\System32\ucrtbase.dll
Report Id: 5b869d1b-7381-4045-8661-53a8ff2a2a23
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by jasonwbarnett** [comment] 2023-05-31 21:29
Is there any debugging or other things I do to collect more information for the maintainers of this project?

**Comment by kchibisov** [comment] 2023-06-01 07:32
From what I've found it seems like the issue with the corruption of the windows files.

https://answers.microsoft.com/en-us/windows/forum/all/faulting-module-name-ucrtbasedll/6453123c-3e0c-4dbf-94d4-a68b63e6a33b

I'm providing this as a reference and not as a source of truth.

Also, ensure that your windows version 2019 update or 2018 (the one including ConPTY).

I'll close it as it indicates that the issue is not within alacritty.

**Closed by kchibisov** 2023-06-01 07:32 UTC

**Comment by fluxium** [comment] 2023-11-15 15:14
In case anyone else ends up here with this same issue:

## Runtime context
- Windows 10 running on Alienware m15 R5 (AMD)
- System has at least two GPUs: 
  - Radeon integrated graphics
  - Geforce RTX 3070 (laptop)
- System connected to Dell D6000 universal dock on USB-C
  - Laptop lid is closed and internal display inactive when connected to Dell D6000 dock
  - Benq BL3200 connected to HDMI on dock
- Alacritty 0.12.3

## Behavior
- Exactly as described by @jasonwbarnett in comments above
- This issue persisted even after a nuke and pave on my Windows 10 system
- Dell D6000 dock shows in Windows Device Manager as a display adapter
- After experimentation the issue appears to be absent when disconnected from Dell D6000 dock
- After additional experimentation the issue appears to be absent when connected to Dell D6000 dock with laptop lid open and internal display active
  - Nvidia Optimus (selects best display adapter for internal display) is running on this system which could explain why issue is absent with lid open and internal display active
- When multiple GPUs are present in a system, Windows attempts to decide which one to use app by app
- Hypothesis: when Alacritty executes, Windows WGL API attempts to use the Dell D6000 dock for rendering Alacritty and the process crashes

## Solution
1. In Windows 10 Settings > Display > Graphics settings > Graphics performance preferences, click the Browse button, navigate to, and select alacritty.exe in the Open dialog.
2. Click on the alacritty.exe entry now in the list below the Browse button, then click Options
3. You should see something like this 
![image](https://github.com/alacritty/alacritty/assets/5983328/aa7b7254-21f5-4b4d-b030-72baa27d4da6)
4. The solution that worked for me was to force Windows to select the RTX 3070 for alacritty, like so
![image](https://github.com/alacritty/alacritty/assets/5983328/c612000c-75e1-4056-8ff9-a7bed532c8e4)

> [!NOTE]
> Using Nvidia control panel yielded the same solution, I opted for adding this preference in Windows settings.
> Settings can be found in NVIDIA Control Panel > Manage 3D settings > Program settings tab

## Conclusion
- This solution was only possible because my system has an alternate GPU that doesn't seem to be bound to the dock display adapter when the dock is connected.
- This seems to be a common [grievance](https://www.dell.com/community/en/conversations/laptops-general-locked-topics/latitude-e5570-d6000-dock-3d-hardwareopengl-issues/647f7443f4ccf8a8de216794?commentId=647f745af4ccf8a8de230b8f) with docks like this as a result of their internal architecture (DisplayLink)
- Nvidia Optimus could a confounding variable, as its behavior overlaps with Windows display adapter selection in some scenarios
  - Only applies to mobile systems with multiple GPUs.
- The specifics may not directly solve this issue for you; the troubleshooting process described may enable you to find what works on your system.

Happy TUIng!
