### ISSUE TITLE
Follow urls using keyboard and visible hints

### ISSUE THREAD

**Issue by quite** [alacritty/alacritty#3314] opened 2020-02-09 15:29 UTC
I'm coming from urxvt, and have been using the url-picker extensions. It allows for hitting a key, and hints (say `[a-z]`, for example) appear next to every url, hitting the hint key would run the url action.

**Comment by kchibisov** [comment] 2020-02-09 15:30
duplicate of #2536

**Closed by kchibisov** 2020-02-09 15:30 UTC
