### ISSUE TITLE
Regression: Error reading from PTY in event loop

### ISSUE THREAD

**Issue by lewisdiamond** [alacritty/alacritty#5663] opened 2021-12-05 16:21 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Archlinux
```
$ alacritty --version
alacritty 0.9.0 (fed349aa)
```
Linux/BSD: AwesomeWM

### Logs

```
$ alacritty -e bc --interactive -l
Created log file at "/tmp/Alacritty-55495.log"
[2021-12-05 11:11:39.131671541] [ERROR] [alacritty_terminal] Error reading from PTY in event loop: Input/output error (os error 5)
Deleted log file at "/tmp/Alacritty-55495.log"
```

### Repro
Run `alacritty -e bc --interactive -l` then Ctrl-D to exit `bc`.

**Comment by lewisdiamond** [comment] 2021-12-05 22:15
I've built `v0.9.0` from the repo and I'm unable to reproduce with it.

**Comment by AlexApps99** [comment] 2021-12-05 22:20
![image](https://user-images.githubusercontent.com/30854646/144766149-7490602f-d654-4729-a3a9-21ad908cdfe0.png)
Also have latest Arch Linux alacritty, got this error.
The contents of the log is simply
`[2021-12-06 11:17:41.024773015] [ERROR] [alacritty_terminal] Error reading from PTY in event loop: Input/output error (os error 5)`

**Comment by AlexApps99** [comment] 2021-12-05 22:23
I cannot reproduce with `alacritty -e bc --interactive -l`.
```
$ i3 --version
i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
$ alacritty --version
alacritty 0.9.0 (fed349aa)
$ pacman -Q xorg-server
xorg-server 21.1.1-3
$ pacman -Q linux-lts
linux-lts 5.10.83-1
```

**Comment by swalladge** [comment] 2021-12-05 22:58
I can reproduce this (with the `alacritty -e bc ... variant`, bare `alacritty`, etc., but only if its window is the last window on one of my i3 workspaces.

```
❯ pacman -Qi alacritty | grep Version
Version                  : 0.9.0-2

❯ alacritty --version
alacritty 0.9.0 (fed349aa)

❯ cat /tmp/Alacritty-86900.log
[2021-12-06 09:26:38.399282754] [ERROR] [alacritty_terminal] Error reading from PTY in event loop: Input/output error (os error 5)

❯ pacman -Qi i3-wm | grep Version
Version                  : 4.20.1-1
```

**Comment by chrisduerr** [comment] 2021-12-05 23:13
> I've built v0.9.0 from the repo and I'm unable to reproduce with it.

Assuming it's fixed on master.

**Closed by chrisduerr** 2021-12-05 23:13 UTC

**Comment by AlexApps99** [comment] 2021-12-05 23:28
But I was on the same version as them and could not reproduce their setup, therefore not being able to reproduce proves nothing about the bug being fixed.

**Comment by swalladge** [comment] 2021-12-05 23:31
@apiarian @chrisduerr 

>  therefore not being able to reproduce proves nothing about the bug being fixed.

That is very true.

I just built the latest master though, and can confirm that I can't reproduce this issue on master.

**Comment by lewisdiamond** [comment] 2021-12-05 23:35
> I just built the latest master though, and can confirm that I can't reproduce this issue on master.

I can't reproduce when using my local build of the same git commit. Something's up.

**Comment by chrisduerr** [comment] 2021-12-05 23:58
If the bug can't be reproduced, it doesn't exist. Unless you can reproduce on master, you're just wasting my time.

**Comment by sriedel** [comment] 2021-12-07 07:52
Same issue popped up for me after updating the alacritty arch package from 0.9.0-1 to 0.9.0-2 (alacritty -v output for both versions is: alacritty 0.9.0 (fed349aa))

I'm running on wayland/sway with `$term` set to a bare `alacritty`. As with @swalladge comment, this only happens when closing the last terminal window with a workspace. It doesn't matter if the shell (bash 5.1.12(1)-release) is closed with ^D or exit.

Since the git revision number in the last known good and now bad release are the same, I'm going to have to assume that the arch package maintainers either introduced the regression somehow, or an unfortunate set of circumstances with all involved arch packages is triggering the issue.

**Comment by sriedel** [comment] 2021-12-07 07:56
Ah, there's a bug report for the arch package with more information: https://bugs.archlinux.org/task/72912?project=5&string=alacritty

It seems the issue was with a rust compiler update introducing a new behavior.

**Comment by duritong** [comment] 2022-03-04 12:05
I have the same issue on Fedora 35 and swaywm with alacritty-0.9.0-4.fc35.x86_64
