### ISSUE TITLE
IPC error in sway

### ISSUE THREAD

**Issue by LamaRaz** [alacritty/alacritty#3545] opened 2020-04-02 04:18 UTC
void musl & glibc 
0.4.2
sway

when starting terminal in sway nothing happens
when exiting sway:
..ipc-client.c:88] Unable to receive IPC response1.10, 1.20 and 1.00 ES0.4.2/alacritty/ ../res/text.

st terminal works fine

**Comment by LamaRaz** [comment] 2020-04-02 05:11
the problem is opengl support

GLSL 3.30 is not supported

old netbook N450 cpu

**Comment by cole-h** [comment] 2020-04-02 05:25
Duplicate of https://github.com/alacritty/alacritty/issues/128.

**Closed** 2020-04-02 10:00 UTC
Labels: F - duplicate
