### ISSUE TITLE
Window permanently hidden after pressing Cmd+h on macOS

### ISSUE THREAD

**Issue by bmclean2** [alacritty/alacritty#3403] opened 2020-03-01 13:54 UTC
After pressing Cmd+h on macOS to hide the Alacritty window, the window becomes irreversibly hidden. Clicking on the Alacritty icon in the dock bring back the Alacritty menu, but the window remains hidden. When the happens, all keystrokes in the app producing a chime (including Cmd+q) and the app must be forced quit.

### System

OS: macOS Catalina 10.15.3
Version: alacritty 0.4.1 (4d9253b)

### Logs

Font/Terminal size:

[2020-03-01 08:45] [DEBUG] Estimated DPR: 2
[2020-03-01 08:45] [DEBUG] Estimated Cell Size: 16 x 33
[2020-03-01 08:45] [DEBUG] Estimated Dimensions: Some((3224.0, 1674.0))
[2020-03-01 08:45] [INFO] Device pixel ratio: 2
[2020-03-01 08:45] [INFO] Initializing glyph cache...
[2020-03-01 08:45] [INFO] ... finished initializing glyph cache in 0.041984654s
[2020-03-01 08:45] [INFO] Estimated DPR correctly, skipping resize
[2020-03-01 08:45] [INFO] Cell Size: 16 x 33
[2020-03-01 08:45] [INFO] Padding: 12 x 12
[2020-03-01 08:45] [INFO] Width: 3224, Height: 1674
[2020-03-01 08:45] [INFO] PTY Dimensions: Line(50) x Column(200)
[2020-03-01 08:45] [INFO] Initialisation complete
[2020-03-01 08:45] [INFO] Font size changed to Size(28) with DPR of 2
[2020-03-01 08:45] [DEBUG] New num_cols is 158 and num_lines is 45
[2020-03-01 08:45] [INFO] Width: 2560, Height: 1510

**Comment by kchibisov** [comment] 2020-03-01 14:00
fixed on the latest master

**Comment by kchibisov** [comment] 2020-03-01 14:01
duplicate of #1465

**Closed by kchibisov** 2020-03-01 14:00 UTC
