### ISSUE TITLE
Blinking cursor

### ISSUE THREAD

**Issue by ThatOneCalculator** [alacritty/alacritty#4113] opened 2020-08-12 03:43 UTC
I might be blind, but I can't find any way to enable a blinking cursor. Is that a thing on alacritty?

**Comment by kchibisov** [comment] 2020-08-12 03:45
duplicate of #302

**Closed by kchibisov** 2020-08-12 03:45 UTC

**Comment by ThatOneCalculator** [comment] 2020-08-12 05:42
Damn, that thread was closed and is from 3 years ago.
