### ISSUE TITLE
Tmux and powerline symbols 

### ISSUE THREAD

**Issue by okgolove** [alacritty/alacritty#3600] opened 2020-04-17 10:20 UTC
OS: macOS
Version: alacritty 0.4.2 (f68de37)

### Logs

Font/Terminal size: 
```[2020-04-17 13:13:01.305958000] [INFO] Welcome to Alacritty
[2020-04-17 13:13:01.306852000] [INFO] Configuration loaded from "/Users/okgolove/.config/alacritty/alacritty.yml"
[2020-04-17 13:13:01.346246000] [DEBUG] Estimated DPR: 2
[2020-04-17 13:13:01.346761000] [DEBUG] Estimated Cell Size: 19 x 43
[2020-04-17 13:13:01.346785000] [DEBUG] Estimated Dimensions: None
[2020-04-17 13:13:01.418100000] [INFO] Device pixel ratio: 2
[2020-04-17 13:13:01.421813000] [INFO] Initializing glyph cache...
[2020-04-17 13:13:01.435582000] [INFO] ... finished initializing glyph cache in 0.01364349s
[2020-04-17 13:13:01.436097000] [INFO] Cell Size: 19 x 43
[2020-04-17 13:13:01.436134000] [INFO] Padding: 0 x 0
[2020-04-17 13:13:01.436170000] [INFO] Width: 1600, Height: 1200
[2020-04-17 13:13:01.437206000] [INFO] PTY Dimensions: Line(27) x Column(84)
[2020-04-17 13:13:01.442242000] [INFO] Initialisation complete
[2020-04-17 13:13:01.682208000] [DEBUG] Term::resize dimensions unchanged
[2020-04-17 13:13:01.682561000] [INFO] Width: 1600, Height: 1200
[2020-04-17 13:13:01.787366000] [DEBUG] New num_cols is 188 and num_lines is 47
[2020-04-17 13:13:01.795132000] [INFO] Width: 3584, Height: 2056
[2020-04-17 13:13:12.897700000] [DEBUG] Term::resize dimensions unchanged
[2020-04-17 13:13:12.898318000] [INFO] Width: 3584, Height: 2056
```

My config:
```
window:
  decorations: none
  startup_mode: Maximized

font:
  normal:
    family: Monaco For Powerline
    style: Regular

  bold:
    family: Monaco For Powerline
    style: Bold

  italic:
    family: Monaco For Powerline
    style: Italic

  size: 16.0
  use_thin_strokes: true

colors:
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'

  cursor:
    text: '#1d1f21'
    cursor: '#ffffff'

  normal:
    black:   '#1d1f21'
    red:     '#cc6666'
    green:   '#b5bd68'
    yellow:  '#e6c547'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#70c0ba'
    white:   '#373b41'

  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#282a2e'
    white:   '#feffff'


selection:
  save_to_clipboard: true

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach -t base || tmux new -s base"

key_bindings:
  - { key: Q,      mods: Command,            action: None             }
  - { key: W,      mods: Command,            action: None             }
```

I'd say this one is pretty related to https://github.com/alacritty/alacritty/issues/2384 becauce the behaviour is very similar.

How to reproduce:

Tmux autostarts using alacritty config:
```
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach -t base || tmux new -s base"
```
When alacritty starts tmux this way powerline symbols don't work and are replaced by underscore.

If I remove shell settings from autostart and starts tmux manually powerline symbols work properly.

**Comment by kchibisov** [comment] 2020-04-17 10:25
Try `tmux -u` or set locale in alacritty.yml(preferred solution for now).


duplicate of  #2566

**Closed by kchibisov** 2020-04-17 10:25 UTC
