### ISSUE TITLE
Opacity setting is just making my terminal darker

### ISSUE THREAD

**Issue by Giatroo** [alacritty/alacritty#4369] opened 2020-10-30 22:58 UTC
### System

OS: Ubuntu 20.04
Version: alacritty 0.5.0 (also tried version 0.6.0-dev)
Linux/BSD: (sorry, but I don't what exactly that mean)
Windows: My `alacritty -v` output is:
```
[INFO] Welcome to Alacritty
[INFO] Configuration loaded from "/home/giatro/.config/alacritty/alacritty.yml"
libEGL warning: DRI2: failed to authenticate
[INFO] Device pixel ratio: 1
[INFO] Initializing glyph cache...
[INFO] ... finished initializing glyph cache in 0.036485274s
[INFO] Estimated DPR correctly, skipping resize
[INFO] Cell Size: 8 x 17
[INFO] Padding: 0 x 10
[INFO] Width: 696, Height: 1550
[INFO] PTY dimensions: Line(90) x Column(87)
[INFO] Initialisation complete
[INFO] Width: 696, Height: 740
```

### Description

When I set the `background_opacity` to some value like `0.2`, it just make my terminal darker, but not transparent. I looked at some other issues about the topic, but they are all closed. So I decided to open another issue about the topic to try solving my problem.

(Sorry if I filled some of those template fields incorrectly, this is my first time opening an issue)

**Comment by chrisduerr** [comment] 2020-10-30 23:40
Which window manager do you run? That sounds like you're running X11 without a compositor.

**Comment by Giatroo** [comment] 2020-10-30 23:52
I run the default from Ubuntu. I think its name is GNOME (or GNOME Shell). Do you know how can I check that?

**Comment by Giatroo** [comment] 2020-10-30 23:54
I run Ubuntu inside a Virtual Box VM. I saw some commentaries that this could lead to some problems.

**Comment by chrisduerr** [comment] 2020-10-30 23:59
> I run Ubuntu inside a Virtual Box VM. I saw some commentaries that this could lead to some problems.

Yes, that is the problem. Making this a duplicate of https://github.com/alacritty/alacritty/issues/4217.

**Closed by chrisduerr** 2020-10-30 23:59 UTC
