### ISSUE TITLE
After resume, a window with alacritty can no longer be moved to a different location on the screen

### ISSUE THREAD

**Issue by bronze51** [alacritty/alacritty#4009] opened 2020-07-21 21:07 UTC
When the system resumes after suspend, any window with alacritty in it can no longer be moved by selecting it with the mouse and dragging it.

### System

OS: Arch Linux
Version: 0.4.3
Linux/BSD: Wayland, gnome

### Logs

no crash

**Comment by chrisduerr** [comment] 2020-07-21 21:25
Can it be moved or interacted with using other methods? Also is the window itself still alive, so does it still redraw?

**Comment by bronze51** [comment] 2020-07-21 21:58
Gnome: "Move a window by dragging the titlebar, or hold down Super and drag anywhere in the window."
I cannot move by dragging the title bar. But dragging when holding down Super works!

If redrawing means that I can still interact with the shell in it, then yes.

**Comment by kchibisov** [comment] 2020-07-22 01:16
duplicate of https://github.com/alacritty/alacritty/issues/3543

**Closed by kchibisov** 2020-07-22 01:16 UTC
Labels: DS - Wayland, H - linux
