### ISSUE TITLE
Sharing the terminal window makes the text invisible

### ISSUE THREAD

**Issue by Matteoverzotti** [alacritty/alacritty#4901] opened 2021-03-17 09:27 UTC
### System

OS: Windows 10, Ubuntu WSL
Version: alacritty 0.8.0-dev (d5dd009)

When I'm on a discord call, for example, and want to share my window, the text disappears. In the image below I show what's wrong, while highlighting the "invisible" row.
![image](https://user-images.githubusercontent.com/58049266/111444718-567b9480-8713-11eb-8dc8-0c77239cc8dc.png)

**Comment by chrisduerr** [comment] 2021-03-17 11:38
Duplicate of #4855.

**Closed by chrisduerr** 2021-03-17 11:38 UTC
