### ISSUE TITLE
Sluggish When Resizing

### ISSUE THREAD

**Issue by yanzhang0219** [alacritty/alacritty#3328] opened 2020-02-12 00:45 UTC
When I resize the window by dragging my mouse on the window edge, the resizing is sluggish. See the GIF I attached below

![alacritty-resize-sluggish](https://user-images.githubusercontent.com/11582667/74292640-65f90480-4ced-11ea-9ad2-435eb9b75c4b.gif)

The edge changing cannot follow the mouse point. 

### System

OS: macOS 10.15.3
Version: alacritty 0.4.1 (4d9253b)
BTW, I installed Alacritty from brew and I haven't configured it yet. 

Any suggestions to solve this? Thank you.

**Comment by chrisduerr** [comment] 2020-02-12 20:12
Can you share your configuration file? I've tried to reproduce this on my macbook, but I wasn't able to.

**Comment by yanzhang0219** [comment] 2020-02-12 21:01
@chrisduerr I just installed it and didn't do any configuration.

**Comment by DivineGod** [comment] 2020-02-12 23:28
In reading this issue and trying out for myself with alacritty and other applications it seems retina (macbook pro laptop screen vs external 1080p) display makes the "sluggish" behavior worse. The behavior also exists on other applications I tested (Firefox, Slack, Chrome, Messages).

**Comment by yanzhang0219** [comment] 2020-02-13 03:44
@DivineGod Thanks. To clarify, my laptop is MacBook pro 15'' retina late 2013 and it drives two external monitors, one is 24'' (1920 x 1200) and the other is 27'' (3840 x 2160). Also, I have tried all these four apps you mentioned on both monitors, but all of them do not show this issue. For example, I opened Slack and then I tried to resize it by dragging its window border, but not any sluggish issues and instead the dragging was very very smooth.

**Comment by kchibisov** [comment] 2020-02-13 04:21
I feel like we're just triggering something that poor macOS OpenGL doesn't like. I do remember this issue on intel integrated graphics on a 13 inch macbooks. Or maybe macOS blocks event loop for some reason during resize and we can't redraw, but knowing that @chrisduerr doesn't have this issue on his laptop with AMD graphics, I kind of think that it's related to graphics tbh. However I can't say anything about nvidia GPU, etc, but knowing that laptop could switch both of them on the fly, maybe it decides to use intel's one.

I'm not saying that you need a decent graphics performance to run alacritty, I'm saying that bad macOS OpenGL could be the issue, since on Linux macbook's hardware performs much better, at least for me.

**Comment by yanzhang0219** [comment] 2020-02-13 04:28
@kchibisov Thank you very much for this information and it helps a lot. Probably I should update my mac someday in the future, and after all, it is already 6 years old 🤣. BTW, you are running Linux on your macbook, right? Which distro? I want to give it a shot. I am just worrying about the potential hardware drivers. Thanks!

**Comment by kchibisov** [comment] 2020-02-13 04:42
>BTW, you are running Linux on your macbook, right?

Yes, I'm running Linux on 2015 13 inch macbook. I can't speak for nvidia based systems, since they usually has hard times under Linux tbh.

> Which distro?

I'm not sure that this information make any sense, but it's Gentoo.

>I want to give it a shot. I am just worried about the potential hardware drivers. Thanks!

I guess you can boot something common like Ubuntu/Fedora from usb stick and try, but I'd say that it's very individual to your machine whether it'll run properly or not. Mine for example uses broadcom wireless module, which is absolutely horrible and due to it hibernate doesn't work (I don't need it though, but I can always remove kernel module to make things work :- ) ). Also I'd recommend to just find out folks who run it on your particular model(blogs, etc).



I still want to understand what actually could cause this issue on macOS, since we can't just say that it's "hardware problem" and don't do anything here. Maybe we're not doing something properly in terms of setting up window, etc. I feel like macOS scales window itself somehow during resize and you see this issue(maybe it thinks that we can't resize?). Since knowing our drawing code, this is literally impossible to do the thing you're showing on a gif.

**Comment by yanzhang0219** [comment] 2020-02-13 04:45
Thank you!

**Comment by chrisduerr** [comment] 2020-02-13 11:18
I've tried it on my macbook and it seems more sluggish when testing on the laptop screen directly (highdpi), rather than the other two external monitors.

However I currently don't have any mouse that can connect to it, so I'll try tomorrow again at work with a proper mouse, since everything feels sluggish with a touchpad.

**Comment by yanzhang0219** [comment] 2020-02-13 11:31
@chrisduerr Thank you. Probably this issue has the same reason as that rearranging issue I reported. Hope this issue can be fixed because I really want to use Alacritty which is incredibly fast and compact.

**Comment by chrisduerr** [comment] 2020-02-14 23:07
@jrmuizel would you mind testing the latest Alacritty master w.r.t. your jiggling issue?

@yanzhang0219 has said his problems were mostly resolved by compiling Alacritty from source.

**Comment by jrmuizel** [comment] 2020-02-14 23:18
I still have my issue when compiling master from source. I suspect it is a different issue than this one. It was never sluggish for me.

**Closed** 2020-02-14 23:20 UTC
Labels: A - needs repro, C - waiting on author, H - macos
