### ISSUE TITLE
history to a file

### ISSUE THREAD

**Issue by nagy135** [alacritty/alacritty#3289] opened 2020-02-04 21:18 UTC
I would really appreciate (if this isnt supported already) to have some keybind that would output entire history of current alacritty instance to a file. I m using my setup with keyboard exclusively, I rarely touch a mouse for hours and this one thing is missing and forces me to use mouse, and that is ability to capture output of one of commands to my clipboard....I can easily imagine scripting it (and I have many more ideas) but i need to get that output somehow...I was thinking about using tmux for this but I would guess this should be trivial to implement. Please if this sounds like good idea, please let me know

**Comment by kchibisov** [comment] 2020-02-04 21:57
duplicate of this #262 or #2568 . I guess you're more interested in #262 anyway.

**Closed by kchibisov** 2020-02-04 21:57 UTC

**Comment by nagy135** [comment] 2020-02-04 22:03
thanks for redirection

**Comment by nagy135** [comment] 2020-02-06 14:50
> duplicate of this #262 or #2568 . I guess you're more interested in #262 anyway.

I looked at those issues, and indeed that functionality would solve everything I described here. I would still like to ask you, if simple "dump to file" functionality would not be something you would like to have anyway. I can imagine all sorts of people coming up with ideas how to process history content with some scripts, we would just bind that dumping to some key and create multiple entr-triggered scripts . Its hard to implement every functionality into alacritty (as those issues clearly show), and this would be some sort of API for quick user ideas. Also it seems to be already implemented in [this branch](https://github.com/jynnantonix/alacritty/tree/v0.3.3-scrollback-search) ...we would just need to write the data to a file.

**Comment by kchibisov** [comment] 2020-02-06 14:53
I heard that #262 could show up soonish, since it's the thing @chrisduerr is working right now. So I don't see any point about adding dump to a file thing. Like you can basically select the entire scrollback with it under a second and paste to file.

**Comment by nagy135** [comment] 2020-02-06 15:05
I would like to pipe all written commands to a dmenu select and have it in clipboard, then I would like to select command (in dmenu) and obtain its output to a clipboard ...thats would be super handy, and I dont see how I could do it not except for a mouse, when output is multiple screens its annoying ...I understand your position tho, I will maintain my own branch (looking forward to #262)

**Comment by chrisduerr** [comment] 2020-02-06 16:28
@nagy135 You're probably more interested in https://github.com/alacritty/alacritty/issues/1615, than in the other issues linked so far from what I can tell.
