### ISSUE TITLE
[mac] ctrl + / not work

### ISSUE THREAD

**Issue by findNextStep** [alacritty/alacritty#4584] opened 2020-12-17 03:06 UTC
when use `crtl + /`it do nothing in alacritty,but show ^_ in kitty

### System

OS: macOS
Version: alacritty 0.6.0

**Comment by chrisduerr** [comment] 2020-12-17 03:09
Empty config? What shell?

**Comment by findNextStep** [comment] 2020-12-17 04:05
> Empty config? What shell?

in zsh and vim
here is my config https://github.com/findNextStep/mydot

**Comment by findNextStep** [comment] 2020-12-17 04:08
my config should have nothing  effect i try`zsh -d -f -i`,is same

**Comment by chrisduerr** [comment] 2020-12-17 05:12
What do you get when you run `alacritty --print-events | grep "ReceivedCharacter"` and press these keys?

**Comment by findNextStep** [comment] 2020-12-17 07:20
> What do you get when you run `alacritty --print-events | grep "ReceivedCharacter"` and press these keys?

no thing show out

**Comment by chrisduerr** [comment] 2020-12-17 21:50
Then this is a duplicate of https://github.com/alacritty/alacritty/issues/1359.

**Closed by chrisduerr** 2020-12-17 21:50 UTC
