### ISSUE TITLE
Copy URL to Clipboard on Right Click

### ISSUE THREAD

**Issue by amayer5125** [alacritty/alacritty#4063] opened 2020-08-02 01:02 UTC
I've recently switched from termite to alacritty with the release of Vi mode. The only feature I miss is right clicking on URLs would copy them to the clipboard. I've read though the alacritty.yml config to see if anything in there mentioned how this could be achieved through configuration but didn't find anything. I tried setting the right click mouse_binding to copy but it didn't have the desired effect.

**Comment by kchibisov** [comment] 2020-08-02 01:23
If you select something it should be automatically yanked to middle mouse buffer. We have a semantic selection on a double click, so if you double click on a URL it should be selected to a clipboard.The only issue could be that `:` is a part of `semantic_escape_chars`, but you may double click on `:` or remove `:` from semantic escape chars.

So at this point I don't see any value in coping url on a right click, especially knowing that right click is already being used to expand selection.

**Comment by chrisduerr** [comment] 2020-08-02 01:30
I can see *some* value in this suggestion. Being able to easily copy a URL with the mouse might be interesting, though I don't see why a URL would be more interesting to copy than any other text.

Generally the only regular interaction with a URL should be to open it with left click, I'm not sure which use case would require frequently copying a URL to paste it elsewhere. If it's just about literal text copy, then I agree with @kchibisov that the selection clipboard is probably the right thing to use and there's no need to add special handling for URLs.

In some scenarios it might also be better to replace the launcher with an application that allows you to pick what you want to do with your URL, if you frequently open URLs in different browsers for example. That is already possible though.

**Comment by amayer5125** [comment] 2020-08-02 01:47
I tried double clicking on a link to select it and it opens the link in the web browser and then highlights it. I don't believe this will work for my use case.

I do a lot of web development and thus use a few different browsers. There are times when I would like to test something in my non-default web browser or I have multiple chrome windows opened with different accounts or incognito windows.

**Comment by kchibisov** [comment] 2020-08-02 01:53
If it opens during double click it's a bug.

**Comment by kchibisov** [comment] 2020-08-02 01:55
>I tried double clicking on a link to select it and it opens the link in the web browser and then highlights it. I don't believe this will work for my use case.

It'll work if it got fixed for a case, when you don't have modifier. If you have a modifier to open urls, it won't trigger opening, ofc (that's likely why I haven't noticed it).

**Comment by kchibisov** [comment] 2020-08-02 01:59
Though, just thinking about, and having a delay on opening links, which will be equal to a double click threshold is not something some users will want. And so it's likely not entirely a bug. So I guess the option you have right now is to set a modifier key for opening urls, which should prevent double click from opening a link.

**Comment by chrisduerr** [comment] 2020-08-02 02:06
Double clicking opening URLs does open them right now and while it's not exactly *desired*, I am aware of this limitation. Though if you move your cursor during the first click, you will be able to double click on URLs without opening them.

**Comment by gvfarns** [comment] 2020-10-15 00:30
This is a subset of what I think is the real enhancement. On the linux desktop there are two clipboards: the primary selection clipboard (used with middle click) and the window manager clipboard (used with a menu that comes up when right clicking). As far as I can tell, alacritty only uses one clipboard and I miss having two. 

Using only one clipboard is like using only one monitor: plenty of people do it and it works, but it's not the best way to be productive. I don't think it makes sense to force that upon users.

**Comment by kchibisov** [comment] 2020-10-15 00:54
>This is a subset of what I think is the real enhancement. On the linux desktop there are two clipboards: the primary selection clipboard (used with middle click) and the window manager clipboard (used with a menu that comes up when right clicking). As far as I can tell, alacritty only uses one clipboard and I miss having two.

>Using only one clipboard is like using only one monitor: plenty of people do it and it works, but it's not the best way to be productive. I don't think it makes sense to force that upon users.

I don't understand about what you're talking here. Alacritty uses 2 clipboards if they are available, one is middle click paste the other is `ctrl + shift + v`, that's the same how any other terminal work out there.

This issue is completely unrelated to what you're talking about.

**Comment by gvfarns** [comment] 2020-10-15 01:34
Thanks, Kirill. That's very helpful information, and sorry for deviating from the main thrust of this discussion.

The relationship is that this enhancement discusses a different use of the right click. In frequently used terminals, right click brings up a menu with copy/paste etc. including copying the URL to the clipboard. This enhancement focuses on the treatment of URLs, but I think a better solution is a menu with the usual right click items, including "copy URL." Is that not what users generally expect when right clicking?

**Comment by kchibisov** [comment] 2020-10-15 01:36
idk, I open a frequently used xterm/urxvt and they both expand selection on right click, so 'frequently used' is a bit biased here.

**Comment by gvfarns** [comment] 2020-10-15 01:54
Agreed 100%. Expectations depend on one's history.

Note that Konsole, Gnome-Terminal, xfce-terminal, and lxterminal all have right click menus. As do almost all non-terminal applications I can think of. Web browsers, gui-based text editors, file managers, word processors, spreadsheets. I can't think of any application aside from the terminals you mention that don't bring up a menu when right clicked. 

It can be argued of course, and it is subjective. But I think there is a very strong argument for the rxvt standard of expanding selections being outmoded and that it does not conform to 2020 user expectations. New users, certainly, and any coming from other OSs or who are accustomed to using the default terminal emulator in their system.

I would be happy to create a separate issue discussing this if you think that makes more sense. Appreciate your patience.

**Comment by nixpulvis** [comment] 2020-10-15 03:33
I would not want Alacritty to ever have any kind of right click menu, and I doubt any of the other maintainers would disagree with me on this.

Also, we follow the expected semantics of the two existing clipboards. When I started learning about how they operated I was a bit confused at first too, but one is really the 'selection buffer'. You can test this by selecting some text in Firefox (for example) and the pasting it into another text input. I'm not sure I *like* the way this works exactly, but that's beyond my control, and I've learned to live with things.

A fancy clipboard manager which can deal with a stack of buffers or something would be kinda neat, but I personally haven't looked into that.

**Comment by rfs613** [comment] 2020-11-12 14:40
Currently it seems there can only be one action (with optional modifier) defined for a URL. 
It would be useful if there could be multiple actions for URLs, differentiated by modifier.

For example you might have:
- plain click to open with xdg-open
- shift-click to open with xclip (placing the URL in the clipboard)
- ctrl-click to open with a non-default browser

**Comment by kchibisov** [comment] 2020-11-12 14:51
>plain click to open with xdg-open

Well, you can use custom modifiers, but it's possible to open with whatever you launcher you provide.

> shift-click to open with xclip (placing the URL in the clipboard)

I don't understand this one, but you can double click on url to copy it on Linux/BSD or with `save_to_clipboard`, since selection is always yanked into primary clipboard(middle mouse button and with `save_to_clipboard` it'll be in normal clipboard as well).

>ctrl-click to open with a non-default browser

Not sure about this one tbqh, I think it only useful if you're doing some web development?

**Comment by rfs613** [comment] 2020-11-12 15:09
> > plain click to open with xdg-open
> 
> Well, you can use custom modifiers, but it's possible to open with whatever you launcher you provide.

Yes, the action can be configured to use whichever launcher I like... but the issue is there can only be one "trigger".
What I am suggesting is to allow having multiple triggers (via modifiers), each of which can open with a different launcher.
I have tried adding multiple "url:" blocks to the config file, this parses okay, but it seems only the last entry gets used.
 
> > shift-click to open with xclip (placing the URL in the clipboard)
> 
> I don't understand this one, but you can double click on url to copy it on Linux/BSD or with `save_to_clipboard`, since selection is always yanked into primary clipboard(middle mouse button and with `save_to_clipboard` it'll be in normal clipboard as well).

Yes, the selection is yanked, but double-clicking also seems to open the URL (which may be a bug).

> > ctrl-click to open with a non-default browser
> 
> Not sure about this one tbqh, I think it only useful if you're doing some web development?

My use case is that I have multiple browsers running, FF for personal stuff, Chromium for work.
It would be useful to be able to direct which browser opens a link.

**Comment by kchibisov** [comment] 2020-11-12 15:23
>Yes, the selection is yanked, but double-clicking also seems to open the URL (which may be a bug).

You may try holding shift or any other modifier during that, should prevent opening.

**Comment by rfs613** [comment] 2020-11-12 16:04
> You may try holding shift or any other modifier during that, should prevent opening.

Yes that does work. It would however be a nice enhancement to be able to configure several different actions to take on URLs, depending on the modifier pressed.

**Comment by faern** [comment] 2020-12-17 19:25
I would also love a way to easily copy a URL into the clipboard buffer. Holding down some modifier to temporarily disable the open action and then double clicking has the downside mentioned above that `:` is part of `semantic_escape_chars`. Editing my `semantic_escape_chars` is not optimal, and finding and double clicking on the single `:` cell is hard/makes it way slower.

Having multiple browsers is definitely not only for web developers. I have multiple browsers open all the time for different security domains. Some inside VPN tunnels, some in private mode etc. I also want to copy URLs in order to paste them over chats and things like that.

>  It would be useful if there could be multiple actions for URLs, differentiated by modifier.

This sounds like an awesome idea! I don't see any downsides as it does not collide with any existing features/bindings(?). It would make the already existing URL-detection/interaction way more flexible.

**Comment by shibumi** [comment] 2021-05-20 16:58
I think this feature can be solved via using the new alacritty hints:

```
- regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
          [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
  action: Copy
  post_processing: true
  mouse:
    enabled: true
```

I just don't know how to use Right click instead of normal click

**Comment by thithib** [comment] 2021-05-23 17:48
Thanks, that's a start! Hopefully the Hints feature can be extended to handle mouse bindings too.

**Comment by Inc0n** [comment] 2021-08-03 21:24
Hi, 
If I choose to use `command`, and had it set to `firefox`, how should I pass `--private-window` to this configuration?

**Comment by shibumi** [comment] 2021-08-03 21:41
@Inc0n I would expect something like `command: "firefox --private window"` if this doesn't work just create a script that calls firefox. Like this: `command: /usr/local/bin/my-script` and then in the script: 
```
#!/bin/bash
firefox --private-window $@
```

**Comment by Inc0n** [comment] 2021-08-05 10:25
For some reasons the first methods didn't work, but the second one is a solution.
However, before with url, it would able to configure it with program and args, but now with the current hint config, it could not work the same way.

**Comment by wungad** [comment] 2023-04-05 05:52
To bind a new command to `Shift+Click`  (e.g. `chromium --incognito`) and keep the existing `Left+Click` (default `xdg-open`), make sure that both hints are declared in the configuration, and that your declaration comes before the default one.
Here's the relevant config part:
```yaml
hints:
  enabled:
  # incognito
   - regex: "https?:[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: true
     command: { program: "chromium", args: ["--incognito"] }
     post_processing: true
     mouse:
       enabled: true
       mods: Shift
  # default
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: true
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift
```
```
$ alacritty -V
alacritty 0.12.0 (5a728195)
```

**Comment by faern** [comment] 2023-04-18 06:11
@wungad This is awesome! I just replaced chromium with `wl-copy` and achieved what I wanted.

Is there any specific reason you use different regexes for the two hints? I now used your second regex for both to make both actions available on more link types.

**Comment by wungad** [comment] 2023-05-05 22:27
No specific reason. I simply don't need any other protocol to be handled in incognito.

**Comment by kchibisov** [comment] 2023-06-12 06:09
Given that hints allow that, I'll close this issue.

**Closed by kchibisov** 2023-06-12 06:09 UTC
Labels: enhancement

**Comment by thithib** [comment] 2025-02-17 11:49
I'm sorry but I don't understand how hints solve the original issue here. How can one make right clicking on a URL copy it to the clipboard (or perform any other custom command/action)?

**Comment by kchibisov** [comment] 2025-02-17 11:56
you can read the hints section for more information on how to do that. urls are also _hints_.

**Comment by thithib** [comment] 2025-02-17 12:25
I did multiple times and I see no way to bind an action to **right** click.

**Comment by kchibisov** [comment] 2025-02-17 12:35
See https://github.com/alacritty/alacritty/issues/8486
