### ISSUE TITLE
Alacritty prints "garbage" when switching windows.

### ISSUE THREAD

**Issue by tuxiqae** [alacritty/alacritty#3229] opened 2020-01-20 09:23 UTC
Since a couple of days ago, whenever I try to switch windows (using ALT+⬅️ or ALT+➡️) Alacritty  inserts a new line to the current window (before the switch) or prints sequences such as `^[[1;3C^[[1;3C^[[1;3C^[[1;3D^[[1;3C^[[1;3C` OR `CCCDCC` .
Seems like it only prints if I'm in a blocking app inside of Alacritty -> I.E. if I am using ssh or tail -f.

Feel free to contact me if you need any help debugging this issue.

P.S. Seems like this issue doesn't happen in Terminator.

### System

OS: Linux
Version: alacritty 0.4.1
Linux/BSD: X11, i3

### Logs

> ╰─>$ alacritty --print-events
> Created log file at "/tmp/Alacritty-4733.log"
> [2020-01-20 11:00] [INFO] Welcome to Alacritty
> [2020-01-20 11:00] [INFO] Configuration loaded from "/home/\<REDACTED\>/.config/alacritty/alacritty.yml"
> libEGL warning: DRI2: failed to authenticate
> [2020-01-20 11:00] [INFO] Device pixel ratio: 1
> [2020-01-20 11:00] [INFO] Initializing glyph cache...
> [2020-01-20 11:00] [INFO] ... finished initializing glyph cache in 0.060764953s
> [2020-01-20 11:00] [INFO] Cell Size: 9 x 17
> [2020-01-20 11:00] [INFO] Padding: 2 x 2
> [2020-01-20 11:00] [INFO] Width: 800, Height: 600
> [2020-01-20 11:00] [INFO] PTY Dimensions: Line(35) x Column(88)
> [2020-01-20 11:00] [INFO] Initialisation complete
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(Init)
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: Destroyed }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Resized(LogicalSize { width: 1806.0, height: 928.0 }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Moved(LogicalPosition { x: 55.0, y: 95.0 }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: (empty) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(true) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: (empty) } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(58720258))))
> [2020-01-20 11:00] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(58720269))))
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] Width: 1806, Height: 928
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 991, tv_nsec: 954278164 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Title("fish /home/\<REDACTED\>"))
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Title("fish /home/\<REDACTED\>"))
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 992, tv_nsec: 41055047 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: (empty) }) }
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged(ALT) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 992, tv_nsec: 357825007 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 106, state: Pressed, virtual_keycode: Some(Right), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 992, tv_nsec: 497533033 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorLeft { device_id: DeviceId(X(DeviceId(2))) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 992, tv_nsec: 519067516 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 992, tv_nsec: 632326782 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 105, state: Pressed, virtual_keycode: Some(Left), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 56316218 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: ALT } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(true) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: ALT } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 105, state: Pressed, virtual_keycode: Some(Left), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(58720269))))
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 88143434 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(MouseCursorDirty)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 88245767 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 107564124 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Title("fish /home/\<REDACTED\>"))
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 145302054 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 158009039 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 173143337 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 105, state: Released, virtual_keycode: Some(Left), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(true) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: ALT } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 250850338 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged((empty)) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 359034101 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 993, tv_nsec: 359390241 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: (empty) }) }
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged(ALT) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 69241756 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 69503194 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 106, state: Pressed, virtual_keycode: Some(Right), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorLeft { device_id: DeviceId(X(DeviceId(2))) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 169006434 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 280621085 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 105, state: Pressed, virtual_keycode: Some(Left), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 658245505 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: ALT } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(true) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: ALT } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 105, state: Pressed, virtual_keycode: Some(Left), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(58720269))))
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 689359818 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(MouseCursorDirty)
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 702496893 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Title("fish /home/\<REDACTED\>"))
> [2020-01-20 11:00] [INFO] glutin event: UserEvent(Wakeup)
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 736059423 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 105, state: Released, virtual_keycode: Some(Left), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(true) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 228.0, y: 664.0 }, modifiers: ALT } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 761089337 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 105, state: Pressed, virtual_keycode: Some(Left), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 105, state: Released, virtual_keycode: Some(Left), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: CursorLeft { device_id: DeviceId(X(DeviceId(2))) } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 105, state: Released, virtual_keycode: Some(Left), modifiers: ALT }, is_synthetic: true } }
> [2020-01-20 11:00] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720269))), event: Focused(false) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> ^[[1;3D[2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 853162496 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 105, state: Released, virtual_keycode: Some(Left), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 994, tv_nsec: 977228005 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }) }
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged((empty)) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 995, tv_nsec: 454528464 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: (empty) }) }
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged(CTRL) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 995, tv_nsec: 644828987 }, requested_resume: None })
> [2020-01-20 11:00] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(C), modifiers: CTRL }) }
> [2020-01-20 11:00] [INFO] glutin event: MainEventsCleared
> [2020-01-20 11:00] [INFO] glutin event: RedrawEventsCleared
>

**Comment by kchibisov** [comment] 2020-01-20 09:32
This issue should be fixed upstream and is a duplicate of #3204 .

**Closed by kchibisov** 2020-01-20 09:32 UTC
