### ISSUE TITLE
Cursor changes automatically

### ISSUE THREAD

**Issue by AbhinavAchha** [alacritty/alacritty#4888] opened 2021-03-10 17:18 UTC
### System

OS: Linux
Version: 0.7.2

There is an issue wherein I have selected Beam option in cursor.
once I launch neovim the cursor changes to block and it never gets reverted even after closing nvim(not sure if its a neovim issue or alacritty).
The same issue occurs even if I change it to underline also
https://del.dog/velenimucy.txt

**Comment by nixpulvis** [comment] 2021-03-10 17:23
This is because NeoVim is changing the cursor style for you.

Closing as a duplicate of #4505.

**Closed by nixpulvis** 2021-03-10 17:23 UTC
Labels: F - duplicate
