### ISSUE TITLE
Alacritty doesn't work on Fedora 33

### ISSUE THREAD

**Issue by Iniesta8** [alacritty/alacritty#4356] opened 2020-10-27 20:28 UTC
Hi,

after upgrading Fedora 32 to 33, I cannot start alacritty anymore. I get the following errors on startup:

```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    15454 IOT instruction (core dumped)  alacritty
```

I've installed (and already reinstalled) alacritty as follows:

```
# dnf copr enable pschyska/alacritty
# dnf install alacritty
```

Am I missing any package relating wayland or something?

### System

OS: Linux Fedora 33 Workstation
Version: 0.5.0
Linux/BSD: Wayland, Gnome 3.38

**Comment by chrisduerr** [comment] 2020-10-27 20:32
Duplicate of https://github.com/alacritty/alacritty/issues/4206.

**Closed by chrisduerr** 2020-10-27 20:32 UTC

**Comment by rbjorklin** [comment] 2020-10-29 13:56
For those of you who find your way over here from #4206, building from source is easy!

```
# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install dependencies
dnf install -y libxcb-devel fontconfig-devel

# Clone Alacritty
git clone git@github.com:alacritty/alacritty.git

# Build & install Alacritty
cd alacritty
cargo build --release
cp target/release/alacritty /usr/bin/alacritty
```

**Comment by kchibisov** [comment] 2020-10-29 13:58
I've suggest using https://github.com/alacritty/alacritty/blob/master/INSTALL.md , since those are more correct.
