### ISSUE TITLE
Importing config files or color scheme files

### ISSUE THREAD

**Issue by mankinskin** [alacritty/alacritty#3914] opened 2020-07-03 14:53 UTC
Hi, I would like to be able to switch my color scheme for alacritty quickly. In vim, there is a directory with files for the color schemes, and while vim is running, I can set the colorscheme with :colorscheme <name>. Something like this would be useful to have for alacritty.

As I see it now, there only is [this page](https://github.com/alacritty/alacritty/wiki/Color-schemes) defining various color schemes for alacritty, but I would need to copy and paste them into my ~/.config/alacritty/alacritty.yml file every time I want to change my colorscheme. Is it possible to import external files into the alacritty config, so that I only have to change one line to change the color scheme?

**Comment by kchibisov** [comment] 2020-07-03 14:57
duplicate of https://github.com/alacritty/alacritty/issues/779

**Comment by kchibisov** [comment] 2020-07-03 14:58
https://github.com/alacritty/alacritty/wiki/Color-schemes#multiple-schemes this + `sed` could help you now.

**Closed by kchibisov** 2020-07-03 14:57 UTC

**Comment by mankinskin** [comment] 2020-07-03 15:14
Ah thanks
