### ISSUE TITLE
text ghosting on the background of the terminal

### ISSUE THREAD

**Issue by krispy14** [alacritty/alacritty#3719] opened 2020-05-12 10:52 UTC
<img width="701" alt="Screen Shot 2020-05-12 at 16 23 05" src="https://user-images.githubusercontent.com/55192001/81675340-66c94000-946e-11ea-999d-6f9843655f51.png">
<img width="656" alt="Screen Shot 2020-05-12 at 16 31 33" src="https://user-images.githubusercontent.com/55192001/81675346-692b9a00-946e-11ea-88ae-25cb8a8b3a53.png">
<img width="656" alt="Screen Shot 2020-05-12 at 16 34 43" src="https://user-images.githubusercontent.com/55192001/81675418-85c7d200-946e-11ea-9a85-fb8dbb69593b.png">

The text looks a lot noticeable when i am using the terminal. There is certain ghosting in the background of the terminal. I dont know what this is but i only experienced it when using alacritty.

Version: alacritty 0.4.2 (f68de37)

**Comment by kchibisov** [comment] 2020-05-12 13:27
duplicate of #889

**Closed by kchibisov** 2020-05-12 13:27 UTC
