### ISSUE TITLE
Missing application display at high resolutions

### ISSUE THREAD

**Issue by timlkelly** [alacritty/alacritty#4208] opened 2020-09-06 17:35 UTC
On a 28" monitor (3840x2160) at a certain font size Alacritty does not render roughly the bottom quarter of the screen when using ncurses applications. I have noticed this specifically in tmux and lnav. If you increase the font size, eventually the text will fill the entire application window. The first screenshot shows the display missing the bottom portion, the second when I have pressed `ctrl` + `+` to increase font size until I can see the entire application.

![Screen Shot 2020-09-06 at 12 26 30 PM](https://user-images.githubusercontent.com/8271737/92331508-ada1fd80-f03c-11ea-90b1-41108f661129.png)

![Screen Shot 2020-09-06 at 12 26 17 PM](https://user-images.githubusercontent.com/8271737/92331509-b72b6580-f03c-11ea-8c4f-aa6cfc219b71.png)

### System

OS: macOS
Version: `alacritty 0.5.0 (a6681e3)`

### Logs

The last two entries in the logs are the boundary of when the display issue occurs when zooming in/out

```
~/development ❯ alacritty -vv
Created log file at "/var/folders/k_/2cqgcwvj297fcmq8q9l__hfw0000gn/T/Alacritty-63538.log"
[2020-09-06 12:24:37.150659000] [DEBUG] Using environment locale: en_US.UTF-8
[2020-09-06 12:24:37.150825000] [INFO] Welcome to Alacritty
[2020-09-06 12:24:37.150852000] [INFO] Configuration loaded from "/Users/tim/.alacritty.yml"
[2020-09-06 12:24:37.198555000] [DEBUG] Estimated DPR: 1
[2020-09-06 12:24:37.198632000] [DEBUG] Estimated Cell Size: 6 x 14
[2020-09-06 12:24:37.198651000] [DEBUG] Estimated Dimensions: None
[2020-09-06 12:24:37.244353000] [INFO] Device pixel ratio: 1
[2020-09-06 12:24:37.247425000] [INFO] Initializing glyph cache...
[2020-09-06 12:24:37.264782000] [INFO] ... finished initializing glyph cache in 0.017204096s
[2020-09-06 12:24:37.264910000] [INFO] Cell Size: 6 x 14
[2020-09-06 12:24:37.264934000] [INFO] Padding: 5 x 5
[2020-09-06 12:24:37.264955000] [INFO] Width: 800, Height: 600
[2020-09-06 12:24:37.266756000] [INFO] PTY dimensions: Line(42) x Column(131)
[2020-09-06 12:24:37.275595000] [INFO] Initialisation complete
[2020-09-06 12:24:37.484458000] [DEBUG] New num_cols is 315 and num_lines is 124
[2020-09-06 12:24:37.491926000] [INFO] Width: 1900, Height: 1752
[2020-09-06 12:24:37.506309000] [DEBUG] New num_cols is 315 and num_lines is 149
[2020-09-06 12:24:37.529465000] [INFO] Width: 1900, Height: 2108
[2020-09-06 12:24:43.412396000] [DEBUG] New num_cols is 317 and num_lines is 149
[2020-09-06 12:24:43.419618000] [INFO] Width: 1915, Height: 2108
[2020-09-06 12:24:43.455010000] [DEBUG] New num_cols is 633 and num_lines is 149
[2020-09-06 12:24:43.468342000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:24:48.415275000] [DEBUG] unknown device status query: 1337
[2020-09-06 12:24:51.856544000] [INFO] Font size changed to Size(23) with DPR of 1
[2020-09-06 12:24:51.865540000] [DEBUG] New num_cols is 542 and num_lines is 149
[2020-09-06 12:24:51.866015000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:24:52.467889000] [INFO] Font size changed to Size(24) with DPR of 1
[2020-09-06 12:24:52.472590000] [DEBUG] New num_cols is 542 and num_lines is 139
[2020-09-06 12:24:52.472834000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:25:19.173462000] [INFO] Font size changed to Size(25) with DPR of 1
[2020-09-06 12:25:19.177707000] [DEBUG] Term::resize dimensions unchanged
[2020-09-06 12:25:19.178949000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:25:28.292018000] [INFO] Font size changed to Size(24) with DPR of 1
[2020-09-06 12:25:28.297283000] [DEBUG] Term::resize dimensions unchanged
[2020-09-06 12:25:28.297652000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:26:08.192890000] [INFO] Font size changed to Size(25) with DPR of 1
[2020-09-06 12:26:08.196255000] [DEBUG] Term::resize dimensions unchanged
[2020-09-06 12:26:08.196549000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:26:09.120163000] [INFO] Font size changed to Size(24) with DPR of 1
[2020-09-06 12:26:09.122124000] [DEBUG] Term::resize dimensions unchanged
[2020-09-06 12:26:09.122319000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:26:10.393808000] [INFO] Font size changed to Size(23) with DPR of 1
[2020-09-06 12:26:10.398146000] [DEBUG] New num_cols is 542 and num_lines is 149
[2020-09-06 12:26:10.401964000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:26:11.396577000] [INFO] Font size changed to Size(24) with DPR of 1
[2020-09-06 12:26:11.402930000] [DEBUG] New num_cols is 542 and num_lines is 139
[2020-09-06 12:26:11.410929000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:26:20.335580000] [INFO] Font size changed to Size(23) with DPR of 1
[2020-09-06 12:26:20.337537000] [DEBUG] New num_cols is 542 and num_lines is 149
[2020-09-06 12:26:20.349620000] [INFO] Width: 3810, Height: 2108
[2020-09-06 12:26:37.214618000] [DEBUG] New num_cols is 270 and num_lines is 149
[2020-09-06 12:26:37.223804000] [INFO] Width: 1900, Height: 2108
```

**Comment by kchibisov** [comment] 2020-09-06 17:38
Seems like a duplicate of https://github.com/alacritty/alacritty/issues/3695

**Closed by kchibisov** 2020-09-06 17:38 UTC

**Comment by timlkelly** [comment] 2020-09-06 17:40
Ah, yes. Sorry about that. I didn't find that issue when searching earlier.
