### ISSUE TITLE
Can't display chinese character on windows 10 ltsc

### ISSUE THREAD

**Issue by qianxinbubian** [alacritty/alacritty#3442] opened 2020-03-11 13:03 UTC
### English
- My platform is win10 ltsc and alacritty is the latest 0.4.1.
- Chinese characters are always displayed in the same color as the background and occupy the space of two English characters, but the Chinese characters cannot be seen, and it is not possible to change the background.
### 中文
- 操作系统是win10ltsc ，alacritty版本是最近的0.4.1
- 汉字显示的总是和背景颜色一样，也是占用两个英文字符的空间，但是不能看到汉字，换了几种背景也不行

**Comment by kchibisov** [comment] 2020-03-11 13:29
duplicate of #3215

**Closed by kchibisov** 2020-03-11 13:29 UTC
