### ISSUE TITLE
Freeze/crash when pasting unavailable text

### ISSUE THREAD

**Issue by siroccal** [alacritty/alacritty#5571] opened 2021-10-29 20:02 UTC
Alacritty freezes when trying to paste text that's not available anymore.

1. Open a browser like firefox or chromium and copy some text.
2. Close the browser.
3. Paste the text into alacritty.
4. It freezes completely.

### System

OS: Linux
Version: alacritty 0.9.0 (fed349aa) and alacritty 0.10.0-dev (1df7dc51)
DE: Wayland, KDE

### Logs

Crashes: freezes. clicking the close window button eventually kills it: `'./target/release/alacritty -vv' terminated by signal SIGTERM (Polite quit request)`
Font/Terminal size: `No config file found; using default`

**Comment by chrisduerr** [comment] 2021-10-31 11:20
Duplicate of https://github.com/alacritty/alacritty/issues/2453.

**Closed by chrisduerr** 2021-10-31 11:20 UTC
