### ISSUE TITLE
supports configuring multiple fonts

### ISSUE THREAD

**Issue by shenghui0779** [alacritty/alacritty#7385] opened 2023-11-23 12:28 UTC
eg: 
  family: `Iosevka,'LXGW WenKai'`

**Comment by kchibisov** [comment] 2023-11-23 12:31
Duplicate of #957

**Closed by kchibisov** 2023-11-23 12:31 UTC

**Comment by bryanme5** [comment] 2024-04-27 22:40
Actually I am not sure if its a duplicate or not, I mean, before alacritty yaml supported several fonts but now it only support one. When trying to specify another (for complete missing glyphs) it expects a string, not a sequence. 

Maybe I am wrong, i would appreciate if someone corrects me.

**Comment by bryanme5** [comment] 2024-04-27 22:41
> Duplicate of #957


Actually I am not sure if its a duplicate or not, I mean, before alacritty yaml supported several fonts but now it only support one. When trying to specify another (for complete missing glyphs) it expects a string, not a sequence.

Maybe I am wrong, i would appreciate if someone corrects me.

**Comment by chrisduerr** [comment] 2024-04-28 01:28
> before alacritty yaml supported several fonts

It never did. It just didn't complain. It always only used one font.

**Comment by Shurtu-gal** [comment] 2024-12-05 20:11
Suppose I want to use nerd fonts while also wanting support for Japanese what should be done then?
