### ISSUE TITLE
Long-running processes sometimes pop up an invisible window

### ISSUE THREAD

**Issue by chris-morgan** [alacritty/alacritty#2656] opened 2019-07-19 08:50 UTC
Windows 10 version 1903, on Alacritty 0.3.0, but I’ve just now upgraded to master. Looking at the changes since then, I don’t *think* it’ll fix this bug—looks like it’s still on the same version of winit, and there *probably* aren’t related changes. But I’ll see if it keeps happening.

Sample steps:

1. Use zsh in Ubuntu in WSL in Alacritty.

2. Have a long-running process, such as a `less` invocation pending user input or an HTTP server; I don’t *think* a terminal sitting at a zsh prompt does it, but it doesn’t seem to be a simple always-easily-reproducible thing.

3. Do things like let my laptop go to sleep or plug or unplug my low-DPI external displays.

4. Observe a dummy window appear in the task bar and Alt-Tab list: it has no icon or title or actual visible presence; AutoHotkey’s Window Spy (which I happened to have to hand) tells me it has the class “Winit Thread Event Target” (different from the main window’s class “Window Class”). This fingers https://github.com/rust-windowing/winit/blob/v0.19.1/src/platform/windows/events_loop.rs#L341 for starters.

When present, this dummy window is unclosable; it ignores attempts to close it through the task bar or the Alt-Tab switcher. It does not disappear until you close the real Alacritty window (e.g. with Ctrl-D in zsh).

This is very likely a winit issue, but I figured I’d start here, here being where I’ve *experienced* it. It seems likely that Alacritty has *triggered* something with how it’s using winit. The bug might also actually be in winit. winit’s eventloop-2.0 work may fix this, who knows. It’s also possible that the bug lies with DWM or something else in Windows. I don’t know how to do something like look through all the HWNDs of a process before and after to see if anything has changed.

**Comment by chrisduerr** [comment] 2019-07-19 12:32
Can you reproduce this with one of the glutin examples? If you clone the repository, you can run it using `cargo run --example window`.

**Comment by chrisduerr** [comment] 2019-11-08 05:39
https://github.com/jwilm/alacritty/issues/2961 seems to describe a similar issue which even leads to Alacritty getting killed by Windows.

The issue has been reported upstream in https://github.com/rust-windowing/winit/issues/1265.

**Comment by chrisduerr** [comment] 2019-11-26 22:20
@chris-morgan This has been opened a long, long time ago. Could you verify that it is still broken with the 0.4.0 release?

**Comment by chris-morgan** [comment] 2019-11-26 22:25
I shall investigate this in the near future.

**Comment by chrisduerr** [comment] 2019-11-26 22:26
Awesome, thanks for the quick reply. Feel free to comment directly in the upstream issue, that should make things a little easier.

**Comment by chris-morgan** [comment] 2019-11-26 23:22
I haven’t been able to reproduce this issue within a few minutes. I suspect the new winit event loop may have incidentally fixed it.

**Comment by chris-morgan** [comment] 2019-12-17 05:27
Alas, I just now reproduced it on 0.4.1-dev (c104215) when unplugging from my external monitors. 🙁

At some point I may look into this in more detail, but it probably won’t be in the immediate future.

**Comment by chrisduerr** [comment] 2020-11-28 15:08
@chris-morgan If you can still reproduce this, we should probably move this to the winit repo? Otherwise chances are nobody is going to find and fix it. If it already got fixed, we can close this.

**Comment by chris-morgan** [comment] 2020-11-28 15:53
Yeah, I had this happen to me again a few weeks ago, and I’ve also noticed that this phantom window shows up in Zoom screen sharing window selection.

Now that Zoom offers me a good way of detecting the window’s presence, I’ll soon look into reproducing this with the glutin examples and with bare winit. Probably a few days before I make time to do that, but I’ll keep this tab open so I don’t forget.

**Comment by chrisduerr** [comment] 2020-11-28 15:57
> Now that Zoom offers me a good way of detecting the window’s presence, I’ll soon look into reproducing this with the glutin examples and with bare winit. Probably a few days before I make time to do that, but I’ll keep this tab open so I don’t forget.

Oh that's awesome, more than I ever could have wished for. Thanks!

If you happen to not get around to this, please just let me know and I'll at least open an issue upstream so someone else can investigate it.

**Comment by kpm** [comment] 2021-11-01 04:47
Hi, I'm seeing this issue on windows 20H2 after my laptop goes to sleep.  It looks like the issue in winit was fixed by pull request: https://github.com/rust-windowing/winit/pull/1977 which was merged on Aug 12.  I guess the next version of alacritty will make use of that when it is released.  Is there a dev build I can try?

https://github.com/rust-windowing/winit/issues/1265 mentions that killing and restarting windows explorer reproduces the bug.

**Comment by kpm** [comment] 2022-01-03 00:48
I have tested  v0.10.0-rc1 and it looks like if fixes this issue for me.  I haven't had any invisible windows pop up.

**Comment by chrisduerr** [comment] 2022-01-03 13:03
Thanks for letting us know.

**Closed by chrisduerr** 2022-01-03 13:03 UTC
Labels: B - bug, C - waiting on author, S - winit/glutin, A - deps, B - crash, H - windows
