### ISSUE TITLE
Alacritty thinks, that ctrl is pressed in fullscreen mode on OS X.

### ISSUE THREAD

**Issue by bilichboris** [alacritty/alacritty#3312] opened 2020-02-08 09:34 UTC
I usually navigate between workplaces on mac with ctrl+arrowkey. When alacritty is in the fullscreen mode, a hold ctrl, then press an arrow key to go to another desktop. When I return to alacritty again (reproduces every time I go back with trackpad gesture), the terminal still thinks that ctrl is pressed, so when I want to type "ls", for example, it cleares the screen instead of typing 'l'. 

### System

OS: macOS
Version: 0.4.1

### Logs
[alacritty.log](https://github.com/alacritty/alacritty/files/4173990/alacritty.log)

**Comment by kchibisov** [comment] 2020-02-08 09:36
duplicate of #3188

**Closed by kchibisov** 2020-02-08 09:36 UTC
