### ISSUE TITLE
Double-tap by touchpad on the titlebar doesn't maximize/unmaximize the window in GNOME 44, Wayland

### ISSUE THREAD

**Issue by darkblaze69** [alacritty/alacritty#7011] opened 2023-06-17 10:11 UTC
### System

OS: Arch
Version: alacritty 0.13.0-dev (ea2c39e6)
Linux/BSD: Wayland session on GNOME 44

Double-tap by touchpad on the titlebar doesn't maximize/unmaximize the window.

Instead triple-tap maximizes/unmaximized the window.

Mouse double-click works.

**Comment by kchibisov** [comment] 2023-06-24 21:37
How fast do you tap? There's no difference between touchpad and mouse from the Wayland protocol point of view, so it's a matter of speed when it comes to touchpad double tap.

**Comment by Lucksinia** [comment] 2023-06-28 21:13
That's could be related to #6983. 
I tried to check this behavior on my machine, something is weird and it's going on. But I am starting to think this is GNOME 44...
### What I mean ###
While double-tapping did not work for me, double-_clicking_ did. (and tripple-tapping to)
My speed is somewhere around 125~300ms on average.(7.78 in a second) So it should be plenty.
Double-tapping transforms cursor to move alacritty window. Same can be done with _one_ click.

### System ###
OS: Ubuntu 23.04 (Lunar Lobster)
Version: alacritty 0.12.1
Linux/BSD: Wayland with GNOME 44

### Window ###
Default config.

**Comment by kchibisov** [comment] 2023-07-11 05:08
Could someone try the latest master?

**Comment by darkblaze69** [comment] 2023-07-11 14:22
With the latest db903503df024a3f5066937fbe0272be88226738 I cannot maximize/unmaximize with touchapd at all. Even with triple tap. Previous 09c4471b4cd6b32a2de79a08c447284b62a80d54 allowed to do it at least with triple tap.

**Comment by kchibisov** [comment] 2023-07-11 14:37
Could you post `WAYLAND_DEBUG=1` from it please?

**Comment by kchibisov** [comment] 2023-07-11 14:43
I've tried with my laptop on sway and it works as it should (I see the request to get the window maximized at least) after pressing on the title bar twice.

**Comment by darkblaze69** [comment] 2023-07-11 21:05
Log with WAYLAND_DEBUG=1. Double tap and triple tap.

[wl-alacritty.log](https://github.com/alacritty/alacritty/files/12021531/wl-alacritty.log)

**Comment by kchibisov** [comment] 2023-07-12 09:09
@darkblaze69 I'd also assume that double click to select a word in alacritty doesn't work for you?

**Comment by darkblaze69** [comment] 2023-07-12 19:13
With this patch I'm able to triple tap again.
I'm sure I'm not slow with taps and doing this pretty fast and it's for sure not the 0.3 of the second. Will run debug events later.
At first I asked in mutter issue tracker and they say it's the client. https://gitlab.gnome.org/GNOME/mutter/-/issues/2669

**Comment by darkblaze69** [comment] 2023-07-12 19:22
double click to select the word works. Guys at mutter say it could be something related to CSD.

**Comment by darkblaze69** [comment] 2023-07-12 19:36
I've built with `cargo build --release`, run from `target/release/`
Here's logs:

[li-events.log](https://github.com/alacritty/alacritty/files/12032289/li-events.log)

[wl-debug.log](https://github.com/alacritty/alacritty/files/12032290/wl-debug.log)

**Comment by kchibisov** [comment] 2023-07-13 04:43
Let's start with the libinput logs
```
-event11  GESTURE_HOLD_BEGIN      +0.215s	1
 event11  GESTURE_HOLD_BEGIN      +1.368s	1
 event11  GESTURE_HOLD_BEGIN      +1.531s	1 // Double tap here
 event11  GESTURE_HOLD_BEGIN      +2.613s	1
 event11  GESTURE_HOLD_BEGIN      +2.798s	1 // Double tap here
 event11  GESTURE_HOLD_BEGIN      +3.823s	1
 event11  GESTURE_HOLD_BEGIN      +4.008s	1 // Double tap here
 event11  GESTURE_HOLD_BEGIN      +4.200s	1 // Triple tap
 event11  GESTURE_HOLD_BEGIN      +5.403s	1
 event11  GESTURE_HOLD_BEGIN      +5.588s	1 // Double tap
 event11  GESTURE_HOLD_BEGIN      +5.766s	1 // Triple tap
 event11  GESTURE_HOLD_BEGIN      +6.911s	1
 event11  GESTURE_HOLD_BEGIN      +7.111s	1 // Double tap
 event11  GESTURE_HOLD_BEGIN      +7.289s	1 // Triple tap
 event11  GESTURE_HOLD_BEGIN      +10.214s	1
 event11  GESTURE_HOLD_BEGIN      +11.132s	1
 event11  GESTURE_HOLD_BEGIN      +12.754s	1
 event11  GESTURE_HOLD_BEGIN      +13.651s	1
```

For me it looks more or less good, however let's now see what we've got on the wayland side, for grep 'wl_pointer@20.button|move|maximize`.

```
[1135579.263] wl_pointer@20.button(2744, 907047, 272, 1)
[1135579.328]  -> xdg_toplevel@35.move(wl_seat@8, 2744)
[1144375.881] wl_pointer@20.button(2761, 915854, 272, 1)
[1144375.918]  -> xdg_toplevel@35.move(wl_seat@8, 2761)
[1145720.100] wl_pointer@20.button(2768, 917182, 272, 1)
[1145720.135]  -> xdg_toplevel@35.move(wl_seat@8, 2768)
[1146965.425] wl_pointer@20.button(2775, 918427, 272, 1)
[1146965.460]  -> xdg_toplevel@35.move(wl_seat@8, 2775)
[1148190.285] wl_pointer@20.button(2782, 919637, 272, 1)
[1148190.320]  -> xdg_toplevel@35.move(wl_seat@8, 2782)
[1148588.580] wl_pointer@20.button(2787, 920014, 272, 1)
[1148588.621]  -> xdg_toplevel@35.move(wl_seat@8, 2787)
[1149762.438] wl_pointer@20.button(2794, 921217, 272, 1)
[1149762.479]  -> xdg_toplevel@35.move(wl_seat@8, 2794)
[1150146.699] wl_pointer@20.button(2799, 921580, 272, 1)
[1150146.769]  -> xdg_toplevel@35.move(wl_seat@8, 2799)
[1151278.781] wl_pointer@20.button(2806, 922725, 272, 1)
[1151278.814]  -> xdg_toplevel@35.move(wl_seat@8, 2806)
[1151641.759] wl_pointer@20.button(2811, 923102, 272, 1)
[1151641.847]  -> xdg_toplevel@35.move(wl_seat@8, 2811)
[1154566.434] wl_pointer@20.button(2828, 926028, 272, 1)
[1154746.590] wl_pointer@20.button(2829, 926084, 272, 0)
[1154746.642]  -> xdg_toplevel@35.set_maximized()
[1157114.567] wl_pointer@20.button(2850, 928568, 272, 1)
[1157293.811] wl_pointer@20.button(2851, 928631, 272, 0)
[1157293.859]  -> xdg_toplevel@35.unset_maximized()
```

We're interested in `wl_pointer@20.button` events, where they hava `1` at the end, the `1` means pressed. The second argument here is a timestamp of the events with milliseconds granularity, so by doing a `diff` between the ones adjustment ones we'll get the time between you've clicked. I'd say before that we don't rely on such a thing internally and we just use the current timestamp when we've seen event during event processing. But let's just compute the differences in time between those events.

```
[1135579.263] wl_pointer@20.button(2744, 907047, 272, 1)
[1144375.881] wl_pointer@20.button(2761, 915854, 272, 1) // 8 seconds 
[1145720.100] wl_pointer@20.button(2768, 917182, 272, 1) // 1328ms 
[1146965.425] wl_pointer@20.button(2775, 918427, 272, 1) // 1245ms
[1148190.285] wl_pointer@20.button(2782, 919637, 272, 1) // 1210 ms
[1148588.580] wl_pointer@20.button(2787, 920014, 272, 1) // 377ms double click
[1149762.438] wl_pointer@20.button(2794, 921217, 272, 1) // 1203ms
[1150146.699] wl_pointer@20.button(2799, 921580, 272, 1) // 363ms double click
[1151278.781] wl_pointer@20.button(2806, 922725, 272, 1) // 1145
[1151641.759] wl_pointer@20.button(2811, 923102, 272, 1) // 377 ms , double click
[1154566.434] wl_pointer@20.button(2828, 926028, 272, 1) // 3s
[1154746.642]  -> xdg_toplevel@35.set_maximized()
```

If you see on the wayland logs, the time between the clicks when you did double clicks were very close to 400ms. On libinput logs the time between the clicks were 150ms-200ms, this is for example what I have in wayland logs on sway and it matches libinput results on my end.

For now though, I'll try to rewrite and use the timestamps directly from the events, since they might provide better results. I'll come back to you with that eventually.

**Comment by kchibisov** [comment] 2023-07-13 09:15
@darkblaze69 do you have any GNOME extensions installed? Or maybe some extra software for touchpad/keyboard which might slow down gnome processing here? It's really odd that your libinput clicks were twice as fast as the ones on the wayland protocol messages dump.

**Comment by darkblaze69** [comment] 2023-07-13 09:51
For capturing I've disabled extensions, and I also tried booting from the fresh Arch installation.

**Comment by kchibisov** [comment] 2023-07-13 11:16
Well, I'll try to use timestamps directly and ask you to retest once everything will be in place, but I'm not sure how I could help you further after that.

**Comment by kchibisov** [comment] 2023-07-13 11:51
@darkblaze69 I think if you could collect the log in the following way, we could at least bring it to mutter, if we observe libinput deltas being way more different that what we have on wayland end

```sh
# Or cargo run --release instead of alacritty.
WAYLAND_DEBUG=1 alacritty -v > full-log.txt 2>&1
# Then in some other terminal start.
libinput debug-events --verbose >> full-log.txt
```

In the end your `full-log.txt` should contain both wayland log, libinput log, and alacritty startup log. By that we could clearly say why you have so long delays.

**Comment by darkblaze69** [comment] 2023-07-13 19:31
Here it is.
2x double taps, 2x triple taps, 2x double clicks for word select (successful) 
But the log seems not interleaved
[full-log.txt](https://github.com/alacritty/alacritty/files/12043754/full-log.txt)

Also adding another log interleaved and sorted by timestamp

[full-ts.txt](https://github.com/alacritty/alacritty/files/12043833/full-ts.txt)

**Comment by kchibisov** [comment] 2023-07-14 02:14
Ok, I brought it to gnome, nothing alacritty can really help you here to avoid tripple clicking.

See https://gitlab.gnome.org/GNOME/mutter/-/issues/2669#note_1790825

**Comment by kchibisov** [comment] 2023-07-14 02:15
I'd keep this issue opened to make upstream stack *use timestamps from events to decide on double/triple clicks*, which could give better results, but it won't eliminate triple clicks you must do.

**Comment by darkblaze69** [comment] 2023-07-15 05:58
Thanks for your thorough involvement in this issue.
As a possible example there's foot terminal for Wayland using also CSD and it works correctly with taps.

**Comment by kchibisov** [comment] 2023-07-15 06:29
There's no difference between the tap or click from the point of a wayland client application. The issue is what gnome does now and that it doesn't work with some policies of handling double clicks. In this case the issue is gnome bug, but we could work around it by changing the way we react to clicking on decorations and starting the move.

**Comment by kchibisov** [comment] 2023-07-15 08:18
You could try this branch, it should fix your issue https://github.com/alacritty/alacritty/pull/7079

**Comment by darkblaze69** [comment] 2023-07-15 14:24
Great! it works now

**Closed** 2023-09-03 23:01 UTC
Labels: C - waiting on maintainer, S - winit/glutin, DS - Wayland
