### ISSUE TITLE
Crush on Ubuntu 23.04 Wayland 

### ISSUE THREAD

**Issue by golanguage** [alacritty/alacritty#7460] opened 2023-12-26 06:33 UTC
### System

OS: Ubuntu 23.04
Version: 0.12.2
Linux: Wayland
ThinkPad E580
### Logs
```
✦ ❯ alacritty -vv
Created log file at "/tmp/Alacritty-9373.log"
[0.000004752s] [INFO ] [alacritty] Welcome to Alacritty
[0.000289168s] [INFO ] [alacritty] Version 0.12.2
[0.000341301s] [INFO ] [alacritty] Running on Wayland
[0.000907649s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.058219422s] [INFO ] [alacritty] Using EGL 1.4
[0.154931241s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.199989360s] [INFO ] [alacritty] Window scale factor: 1
[0.202769944s] [DEBUG] [alacritty] Loading "monospace" font
[0.210228585s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.230011809s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.256756737s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.279372399s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.302506892s] [INFO ] [alacritty] Running on Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)
[0.302646046s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
Error: There was an error initializing the shaders: Failed compiling shader: 
warning: queue 0x7fea70000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@28 still attached
  zwp_primary_selection_device_manager_v1@20 still attached
  wl_data_device@27 still attached
  wl_seat@24 still attached
  wl_data_device_manager@23 still attached
  wl_registry@19 still attached
warning: queue 0x556b83bdd4f0 destroyed while proxies still attached:
  wl_buffer@52 still attached
  wl_buffer@51 still attached
  wl_buffer@50 still attached
  wl_buffer@49 still attached
  wl_subsurface@44 still attached
  wl_surface@43 still attached
  wl_subsurface@42 still attached
  wl_surface@41 still attached
  wl_subsurface@40 still attached
  wl_surface@39 still attached
  wl_subsurface@38 still attached
  wl_surface@37 still attached
  wl_subsurface@36 still attached
  wl_surface@35 still attached
  xdg_wm_base@33 still attached
  xdg_activation_v1@14 still attached
  zwp_text_input_manager_v3@13 still attached
  zwp_pointer_constraints_v1@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  wl_seat@10 still attached
  wp_fractional_scale_manager_v1@9 still attached
  wp_viewporter@8 still attached
  wl_subcompositor@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
[0.329275936s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-9373.log"
Error: "Event loop terminated with code: 1"
```

**Comment by golanguage** [comment] 2023-12-26 06:36
❯ cargo run -- -vv
   Compiling alacritty v0.14.0-dev (/home/test/proj/rust/alacritty/alacritty)
   Compiling alacritty_terminal v0.20.1-dev (/home/test/proj/rust/alacritty/alacritty_terminal)
   Compiling alacritty_config v0.1.3-dev (/home/test/proj/rust/alacritty/alacritty_config)
   Compiling alacritty_config_derive v0.2.3-dev (/home/test/proj/rust/alacritty/alacritty_config_derive)
    Finished dev [unoptimized + debuginfo] target(s) in 32.29s
     Running `target/debug/alacritty -vv`
Created log file at "/tmp/Alacritty-9750.log"
[0.000057099s] [INFO ] [alacritty] Welcome to Alacritty
[0.000412602s] [INFO ] [alacritty] Version 0.14.0-dev (caf8c7fc)
[0.000487167s] [INFO ] [alacritty] Running on Wayland
[0.002012403s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.062302820s] [INFO ] [alacritty] Using EGL 1.4
[0.062768671s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.274168904s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.303598250s] [INFO ] [alacritty] Window scale factor: 1
[0.306137838s] [DEBUG] [alacritty] Loading "monospace" font
[0.317310188s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.339886334s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.362167674s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.387282938s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.415419822s] [INFO ] [alacritty] Running on Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)
[0.415566255s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 21.3.9 Amber, shader_version 4.60
[0.415623023s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.433931578s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-9750.log"
Error: Render(Shader(Compile("")))

**Comment by kchibisov** [comment] 2023-12-26 07:04
Fixed on latest rc.

**Comment by kchibisov** [comment] 2023-12-26 07:04
it's not a crash though, it's error.

**Closed by kchibisov** 2023-12-26 07:04 UTC

**Comment by golanguage** [comment] 2023-12-26 12:09
@kchibisov  
It represents on v0.13.0-rc2 and v0.14.0-dev.
I'm not sure there is any hardware or configure reason.
> it's not a crash though, it's error.
```
alacritty (b8acfda) via 🦀 v1.74.1 
❯ cargo run -- -vv
   Compiling alacritty v0.13.0-rc2 (/home/test/proj/rust/alacritty/alacritty)
   Compiling alacritty_terminal v0.20.0-rc2 (/home/test/proj/rust/alacritty/alacritty_terminal)
   Compiling alacritty_config v0.1.2-rc2 (/home/test/proj/rust/alacritty/alacritty_config)
   Compiling alacritty_config_derive v0.2.2-rc2 (/home/test/proj/rust/alacritty/alacritty_config_derive)
...


Error: Render(Shader(Compile("")))

```

**Comment by kchibisov** [comment] 2023-12-26 12:45
I'd suggest to bring it to mesa, since it fails to compile shaders without any message. I'm not into supporting amber drivers anyway.

You can try adding

```
[debug]
renderer = "gles2_pure"
```

into your config.

**Comment by golanguage** [comment] 2023-12-27 00:28
> I'd suggest to bring it to mesa, since it fails to compile shaders without any message. I'm not into supporting amber drivers anyway.
> 
> You can try adding
> 
> ```
> [debug]
> renderer = "gles2_pure"
> ```
> 
> into your config.
Not obvious different. May the Intel integrated card and driver are too old....
```
[0.060033336s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/test/.config/alacritty/alacritty.toml"
[0.160109501s] [INFO ] [alacritty] Using EGL 1.4
[0.162823300s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.359664801s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.417947703s] [INFO ] [alacritty] Window scale factor: 1
[0.421088438s] [DEBUG] [alacritty] Loading "monospace" font
[0.428524449s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.450522851s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.477984290s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.510221147s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.535765388s] [INFO ] [alacritty] Running on Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)
[0.535921709s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 21.3.9 Amber, shader_version 4.60
[0.535991799s] [INFO ] [alacritty] Using OpenGL ES 2.0 renderer
[0.570457087s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-45974.log"
Error: Render(Shader(Compile("")))
```

**Comment by kchibisov** [comment] 2023-12-27 00:33
We can work with `i915` mesa driver, it's just your issue is that it fails for some unknown reason in mesa and we have no indication. Like the issue is closed because it's a `mesa` issue or ubuntu is lacking some backports.

I'd suggest to ask mesa devs, but `amber` platform is for obsolete hardware mostly.

**Comment by golanguage** [comment] 2023-12-27 01:49
> We can work with `i915` mesa driver, it's just your issue is that it fails for some unknown reason in mesa and we have no indication. Like the issue is closed because it's a `mesa` issue or ubuntu is lacking some backports.
> 
> I'd suggest to ask mesa devs, but `amber` platform is for obsolete hardware mostly.

Thanks. Now I'm trying to learn a litter OpenGL, including what amber is.

**Comment by kchibisov** [comment] 2023-12-27 02:16
mesa amber is a https://docs.mesa3d.org/amber.html thing.

**Comment by golanguage** [comment] 2023-12-27 03:02
```
dpkg -l |rg -i amber
sudo apt remove libegl-amber0
sudo apt remove libgl1-amber-dri
```
Now alacritty is working! 
It is great!

Thanks @kchibisov

**Comment by kchibisov** [comment] 2023-12-27 03:19
is it still hardware accelerated though in `alacritty -vv`?

**Comment by golanguage** [comment] 2023-12-27 03:47
Yes, I think.
```
❯ cargo run -- -vv
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/alacritty -vv`
Created log file at "/tmp/Alacritty-63926.log"
[0.000060623s] [INFO ] [alacritty] Welcome to Alacritty
[0.000519805s] [INFO ] [alacritty] Version 0.14.0-dev (187f9ca3)
[0.000602079s] [INFO ] [alacritty] Running on Wayland
[0.001714026s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.117261680s] [INFO ] [alacritty] Using EGL 1.5
[0.117565612s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.280464720s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.314654997s] [INFO ] [alacritty] Window scale factor: 1
[0.320398514s] [DEBUG] [alacritty] Loading "monospace" font
[0.328978908s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.349411237s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.372865854s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.396111338s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.421636758s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics 620 (KBL GT2)
[0.421791644s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.1 - kisak-mesa PPA, shader_version 4.60
[0.421878555s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.458567763s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.459279499s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.522850756s] [INFO ] [alacritty] Cell size: 9 x 18
[0.523027384s] [INFO ] [alacritty] Padding: 0 x 0
[0.523091709s] [INFO ] [alacritty] Width: 800, Height: 600
[0.523386891s] [INFO ] [alacritty] PTY dimensions: 33 x 88
[0.534135530s] [INFO ] [alacritty] Initialisation complete
[0.651126579s] [INFO ] [alacritty] Font size changed to 15.0 px
[0.651316651s] [INFO ] [alacritty] Cell size: 9 x 18
[0.782917552s] [INFO ] [alacritty] Padding: 0 x 0
[0.783101407s] [INFO ] [alacritty] Width: 800, Height: 600
[0.790104525s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Light, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.791262293s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO | COLOR, render_mode: "Mono", lcd_filter: 1 }

```

**Comment by kchibisov** [comment] 2023-12-27 03:49
yeah, looks fine, cheers.
