### ISSUE TITLE
`startup_mode: Maximized` in Windows is `Fullscreen` when `decorations: none`

### ISSUE THREAD

**Issue by ellipticaldoor** [alacritty/alacritty#5507] opened 2021-09-23 09:35 UTC
### System
OS: Windows 10
Version: alacritty 0.9.0 (fed349a)

I have the following config on windows

```yml
window:
  decorations: none
  startup_mode: Maximized
```
If decorations is none and startup_mode is Maximized then it behaves like it's full screen.

I think this is a bug, even if there are no decorations I will expect the window to not go fullscreen and cover the taskbar

**Comment by chrisduerr** [comment] 2021-09-23 11:37
Duplicate of https://github.com/alacritty/alacritty/issues/3784.

**Closed by chrisduerr** 2021-09-23 11:37 UTC
