### ISSUE TITLE
Spawning with properties fail on AwesomeWM

### ISSUE THREAD

**Issue by Matows** [alacritty/alacritty#3575] opened 2020-04-10 21:34 UTC
### System

OS: Archlinux
Version: 0.4.2
Linux: X11, AwesomeWM

### Issue

I'm trying to spawn Alacritty with the following properties on AwesomeWM : 
`{floating=true, placement=awful.placement.centered, titlebars_enabled=false, ontop=true}`

But instead of spawning, it just doesn't show up or appears as a normal (tiled) window.

The whole command I tried : 
`echo 'awful.spawn("alacritty -e ncpamixer", {floating=true,placement=awful.placement.centered,titlebars_enabled=false,ontop=true})' | awesome-client`

According to users of AwesomeWM in [this Reddit thread](https://www.reddit.com/r/awesomewm/comments/fvzfq9/spawn_floating_terminal_wont_work/), I can use *rules* to achieve the behavior I want, but It seems a little bit dirty to me.

Is it a bug? A feature request? Or should I just use rules instead of trying to summon with properties?

**Comment by cjpbirkbeck** [comment] 2020-04-10 22:00
I had the same issue. According to [the AwesomeWM documentation](https://awesomewm.org/doc/api/libraries/awful.spawn.html), those rules use [the startup notification spec from freedesktop.org](https://www.freedesktop.org/wiki/Specifications/startup-notification-spec/), which currently alacritty doesn't support, see #2824. So beyond write your own patch to make it work with the spec and either hope it get pulled or use your own fork, I don't think there is much else you (or I) can do.

**Comment by chrisduerr** [comment] 2020-04-11 05:20
Closing as duplicate of #2824.

**Closed by chrisduerr** 2020-04-11 05:20 UTC
