### ISSUE TITLE
Alacritty version 0.4.1 crashes on startup (assertion failed on dark_mode.rs:135:13)

### ISSUE THREAD

**Issue by leandrosansilva** [alacritty/alacritty#3380] opened 2020-02-26 10:58 UTC
### System

OS: Windows 10 (Version 1903 OS Build 18362.207)
Version: alacritty 0.4.1 (4d9253b)

### Logs

Alacritty crashes on startup, with nothing being shown other than a message:

```
panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', C:\Users\travis\.cargo\git\checkouts\winit-c2fdb27092aba5a7\d1c6506\src\platform_impl\windows\dark_mode.rs:135:13
```

I deleted my alacritty.yml to be sure it's not being caused by any custom config (I was using version 0.3.3 before, that did not crash).

**Comment by DivineGod** [comment] 2020-02-26 11:53
Duplicate of https://github.com/alacritty/alacritty/issues/3177

**Closed** 2020-02-26 12:07 UTC
Labels: F - duplicate, H - windows
