### ISSUE TITLE
feature: allow setting a titlebar suffix via config (+ env var?) to identity term emu

### ISSUE THREAD

**Issue by colemickens** [alacritty/alacritty#7363] opened 2023-11-12 22:50 UTC
I sometimes change between terminal emulators and I'd like to be able to quickly identify the term based on the window title.

Wezterm allows me to do this by running Lua when the titlebar changes, so I can modify the example and add "- wezterm" and achieve my goal.

Rio happens to just not support dynamic titlebars from what I can tell, and just leaves it as Rio, which just ends up working out for me.

Would it be possible for Alacritty to support this? I feel like it could be implemented in one or more of these ways:
* support a config file "titlebar_suffix"
* support an env var "ALACRITTY_TITLEBAR_SUFFIX"
* support a config option "titlebar_includes_program" that encodes the terminal emulator's name in the titlebar

**Comment by kchibisov** [comment] 2023-11-12 23:01
duplicate of #4436

**Closed by kchibisov** 2023-11-12 23:01 UTC
