### ISSUE TITLE
Feature request: Option to disable cursor invert when fixed cursor color is set

### ISSUE THREAD

**Issue by zapling** [alacritty/alacritty#4886] opened 2021-03-10 14:08 UTC
Basically I would like to disable the forced cursor invert introduced here https://github.com/alacritty/alacritty/pull/4031

I'm having this issue in neovim when doing a `/` search.

I could not find any solution or workaround to this, but I might have missed something?

![Screenshot_2021-03-10_15-02-05](https://user-images.githubusercontent.com/15123086/110640970-bae9a180-81b1-11eb-8cd6-5008e209c77a.png)
![Screenshot_2021-03-10_15-02-16](https://user-images.githubusercontent.com/15123086/110640972-bae9a180-81b1-11eb-9053-23bafce70435.png)

<details><summary>alacritty.yml</summary>
<p>

```
colors:
  # Default colors
  primary:
    background: '0x272727'
    # background: '0x32302f'
    foreground: '0xd5c4a1'

  cursor:
    text: '0x32302f'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x32302f'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xfbf1c7'

  indexed_colors:
    - { index: 16, color: '0xfe8019' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3c3836' }
    - { index: 19, color: '0x504945' }
    - { index: 20, color: '0xbdae93' }
    - { index: 21, color: '0xebdbb2' }
```
</p>
</details>

**Comment by chrisduerr** [comment] 2021-03-10 19:16
This is a duplicate of https://github.com/alacritty/alacritty/issues/4564. I'd personally much rather solve these issues than add an option for disabling it completely, but there doesn't seem to be a clear solution iirc.

**Closed by chrisduerr** 2021-03-10 19:16 UTC
