### ISSUE TITLE
Optimizing alacritty's startup time

### ISSUE THREAD

**Issue by mkrasnitski** [alacritty/alacritty#4393] opened 2020-11-09 03:30 UTC
I recently switched to Alacritty from URxvt after config importing was added (now I can import my pywal colors easily), and my only gripe is with the (already pretty fast) startup time. Here's a comparison between the two:

With alacritty:

     ❯ time alacritty -e true
    alacritty -e true  0.15s user 0.03s system 107% cpu 0.165 total

With URxvt:

     ❯ time urxvt -e true
    urxvt -e true  0.06s user 0.00s system 96% cpu 0.066 total

While the absolute difference here is only 0.1 seconds, relatively speaking this is a 2.5x difference in startup time that is not unnoticeable. I have a keybind to bring up a terminal, and with URxvt the window pops up before my finger has even lifted from the keyboard, which I really like. What options exist in alacritty to lazy-load or maybe skip loading certain things? If there are none, maybe this is the excuse I need to get good at Rust and contribute :) In which case, what does the startup "pipeline" look like, and what obstacles stand in the way of a faster startup time?

**Comment by kchibisov** [comment] 2020-11-09 03:34
Duplicate of  #4393.

**Closed by kchibisov** 2020-11-09 03:34 UTC

**Comment by mkrasnitski** [comment] 2020-11-09 03:37
Sorry, what? You marked my issue as a duplicate of itself...

**Comment by kchibisov** [comment] 2020-11-09 03:39
Duplicate of https://github.com/alacritty/alacritty/issues/782
