### ISSUE TITLE
Selection broken on internal retina display

### ISSUE THREAD

**Issue by georgemorgan** [alacritty/alacritty#3263] opened 2020-01-29 20:56 UTC
Selection is broken on the internal retina display of my 15" MacBook Pro. When I select a line of text, alacritty actually selects a line several lines above the line I'm trying to select. The same build of alacritty works fine on my external displays; selection works normally. Using the same build on my internal display, selection is broken.

### System

OS: macOS
Version: alacritty 0.4.2-dev (871a22e)

### Logs

```
Created log file at "/var/folders/m9/1yjm532126b_dycsd_r77m9wj47t6h/T/Alacritty-33771.log"
[2020-01-29 12:54] [INFO] Welcome to Alacritty
[2020-01-29 12:54] [INFO] Configuration loaded from "/Users/gemorgan/.config/alacritty/alacritty.yml"
[2020-01-29 12:54] [DEBUG] Estimated DPR: 2
[2020-01-29 12:54] [DEBUG] Estimated Cell Size: 12 x 24
[2020-01-29 12:54] [DEBUG] Estimated Dimensions: Some((1232, 640))
[2020-01-29 12:54] [INFO] Device pixel ratio: 2
[2020-01-29 12:54] [INFO] Initializing glyph cache...
[2020-01-29 12:54] [INFO] ... finished initializing glyph cache in 0.014733625s
[2020-01-29 12:54] [INFO] Estimated DPR correctly, skipping resize
[2020-01-29 12:54] [INFO] Cell Size: 12 x 24
[2020-01-29 12:54] [INFO] Padding: 16 x 20
[2020-01-29 12:54] [INFO] Width: 1232, Height: 640
[2020-01-29 12:54] [INFO] PTY Dimensions: Line(25) x Column(100)
[2020-01-29 12:54] [INFO] Initialisation complete
```

**Comment by kchibisov** [comment] 2020-01-29 21:02
duplicate of #3191

**Closed by kchibisov** 2020-01-29 21:02 UTC
