### ISSUE TITLE
Not running on Manjaro.

### ISSUE THREAD

**Issue by kanitsharma** [alacritty/alacritty#3308] opened 2020-02-07 07:50 UTC
Hi, I am using manjaro-gnome, I installed alacritty using snap but while starting it, it gives the following error.

```bash
$ alacritty
alacritty: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```
I have also tried installing it using pacman but to no avail.

**Comment by kchibisov** [comment] 2020-02-07 07:54
Could you try installing alacritty-git from AUR?

**Comment by kchibisov** [comment] 2020-02-07 07:55
I'm not aware that we even have snaps somewhere tbh.

**Comment by kanitsharma** [comment] 2020-02-07 07:56
Alright, I will give it a shot. But I did installed the official arch package first but It also didn't work,

**Comment by kchibisov** [comment] 2020-02-07 07:58
FYI snap is from 2018 and not maintained by us.

**Comment by kchibisov** [comment] 2020-02-07 08:02
Also, it seems like a know issue in some distros, could you check https://bugzilla.redhat.com/show_bug.cgi?id=1579464 or something similar, maybe you have odd FreeType package? I feel like it's a broken package on your system or something like that.

**Comment by kanitsharma** [comment] 2020-02-07 08:17
When I run the official arch package, here is what is gives

```bash
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {
    xmodifiers: None,
    fallbacks: [
        PotentialInputMethod {
            name: "@im=local",
            successful: Some(
                false,
            ),
        },
        PotentialInputMethod {
            name: "@im=",
            successful: Some(
                false,
            ),
        },
    ],
    _xim_servers: Err(
        GetPropertyError(
            TypeMismatch(
                0,
            ),
        ),
    ),
}', /build/.cargo/git/checkouts/winit-c2fdb27092aba5a7/d1c6506/src/platform_impl/linux/x11/mod.rs:109:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by kchibisov** [comment] 2020-02-07 08:46
Oh, this sounds familiar, what's your `locale`?

anyway, duplicate of #1574

**Closed by kchibisov** 2020-02-07 08:46 UTC
Labels: A - needs repro, C - waiting on author
