### ISSUE TITLE
Command key seems stuck.

### ISSUE THREAD

**Issue by wild-endeavor** [alacritty/alacritty#3196] opened 2020-01-12 22:42 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

Bug: The command key sometimes seems to be stuck.  After Command-Tab'ing several times back and forth between Alacritty and Chrome, typing an `m` will minimize the Alacritty window, almost as if `Command+m` was pressed (the default minimize shortcut on macos).

(This is not happening in other applications, so I highly doubt the command key is physically stuck or stuck at a software layer.)

What I would expect to happen instead: Just an `m` character appearing.

### System

OS: macOS
Version: `alacritty --version` output
`alacritty 0.4.1 (4d9253b)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
```
Created log file at "/var/folders/ft/sf65txh561s4tkbq5s6r5v7c0000gn/T/Alacritty-81379.log"
[2020-01-12 14:35] [INFO] Welcome to Alacritty
[2020-01-12 14:35] [INFO] Configuration loaded from "/Users/ytong/.config/alacritty.yml"
[2020-01-12 14:35] [DEBUG] Estimated DPR: 2
[2020-01-12 14:35] [DEBUG] Estimated Cell Size: 15 x 33
[2020-01-12 14:35] [DEBUG] Estimated Dimensions: Some((2408.0, 1592.0))
[2020-01-12 14:35] [INFO] Device pixel ratio: 2
[2020-01-12 14:35] [INFO] Initializing glyph cache...
[2020-01-12 14:35] [INFO] ... finished initializing glyph cache in 0.028440683s
[2020-01-12 14:35] [INFO] Estimated DPR correctly, skipping resize
[2020-01-12 14:35] [INFO] Cell Size: 15 x 33
[2020-01-12 14:35] [INFO] Padding: 4 x 4
[2020-01-12 14:35] [INFO] Width: 2408, Height: 1592
[2020-01-12 14:35] [INFO] PTY Dimensions: Line(48) x Column(160)
[2020-01-12 14:35] [INFO] Initialisation complete
[2020-01-12 14:35] [INFO] Font size changed to Size(25) with DPR of 2
[2020-01-12 14:35] [DEBUG] Term::resize dimensions unchanged
[2020-01-12 14:35] [INFO] Width: 2408, Height: 1592
[2020-01-12 14:36] [INFO] Goodbye
Deleted log file at "/var/folders/ft/sf65txh561s4tkbq5s6r5v7c0000gn/T/Alacritty-81379.log"
```

Keyboard and bindings: `alacritty --print-events`
log file attached.
[Alacritty-81575.log](https://github.com/alacritty/alacritty/files/4051685/Alacritty-81575.log)

**Comment by chrisduerr** [comment] 2020-01-12 22:43
Sounds like a duplicate of https://github.com/alacritty/alacritty/issues/3188.

**Comment by wild-endeavor** [comment] 2020-01-12 22:44
Yup.  Thanks for pointing that out!

**Closed by chrisduerr** 2020-01-12 22:43 UTC
