### ISSUE TITLE
Invalid window geometry for xdg_surface

### ISSUE THREAD

**Issue by asegarra** [alacritty/alacritty#7058] opened 2023-07-06 19:30 UTC
When opening Alacritty, gnome-shell outputs a warning to the log saying that current behavior will result in client termination in the future.

### System

OS: Fedora Linux 38
Version: 0.12.1
Linux/BSD: Gnome 44.2 Wayland

### Logs

`Jul 06 15:20:53 fedora gnome-shell[2787]: Invalid window geometry for xdg_surface@45. Ignoring for now, but this will result in client termination in the future.`

This is writtent to the journal when exiting the application, probably not related but here it is just in case:

```
Jul 06 15:21:00 fedora Alacritty.desktop[29034]: warning: queue 0x7f9404000ca0 destroyed while proxies still attached:
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   zwp_primary_selection_offer_v1@4278190081 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_data_offer@4278190080 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   zwp_primary_selection_device_v1@24 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   zwp_primary_selection_device_manager_v1@20 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_data_device@23 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_seat@22 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_data_device_manager@21 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_registry@19 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]: warning: queue 0x557dd0a39080 destroyed while proxies still attached:
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_buffer@49 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_buffer@55 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_buffer@56 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_shm_pool@61 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_subsurface@44 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_surface@43 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_subsurface@42 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_surface@41 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_subsurface@40 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_surface@39 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_subsurface@38 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_surface@37 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_subsurface@36 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_surface@35 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   xdg_wm_base@33 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   xdg_activation_v1@14 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   zwp_text_input_manager_v3@13 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   zwp_pointer_constraints_v1@12 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   zwp_relative_pointer_manager_v1@11 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_seat@10 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wp_fractional_scale_manager_v1@9 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wp_viewporter@8 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_subcompositor@7 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_output@6 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_shm@5 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_compositor@4 still attached
Jul 06 15:21:00 fedora Alacritty.desktop[29034]:   wl_registry@2 still attached
```

**Comment by kchibisov** [comment] 2023-07-06 19:45
duplicate of #6184.

**Closed by kchibisov** 2023-07-06 19:45 UTC
