### ISSUE TITLE
Doesn't Open on Windows Via RDP

### ISSUE THREAD

**Issue by yerttle** [alacritty/alacritty#3865] opened 2020-06-18 14:18 UTC
Have just installed Alacritty on windows 10 (1903) via choco on an RDP session and am getting the below error:

![image](https://user-images.githubusercontent.com/30318189/85031724-ec7b9200-b176-11ea-8cd0-3d218faea4fc.png)

If I connect to the machine directly, not via RDP, Alacritty opens fine and will remain open when I connect via RDP. However new shells will still crash.

**Comment by chrisduerr** [comment] 2020-06-18 22:22
This is a duplicate of #2740 and a driver restriction we cannot do anything about.

**Closed by chrisduerr** 2020-06-18 22:22 UTC
