### ISSUE TITLE
Windows Full screen + Alt-tab not working?

### ISSUE THREAD

**Issue by p5a0u9l** [alacritty/alacritty#4485] opened 2020-11-25 17:30 UTC
I thought this might have been fixed in #2438. Just upgraded to 0.6 hoping the issue was fixed. 

When in full-screen mode, trying to Alt-tab to another window switches focus, but the full-screen alacritty window is all that's visible. 

### System

OS: Windows
Version: `alacritty 0.6.0 (04cbf76)` 

Windows: 
```
PS C:\Users\padams> [2020-11-25 09:29:31.586025400] [INFO ] [alacritty] Welcome to Alacritty
Created log file at "C:\Users\padams\AppData\Local\Temp\Alacritty-5920.log"
[2020-11-25 09:29:31.590335100] [INFO ] [alacritty] Configuration files loaded from:
[2020-11-25 09:29:31.590805400] [INFO ] [alacritty]   "C:\Users\padams\AppData\Roaming\alacritty\alacritty.yml"
[2020-11-25 09:29:31.753584500] [INFO ] [alacritty] Device pixel ratio: 1
[2020-11-25 09:29:31.804410100] [INFO ] [alacritty] Initializing glyph cache...
[2020-11-25 09:29:31.887188500] [INFO ] [alacritty] ... finished initializing glyph cache in 0.0821826s
[2020-11-25 09:29:31.887699400] [INFO ] [alacritty] Cell size: 8 x 17
[2020-11-25 09:29:31.888275000] [INFO ] [alacritty] Padding: 0 x 0
[2020-11-25 09:29:31.888691400] [INFO ] [alacritty] Width: 1024, Height: 768
[2020-11-25 09:29:31.916045100] [INFO ] [alacritty] PTY dimensions: Line(45) x Column(128)
[2020-11-25 09:29:31.922596800] [INFO ] [alacritty] Initialisation complete
[2020-11-25 09:29:31.924530600] [INFO ] [alacritty] Padding: 0 x 0
[2020-11-25 09:29:31.924530600] [INFO ] [alacritty] Width: 1024, Height: 768
```

**Comment by chrisduerr** [comment] 2020-11-25 17:32
Duplicate of https://github.com/alacritty/alacritty/issues/4072.

**Closed by chrisduerr** 2020-11-25 17:32 UTC
