### ISSUE TITLE
Wayland clipboard panic

### ISSUE THREAD

**Issue by shulcsm** [alacritty/alacritty#2771] opened 2019-09-02 13:18 UTC
On master 2f93fb34b1b237bea4d1bea67a67c7c8efe6e5dc copying from clipboard causes intermittent crashes.
Trace:
https://gist.github.com/shulcsm/61bf7b87b5f8bd5f5d705fdf1f7003ba#file-gistfile1-txt

**Comment by kchibisov** [comment] 2019-09-02 13:29
Would you mind sharing information about your setup? What's your Wayland compositor ( e.g. `sway`) and distro? Which clipboard (primary(mouse)/selection(`Ctrl+Shift+C`)) causes panic? Also would you mind reproducing the issue with `RUST_BACKTRACE=1 WAYLAND_DEBUG=1 alacritty`.

**Comment by shulcsm** [comment] 2019-09-02 13:47
> Would you mind sharing information about your setup? What's your Wayland compositor ( e.g. `sway`) and distro? Which clipboard (primary(mouse)/selection(`Ctrl+Shift+C`)) causes panic? Also would you mind reproducing the issue with `RUST_BACKTRACE=1 WAYLAND_DEBUG=1 alacritty`.

Ubuntu 18.04
Gnome Shell 3.28.4
Mutter 3.28.1
Caused by primary mouse selection.

I will try to reproduce with WAYLAND_DEBUG=1

**Comment by gjabell** [comment] 2019-11-25 16:35
Getting the same issue under Sway on Alpine, except with `Ctrl-Shift-C`. Running with `WAYLAND_DEBUG=client` gives the following error (full log attached):

```
[934842.877] wl_keyboard@7.key(103938, 89175265, 46, 0)
[934869.476] wl_data_source@36.send("text/plain;charset=utf-8", fd 18)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[934871.523] wl_keyboard@38.key(103938, 89175265, 46, 0)
[934909.615] wl_keyboard@7.key(103939, 89175331, 42, 0)
[934909.670] wl_keyboard@7.modifiers(103940, 4, 0, 0, 0)
[wayland-client error] A handler for wl_data_source panicked.
```

Guessing this has something to do with not being able to open the system clipboard; I have `wl-clipboard` installed, but I'm not sure if alacritty needs extra setup to hook into it.


[alacritty.txt](https://github.com/jwilm/alacritty/files/3887655/alacritty.txt)

**Comment by chrisduerr** [comment] 2019-11-25 17:27
I'm surprised you're running into this on Sway, since afaik it has been our most reliable platform regarding clipboard support.

Does the selection clipboard also cause a panic for you @gjabell, or does that work fine?

It also might be good to know which Sway version you're running and which GPU you have.

**Comment by gjabell** [comment] 2019-11-25 21:25
Looks like mouse selection also causes a panic, oddly enough I couldn't get it to panic when running it with `WAYLAND_DEBUG=client`, but running it normally consistently panics on selection... O.o

Running Sway v1.2 with an Intel HD Graphics 520 card

**Comment by kchibisov** [comment] 2019-11-25 21:29
@gjabell since you're getting it constantly please record with `RUST_BACKTRACE=1`.

**Comment by gjabell** [comment] 2019-11-25 21:45
Here's the output from `RUST_BACKTRACE`:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:999:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: wl_display_dispatch_queue_pending
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
[wayland-client error] A handler for wl_data_source panicked.
```

Fairly similar to the other stacktrace, not sure if there should be more output.

**Comment by kchibisov** [comment] 2019-11-25 21:47
I guess it's enough for me.

**Comment by chrisduerr** [comment] 2019-11-25 22:10
There will be more output when compiling Alacritty from source.

**Comment by varagnac** [comment] 2020-05-02 07:38
I encountered a similar error. The backtrace is similar. Of course the problem I think is totally different since in my case it was not `src/libcore/result.rs`. But I'm running alacritty with a git version alacritty 0.5.0-dev (a425fe6b)
.After `sudo mv $(which clipman) .` (I have replaced my home directory with $HOME)
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.4.0/src/threaded.rs:353:41
stack backtrace:
   0:     0x5562db569b5f - <unknown>
   1:     0x5562db43cdec - <unknown>
   2:     0x5562db569071 - <unknown>
   3:     0x5562db568bd0 - <unknown>
   4:     0x5562db5681af - <unknown>
   5:     0x5562db567d58 - <unknown>
   6:     0x5562db43a6d0 - <unknown>
   7:     0x5562db4411c2 - <unknown>
   8:     0x5562db5650a2 - <unknown>
   9:     0x5562db53e438 - <unknown>
  10:     0x5562db53e221 - <unknown>
  11:     0x7fc83fd74f6b - <unknown>
  12:     0x7fc83fd71662 - <unknown>
  13:     0x7fc83fd72ccc - wl_display_dispatch_queue_pending
  14:     0x5562db58d9fb - <unknown>
  15:     0x5562db552ac4 - <unknown>
  16:     0x5562db564b4d - <unknown>
  17:     0x5562db56687a - <unknown>
  18:     0x5562db57bc7f - <unknown>
  19:     0x5562db57edfd - <unknown>
  20:     0x7fc83fbce46f - start_thread
  21:     0x7fc83fae43d3 - clone
  22:                0x0 - <unknown>
[wayland-client error] A handler for wl_data_source panicked.
[1]    56948 abort (core dumped)  RUST_BACKTRACE=full WAYLAND_DEBUG=1 alacritty
```

In my case it was my mistake. I uninstalled https://github.com/yory8/clipman accidently, and I have a 'exec wl-paste -t text --watch clipman store' line in swaywm config. So when I try to copy anything in alacritty, wl-paste will try to pass it to a non-existent command. I don't know why this will lead to a crash, but when I reinstalled clipman everything was fixed.  This behavior is very strange, since other wayland native terminal will not crash in this situation, and I really don't think it should cause crashes.
AFAK `wl-paste` just passes the clipboard contents to `clipman`, I don't know why it will cause the crash. 
I did an experiment, just ran `wl-paste --watch abc`, ran alacritty and tried ctrl-shift-c to copy, it crashed with wl-paste outputing `Failed to spawn abc: No such file or directory`. Strangely `ls | wl-copy` won't cause alacritty to crash.

**Comment by kchibisov** [comment] 2020-05-02 07:46
Because data source died, so thing blew up and we were reading from non existing pipe or something like that.

**Comment by kchibisov** [comment] 2020-10-01 16:47
Closing, since clipboard can't panic anymore, it can die, but not panic.

**Closed by kchibisov** 2020-10-01 16:47 UTC
Labels: A - deps, B - crash, DS - Wayland, H - linux, S-clipboard
