### ISSUE TITLE
--working-directory option fails

### ISSUE THREAD

**Issue by isyq** [alacritty/alacritty#3395] opened 2020-02-28 03:37 UTC
On Windows 10, --working-directory option doesn't work for Alacritty v0.4.1.

Try: 
$ alacritty.exe --working-directory "C:\software"

It reports as:

_'\\?\C:\software'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory._

**Comment by chrisduerr** [comment] 2020-02-28 04:21
Is this with ConPTY or WinPTY? This can be found in the `alacritty -v` output.

**Comment by isyq** [comment] 2020-02-28 07:16
By setting the option **winpty_backend: false or true** in alacritty.yml, I can switch backend between ConPTY and WinPTY. I can see debug log by -v option.

Result shows both cases have this issue.

I used an old version for months, --working-directory just worked. This issue happens since I update to v0.4.1 today.

**Comment by kchibisov** [comment] 2020-02-28 07:19
Could you try to repro this issue on the latest master?

**Comment by davidhewitt** [comment] 2020-02-28 07:34
I'm pretty confident this is a duplicate of the fixed #3198

**Comment by isyq** [comment] 2020-03-02 05:11
> 
> 
> Could you try to repro this issue on the latest master?

@kchibisov , I don't know how to run from source code, I will have to wait for a next version of binary. 
@davidhewitt has got the cause, need I close this issue now or you will close it?

**Closed** 2020-03-02 05:20 UTC
Labels: C - waiting on author, F - duplicate, H - windows
