### ISSUE TITLE
Action Quit closes multiple instances

### ISSUE THREAD

**Issue by duongdominhchau** [alacritty/alacritty#3201] opened 2020-01-13 15:15 UTC
I bind `Ctrl+W` to the action `Quit`. When I open multiple instances of Alacritty and press `Ctrl+W`, it closes current instance and some previous instance too. Sometimes it closes two, sometimes it's three, and sometimes it correctly closes only the instance where I pressed `Ctrl+W`. Only some instances are closed, not all, because I tried spawned 10 instances and press `Ctrl+W`, it doesn't close all 10, only 2 to 3 each time.

### Steps to reproduce
1. Open three Alacritty instances.
2. Press the key bound to Quit action (in my case it's `Ctrl+W`)

### Expected behavior
Only one instance is closed.

### Actual behavior
Two or three instances are closed at once.

### System
* OS: Arch Linux
* Version: alacritty 0.4.1
* X11, OpenBox

**Comment by chrisduerr** [comment] 2020-01-13 16:34
Could you share the `alacritty --print-events` output of an instance that is closed illegitimately?

**Comment by duongdominhchau** [comment] 2020-01-13 17:35
Here is the command I use to start two new instances of Alacritty:
```sh
alacritty --print-events > a.txt & alacritty --print-events > b.txt
```

Let's call these instances A and B. I press `Ctrl+W` on B, then A is automatically closed too.

This is the content from A (i.e: content of `a.txt`):
```
Created log file at "/tmp/Alacritty-3290703.log"
[2020-01-14 00:24] [INFO] Welcome to Alacritty
[2020-01-14 00:24] [INFO] Configuration loaded from "/home/chau/.config/alacritty/alacritty.yml"
[2020-01-14 00:24] [INFO] Device pixel ratio: 1.25
[2020-01-14 00:24] [INFO] Initializing glyph cache...
[2020-01-14 00:24] [INFO] ... finished initializing glyph cache in 0.02031121s
[2020-01-14 00:24] [INFO] Estimated DPR correctly, skipping resize
[2020-01-14 00:24] [INFO] Cell Size: 12 x 25
[2020-01-14 00:24] [INFO] Padding: 0 x 0
[2020-01-14 00:24] [INFO] Width: 960, Height: 625
[2020-01-14 00:24] [INFO] PTY Dimensions: Line(25) x Column(80)
[2020-01-14 00:24] [INFO] Initialisation complete
[2020-01-14 00:24] [INFO] glutin event: NewEvents(Init)
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: Resized(LogicalSize { width: 768.0, height: 500.0 }) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: Moved(LogicalPosition { x: 255.2, y: 110.4 }) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 548.0, y: 287.2 }, modifiers: (empty) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: Focused(true) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 548.0, y: 287.2 }, modifiers: (empty) } }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(81788932))))
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] Width: 960, Height: 625
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22435, tv_nsec: 827853251 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22435, tv_nsec: 832130522 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 293291566 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 298833771 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 335864688 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 337363977 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 337741112 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 338014803 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 348610037 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 348931142 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: (empty) }) }
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged(CTRL) }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 105292788 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 105873752 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 17, state: Pressed, virtual_keycode: Some(W), modifiers: CTRL }) }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 168824862 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 17, state: Pressed, virtual_keycode: Some(W), modifiers: CTRL }, is_synthetic: false } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788932))), event: ReceivedCharacter('\u{17}') }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 169236728 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Exit)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: LoopDestroyed
[2020-01-14 00:24] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-3290703.log"
```

And this is from B:
```
Created log file at "/tmp/Alacritty-3290704.log"
[2020-01-14 00:24] [INFO] Welcome to Alacritty
[2020-01-14 00:24] [INFO] Configuration loaded from "/home/chau/.config/alacritty/alacritty.yml"
[2020-01-14 00:24] [INFO] Device pixel ratio: 1.25
[2020-01-14 00:24] [INFO] Initializing glyph cache...
[2020-01-14 00:24] [INFO] ... finished initializing glyph cache in 0.020283198s
[2020-01-14 00:24] [INFO] Estimated DPR correctly, skipping resize
[2020-01-14 00:24] [INFO] Cell Size: 12 x 25
[2020-01-14 00:24] [INFO] Padding: 0 x 0
[2020-01-14 00:24] [INFO] Width: 960, Height: 625
[2020-01-14 00:24] [INFO] PTY Dimensions: Line(25) x Column(80)
[2020-01-14 00:24] [INFO] Initialisation complete
[2020-01-14 00:24] [INFO] glutin event: NewEvents(Init)
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: Resized(LogicalSize { width: 768.0, height: 500.0 }) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: Moved(LogicalPosition { x: 255.2, y: 110.4 }) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 548.0, y: 287.2 }, modifiers: (empty) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: Focused(true) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 548.0, y: 287.2 }, modifiers: (empty) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorLeft { device_id: DeviceId(X(DeviceId(2))) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: Focused(false) }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(79691780))))
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] Width: 960, Height: 625
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22435, tv_nsec: 821285222 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22435, tv_nsec: 832242144 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 234402014 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 248878281 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 294182915 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 295683047 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 296116137 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 296300841 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 298831836 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22436, tv_nsec: 299151944 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: (empty) }) }
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged(CTRL) }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 105010116 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 17, state: Pressed, virtual_keycode: Some(W), modifiers: CTRL }) }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 168412210 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 548.0, y: 287.2 }, modifiers: CTRL } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 17, state: Released, virtual_keycode: Some(W), modifiers: CTRL }, is_synthetic: true } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: true } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: Focused(false) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: Focused(true) }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 548.0, y: 287.2 }, modifiers: CTRL } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 17, state: Pressed, virtual_keycode: Some(W), modifiers: CTRL }, is_synthetic: true } }
[2020-01-14 00:24] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(79691780))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: true } }
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 22437, tv_nsec: 188976935 }, requested_resume: None })
[2020-01-14 00:24] [INFO] glutin event: UserEvent(Exit)
[2020-01-14 00:24] [INFO] glutin event: MainEventsCleared
[2020-01-14 00:24] [INFO] glutin event: RedrawEventsCleared
[2020-01-14 00:24] [INFO] glutin event: LoopDestroyed
[2020-01-14 00:24] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-3290704.log"
```

**Comment by chrisduerr** [comment] 2020-01-13 17:39
This is a duplicate of #3109, which has a pretty simple patch. I'll create a PR in a second, hopefully that should fix it.

**Closed by chrisduerr** 2020-01-13 17:39 UTC
