### ISSUE TITLE
[Wayland] Crash when resizing window too small

### ISSUE THREAD

**Issue by b0o** [alacritty/alacritty#2895] opened 2019-10-19 11:27 UTC
Under Wayland, Alacritty crashes consistently when resized below approximately 160px in either height or width. Setting `WINIT_UNIX_BACKEND=x11` prevents this crash.  

```
alacritty 0.3.3 (a75e949)
sway v1.2 (wlroots v0.8.1)
Linux 5.3.6-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 11 18:28:05 UTC 2019 GNU/Linux
```

```
$ RUST_BACKTRACE=full ./target/debug/alacritty
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
wl_drm@43: error 2: invalid name
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1084:5
stack backtrace:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1084:5
   0:     0x55c0b16bc5db - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55c0b16bc5db - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55c0b16bc5db - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55c0b16bc5db - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55c0b16bc5db - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x55c0b16bc2b6 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x55c0b16bcd4d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55c0b16bc8d2 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55c0b16bc7b6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55c0b16ddf0d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x55c0b16de007 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x55c0b13bd340 - core::result::Result<T,E>::unwrap::h4dcad5a74d687370
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12:     0x55c0b138b6c6 - <wayland_client::<impl calloop::sources::EventSource for wayland_client::event_queue::EventQueue>::make_dispatcher::Dispatcher as calloop::sources::EventDispatcher<Data>>::ready::h9ba56154af651043
                               at /home/maddy/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.23.6/src/lib.rs:283
  13:     0x55c0b06c8f24 - calloop::loop_logic::EventLoop<Data>::dispatch_events::hc2d0667b049653c8
                               at /home/maddy/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.4.4/src/loop_logic.rs:157
  14:     0x55c0b06c92a4 - calloop::loop_logic::EventLoop<Data>::dispatch::hb8605920283728db
                               at /home/maddy/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.4.4/src/loop_logic.rs:189
  15:     0x55c0b072c3e5 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::hace73442d1cf28e0
                               at /home/maddy/.cargo/git/checkouts/winit-c2fdb27092aba5a7/08cb950/src/platform_impl/linux/wayland/event_loop.rs:568
  16:     0x55c0b0849196 - winit::platform_impl::platform::EventLoop<T>::run_return::h6625450b5bcefdc0
                               at /home/maddy/.cargo/git/checkouts/winit-c2fdb27092aba5a7/08cb950/src/platform_impl/linux/mod.rs:609
  17:     0x55c0b0682b1c - <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return::hf8d9e40882794815
                               at /home/maddy/.cargo/git/checkouts/winit-c2fdb27092aba5a7/08cb950/src/platform/desktop.rs:43
  18:     0x55c0b089628d - alacritty::event::Processor<N>::run::h3f80de7037f69753
                               at alacritty/src/event.rs:346
  19:     0x55c0b0840bef - alacritty::run::h2cb7b869f8ab551d
                               at alacritty/src/main.rs:215
  20:     0x55c0b083f60b - alacritty::main::h3463e27e4eb6db05
                               at alacritty/src/main.rs:106
  21:     0x55c0b0723ed0 - std::rt::lang_start::{{closure}}::h85bd6445b4ffb376
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  22:     0x55c0b16bc753 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  23:     0x55c0b16bc753 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  24:     0x55c0b16c554a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  25:     0x55c0b16bd31d - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  26:     0x55c0b16bd31d - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  27:     0x55c0b16bd31d - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  28:     0x55c0b0723ea9 - std::rt::lang_start::h189ee5ac098283b4
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  29:     0x55c0b084117a - main
  30:     0x7f62b9531153 - __libc_start_main
  31:     0x55c0b05e619e - _start
  32:                0x0 - <unknown>
stack backtrace:
   0:     0x55c0b16bc5db - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55c0b16bc5db - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55c0b16bc5db - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55c0b16bc5db - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55c0b16bc5db - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x55c0b16bc2b6 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x55c0b16bcd4d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55c0b16bc8d2 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55c0b16bc7b6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55c0b16ddf0d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x55c0b16de007 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x55c0b125bb40 - core::result::Result<T,E>::unwrap::h6c590e4beefe4b98
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12:     0x55c0b11f8d1e - smithay_clipboard::threaded::clipboard_thread::h6726c953b7ff0921
                               at /home/maddy/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.3.5/src/threaded.rs:478
  13:     0x55c0b11f6b9a - smithay_clipboard::threaded::ThreadedClipboard::new_from_external::{{closure}}::h9a476f84ec6a09b7
                               at /home/maddy/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.3.5/src/threaded.rs:101
  14:     0x55c0b1265642 - std::sys_common::backtrace::__rust_begin_short_backtrace::h70e6bc59dfce0a9b
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/sys_common/backtrace.rs:77
  15:     0x55c0b1256461 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h4e8796e6bffbaa90
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/mod.rs:470
  16:     0x55c0b122f0a1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hcc4e1580b0a8275a
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:315
```

**Comment by chrisduerr** [comment] 2019-10-19 12:04
Thanks for opening a bug, I've reported it upstream in https://github.com/rust-windowing/winit/issues/1231.

**Comment by kchibisov** [comment] 2019-10-19 13:41
Whats your GPU + driver?

**Comment by b0o** [comment] 2019-10-19 14:01
@kchibisov 

I have an RX 5700 XT (Navi 10) 
```
$ lspci | grep VGA
44:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5700 / 5700 XT] (rev c1)
```

With drivers from [here](https://pkgbuild.com/~lcarlier/mesa-git/x86_64/)

```
Name            : amdvlk
Version         : 2019.Q3.6-1
Description     : AMD's standalone Vulkan driver
Architecture    : x86_64
URL             : https://github.com/GPUOpen-Drivers
Licenses        : MIT
Groups          : None
Provides        : vulkan-driver
Depends On      : None
Optional Deps   : None
Required By     : None
Optional For    : vulkan-icd-loader
Conflicts With  : None
Replaces        : None
Installed Size  : 52.08 MiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Wed 25 Sep 2019 07:02:02 AM PDT
Install Date    : Thu 26 Sep 2019 05:31:14 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum

Name            : mesa-git
Version         : 1:19.3.0_devel.116477.3ad6154f4eb-1
Description     : an open-source implementation of the OpenGL specification (git version)
Architecture    : x86_64
URL             : http://mesa3d.sourceforge.net
Licenses        : custom
Groups          : mesagit
Provides        : mesa  mesa-vdpau  libva-mesa-driver  mesa-dri  mesa-libgl  opengl-driver
Depends On      : libdrm  wayland  libxxf86vm  libxdamage  libxshmfence  libsystemd  libelf  libomxil-bellagio  libunwind  llvm-libs-git  lm_sensors  libglvnd
Optional Deps   : opengl-man-pages: for the OpenGL API man pages
Required By     : cgal  gst-plugins-base-libs  gtk3  lib32-mesa-git  libglvnd  opencl-mesa-git  qt5-base  slop  virglrenderer  wlroots  xf86-video-amdgpu-git
Optional For    : None
Conflicts With  : mesa  mesa-vdpau  libva-mesa-driver  mesa-dri  mesa-libgl
Replaces        : None
Installed Size  : 87.10 MiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Fri 18 Oct 2019 08:05:53 AM PDT
Install Date    : Sat 19 Oct 2019 03:35:32 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum

Name            : opencl-mesa-git
Version         : 1:19.3.0_devel.116477.3ad6154f4eb-1
Description     : OpenCL support for mesa drivers (git version)
Architecture    : x86_64
URL             : http://mesa3d.sourceforge.net
Licenses        : custom
Groups          : mesagit
Provides        : opencl-mesa  opencl-driver
Depends On      : mesa-git  expat  libdrm  libelf  lm_sensors  libunwind  libclc-git  clang-git
Optional Deps   : opencl-headers: headers necessary for OpenCL development
Required By     : None
Optional For    : ocl-icd
Conflicts With  : opencl-mesa
Replaces        : None
Installed Size  : 46.16 MiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Fri 18 Oct 2019 08:05:53 AM PDT
Install Date    : Sat 19 Oct 2019 03:35:55 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum

Name            : vulkan-radeon-git
Version         : 1:19.3.0_devel.116477.3ad6154f4eb-1
Description     : Radeon's Vulkan mesa driver (git version)
Architecture    : x86_64
URL             : http://mesa3d.sourceforge.net
Licenses        : custom
Groups          : mesagit
Provides        : vulkan-radeon  vulkan-driver
Depends On      : wayland  libx11  libxshmfence  libelf  libdrm  llvm-libs-git
Optional Deps   : vulkan-mesa-layer-git: a vulkan layer to display information using an overlay
Required By     : lib32-vulkan-radeon-git
Optional For    : vulkan-icd-loader
Conflicts With  : vulkan-radeon
Replaces        : None
Installed Size  : 5.96 MiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Fri 18 Oct 2019 08:05:53 AM PDT
Install Date    : Sat 19 Oct 2019 03:35:41 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum

Name            : xf86-video-amdgpu-git
Version         : 513.b467d25-1
Description     : X.org AMD video driver for the Xorg X server (git version)
Architecture    : x86_64
URL             : http://xorg.freedesktop.org/
Licenses        : custom
Groups          : xorg-drivers
Provides        : xf86-video-amdgpu
Depends On      : libdrm  systemd-tools  mesa-git
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : xorg-server<1.20.0  X-ABI-VIDEODRV_VERSION<24  X-ABI-VIDEODRV_VERSION>=25  xf86-video-amdgpu
Replaces        : None
Installed Size  : 170.00 KiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Tue 15 Oct 2019 09:36:14 PM PDT
Install Date    : Wed 16 Oct 2019 03:12:31 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum
```

**Comment by kchibisov** [comment] 2019-10-19 14:22
it seems like a problem with graphics driver honestly, since your GPU is quite new and error came from protocol. I can't repro your issue on Rx 570.

**Comment by b0o** [comment] 2019-10-19 15:08
Very possible. I wasn't able to reproduce the issue with any Qt/GTK apps, but I was able to repro with [Kitty](https://github.com/kovidgoyal/kitty) (plus another random app I found which uses winit).

**Comment by kchibisov** [comment] 2020-05-16 19:27
Since we can't do anything here, closing.

**Closed by kchibisov** 2020-05-16 19:27 UTC
Labels: A - deps, B - crash, DS - Wayland, H - linux, S - winit/glutin

**Comment by chrisduerr** [comment] 2020-05-16 19:38
Since this isn't going to be fixed in Alacritty, the best option to get this fixed is to report it to Mesa. So I've opened a bug here:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/2982

I personally can't reproduce this, so following that issue might be useful if they request some additional information.

**Comment by chrisduerr** [comment] 2020-05-18 19:11
According to the mesa bug report, this has been fixed in mesa 20. Can you confirm that this is the case @b0o?

**Comment by b0o** [comment] 2020-05-20 15:24
@chrisduerr I believe it has been fixed, but I can't confirm 100% because I'm no longer using a Navi 10 GPU.
