### ISSUE TITLE
using Alt+ i / e / n break others modifiers

### ISSUE THREAD

**Issue by 0xlkda** [alacritty/alacritty#6460] opened 2022-10-31 11:57 UTC
With default config, using Alt+ i / u / e / o / n broken other modifiers.

### System

OS: macOS
Version: alacritty 0.12.0-dev (578e0848)

### Logs
events: https://pastebin.mozilla.org/NcRf7J9c

![Alacritty-2022-10-31 at 18 49 47](https://user-images.githubusercontent.com/14184017/199002367-1203a181-5cbf-4694-95d5-2f6a181ce276.gif)

**Comment by chrisduerr** [comment] 2022-11-05 22:09
Duplicate of #62.

**Closed by chrisduerr** 2022-11-05 22:09 UTC

**Comment by suckerSlayer** [comment] 2023-02-18 08:35
For those who are struggling with this, I figure it out using a workaround way, with the help of 'karabiner.
```
  # alacritty.yml
  # - { key: N,        mods: Alt,     chars: "\x1bn"                       }
  # Tricky way to trigger Meta+n in Alacritty: Becasuse on MacOS option+n will
  # promote a "˜" and block the keyBinding proceeding, so instead use Command+n
  # to trigger Meta+n by with the help from karabiner. 
  # Karabiner will map left_option+n to left_command+n, so you don't have to
  # literally press Command+n to trigger Meta+n, just do as the natural way
  # pressing the Alt+n, and karabiner and alacritty will ensure the Meta+n
  # trigger for you.
  - { key: N,        mods: Command,     chars: "\x1bn"                       }
```
```
# alacritty_karabiner.json
{
  "title": " Alacritty",
  "rules": [
    {
      "description": "Alacritty: alt+n send command+n",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "n",
            "modifiers": {
              "mandatory": [
                "left_option"
              ],
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "n",
              "modifiers":[ 
                "left_command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "org.alacritty"
              ]
            }
          ]
        }
      ]
    }
  ]
}

```
