### ISSUE TITLE
Windows + Alacritty + Powershell multiple tmux status bars

### ISSUE THREAD

**Issue by sriramkandukuri** [alacritty/alacritty#4682] opened 2021-01-09 14:56 UTC
Hi,

I am trying to open tmux running on remote ubuntu system over ssh from powershell

Same from windows terminal works fine.
Where as from alacritty tmux session showing corrupted linefeeds and multiple status lines.

Thanks & Regards,
Sriram.K

**Comment by chrisduerr** [comment] 2021-01-09 15:00
Which TERM do you use on the remote system? Chances are you might have to update your ConPTY version.

**Comment by sriramkandukuri** [comment] 2021-01-09 15:04
Hi,

Remote system also has alacritty installed and terminfo has alacritty.
Tmux is started from xterm-256color shell

could you please help me out with steps to update ConPTY?

Thanks & Regards.
Sriram.K

**Comment by chrisduerr** [comment] 2021-01-09 15:13
The process is documented in the comments here: https://github.com/alacritty/alacritty/pull/4501#issuecomment-744058879

Please note that this requires some work to get running and isn't recommended. The recommended way to run the ConPTY is to use the broken one Microsoft provides.

Since this is likely a Windows issue though, could you try reproducing it from a Linux host?

**Comment by sriramkandukuri** [comment] 2021-01-09 15:40
Hi,

On Linux host its working fine. I have tried to open alacritty from xforwarding shell and that works fine.

But faced some other issue when running alacritty from a terminal in vnc (window manager is KDE)
```
thread 'main' panicked at 'X server has XInput extension 1.3 but does not support XInput2', <::std::macros::panic macros>:5:6
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: winit::platform_impl::platform::x11::EventLoop<T>::new
             at /home/sriram/devenv/build/alacritty/alacritty/<::std::macros::panic macros>:5
  14: winit::platform_impl::platform::EventLoop<T>::new_x11_any_thread
             at /home/sriram/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:634
  15: alacritty::main
             at /home/sriram/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:591
  16: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.43.0/src/libstd/rt.rs:67
  17: main
  18: __libc_start_main
  19: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by chrisduerr** [comment] 2021-01-09 16:33
If it works fine, then it's likely fixed by an update to the ConPTY. Sooner or later this will be rolled out through Windows updates, but since we're talking about Microsoft here it will probably take a while. I think the next update should be in May? You could also try Windows 10 Insider to see if that helps.

Should this still happen after a couple of Windows updates, or when manually switching to an updated ConPTY version, please let me know.

The XInput bug might just be due to missing packages, but is unrelated to this issue. If you need support with that please open another issue.

**Closed by chrisduerr** 2021-01-09 16:33 UTC
