### ISSUE TITLE
Alacritty loses keystrokes at random

### ISSUE THREAD

**Issue by joshholl** [alacritty/alacritty#3349] opened 2020-02-17 16:52 UTC
I currently have a frustrating situation going on where at random, certain keys arent written to the terminal when pressed. To rule out a keyboard issue, I have gone to another application and typed the same keys without issue.

In the attached logs i was attempting to type `npm` when the terminal refused to take the letter `m`. I have found that I can enter CTRL+M and it clears whatever bad state Alacritty seems to be in at the moment and allows me to once again enter text. I did enter `CTRL+M` and was able to run the command successfully.

I also have random "crashes" where the application minimizes or closes the active window and cannot be restarted without terminating its process. Given this seems to be a separate concern i will file a separate issue for that. 

### System

OS:macOS (10.15.3, Catalina)
Version: alacritty 0.4.1 (4d9253b)
Shell: ZSH 

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
[Alacritty.log](https://github.com/alacritty/alacritty/files/4214997/Alacritty.log)

**Comment by joshholl** [comment] 2020-02-17 16:53
after reading #3281 it sounds like this may be a similar situation, though I am not in vim when this occurs

**Comment by bsdps7** [comment] 2020-02-17 17:35
I can confirm this too, from macOS 10.15.3 Catalina. Alacritty seems to not register keys at times.

**Comment by kchibisov** [comment] 2020-02-17 19:29
Duplicate of #3188.

**Closed by kchibisov** 2020-02-17 19:29 UTC
