### ISSUE TITLE
Incorrect modifiers at startup on X11

### ISSUE THREAD

**Issue by SoptikHa2** [alacritty/alacritty#3708] opened 2020-05-10 09:53 UTC
### System

OS: Linux
Version: `alacritty 0.4.2`
WM: X11, i3-gaps `4.18.1 (2020-04-23)` , Picom `vgit-e553e`

### Logs
Attached is event log.
[alacritty.log](https://github.com/alacritty/alacritty/files/4605435/alacritty.log)

Video showcasing (poorly, but it is visible) what I actually do is available [here](https://soptik.tech/alacritty.ogv).

### Explanation

In the video, the newly opened terminal window is alacritty launched from i3:
```
bindsym $mod+Return exec alacritty --print-events --persistent-logging
```

When I launch the terminal window this way via i3, whenever I press a key (for example `l`), the most recent command from history that begins with that letter (in this case: `ls`) is automatically executed without me pressing anything else.

When I press `Ctrl`, the issue disappears and I can start using terminal as usual.

This issue does not appear when I launch alacritty in another way, for example by running `alacritty` in other terminal.

This issue is unique to alacritty, it doesn't occur in other terminals.

The current workaround is launching alacritty from WM with script like this:

```zsh
#!/bin/zsh
alacritty &
sleep 0.5
xte <<<"key Control_L"
```

**Comment by kchibisov** [comment] 2020-05-10 09:56
Could you try with `alacritty --config-file /dev/null`?

**Comment by SoptikHa2** [comment] 2020-05-10 09:59
I can confirm this still happens. Is there some way I can provide more information?

**Comment by kchibisov** [comment] 2020-05-10 10:04
duplicate of #3466

**Comment by kchibisov** [comment] 2020-05-10 10:09
Actually, let me open this, since you have `correct` logs showing that it's a bug, unlike the other issue.

**Comment by kchibisov** [comment] 2020-05-10 10:13
upstream bug https://github.com/rust-windowing/winit/issues/1563

**Comment by bombela** [comment] 2020-05-22 02:00
Could adding `--release` to bindsym work around the problem? That wouldn't make much sense, but maybe could help to work around the problem.

https://i3wm.org/docs/userguide.html#keybindings

Side note: i3 `exec` in a shell. Which lingers around. Wasting a bit of system resource. You can `exec` from the shell to eliminate this:
`bindsym $mod+Return exec exec alacritty --print-events --persistent-logging`

**Comment by SoptikHa2** [comment] 2020-06-04 13:57
Sorry for late reply, I somehow missed this.

Your solution works perfectly. Thanks a lot!

**Comment by kchibisov** [comment] 2020-06-04 17:29
The log shows the issues regardless of proposed solutions.

**Comment by chrisduerr** [comment] 2020-06-04 17:43
My bad, you're absolutely right. I thought the modifier issue was tracked separately. Renaming to make that clear.

**Closed** 2020-10-07 14:40 UTC
Labels: A - deps, B - bug, B - regression, DS - X11, P - high, S - winit/glutin
