### ISSUE TITLE
Afterimage in Alacritty on macos.

### ISSUE THREAD

**Issue by Oyami-Srk** [alacritty/alacritty#4502] opened 2020-11-30 14:08 UTC
### System

OS: macOS
Version: alacritty 0.6.0 (04cbf76)

![](https://ftp.bmp.ovh/imgs/2020/11/31149b0f3319bb34.png)

Those afterimage could be cleared by resize the window. But scrolling the text makes new afterimage on windows.
This bug exists at 0.4.0 the version I started using alacritty.

**Comment by chrisduerr** [comment] 2020-11-30 15:35
Duplicate of #889. Will likely be fixed with the next release.

**Closed by chrisduerr** 2020-11-30 15:35 UTC
