### ISSUE TITLE
Blocking paste freezing Alacritty

### ISSUE THREAD

**Issue by lovesegfault** [alacritty/alacritty#2453] opened 2019-05-17 05:04 UTC
# Issue
I'm on Gentoo, running Sway (and thus Wayland.) The clipboard has never really worked on Wayland, it's consistently a mess. Talks with @chrisduerr and @cmr suggested that it should be fixed on master.

Today I compiled master with rustc 1.34.2 to try, and it seems like it is still not working.

# How to reproduce
1. Running Sway (might work on other Wayland WMs?)
2. Open Firefox with `GDK_BACKEND=wayland` set.
3. Select and copy some text on Firefox.
4. Switch to another workspace where Alacritty is.
5. Paste text (ctrl+shift+v)

The result should be a freeze and eventually a crash.

On a release build I get this:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

On a debug build with backtracing I get this:
```
alacritty on  master via 𝗥 v1.34.2 [I] ➜ RUST_BACKTRACE=1 cr
   Compiling alacritty v0.3.2 (/home/bemeurer/src/alacritty/alacritty)
    Finished dev [unoptimized + debuginfo] target(s) in 7.18s
     Running `target/debug/alacritty`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/result.rs:798
  10: winit::platform::platform::wayland::keyboard::init_keyboard::{{closure}}
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/wayland/keyboard.rs:111
  11: smithay_client_toolkit::keyboard::implement_kbd::{{closure}}::{{closure}}::{{closure}}
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.5/src/keyboard/mod.rs:720


^C
```

**Comment by lovesegfault** [comment] 2019-05-17 05:08
I just realized I was running on my branch with an updated Cargo.lock. Here's the backtrace on upstream master:

```
alacritty on  remotes/upstream/HEAD via 𝗥 v1.34.2 took 1m 59s [I] ➜ RUST_BACKTRACE=1 cr
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/alacritty`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/result.rs:798
  10: winit::platform::platform::wayland::keyboard::init_keyboard::{{closure}}
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/wayland/keyboard.rs:111
  11: smithay_client_toolkit::keyboard::implement_kbd::{{closure}}::{{closure}}::{{closure}}
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.5/src/keyboard/mod.rs:720
thread 'main' panicked at 'Wayland connection lost.: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::expect
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/result.rs:825
  10: winit::platform::platform::wayland::event_loop::EventsLoop::poll_events
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/wayland/event_loop.rs:169
  11: winit::platform::platform::EventsLoop::poll_events
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/mod.rs:504
  12: winit::EventsLoop::poll_events
             at /home/bemeurer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/lib.rs:276
  13: alacritty_terminal::window::Window::poll_events
             at ./alacritty_terminal/src/window.rs:245
  14: <alacritty_terminal::event::Processor<N>>::process_events
             at ./alacritty_terminal/src/event.rs:547
  15: alacritty::run
             at alacritty/src/main.rs:221
  16: alacritty::main
             at alacritty/src/main.rs:114
  17: std::rt::lang_start::{{closure}}
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libstd/rt.rs:64
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  21: std::rt::lang_start
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libstd/rt.rs:64
  22: main
  23: __libc_start_main
             at ../csu/libc-start.c:308
  24: _start
thread 'pty reader' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /var/tmp/portage/dev-lang/rust-1.34.2/work/rustc-1.34.2-src/src/libcore/result.rs:798
  10: alacritty_terminal::window::Proxy::wakeup_event_loop
             at alacritty_terminal/src/window.rs:501
  11: alacritty_terminal::display::Notifier::notify
```

**Comment by chrisduerr** [comment] 2019-05-17 18:17
Have you tried out the Wayland clipboard support previously and it worked, or is this the first time testing?

It seems to me like the issue is due to the clipboard code causing troubles with our windowing code, even though they should be clearly separated.

Could you try checking out the commit which introduced native clipboard support and run just that commit without updating the dependencies (so build from lockfile)? Maybe an update has caused a regression here.

**Comment by lovesegfault** [comment] 2019-05-17 21:10
> Have you tried out the Wayland clipboard support previously and it worked, or is this the first time testing?

I had the latest Alacritty release before, and it did not work.

> Could you try checking out the commit which introduced native clipboard support and run just that commit without updating the dependencies (so build from lockfile)?

What commit is that?

**Comment by cole-h** [comment] 2019-05-18 01:21
> What commit is that?

Should be https://github.com/jwilm/alacritty/commit/9e89aaa477369b20a06f4b9f636d7fd543c4c985.

Additionally, can you see if installing `wl-clipboard` solves your issue? While not ideal -- installing a package for cross-client clipboard support -- it's the best Wayland has, at the moment. I currently use that and haven't had any problems with copying and pasting between Firefox and Alacritty.

**Comment by chrisduerr** [comment] 2019-05-18 05:47
I have tested this without `wl-clipboard` using just the sway compositor inside of X, so it should work properly just with a clean Sway install.

However I mainly tested copying between Alacritty instances. Does this only happen when copy/pasting between Firefox and Alacritty @lovesegfault? Or is it all applications and Alacritty, or even Alacritty and Alacritty?

**Comment by lovesegfault** [comment] 2019-05-18 10:37
@chrisduerr Between Alacritty instances it's fine. Only when copying from something else _into_ Alacritty that things go nuts.

I've recently experienced an additional case, where the paste will succeed but in a weird way. First it will freeze, for a few (20-30) seconds. Then, _sometimes_, the paste will succeed but it will paste a _bunch_ of times, and in the end there will be `<Paste><Paste><Paste><Paste><Paste><Paste>...`

Pretty weird!

**Comment by lovesegfault** [comment] 2019-05-18 10:38
@cole-h I already had `wl-clipboard` installed from the get-go.

**Comment by chrisduerr** [comment] 2019-05-18 10:39
If there's `<Paste>` at the end and it throws you into paste mode (should be shown in the status line in vim), that's a vim thing. The reason why there's multiple of those is probably because it pastes a bunch of times.

So I'd assume that should be fixed once the root cause is resolved.

**Comment by lovesegfault** [comment] 2019-05-18 10:41
@chrisduerr I've experienced the "freeze + repeated pastes" on multiple terminal applications. Namely, Vim, Neovim, Weechat, Radare2, and gopass.

**Comment by DarkDefender** [comment] 2019-05-21 09:10
@lovesegfault can you see if 0.3.2 works for you? I'm also running gentoo and also noticed that the clipboard is broken in the latest master. However, it works for me with 0.3.2.

**Comment by chrisduerr** [comment] 2019-05-21 14:24
The latest master completely reworked the clipboard, so testing 0.3.2 would not really be beneficial.

**Comment by lovesegfault** [comment] 2019-05-23 03:28
This issue seems to have disappeared with FF 67. Weird.

**Comment by trimental** [comment] 2019-06-01 13:58
@chrisduerr I was not able to replicate this issue with another gtk wayland application and @lovesegfault reports it to be fixed with FF 67. I think this was likely to have been an issue with wayland firefox. 

In that case, is this issue still active or should it be closed?

**Comment by chrisduerr** [comment] 2019-06-01 15:23
I'd say the issue was likely that FF was blocking to return the clipboard data and Alacritty reads the clipboard data synchronously in the main thread, leading to all blockages directly propagating to Alacritty.

This was already showing up with the empty clipboard previously, though that has been fixed in the Wayland library to resolve immediately.

I think it's worth to keep this issue around to track this problem, because I don't think Alacritty should crap itself, regardless of what the application at the other end of the clipboard is doing.

**Comment by mcoffin** [comment] 2019-06-08 19:31
Just FYI, if you're on a modern-ish version of firefox, the environment variable to enable wayland is `MOZ_ENABLE_WAYLAND=1` and it kinda ignores `GTK_PLATFORM`.

Someone else will know *far* better than I do, but I find `kill`ing Xwayland to be pretty useful in making sure that something isn't running under Xwayland that you think should be running natively.

**Comment by physkets** [comment] 2019-06-22 13:55
I am using Firefox 67.0.4 on Arch, with the environment variable: `GDK_BACKEND=wayland`.  
Upon copying from Alacritty and pasting in FF works, but upon copying from FF and pasting in Alacritty, it freezes, and eventually crashes, with the following:

```
$ RUST_BACKTRACE=1 alacritty
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __GI___clone
```

**Comment by chrisduerr** [comment] 2019-06-22 14:00
@physkets This should probably be reported into a separate issue, since it's completely unrelated to Alacritty freezing and likely an issue with the clipboard library.

**Comment by trimental** [comment] 2019-06-22 14:01
@physkets can you run with the env variable WAYLAND_DEBUG=1 

That would be more descriptive of the error then RUST_BACKTRACE due to it being a wayland event loop issue

**Comment by kchibisov** [comment] 2019-08-18 20:55
Can someone steel reproduce this issue on the latest master? We've pushed some changes related to wayland clipboard integration, so maybe something has changed for you?

**Comment by chrisduerr** [comment] 2019-08-20 22:06
Oh right @kchibisov, this issue was originally about something different but is now about our clipboard data being read in the main thread, which means that if the clipboard is blocking Alacritty will freeze.

As a solution we should start the clipboard in a separate thread and only insert it once the data is available. For putting things into the clipboard this is irrelevant.

I think it might make sense to wait for the event loop rework with this one though.

**Comment by NilsIrl** [comment] 2020-07-22 14:04
This has suddenly started to happen to me today. So far I have had **zero** problems with the clipboard with alacritty on wayland. I didn't upgrade or anything, just started to happen out of nowhere.

**Comment by chrisduerr** [comment] 2020-07-22 16:30
Sounds like a compositor updated might have been involved? Generally running into this should be rare, since the clipboard shouldn't take long to be read.

**Comment by NilsIrl** [comment] 2020-07-23 16:35
> Sounds like a compositor updated might have been involved? Generally running into this should be rare, since the clipboard shouldn't take long to be read.

I don't think I updated my compositor. After a reboot, everything was fixed, however during the session in which it happened, pasting into alacritty would consistently cause it to freeze. It would be very hard to reproduce.

**Comment by NilsIrl** [comment] 2020-08-03 12:18
This just happened to me again (again without any actions on my behalf, no updates, nothing).

I tried running `wl-paste` and it wouldn't return. This suggests that this problem isn't actually related to alacritty but rather either sway or Firefox.

**Comment by kaimast** [comment] 2020-10-18 21:04
I think I have the same problem on GNOME as well.

**Comment by pkulak** [comment] 2021-03-12 20:17
This just started happening to me on FF 86.0.2. No idea why. Downgrading to 86.0 fixed it.

**Comment by yavorski** [comment] 2022-03-23 15:39
This issue started to happen consistently and very often with version alacritty `0.10.1`. Never experienced it before.

**Closed** 2023-10-21 18:56 UTC
Labels: B - bug, S - clipboard
