### ISSUE TITLE
Proper support for (un)hinding on macOS

### ISSUE THREAD

**Issue by OkanEsen** [alacritty/alacritty#1465] opened 2018-07-22 02:14 UTC
After testing the latest changes in dbcb5885adb1f0b23c29838ef8dd837212322409 (#1281) I noticed, that I can't regain focus, or rather partially, of the Alacritty window after using the `CMD + H` keystroke.

~The first part shows the normal behavior and the second part, after the key stroke was pressed. You can also see, that the window action buttons also don't work anymore (keystrokes are still working though).~

**Comment by chrisduerr** [comment] 2018-07-22 09:05
Huh that behavior seems rather odd, thanks for the report. I'd assume that this is something that needs to be handled in winit/glutin.

**Comment by skibz** [comment] 2018-07-24 10:23
i've actually [had a crack](https://github.com/jwilm/alacritty/compare/master...skibz:feature-macos-show-hide) at enhancing this part of alacritty. my eventual plan is to expose a toggle option to the alacritty config, so that you may bind one key to show and hide.

once i've reached that point, i plan on exposing window coordinate options to the alacritty config, too.

i wasn't actually planning on trying to get my changes merged upstream, but if this is something that others may want/need...

**Comment by skibz** [comment] 2018-07-24 10:30
i just realised, based on the original post here, the alacritty window not being unhidden is actually a regression? did this used to work normally? if so, my work here could be kind of pointless...

**Comment by skibz** [comment] 2018-07-24 10:47
for what it's worth, i've just pushed the window visibility toggle option in my personal fork.

**Comment by jansol** [comment] 2018-07-29 05:05
Hiding the window definitely seems to break *something*. I can unhide the window again by focusing another application and then back to alacritty. However, after that only the title bar of the window seems to be clickable and the window can't be resized anymore either. Consequently, the window can only be focused by clicking on the titlebar.

**Comment by JesseFarebro** [comment] 2018-09-20 19:01
Adding to this issue, on MacOS when you launch mission control (three swipe up gesture on MBP) to expose all windows, alacritty will sometimes lose focus when clicked on from mission control.

I can also confirm this bug, when hiding alacritty there are some weird issues with focus. If you select another window then re-select alacritty (as per @jansol) it seems to work again.

**Comment by jwilm** [comment] 2018-09-21 15:29
@JesseFarebro I experience the mission control focus issue as well; it's super annoying! My workaround has been leaning on alt-tab (or is it cmd-tab?) since that doesn't trigger the focus problem. Would be nice to get this fixed for real, though.

**Comment by jansol** [comment] 2018-12-13 04:41
Noticed the mission control issue now as well. It seems that when moving focus from some other application to alacritty, alacritty itself does get focus, but its (only) window does not. There is also another very annoying case where this happens: when clicking the alacritty window after opening an URL, which shifted focus to the browser.

When alacritty was focused but not in the foreground it does come to the front when focused again in mission control. Likely some deficiency in winit's handling of `makeKey{AndOrderFront}`.

**Comment by nixpulvis** [comment] 2019-10-19 03:52
Just for reference, since (while this bug still persists) some details have changed in the behavior since some commenters above have posted:

https://github.com/jwilm/alacritty/issues/2891#issuecomment-543958230

**Comment by bfqrst** [comment] 2019-11-25 09:33
As of the latest post 0.3.3 releases including RC5 I'm not able to restore the window after doing a Command + H on macOS. The workarounds mentioned [here](https://github.com/jwilm/alacritty/issues/2891#issuecomment-543958230) don't seem to work anymore. Since Command + H is somewhat muscle memory with most macOS users, unfortunately this is a step back.

**Comment by chrisduerr** [comment] 2020-01-19 23:46
The PR to support this has just landed upstream, we're now just waiting for a new release.

**Closed** 2020-02-07 13:44 UTC
Labels: A - deps, H - macos, S - winit/glutin

**Comment by shedali** [comment] 2020-02-11 16:18
just built the latest and confirm that it works on OS X Catalina 10.15.3 👍

**Comment by ovitente** [comment] 2020-02-12 09:33
Mac os Mojave.
Alacritty ver: `alacritty 0.4.1 (4d9253b)`

**The issue is not fixed.**

I am using SimpleFullScreen Mode. And when I press CMD+H - it dissapears and cannot be restored in any previous solutions from previous duplicated issues.
Only killing the process.

**Comment by jansol** [comment] 2020-02-12 11:47
@ovitente as you can see above, the fix for this was just merged into the master branch less than a week ago. You are using the current stable release version, which is way older than that and does not have the fix discussed here. The fix will be in the next stable release.

**Comment by ovitente** [comment] 2020-02-13 11:35
@jansol Thank you for clarifying this, I haven't noticed this fact.

Btw, I have moved whole my really custom workflow with tmux, ranger, vim to Alacritty, and I want to ask, what can I do for you, developers as very active user to help you do it better?

**Comment by chrisduerr** [comment] 2020-02-13 12:39
> Btw, I have moved whole my really custom workflow with tmux, ranger, vim to Alacritty, and I want to ask, what can I do for you, developers, as very active user (not dev), to help you do it better?

I'm not sure what you're trying to say? Are you saying that Alacritty does not support something properly and you're asking us to change that?

Also I'd be surprised if your *really custom* workflow is that unusual.

**Comment by daern91** [comment] 2020-02-13 16:06
@chrisduerr, I'm quite sure @ovitente is simply asking if there is anything that he can do, "as a very active user", to support you in your work.

**Comment by ovitente** [comment] 2020-02-13 16:29
@chrisduerr 

> I'm not sure what you're trying to say? Are you saying that Alacritty does not support something properly and you're asking us to change that?

>Also I'd be surprised if your really custom workflow is that unusual.

No))
But, compared to other developers that I personally know, or my teammates, my workflow sometimes is more effective than a regular approach, where people don't try to use the power of several tools working together, like Alacritty, vim, tmux, ranger. Or analogs.

So I am really grateful for this terminal emulator, it made my work much smoother and nicer, so I can get more joy from my work. That's why I am interested to help you with something I can do. Test some use cases or compatibility with some features of tmux, ranger, vim, etc.
Thank you)

**Comment by chrisduerr** [comment] 2020-02-13 17:07
The best help you can give as a non-dev is probably just to test things out. There are a few people that don't actively contribute with code but give great feedback on patches, changes to documentation or regularly report bugs and issues with Alacritty. All of that helps tremendously, even though they make no active code contributions.

**Comment by nixpulvis** [comment] 2020-02-14 17:23
@ovitente im a collaborator for Alacritty who probably helps out mostly by running the master branch and checking for bugs in new features or strange functionality.

**Comment by ovitente** [comment] 2020-02-17 16:21
@nixpulvis I would like to help you with that too because I am interested in making alacritty much better.
I already have found one odd issue with mapped cmd key _(sometimes it keeps sending pressed state)_ with the latest build but didn't start looking for this issue here. maybe it exists)

So how can i contact with you? Maybe you already have a place for sharing such bits of knowledge about issues, maybe slack or telegram? Before posting it here.

**Comment by chrisduerr** [comment] 2020-02-17 16:27
> I already have found one odd issue with mapped cmd key (sometimes it keeps sending pressed state) with the latest build but didn't start looking for this issue here. maybe it exists)

This issue is known already and an upstream fix exists.

> So how can i contact with you? Maybe you already have a place for sharing such bits of knowledge about issues, maybe slack or telegram? Before posting it here.

It's usually pretty easy to get in contact for quick discussions on IRC, we've got the #alacritty channel on freenode for that.

If it's about bugs specifically though, you can always just open an issue.

**Comment by nixpulvis** [comment] 2020-02-18 23:08
@ovitente as @chrisduerr said, IRC is the best way to chat. I'm not always around, but there's usually someone there.

Otherwise you can, scan issues, test PRs. We always need more eyes on more OSes. Thanks for your interest in helping out!
