### ISSUE TITLE
Alacritty unresponsive after switching back from another virtual console on sway

### ISSUE THREAD

**Issue by littenup** [alacritty/alacritty#2604] opened 2019-06-30 08:50 UTC
I am using alacritty 0.3.3 with sway 1.1 on  Void Linux.
The issue also appeared with alacritty 0.3.2.

After I switch to another virtual consoles, while alacritty is selected (in sway), it is unresponsive to any inputs (keyboard or scrolling), until I select (or start) another window (and reselect alacritty).

Steps to reproduce:
1. start sway on tty1
2. start alacritty and have it selected
3. switch to tty2 (ctrl+alt+f2)
4. switch back to tty1 (ctrl+alt+f1)
5. try to enter something into alacritty

Here is the log with --print-events, but when alacritty did not respond to input, there where also no events printed:
[alacritty.print-events.log](https://github.com/jwilm/alacritty/files/3342688/alacritty.print-events.log)

**Comment by chrisduerr** [comment] 2019-06-30 10:07
I can't reproduce this on X11/i3, have you ever experienced similar behavior in any other application?

**Comment by littenup** [comment] 2019-06-30 11:30
Ohh, I forgot to mention. When running alacritty on XWayland back end the issue is gone. So this appears to be Wayland specific.

I don't have the same issue with other applications. Even with others using Wayland natively (tested with libreoffice when XWayland was disabled).

**Comment by chrisduerr** [comment] 2019-06-30 11:39
I'm wondering if this might be a graphics driver thing. Libreoffice doesn't use OpenGL for rendering for example, tough I'm unsure if there's a good native Wayland app to test this.

One thing you can test however, is if this is an Alacritty bug or a bug in one of our dependencies. If you clone https://github.com/rust-windowing/glutin and run `cargo run --examlpe window`, it would be interesting to see if that causes the same issue. That would indicate that at least Alacritty specifically isn't at fault, but our windowing library might be.

**Comment by littenup** [comment] 2019-06-30 12:38
Well `--example window` doesn't open any window, but `--example multiwindow` works.
The glutin example doesn't have the same issue. I still get event output to stdout after switching back from another virtual console.

**Comment by chrisduerr** [comment] 2019-06-30 15:44
Could you test #2438?

**Comment by kchibisov** [comment] 2019-06-30 19:33
@chrisduerr FYI, I was able to reproduce this bug on wayland (sway) with current master and #2438 . The window is in focus ( as @littenup said), you can resize ( and it handles resize), send to another workspace, but you can't `type` in it unless refocus.

**Comment by chrisduerr** [comment] 2019-06-30 21:35
Might be interesting to see how this behaves in a different Wayland compositor, especially with Nvidia's drivers maybe instead of Intel/AMD.

**Comment by kchibisov** [comment] 2019-06-30 21:51
@chrisduerr If you're about nvidia proprietary drivers they are not supported in `sway`, and many other `wayland` compositors beside `gnome`'s compositor and `kwin`. So testing it under `gnome` should be a good idea.

In case you're about `nouveau` I don't think that it behaves much different than intel/AMD.

**Comment by chrisduerr** [comment] 2019-06-30 22:06
Yeah, this is why I recommended testing another Wayland compositor.

**Comment by neon64** [comment] 2019-07-09 11:17
I have also experienced this issue, not just with `sway`, but also `cage`, another wlroots compositor (after I added my own patch to enable VT switching). This doesn't occur in Gnome, and it also doesn't occur when I use a different terminal emulator (e.g.: kitty) within sway. That means it seems to be some intersection of wlroots and alacritty that doesn't play nicely.

**Comment by MichaelAquilina** [comment] 2019-08-01 16:35
fwiw I think I experience similar behaviour in firefox too, so this might be a sway/wlroots bug

**Comment by p-e-w** [comment] 2020-01-08 04:57
I can confirm this issue on Fedora 31 using Sway 1.2. Alacritty is the only application with this problem on my system.

Two additional observations:

* Control characters still work, e.g. pressing Ctrl+C prints `^C` in Bash.
* Pressing and releasing the Sway `$mod` key (usually Alt) makes everything work again

**Comment by tabell** [comment] 2020-01-25 06:59
I am also seeing this on Sway 1.2, alacritty 0.4.1 on void linux. As far as I can tell Firefox is not affected. Pressing the mod key (bind is bound to Super) does _not_ appear to resolve it. 

If I switch to another workspace or open a new window (thus switching focus away from the one in question) then typing works again.

**Comment by ratmice** [comment] 2020-01-25 20:12
I'm seeing this on x11 occasionally where @p-e-w 's recommendation to hit alt made things work again. On one occasion I have seen that input works but instead of inputting the key as normal hitting the "a" key will print ^a for all the keys.

This makes me believe that what might be happening is that alacritty is storing the modifier as state, and that when hitting the magic chord keys ctrl-alt-f[n] to go to the console, that state  of the modifier is not being cleared on the subsequent key release which happens on the console.

**Comment by kchibisov** [comment] 2020-01-25 20:24
@ratmice you're issue should be fixed on the latest master. Wayland issue is different, since we're not getting any input events.

**Comment by kchibisov** [comment] 2020-01-25 20:33
However just reading once again through your comment makes me believe that issue is a bit different, however just pressing any key on X11 should do something about this issue IIRC, anyway your thing is different compared to what we have on Wayland, and Wayland modifiers tracking is a completely different thing, since compositor is sending a proper events for you, so you kind of have modifiers tracking on a compositor level.

When you're on tty X11 doesn't know about any key releases, I'd guess, so maybe our windowing library messes things a bit if you release modifiers on tty and switch back, however it's trying to update them on likely every key press, etc, so it's really strange to see this issue on X11 tbh. Anyway, open a separate issue from this one and try to add a log file from `--print-events`.

**Comment by chrisduerr** [comment] 2020-01-26 17:46
@ratmice Would you mind reporting this in a separate issue, including the `--print-events` log? I'm not aware of this problem and I cannot reproduce it.

**Comment by ratmice** [comment] 2020-01-26 17:59
@chrisduerr not at all, I was going to do that next time I manage to reproduce it.

**Comment by kchibisov** [comment] 2020-03-09 16:19
related sway bug https://github.com/swaywm/sway/issues/3244

**Comment by kchibisov** [comment] 2020-03-09 16:24
The one thing we can do is to add a workaround in winit or fix sway ofc, but I'm completely against adding a workaround for confirmed sway bug in winit, so "not our issue" and sway should be patched.

**Closed by kchibisov** 2020-03-09 16:24 UTC
Labels: B - bug, DS - Wayland, H - linux, S - winit/glutin

**Comment by p-e-w** [comment] 2020-03-11 08:35
It's pretty crazy that Alacritty is now the terminal officially recommended by Sway, given that Alacritty is basically unusable in Sway because of this bug...

**Comment by kchibisov** [comment] 2020-03-11 10:29
TTY switch is a rare thing and you should just refocus window to fix it, how
It is unusable?

**Comment by tabell** [comment] 2020-03-11 15:45
I would not say it's unusable but I use physlock as my screen locker which means every time I wake from sleep I encounter the issue. It's definitely not rare.

**Comment by kchibisov** [comment] 2020-03-11 15:49
then patch sway(wlroots), since this bug belongs to it?

**Comment by nixpulvis** [comment] 2020-03-11 21:45
I agree it's a frusterating bug, no doubt. But my understanding is the same, this doesn't seems like an alacritty issue. If someone running Sway would care to open an issue with their devs and link it here that would be helpful, but I see no reason to reopen this issue as it stands.

If we're wrong and it **is** in fact an Alacritty issue, we'll look more into it.

**Comment by kchibisov** [comment] 2020-03-11 21:49
@nixpulvis I've already linked a bug here https://github.com/alacritty/alacritty/issues/2604#issuecomment-596629248 and explained in a bug I've opened in sway 
https://github.com/swaywm/sway/issues/5085

**Comment by kchibisov** [comment] 2020-03-14 04:07
fyi sway/wlroots fixed this bug.

**Comment by p-e-w** [comment] 2020-03-19 06:09
@kchibisov I was actually seeing this bug in many more situations than TTY switching, such as when simply moving focus to another window and back, hence the "unusable".

However, I am no longer able to reproduce these problems with the latest Alacritty and Sway, so it looks like the more general manifestation of this bug has been fixed as well.
