### ISSUE TITLE
The backspace key is not functioning properly when typing in Chinese.

### ISSUE THREAD

**Issue by tomatofrommars** [alacritty/alacritty#6920] opened 2023-05-11 08:06 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS 13.3.1
Version: alacritty 0.12.1-rc1 (110f81d)

### Logs
Keyboard events: [Alacritty-22064.log](https://github.com/alacritty/alacritty/files/11449693/Alacritty-22064.log)

The backspace key is not functioning properly when typing in Chinese. Specifically, when there is only one character left in the input method bar, pressing the backspace key once deletes two characters instead of one.

![alacritty-log](https://github.com/alacritty/alacritty/assets/16113120/4d692cc9-c346-45d6-a234-c555cc5f308c)

**Comment by kchibisov** [comment] 2023-05-11 12:38
Your log doesn't contain any keyboard events at all. Is it a standard macOS IME?

**Comment by chrisduerr** [comment] 2023-05-13 00:34
Closing as duplicate of #458. I don't think there's any point in trying to track down more macOS keybinding issues considering we already know the fix for it will likely be the new keyboard API.

**Comment by kchibisov** [comment] 2023-05-13 00:38
See https://github.com/rust-windowing/winit/commit/a9e168e10d819ad8c66ccb336df4e2878600c800

**Comment by chrisduerr** [comment] 2023-05-13 00:42
Do you think this might help with https://github.com/alacritty/alacritty/issues/6827?

**Comment by kchibisov** [comment] 2023-05-13 00:51
It was mentioned that `0.10.1` is also affected, but I've started breaking macOS input on regular basis since `0.11.0`.

Though, they could try to test `rc-2`.

**Comment by tomatofrommars** [comment] 2023-05-15 07:02
> Your log doesn't contain any keyboard events at all. Is it a standard macOS IME?

Yes, it is.

I tried to compile #6924. The problem still exists.

Keyboard events: 
[alacritty-0.12.1-rc1.log](https://github.com/alacritty/alacritty/files/11474888/alacritty-0.12.1-rc1.log)
[alacritty-0.13.0-dev.log](https://github.com/alacritty/alacritty/files/11474891/alacritty-0.13.0-dev.log)

**Comment by kchibisov** [comment] 2023-05-15 10:11
Are you sure that you've compiled it correctly? Because I can't repro that bug anymore.

**Comment by tomatofrommars** [comment] 2023-05-15 10:27
> Yeah, looking at the log, you've compiled the wrong thing. Your hash doesn't match the one on the branch.

It works. Thank you.

**Closed** 2023-05-16 00:03 UTC
Labels: H - macos, B - regression, C - waiting on dependency
