### ISSUE TITLE
Allow configuration for padding top

### ISSUE THREAD

**Issue by feluxe** [alacritty/alacritty#7411] opened 2023-12-03 18:28 UTC
Hi, I'm using alacritty with i3wm on Linux. I use the padding option in order to push the prompt line a little upwards, so that it's not too close to the edge of my screen. This however also adds a padding to the top hiding the scrollable text output stream. I'd love to configure a padding for *bottom only*. To me this is similar to a website, only upside down. The prompt is the nav and the terminal output is the endless scrollable stream. (Think of reddit upside down). The top padding is kinda annoying if you see it like this.

![image](https://github.com/alacritty/alacritty/assets/6545589/1993bde7-646e-47d6-b2b3-25916ff2b4e3)

**Comment by chrisduerr** [comment] 2023-12-03 22:47
Duplicate of https://github.com/alacritty/alacritty/issues/4297.

Fundamentally I don't think there's anything wrong with it and it would be simple to implement, I'm not interested in implementing it myself though.

If someone actually wants this, I'm happy to entertain a PR.

**Closed by chrisduerr** 2023-12-03 22:47 UTC

**Comment by travistylervii** [comment] 2024-03-14 05:09
> Duplicate of #4297.
> 
> Fundamentally I don't think there's anything wrong with it and it would be simple to implement, I'm not interested in implementing it myself though.
> 
> If someone actually wants this, I'm happy to entertain a PR.

Nothing wrong with it? 
![CleanShot 2024-03-13 at 22 09 12@2x](https://github.com/alacritty/alacritty/assets/4889865/9f8806d3-a69e-42a8-94aa-a4cab8ed6be5)

**Comment by kiosion** [comment] 2024-08-06 18:16
> If someone actually wants this, I'm happy to entertain a PR.

Still open to this? I could take a shot at it. Would love to use the 'Transparent' title bar option but it looks incredibly bad with overlapping content.

**Comment by chrisduerr** [comment] 2024-08-06 20:29
See #4297 for details. Nobody has yet made any convincing arguments for why this feature would be necessary.

**Comment by travistylervii** [comment] 2024-08-06 20:53
@chrisduerr did you see my screenshot? The close, max and min buttons in apples UI cover the code area. It's not an ideal design aesthetic. It would be nice to have the option to avoid any UI / code overlap.

**Comment by chrisduerr** [comment] 2024-08-06 20:55
Yes I have. The correct solution to that is to expose a function in winit to get the reserved area of a window and to add that as padding explicitly.

Adding random top padding values is a workaround, not a correct solution. Again, read #4297.
