### ISSUE TITLE
can't set the TERM right...

### ISSUE THREAD

**Issue by Brane212** [alacritty/alacritty#3622] opened 2020-04-21 07:03 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Gentoo Linux with sway
Version: `alacritty --version` output / alacritty 0.5.0-dev (03bce99)

### issue:

None of the TERM values seem to work right. Default is TERM=alacritty, which makes arrows emit double code left/right/up/down. This means that in Midnight Commander, for example, I can jump only to every second line and column.

TERM=linux fixes that issue, but with it I lose all F1-F12 keys, so I have to emulated them with ESC-1...ESC..9.

**Comment by kchibisov** [comment] 2020-04-21 07:09
>None of the TERM values seem to work right. Default is TERM=alacritty, which makes arrows emit double code left/right/up/down. This means that in Midnight Commander, for example, I can jump only to every second line and column.

delete old default bindings from the config, it seems like you have collision right now.

duplicate of  #3476

**Closed by kchibisov** 2020-04-21 07:09 UTC
