### ISSUE TITLE
Resizing extremely sluggish on tiling WM (bspwm) with nvidia graphics

### ISSUE THREAD

**Issue by phisch** [alacritty/alacritty#5211] opened 2021-06-06 14:54 UTC
When resizing a tiled alacritty window in bspwm on a machine with nvidia gpu, the resize is extremely sluggish. Moving the mouse for 2-3 seconds, and the alacritty window needs another 2-3 seconds to catch back up with all the resize events:

https://user-images.githubusercontent.com/1282767/120928941-17902600-c6e7-11eb-99b2-283ed15237a8.mp4

I don't know the technical details of why this happens, but this has been reported before and was closed without a solution: https://github.com/alacritty/alacritty/issues/4381

This recent pull request offered an option to disable vsync through configuration, which even if it is a bad solution, it still is a solution: https://github.com/alacritty/alacritty/pull/5209

Here is how the resizing looks like without vsync:

https://user-images.githubusercontent.com/1282767/120929102-009e0380-c6e8-11eb-8d17-beb5163ae6e8.mp4

I don't have the technical knowledge to know why the resizing is so sluggish, but i know that alacritty is literally the only application on my system which does this. 

Just let me know if i can help in any way, because i really want to find a proper solution to this problem!

### System

OS: Linux (arch)
Version: 0.8.0 (a1b13e68)
Linux/BSD: X11, bspwm, picom

### Logs
Log while resizing: [alacritty_resize.log](https://github.com/alacritty/alacritty/files/6604358/alacritty_resize.log)

**Comment by chrisduerr** [comment] 2021-06-06 15:21
Duplicate of #4381.

**Closed by chrisduerr** 2021-06-06 15:21 UTC

**Comment by phisch** [comment] 2021-06-06 15:25
@chrisduerr it's a duplicate of another closed issue that nobody reacts to or takes serious. Another issue other people can't easily find because it is closed.

It looks like you have just given up on that issue and are just silencing it.

You are really not making it easy to get any progress on this...
