### ISSUE TITLE
Text render is off (ZSH)

### ISSUE THREAD

**Issue by dgrabla** [alacritty/alacritty#884] opened 2017-11-02 09:28 UTC
Which operating system does the issue occur on?
MACOS + ZSH

I started using Alacritty in early October and since then I have this issue. I am using default macos configuration file. It doesnt happen on MACOS terminal or iterm2.  I am using zprezto - with the pure theme.
https://github.com/sindresorhus/pure

![20171102_issueterminalalacritty](https://user-images.githubusercontent.com/1942073/32318319-336fb6aa-bfb7-11e7-908e-e1ad0eb3dee2.gif)

I tried to solve the issue but I run out of ideas. I guessed it is something related to the ZSH prompt, but it happens with all the ZSH prompts I tried. It doesnt happen with bash.

**Comment by jwilm** [comment] 2017-11-02 15:07
Looks like an issue with wide char width mismatch

**Comment by q-b** [comment] 2017-11-03 18:33
Confirmed
```
~/Development/rust/alacritty master
❯ zsh --version
zsh 5.4.2 (x86_64-apple-darwin15.6.0)

~/Development/rust/alacritty master
❯ git log -1
commit f68558e9dcce97e0d4d842a2d5b62e31e4124210 (HEAD -> master, origin/master, origin/HEAD)
Author: Bailey <github@monokro.me>
Date:   Tue Oct 31 08:54:30 2017 -0700

    Link to FAQ when referencing it (#881)
```

**Comment by ooJerryLeeoo** [comment] 2018-04-22 10:56
It seems like the problem is caused by the `❯` symbol, a quick fix will be setting the `PURE_PROMPT_SYMBOL` to something else like like `$`:
```sh
export  PURE_PROMPT_SYMBOL='$'
```

**Comment by pwang2** [comment] 2020-09-10 14:49
This has been an issue for a long long time? any follow up?  
Not just this, it(v0.5.0) will make vim nerdtree split off too.

**Comment by chrisduerr** [comment] 2020-09-10 18:47
It shouldn't be an issue iirc and I cannot reproduce it. Most likely problem is a system configuration issue.

**Comment by q-b** [comment] 2020-09-10 19:11
I quickly checked the homebrew version, and cannot reproduce the bug. Since the whole OS was updated, zsh and alacritty as well, and my prompt is not the same... 🤷‍♂️

**Comment by chrisduerr** [comment] 2020-09-10 19:46
I'll just close this for now, if someone can reproduce it that should lead to new bug reports which will probably be easier to resolve than having an ancient thread around with nobody left to help troubleshoot.

**Closed by chrisduerr** 2020-09-10 19:46 UTC
Labels: A - needs repro, S - unicode
