### ISSUE TITLE
Alacritty on Flathub

### ISSUE THREAD

**Issue by Peque** [alacritty/alacritty#2571] opened 2019-06-21 15:31 UTC
It would be great to have Alacritty available on Flathub (as a Flatpak application).

Opening this issue as a follow-up of https://github.com/jwilm/alacritty/issues/2412.

**Comment by chrisduerr** [comment] 2020-04-26 20:11
Since Alacritty has no intention to maintain anything package related ourselves, I'm going to close this issue.

However if someone is interested in creating a flatpak application and it requires patches in Alacritty, those are always welcome.

**Closed by chrisduerr** 2020-04-26 20:11 UTC
Labels: H - linux, S - packaging

**Comment by darthrevan13** [comment] 2020-05-05 10:03
The intention is to have an open bug to follow the progress of Allacritty as a Flatpak even if not done in an official manner. This is the first result on Google for "alacritty flatpak". Please reopen this issue.

**Comment by ineol** [comment] 2020-05-24 16:20
In any case, I believe that one problem is that we want the shell to be run from outside the sandbox where the terminal would be running. [I have tried](/ineol/io.alacritty.Alacritty) to use `flatpak-spawn --host` to run the shell from the host (cf the config file there) but they are some problems, for instance the arrow keys do not work properly for some reason.

**Comment by PranavBhattarai** [comment] 2021-04-29 10:30
Flatpak would have definitely made things easier for a user who wants to install Alacritty.

The fast way to come to an end by closing the issue is disappointing. 

I had installed Alacritty on Ubuntu 20.10 using PPA. The annoying thing about that was, I was receiving Alacritty updates daily. The maintainer was releasing a new update every day. 

```
sudo apt install alacrity 
sudo apt install alacrity-dev
```
There is a difference between these two commands. The maintainer "mmstick76" should have used this concept of dev built and stable built. For Ubuntu 21.04 release, the PPA has not been updated yet.

P.S: All this trouble would have solved if we had a flatpak for Alacritty.

**Comment by tinywrkb** [comment] 2021-04-29 19:20
For reference: https://gitlab.gnome.org/chergert/flatterm

**Comment by akvadrako** [comment] 2022-03-02 10:16
Using alacritty with flatpak for normal situations will require more work than a package. `flatpak-spawn` doesn't do TTY proxying [^1][^2] so won't work for an interactive shell.

I think alacritty would need a helper "portal" to allocate the tty and launch the shell on the host, while the rest of the app exists in the sandbox.

[^1]: https://github.com/flatpak/flatpak/issues/3697
[^2]: https://github.com/flatpak/flatpak/issues/3285

**Comment by primeagen-rustaceans** [comment] 2023-06-16 13:08
> Flatpak would have definitely made things easier for a user who wants to install Alacritty.
> 
> The fast way to come to an end by closing the issue is disappointing.
> 
> I had installed Alacritty on Ubuntu 20.10 using PPA. The annoying thing about that was, I was receiving Alacritty updates daily. The maintainer was releasing a new update every day.
> 
> ```
> sudo apt install alacrity 
> sudo apt install alacrity-dev
> ```
> 
> There is a difference between these two commands. The maintainer "mmstick76" should have used this concept of dev built and stable built, but he didn't. So, all normal users are getting a daily dose of updates.
> 
> For Ubuntu 21.04 release, the PPA has not been updated yet.
> 
> P.S: All this trouble would have solved if we had a flatpak for Alacritty.

I am new to development. I am getting Unable to locate package alacrity. while running sudo apt install alacrity

**Comment by kchibisov** [comment] 2023-09-19 14:17
Given that flatpak support requires patching the source with the **flatpak specific logic** (it's not just about API, you need to use flatpak binaries and communicate with env).

All of that is required to violate the flatpak sandbox and give a false promise of security of the end users (they might thing that if the app doesn't access network, shell also won't access it, but it's a lie).

Anyone interested, could patch and package alacritty themselves to support a flatpak, but then such package must not affiliate with the upstream (alacritty/alacritty) in any way.

Given that majority of distros package alacritty (even ubuntu, because they can pull the debian packages), the argument about packaging is also doesn't apply.
