### ISSUE TITLE
Ibus not working in Alacritty

### ISSUE THREAD

**Issue by thevan96** [alacritty/alacritty#3897] opened 2020-06-28 04:57 UTC
I'm VietNamese, i use ibus typing vietnamese.
- All applications in Kde work well with ibus, but  alacritty not working
- Character arrow symbol too smal ( ➜ oh-my-zsh theme)
### System
OS: Ubuntu 20.04 LTS x86_64
Version: alacritty 0.4.3
Linux/BSD: KDE Desktop enviroment 
Shell: zsh 5.8
DE: Plasma
WM: KWin
Terminal: alacritty

### Log
![ibusError](https://user-images.githubusercontent.com/47932916/85938324-6f020f80-b936-11ea-8788-d3020252683e.gif)

**Comment by chrisduerr** [comment] 2020-06-28 15:09
Duplicate of #1613.

**Closed by chrisduerr** 2020-06-28 15:09 UTC

**Comment by hasufell** [comment] 2024-08-29 08:17
I read the duplicate ticket and I don't understand how it's related.

With the latest version of alacritty, Ibus does not work for me:
![umlaut](https://github.com/user-attachments/assets/b271fa6c-ff43-458e-8676-985a927d95c1)

As you can see it's working fine in GTK+ app.

**Comment by Shamaoke** [comment] 2024-09-23 06:26
It doesn't work for me either. Neither ibus (ibus-anthy, ibus-emoji, ibus-unicode) nor compose key input interfaces aren't embedded into the terminal window. This happens on my work PC. On my home laptop, however, all works without any problems. Both computers work in the same operational environment (Arch Linux) with the same version of Alacritty and with exactly the same Alacritty configuration.
