### ISSUE TITLE
With Non nerd font Alacritty not shows font icons (unicode characters)

### ISSUE THREAD

**Issue by ciscohack** [alacritty/alacritty#6022] opened 2022-04-24 19:37 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: `alacritty 0.10.1`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`

```
Created log file at "/var/folders/2h/dl8j4_2n3rz26kvb51jhhbd00000gn/T/Alacritty-9816.log"
[0.000004235s] [INFO ] [alacritty] Welcome to Alacritty
[0.000299568s] [INFO ] [alacritty] Version 0.10.1 (2844606)
[0.004082808s] [INFO ] [alacritty] Configuration files loaded from:
                                                               "/Users/prav/.config/alacritty/alacritty.yml"
[0.005169564s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.055221852s] [DEBUG] [alacritty] Estimated DPR: 2
[0.055519404s] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 2656, height: 2440 })
[0.055650013s] [DEBUG] [alacritty] Estimated cell size: 20 x 56
[0.120096833s] [INFO ] [alacritty] Device pixel ratio: 2
[0.125770873s] [INFO ] [alacritty] Initializing glyph cache...
[0.226320174s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.100361381s
[0.226536732s] [INFO ] [alacritty] Estimated DPR correctly, skipping resize
[0.226639623s] [INFO ] [alacritty] Cell size: 20 x 56
[0.226686068s] [INFO ] [alacritty] Padding: 8 x 16
[0.226727481s] [INFO ] [alacritty] Width: 2656, Height: 2440
[0.227214112s] [INFO ] [alacritty] PTY dimensions: 43 x 132
[0.233895901s] [INFO ] [alacritty] Initialisation complete
[1.552449284s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['8',],[],['f','i','l','e',':','/','/','/','U','s','e','r','s','/','p','r','a','v','e','r','a','i',],] at line 949
[1.552537545s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['8',],[],[],] at line 949
[1.624081025s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['8',],[],['f','i','l','e',':','/','/','/','U','s','e','r','s','/','p','r','a','v','e','r','a','i',],] at line 949
[1.624247201s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['8',],[],[],] at line 949
```

Hello experts,

As I understand Alacritty should support glyphs and they have the biggest database than any other terminal for showing icons but I have noticed alacritty is working like the old terminal in this area and not showing icons on the terminal If the font is not nerd font. if  alacritty not support this then can this be part of near-future releases 

below is a small example of an icon missing. is there any setting or something to fix this issue? i have powerline symbols installed 

![image](https://user-images.githubusercontent.com/11479557/164993460-2acb6e62-f36d-4cac-aa2c-d26f87725377.png)

**Comment by ciscohack** [comment] 2022-04-25 04:28
hello Experts any input or help on this

**Comment by ciscohack** [comment] 2022-04-25 05:33
here is the Pragmatopro mono

![image](https://user-images.githubusercontent.com/11479557/165026456-2e0dceee-00bd-4dbe-8243-6e51dca9610c.png)

**Comment by chrisduerr** [comment] 2022-04-26 00:31
Duplicate of #2800.

**Closed by chrisduerr** 2022-04-26 00:31 UTC

**Comment by ciscohack** [comment] 2022-04-26 04:27
@chrisduerr  Thanks sir I can see you duplicate the ticket with another open case... in fact, alacritty has many issues with glyph rendering and many folks reported it in past. I am still not sure what is the solution provided in the other case but hunting what can be done to resolve this annoying issue. I have locate as per recommendation so not a locale problem for sure

Can't we use try iterm2 solution or kitty method of symbol-map option to use nerd/powerline glyph to fix this issue
