### ISSUE TITLE
Keys from Spanish keyboard not recognised on macOSX

### ISSUE THREAD

**Issue by MarioAriasC** [alacritty/alacritty#753] opened 2017-08-24 19:06 UTC
Some characters (such as Ñ, ~, `, ^, [,]) aren't recognised.

I did manage to set ~ in the `alacritty.yml` file with

```yml
# tilde (~)
  - { key: Semicolon,mods: Alt,     chars: "\u007E"                      }
``` 
But ñ is impossible as that keystroke shows `(arg: 1)` in the terminal

**Comment by kenan-rhoton** [comment] 2018-03-20 06:03
funny, I have no problem with ñ at all, but I can't input the following characters (commas for clarity):
```
\,`,^,[,],´,¨,{,},|,@,#`
```

In particular, the [] and {} make it unusable for my use case (developing). I might give the source a go, since this seems like it should be simple to fix (although I suppose it can be patched with key entries).

Spanish layout for reference: https://commons.wikimedia.org/wiki/File:KB_Spanish.svg

**Comment by kenan-rhoton** [comment] 2018-03-20 07:09
Initial config "patch" for anyone with the same problems:

```yaml
  - { key: Semicolon,mods: Alt,     chars: "~"                           }
  - { key: Key1,     mods: Alt,     chars: "|"                           }
  - { key: Key2,     mods: Alt,     chars: "@"                           }
  - { key: Key3,     mods: Alt,     chars: "#"                           }
  - { key: LBracket,                chars: "`"                           }
  - { key: LBracket, mods: Shift,   chars: "^"                           }
  - { key: LBracket, mods: Alt,     chars: "["                           }
  - { key: RBracket, mods: Alt,     chars: "]"                           }
  - { key: Apostrophe,              chars: "´"                           }
  - { key: Apostrophe,mods: Shift,  chars: "¨"                           }
  - { key: Apostrophe,mods: Alt,    chars: "{"                           }
  - { key: Backslash,mods: Alt,     chars: "}"                           }
  - { key: Caret,    mods: Alt,     chars: "\\"                          }
```

This doesn't make the accents behave "normally" in the sense that it doesn't combine them properly with the next character. If I find a solution to that, I will update here. However, it would be nice to see alacritty detect this "out of the box".

**Comment by jwilm** [comment] 2018-03-20 15:45
@kenan-rhoton are you also on macOS?

**Comment by kenan-rhoton** [comment] 2018-03-20 17:57
Indeed I am, sorry for not making that clear.

**Comment by kenan-rhoton** [comment] 2018-04-18 09:46
Any updates on this subject? I would be open to submitting a PR but have trouble finding the relevant parts in the code.

**Comment by lrascao** [comment] 2019-03-26 23:32
on a PT keyboard and latest master i managed to get []{} working with this config
````
  - { key: LBracket,     mods: Alt|Shift,     chars: "\x7B"                  }  # left curly bracket {
  - { key: RBracket,     mods: Alt|Shift,     chars: "\x7D"                  }  # right curly bracket }
  - { key: LBracket,     mods: Alt,     chars: "\x5b"                        }  # left square bracket [
  - { key: RBracket,     mods: Alt,     chars: "\x5d"                        }  # right square bracket ]
````

**Comment by ctafur80** [comment] 2019-05-25 18:01
I had the same problem. The solution is on https://github.com/jwilm/alacritty/wiki/Keyboard-mappings. For my Spanish-layout keyboard I just added:

```
  # Ajustes para teclado español/spanish de España
  - {
    key: Caret,
    mods: Alt,
    chars: "\x5c" # barra invertida `\`
    }

  # - {
  #   key: Key1,
  #   mods: Alt,
  #   chars: "\x7c" # barra vertical `|`
  #   }

  - {
    key: Key2,
    mods: Alt,
    chars: "@" # arroba `@`
    }

  - {
    key: Key3,
    mods: Alt,
    chars: "#" # almohadilla/cardinalidad `#`
    }

  - {
    key: Key6,
    mods: Alt,
    chars: "¬" # negación en lógica `¬`
    }

  - {
    key: 39,
    mods: Alt,
    chars: "{" # abre llaves `{` | 39 = Apostrophe
    }

  - {
    key: 42,
    mods: Alt,
    chars: "}" # abre llaves `}` | 42 = Backslash
    }

  - {
    key: 33,
    mods: Alt,
    chars: "[" # abre corchetes `[` | 33 = Grave
    }

  - {
    key: 30,
    mods: Alt,
    chars: "]" # cierra corchetes `]` | 30 = Equals
    }

  - {
    key: Backslash,
    mods: Alt,
    chars: "\x5c" # barra invertida `\`
    }

  - {
    key: 18,
    mods: Alt,
    chars: "\x7c" # barra vertical `|` | 18 = Key1
    } # Me da problemas: me la muestra como `\|`
```

There is one thing that I'm still not able to fix: Whenever I try to write a vertical bar (`|`) Alacritty shows this: `\|`.

**Comment by ctafur80** [comment] 2019-09-19 09:06
I've finally found a solution:

```yaml
  # Ajustes para teclado macOS español/spanish de España con layout ISO (no ANSI); tecla Intro grande.
  - { key: 10,     mods: Alt,    chars: "\x5c" } # barra invertida `\`
  - { key: 18,        mods: Alt,    chars: "\x7c" } # barra vertical `|`
  - { key: Key2,      mods: Alt,    chars: "@" } # arroba `@`
  - { key: Key3,      mods: Alt,    chars: "#" } # almohadilla/cardinalidad `#`
  - { key: Key6,      mods: Alt,    chars: "¬" } # negación en lógica `¬`
  - { key: 39,        mods: Alt,    chars: "{" } # abre llaves `{`
  - { key: 42,        mods: Alt,    chars: "}" } # cierra llaves `}`
  - { key: 33,        mods: Alt,    chars: "[" } # abre corchetes `[`
  - { key: 30,        mods: Alt,    chars: "]" } # cierra corchetes `]`
```

**Comment by ricardojoaoreis** [comment] 2020-05-19 07:57
I'm also having this issue with a pt-PT macOS layout and the solution on the wiki page isn't working for me. 😔

**Comment by chrisduerr** [comment] 2020-05-19 11:53
Duplicate of #458.

**Closed by chrisduerr** 2020-05-19 11:53 UTC
Labels: A - deps, H - macos, S - winit/glutin
