### ISSUE TITLE
Unicode strikethrough weirdness

### ISSUE THREAD

**Issue by iximeow** [alacritty/alacritty#1230] opened 2018-04-05 04:58 UTC
#### Which operating system does the issue occur on?
Seen on linux, dunno about others.

#### If on linux, are you using X11 or Wayland?
X11

Unicode strikethrough overlay (for me!) appear to not overlay as much as next-to-lay:
![an example](https://user-images.githubusercontent.com/4615790/38347731-10b162bc-3852-11e8-8969-24a4ca91749a.png)

Someone else saw them overlay, but with empty space where I see the standalone strikethrough in the above image.

I'm using alacritty 0.1.0, font is ubuntu mono, haven't tried to replicate elsewhere (didn't see another issue but this seems like something that might already be known or fixed)

**Comment by sodiumjoe** [comment] 2018-04-05 05:00
dupe of #806, should be fixed by #1078

**Comment by iximeow** [comment] 2018-04-05 05:00
ah cool! I'll figure out rebuilding and confirm then, sorry for dupe :)

**Comment by dequis** [comment] 2018-04-05 05:14
That issue seems to be about real strikethrough with proper ansi control codes, while this is about the unicode hack with combining characters.

**Comment by sodiumjoe** [comment] 2018-04-05 05:17
my mistake, I wasn't sure what I was supposed to be looking at. I guess it's supposed to look like this?

![2018-04-04 at 10 16 pm](https://user-images.githubusercontent.com/845857/38348325-fbf18902-3855-11e8-95b2-7ba7a685c8ad.png)

**Comment by chrisduerr** [comment] 2018-04-05 15:36
Currently unicode characters are not combined or normalized at all. So this should be an issue with current master and scrollback.

**Comment by kchibisov** [comment] 2020-01-19 16:14
as far as I can tell should be fixed in latest version(probably even earlier).

**Closed by kchibisov** 2020-01-19 16:14 UTC

**Comment by chrisduerr** [comment] 2020-01-19 16:20
Should have been fixed in 1cebcd660bf0b6dc514341fe6bc7a392b1572849 to be precise.
