### ISSUE TITLE
Move two cells when press left or right key with tmux

### ISSUE THREAD

**Issue by h-michael** [alacritty/alacritty#3527] opened 2020-03-28 05:23 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux
Version: c35dbc96575f6147de97be15c5134bc7fabe50bd
Linux/BSD: X11, i3

## repdoduce steps
"|" is cursor position.

1. start tmux
2. input "foobar"
3. cursor position is "foobar|"
4. press left key once
5. cursol position is "foob|ar"

![Peek 2020-03-28 12-56](https://user-images.githubusercontent.com/4556097/77814502-fe5c1480-70f4-11ea-8f79-096b47c0ba92.gif)

This occured after 1a8cd172e520e493bacc9c6a2ae6f80de086eaa3

**Comment by kchibisov** [comment] 2020-03-28 07:55
Duplicate of #3487

**Closed by kchibisov** 2020-03-28 07:55 UTC
