### ISSUE TITLE
Alacritty + Neovim character rendering issues on Windows 8.1...

### ISSUE THREAD

**Issue by dseeni** [alacritty/alacritty#3662] opened 2020-05-01 02:37 UTC
Hi Alacritty, 
![image](https://user-images.githubusercontent.com/6591429/80777100-f12dad80-8b18-11ea-8ff7-f027e04ccca2.png)

I'm stuck on windows 8.1 on this work machine, and I'd like to try and use alacritty with neovim, does anyone know what settings should be set in the alacritty.yml file? It's pretty much blank, but I am using powershell 7 which works well. 

Vim runs fine.. but neovim for some reason the terminal is not recognizing characters...all default settings in neovim. Alacritty is default also. 

Please advise 

### System

OS: Windows
Version: alacritty 0.4.2 (f68de37)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY
### Logs

Maybe its fonts or bindings? I am just using defaults... what can I set them to?

**Comment by chrisduerr** [comment] 2020-05-03 23:38
I'd assume you're talking about the (B characters showing up?

Seems like it might be a locale or terminfo issue. What terminfo are you using?

However when using WinPTY, you will run into many bugs that will never get fixed. So for a better experience I'd recommend using Windows 10's ConPTY.

**Comment by dseeni** [comment] 2020-05-04 00:00
Yeah the <Enter>(B, I don't have any term info set, I'll try that though. Yeah things would be much simpler if I could just use windows 10, stuck on 8.1 on this machine sadly. Thanks for the tip!

**Comment by keaising** [comment] 2022-11-23 09:43
Same here, I use Windows 10 22H2 (19045.2311) and Alaritty v0.11.0 can reproduce this issue.

You can see the last char of bottom line of the neovim (the 2nd `l` of the `All`) is on the next line, and tmux has the same issue.

Do you have any ideas about this problem? I can provide more details if you'd like to search the root cause. @chrisduerr 

![image](https://user-images.githubusercontent.com/8179012/203514213-8612a3f7-274a-4942-b3d5-54296f24fe54.png)

**Comment by keaising** [comment] 2022-11-23 14:06
I think I have found the problem.

I try to change `$TERM` from `screen-256color` to `xterm-256term` and the problem disappear.

If someone meet the same problem, you can use `echo $TERM` to check your terminfo first.

**Comment by chrisduerr** [comment] 2022-11-24 23:44
Closing since WinPTY isn't even supported anymore.

**Closed by chrisduerr** 2022-11-24 23:44 UTC
Labels: H - windows
