### ISSUE TITLE
Docker stats redraw flashing

### ISSUE THREAD

**Issue by esetnik** [alacritty/alacritty#3790] opened 2020-05-29 14:06 UTC
When issuing a command that refreshes the screen like `docker stats` the alacritty terminal flashes on every redraw. The equivalent command in iTerm2 with GPU acceleration enabled does not cause any flashing. See the gif for a side-by-side comparison.
![May-29-2020 09-59-37](https://user-images.githubusercontent.com/664434/83268693-fd4a7080-a193-11ea-94a3-d0acbd3ea5c1.gif)

### System

OS: macOS
Version:  alacritty 0.4.2 (f68de37)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
```
❯ alacritty -vv
Created log file at "/var/folders/0k/xnkw88y928z_hfn58tlmhwxm0000gn/T/Alacritty-86596.log"
[2020-05-29 10:01:38.852887000] [INFO] Welcome to Alacritty
[2020-05-29 10:01:38.853039000] [INFO] Configuration loaded from "/Users/ethan/.config/alacritty/alacritty.yml"
[2020-05-29 10:01:38.876718000] [DEBUG] Estimated DPR: 2
[2020-05-29 10:01:38.876769000] [DEBUG] Estimated Cell Size: 16 x 33
[2020-05-29 10:01:38.876785000] [DEBUG] Estimated Dimensions: None
[2020-05-29 10:01:38.907092000] [INFO] Device pixel ratio: 2
[2020-05-29 10:01:38.908974000] [INFO] Initializing glyph cache...
[2020-05-29 10:01:38.936731000] [INFO] ... finished initializing glyph cache in 0.027700564s
[2020-05-29 10:01:38.936795000] [INFO] Cell Size: 16 x 33
[2020-05-29 10:01:38.936816000] [INFO] Padding: 0 x 0
[2020-05-29 10:01:38.936832000] [INFO] Width: 1600, Height: 1200
[2020-05-29 10:01:38.936877000] [INFO] PTY Dimensions: Line(36) x Column(100)
[2020-05-29 10:01:38.938943000] [INFO] Initialisation complete
```

**Comment by chrisduerr** [comment] 2020-05-29 17:31
Duplicate of https://github.com/alacritty/alacritty/issues/598.

**Closed by chrisduerr** 2020-05-29 17:31 UTC
