### ISSUE TITLE
Severe input lag

### ISSUE THREAD

**Issue by hedgeberg** [alacritty/alacritty#5883] opened 2022-02-12 04:32 UTC
Alacritty has very bad input lag when running it on my setup. Usually, a character won't be rendered until the next keypress occurs or about 5 seconds later, whichever comes first. My setup is admittedly a bit odd, so figuring out where the issue is is tricky. I'm using a slightly custom bumblebee setup to manage the NVIDIA optimus state. The issue definitely seems to be GPU related, because when run with `optirun` and rendered via the discrete GPU, the terminal works exactly as I would expect it to.  

What information (other than what is provided already) can I collect to help pin this problem down? 

### System

OS: Arch Linux -- 5.16.5-arch1-1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux
Version: alacritty 0.11.0-dev (774eb03f)
Linux/BSD: X11 w/ GNOME4 
GPU: Intel (w/ i915 mesa drivers) & nvidia (w/ nvidia drivers)

### Logs

Crashes: None
alacritty -vv:
```
Created log file at "/tmp/Alacritty-89730.log"
[0.000000702s] [INFO ] [alacritty] Welcome to Alacritty
[0.000044497s] [INFO ] [alacritty] Version 0.11.0-dev (774eb03f)
[0.000057751s] [INFO ] [alacritty] Running on X11
[0.000374836s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/hedge/.config/alacritty/alacritty.yml"
[0.018449432s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.021091989s] [DEBUG] [alacritty] Estimated DPR: 1
[0.021109444s] [DEBUG] [alacritty] Estimated window size: None
[0.021139140s] [DEBUG] [alacritty] Estimated cell size: 9 x 21
[0.073710183s] [INFO ] [alacritty] Device pixel ratio: 1
[0.079811253s] [INFO ] [alacritty] Initializing glyph cache...
[0.085643594s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.092264491s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.099476503s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.106390167s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.119877061s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.040035447s
[0.122872131s] [INFO ] [alacritty] Cell size: 9 x 21
[0.122889118s] [INFO ] [alacritty] Padding: 0 x 0
[0.122913316s] [INFO ] [alacritty] Width: 800, Height: 600
[0.127824749s] [INFO ] [alacritty] PTY dimensions: 28 x 88
[0.130788538s] [INFO ] [alacritty] Initialisation complete
[0.214997805s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.215060272s] [INFO ] [alacritty] Padding: 0 x 0
[0.215073389s] [INFO ] [alacritty] Width: 800, Height: 600
[0.380692395s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','c','h','r','y','s','a','n','t','h','e','m','u','m','/','h','o','m','e','/','h','e','d','g','e','/','D','o','c','u','m','e','n','t','s','/','a','l','a','c','r','i','t','t','y',],] at line 951
[0.401016670s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[4.909691375s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-89730.log"
```

Keyboard and bindings: `alacritty --print-events` -- output here: [debug_output.txt](https://github.com/alacritty/alacritty/files/8052692/debug_output.txt)

**Comment by chrisduerr** [comment] 2022-02-12 04:55
Have you tried running Wayland? Does that resolve these issues?

**Comment by hedgeberg** [comment] 2022-02-12 05:15
I have not, because wayland refuses to work on my hardware. I spent a lot of time fighting to get it running a while back, and it didn't work at all. I don't think running alacritty under wayland is a test I'll reasonably be able to run, sorry.

**Comment by chrisduerr** [comment] 2022-02-12 06:12
> I spent a lot of time fighting to get it running a while back, and it didn't work at all.

Fyi in case your issue was with Nvidia drivers not supporting Wayland, that should be resolved.

> when run with optirun and rendered via the discrete GPU, the terminal works exactly as I would expect it to.

This sounds like you're running into the buggy intel driver on X11 which doesn't vsync correctly. You mentioned your setup is "a bit odd", have you tried it without the custom bumblebee setup?

**Comment by hedgeberg** [comment] 2022-02-12 07:17
The custom bumblebee setup is designed so that I can boot without it and render solely to the dGPU by passing a kernel flag, so, yes, and alacritty runs fine in a purely nvidia graphics pipeline on this system. I agree that the issue is in the intel stack somewhere, but alacritty is the only application that behaves like this, which suggests to me that something can be changed on alacritty's end to resolve this. 

I'm happy to do the debugging/patching myself and submit a pull request, I just need to know where best to start. Mind pointing me in the right direction?

**Comment by kchibisov** [comment] 2022-02-12 10:04
Are you sure it's not running on dGPU and copied to iGPU? Also, compare to other opengl apps, since otherwise it's not that useful

**Comment by hedgeberg** [comment] 2022-02-12 11:14
Yes. The dGPU is fully powered off, the power state does not change, no modules capable of driving the dGPU are loaded into the kernel, etc. I am 100% certain that at the time of testing the dGPU is not active. The whole point of this setup is so that I can have assurance of whether or not the dGPU is active for the sake of power management.  

Do you have an opengl reference/low-power benchmark you want me to use? Because the first one that comes to mind, glxgears, runs just fine, even when the dGPU is forcibly disabled. I've used glxinfo to double check that mesa/i915 is being used to render opengl in normal operation as well, fwiw.

**Comment by chrisduerr** [comment] 2022-02-15 11:19
> Do you have an opengl reference/low-power benchmark you want me to use? Because the first one that comes to mind, glxgears, runs just fine, even when the dGPU is forcibly disabled. I've used glxinfo to double check that mesa/i915 is being used to render opengl in normal operation as well, fwiw.

I'm not sure what you could use, but you'd have to use something that actually blocks on vsync. IIRC glxgears just pumps out frames as fast as possible.

And this is likely also what most applications using OpenGL that work will do. Something like Kitty use internal timers for their drawing which is something that has been considered for Alacritty too, but your GPU is still not behaving correctly (as far as I can tell at least), so breakage in applications is to be expected?

**Comment by paulwhiting** [comment] 2022-04-25 03:49
I am affected by this bug on macOS Monterey, alacritty version 0.10.1 (2844606).  It only occasionally manifests itself on its own, but when I ssh to a particular server it happens every 3 or 4 keystrokes.  For reference, if I use a different terminal such as iterm there is no delay.

**Comment by bobossler** [comment] 2022-05-06 20:26
I am also affected by this bug. It has been happening for several months running alacritty 0.10.1-rc1 from the repository, I am running on a System76 Meerkat with 32 GB of memory, Intel® Core™ i3-10110U CPU @ 2.10GHz × 4, Mesa Intel® UHD Graphics (CML GT2), a Gnome DE on X11, and Pop!_OS 22.04 LTS. The issue was also very noticeable under the Pop!_OS 21.10 release. I am running a current kernel: Linux system76-pc 5.17.5-76051705-generic #202204271406~1651504840~22.04~63e51bd SMP PREEMPT Mon May 2 15: x86_64 x86_64 x86_64 GNU/Linux, but the issue has spanned several kernel updates. Oh, I also have a dual monitor setup.

At first I thought I had isolated the issue to when alacritty had a full-screen window, but that wasn't the case. I can have two windows side-by-side and they will both lag. It also doesn't matter which monitor the windows are on; alacritty has been lagging everywhere. The lag happens at the command line, within vim, sqlite3, and other terminal-based programs. No other terminal emulator programs experience the lag. I have tried gnome-terminal, guake, xterm/uxterm, etc. The frequency of the lag is almost to the point of being unusable. I can't rely on my keystrokes being registered properly.

**Comment by ajukraine** [comment] 2022-06-24 23:04
> Alacritty has very bad input lag when running it on my setup. Usually, a character won't be rendered until the next keypress occurs or about 5 seconds later, whichever comes first.

I have very same issue on my MacBook Pro 16. It also occurs in Kitty terminal. But is not reproducible with iTerm2.
It really is a pain to use Alacritty (and Kitty) for daily work with such inconsistent lags...

**Comment by kchibisov** [comment] 2023-06-12 05:49
I'll close this given that rendering scheduling was changed.

The reason you've asked to test on Wayland at some point, was solely due to different rendering on it.

The macOS issue is likely due to apple OpenGL weird behavior.

Open a new issue if the problem is present.

**Closed by kchibisov** 2023-06-12 05:49 UTC
