### ISSUE TITLE
Powershell starts up with extra stuff prepended to the path

### ISSUE THREAD

**Issue by raphtlw** [alacritty/alacritty#3325] opened 2020-02-11 10:36 UTC
### System

OS: Windows
Version: 0.4.1
Windows: ConPTY

### Logs

Font/Terminal size: Device pixel ratio: 1.5, Width: 1122, Height: 642

### What happens
When I open the terminal in a directory, it has this word prepended to the path: `Microsoft.PowerShell.Core\FileSystem::\\?`

**Comment by chrisduerr** [comment] 2020-02-11 14:20
Duplicate of https://github.com/alacritty/alacritty/issues/3198.

**Closed by chrisduerr** 2020-02-11 14:20 UTC
