### ISSUE TITLE
Wrong position of cursor with oh my zsh and prezto

### ISSUE THREAD

**Issue by jansedlon** [alacritty/alacritty#3016] opened 2019-11-25 09:09 UTC
Which operating system does the issue occur on?
MacOS Catalina

I have installed oh-my-zsh alongside with prezto. When I'm in a directory which is not a git repository, everything is fine (first screenshot).. But when I'm in a directory which IS a git repository, cursor is moved by 3 positions to the left. Any idea how to fix it?

![image](https://user-images.githubusercontent.com/13948180/69526941-91c8e180-0f6b-11ea-8c29-ac5a76e3b77d.png)
![image](https://user-images.githubusercontent.com/13948180/69526982-a311ee00-0f6b-11ea-9d1c-bc17e4e79248.png)

PS: It works fine in JetBrains terminal and default MacOS terminal

**Comment by chrisduerr** [comment] 2019-11-25 13:05
Can you reproduce this when launching Alacritty from iTerm?

**Comment by andrewnicolalde** [comment] 2020-05-08 16:57
This is happening to me as well, though just with oh-my-zsh. Any way I can help?

**Comment by kchibisov** [comment] 2020-05-08 17:06
Could someone try the latest master?

**Comment by scotstan** [comment] 2020-08-02 05:00
Work around № 1:

With alacrity 5.0 and zsh, I disabled zsh-syntax-highlighting plugin. That fixed readline style cursor manipulation for me. 

Work around № 2:
Upgrade your zsh-syntax-highlighting (current version for me at the time is 0.8.0-alpha)

**Comment by chrisduerr** [comment] 2020-08-02 15:41
Closing since the author hasn't replied for a while and it's probably not an Alacritty issue.

**Closed by chrisduerr** 2020-08-02 15:41 UTC
Labels: A - needs repro, H - macos
