### ISSUE TITLE
alacritty doesn't show up in nvidia-smi or nvtop

### ISSUE THREAD

**Issue by ChocolateOverflow** [alacritty/alacritty#4737] opened 2021-01-26 07:19 UTC
### System

OS: Manjaro Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: X11, bspwm

### Logs

Crashes: N/A
Font/Terminal size:

```
Created log file at "/tmp/Alacritty-13112.log"
[2021-01-26 14:11:42.413795068] [INFO ] [alacritty] Welcome to Alacritty
[2021-01-26 14:11:42.413966071] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/jco/.config/alacritty/alacritty.yml"
[2021-01-26 14:11:42.442477487] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-01-26 14:11:42.444957998] [DEBUG] [alacritty] Estimated DPR: 1.5
[2021-01-26 14:11:42.445048252] [DEBUG] [alacritty] Estimated window size: None
[2021-01-26 14:11:42.445072536] [DEBUG] [alacritty] Estimated cell size: 8 x 16
[2021-01-26 14:11:42.543275571] [INFO ] [alacritty] Device pixel ratio: 1.5
[2021-01-26 14:11:42.549132283] [INFO ] [alacritty] Initializing glyph cache...
[2021-01-26 14:11:42.550524183] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-01-26 14:11:42.552227504] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-01-26 14:11:42.554003072] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-01-26 14:11:42.555918079] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-01-26 14:11:42.564682219] [INFO ] [alacritty] ... finished initializing glyph cache in 0.015524056s
[2021-01-26 14:11:42.564913223] [INFO ] [alacritty] Cell size: 8 x 16
[2021-01-26 14:11:42.564944710] [INFO ] [alacritty] Padding: 0 x 0
[2021-01-26 14:11:42.564950526] [INFO ] [alacritty] Width: 800, Height: 600
[2021-01-26 14:11:42.575132650] [INFO ] [alacritty] PTY dimensions: Line(37) x Column(100)
[2021-01-26 14:11:42.580884646] [INFO ] [alacritty] Initialisation complete
[2021-01-26 14:11:42.581190623] [DEBUG] [alacritty_terminal] New num_cols is 119 and num_lines is 65
[2021-01-26 14:11:42.583718787] [INFO ] [alacritty] Padding: 0 x 0
[2021-01-26 14:11:42.583738893] [INFO ] [alacritty] Width: 954, Height: 1054
[2021-01-26 14:11:42.689881915] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-01-26 14:11:45.358049220] [INFO ] [alacritty] Goodbye
```

Keyboard and bindings: `https://github.com/ChocolateOverflow/dotfiles_arch/blob/main/config/alacritty/alacritty.yml`

```
$ nvidia-smi
Tue Jan 26 14:13:37 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8    N/A /  N/A |      4MiB /  4042MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       840      G   /usr/lib/Xorg                       4MiB |
+-----------------------------------------------------------------------------+
```

```
$ lspci | grep -i nvidia
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
```

```
$ pacman -Qs nvidia
local/cuda 11.2.0-3
local/lib32-nvidia-utils 460.32.03-1
local/libvdpau 1.4-1
local/linux54-nvidia 460.32.03-3 (linux54-extramodules)
local/mhwd-nvidia 460.32.03-1
local/mhwd-nvidia-340xx 340.108-1
local/mhwd-nvidia-390xx 390.141-1
local/nvidia-prime 1.0-4
local/nvidia-utils 460.32.03-1
local/nvtop 1.1.0-1
local/opencl-nvidia 460.32.03-1
local/pycuda-headers 2020.1-5
```

Even when I open 47 (seemingly the upper limit) alacritty terminals, it doesn't appear on `nvidia-smi` or `nvtop` at all. Is there something I have to set up to get alacritty to use my GPU and NVIDIA?

**Comment by chrisduerr** [comment] 2021-01-26 08:01
Is your GPU enabled? Or are you running off the iGPU?

**Comment by ChocolateOverflow** [comment] 2021-01-27 03:13
@chrisduerr I'm not knowledgeable about GPU settings so I don't know about iGPU but I'm pretty sure my GPU is working, seeing as Xorg is using the GPU.

**Comment by chrisduerr** [comment] 2021-01-27 09:04
Sounds like a duplicate of https://github.com/alacritty/alacritty/issues/3587 to me then.

**Closed by chrisduerr** 2021-01-27 09:04 UTC

**Comment by ChocolateOverflow** [comment] 2021-01-28 08:33
I believe my laptop has only 1 GPU, so either everything is on the same GPU, or nothing is using the GPU. #3587 seems to deal with 2 separate GPUs, so it's probably not a duplicate.

**Comment by chrisduerr** [comment] 2021-01-28 08:58
It's not possible to run Alacritty without a GPU. So you're probably wrong in one way or another.
