### ISSUE TITLE
I get this burn-in effect when opacity is < 1 and I maximize to SimpleFullScreen from Windowed.

### ISSUE THREAD

**Issue by mrillusi0n** [alacritty/alacritty#4131] opened 2020-08-15 10:23 UTC
### System

OS: macOS
Version: `alacritty 0.5.0-dev (058b036)

![image](https://user-images.githubusercontent.com/37063502/90310467-21099100-df0f-11ea-9f19-51e91a8ee165.png)

**Comment by chrisduerr** [comment] 2020-08-15 14:34
Duplicate of #889.

**Closed by chrisduerr** 2020-08-15 14:34 UTC
