### ISSUE TITLE
Right mouse to paste only -- no selection?

### ISSUE THREAD

**Issue by tmpm697** [alacritty/alacritty#5236] opened 2021-06-14 08:44 UTC
I have set right mouse click to paste like below:
```
mouse_bindings:
 - { mouse: Right, action: Paste }
```

But seem by default left/right-mouse used to select text on terminal. and with above settings, when I select text with left mouse to put to clipboard and right mouse to paste to prompt, it pastes the text but also have selection function work depends on where cursor is.

How to have left mouse to select -- default and right  mouse to paste only  -- no select text?

**Comment by chrisduerr** [comment] 2021-06-14 08:50
Duplicate of #4132.

**Closed by chrisduerr** 2021-06-14 08:50 UTC

**Comment by tmpm697** [comment] 2023-06-29 14:35
this seem not really duplicated?

with this:
```
mouse_bindings:
  - { mouse: Right, action: Paste }
```

I want to paste with right mouse click `and` i don't want same right mouse click to also able to select text.
@chrisduerr 

currently right mouse click do both feature with above setting: paste and select text.
