### ISSUE TITLE
Mac Os x [ ] issue

### ISSUE THREAD

**Issue by MyraBaba** [alacritty/alacritty#3669] opened 2020-05-01 18:46 UTC
I installed from brew cask ...

in my mac os x I couldn't find the write  [ ] .

Normally its should be typed from OPTION-8 and OPTION-9 .

How can I map the same as in mac osx for [ ] ?

Best

**Comment by chrisduerr** [comment] 2020-05-01 19:00
Which keyboard layout are you using?

**Comment by MyraBaba** [comment] 2020-05-01 19:02
I an new to alacritty but I am using : https://github.com/makccr/dot/blob/master/.config/alacritty/alacritty.yml 
config.

What should I do ?

**Comment by chrisduerr** [comment] 2020-05-01 19:12
I'm curious about your system keyboard layout. Are you using the US QWERTY layout?

**Comment by MyraBaba** [comment] 2020-05-01 19:13
Turkish Q

**Comment by MyraBaba** [comment] 2020-05-01 19:14
My keyboard working very in normal shell and can type [ ] .

But in alacritty I cant.

**Comment by thoughtarray** [comment] 2020-05-02 04:31
I can repro this. I was able to get the square brackets to output like so on MacOS:
Option-8 then Option-8 again to output "["
Option-8 then Option-9 to output "]"

Seems to be some kind of keybinding. I looked at the config and don't see any default bindings that might be capturing it. Option and a lot of the number keys don't work.

**Comment by chrisduerr** [comment] 2020-05-03 23:24
This is a duplicate of #458.

**Closed by chrisduerr** 2020-05-03 23:24 UTC
Labels: H - macos

**Comment by pslobo** [comment] 2020-07-01 12:14
I'm seeing this issue too, but not entirely sure it is the same thing happening in #458. I'm using a QWERTY (pt-PT) layout, and the exact same things as the OP happens here, with the addition, that when I try and type Option-8 and then Option-8 again, nothing happens and I can't type anything further until I type Ctrl-C

With `--print-events` I see this in a nutshell (truncated for brevity)

```
[2020-07-01 13:09:04.837249000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
[2020-07-01 13:09:04.837356000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: ReceivedCharacter('[') }
[2020-07-01 13:09:04.837402000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
...
[2020-07-01 13:09:06.019188000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
[2020-07-01 13:09:06.019269000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: ReceivedCharacter('[') }
...
[2020-07-01 13:09:06.020017000] [INFO] glutin event: UserEvent(MouseCursorDirty)
...
[2020-07-01 13:09:06.127106000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
...
# Tried to type 2 twice
[2020-07-01 13:09:08.386472000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 19, state: Pressed, virtual_keycode: Some(Key2), modifiers: (empty) }, is_synthetic: false } }
[2020-07-01 13:09:08.386583000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: ReceivedCharacter('2') }
[2020-07-01 13:09:08.386664000] [INFO] glutin event: MainEventsCleared
[2020-07-01 13:09:08.386723000] [INFO] glutin event: RedrawEventsCleared
[2020-07-01 13:09:08.387446000] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 365859262508837 }, requested_resume: None })
[2020-07-01 13:09:08.387577000] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2020-07-01 13:09:08.387679000] [INFO] glutin event: MainEventsCleared
[2020-07-01 13:09:08.387743000] [INFO] glutin event: RedrawEventsCleared
[2020-07-01 13:09:08.465927000] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 365859262864448 }, requested_resume: None })
[2020-07-01 13:09:08.466258000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 19, state: Released, virtual_keycode: Some(Key2), modifiers: (empty) }, is_synthetic: false } }
[2020-07-01 13:09:08.466351000] [INFO] glutin event: MainEventsCleared
[2020-07-01 13:09:08.466406000] [INFO] glutin event: RedrawEventsCleared
[2020-07-01 13:09:09.204845000] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 365859341541816 }, requested_resume: None })
[2020-07-01 13:09:09.205114000] [INFO] glutin event: MainEventsCleared
[2020-07-01 13:09:09.205186000] [INFO] glutin event: RedrawEventsCleared
[2020-07-01 13:09:09.205252000] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 365860080306689 }, requested_resume: None })
[2020-07-01 13:09:09.205371000] [INFO] glutin event: MainEventsCleared
[2020-07-01 13:09:09.205446000] [INFO] glutin event: RedrawEventsCleared
[2020-07-01 13:09:09.205513000] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 365860080568550 }, requested_resume: None })
[2020-07-01 13:09:09.209408000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 19, state: Pressed, virtual_keycode: Some(Key2), modifiers: (empty) }, is_synthetic: false } }
[2020-07-01 13:09:09.209540000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: ReceivedCharacter('2') }
...
# Gave up and typed Ctrl-C
[2020-07-01 13:09:10.566639000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[2020-07-01 13:09:10.566695000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: ModifiersChanged(CTRL) }
[2020-07-01 13:09:10.566730000] [INFO] glutin event: MainEventsCleared
[2020-07-01 13:09:10.566760000] [INFO] glutin event: RedrawEventsCleared
[2020-07-01 13:09:11.081144000] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 365861441847306 }, requested_resume: None })
[2020-07-01 13:09:11.081746000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 8, state: Pressed, virtual_keycode: Some(C), modifiers: CTRL }, is_synthetic: false } }
[2020-07-01 13:09:11.081805000] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437542238928)), event: ReceivedCharacter('\u{3}') }
[2020-07-01 13:09:11.081837000] [INFO] glutin event: MainEventsCleared
```
