### ISSUE TITLE
Window borders useless on Linux (Fedora, Wayland)

### ISSUE THREAD

**Issue by leehambley** [alacritty/alacritty#3299] opened 2020-02-06 08:22 UTC
Since a recent Fedora update (I'm not sure which of the 3000 packages updates is responsible) the window border no longer receives events, and "clicks through" as if it is not there, e.g clicking on the border, with another app behind focuses the other app.

This makes it impossible to use Alacritty as the window is immobile, cannot be dragged or resized.

![Screenshot from 2020-02-06 09-16-57](https://user-images.githubusercontent.com/18952/73918517-11efb980-48c2-11ea-9111-aaec68d57190.png)

## Relevant Alacritty Config

Here's everything from the `window:` section

```
window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: full

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Windowed

  # Window title
  title: Alacritty

  # Window class (Linux only):
  class: Alacritty
```

### System

OS: Linux
Version: 0.4.1
Linux/BSD: Wayland, Gnome

### Logs

Logs don't seem relevant, except to confirm that clicking on the window border/etc does nothing, and triggers no events that alacritty can see. Here's the last few lines anyway:

```
[2020-02-06 09:19] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 981, tv_nsec: 365511191 }, requested_resume: None })
[2020-02-06 09:19] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-06 09:19] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-06 09:19] [INFO] glutin event: MainEventsCleared
[2020-02-06 09:19] [INFO] glutin event: RedrawEventsCleared
[2020-02-06 09:19] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 981, tv_nsec: 382006801 }, requested_resume: None })
[2020-02-06 09:19] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-06 09:19] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-06 09:19] [INFO] glutin event: MainEventsCleared
[2020-02-06 09:19] [INFO] glutin event: RedrawEventsCleared
[2020-02-06 09:19] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 981, tv_nsec: 398422093 }, requested_resume: None })
[2020-02-06 09:19] [INFO] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94852825220816))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(C), modifiers: CTRL }, is_synthetic: false } }
[2020-02-06 09:19] [INFO] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94852825220816))), event: ReceivedCharacter('\u{3}') }
[2020-02-06 09:19] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-06 09:19] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-06 09:19] [INFO] glutin event: MainEventsCleared
[2020-02-06 09:19] [INFO] glutin event: RedrawEventsCleared
^C
```

**Comment by leehambley** [comment] 2020-02-06 08:25
Update, I went back to the docs to see if something about my config was too old to be read properly anymore, and found out that it's recommended in the readme to set `env WINIT_UNIX_BACKEND=x11 alacritty` I can confirm this makes things work.

Weirdly things have worked fine without this for the last... nearly a half year or more?

**Comment by kchibisov** [comment] 2020-02-06 10:23
this is a GNOME (mutter) bug

duplicate of  #3258

**Closed by kchibisov** 2020-02-06 10:23 UTC
Labels: F - duplicate
