### ISSUE TITLE
Couldn't find any pixel format that matches the criterias

### ISSUE THREAD

**Issue by shoober420** [alacritty/alacritty#1268] opened 2018-04-24 04:18 UTC
Using Arch Linux with X11 which is fully up too date, an error occurs when trying to open alacritty.

```
Alacritty encountered an unrecoverable error:

Error creating GL context; Couldn't find any pixel format that matches the criterias.
```

I'm using a NVIDIA Geforce 760 GTX video card with the latest propietary video drivers (396.18).

**Comment by Sas-18** [comment] 2018-04-25 05:46
Hope it's OK to add to this thread as I have the exact same error. Attaching files (glxinfo, etc)..

**uname -a:** Linux Unimatrix-18 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Running Linux Mint 18 (up to date) with X11, Xinerama, and Nvidia 384. Video cards = 2 x Nvidia GT-710.

NOT using composite extension (apparently it doesn't like Xinerama).

Alacritty build was cloned fresh from GIT; tried cleaning and refreshing cache, rebuilt, still the same.

Tried using LD_PRELOAD to insert the libnvidia-wayland-egl.so into the linker when running Alacritty to see if that would point it in the right direction but it made no difference.

[INSTALLED_PKGS.txt](https://github.com/jwilm/alacritty/files/1945595/INSTALLED_PKGS.txt)
[GLX_INFO.txt](https://github.com/jwilm/alacritty/files/1945598/GLX_INFO.txt)
[GLX_GEARS.txt](https://github.com/jwilm/alacritty/files/1945597/GLX_GEARS.txt)

If there's some more data that might help, please do tell, I'll be happy to supply it.

Sas-18

**Comment by Sas-18** [comment] 2018-04-26 22:26
[This other Github thread about Piston](https://github.com/PistonDevelopers/piston/issues/1202) found me a workaround and apparent cause, which seems to come from a commit in Mesa between 17.1 to 17.2 involving sRGB pixel format... I don't understand what Mesa does on my system anyway-- I thought the Nvidia driver dealt with everything, but whatever, I can read about that later. Maybe I need to re-install something :/

Anyway, editing `Alacritty/src/window.rs` to disable sRGB as follows:

`192:        .with_srgb(false)`

and just in case, since I have composite disabled on my machine, and I read something about Alacritty starting up transparent at first, and knowing that things that _need_ composite/transparency _always_ crash when they can't have it, I also changed:

`211:        .with_transparency(false)`

After that, Alacritty compiled & ran for the first time for me. Started fast, looked good, though without any window decorations, I wonder how come-- by design, or a WM_HINTS issue? I'm using `metacity --no-composite` for the WM.

**Comment by chrisduerr** [comment] 2018-04-26 22:46
Making use of `.with_transparency(true)` without a compositor should not crash alacritty but instead just lead to no transparency showing up.

And regarding the `.with_srgb` part, alacritty should already start using `.with_srgb(false)` and only retry with srgb enabled if it is required and `.with_srgb(false)` failed. You can see that part of the code here: 
https://github.com/jwilm/alacritty/blob/master/src/window.rs#L213-L214

This has been updated kinda recently so maybe you're just not running the latest master?

I don't personally use window decorations but they should show up I think. At least I've never seen that issue before. Assuming that the following line is present:
https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L34

**Comment by Sas-18** [comment] 2018-04-26 23:04
Just to verify, it was indeed the latest master, cloned fresh. I will be going though all this again a bit later, having just re-installed my nvidia driver. I'll be starting with a fresh master again, I'll leave the source code alone and see what happens.
And yes, the lack of decorations was my fault :)

**Comment by shoober420** [comment] 2018-04-27 02:15
I did do a git pull from the latest master when testing this, so thats not the reason. I too, have the composite extension disabled in my xorg.conf file. I will the workaround from Sas-18 to try and debug this. Here is my xorg.conf file just for reference.

[xorg.txt](https://github.com/jwilm/alacritty/files/1953622/xorg.txt)

**Comment by Sas-18** [comment] 2018-04-27 04:02
Fresh clone of Master, followed by "cargo update", all after a fresh install of Nvidia driver, and a reboot for good measure.. Same as before; Alacritty will not run:

```
~/Downloads/alacritty $ RUST_BACKTRACE=1 ./target/release/alacritty

Alacritty encountered an unrecoverable error:

Error creating GL context;
Couldn't find any pixel format that matches the criterias.

```
Here's some current system config files, ldconfig output, compile log and stuff:

[reboot: Xorg.0.log](https://github.com/jwilm/alacritty/files/1953779/Xorg.0.log)
[ldconfig -p](https://github.com/jwilm/alacritty/files/1953734/LDCONFIG.txt)
[xorg.conf](https://github.com/jwilm/alacritty/files/1953736/xorg.conf.txt)
[compiling Alacritty log](https://github.com/jwilm/alacritty/files/1953740/compiling.log)
[GLXINFO | grep GL](https://github.com/jwilm/alacritty/files/1953744/GLXINFO.txt)
[GLXINFO | grep sRGB](https://github.com/jwilm/alacritty/files/1953768/GLXINFO_grep_sRGB.txt)
[GLXINFO](https://github.com/jwilm/alacritty/files/1953745/GLXINFO_FULL.txt)


After editing src/window.rs line 192 as follows:

192:  `        .with_srgb(false)`

 ... and Alacritty compiles **BUT DOES NOT RUN**:

```
~/Downloads/alacritty $ cargo clean 
~/Downloads/alacritty $ cargo build --release

   Compiling winit v0.11.3
warning: unused variable: `srgb`
   --> src/window.rs:189:5
    |
189 |     srgb: bool,
    |     ^^^^ help: consider using `_srgb` instead
    |
    = note: #[warn(unused_variables)] on by default

    Finished release [optimized + debuginfo] target(s) in 1267.84 secs

$ RUST_BACKTRACE=1 ./target/release/alacritty

Alacritty encountered an unrecoverable error:

	Error creating GL context;
        Couldn't find any pixel format that matches the criterias.

```

So, as you rightly suggested Christian Duerr, the srgb part does not appear to be the cause. Currenly rebuilding with line 192 unedited, but with the transparency disabled on line 211:

211:`           .with_transparency(false)`

... will update shortly.

**Comment by shoober420** [comment] 2018-04-27 04:04
With the debugging information from Sas-18, I have found the culprit. It is indeed "211: .with_transparency(true)". When compiling with transparency set to "false", alacritty launches and runs great. This must be because we both have the composite extension disabled on our systems for the X.Org dispay server. I personally don't use transparency anyway, so I will keep it disabled, as well as vsync.

**Comment by Sas-18** [comment] 2018-04-27 04:32
Recompiling Alacritty with the transparency disabled, solves the issue for me.
```
$ RUST_BACKTRACE=1 ./target/release/alacritty -v
Welcome to Alacritty.
Configuration loaded from /home/brina18/.config/alacritty/alacritty.yml
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.21728049
width: 884, height: 556
Cell Size: (11 x 23)
PTY Dimensions: Line(24) x Column(80)
Font size changed: Size(32)
width: 884, height: 556
Goodbye.
```
I'm figuring it's my lack of COMPOSITE extension. Not the first time something won't run without one/both of COMPOSITE or RandR, but composite doesn't cooperate with Xinerama, and RandR doesn't detect the second video card. And Nouveau (though progressing nicely) doesn't stack up against the Nvidia binary for performance, nor provide a working Xinerama setup.

For the record: if I try to enable transparency for background color on e.g. my desktop panel (mate-panel or gnome-panel) the panel will instantly start crashing and restarting, until I set the color back to 100% opaque.

**Comment by chrisduerr** [comment] 2018-04-27 14:13
Okay, I thought you were just not running a compositor, but if you actually have disabled the compositing extension, the alpha value of rgba will not be present and throw an error.

There have been quite a few errors which originate from `with_transparency(true)` and I would propose that live config reload for this flag should be disabled. So instead the transparency is set at startup which would allow us to use `with_transparency(transparency_setting)`. I'll open a PR for this in a bit.

**Comment by chrisduerr** [comment] 2018-04-27 14:52
I've opened a PR which starts alacritty using `with_transparency(false)` if the opacity is set to `1.0` on startup. This should fix the issues mentioned. Feel free to test if you have the time to. :)

**Comment by Sas-18** [comment] 2018-04-27 19:09
My Git skills proved inadequate for pulling in your change so I downloaded the archive from your fork.
It works for me, but I'm not sure it's working exactly as expected:
Even if I change the opacity value to something other than 1.0 it starts up for me anyway. I expected it to return the error message. Is this the proper behaviour?

Thanks!

**Comment by chrisduerr** [comment] 2018-04-27 20:48
No it's not. That's super weird. It should start using `with_transparency(true)` if you start it with transparency set to anything but `1.0`. But chances are you might have just done something wrong with the config, if it starts up now but master doesn't, it should work as intended.

**Comment by shoober420** [comment] 2018-04-28 17:30
Having another instance open might have something to do with issue

**Comment by chrisduerr** [comment] 2018-04-28 17:58
@Sas-18 The issue with live-config-reload could be related to a broken config file. You can test that by starting alacritty from a different terminal, then start it using a fixed config file and try changing a value which is certain to support live-config-reload (like the terminal colors).

**Comment by Sas-18** [comment] 2018-04-29 03:30
@shoober420 No, I have not experienced that situation with processes that won't end. Processes terminate normally for me.

> @Sas-18 The issue with live-config-reload could be related to a broken config file. You can test that by starting alacritty from a different terminal, then start it using a fixed config file and try changing a value which is certain to support live-config-reload (like the terminal colors).

@chrisduerr I don't want to totally hijack this thread (with live reload, separate issue from the OP issue) but following your suggestions didn't discover me anything so far; live reload does not seem to work for me, and I have no evidence that the config file is broken. I'll see if there's a better place to discuss it though, i.e. an open issue about live-reload :) and if I can't find it, I'll create a new issue.

Thank you both for your input!

**Comment by chrisduerr** [comment] 2018-04-29 09:52
Yeah please do, thanks.

**Comment by C-Bouthoorn** [comment] 2018-05-02 16:43
Not 100% sure it's relevant to this thread, but the sRGB issue with Mesa has been fixed with `mesa 18.*` ( See https://github.com/PistonDevelopers/piston/issues/1202 for more information. )

**Comment by chrisduerr** [comment] 2018-05-02 16:52
It might be relevant to this issue, but the PR to mitigate seems like a good addition regardless, unless `mesa 18.*` magically fixed all the other issues related to transparency.

**Comment by paul-tcell** [comment] 2018-12-12 23:05
same issue on a virtualbox guest running linux mint 18 (which is basically ubuntu bionic)

```
$ inxi -G
Graphics:  Card: InnoTek Systemberatung VirtualBox Graphics Adapter
           Display Server: x11 (X.Org 1.19.6 ) drivers: (unloaded: fbdev,vesa) FAILED: modesetting
           Resolution: 3840x2160@60.00hz
           OpenGL: renderer: Chromium version: 2.1 Chromium 1.9
```
kernel: 4.15.0-20-generic
wm:  lightdm / cinnamon
mesa: 18.0.5-0ubuntu0~18.04.1

**Comment by chrisduerr** [comment] 2018-12-12 23:18
@paul-tcell can you check if #1279 fixes this problem for you?

**Comment by paul-tcell** [comment] 2018-12-12 23:34
> @paul-tcell can you check if #1279 fixes this problem for you?

that branch gives me this error:
```
[2018-12-12 15:30] [ERROR] Alacritty encountered an unrecoverable error:

	There was an error initializing the shaders: failed compiling shader: ERROR: 0:14: '' :  version '330' is not supported
ERROR: 0:14: '' : syntax error: #version
ERROR: 0:15: 'layout' : syntax error: syntax error
```

which maybe means maybe this fixes this issue and I am hitting the next one 🙂 
looks like https://github.com/jwilm/alacritty/issues/128

**Comment by chrisduerr** [comment] 2018-12-12 23:48
I'm still unsure if #1279 is worth merging at this point, but I guess VirtualBox is something to consider here.

**Comment by dvergeylen** [comment] 2019-02-14 15:23
I can confirm removing `transparency(true)` makes it work.

Setup: Debian testing + nvidia proprietary drivers installed + bumblebee (optimus card Nvidia + intel)

Any chance to see #1279 merged some day? 😇

**Comment by chrisduerr** [comment] 2019-02-14 16:32
I don't think #1379 is the correct way forward with this issue. I'd rather have a compile-time flag for this than hurt the large majority of users by a bug that only affects a few and isn't actually fixed but just worked around with that PR.

**Comment by kchibisov** [comment] 2019-09-16 12:21
Could someone try to reproduce this issue on #2438?

**Comment by cronyakatsuki** [comment] 2022-10-14 11:08
Also having this problem now with an optimus laptop with amd igpu with nvidia gpu, using amd gpu normally still get the error.
> alacritty -vv output
```
Created log file at "/tmp/Alacritty-3586.log"
[0.000011873s] [INFO ] [alacritty] Welcome to Alacritty
[0.000106717s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000135562s] [INFO ] [alacritty] Running on X11
[0.001187790s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/crony/.config/alacritty/alacritty.yml"
[0.006579747s] [DEBUG] [alacritty] Loading "FiraCode Nerd Font" font
[0.023295488s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.029726962s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.035914969s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.042076926s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.047058634s] [DEBUG] [alacritty] Estimated scaling factor: 1.25
[0.047126730s] [DEBUG] [alacritty] Estimated window size: None
[0.047139022s] [DEBUG] [alacritty] Estimated cell size: 12 x 26
Error: Error creating GL context; Received multiple errors:
	Couldn't find any pixel format that matches the criteria.
	Couldn't find any pixel format that matches the criteria.

[0.166379037s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-3586.log"
Error: "Event loop terminated with code: 1"
```

**Comment by kchibisov** [comment] 2022-10-14 11:14
Try #6390.

**Comment by cronyakatsuki** [comment] 2022-10-15 10:57
> Try #6390.

@kchibisov #6390 Works like a charm for me with no problems.

**Closed** 2022-11-03 16:37 UTC
Labels: H - linux
