### ISSUE TITLE
alacritty window decorations stop working after changing tty

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#3543] opened 2020-04-01 01:12 UTC
fedora 31 igpu haswell
0.4.2
Wayland, Gnome up to date

After switching to a different tty and back to gnome the window decorations of the terminal stop working

not responsive to mouse over or clicks
cannot move windows
new alacritty windows are fully operational
existing terminals appear fully functional

all other windows not affected

**Comment by chrisduerr** [comment] 2020-04-01 16:51
Can you reproduce this with the examples of our depedency [glutin](https://github.com/rust-windowing/glutin)?

If you have a Rust toolchain installed, you can test this using `cargo run --example window`.

**Comment by kchibisov** [comment] 2020-04-01 16:55
This bug doesn't require repro, since I can repro it myself and I know why it happens. The bug is in SCTK 0.6.6, since it should recreate pointer/keyboard/touch after tty switch, which it doesn't do, this bug is fixed in SCTK 0.8.0 so it could be fixed after winit update to 0.8.0 or back porting the fix to 0.6.x branch, which I don't really found of, since it's a bit complex.

**Comment by kchibisov** [comment] 2020-10-07 14:45
Fixed by #4275.

**Closed by kchibisov** 2020-10-07 14:45 UTC
Labels: A - deps, B - bug, C - waiting on dependency, DS - Wayland
