### ISSUE TITLE
Expand `~` character to home directory in import path

### ISSUE THREAD

**Issue by EdenEast** [alacritty/alacritty#4334] opened 2020-10-22 22:24 UTC
My configuration is managed under source control. It is used on multiple machine and multiple platforms. This means that
I cannot have absolute paths to import files. I format the paths based on my users `~/` directory. This works well on
Linux but on my windows machine it does not understand `~`.

Thoughts on the expansion of `~`:
- If user sets HOME env use that
- If HOME is not set then use `dirs::home_dir()`
  - Windows: `C:\Users\{Username}`
  - Mac: `/Users/{Username}`
  - Linux: `/home/{Username}`

**Comment by chrisduerr** [comment] 2020-10-22 22:30
Duplicate of https://github.com/alacritty/alacritty/issues/4157.

**Closed by chrisduerr** 2020-10-22 22:30 UTC
