### ISSUE TITLE
Primary selection not updated

### ISSUE THREAD

**Issue by Depado** [alacritty/alacritty#4735] opened 2021-01-25 17:25 UTC
### System

OS: Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: Gnome Wayland (Manjaro)

### Issue

I'm using primary selection a lot. I've recently installed alacritty on my new system, and for some reason, I can select some text once, paste it using middle mouse click, and if I select another text in the terminal the primary selection buffer isn't updated, which means when I do another middle mouse click it pastes the first content I selected. I don't know if that's an issue with alacritty itself or my system but this doesn't happen in applications like Firefox and such. Also, weird behavior, if I change my current app (alt-tab, change of virtual desktop), I am able to select and paste again, only once, again.

**Comment by chrisduerr** [comment] 2021-01-25 17:36
Are there any output logs?

**Comment by Depado** [comment] 2021-01-25 21:01
Not that I can see. The `-vvv` logs doesn't show anything when I select, and with events shown there's so much output I can't distinguish what's going on. I'll try to filter that out.

**Comment by chrisduerr** [comment] 2021-01-25 21:29
The alt tabbing sounds strange to me. If the clipboard thread crashed, I would understand, but if it recovers that sounds like everything should be working fine.

Does copying to the clipboard work, not the primary selection buffer? If so that should mean that Alacritty is still able to communicate properly with Wayland. If that works just fine, I'd honestly try to test with a different compositor since GNOME is usually a bit suspect.

**Comment by alexey-mercari** [comment] 2021-01-26 06:47
happens to me as well. 
100% reproducable.

I can provide any logs, just tell me what is needed.

```
$ alacritty --version
alacritty 0.7.1 (a852eb85)

$ uname -a
Linux workd 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 3.38.3

$ env | grep XDG
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
```

**Comment by axxapy** [comment] 2021-01-26 06:48
happens to me as well. 
100% reproducible.

I can provide any logs, just tell me what is needed.

```
$ alacritty --version
alacritty 0.7.1 (a852eb85)

$ uname -a
Linux workd 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 3.38.3

$ env | grep XDG
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
```

**Comment by Depado** [comment] 2021-01-26 09:42
Note that I wasn't facing that issue when I wasn't on Wayland. Otherwise, that's the exact same thing as @axxapy. Tried grepping on the output of `alacritty --print-events` but I quite don't know what I'm looking for to be honest.

**Comment by apexo** [comment] 2021-01-26 14:53
> Does copying to the clipboard work, not the primary selection buffer? If so that should mean that Alacritty is still able to communicate properly with Wayland. If that works just fine, I'd honestly try to test with a different compositor since GNOME is usually a bit suspect.

Copy/Paste (Ctrl+Shift+C/Ctrl+Shift+V): same issue

**Comment by r-c-f** [comment] 2021-01-29 01:30
On Sway I get nothing of the sort, but I can reproduce this on Weston (for the clipboard only, seeing as how they don't even implement the primary selection). 
[Here's the full wayland log when it happens](https://github.com/alacritty/alacritty/files/5890994/wl-log.txt) if that is more useful.

**Comment by chrisduerr** [comment] 2021-01-29 09:56
@r-c-f By reproduce you mean you can not only get the clipboard to stop working, but it also starts working again once you switch between applications?

> The -vvv logs doesn't show anything when I select, and with events shown there's so much output I can't distinguish what's going on. I'll try to filter that out.

If someone can check the logs and grep for `clipboard` with at least warn and debug enabled, that might be helpful. There should be the errors `Unable to load text from clipboard` and `Unable to store text in clipboard` emitted when a store/load fails for some reason.

**Comment by jamesodhunt** [comment] 2021-01-29 10:15
I don't see any errors/warnings or any mention of clipboard or selection running as:

```bash
$ script -fec 'alacritty -vvv --print-events -o debug.log_level=Trace'
```

**Comment by chrisduerr** [comment] 2021-01-29 10:19
Just `alacritty -vvv | grep "clipboard"` should be sufficient. Though that would mean that the clipboard thinks it is operating smoothly, which kinda makes me suspect that it might be a compositor problem.

Maybe @vberger knows what's going on?

**Comment by apexo** [comment] 2021-01-29 10:28
> Just `alacritty -vvv | grep "clipboard"` should be sufficient.

This produces no output.

> which kinda makes me suspect that it might be a compositor problem.

Maybe, but other applications (firefox, konsole, gnome-terminal, thunderbird) don't seem to encounter this problem.

**Comment by r-c-f** [comment] 2021-01-29 10:59
@chrisduerr Indeed. Grepping through logs for the relevant wayland events while repeatedly copying random text without changing focus, one sees from alacritty a pattern like
```
[3126281.805]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@60)
[3126281.836]  -> wl_data_source@60.offer("text/plain;charset=utf-8")
[3126281.859]  -> wl_data_source@60.offer("UTF8_STRING")
[3126281.882]  -> wl_data_device@49.set_selection(wl_data_source@60, 3032)
[3128652.321]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@32)
[3128652.353]  -> wl_data_source@32.offer("text/plain;charset=utf-8")
[3128652.375]  -> wl_data_source@32.offer("UTF8_STRING")
[3128652.398]  -> wl_data_device@49.set_selection(wl_data_source@32, 3032)
[3130578.007]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@58)
[3130578.039]  -> wl_data_source@58.offer("text/plain;charset=utf-8")
[3130578.060]  -> wl_data_source@58.offer("UTF8_STRING")
[3130578.084]  -> wl_data_device@49.set_selection(wl_data_source@58, 3032)
[3133951.679]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@59)
[3133951.742]  -> wl_data_source@59.offer("text/plain;charset=utf-8")
[3133951.770]  -> wl_data_source@59.offer("UTF8_STRING")
[3133951.795]  -> wl_data_device@49.set_selection(wl_data_source@59, 3032)
[3135535.431]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@56)
[3135535.463]  -> wl_data_source@56.offer("text/plain;charset=utf-8")
[3135535.486]  -> wl_data_source@56.offer("UTF8_STRING")
[3135535.510]  -> wl_data_device@49.set_selection(wl_data_source@56, 3032)
[3137102.011]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@51)
[3137102.042]  -> wl_data_source@51.offer("text/plain;charset=utf-8")
[3137102.064]  -> wl_data_source@51.offer("UTF8_STRING")
[3137102.088]  -> wl_data_device@49.set_selection(wl_data_source@51, 3032)
[3138700.244]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@57)
[3138700.275]  -> wl_data_source@57.offer("text/plain;charset=utf-8")
[3138700.297]  -> wl_data_source@57.offer("UTF8_STRING")
[3138700.321]  -> wl_data_device@49.set_selection(wl_data_source@57, 3032)
[3140219.220]  -> wl_data_device_manager@42.create_data_source(new id wl_data_source@43)
[3140219.250]  -> wl_data_source@43.offer("text/plain;charset=utf-8")
[3140219.272]  -> wl_data_source@43.offer("UTF8_STRING")
[3140219.296]  -> wl_data_device@49.set_selection(wl_data_source@43, 3032)
```
and so on, whereas with weston-terminal (which is functioning as one expects) there is 
```
3022002.486] wl_data_device@12.data_offer(new id wl_data_offer@28959000)
[3022002.519] wl_data_offer@4278190081.offer("text/plain;charset=utf-8")
[3022002.540] wl_data_device@12.selection(wl_data_offer@4278190081)
[3022002.560]  -> wl_data_offer@4278190080.destroy()
[3022002.576] wl_data_source@25.send("text/plain;charset=utf-8", fd 8)
[3026536.804]  -> wl_data_device_manager@9.create_data_source(new id wl_data_source@27)
[3026536.834]  -> wl_data_source@27.offer("text/plain;charset=utf-8")
[3026536.857]  -> wl_data_device@12.set_selection(wl_data_source@27, 2872)
[3026537.008] wl_data_source@25.cancelled()
[3026537.032]  -> wl_data_source@25.destroy()
[3026537.050] wl_data_device@12.data_offer(new id wl_data_offer@28846456)
[3026537.077] wl_data_offer@4278190080.offer("text/plain;charset=utf-8")
[3026537.099] wl_data_device@12.selection(wl_data_offer@4278190080)
[3026537.121]  -> wl_data_offer@4278190081.destroy()
[3026537.139] wl_data_source@27.send("text/plain;charset=utf-8", fd 8)
[3028467.588]  -> wl_data_device_manager@9.create_data_source(new id wl_data_source@25)
[3028467.619]  -> wl_data_source@25.offer("text/plain;charset=utf-8")
[3028467.641]  -> wl_data_device@12.set_selection(wl_data_source@25, 2881)
[3028467.809] wl_data_source@27.cancelled()
[3028467.832]  -> wl_data_source@27.destroy()
[3028467.849] wl_data_device@12.data_offer(new id wl_data_offer@29271912)
[3028467.875] wl_data_offer@4278190081.offer("text/plain;charset=utf-8")
[3028467.895] wl_data_device@12.selection(wl_data_offer@4278190081)
[3028467.915]  -> wl_data_offer@4278190080.destroy()
[3028467.931] wl_data_source@25.send("text/plain;charset=utf-8", fd 8)
[3031082.332]  -> wl_data_device_manager@9.create_data_source(new id wl_data_source@27)
[3031082.363]  -> wl_data_source@27.offer("text/plain;charset=utf-8")
[3031082.385]  -> wl_data_device@12.set_selection(wl_data_source@27, 2890)
[3031082.536] wl_data_source@25.cancelled()
[3031082.558]  -> wl_data_source@25.destroy()
[3031082.575] wl_data_device@12.data_offer(new id wl_data_offer@29313056)
[3031082.601] wl_data_offer@4278190080.offer("text/plain;charset=utf-8")
[3031082.621] wl_data_device@12.selection(wl_data_offer@4278190080)
[3031082.641]  -> wl_data_offer@4278190081.destroy()
[3031082.656] wl_data_source@27.send("text/plain;charset=utf-8", fd 8)
[3090153.663]  -> wl_data_device_manager@9.create_data_source(new id wl_data_source@25)
[3090153.692]  -> wl_data_source@25.offer("text/plain;charset=utf-8")
[3090153.715]  -> wl_data_device@12.set_selection(wl_data_source@25, 2899)
[3090153.873] wl_data_source@27.cancelled()
[3090153.896]  -> wl_data_source@27.destroy()
```
At a glance I would guess the proximate cause is the absence of the `wl_data_source.cancelled()`, with the effect that the old `wl_data_source` -- still entirely valid so far as the protocol is concerned -- is being used, no matter how many new ones are successfuly created and offered to the compositor. Once another client sets the selection the cycle is broken as `cancelled()` is finally received. 

If the `WAYLAND_DEBUG` logs under GNOME show the same thing it would be unlikely to be a compositor bug, but even if it isn't I would strongly suspect that it's not really alacritty proper that is at fault but one in the chain of dependencies that are actually speaking Wayland to the compositor.

**Comment by jamesodhunt** [comment] 2021-01-29 11:02
It looks like a regression. It works for me if I build alacritty 0.6.0 (04cbf76).

A manual bisect shows the failure was introduced on this commit:

- https://github.com/alacritty/alacritty/commit/116faba7c607f1b2cb56c390d44b33a52603f642

So it looks like an issue with the https://github.com/Smithay/smithay-clipboard crate.

**Comment by chrisduerr** [comment] 2021-01-29 11:11
I've reported the issue upstream in https://github.com/Smithay/smithay-clipboard/issues/33. If anyone has additional information, I'd recommend posting it there.

**Comment by axxapy** [comment] 2021-02-02 06:00
I can confirm that currently working workaround is to downgrade alacritty to 0.6.0
Tested on gnome 3.38.3 (arch linux, kernel 5.10.11)

**Comment by dvergeylen** [comment] 2021-02-08 10:06
Fixed upstream:

Issue: https://github.com/Smithay/smithay-clipboard/issues/33
merged PR: https://github.com/Smithay/smithay-clipboard/pull/35

Thanks @chrisduerr !

**Comment by jamesodhunt** [comment] 2021-02-11 08:36
Fedora 33 has just updated to Alacritty 0.7 (`alacritty-0.7.1-1`), meaning a lot more users are going to be impacted by this problem.

/me switches to his 0.6.0 build again :smile:

**Comment by fredrikjonson** [comment] 2021-02-12 07:22
I was eager to try the patch. It seems to be possible to to override the transitive dependency by adding the new version of smithay-clipboard to alacritty/Cargo.toml and build. Caveat though, not sure what I'm doing, but it seems to work. 🙂
```
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index 923659d..ec790a8 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -30,6 +30,7 @@ notify = "4"
 parking_lot = "0.11.0"
 crossfont = { version = "0.2.0", features = ["force_system_fontconfig"] }
 urlocator = "0.1.3"
+smithay-clipboard = "0.6.3"
 copypasta = { version = "0.7.0", default-features = false }
 libc = "0.2"
 unicode-width = "0.1"
```

**Closed** 2021-02-13 18:15 UTC
Labels: A - deps, B - bug, B - regression, DS - Wayland, S - clipboard
