### ISSUE TITLE
macOS tabs overlap top text (until window resized)

### ISSUE THREAD

**Issue by sshock** [alacritty/alacritty#5978] opened 2022-03-27 19:40 UTC
### System

OS: macOS
Version: 0.10.1

### Description

Thank you so much for implementing https://github.com/alacritty/alacritty/issues/1544 !

I found a little bug though.  When a window/tab is created, it overlaps the top section (about one line of text).  However, if I then proceed to resize the window a tiny bit, it figures things out and adjusts so that the top section is no longer covered up.

### Screenshots

Before creating any tabs:

<img width="838" alt="1" src="https://user-images.githubusercontent.com/1693761/160297820-547b0177-bec4-4614-8c8c-2871c0e93fde.png">

After a tab is created (the problem is on both tabs; I clicked on the first tab just to illustrate):

<img width="838" alt="2" src="https://user-images.githubusercontent.com/1693761/160297822-c4611a4f-b3ed-48a4-94b0-e4ee4d9726c4.png">

After resizing (problem fixed):

<img width="844" alt="3" src="https://user-images.githubusercontent.com/1693761/160297827-1e05f9b2-a537-444f-a760-5aa8c8ae113f.png">

**Comment by chrisduerr** [comment] 2022-03-28 05:35
Duplicate of https://github.com/alacritty/alacritty/issues/5876.

**Closed by chrisduerr** 2022-03-28 05:35 UTC
