### ISSUE TITLE
Text gets disordered in cmus, with kajis.

### ISSUE THREAD

**Issue by Kazimazi** [alacritty/alacritty#3721] opened 2020-05-12 18:12 UTC
As I'm switching between songs, characters get all over the place. A [video](https://streamable.com/o0orae) would show it perfectly.
It only happens with songs which have japanese characters in their name and when my alacritty is on version 0.4.*, otherwise it works without any mistakes.

Alacritty version: 0.4.2
OS: NixOS
locale: en_US.UTF-8
term: xterm-256color
Tried it both in bspwm and swaywm.

**Comment by kchibisov** [comment] 2020-05-12 18:24
Can you do the following?

- set history size in your config to 0
- run alacritty with `alacritty --ref-test`
- repro your issue
- close alacritty with a system hotkey, while your disordered text is on screen

After that checkout the directory from where you've launched it and attach `alacritty.recording` file.

**Comment by Kazimazi** [comment] 2020-05-12 18:51
Uploaded it [here](https://gist.github.com/Kazimazi/4e6d8c3607c03dc42810603ece4c8044).

**Comment by chrisduerr** [comment] 2020-05-12 21:17
@Kazimazi Does `cat` ing that file in bash produce a broken version for you?

**Comment by kchibisov** [comment] 2020-05-12 21:21
you should `cat file && sleep 100`, I guess.

**Comment by Kazimazi** [comment] 2020-05-12 23:24
@chrisduerr @kchibisov yes it renders alacritty unuseable

**Comment by chrisduerr** [comment] 2020-05-13 02:35
That recording renders just fine for me. Could you share additional system information? Which OS? Which locale? Which `TERM`?

**Comment by Kazimazi** [comment] 2020-05-13 03:26
Oh sorry I messed up, my last statement is false.

 I made a [new video](https://streamable.com/8ur8tx) and uploaded a [new recording](https://gist.github.com/Kazimazi/b97756cc104a81378049ffbd588a4e25) about the whole process of opening cmus and cat-ing the recording so its more descriptive and if I made a mistake it could be pointed out.
Notice as I cat-ed the recording my cursor highlight disappeared... weird.

Going to put system info in original post.

**Comment by kchibisov** [comment] 2020-05-13 08:24
>Notice as I cat-ed the recording my cursor highlight disappeared... weird.

It was just hidden, type `reset` and should be fixed.

**Comment by kchibisov** [comment] 2020-05-13 08:28
>when my alacritty is on version 0.4.*, otherwise it works without any mistakes.

Are you sure that you can repro on `v0.4.1`? It seems like catting your file only breaks on `v0.4.2`, however every version before from `v0.3.3.` up to `v0.4.1` works the same.

**Comment by kchibisov** [comment] 2020-05-13 08:36
Ok, it seems like on the output you've provided the difference starts from 2ef5e47

**Comment by chrisduerr** [comment] 2020-05-13 08:48
Minimal repro: `echo -e "\e]0;｜a"`

**Comment by chrisduerr** [comment] 2020-05-13 09:10
Duplicate of https://github.com/alacritty/alacritty/issues/3591, waiting for bump of `vte` crate.

**Closed** 2020-05-13 09:10 UTC
Labels: B - regression, F - duplicate, P - high, S - terminal

**Comment by kchibisov** [comment] 2020-05-13 10:58
fyi, the fix is in master branch now, you can retest and say whether it fixes the issue for you.

**Comment by Kazimazi** [comment] 2020-05-14 02:20
I'm gonna check it out as soon as I get some time.
