### ISSUE TITLE
Alt-Shift-3 does not work on UK keyboard (linux)

### ISSUE THREAD

**Issue by eggbean** [alacritty/alacritty#5516] opened 2021-09-27 15:00 UTC
### System
OS: Linux (other OSs not tested)
Version: tested on 0.8.0 and 0.9.0
Linux: X11/GNOME 3.xx (Pop!_OS 21.04)

ThinkPad T480s with UK keyboard

In bash `Ctrl-v`, `Alt-Shift-3` returns `£` as though only `Shift-3` was typed.

Possibly the same issue:
https://github.com/alacritty/alacritty/issues/1073
https://github.com/alacritty/alacritty/issues/186
https://github.com/alacritty/alacritty/issues/55
https://github.com/alacritty/alacritty/issues/170

Is there anything I can do about this, as it seems to be a long-standing problem? I have been using Alacritty for a while and I like everything else about it.

Is there a possible workaround by adding a binding in `alacritty.yaml`?

**Comment by chrisduerr** [comment] 2021-09-28 00:35
Duplicate of #55.

> Is there anything I can do about this, as it seems to be a long-standing problem?

Not really. This is an upstream bug that needs to be fixed in winit.

> Is there a possible workaround by adding a binding in alacritty.yaml?

You'd have to look at the `--print-events` output, but chances are you're not receiving an appropriate KeyboardInput event.

**Closed as completed by chrisduerr** 2021-09-28 00:35 UTC
Labels: F - duplicate
