### ISSUE TITLE
freezes on intel integrated graphics (X1 carbon) in 2monitor config

### ISSUE THREAD

**Issue by chris-aeviator** [alacritty/alacritty#3781] opened 2020-05-28 05:02 UTC
When running in a 2 monitor Config, 1 external, one internal and using alacritty on the internal laptop monitor (X1 carbon), alacritty freezes after several seconds (e.g. after openig vim). I can perfectly fine use alacritty for the whole day on the external monitor without any of this behavour. 

### System

Arch Linux
alacritty v 0.4.2
BSPWM + compton

### Logs
window freezes, have to kill it with with xkill, thus no logs

**Comment by kchibisov** [comment] 2020-05-28 07:59
Do you see something in dmesg? Does it  happen without compton?

Seems like duplicate of #3284

**Closed by kchibisov** 2020-05-28 07:59 UTC

**Comment by kchibisov** [comment] 2020-05-28 08:13
Also, can you try running alacritty like that `MESA_LOADER_DRIVER_OVERRIDE=i965 alacritty`

**Comment by chris-aeviator** [comment] 2020-05-29 04:39
@kchibisov trying to reproduce, since I avoided using alacritty (and crashing) due to the bug I still try to find a reliable way. Thanks for pointing out the driver issue, indeed I've had other problems (e.g. electron apps freezing) that only appeared after a system upgrade it looks very much this could be the issue.

**Comment by kchibisov** [comment] 2020-05-29 04:42
Try setting `MESA_LOADER_DRIVER_OVERRIDE=i965` globally..
