### ISSUE TITLE
Vim issues with Alacritty 0.4.3 (Portable) on Windows 10 

### ISSUE THREAD

**Issue by har5ha** [alacritty/alacritty#3861] opened 2020-06-17 12:10 UTC
Initially every file loads perfectly in VIM (including my colorscheme) but whenever I try to navigate/scroll beyond a point(scrolling upwards) in the file the following happens and returns to normal colors after scrolling back and forth. I am using Alacritty and Vim under WSL2.  `**Updated** >>  (Come to find out I am still on ** WSL1 **. Check my later comments.. )`

Noticed that the odd coloring/artifact disappears if I resize the Alacritty window. 

On further investigation I found a similar issue was reported earlier : https://github.com/alacritty/alacritty/issues/1376

Hoping someone can help me out. Thanks in advance. 
 
![Bug_report_Alacritty_0 43_2020-06-17](https://user-images.githubusercontent.com/135051/84895387-dc54ab80-b0bf-11ea-87f0-e8cc7acdf74e.png)
 

![Bug_2_Annotation 2020-06-17 173355](https://user-images.githubusercontent.com/135051/84896079-ec20bf80-b0c0-11ea-9c6c-7361930e430a.png)

![Bug_3_Annotation 2020-06-17 173355](https://user-images.githubusercontent.com/135051/84896085-efb44680-b0c0-11ea-8034-e7f6e5b4d40c.png)

### System
OS: Windows 10 (WSL2)
Version: Alacritty 0.4.3 (Portable)

**Comment by kchibisov** [comment] 2020-06-18 04:45
Could you provide `alacritty.recording` from `alacritty --ref-test`? It should create 4 files (3 json and one recording) you can delete all json ones and just give us recording one.

To make a proper record, just start `alacritty --ref-test`, repro your issue and close with `Alt + F4` when you see broken vim on screen.

**Comment by har5ha** [comment] 2020-06-18 06:12
> 
> 
> Could you provide `alacritty.recording` from `alacritty --ref-test`? It should create 4 files (3 json and one recording) you can delete all json ones and just give us recording one.
> 
> To make a proper record, just start `alacritty --ref-test`, repro your issue and close with `Alt + F4` when you see broken vim on screen.

Thanks! for your help. I have attached below the Zip file of the generated "alacritty.recording", you requested. 

Feel free to let me know if you need anything else. 


>[alacritty.recording.zip](https://github.com/alacritty/alacritty/files/4796565/alacritty.recording.zip)

**Comment by chrisduerr** [comment] 2020-06-18 08:49
Could you try WSL1/ConPTY? It seems like Alacritty is rendering everything correctly here, but somehow vim is outputting garbage.

**Comment by har5ha** [comment] 2020-06-18 09:15
> 
> 
> Could you try WSL1/ConPTY? It seems like Alacritty is rendering everything correctly here, but somehow vim is outputting garbage.

Sorry I don't have access to WSL1 machine, this is a new Laptop and I ended up installing WSL2 directly.

I tried the above steps with "Windows Terminal", cmd.exe as well as MobaXterm and none of them seem to have the issue with VIM.

PS: 
Also noted that this happens in Vim with only some color-schemes which have non-black (eg. #080808 ) background colorset,  instead of say (#000000). Black background color-schemes at least appear to work fine.

**Comment by chrisduerr** [comment] 2020-06-18 22:39
Do you have the Alacritty terminfo installed? You can try running it with TERM=xterm-256color.

Windows Terminal unfortunately doesn't actually run with the default PTY backend of Windows 10 but instead uses a pre-release version. So unfortunately they themselves seem to acknowledge that the stable software they ship isn't really usable.

**Comment by har5ha** [comment] 2020-06-19 04:05
I  get the following output, without doing any of the above. And I also have `TERM: xterm-256color` set in "alacritty.yml" file under %Appdata%/Roaming/alacritty
```
$ echo $TERM
 xterm-256color
```



> 
> 
> Do you have the Alacritty terminfo installed? You can try running it with TERM=xterm-256color.
> ....

No, but I am guessing from your comments. That I should be downloading the "alacritty.info" file from [Releases](https://github.com/alacritty/alacritty/releases) 

and run the [following command](https://github.com/alacritty/alacritty/blob/8d5e1226d500579692128439abd9c991ba9a72d3/INSTALL.md#terminfo) in Ubuntu/Kali under Windows(WSL2) 

`sudo tic -e alacritty,alacritty-direct alacritty.info`

PS: 
Can you confirm that the above steps are right?. Also, a big thanks! for all the help.

**Comment by chrisduerr** [comment] 2020-06-19 20:48
> Can you confirm that the above steps are right?

Yeah that looks correct.

You said that you don't have access to WSL1, but can you not have both WSL1 and WSL2 at the same time? Also have you tested using WinPTY instead of ConPTY (see config option `winpty_backend`). You can verify which backend is actually being loaded by running `alacritty -v`.

**Comment by har5ha** [comment] 2020-06-21 06:25
...
> You said that you don't have access to WSL1, but can you not have both WSL1 and WSL2 at the same time? Also have you tested using WinPTY instead of ConPTY (see config option `winpty_backend`). You can verify which backend is actually being loaded by running `alacritty -v`.

Haven't tried it yet, also having some unrelated issue with my Laptop currently. I ran the `sudo tic -e alacritty,alacritty-direct alacritty.info` command as well as set the `winpty_backend` , but haven't noticed any change in the behavior.

**Comment by chrisduerr** [comment] 2020-06-21 22:12
> But in "Windows Terminal" everything runs perfectly.

That doesn't really help, since Windows Terminal does not rely on the APIs Microsoft provides publicly in their releases.

There's a good chance things will just get fixed once the pre-release PTY backend Windows Terminal is using is publicly released.

**Comment by chrisduerr** [comment] 2020-06-21 22:13
Which Windows version are you on exactly?

**Comment by har5ha** [comment] 2020-06-22 02:54
> 
> 
> > But in "Windows Terminal" everything runs perfectly.
> 
> That doesn't really help, since Windows Terminal does not rely on the APIs Microsoft provides publicly in their releases.
> 
> There's a good chance things will just get fixed once the pre-release PTY backend Windows Terminal is using is publicly released.

Okay. Thanks!

> 
> 
> Which Windows version are you on exactly?

```
C:\>systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.18363 N/A Build 18363
```

**Comment by chrisduerr** [comment] 2020-06-24 17:21
I'm not quite sure what else there is to test. The escapes the Windows PTY produces seem to be pretty garbage, so if changing the `TERM` doesn't work, there's nothing we can do. Since this isn't a problem with how we interpret these escapes but with the escapes that are emitted.

Maybe @davidhewitt or @cole-h can give this a test, but other than that I would chalk it up to a Windows PTY issue that will eventually be resolved with a Windows update hopefully.

**Comment by davidhewitt** [comment] 2020-06-24 17:41
I'm happy to test on my machine. @har5ha can you share a file and roughly the key sequences I should use to get a reliable repro?

(I'm running Windows 10 2004, WSL2 with Ubuntu 20.04)

**Comment by har5ha** [comment] 2020-06-25 10:40
> 
> 
> I'm happy to test on my machine. @har5ha can you share a file and roughly the key sequences I should use to get a reliable repro?
> 
> (I'm running Windows 10 2004, WSL2 with Ubuntu 20.04)

I am running Alacritty 0.4.3 (Portable) [.exe] on Windows and from the Windows command prompt starting/running Kali. In the Bash shell i'm running VIM with Lettuce (colorscheme).. And when I open a file in VIM and scroll downwards and then upwards, the above happens (Screenshots included above ^^) (or) even resize the alacritty window . This doesn't happen when I have other VIM colorschemes(with #000000 as background) loaded.

**Comment by davidhewitt** [comment] 2020-06-27 13:29
I had a go, this was the command I used to set vim non-black background:

```
:highlight Normal ctermfg=grey ctermbg=darkblue
```

Scrolling up and down a large file for a bit, I couldn't reproduce on my setup.

@har5ha your Windows 10 OS version is a little old, perhaps you should consider upgrading? (Can use update assistant at https://www.microsoft.com/en-gb/software-download/windows10) Also I think you might be running WSL1 (not WSL2) with that reported OS version? I'm on May 2020 update which is the first stable Windows 10 to provide WSL2:

```
C:\Windows>ver
Microsoft Windows [Version 10.0.19041.329]
```

**Comment by har5ha** [comment] 2020-06-27 14:24
> @har5ha your Windows 10 OS version is a little old, perhaps you should consider upgrading? (Can use update assistant at https://www.microsoft.com/en-gb/software-download/windows10) Also I think you might be running WSL1 (not WSL2) with that reported OS version? I'm on May 2020 update which is the first stable Windows 10 to provide WSL2:
> 
> ```
> C:\Windows>ver
> Microsoft Windows [Version 10.0.19041.329]
> ```

I think you are right I am currently on WSL1, still.  But my Windows Update has not yet given me the option to upgrade. Now I am really confused.
![Win10_](https://user-images.githubusercontent.com/135051/85924394-abd6f380-b8af-11ea-9aa5-63de2cf7d0c8.jpg)

**Comment by davidhewitt** [comment] 2020-06-27 14:26
Yep you could try using the update assistant I linked to above to manually force an update (rather than waiting for it to be sent to your device / windows update).

**Comment by har5ha** [comment] 2020-06-27 14:39
> 
> 
> Yep you could try using the update assistant I linked to above to manually force an update (rather than waiting for it to be sent to your device / windows update).

Thanks a lot! for your help David. I am on a Office Laptop, so I might hold off on it a bit longer.

**Comment by chrisduerr** [comment] 2020-06-27 17:12
I'm going to close this for now since I'd assume it's just due to an outdated Windows version. If you update things and it's still broken, please let us know and I can re-open this issue.

**Closed by chrisduerr** 2020-06-27 17:12 UTC
Labels: H - windows
