### ISSUE TITLE
Chinese characters occasionally have an issue in neovim.

### ISSUE THREAD

**Issue by kevinhwang91** [alacritty/alacritty#3555] opened 2020-04-04 00:32 UTC
### System

OS: Linux/BSD/macOS/Windows
Version: 0.4.2
Linux/BSD: X11, GNOME

There is a very strange phenomenon. After neovim is used for a period of time, the Chinese characters will appear as shown below:
![2020-04-04_04-54](https://user-images.githubusercontent.com/17562139/78413938-5098ba80-764c-11ea-9f5e-17e25952d0f9.png)

It doesn't happen  with 100% probability.

It runs inside tmux. When I reset alacritty and attach it to tmux, everything works fine as expect.

This has never happened in the gnome-terminal.

**Comment by chrisduerr** [comment] 2020-04-04 00:34
> When I reset alacritty and attach it to tmux, everything works fine as expect.

Could you go into more detail what you mean by that? Do you run `reset`, or do you mean you restart Alacritty?

**Comment by kchibisov** [comment] 2020-04-04 00:37
duplicate of #791

**Comment by kevinhwang91** [comment] 2020-04-04 00:38
> > When I reset alacritty and attach it to tmux, everything works fine as expect.
> 
> Could you go into more detail what you mean by that? Do you run `reset`, or do you mean you restart Alacritty?

yes

**Closed by kchibisov** 2020-04-04 00:37 UTC
Labels: S - font, S - unicode

**Comment by kchibisov** [comment] 2020-04-04 00:41
try to change your font size (just increase and then decrease), it should fix it.

**Comment by kevinhwang91** [comment] 2020-04-04 00:44
> try to change your font size (just increase and then decrease), it should fix it.

Thanks. If you have free time, please fix this issue.
