### ISSUE TITLE
Sending SYN before pasting can break bracketed paste

### ISSUE THREAD

**Issue by ii8** [alacritty/alacritty#3892] opened 2020-06-27 17:11 UTC
To reproduce, run a program that sets bracketed paste mode such as bash.
Then enter `Ctrl-v`, then `Ctrl-Shift-v` with text in the clipboard to paste.
Now there is the bracketed paste mode beginning sequence in the pasted text instead of being understood by readline.

It's also possible with ESC instead of SYN, and possibly more. SYN is just the most problematic because the user is most likely to accidentally press that before using `Ctrl-Shift-v`.

I actually have the same problem in my own terminal emulator [havoc](/ii8/havoc) but it's not obvious to me what the right fix is here, so I thought maybe you have ideas.

OS: Void Linux
Version: alacritty 0.4.3
WM: Wayland, Sway

**Comment by kchibisov** [comment] 2020-06-27 17:13
Does any other terminal handle that somehow? A good start would be to check, let's say libvte based ones, like termite, sakura, etc. And ofc, xterm.

**Comment by chrisduerr** [comment] 2020-06-27 17:16
I'm not sure if this behavior is incorrect tbh. You're setting bracketed paste mode and basically then sending an arbitrary escape, that should be neutralized. It's kinda like pasting escapes directly to the terminal in bracketed paste mode.

**Comment by ii8** [comment] 2020-06-27 20:46
In both libvte and xterm the text is pasted as it was copied. I can't find anything in their source that would prevent this problem though, I'll have to read more thoroughly at some point.

**Comment by kchibisov** [comment] 2020-06-27 20:56
I'm not entirely sure what you're testing, but vte terminals, etc do behave exactly like alacritty here. The problem is that start of bracketed paste reply is failing. The only thing alacritty is doing with brackted paste is that it removes all the escapes, but I'm not sure that there's any terminal that handles this `Ctrl + V` scenario, and I guess it's kind of expected that it's failing here. There' s no way to prevent this issue from happening, other than put `\0` or some other non printable character right before writing a reply for bracketed paste. If you want to play with some bracketed paste https://thejh.net/misc/website-terminal-copy-paste

Side note: 
bash isn't using bracketed paste by default, unless you've enabled it in inputrc IIRC. So verify that bracketed paste is being used before testing in other terminals.

Since you've done some research @chrisduerr  as well, should we just close this issue, since we can't really do anything about it and our behavior matches the rest of the terminals, knowing that inserting invisible chars isn't an option and not something the user wants as well.

**Comment by chrisduerr** [comment] 2020-06-27 21:12
> Since you've done some research @chrisduerr as well, should we just close this issue, since we can't really do anything about it and our behavior matches the rest of the terminals, knowing that inserting invisible chars isn't an option and not something the user wants as well.

I'm not entirely sure. I think it's a serious concern and it might be useful to check how the shell could work around this. On the other hand, it's not really something we can do a lot about ourselves.

**Comment by ii8** [comment] 2020-06-27 21:13
Ok, I guess if xterm behaves like this as well then that's just how it is.
One could imagine that the proper fix would be to keep track of state that would disrupt the beginning of any new control sequence you want to send to the child program and escape/disable the action in those scenarios.
But if nobody else does it then why bother.

**Closed by chrisduerr** 2020-06-27 21:12 UTC

**Comment by chrisduerr** [comment] 2020-06-27 21:14
>  One could imagine that the proper fix would be to keep track of state that would disrupt the beginning of any new control sequence you want to send to the child program and escape/disable the action in those scenarios.

That cannot be done in the terminal though. The terminal emulator is not aware of this state. However the shell totally could and that is why it might be worth it to bring it up to zsh devs.

**Comment by ii8** [comment] 2020-06-27 21:21
> That cannot be done in the terminal though.

I'm not sure the shell could do it either. The terminal is aware of the intended semantics, the shell can't distinguish when the next character is meant to be escaped or not. The terminal knows that the start of a bracketed paste should never be escaped.

**Comment by chrisduerr** [comment] 2020-06-27 21:41
> the shell can't distinguish when the next character is meant to be escaped or not. 

The problem is that the shell is escaping characters. So of course it knows. If the shell just completely ignores bracketed paste, there's nothing we can do about that either, at that point it's not up to us anymore.
