### ISSUE TITLE
When I press Up or Down arrow it read as if I press them twice.

### ISSUE THREAD

**Issue by giellamoswhard** [alacritty/alacritty#3627] opened 2020-04-22 12:21 UTC
### System

OS: Ubuntu 20.03
Version: alacritty 0.5.0-dev (3bfb595)
Linux/BSD: X11 Mutter

**Comment by kchibisov** [comment] 2020-04-22 12:23
duplicate of #3476 

tldr, delete old bindings and use new ones from default alacritty.yml.

**Closed by kchibisov** 2020-04-22 12:23 UTC
