### ISSUE TITLE
Modifiers  for emacs

### ISSUE THREAD

**Issue by Ergus** [alacritty/alacritty#2049] opened 2019-01-30 00:38 UTC
Hi:
I am trying to use emacs from inside alacritty but I there ase some missing keybinds. For example 
Control-;   only  inserts ;
Control-?  only inserts ?
xterm enables this with the option of 8 bits inputs:
*eightBitInput:   false
*eightBitOutput:  true

And other associated like *metaSendsEscape:  true.

The most complex modifiers are not accepted either like:
Control-J (Control-Shift-J) which inserts only Control-j and ignores the shift.

I know that this is a limitation in many old terminals but a new one should fix it more or less in the same way that xterm does.

**Comment by chrisduerr** [comment] 2019-01-30 19:52
> metaSendsEscape

Alacritty actually has this option since a recent patch. Though there are still some issues around it.

There's no solution for the other bindings though, it might be possible to create custom bindings for these though.

I'd be cautious with saying 'new terminal should fix it' though, because these options are actually breaking things for user  convenience, so the fixed way would be with these option disabled.

**Comment by SamHH** [comment] 2019-02-07 14:46
For what it's worth I'm seeing similar issues in Neovim where for example I can bind `Enter` but not `S-Enter`.

**Comment by ForceFaction** [comment] 2019-04-12 19:03
I can not use Key Combinations with Control and the Arrow Keys. For example C-<Left Arrow> comes in as M-[ 1 ; 5 c.

**Comment by sammoth** [comment] 2019-04-25 05:38
I have the same issue, lots of keybindings are nonfunctional in emacs using the alacritty terminfo files. I have true color working in emacs by following the instructions [here](https://github.com/syl20bnr/spacemacs/wiki/Terminal) and setting TERM to xterm-24bit in alacritty's config.

**Comment by sammoth** [comment] 2019-04-25 06:00
This also fixes mouse support in Emacs which wasn't working with the alacritty terminfo. I'm using this:


```
xterm-24bit|xterm with 24-bit direct color mode,
   use=xterm-256color,
   sitm=\E[3m,
   ritm=\E[23m,
   RGB,
   colors#0x1000000, pairs#0x7FFF,
   initc@, op=\E[39;49m,
   setab=\E[%?%p1%{8}%<%t4%p1%d%e48;2;%p1%{65536}%/%d;%p1%{256}
         %/%{255}%&%d;%p1%{255}%&%d%;m,
   setaf=\E[%?%p1%{8}%<%t3%p1%d%e38;2;%p1%{65536}%/%d;%p1%{256}
         %/%{255}%&%d;%p1%{255}%&%d%;m,
   setb@, setf@,
   hs, dsl=\E]2;\007, fsl=^G, tsl=\E]2;,
```

**Comment by johnae** [comment] 2019-05-01 08:18
Yeah I also have this problem. Emacs is fine in termite for example.

**Comment by luisalima** [comment] 2021-12-21 11:08
I also have this problem, emacs is unusable inside Alacritty right now, even with hacky keybindings in Alacritty config.

**Comment by bphenriques** [comment] 2022-04-15 08:26
Is this something actively being considered? 

Keybindings is the only nuisance that kinda forced me to look at Kitty (IMO is a bit bloated for _my_ use-case). I like how minimal Alacritty is. Before someone asks..  I would like to contribute but Rust and keybindings management are concepts way beyond my current knowledge 😛

**Comment by Ergus** [comment] 2022-04-15 09:24
At the end I switched to xterm... So I am no following this issue anymore.

**Comment by lfrestrepog** [comment] 2022-05-29 18:51
Hi,
Just wanted to comment I too am an emacs user stuck with the same issue. I'm using alacritty 0.10.1 on windows and running emacs on wsl (I don't think it makes a difference, but maybe it could help other people relate).
Any advise would be appreciated.

**Comment by tol-karacomp** [comment] 2022-10-22 18:17
Looks like this is abandoned. And, emacs compatibility is still an issue.

**Comment by Ergus** [comment] 2022-10-22 19:41
Indeed, no progress on this. At the end I went back to xterm.

**Comment by szebenyib** [comment] 2023-01-26 09:35
I second to this. Not being able to differentiate between <CR> and Ctrl+<CR> is really annoying.

**Comment by andrewbanchich** [comment] 2023-04-22 13:19
@chrisduerr Are there any plans on fixing this? I can't use Emacs from Alacritty, and it looks like others can't either. I've also seen posts about Vim issues due to this.

**Comment by chrisduerr** [comment] 2023-04-23 18:47
I have no desire of "fixing" this.

**Comment by ezmiller** [comment] 2023-06-28 02:27
I've been interested in Alacritty, but not having a way to resolve this is also a bit of a deal breaker.

**Comment by jimporter** [comment] 2023-07-20 22:01
Regardless of whether the maintainers are willing to accept a fix here, hopefully I can help clarify what the higher-level request is (and how to configure Alacritty so that it Just Works(TM) for you).

Obviously, this isn't just an Emacs issue (though Emacs uses enough modifier-heavy keybindings that it comes up in Emacs use more than other programs); it's an issue with sending "extended" key combinations. As far as I know, there are two conventions for this: [xterm](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Alt-and-Meta-Keys)-style (`\e[27;<modifier>;<keycode>~`) and [libtickit](https://www.leonerd.org.uk/hacks/fixterms/)-style (`\e[<keycode>;<modifier>u`). (See the libtickit link for examples of how to specify `<modifier>` and `<keycode>`; they should be the same values in either form, I think.)

It'd certainly be nice if Alacritty adopted one of these conventions (at least as an option), though I can also see some reasons for not supporting it directly: since normally, `Ctrl+Shift+FOO` sends the same thing as `Ctrl+FOO`, it means a terminal emulator can treat `Ctrl+Shift` keybindings as reserved for the terminal emulator itself. (This reasoning doesn't apply to other key combinations, though.)

For *users* who want this, it's not too hard to support. Just add something like this to your configuration:
```yaml
key_bindings:
  - { mods: Control, key: Semicolon, chars: "\u001b[27;5;59~" }
  # ...
```
Or if you're using v0.13+ with TOML configuration:
```toml
[keyboard]
bindings = [
  { mods = "Control", key = "Semicolon", chars = "\u001b[27;5;59~" },
  # ...
]
```
You'll have to bind every extended key combination like this, which is tedious, but it's also pretty straightforward.

**Comment by jian-lin** [comment] 2023-07-20 22:13
> As far as I know, there are two conventions for this: xterm and libtickit-style

FYI, there is another one: [kitty keyboard protocol][kkp].  There are comparisons between it and those two you mentioned at the end of that page.

That page also lists an Emacs package which implements the kitty keyboard protocol.  You may find it useful if you want to implement xterm or libtickit protocol yourself.  (I wrote my own one for kitty keyboard protocol before that package but does not make it public).

[kkp]: https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by jimporter** [comment] 2023-08-02 20:03
> Thanks, @jimporter. I used this to start implementing Alt + B/F to have emacs like key binding in the terminals. I added

I'm not sure why you'd need special bindings for `Alt+<char>`. By default, most terminal emulators (alacritty included) should send that as `ESC` followed by `<char>`. There are timing issues with that (see the libtickit link I posted for some details if you're interested), but it should work pretty much everywhere without configuration. You *can* specify `Alt+<char>` sequences like you did above, but I'd expect that to work in fewer places.

Overall, the configuration I suggested is mainly useful for key sequences you *can't* represent using the traditional rules (for example `Ctrl+<digit>` or `Ctrl+Shift+<letter>`).

**Comment by kchibisov** [comment] 2023-08-02 20:07
Duplicate of #6378 and #3101

**Closed by kchibisov** 2023-08-02 20:07 UTC
Labels: enhancement

**Comment by ickc** [comment] 2023-08-03 14:48
> I'm not sure why you'd need special bindings for `Alt+<char>`. By default, most terminal emulators (alacritty included) should send that as `ESC` followed by `<char>`. There are timing issues with that (see the libtickit link I posted for some details if you're interested), but it should work pretty much everywhere without configuration. You _can_ specify `Alt+<char>` sequences like you did above, but I'd expect that to work in fewer places.
> 
> Overall, the configuration I suggested is mainly useful for key sequences you _can't_ represent using the traditional rules (for example `Ctrl+<digit>` or `Ctrl+Shift+<letter>`).

It's on a macOS and by default in Alacritty typing Opt+B and Opt+F would resulted in `∫`, `ƒ` respectively.

Strangely, as I have the following in `DefaultKeyBinding.dict` (following Jacob Rus):

```js

    "~f"        = "moveWordForward:";               /* M-f          Move forward word */
    "~b"        = "moveWordBackward:";              /* M-b          Move backward word */
```

Which means that in typical macOS application I already have Opt+B and Opt+F doing the move backward/forward a word. So it seems that Alacritty is overriding my overridden macOS keybinding and revert it back to how default macOS keybinding is working.

Should this be filed as a separate issue?

Thanks.

**Comment by kchibisov** [comment] 2023-08-03 14:52
@ickc have you tried configuring alacritty's input? `window.option_as_alt` in the config is what you need to get Alt working on macOS.

**Comment by ickc** [comment] 2023-08-03 21:31
@kchibisov, thank you very much. I was completely looking in the wrong place to configure this. It's working as expected.
