### ISSUE TITLE
Graphical artifacts with window transparency

### ISSUE THREAD

**Issue by mkeeler** [alacritty/alacritty#889] opened 2017-11-06 13:57 UTC
Which operating system does the issue occur on? MacOS (10.12.6 - Intel Iris Pro graphcis)

So when I have window transparency turned on (background_opacity: 0.85) I sometimes see graphical artifacts where text is rendered in the background of what was previously on my terminal. An image is attached. This occurs both within tmux and outside of tmux after detaching.

I cant seem to figure out what makes it occur or why its displaying a particular text but its pretty reproducible for me.

<img width="368" alt="artifact" src="https://user-images.githubusercontent.com/1641976/32444417-8bd8bc1c-c2d0-11e7-98eb-d8b00868ae13.png">

**Comment by mafredri** [comment] 2018-04-22 10:12
Same issue here, I recorded a screencast demoing the issue:

![alacritty-artifacts2](https://user-images.githubusercontent.com/147409/39093849-cc556e0c-462e-11e8-95f2-4ce1f1edcfda.gif)

(As you might notice, it's easily repeatable when hiding Alacritty via Cmd+H)

**Comment by epwalsh** [comment] 2018-07-19 16:15
Same issue here on a MacBook Air running OS X 10.13.5.

**Comment by stephenprater** [comment] 2018-07-23 06:59
Same issue on Macbook Pro 10.12.16

![image](https://user-images.githubusercontent.com/149870/43061704-132eef78-8e0b-11e8-965b-c9dbd3123e76.png)

You can't actually see the background effect in this screen shot - _only_ the ghosting effect.  I had just closed a split where the lighter part is.

**Comment by kirbpowell** [comment] 2019-03-04 23:21
Seeing the same issue here with `background_opacity: 0.5`, running on Macbook Pro 10.14.2 with Radeon Pro 560X graphics.

**Comment by tomaskallup** [comment] 2019-04-08 14:18
The problem is window shadow, I had the same problem with iTerm2 borderless patch and removing shadow fixed the issue. Would it be possible to add an option to remove window shadow?

**Comment by remi-gelinas** [comment] 2019-04-26 03:46
Same issue here with `background_opacity: 0.3` on a 2018 Macbook Pro with Iris Pro graphics.

**Comment by amagura** [comment] 2019-05-09 15:49
I'm having this issue with `background_opacity: 0.6` on a 2018 MacBook Pro (15).

**Comment by vaibhav-y** [comment] 2019-05-29 14:19
Re: #2490, these are the steps to reproduce on macOS Mojave 10.14.5
1. Enable window trasparency
2. Resize an alacritty window, note the position of any existing text on the window at the maximum size scaled to by dragging the corner
3. Once the redraw happens, there are artifacts of the on-screen text as it appeared just before releasing the resize-drag. 


These seem to be a part of the window background and are unselectable. Other notable behaviours:

1. The artifacts are not visible if the window focus is lost. They are restored on restoring window focus
2. Resizing the window after this replaces the old artifacts with new ones.
3. These don't seem to exist in full-screen mode.


Related screenshot

![Screen Shot 2019-05-29 at 09 48 26](https://user-images.githubusercontent.com/3663231/58562694-bed44b80-81f7-11e9-969f-c85d43d263a6.png)

**Comment by lukeberry99** [comment] 2019-08-28 14:44
Any update on this issue? @jwilm

**Comment by slecrenski** [comment] 2020-03-15 17:31
Hey guys.  So I'm pretty sure this is related to the res/text.f.glsl shader.  When I modified the code to use ```rust

**Comment by slecrenski** [comment] 2020-03-15 17:35
Hey guys.  This was irritating me quite a bit today so I decided to dig in a bit. So I think maybe that this is related to the res/text.f.glsl shader. When I modified the code to use 
```rust

vec3 textColor = texture(mask, TexCoords).rgb;
alphaMask = vec4(textColor, 0.0);
color = vec4(fg, 1.0);

/*
    if (backgroundPass != 0) {
        if (bg.a == 0.0)
            discard;

        alphaMask = vec4(1.0);
        color = vec4(bg.rgb, 1.0);
    } else {
        vec3 textColor = texture(mask, TexCoords).rgb;
        //alphaMask = vec4(textColor, textColor.r);
	alphaMask = vec4(textColor, textColor.r);
        color = vec4(fg, 1.0);
    }

    */
```

So maybe it is shader related?  Maybe @jwilm  might know why.

**Comment by amatsus** [comment] 2020-03-23 10:56
I tried adding setHasShadow() to the winit library as @tomaskallup advised. It's working as expected.
```diff
--- winit-0.22.0.orig/src/platform_impl/macos/window.rs	2020-03-16 22:29:58.000000000 +0900
+++ winit-0.22.0/src/platform_impl/macos/window.rs	2020-03-17 01:09:11.000000000 +0900
@@ -223,6 +223,7 @@
                 }
             }

+            ns_window.setHasShadow_(NO);
             ns_window.center();
             ns_window
         });
```

**Comment by kchibisov** [comment] 2020-03-23 11:12
It seems like it's something required for transparent windows on macOS, since I found other links to use the `setHasShadow_(NO)` for transparent windows as well as using `setOpaque(NO)`.

I feel like managing such thing directly in alacritty based on config opacity value is a way to go.  winit already provides us with method to get `ns_window`, so it should be something simple as add a bunch of `cfg` and call proper method where we're updating/setting opacity. However it'll require someone with macOS to implement it(not me).

if anyone is interested in doing it, let me know.

**Comment by chrisduerr** [comment] 2020-03-23 17:30
> I feel like managing such thing directly in alacritty based on config opacity value is a way to go.

Is it? I don't think it makes a lot of sense to allow users to set transparency unless it actually works. So winit should set this if it isn't possible to make this work otherwise.

**Comment by kchibisov** [comment] 2020-03-23 17:33
I mean you need shadows for non transparent windows and you don't need them for transparent. As well as opaque state, winit doesn't know anything about dynamic alpha managing we do at all.

**Comment by slecrenski** [comment] 2020-03-23 17:49
The idea of turning off macOS window shading to make this work seems like a hack.  Does anyone know why the graphical artifacts occur?  I attempted a workaround of not resizing the window which works for a little while but I noticed that times when the computer goes to sleep or resize events from my docking monitor to normal monitor also cause the issue.  I have even seen the opposite effect (when not focused on the window the graphical artifacts show and when focused they go away)  It seems to me that some OpenGL shading buffer is not properly cleared maybe.  I did mess around with the fragment shader (res/text.f.gls) and can get things to partially not show the artifacts.  I'm wondering if the fragment shader buffers need to be cleared on resize events?  My OpenGL is a bit rubbish so not sure if this even makes sense.

**Comment by kchibisov** [comment] 2020-03-23 17:58
Well this issue is present only on macOS, transparency is done by your system compositor, so I can assume that it's doing some optimizations for non opaque windows by default. We clear the entire screen each time we redraw, so as well during resizes, etc, if `glClear` doesn't work than what can we expect from this platform in the end?

**Comment by slecrenski** [comment] 2020-03-23 18:18
I don't remember seeing any artifacts when using glutin's example with transparency.  aka. https://github.com/rust-windowing/glutin/blob/master/glutin_examples/examples/transparent.rs  But maybe using text and a custom fragment shader glutin is doing some internal optimizations which cause the artifacts?  Otherwise if alacritty is properly clearing fragment shader buffers then I feel like maybe it is an Apple issue that should be reported.

**Comment by slecrenski** [comment] 2020-03-23 19:29
I'm going to play around with this some more tonight hopefully.  Alacritty uses Glutin.  On MacOS I think Glutin uses https://developer.apple.com/documentation/appkit/nsopenglcontext  which seems to be deprecated.  In any case.  https://developer.apple.com/documentation/appkit/nsopenglcontext/1436106-clearcurrentcontext seems to require a subsequent call to makeCurrentContext() to do anything.  I sort of wish Alacritty had some architectural diagrams that explain the primary components and how they work etc.  Also doesn't MacOS maybe have some OpenGL emulator for metal now?  Because of this issue I seriously will not be able to sleep properly until a root cause is identified.  I didn't get transparency to work at all on Ubuntu.  Which system compositor with transparency support were you using here?

**Comment by kchibisov** [comment] 2020-03-23 19:53
>I sort of wish Alacritty had some architectural diagrams that explain the primary components and how they work etc.

GUI is in `alacritty`, render is in `alacritty/src/render/mod.rs`, which is called from `fn draw` in `alacritty/src/display.rs`, event loop is in `alacritty/src/event.rs`, which calls `fn draw`. We're very simple and you can likely guess most things from the file names. you can always ask us in #alacritty on freenode for more real time help.

We have plans to move to gfx-rs, where we can use Metal on macOS, but it's just a plan.

>I didn't get transparency to work at all on Ubuntu. Which system compositor with transparency support were you using here?

On X11 there's a `picom`/`compton`, `GNOME/KDE` should have it by default, since they are also compositors.

**Comment by kchibisov** [comment] 2020-03-24 14:46
Just putting some links here after more investigation on IRC. it seems like a known problem and a some apps has a work around in some form (iterm,chrome).

https://gitlab.com/gnachman/iterm2/-/blob/master/sources/iTermWindowImpl.m#L507
https://gitlab.com/gnachman/iterm2/-/blob/master/sources/PseudoTerminal.m#L4775
https://gitlab.com/gnachman/iterm2/issues/2925
https://chromium.googlesource.com/chromium/src/+/00264f70be2e0d93dbea53cd1981074869b0c48b/ui/base/cocoa/underlay_opengl_hosting_window.mm#15
https://gitlab.com/gnachman/iterm2/-/issues/299

**Comment by chrisduerr** [comment] 2020-03-24 16:12
As an important note, it seems like after Mojave it is not possible to use `setContentHasShadow` to `false` anymore. So the only options are either disabling shadows completely, or manually invalidating the shadows.

The latter seems to be the recommended approach and what I would suggest. Patching that into winit or glutin should allow providing this fix to everyone.

**Comment by jhwheeler** [comment] 2020-07-20 13:15
Is there any workaround for this? For now I have just turned off my transparency, kind of a bummer as this is a core part of my workflow.

Thanks in advance!

**Comment by rbren** [comment] 2020-08-18 10:42
FWIW I'm seeing this specifically when I resize the window very quickly.

I can get it to go away by _slowly_ resizing the window a couple lines, then _slowly_ moving it back.

**Closed** 2020-12-21 06:40 UTC
Labels: B - bug, H - macos, S - render, S - transparency
