### ISSUE TITLE
X11 Clipboard selection gets inconsistent between windows

### ISSUE THREAD

**Issue by dotdash** [alacritty/alacritty#6252] opened 2022-08-10 09:47 UTC
When working with multiple windows, the X11 clipboard contents get out of sync. With different windows pasting different text on MMB click.

### How to reproduce

1. Open two alacritty windows.
2. Type `# foo' in the first one.
3. Type `# bar' in the second one.
4. Double click `foo` in the first window to select it.
5. Double click `bar` in the second window to select it.
6. Press MMB in the first window -> `bar` gets pasted.
7. Press MMB in the second window -> `foo` gets pasted.

It seems to update the selection upon leaving the window, but there must be something more to it, because sometimes things work as expected, and in some situations pressing MMB multiple times in a row in the same window pastes different texts.

### System

OS: Linux Ubuntu Jammy
Version: alacritty 0.10.1
Linux/BSD: X11, AwesomeWM + gnome-sessoin

**Comment by chrisduerr** [comment] 2022-08-11 05:26
Duplicate of https://github.com/alacritty/alacritty/issues/5398.

**Closed by chrisduerr** 2022-08-11 05:26 UTC
