### ISSUE TITLE
`startup_mode = "Maximized"` showing no window after upgrading to 0.13.0

### ISSUE THREAD

**Issue by puresick** [alacritty/alacritty#7503] opened 2023-12-29 21:31 UTC
After updating alacritty to 0.13.0 and migrating the configuration file via `alacritty migrate`, alacritty did not show any window despite the process running after starting. I cherry picked the configuration file until I found that `startup_mode = "Maximized"` was the issue – commenting it out resulted in alacritty starting and showing a window as expected. Running `alacritty` in another terminal shows no output to STDOUT.

### System

OS: Arch Linux (Linux 6.6.8-arch1-1)
Version: alacritty 0.13.0 (78fa4d6f)
Linux/BSD: Gnome 45 (Wayland)

### Logs

Crashes: No log output

**Comment by kchibisov** [comment] 2023-12-29 21:37
duplicate of https://github.com/alacritty/alacritty/issues/7465

**Closed by kchibisov** 2023-12-29 21:37 UTC
