### ISSUE TITLE
Unable to paste into search

### ISSUE THREAD

**Issue by ajeetdsouza** [alacritty/alacritty#4181] opened 2020-08-28 09:53 UTC
The Search feature (Ctrl+Shift+F) is pretty great, but I'm unable to paste into the search bar using the regular Ctrl+Shift+V shortcut.

**Comment by kchibisov** [comment] 2020-08-28 09:55
Duplicate of #4181.

It was intentionally implemented that way, but I guess we can support at least paste into it.

**Closed by kchibisov** 2020-08-28 09:55 UTC

**Comment by ajeetdsouza** [comment] 2020-08-28 09:57
My bad. Thanks!

You linked back to the same issue, I think you meant https://github.com/alacritty/alacritty/issues/4176.

**Comment by kchibisov** [comment] 2020-08-28 10:00
Yeah, that issue, thx.
