### ISSUE TITLE
unintended A|B|C|D inputs on arrow keys

### ISSUE THREAD

**Issue by 5paceToast** [alacritty/alacritty#3203] opened 2020-01-13 16:22 UTC
When alacritty is focused when the user switches between workspaces using ctrl+alt+arrows, alacritty gets a letter ("A", "B", "C" or "D") pasted into it (both from and to the workspace in question).
This is a regression (from 0.4.0 if I recall correctly).
Typically, these events should be eaten up by the WM but alacritty probably has access to them due to being a GL application.

I'll try to bisect for the exact commit that regressed this when I get home.

### System

OS: Arch Linux amd64
Version: alacritty 0.4.1
Linux/BSD: X11 Plasma 5

### Logs

Font/Terminal size:
```
[2020-01-13 11:18] [INFO] Welcome to Alacritty
[2020-01-13 11:18] [INFO] Configuration loaded from "/home/toast/.config/alacritty/alacritty.yml"
[2020-01-13 11:18] [DEBUG] Estimated DPR: 1
[2020-01-13 11:18] [DEBUG] Estimated Cell Size: 9 x 17
[2020-01-13 11:18] [DEBUG] Estimated Dimensions: Some((814.0, 463.0))
[2020-01-13 11:18] [INFO] Device pixel ratio: 1
[2020-01-13 11:18] [INFO] Initializing glyph cache...
[2020-01-13 11:18] [INFO] ... finished initializing glyph cache in 0.014460414s
[2020-01-13 11:18] [INFO] Estimated DPR correctly, skipping resize
[2020-01-13 11:18] [INFO] Cell Size: 9 x 17
[2020-01-13 11:18] [INFO] Padding: 2 x 2
[2020-01-13 11:18] [INFO] Width: 814, Height: 463
[2020-01-13 11:18] [INFO] PTY Dimensions: Line(27) x Column(90)
[2020-01-13 11:18] [INFO] Initialisation complete
[2020-01-13 11:18] [DEBUG] Term::resize dimensions unchanged
[2020-01-13 11:18] [INFO] Width: 814, Height: 463
[2020-01-13 11:18] [INFO] Goodbye
```
Keyboard and bindings:
```
[2020-01-13 11:17] [INFO] Welcome to Alacritty
[2020-01-13 11:17] [INFO] Configuration loaded from "/home/toast/.config/alacritty/alacritty.yml"
[2020-01-13 11:17] [INFO] Device pixel ratio: 1
[2020-01-13 11:17] [INFO] Initializing glyph cache...
[2020-01-13 11:17] [INFO] ... finished initializing glyph cache in 0.015014405s
[2020-01-13 11:17] [INFO] Estimated DPR correctly, skipping resize
[2020-01-13 11:17] [INFO] Cell Size: 9 x 17
[2020-01-13 11:17] [INFO] Padding: 2 x 2
[2020-01-13 11:17] [INFO] Width: 814, Height: 463
[2020-01-13 11:17] [INFO] PTY Dimensions: Line(27) x Column(90)
[2020-01-13 11:17] [INFO] Initialisation complete
[2020-01-13 11:17] [INFO] glutin event: NewEvents(Init)
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(165675010))))
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1655, tv_nsec: 629867134 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Focused(true) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 966.0, y: 765.0 }, modifiers: (empty) } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Resized(LogicalSize { width: 814.0, height: 463.0 }) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Moved(LogicalPosition { x: 0.0, y: 0.0 }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(165675010))))
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] Width: 814, Height: 463
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1655, tv_nsec: 632185908 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1655, tv_nsec: 914666900 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1655, tv_nsec: 936740470 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1655, tv_nsec: 946202095 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Title("~"))
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1656, tv_nsec: 472833140 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1656, tv_nsec: 473758817 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1656, tv_nsec: 477577270 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1656, tv_nsec: 494235799 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: (empty) }) }
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: ModifiersChanged(CTRL) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 43485919 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 43632227 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: CTRL }) }
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: ModifiersChanged(CTRL | ALT) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 76449004 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 76537055 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 103, state: Pressed, virtual_keycode: Some(Up), modifiers: CTRL | ALT }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 895543452 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 103, state: Released, virtual_keycode: Some(Up), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Focused(false) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Focused(true) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 966.0, y: 736.0 }, modifiers: CTRL | ALT } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 103, state: Pressed, virtual_keycode: Some(Up), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 896109877 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 896904325 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 897957793 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 898327779 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 103, state: Released, virtual_keycode: Some(Up), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Focused(false) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 911827535 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 911906917 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 929271417 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 931029506 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 103, state: Released, virtual_keycode: Some(Up), modifiers: CTRL | ALT }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1657, tv_nsec: 962540006 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 108, state: Pressed, virtual_keycode: Some(Down), modifiers: CTRL | ALT }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 207515373 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 207766495 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 207978051 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 209020625 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 209292628 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: Focused(true) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 966.0, y: 736.0 }, modifiers: CTRL | ALT } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 108, state: Pressed, virtual_keycode: Some(Down), modifiers: CTRL | ALT }, is_synthetic: true } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 212267079 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 212810378 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 212886368 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 108, state: Released, virtual_keycode: Some(Down), modifiers: CTRL | ALT }) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 108, state: Released, virtual_keycode: Some(Down), modifiers: CTRL | ALT }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 271579895 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }) }
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: ModifiersChanged(CTRL) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: CTRL }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 397534315 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(C), modifiers: CTRL }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 598494539 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(C), modifiers: CTRL }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: ReceivedCharacter('\u{3}') }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 598658196 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 598701965 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 598937863 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Title("~"))
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 599639255 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 611097960 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 627762461 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 46, state: Released, virtual_keycode: Some(C), modifiers: CTRL }) }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 46, state: Released, virtual_keycode: Some(C), modifiers: CTRL }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 695555733 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 32, state: Pressed, virtual_keycode: Some(D), modifiers: CTRL }) }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 943540633 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 32, state: Pressed, virtual_keycode: Some(D), modifiers: CTRL }, is_synthetic: false } }
[2020-01-13 11:17] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(165675010))), event: ReceivedCharacter('\u{4}') }
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 943664003 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 943714789 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 1658, tv_nsec: 943957732 }, requested_resume: None })
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Exit)
[2020-01-13 11:17] [INFO] glutin event: UserEvent(Wakeup)
[2020-01-13 11:17] [INFO] glutin event: MainEventsCleared
[2020-01-13 11:17] [INFO] glutin event: RedrawEventsCleared
[2020-01-13 11:17] [INFO] glutin event: LoopDestroyed
[2020-01-13 11:17] [INFO] Goodbye
```

**Comment by chrisduerr** [comment] 2020-01-13 16:51
This is a duplicate of https://github.com/alacritty/alacritty/issues/3109.

**Closed by chrisduerr** 2020-01-13 16:51 UTC
