### ISSUE TITLE
not show Chinese words

### ISSUE THREAD

**Issue by zjiel** [alacritty/alacritty#6000] opened 2022-04-15 13:57 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: 0.10.1
Linux/BSD: X11

I am able to see Chinese words when use fcitx5, but show error characters. It works well from other terminal, for instance, mate-terminal.

**Comment by chrisduerr** [comment] 2022-04-15 17:12
Could you be a little more specific please?

**Comment by zjiel** [comment] 2022-04-16 00:35
Thx for your quick response:

I am able to see the right Chinese characters as snapshot 2022-04-16_08-26. I see the error character when I choose option 2 as 2022-04-16_08-26_1.

![2022-04-16_08-26](https://user-images.githubusercontent.com/19465768/163654762-27e4c4a1-c9da-4ac5-b8af-0993f9f8a8c1.png)
![2022-04-16_08-26_1](https://user-images.githubusercontent.com/19465768/163654790-97176ba9-6ebc-4ed2-96e7-8386854a2a74.png)

**Comment by chrisduerr** [comment] 2022-04-16 06:14
What's your locale?

**Comment by zjiel** [comment] 2022-04-18 01:41
LANG=en_US.utf8
LC_CTYPE=zh_CN.UTF-8
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

**Comment by chrisduerr** [comment] 2022-04-18 05:23
If you change `LC_CTYPE`, does that change anything?

**Comment by yanganto** [comment] 2022-10-05 02:06
Chinese works with `alacritty` 0.10.1

![alacity_chinese](https://user-images.githubusercontent.com/10803111/193963086-af79c6b1-4650-4880-84d6-aa10a49e1640.png)

From my side, I can not type Chinese words into the terminal, but I can copy and paste them from other applications.  The issue is the input method does not work with `alacritty`, or I only set local as the following.
```
LANG=en_US.UTF-8
```
Showing Chinese words look good.  

Just a reference for @chrisduerr, this issue could be closed.

**Comment by chrisduerr** [comment] 2022-10-05 03:30
Yeah, closing since there hasn't been a reply to my last comment.

**Closed by chrisduerr** 2022-10-05 03:30 UTC
Labels: F - insufficent detail
