### ISSUE TITLE
copy/paste broke on wayland after switching to console

### ISSUE THREAD

**Issue by wommel** [alacritty/alacritty#3050] opened 2019-11-28 17:12 UTC
On archlinux using sway after switching to console copy/paste does not work in windows opened before switching.

~~Until version 0.4.0 the same issue existed for paste but it got fixed :)~~

**Comment by kchibisov** [comment] 2019-11-28 17:17
I'm aware of this issue and it was never fixed iirc. Switching to console can kill clipboard in some alacritty instances for whatever reason, so purely random thing.

**Comment by wommel** [comment] 2019-11-28 17:34
you are right :(

it coincidentally worked on my first test.

**Comment by lovesegfault** [comment] 2019-11-29 05:48
I can reproduce this on NixOS unstable.

**Comment by cole-h** [comment] 2019-12-22 16:12
I have also reproduced this by putting my computer to sleep (`systemctl suspend`). Every terminal instance I had open can no longer copy/paste to/from anywhere (even itself).

Uncertain if suspending reproduces every time. Will update tomorrow whether or not that is the case --  might make this easier to resolve.

`alacritty 0.4.1-dev (8a833406)`

**Comment by kchibisov** [comment] 2019-12-22 16:14
suspend and tty switch should trigger the same events, so it's a bit expected for them to cause this issue.

**Comment by eternal-sorrow** [comment] 2019-12-30 22:14
I have the same issue on sway here.

**Comment by leehambley** [comment] 2019-12-30 22:16
Same issue on Wayland, Gnome, Fedora here (only sharing because I don't think this is Sway specific, but another Wayland funtime)

**Comment by Kha** [comment] 2020-02-06 10:45
This issue is annoying enough that I was about to try debugging it, but it looks like it has already been **fixed on master**! I can definitely reproduce it with 0.4.1 on sway 1.2, but not anymore using b72903e720ca1fef2ed450c1026eb8331efc0288. Not sure which commit actually fixed it.

**Comment by chrisduerr** [comment] 2020-02-06 16:43
@kchibisov Could you take another look at this? I don't see any reason why it would be fixed, so I'd be a bit cautious about closing this prematurely.

**Comment by kchibisov** [comment] 2020-02-06 16:47
I also don't see any point why this thing could be closed tbh. We did literally nothing about it since v0.4.1 so it's likely a luck or someone stopped switching to console that often.

I'll take a look on this thing right after I'll finish other Wayland/font related font.

**Comment by wommel** [comment] 2020-02-06 17:09
sadly still occures for me on current master

**Comment by Kha** [comment] 2020-02-06 17:12
Yes, I may have spoken too soon :( . I even gave it a day, but the issue seems to be less reproducible than I thought.

**Comment by cole-h** [comment] 2020-02-06 22:40
Without having any underlying knowledge on how our clipboard behaves (in general, much less on Wayland), I would hazard a guess that this takes a while to manifest. I've previously suspended for a few minutes at a time and the issue doesn't crop up, but if I suspend overnight (usually around 7-8 hours), all of my terminals lose clipboard functionality upon wake. It's unfortunate that this takes so much time to (reliably) manifest.

**Comment by Kha** [comment] 2020-02-29 11:17
A few weeks later, I can definitely confirm that the issue completely vanished for me after moving to b72903e after all. Unfortunately, as @cole-h said, it seems to be very hard to reproduce, so I can't really bisect the commits in between. Even worse, if I run the stable version of alacritty in parallel to the mentioned commit, switching to a TTY reliably breaks C&P **in the pre-release alacritty only**. It is only when I run nothing but that pre-release commit that I don't get this issue anymore.

**Closed** 2020-03-09 23:15 UTC
Labels: B - bug, DS - Wayland, H - linux, S-clipboard
