### ISSUE TITLE
Keys interpreted as tmux commands sometimes after alt-tabbing

### ISSUE THREAD

**Issue by kcking** [alacritty/alacritty#3376] opened 2020-02-24 21:44 UTC
### Bug
I use tmux within alacritty and everything has been working great on 0.3.3 for 6 months now. Yesterday I upgraded to 0.4.1 with brew cask and now sometimes when I alt-tab back into alacritty all of my key strokes are interpreted as tmux commands. For example, if I hit x it closes the pane, v it splits the pane. I have to alt-tab back out and in again to fix this behavior.

### System

OS: macOS 10.14.6 (18G3020)
Version: 
Problem present in both `alacritty 0.4.1 (4d9253b)` (current brew cask) and `alacritty 0.4.2-dev (14dc170)`
Problem not present in `alacritty 0.3.3 (cc3e4d3)`, which I have been using for months.

### Logs

Crashes: not crashing :)
Font/Terminal size:
```
[2020-02-24 12:58:41.976239000] [DEBUG] Estimated DPR: 2
[2020-02-24 12:58:41.976293000] [DEBUG] Estimated Cell Size: 24 x 50
[2020-02-24 12:58:41.976314000] [DEBUG] Estimated Dimensions: None
[2020-02-24 12:58:42.034966000] [INFO] Device pixel ratio: 2
[2020-02-24 12:58:42.037598000] [INFO] Initializing glyph cache...
[2020-02-24 12:58:42.079379000] [INFO] ... finished initializing glyph cache in 0.041721603s
[2020-02-24 12:58:42.079427000] [INFO] Cell Size: 24 x 50
[2020-02-24 12:58:42.079443000] [INFO] Padding: 0 x 0
[2020-02-24 12:58:42.079459000] [INFO] Width: 1600, Height: 1200
[2020-02-24 12:58:42.079503000] [INFO] PTY Dimensions: Line(24) x Column(66)
```
Keyboard and bindings: `alacritty --print-events`
When running alacritty with `--print-events` I have not been able to repro this issue :/

Thanks in advance for any help with this issue!

**Comment by kchibisov** [comment] 2020-02-24 21:58
duplicate of #3188

**Closed by kchibisov** 2020-02-24 21:58 UTC
