### ISSUE TITLE
Detect and Alert Users on Unused YAML Keys

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#3467] opened 2020-03-15 16:43 UTC
To help users configure Alacritty more reliably, we should either warn, or throw errors when an unused YAML key is provided. I've been bit by this a number of times. There are a few ways I see silent unused keys causing issues.

1. I forget what mapping a key should belong to, for example
```yaml
window:
  title: Foo
  dynamic_title: false
```
2. I misspell a key name (I'm a horrible speller)
```yaml
window:
  decerations: none
```
3. I mess up indentation, since YAML wants to make things as hard for people as possible (taken from #3462)
```yaml
colors:
  primary:
    background: '0x272822'
    foreground: '0xF8F8F2'
  normal:
   black:   '0x272822'
   # ...
   white:   '0xF8F8F2'
  bright:
   black:   '0x75715E'
   # ...  
   white:   '0xF9F8F5'
  background_opacity: 0.0
```

I would expect each of these examples to be alerted to the user when they attempt them. Since they are all clearly errors. I'm sure I could hunt down issues for each of these cases, and there would be a number of them, however I'm also sure we are all aware of this issue, and it shouldn't need further motivation.

Perhaps https://github.com/dtolnay/serde-ignored can save us for too much headache implementing this. The main concern is with allowing YAML templates (or whatever they are called) for more complex user configurations. Ideally only **used** templates would not cause a warning.

**Comment by ru-lai** [comment] 2020-03-19 11:11
Hi!
I'd like to take this issue.  
When I get the go ahead, I'll start to post any findings / questions in this issue.

**Comment by ru-lai** [comment] 2020-03-25 12:22
Hey @nixpulvis, I had a few questions after digging in:

First, What approach do you suggest we take in integrating serde_yaml in the project?

Yaml files are not consumable out of the box with serde_ignored as of right now, due to the face that it doesn't appear that the Deserializer is publicly available in serde_yaml at this moment.

https://github.com/dtolnay/serde-yaml/issues/44

If we are looking to implement in the interim, do you think that it would be best to implement a conversion from the yaml string to json or read the values with a reader (both solutions mentioned in the issue). 

Second, even if we integrate serde_ignored into the project, we can solve the yaml key with empty value as well as duplicated issues it doesn't seem to address config keys that are mistyped / misspelled.  I was thinking of taking the following approach for this:
1. Using [this method](http://blog.notdot.net/2007/4/Damn-Cool-Algorithms-Part-1-BK-Trees) of using a BKTree and the Levenshtein distance to store all the strings in the config. A crate for this exists [here](https://github.com/eugene-bulkin/rust-bk-tree)
2. Based on the value of the key and a constant we choose the edit distance to be, we offer an error message with suggestions.

How poorly misspelled do we want to warn the users of?  And do we want to show the user all of their config warnings at one time?

**Comment by kchibisov** [comment] 2020-03-25 12:45
I'd like to add one note, users could have 'unused' values, which are actually used for other purposes, like multi color scheme setups, etc. So I'm completely against warninig on all unused values. However we dicused recently on moving to TOML for newer configurations (keeping `yaml` for some time), so before we dig to match into YAML voodoo here, maybe we shouldn't do 'Alert's at all, since in TOML it's pretty hard to make a mistake.

For now I see too much complexity for such feature. The main problem I see with our config are errors due to indention, they could be solved by using TOML.

I'd also like to haer @chrisduerr opinion here, so we won't end up doing useless work.

**Comment by nixpulvis** [comment] 2020-03-25 13:00
Good point @kchibisov, if this isn't an easy fix, perhaps we should look into what the solution to the same issues is in TOML as well. Since I know there has been general support for switching our config format over to that at some point.

@ru-lai 

I'm not a fan of deserializing everything to strings.

I'm also unsure we need to do anything fancy with levenshtein distance. I would simply expect an error on a key that isn't expected. Perhaps a feature like "did you mean xxx" would be nice, but it's not required.

**Comment by chrisduerr** [comment] 2020-03-26 01:36
> keeping yaml for some time

I'm not sure if I'd ever want to remove the ability to use yaml tbh. TOML just seems to be missing some features of YAML that people actually use. So I'd assume for now that it will forever be the case that there might be some unused keys we want to allow.

> I'm also unsure we need to do anything fancy with levenshtein distance.

I agree on this, we should keep it simple. We don't need to suggest what the user might have wanted, they can easily figure that out themselves.

I think the best approach would be to just log it to debug logs to make troubleshooting easier for us. Since I am not aware of any solution that wouldn't harm users that know how to type.

**Comment by nixpulvis** [comment] 2020-03-26 14:44
> I think the best approach would be to just log it to debug logs to make troubleshooting easier for us. Since I am not aware of any solution that wouldn't harm users that know how to type.

I disagree with this. Why wouldn't we throw a proper warning or error (in the yellow/red box)? Why should we, the developers, be involved in fixing user configs. Many programs I know of alert users visibly on a bad config.

**Comment by chrisduerr** [comment] 2020-03-26 14:55
> Why wouldn't we throw a proper warning or error (in the yellow/red box)?

Because we have no way to know when it is actually a mistake or when it was done intentionally?

Having unused fields in a yaml file is not an error and it shouldn't be treated as one. The user might be doing it for a very good reason.

**Comment by nixpulvis** [comment] 2020-03-26 15:19
> The user might be doing it for a very good reason.

I'm assuming you're imagining cases where the user uses "repeated" mappings, for example https://github.com/alacritty/alacritty/wiki/Color-schemes#multiple-schemes. However, I wouldn't expect this to log anything then either, since it's not unexpected. I'm personally not a fan of these `&template` keys in my config, but I understand some people find them useful.

Perhaps we should only throw an error on unused keys underneath one level of our own built in keys. This would catch any issues, though not all of them.

**Comment by chrisduerr** [comment] 2020-03-26 15:27
> Perhaps we could only throw an error on unused keys underneath one level of our own built in keys. This would catch any issues, though not all of them.

That seems rather complicated for a minor improvement that fixes only some of the issues.

**Comment by nixpulvis** [comment] 2020-03-26 16:17
I wonder if we could just ignore unused anchor keys (keys with a leading `&`)?

**Comment by chrisduerr** [comment] 2020-03-26 21:05
Not having a yaml anchor doesn't mean it's not intentional.

**Comment by nixpulvis** [comment] 2020-03-26 21:21
@chrisduerr can you give an example? I'm honestly not sure I'm following you here.

**Comment by chrisduerr** [comment] 2020-03-26 23:17
> can you give an example

Just look at the yaml anchor colorscheme example. The key `schemes` is just for organization and completely unused.

**Comment by ru-lai** [comment] 2020-04-05 07:59
@chrisduerr @nixpulvis it seems like then that this feature will do the following:
1. Find all leaf nodes in a nested structure that don't have any values
i.e. primary in the following
```
schemes:
    colors:
       primary:
       secondary: '#cacaca'
```
2. Print out a debug log that says that there is a leaf key in the config file that does not have a value.

Is my understanding correct?

**Comment by chrisduerr** [comment] 2020-04-05 14:39
@ru-lai Your understanding is not correct. The problem is not about finding leaf nodes without any values, but also about finding nodes with values that are in the incorrect location, or nodes that shouldn't exist in the first place.

As already discussed in this issue, there is no clear solution to this though.

**Comment by Fi3** [comment] 2020-04-08 14:52
Just warn on everything but the key prefixed by `ingore`. And in the warning put something like:
```
Unused key "schemes" at line ...,
if you did it intentionally change the key to "ingnore-schemes" to fix the warning
```
Could be a solution?

**Comment by nixpulvis** [comment] 2020-04-08 15:10
@Fi3 I feel like that could be really irritating for users who **intentionally** leave unused keys in the config as mentioned in the #multiple-schemes link, pasted below:

```yaml
schemes:
  solarized_light: &light
    primary:
      #...
    normal:
      #...
    bright:
      #...
  solarized_dark: &dark
    primary:
      #...
    normal:
      #...
    bright:
      #...

colors: *light
```

Notice how the `light` key is the only one currently used here.

**Comment by Fi3** [comment] 2020-04-08 16:31
@nixpulvis  Yes, actually I was thinking at ignoring anything nested under a key prefixed with `ignore` but I see that it doesn't completely solve the issue. Ignoring anything with anchor key as pointed out above by @chrisduerr  it will warn for the unused  key `schemes`

**Comment by nixpulvis** [comment] 2020-04-08 17:00
I think I'm thinking of something like **contains** an anchor tag...

**Comment by chrisduerr** [comment] 2022-12-28 18:39
This really is only an issue because we're using YAML and that's hard to use. I think rather than some overly complicated solution like detecting unused keys, it would be much better to just switch to a better configuration file format.

So closing in favor of https://github.com/alacritty/alacritty/issues/6592.

**Closed by chrisduerr** 2022-12-28 18:39 UTC
Labels: enhancement, help wanted, P - low, S - config
