### ISSUE TITLE
When in fullscreen other windows can't be above alacritty (eg via alt-tab)

### ISSUE THREAD

**Issue by desmap** [alacritty/alacritty#4072] opened 2020-08-03 12:55 UTC
### System

OS: Windows 
Version: 5

**Comment by kchibisov** [comment] 2020-08-03 12:57
it's a fullscreen, so I don't expect anything to be above it, you likely want maximize, right?

**Comment by desmap** [comment] 2020-08-03 13:35
> it's a fullscreen, so I don't expect anything to be above it, you likely want maximize, right?

Nope. Are you on a Windows system? All the Windows terminals/consoles let you either move or alt-tab other windows on top of of the full screen mode, Windows users kind of expect this and without, it's hurting productivity.

Terminal/consoles in full-screen != video player in full-screen.

also a screen shot for you (this chrome window above full-screen WSL):
![image](https://user-images.githubusercontent.com/43666255/89188369-da2aab80-d59e-11ea-91e0-1c3a06611c7d.png)

besides: everytime you alt tab a window on that full-scrreen display with alacritty, alacritty flickers (like it is broken or so)

**Comment by kchibisov** [comment] 2020-08-03 13:57
>Nope. Are you on a Windows system?

No. I don't use proprietary systems.

@Osspial sorry for pining here, are you aware whether it should be done somewhere in winit, or it's already exposed by winit, but we're not utilizing it in alacritty.

**Comment by agilesteel** [comment] 2020-08-19 22:17
I can confirm that switching from a full screen alacritty to another app gives focus to another app. However alacritty stays on top of everything and so the focus behavior is not visible. I had vs code "behind it" and the keyboard events went to vs code even though alacritty was above all.

This happens only in alacritty and only in full screen.

**Comment by habamax** [comment] 2020-08-20 12:59
yep, this is kind of annoying when you try to switch to a browser to check documentation and browser "gets the focus" but is invisible -- alacritty is on top of it and doesn't get any input.

**Comment by habamax** [comment] 2020-08-20 13:03
Btw, windows terminal (new one) and cmd.exe have the same Alt-Enter to goto fullscreen and both allow to switch (alt-tab) to another windows/applications.

**Comment by black-desk** [comment] 2020-10-14 03:37
any progress?

**Comment by p5a0u9l** [comment] 2020-11-25 18:47
> i don’t use proprietary systems

not super helpful. not all of us have the luxury of choosing what platform our employers support. 

would be nice to get an update on this. i much prefer using alacritty for performance, but windows terminal gets this seemingly basic behavior correct. then again windows terminal has to be restarted periodically...

**Comment by metryy** [comment] 2020-12-05 16:29
Are there any plans for supporting this? I'm in the same boat as @p5a0u9l and the other modes are buggy for me (opacity rendering, weird scaling bugs, etc) so it would be really helpful if the alt+tab functionality worked on Windows.

**Comment by bradking** [comment] 2020-12-06 16:43
This looks like rust-windowing/winit#1540, which is fixed in upstream winit but not yet released.

**Closed** 2020-12-11 00:40 UTC
Labels: A - deps, B - bug, C - waiting on dependency, H - windows
