### ISSUE TITLE
slow mission control animation

### ISSUE THREAD

**Issue by miguelaht** [alacritty/alacritty#5466] opened 2021-08-31 15:20 UTC
I've noticed when doing the mission control gesture in Mac and the focus is set in the Alacritty window, the animation seems slow and lagged.
The problem is only present after the window reaches certain size.

https://user-images.githubusercontent.com/61668895/131529780-7869343e-c878-4f22-a457-cd75f4d3b8c9.mp4

### System

OS: macOS
Version: 0.9.0 (fed349a)

**Comment by chrisduerr** [comment] 2021-08-31 22:05
Duplicate of https://github.com/alacritty/alacritty/issues/4474.

**Closed by chrisduerr** 2021-08-31 22:05 UTC
