### ISSUE TITLE
Alacritty stops listening to keypresses events after a fashion of time

### ISSUE THREAD

**Issue by Lomig** [alacritty/alacritty#3431] opened 2020-03-08 02:51 UTC
### System

OS: macOS
Version: alacritty 0.4.1 (4d9253b)
Keyboard Layout: MacOS, French AZERTY

### Bug

After some random time, Alacritty starts acting strangely regarding keyboard inputs:
- Sometimes the modifiers is detected as pressed when it's not the case. For an example, typing `v` would then paste the content of the clipboard as if it was `command + v`. (I was not able to reproduce the bug for me to provide any log)
- Sometimes the opposite : the modifier + key is only detected as the key without any modifier

For this second issue, it happened while I was testing keybindings, so I have been able to see the output of `alacritty --print-events` : no event is registered anymore by glutin.

You can see it in action here: https://drive.google.com/file/d/1fX5nKaqtbIytZ_oOzYMbcRBRb1clrgah/view?usp=sharing

As French layouts heavily use modifiers, and as I have many keybindings set for tmux and vim, this makes alacritty unusable :/

Thanks a lot in any case for everything :)

**Comment by chrisduerr** [comment] 2020-03-08 03:20
Duplicate of https://github.com/alacritty/alacritty/issues/3188.

**Closed by chrisduerr** 2020-03-08 03:20 UTC

**Comment by Lomig** [comment] 2020-03-08 12:25
Sorry, @chrisduerr I was not able to find a previous issue talking about the command key.

This being said, Issue #3188 does not seem related to the main issue I'm describing here: after a moment, alacritty does not listen to any modifier keys anymore, and every keystroke is detected as being the pure key.

**Comment by chrisduerr** [comment] 2020-03-08 14:31
I'd be surprised if that isn't the same underlying issue as #3188. Though if you're willing to build from source, you can test it yourself since a patch for #3188 is available.

Otherwise, feel free to wait until #3188 is closed and 0.4.2 is released to test it. If it's still broken, re-opening this shouldn't be a problem.

**Comment by Lomig** [comment] 2020-03-08 18:04
Will do :)

**Comment by nixpulvis** [comment] 2020-03-08 18:39
@Lomig if you want to determine if the patch fixes things for you, and help confirm this is in fact a duplicate, here is the comment with the patch specifically https://github.com/alacritty/alacritty/issues/3188#issuecomment-591075711.
