### ISSUE TITLE
Alacritty exhibiting very strange behaviour on Wayland

### ISSUE THREAD

**Issue by K4LCIFER** [alacritty/alacritty#5739] opened 2022-01-02 03:53 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Arch Linux
Version: Compiled from git repo, and also tried most recent full release in arch repos
Linux/BSD: Gnome Wayland

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
```
Created log file at "/tmp/Alacritty-19745.log"
[2022-01-01 19:45:13.727374976] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/<user>/.config/alacritty/alacritty.yml"
[2022-01-01 19:45:13.739365953] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-01 19:45:13.741333973] [DEBUG] [alacritty] Estimated DPR: 1
[2022-01-01 19:45:13.741358603] [DEBUG] [alacritty] Estimated window size: None
[2022-01-01 19:45:13.741364829] [DEBUG] [alacritty] Estimated cell size: 9 x 19
[2022-01-01 19:45:13.775614471] [INFO ] [alacritty] Device pixel ratio: 1
[2022-01-01 19:45:13.778891178] [INFO ] [alacritty] Initializing glyph cache...
[2022-01-01 19:45:13.781496528] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-01 19:45:13.785898402] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-01 19:45:13.789567479] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-01 19:45:13.793548334] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-01 19:45:13.798351378] [INFO ] [alacritty] ... finished initializing glyph cache in 0.019428631s
[2022-01-01 19:45:13.798400550] [INFO ] [alacritty] Cell size: 9 x 19
[2022-01-01 19:45:13.798410296] [INFO ] [alacritty] Padding: 0 x 0
[2022-01-01 19:45:13.798426812] [INFO ] [alacritty] Width: 800, Height: 600
[2022-01-01 19:45:13.808086292] [INFO ] [alacritty] PTY dimensions: 31 x 88
[2022-01-01 19:45:13.809655047] [INFO ] [alacritty] Initialisation complete
zsh: segmentation fault (core dumped)  alacritty -vv
```
Keyboard and bindings: `alacritty --print-events`
```
Created log file at "/tmp/Alacritty-20280.log"
[2022-01-01 19:47:39.195565223] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/<user>/.config/alacritty/alacritty.yml"
[2022-01-01 19:47:39.247241609] [INFO ] [alacritty] Device pixel ratio: 1
[2022-01-01 19:47:39.250521294] [INFO ] [alacritty] Initializing glyph cache...
[2022-01-01 19:47:39.268856231] [INFO ] [alacritty] ... finished initializing glyph cache in 0.018311216s
[2022-01-01 19:47:39.268889868] [INFO ] [alacritty] Cell size: 9 x 19
[2022-01-01 19:47:39.268897355] [INFO ] [alacritty] Padding: 0 x 0
[2022-01-01 19:47:39.268904942] [INFO ] [alacritty] Width: 800, Height: 600
[2022-01-01 19:47:39.278662512] [INFO ] [alacritty] PTY dimensions: 31 x 88
[2022-01-01 19:47:39.280379687] [INFO ] [alacritty] Initialisation complete
[2022-01-01 19:47:39.280444298] [INFO ] [alacritty] glutin event: NewEvents(Init)
[2022-01-01 19:47:39.280498636] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-01-01 19:47:39.280683418] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94395114237872))))
[2022-01-01 19:47:39.280699218] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-01-01 19:47:39.291408821] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11286, tv_nsec: 553878821 }, requested_resume: None })
[2022-01-01 19:47:39.291514219] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Wayland(WindowId(94395114237872)))), payload: Terminal(CursorBlinkingChange) })
[2022-01-01 19:47:39.291555229] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Wayland(WindowId(94395114237872)))), payload: Terminal(Wakeup) })
[2022-01-01 19:47:39.291564678] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-01-01 19:47:39.291603712] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94395114237872))))
[2022-01-01 19:47:39.291632548] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-01-01 19:47:39.297539030] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11286, tv_nsec: 560009153 }, requested_resume: None })
[2022-01-01 19:47:39.297585481] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-01-01 19:47:39.297593365] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-01-01 19:47:39.299104306] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11286, tv_nsec: 560082888 }, requested_resume: Some(Instant { tv_sec: 11287, tv_nsec: 304123832 }) })
[2022-01-01 19:47:39.299190507] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94395114237872))), event: Focused(true) }
[2022-01-01 19:47:39.299203984] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94395114237872))), event: ModifiersChanged((empty)) }
[2022-01-01 19:47:39.299213474] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-01-01 19:47:39.299219321] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94395114237872))))
[2022-01-01 19:47:39.299225645] [INFO ] [alacritty] glutin event: RedrawEventsCleared
zsh: segmentation fault (core dumped)  alacritty --print-events
```
I recently switched from Xorg (where Alacritty was woriking perfectly fine) to Wayland on Gnome, and now Alacritty has completely ceased all normal functionality. For the most part, If i try to launch alacritty, I'll end up with a transparent window that will eventually just completly crash as seen below

![image](https://user-images.githubusercontent.com/7829231/147865567-3ee145c9-dca6-442b-8053-b119c31c3124.png)

If it does manage to launch, the window itself will be compeletly messed up (Doesn't use GTK at all, and doesn't really look like Qt either) as seen here

![image](https://user-images.githubusercontent.com/7829231/147865660-6bbb00e2-eaf4-48e1-8035-94527fcc9fcc.png)

I first encountered issues with the most up to date full release (which I had installed on Xorg), so I decided to install the git version (which is what is currently installed) and it didn't work either. 

Its essentially compeltely borked for me.

**Comment by chrisduerr** [comment] 2022-01-02 04:03
> If it does manage to launch, the window itself will be compeletly messed up (Doesn't use GTK at all, and doesn't really look like Qt either) as seen here

That's to be expected, because it doesn't.

>  For the most part, If i try to launch alacritty, I'll end up with a transparent window that will eventually just completly crash as seen below

Which GPU and is there any specific behavior that causes it to launch/crash? Or is it just completely random regardless of how often you launch it?

**Comment by K4LCIFER** [comment] 2022-01-02 04:22
> > For the most part, If i try to launch alacritty, I'll end up with a transparent window that will eventually just completly crash as seen below
> 
> Which GPU and is there any specific behavior that causes it to launch/crash? Or is it just completely random regardless of how often you launch it?

GPU: nvidia GTX 1080 with proprietary driver 495

It crashes as soon as it launches. Sometimes immediately crashes by just flickering into existance and dissapearing, and othertimes, the transparent window sits there for a bit until gnome says its not responding.

**Comment by chrisduerr** [comment] 2022-01-02 04:22
Try master please.

**Comment by K4LCIFER** [comment] 2022-01-02 04:27
> Try master please.

[I compiled directly from the git repository.](https://aur.archlinux.org/packages/alacritty-git/)

**Comment by chrisduerr** [comment] 2022-01-02 04:30
That's awfully imprecise. Does your build include https://github.com/alacritty/alacritty/commit/e2b5219eb40eaf36d8255cd87c5202bbb8ba0825?

**Comment by K4LCIFER** [comment] 2022-01-02 04:32
> That's awfully imprecise. Does your build include [e2b5219](https://github.com/alacritty/alacritty/commit/e2b5219eb40eaf36d8255cd87c5202bbb8ba0825)?

`alacritty --version`: alacritty 0.11.0-dev (e2b5219e)

**Comment by chrisduerr** [comment] 2022-01-02 17:17
Could you provide the `WAYLAND_DEBUG=1 alacritty` log for a broken instance?

**Comment by K4LCIFER** [comment] 2022-01-03 00:04
Okay something different is happening now. Alacritty seems to be launching properly everytime now (as in not transparent anymore); however, I cant interact with the window. What I mean by this is I cant click the titlebar buttons to close alacritty, or drag the window around by clicking on the titlebar. The only way to close it is by external means - i.e. typing `exit` to close the terminal, hitting `<alt> + <F4>`, etc. 

The titlebar itself also seems transparent to mouse clicks. For example, if I open an instance of alacritty infront of another program, and then click on the titlebar, the program behind alacritty will be focused into the foreground; however, clicking within alacritty (the terminal itself)  doesn't exhibit the same effect.

Furthermore, it also seems that alacritty exhibits different behaviour depending on how it is launched. If alacritty is launched by tyipng `alacritty` in the command line, the titlebar and everything works as expected; however, if I launch it via the desktop application icon, it exhibits those strange behaviours that I just described.

As for the output of `WAYLAND_DEBUG=1 alacritty`:
There was a constant output stream related to my mouse positition and interactions with alacritty, so I just let it run for ~3s and saved the output as seen [here](https://pastebin.com/QXkU9ahG). Let me know if you want more, or want me to capture it in a different way.

**Comment by chrisduerr** [comment] 2022-01-03 13:04
> Furthermore, it also seems that alacritty exhibits different behaviour depending on how it is launched. If alacritty is launched by tyipng alacritty in the command line, the titlebar and everything works as expected; however, if I launch it via the desktop application icon, it exhibits those strange behaviours that I just described.

That really sounds like something in your env is causing the problem. Please ensure your environment is setup properly **before** Alacritty is launched. Usually if things work when launching from an existing instance, it's not an Alacritty issue, I'd recommend checking locale first probably.

**Comment by MultisampledNight** [comment] 2022-04-20 08:23
This seems very similar to #5739. I can reproduce the issue even when starting from commandline, but I'm using the proprietary Nvidia driver, too. We have a similar issue over in Neovide, see https://github.com/neovide/neovide/issues/1280.

**Comment by MultisampledNight** [comment] 2022-04-20 10:45
Oh well, it's indeed resolved with the mentioned commit included.

**Comment by glfmn** [comment] 2022-10-12 01:10
I have been having the same issue on Wayland with Ubuntu 22.04 on the `amdgpu` driver.  Using `alacritty 0.12.0-dev (182086f5)` built from the master branch seems to work.

**Comment by chrisduerr** [comment] 2022-10-13 00:09
@K4LCIFER Others have claimed master fixes this, can you confirm?

**Closed** 2022-11-15 13:02 UTC
Labels: C - waiting on author
