### ISSUE TITLE
w3mimgdisplay not working correctly

### ISSUE THREAD

**Issue by throwup** [alacritty/alacritty#1021] opened 2018-01-12 19:49 UTC
Which operating system does the issue occur on?
Void Linux

If on linux, are you using X11 or Wayland?
X11

As the title implies image previews for ranger are not behaving correctly for me. Instead of displaying the image properly the preview pane simply stays empty. I can confirm that using the same methods in the urxvt-terminal leads to the images beeing displayed properly. The issue persist whether or not I am using a composite manager (compton).

Configurations used:
`set preview_images true`
`set preview_images_method w3m`

`set preview_images true`
`set use_preview_script true`
`set preview_script /usr/share/doc/ranger/config/scope.sh`
Taken from Issue #107

**Comment by nixpulvis** [comment] 2018-01-12 22:45
Does alacritty even support non-text output? I wasn't aware of it being a feature.

**Comment by maximbaz** [comment] 2018-01-12 23:18
@nixpulvis oh yeah, it's a pretty awesome thing and I use ranger constantly as image preview tool 🙂

@throwup I can only confirm that my config didn't change and it still works today, would be interesting to know why it doesn't work for you. Just to make sure, is the full path to `scope.sh` correct and the file exists, and are you using the latest version of ranger?

**Comment by nixpulvis** [comment] 2018-01-12 23:20
@maximbaz FWIW I copied you ranger config, and verified that `scope.sh` exists, but no image preview work with:

```
ranger-stable 1.8.1
Python 3.6.3 (default, Oct 24 2017, 14:48:20)
[GCC 7.2.0]
```

**Comment by maximbaz** [comment] 2018-01-12 23:22
Do you have w3m installed? It's a tool that is actually rendering the images.

**Comment by nixpulvis** [comment] 2018-01-12 23:23
o.O I guess that'll do it. Install and working now!

**Comment by throwup** [comment] 2018-01-13 11:47
@maximbaz 
My ranger version:
```
$ ranger --version
ranger-stable 1.8.1

Python 3.6.4 (default, Dec 19 2017, 18:03:06)
[GCC 7.2.0] 
```
w3m is installed
```
$ xbps-query -s w3m   
[*] w3m-0.5.3.git20170102_3     Text-based Web browser and pager (with Debian patches)
[*] w3m-img-0.5.3.git20170102_3 Text-based Web browser and pager (with Debian patches) - image display support
```

As I've said, your your configuration works for me when using Urxvt, so a wrong path should not be the issue.

**Comment by throwup** [comment] 2018-01-13 11:53
Oh and moreover, I have found that calling `neofetch --w3m /path/to/image` (neofetch is a sysinfo-script that can display pictures in the terminal using the w3m backend) also does not produce the correct result. So the issue should most definitely not be related to ranger.

**Comment by FichteFoll** [comment] 2018-01-15 19:38
ranger's preview works for me most of the time, but occasionally the image only shows up for a brief period of time and then disappears. This seems to be related to w3m moreso than ranger, but I don't know anything about the internals

**Comment by Declspeck** [comment] 2018-01-20 16:50
@FichteFoll I had the same problem, and managed to fix it. Turns out that `w3mimgdisplay` directly draws on the X11 window of the terminal. If the terminal happens to redraw after that, the image is lost. I believe there is a race condition, Alacritty may or may not swap buffers (or repaint for some other reason) after the image has been drawn. I don't think this is a bug in Alacritty, just that `w3mimgdisplay` is a huge hack.

I wrote a Bash script that delays image drawing requests by 100ms, which was enough to make the preview stable:

```bash
#!/bin/bash
{ 
  while read line; do 
    firstchar=${line:0:1}
    if [[ $firstchar = '0' ]]; then
      # Showing a picture - pause for a moment, in case the terminal has a pending redraw.
      sleep 0.1
    fi
    echo "$line"
  done; 
} | /usr/lib/w3m/w3mimgdisplay
```

You can make Ranger use that by exporting `W3MIMGDISPLAY_PATH` to point to the script. Note that the script references `w3mimgdisplay` by its absolute path, you might need to change it depending on your distro.

**Comment by maximbaz** [comment] 2018-01-20 20:04
I admire such hack 😄 But if it truly helps, maybe suggest incorporating this idea [in w3m itself](https://github.com/tats/w3m)?

**Comment by thegeekyone** [comment] 2018-01-26 00:35
I have to say that alacritty and w3m doesn't go well together, ranger, w3m or anything that is related with w3mimgdisplay does not work for me. while urxvt works flawlessly been trying everything to get image preview to work on alacritty :(

**Comment by jwilm** [comment] 2018-01-30 00:14
There may be something we can fix in Alacritty to prevent the final redraw. Would you mind trying this out with `--print-events` flag and seeing if you can tell what's triggering it?

**Comment by FichteFoll** [comment] 2018-01-30 02:53
Using #657 and `--print-events` doesn't seem to render much useful output. It only seems to show key events (I tried not to use the mouse since that would have been very noisy).

I started ranger in a directory with 6 folders and then some images. So, I had to press <kbd>Down</kbd> 6 times to have the first image rendered. I then proceeded to use up and down keys to have more images previewed. During the whole time, the preview went black (i.e. disappeared after a very short frame) 2 times, if I noticed that correctly. The last preview before pressing <kbd>q</kbd> and exiting ranger was also not rendered, despite the same image having worked before.

[alacritty-ranger-print-events.log](https://github.com/jwilm/alacritty/files/1676229/alacritty-ranger-print-events.log)

**Comment by thegeekyone** [comment] 2018-02-26 22:02
ok a update alacritty image preview works on gnome under xorg but it does not work under BSPWM which is quite odd :/

**Comment by code-andres** [comment] 2018-03-25 19:25
Hi, I tried a lot of terminal emulators for this issue (the only one that draw good the image is xterm) and I have a solution, mainly for XFCE users, but other desktop manager can work:

> Go to Settings > Window Manager Tweaks > Compositor > Uncheck "Enable display compositing"

Why this worked for me?

I read that w3m have problem with terminals with transparency settings, so first I put opacity to 1 on the transparency settings, and the image is draw a little better but with ugly noise.

I search for w3m and transparency keywords, and I read the answer on this site: [Unix StackExchange ranger image-preview with transparent terminal background](https://unix.stackexchange.com/questions/150135/ranger-image-preview-with-transparent-terminal-background)

It mention compton, a compositor for transparency, and I remembered some XFCE options for windows, shadows and other settings like transparency, so I uncheck this and tried again ranger image rendering... 

The result: A clean beautiful image.

This worked even for Terminator, Gnome Terminal and Xfce terminal, but alacritty draw the image better, the others for some reason keep showing the old images under the new one

The good thing: I have a perfect image rendering
The bad thing: Some windows shadows and decorations lost by disabling compton

For other users that does not have XFCE can search transparency settings for the desktop manager that affect the terminal image rendering.

I hope this help.

**Comment by ashkitten** [comment] 2018-03-28 18:25
What if w3imgdisplay instead drew on transparent overlays instead of the window itself? I'm sure this is probably the wrong place to be suggesting this but it definitely makes sense.

**Comment by slavoutich** [comment] 2018-04-05 12:54
I guess that the only non-hacky way to make this working is to incorporate image preview functionality into the terminal itself (like Kitty or Terminology do).
_Writing this mostly to subscribe on a thread :)_

**Comment by codebam** [comment] 2018-07-09 21:50
Can the hack be modified to work with w3m and other programs that use w3m-img other than ranger?

I tried moving `/usr/lib/w3m/w3mimgdisplay` to `/usr/lib/w3m/w3mimgdisplay_`, putting the script at `/usr/lib/w3m/w3mimgdisplay`, and changing the pipe in the script to `/usr/lib/w3m/w3mimgdisplay_` but that just broke images completely in w3m.

**Comment by simeir** [comment] 2018-12-03 00:41
I tried `neofetch --w3m /path/to/image` on the same image on alacritty and on urxvt as @throwup said. Things are displayed properly in urxvt, but on alacritty the output is some unreadable text. I redirected the output into files and did a diff. Everything was the same for the output of these 2 except for the name of the terminal. Therefore, I think the problem is from how alacritty interprets the information given to it to display.

I have also encountered the problem mentioned by @thegeekyone . ranger + w3m works properly in plasma and herbstluftwm for me, but in bspwm nothing is shown. This really is weird as apparently it is working [here](https://github.com/jwilm/alacritty/issues/706).

**Comment by oplehtinen** [comment] 2019-01-24 17:40
You can work around this by running neofetch with `--loop` :

> Redraw the image constantly until Ctrl+C is used. This fixes issues in some terminals emulators when using image mode.

**Comment by buzuck** [comment] 2019-05-22 09:04
A workaround is available here, by replacing `w3m` by `ueberzug`. I just tested it and it works for me. The dotfiles are available as well, and here is the commit Alkeryn made : https://github.com/Alkeryn/dotfiles/commit/c4f7072909f95a8ad3c0c137925cc3f2123cfb45

https://github.com/thestinger/termite/issues/501#issuecomment-468954048

**Comment by Alkeryn** [comment] 2019-05-23 00:07
@buzuck though that commit isn't a fix, it is just a regular of my dotfiles commit
but it is in .config/ranger/*

**Comment by binakot** [comment] 2020-01-15 10:12
Recently I got the same problem: ranger just do not show images. I checked w3m is installed. After a half hour I got it! If you are using Debian or Debian-based distro you have to install `w3m-img` package, because there in no `w3mimgdisplay` in default `w3m` package atm. Got it from [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=180814).

**Comment by RobertLemmens** [comment] 2020-05-20 18:47
> A workaround is available here, by replacing `w3m` by `ueberzug`. I just tested it and it works for me. The dotfiles are available as well, and here is the commit Alkeryn made : [Alkeryn/dotfiles@c4f7072](https://github.com/Alkeryn/dotfiles/commit/c4f7072909f95a8ad3c0c137925cc3f2123cfb45)
> 
> [thestinger/termite#501 (comment)](https://github.com/thestinger/termite/issues/501#issuecomment-468954048)

Can confirm this works! Looking at the github page they specifically developed it with race conditions in mind.

**Comment by spirkinator** [comment] 2020-06-25 02:08
Me too.  I isolated the issue to the window decorations section in the rc.conf.  When line 52 "decorations:" is uncommented and set to "none", the image previews don't display.  When the same line is commented or set to "full", image previews work.

`15 window:
 16   # Window dimensions (changes require restart)
...............
 49   # Values for `decorations` (macOS only):
 50   #     - transparent: Title bar, transparent background and title bar buttons
 51   #     - buttonless: Title bar, transparent background, but no title bar buttons
 52   decorations: none
`

Here are the versions I'm using:
PopOS 20.04
X11
alacritty/focal,now 0.4.3~1591123189~20.04~b089c66 amd64 [installed]
ranger/focal,focal,now 1.9.3-1build1 all [installed]
w3m-el-snapshot/focal,focal 1.4.632+0.20191218.2243.cef0c7e-1 all
w3m-el/focal,focal 1.4.632+0.20181112-2 all
w3m-img/focal,now 0.5.3-37 amd64 [installed]
w3m/focal,now 0.5.3-37 amd64 [installed]

**Comment by adnion** [comment] 2020-07-04 18:50
> > A workaround is available here, by replacing `w3m` by `ueberzug`. I just tested it and it works for me. The dotfiles are available as well, and here is the commit Alkeryn made : [Alkeryn/dotfiles@c4f7072](https://github.com/Alkeryn/dotfiles/commit/c4f7072909f95a8ad3c0c137925cc3f2123cfb45)
> > [thestinger/termite#501 (comment)](https://github.com/thestinger/termite/issues/501#issuecomment-468954048)
> 
> Can confirm this works! Looking at the github page they specifically developed it with race conditions in mind.

For me ueberzug does not work with ranger in alacritty. Still searching for a solution

**Comment by manub23** [comment] 2020-07-30 13:05
> For me ueberzug does not work with ranger in alacritty. Still searching for a solution

FWIW, this `rc.conf` works perfectly with alacritty.
```
set preview_images true
set preview_images_method ueberzug
set use_preview_script true
set preview_script ~/.config/ranger/scope.sh
```

**Comment by adnion** [comment] 2020-07-31 08:26
This works for X11 but not for alacritty in wayland

**Comment by strogiyotec** [comment] 2020-09-11 04:34
Be aware, config mentioned by @manub23  works perfectly fine only for X11. I accidentally ran `ubuntu on wayload` and it didn't work for me (waylod is not supported , only X11)

**Comment by Alkeryn** [comment] 2020-09-12 17:46
@strogiyotec i don't think w3mimgdisplay works in wayland either, afaik they both work by doing a draw using xorg.

**Comment by oknozor** [comment] 2020-11-03 10:38
Hello, have you considered [viu](https://github.com/atanunq/viu) ? It work fine for me under wayland+alacritty.  
I don't use ranger but I just submitted  [this PR](https://github.com/dylanaraps/neofetch/pull/1592) to neofetch.
Maybe it could be added to ranger to.

**Comment by chrisduerr** [comment] 2020-12-17 03:39
Closing since there's no change Alacritty is going to make to better support w3m. If it doesn't work right, it's because w3m is a massive hack.

**Closed by chrisduerr** 2020-12-17 03:39 UTC
