### ISSUE TITLE
Entering a Unicode character corrupts the displayed text

### ISSUE THREAD

**Issue by Kinrany** [alacritty/alacritty#2885] opened 2019-10-16 20:56 UTC
Alacritty 0.33

Windows, used with MinGW64

Entering character "П" (Russian capital "p", U+041F) and moving the cursor left twice corrupts the input. The cursor moves left twice even though I only entered one character, and the underlying characters change randomly.

Might be related to https://github.com/jwilm/alacritty/issues/473

**Comment by chrisduerr** [comment] 2019-10-16 21:10
Could you go into more detail what you mean by 'corruption'?

Sounds like it might be a duplicate of #1295.

**Comment by Kinrany** [comment] 2019-10-16 23:35
Might be related, yes.

Moving the cursor makes the terminal randomly replace characters with other characters from the same string or with character "▒".

For example, `$ Добрый день, товарищ` becomes `Добрый деварищо▒арищи▒`. (Note that `$` got eaten too.)

**Comment by Kinrany** [comment] 2019-10-18 01:04
Everything is fine when I use MinGW directly. The character has the regular width there, not like a `=>` or a similar glyph, if that's what you mean.

In Alacritty entering that single character results in the following message: `bash: $'▒\237': command not found`.

**Comment by chrisduerr** [comment] 2019-10-18 10:54
Having a separate glyph show up with other escapes (`\237`), makes me feel like this is unrelated to character width and instead an issue with Windows unicode support.

Have you tried both ConPTY and WinPTY and verified with `alacritty -v` that the correct PTY is spawned?

**Comment by Kinrany** [comment] 2019-10-18 11:12
`alacritty -v` prints "Using Winpty agent" even with `enable_experimental_conpty_backend: true`.

**Comment by chrisduerr** [comment] 2019-10-18 11:44
If you're talking about WSL2, you're probably even on some kind of Windows 10 insider build though, right? So definitely up to date?

**Comment by Kinrany** [comment] 2019-10-18 11:55
Not that I'm aware of. But I used a script to get rid of the MS bloatware.

I'm not using the Linux subsystem to run bash, if that's what you mean.

**Comment by chrisduerr** [comment] 2019-10-18 13:02
Hmm as usual with Windows those are a lot of moving pieces trying to fit together.

Can you reproduce this when starting Alacritty with cmd.exe?

**Comment by Kinrany** [comment] 2019-10-18 13:21
While trying to reproduce, I also noticed that it happens when I run Alacritty from cmd.exe or by clicking alacritty.exe, but it doesn't happen when I run Alacritty from bash.

Either way, can't reproduce with `alacritty -e cmd`.

**Comment by chrisduerr** [comment] 2019-10-18 13:28
> Either way, can't reproduce with alacritty -e cmd.

That might explain the troubles with reproducing this. Makes it sound like Alacritty is not at fault here, but maybe there's other things that can be tested here. Have you tried out a different shell?

**Comment by Kinrany** [comment] 2019-10-19 15:12
Setting up a new shell on Windows is kind of a pain :(

This isn't my first problem that seems to be a fault of Git Bash. I'll switch to another shell eventually and I'll be able to check then, but I'm not sure how much time it'll take.

Is there anything else I can do now?

**Comment by chrisduerr** [comment] 2019-10-19 17:12
No, but let us know if you can repro in a different shell.

**Comment by chrisduerr** [comment] 2020-01-19 15:56
If this issue is still relevant, have you ever managed to get ConPTY working? I'd assume that this might help with the issue and having an up to date Windows 10 seems like a good idea regardless.

**Comment by Kinrany** [comment] 2020-01-21 12:26
Sadly I still haven't managed to find anything better than Git Bash. At this point it seems easier to switch to WSL :(

**Comment by kchibisov** [comment] 2020-01-21 20:44
Well, you can just launch WSL inside alacritty and retest.

**Comment by Kinrany** [comment] 2020-01-21 20:54
Yeah, I don't have WSL set up, and it's a bit nontrivial because of other questionable OS customizations I made :)

**Comment by chrisduerr** [comment] 2020-01-21 21:37
> Sadly I still haven't managed to find anything better than Git Bash. At this point it seems easier to switch to WSL :(

While the shell might not help, I definitely think that ConPTY might though. Have you ever updated your Windows to test this? Based on the comment history it seems like you only ever ran this in WinPTY.

**Comment by Kinrany** [comment] 2020-01-21 23:41
Uhh, do you by any chance know a good article about all the different parts of a shell? I don't really know anything about ConPTY or WinPTY other than the names and that setting the config to use ConPTY didn't help the last time 😮

**Comment by chrisduerr** [comment] 2020-01-21 23:55
> ConPTY didn't help the last time

You said last time you tried ConPTY, it still printed `Using WinPTY agent` in the log, which indicates that your operating system does not support it yet. So I was curious if you've updated your system since and it is now working. If it doesn't print `Using ConPTY agent`, then it's not working yet.

I've mentioned Windows 10 previously, but you've never actually confirmed that you're running it. Is that accurate or are you maybe still on Windows 7 or 8? That would change things, since ConPTY isn't supported there yet.

**Comment by Kinrany** [comment] 2020-01-22 00:20
Yeah, it's Windows 10. It should be up to date.

I installed the latest Alacritty using Choco, pasted the config file from the 0.4.0 release, edited the config to use ConPTY, and ran `alacritty` with `cmd`:

```
C:\Users\Ruslan>alacritty -V

C:\Users\Ruslan>alacritty 0.4.0 (b115b90)


C:\Users\Ruslan>alacritty -v --config-file "C:\Users\Ruslan\AppData\Roaming\alacritty\alacritty.yml"

C:\Users\Ruslan>Created log file at "C:\Users\Ruslan\AppData\Local\Temp\Alacritty-6692.log"
[2020-01-22 03:16] [INFO] Welcome to Alacritty
[2020-01-22 03:16] [INFO] Configuration loaded from "C:\Users\Ruslan\AppData\Roaming\alacritty\alacritty.yml"
[2020-01-22 03:16] [INFO] Device pixel ratio: 1.25
[2020-01-22 03:16] [INFO] Initializing glyph cache...
[2020-01-22 03:16] [INFO] ... finished initializing glyph cache in 0.047542135s
[2020-01-22 03:16] [INFO] Cell Size: 10 x 21
[2020-01-22 03:16] [INFO] Padding: 0 x 0
[2020-01-22 03:16] [INFO] Width: 1422, Height: 700
[2020-01-22 03:16] [INFO] PTY Dimensions: Line(33) x Column(142)
[2020-01-22 03:16] [INFO] Using Winpty agent
[2020-01-22 03:16] [INFO] Initialisation complete
```

I had a suspicion that the config was not being loaded properly, but the path in the log is correct. And it's still `Using Winpty agent` :(

**Comment by chrisduerr** [comment] 2020-01-22 00:24
@Kinrany Then I suggest updating your operating system. The ConPTY is only supported in 1809+. Previous versions aren't supported anymore anyways, unless you're using Enterprise/Edu.

**Comment by Kinrany** [comment] 2020-01-22 00:32
You're right, my system is somehow on version 1803 even though the security updates are being applied. I'll fix that first.

**Comment by chrisduerr** [comment] 2020-11-28 15:18
Since there's been no reply, I'd assume the update fixed this issue.

**Closed by chrisduerr** 2020-11-28 15:18 UTC
Labels: A - needs repro, C - waiting on author, H - windows, S - unicode
