### ISSUE TITLE
Document setting instance and base class in --help output

### ISSUE THREAD

**Issue by atchim** [alacritty/alacritty#3615] opened 2020-04-19 16:38 UTC
When opening Alacritty with `--class` option it changes the window instance instead the class.
For example, if I do `alacritty --class foo` and I check the window properties I got:
```
Instance: foo
Class: Alacritty
Title: Alacritty
```
`--title` option is working as expected, although.

### Infos

OS: Funtoo Linux
Window Manager: dwm
Alacritty: alacritty 0.5.0-dev (03bce99)

**Comment by kchibisov** [comment] 2020-04-19 16:49
Does `--class foo,foo` works?

**Comment by atchim** [comment] 2020-04-19 16:58
> Does `--class foo,foo` work?

Yes, It works but it sets both instance and class. Also if I do `alacritty --class foo,bar` it sets instance to `foo` and class to `bar`.

**Comment by atchim** [comment] 2020-04-19 17:18
> Does `--class foo,foo` work?

Is it the expected way to set it?

Alacritty's help says:
```
--class <class> Defines window class on Linux [default: Alacritty]
```
So it should change only the class name.

I think would be nice if Alacritty had an option to set both at once. For example:
`--names <instance,class,title> Defines window instance, class and title names`

**Comment by chrisduerr** [comment] 2020-04-19 18:10
It seems like the `--help` is incorrect, the manpage has this documented correctly.

This is working exactly as intended. It's usually the instance class that should be changed anyways, not the base class. And it's possible to change both if you really want to.

So what exactly is the problem with this?

**Comment by atchim** [comment] 2020-04-19 18:22
> It seems like the `--help` is incorrect, the manpage has this documented correctly.
> [ ... ]
> So what exactly is the problem with this?

In this case the only problem is the help. Fixing the help message would be fine.

> I think would be nice if Alacritty had an option to set both at once.

If with `--class` option is possible to set both instance and class and with `--title` is possible to set title, so the creation of this new option is redundant and really not necessary, I think.

**Comment by chrisduerr** [comment] 2020-07-21 23:53
This was fixed in https://github.com/alacritty/alacritty/pull/3648.

**Closed by chrisduerr** 2020-07-21 23:53 UTC
Labels: D - easy, S - docs, help wanted
