### ISSUE TITLE
Alacritty receive characters when I use a shortcut to switch between XFCE desktop.

### ISSUE THREAD

**Issue by Hugal31** [alacritty/alacritty#3109] opened 2019-12-18 09:08 UTC
On XFCE, when I switch from virtual desktops with the shortcut Ctrl+Shift+Right or Left, when I come back to Alacritty, it prints a character, `C` (when I come back with Ctrl+Shift+Right) or `D` (with Ctrl+Shift+Left).

It is the only terminal emulator to do this, xfce4-terminal and terminator are not affected.

When I disable the shortcut in XFCE, all terminal emulators does print C or D when I do Ctrl+Shift+Right or Ctrl+Shift+Left.

I have no problem with Alacritty 0.3.3.

### System

OS: Linux
Version: alacritty 0.4.0 (b115b90)
Linux: X11

### Logs

Here is the output of `alacritty --print-events`, truncated from the press of Ctrl to the release of Ctrl.
What I exactly did:
- Start Alacritty
- Click the virtual desktop on the left
- Go back to the fist desktop with Ctrl+Shift+Right.

<details>
  <summary>Output of `alacritty --print-events`</summary>

```
  Created log file at "/tmp/Alacritty-13442.log"
[2019-12-18 09:44] [INFO] Welcome to Alacritty
[2019-12-18 09:44] [INFO] Configuration loaded from "/home/laloge_h/.config/alacritty/alacritty.yml"
[2019-12-18 09:44] [INFO] Device pixel ratio: 1
[2019-12-18 09:44] [INFO] Initializing glyph cache...
[2019-12-18 09:44] [INFO] ... finished initializing glyph cache in 0.006167811s
[2019-12-18 09:44] [INFO] Cell Size: 9 x 17
[2019-12-18 09:44] [INFO] Padding: 2 x 2
[2019-12-18 09:44] [INFO] Width: 800, Height: 600
[2019-12-18 09:44] [INFO] PTY Dimensions: Line(35) x Column(88)
[2019-12-18 09:44] [INFO] Initialisation complete
[2019-12-18 09:44] [INFO] glutin event: NewEvents(Init)

...

[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged { modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 433256249 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } }) }
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged { modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } } }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 433770839 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 106, state: Pressed, virtual_keycode: Some(Right), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }) }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 796762721 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: RedrawRequested }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 799029618 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: Focused(true) }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 1640.0, y: -46.0 }, modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }, is_synthetic: true } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }, is_synthetic: true } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 106, state: Pressed, virtual_keycode: Some(Right), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }, is_synthetic: true } }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 805464707 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2019-12-18 09:44] [INFO] glutin event: UserEvent(Wakeup)
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 807606616 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 820509558 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 837001636 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 106, state: Released, virtual_keycode: Some(Right), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }) }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: Focused(true) }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 1640.0, y: -46.0 }, modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }, is_synthetic: true } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }, is_synthetic: true } }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 984097880 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2511, tv_nsec: 987333588 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: true, logo: false } }) }
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged { modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } }, is_synthetic: false } }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared
[2019-12-18 09:44] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2512, tv_nsec: 44214893 }, requested_resume: None })
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } }) }
[2019-12-18 09:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: ModifiersChanged { modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-12-18 09:44] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(81788930))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }, is_synthetic: false } }
[2019-12-18 09:44] [INFO] glutin event: EventsCleared

...

[2019-12-18 09:44] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-13442.log"
```

</details>

**Comment by kchibisov** [comment] 2019-12-22 17:01
>I have no problem with Alacritty 0.3.3

We've added a lot of default binging for combined modifers, so now you're getting them, however you shouldn't get any of them, since your wm should idk, capture them (I'm not vary familiar with X11, but I'd expect that).

The most interesting part here is that you're saying that you use `Ctrl + Shift + Right`, `Ctrl + Shift + Left`, however I don't see this events in `alacritty --print-events`, the event I see is `Ctrl + Alt + Right`, so this C/D are commit from it.

Do you have some keyboard configuration/remapping, etc?

**Comment by Hugal31** [comment] 2020-01-06 10:58
I have nothing but the default shortcuts on XFCE4, I even removed a few (Ctrl+Alt+ Numbers).

I did a bisection, and the faulty commit seems to be 1cfb0740bc530da3162292bbf682a234240f26a3.

I could not reproduce the error with 0.4.0, I assume I miss-used cargo install (I did not use --locked then). So the problem is probably coming from the last version of winit.

**Comment by kchibisov** [comment] 2020-01-06 11:01
@Hugal31 Your original report was from v0.3.3, so you're saying that your issue was on v0.3.3, then now you don't have it on v0.4.0, but after v0.4.0 we reintroduced the problem to you, right?

**Comment by Hugal31** [comment] 2020-01-06 11:06
I had no issue with v0.3.3. However I had problem with 0.4.0, that I cannot reproduce now, I am sorry. I assume I miss-used `cargo install` (which does not use the Cargo.lock by default) back then.
I cannot find a better explanation :(

However I can now reproduce the bug on from commit 1cfb074.
I looked at [the changelog of winit](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md), and it seems the version 0.20.0-alpha6 had a bug, so it might come from here.

**Comment by kchibisov** [comment] 2020-01-06 11:21
>I had no issue with v0.3.3. However I had problem with 0.4.0, that I cannot reproduce now, 

Oh, sorry.

@Hugal31 we're not using alpha6, we're using a git commit after alpha6, without the bug you're talking about, so everything should work. It's strange since alpha6 didn't introduce anything to X11 which can relate to your problem. The only thing that could explain is that your WM is forwarding something to alacritty.(Like I see in your print events).

**Comment by kchibisov** [comment] 2020-01-06 11:27
You can't repro with v0.3.3 likely because v0.3.3 didn't have bindings for `Ctrl+Shift+Right` and `Ctrl+Shift+Left` at all, but now since v0.4.0 we have plenty of them in alacritty.

**Comment by chrisduerr** [comment] 2020-01-06 13:57
Generally your WM shouldn't even forward keys that it already captures itself, so I'm not sure how a winit regression could have caused issues here.

**Comment by trofi** [comment] 2020-01-12 23:11
I started receiving workspace switch keys on `xmonad` as well. I'm using `Ctrl-F<N>` to switch workspaces.

`v0.4.0` worked for me while `v0.4.1` started injecting keys like `^[[17;5~` into all alacritty terminals but not `xterm` for comparison. Is there an easy way to check if `xterm` (or an equivalent) also sees these events but swallows them?

Currenlty I'm working it around by injecting empty strings:

```
  # collides with xmonad's desktop switch
  #- { key: F1,       mods: Control, chars: "\x1b[1;5P"                       }
  #- { key: F2,       mods: Control, chars: "\x1b[1;5Q"                       }
  #- { key: F3,       mods: Control, chars: "\x1b[1;5R"                       }
  #...
  - { key: F1,       mods: Control, chars: ""                                }
  - { key: F2,       mods: Control, chars: ""                                }
  - { key: F3,       mods: Control, chars: ""                                }
  ...
```

I've bisected `alacritty` down 1cfb0740bc530da3162292bbf682a234240f26a3  commit:

```
$ git bisect bad
1cfb0740bc530da3162292bbf682a234240f26a3 is the first bad commit
commit 1cfb0740bc530da3162292bbf682a234240f26a3
Author: Christian Duerr <contact@christianduerr.com>
Date:   Sun Jan 5 01:00:50 2020 +0000

    Bump winit to 0.20.0 Alpha 6

    Fixes #3070.
    Fixes #2893.
    Fixes #2877.
    Fixes #2829.
    Fixes #2767.
    Fixes #2271.

 CHANGELOG.md                     |   5 +
 Cargo.lock                       | 167 ++++++++++++++++---------------
 Cargo.toml                       |   1 +
 alacritty/Cargo.toml             |   2 +-
 alacritty/src/config/bindings.rs | 209 ++++++++++++++++-----------------------
 alacritty/src/event.rs           |  24 ++---
 alacritty/src/input.rs           | 136 ++++++++++++-------------
 alacritty/src/url.rs             |   2 +-
 8 files changed, 261 insertions(+), 285 deletions(-)
```

Could it be that `winit` (or some dependency) can somehow bypass `WM` and listens to raw events?

**Comment by kchibisov** [comment] 2020-01-12 23:29
@trofi Could you please provide us with `alacritty --config-file /dev/null --print-events > out.txt` from the **bad** commit you've mentioned and from the one before it? Please, try to do exactly the same things on your system during both repro and send both logs as txt files here.

You should ~do the following:
- run `alacritty --config-file /dev/null --print-events > out.txt`
- focus it if it's not focused
- focus some workspace with your hotkey that pastes some chars in alacritty
- focus back to workspace with alacritty
- close it with system hotkey

**Comment by chrisduerr** [comment] 2020-01-12 23:31
I've just noticed that it looks like `is_synthetic` is always true when a key combination like this is pressed. So it might be possible that it's recommended to ignore events with `is_synthetic` set to true.

@Osspial can you maybe give some recommendations on handling of synthetic events? Should these usually be ignored?

**Comment by trofi** [comment] 2020-01-12 23:47
> @trofi Could you please provide us with `alacritty --config-file /dev/null --print-events > out.txt` from the **bad** commit you've mentioned and from the one before it? Please, try to do exactly the same things on your system during both repro and send both logs as txt files here.
> 
> You should ~do the following:
>     * run `alacritty --config-file /dev/null --print-events > out.txt`
>     * focus it if it's not focused
>     * focus some workspace with your hotkey that pastes some chars in alacritty
>     * focus back to workspace with alacritty
>     * close it with system hotkey

Done the following:

```
$ git checkout 1cfb0740bc530da3162292bbf682a234240f26a3 && cargo build && target/debug/alacritty --config-file /dev/null --print-events > first-bad-1cfb0740bc530da3162292bbf682a234240f26a3.txt
# Ctrl-F7, Ctrl-F6, observed garbage, Win4-Shift-C (close)

$ git checkout 1cfb0740bc530da3162292bbf682a234240f26a3^ && cargo build && target/debug/alacritty --config-file /dev/null --print-events > last-good-1cfb0740bc530da3162292bbf682a234240f26a3^.txt
# Ctrl-F7, Ctrl-F6, observed no garbage, Win4-Shift-C (close)
```

Attached both files:
- [first-bad-1cfb0740bc530da3162292bbf682a234240f26a3.txt](https://github.com/alacritty/alacritty/files/4051767/first-bad-1cfb0740bc530da3162292bbf682a234240f26a3.txt)
- [last-good-1cfb0740bc530da3162292bbf682a234240f26a3^.txt](https://github.com/alacritty/alacritty/files/4051768/last-good-1cfb0740bc530da3162292bbf682a234240f26a3.txt)

**Comment by kchibisov** [comment] 2020-01-12 23:56
@trofi I'm a bit sorry, right now. It turned out that using `--config-file /dev/null` could break event logging for whatever reason, so your logs are bit strange. (I've just rechecked it on my system). Could you do the following but with some empty file. Like `touch empty.txt` and then `alacritty --print-events --config-file empty.txt`?

**Comment by trofi** [comment] 2020-01-13 00:00
Sure. With `--config-file empty.txt` amendment:
-  [last-good-1cfb0740bc530da3162292bbf682a234240f26a3^.txt](https://github.com/alacritty/alacritty/files/4051779/last-good-1cfb0740bc530da3162292bbf682a234240f26a3.txt)
- [first-bad-1cfb0740bc530da3162292bbf682a234240f26a3.txt](https://github.com/alacritty/alacritty/files/4051780/first-bad-1cfb0740bc530da3162292bbf682a234240f26a3.txt)

**Comment by trofi** [comment] 2020-01-13 00:26
Reading https://docs.rs/winit/0.20.0/winit/event/enum.WindowEvent.html it looks like `is_synthetic` might be relevant:

```
is_synthetic: bool

If true, the event was generated synthetically by winit in one of the following circumstances:
    Synthetic key press events are generated for all keys pressed when a window gains focus. Likewise, synthetic key release events are generated for all keys pressed when a window goes out of focus. Currently, this is only functional on X11 and Windows

Otherwise, this value is always false.
```

In my case when I switch to workspace with active `alacritty` I still hold `Ctrl-F6` buttons and that event gets delivered as synthetic. I seem to get only a key when I switch to `alacritty` (`Ctrl-F6`), but no when I switch away from it (`Ctrl-F7`). Even though both events seem to be delivered:

```
$ cat first-bad-1cfb0740bc530da3162292bbf682a234240f26a3.txt  | egrep 'F[67]'

[2020-01-12 23:58] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 65, state: Pressed, virtual_keycode: Some(F7), modifiers: CTRL }) }
[2020-01-12 23:58] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 65, state: Released, virtual_keycode: Some(F7), modifiers: CTRL }, is_synthetic: true } }
[2020-01-12 23:58] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 65, state: Released, virtual_keycode: Some(F7), modifiers: CTRL }, is_synthetic: true } }
[2020-01-12 23:58] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 65, state: Released, virtual_keycode: Some(F7), modifiers: CTRL }) }

[2020-01-12 23:58] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 64, state: Pressed, virtual_keycode: Some(F6), modifiers: CTRL }) }
[2020-01-12 23:58] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 64, state: Pressed, virtual_keycode: Some(F6), modifiers: CTRL }, is_synthetic: true } }
[2020-01-12 23:58] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 64, state: Released, virtual_keycode: Some(F6), modifiers: CTRL }) }
```

Cloud it be that `alacritty` gets confused by currently pressed buttons when currently pressed buttons change between synthetic-only events?

**Comment by kchibisov** [comment] 2020-01-13 00:26
Ok, it turned out that we forgot about "new winit feature", which sends synthetic events in some cases, which leads to the behavior you see on this issue. So we're likely should just ignore them, however I we should wait on this comment to be replied https://github.com/alacritty/alacritty/issues/3109#issuecomment-573470189 .

It's not about combination though, it's all events which could be kind of related to your window, but not direclty...

**Comment by kchibisov** [comment] 2020-01-13 00:30
@trofi yeah, it's related. I think it's safe for alacritty to just ignore them entirey, but we'd agreed on IRC that hearing from winit folks before taking action is better here.

**Comment by Depado** [comment] 2020-01-13 15:57
I have been facing the same issue with Gnome Shell.
Adding these to the config file worked but is still a quickfix if you're annoyed by that:

```yaml
key_bindings:
  - { key: Up, mods: Control|Alt, action: None }
  - { key: Down, mods: Control|Alt, action: None }
```
(For `Ctrl`+`Alt`+`Up`|`Down`, customize according to your needs)

**Comment by chrisduerr** [comment] 2020-01-13 17:46
Could someone verify that https://github.com/alacritty/alacritty/pull/3204 resolves this issue?

**Comment by trofi** [comment] 2020-01-13 20:15
#3204 fixes the problem for me.

**Comment by Hugal31** [comment] 2020-01-14 08:14
#3204 fixes the problem for me too.

**Closed** 2020-01-14 16:01 UTC
Labels: A - needs repro, P - high, S - keybindings

**Comment by dvergeylen** [comment] 2020-01-15 08:58
Late in the game but I also confirm https://github.com/alacritty/alacritty/commit/c1664b348d97d6ab1a1a6956e1823ca70e64351c fixes the problem (Linux Debian 10, X11).

Thanks ! 😎

**Comment by ninjin** [comment] 2020-04-24 15:19
I am still seeing this on v0.4.2 on NixOS using their unstable channel as stable has v0.4.1. Initially I thought it was an issue with them packaging the wrong version, but it [looks legitimate](https://github.com/NixOS/nixpkgs/commit/45f53ccd8bc02282cc0db03bb271143c2d826d45). I am running i3 and the issue shows up when I switch focus left (gives a “D”) and right (gives a “C”) using alt+left and alt+right.

**Comment by chrisduerr** [comment] 2020-04-24 15:38
@ninjin You can verify your Alacritty version using `alacritty --version` and you should make sure that it can be reproduced with an empty config file. I'd be very surprised if this could be reproduced with an empty config on 0.4.2.

**Comment by ninjin** [comment] 2020-04-25 00:57
@chrisduerr: Thank you for the “empty config file” poke as it allowed me to figure out the issue. It was a Nix-specific user error all along as I had `${pkgs.alacritty}` specified in my i3-config for the terminal when it should have been `${pkgs.unstable.alacritty}`. Thus I launched v0.4.1 using alt+enter, but got v0.4.2 using `alacritty --version` from my shell. Sadly, there is very little to learn from this mistake if you are not on NixOS.

As this is my first interaction with Alacritty community, allow me to express a huge thank you for an amazing piece of software. I have been wanting to retire urxvt for so long (about a decade I think) and now I am finally doing so in favour of Alacritty. Configuration is bliss, the code is accessible, etc. Sure, I think there is a ~100ms lag compared to urxvt when from when you lift the finger to when the cursor stops, but I am willing to take a very mild slowdown to save my sanity when it comes to font handling etc. Keep up the awesome work!
