### ISSUE TITLE
Input method compatiblility.

### ISSUE THREAD

**Issue by laishulu** [alacritty/alacritty#3562] opened 2020-04-05 17:47 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System
OS: macOS
Version: alacritty 0.4.1 (4d9253b)
### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
```
bash-3.2$ /Applications/Alacritty.app/Contents/MacOS/alacritty -vv
Created log file at "/var/folders/lb/0_7c63x53ws__f3b9yg87lzr0000gn/T/Alacritty-88523.log"
[2020-04-06 01:40] [INFO] Welcome to Alacritty
[2020-04-06 01:40] [INFO] Configuration loaded from "/Users/mao/.alacritty.yml"
[2020-04-06 01:40] [DEBUG] Estimated DPR: 2
[2020-04-06 01:40] [DEBUG] Estimated Cell Size: 16 x 40
[2020-04-06 01:40] [DEBUG] Estimated Dimensions: None
[2020-04-06 01:40] [INFO] Device pixel ratio: 2
[2020-04-06 01:40] [INFO] Initializing glyph cache...
[2020-04-06 01:40] [INFO] ... finished initializing glyph cache in 0.035841405s
[2020-04-06 01:40] [INFO] Cell Size: 16 x 40
[2020-04-06 01:40] [INFO] Padding: 0 x 0
[2020-04-06 01:40] [INFO] Width: 1600, Height: 1200
[2020-04-06 01:40] [INFO] PTY Dimensions: Line(30) x Column(100)
[2020-04-06 01:40] [INFO] Initialisation complete
[2020-04-06 01:40] [INFO] Font size changed to Size(32) with DPR of 2
[2020-04-06 01:40] [DEBUG] Term::resize dimensions unchanged
[2020-04-06 01:40] [INFO] Width: 1600, Height: 1200
[2020-04-06 01:40] [DEBUG] New num_cols is 168 and num_lines is 40
[2020-04-06 01:40] [INFO] Width: 2688, Height: 1634
```
Keyboard and bindings: `alacritty --print-events`
```
[2020-04-06 01:44] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140630269804768)), event: ReceivedCharacter('输') }
[2020-04-06 01:44] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140630269804768)), event: ReceivedCharacter('入') }
[2020-04-06 01:44] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140630269804768)), event: ReceivedCharacter('法') }
[2020-04-06 01:44] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140630269804768)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(LWin), modifiers: LOGO }, is_synthetic: false } }
[2020-04-06 01:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(DeviceId), event: ModifiersChanged(LOGO) }
[2020-04-06 01:44] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140630269804768)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Released, virtual_keycode: Some(LWin), modifiers: (empty) }, is_synthetic: false } }
[2020-04-06 01:44] [INFO] glutin event: DeviceEvent { device_id: DeviceId(DeviceId), event: ModifiersChanged((empty)) }
```

1. In iTerm2.app/Termnial.app, When input Chinese:
<img width="321" alt="图片" src="https://user-images.githubusercontent.com/1224321/78505399-d714df80-77a5-11ea-8bd7-ee2d701307da.png">
But in Alacritty, no infomation is shown in the terminal
<img width="323" alt="图片" src="https://user-images.githubusercontent.com/1224321/78505503-720db980-77a6-11ea-9985-096f8157cee8.png">

2. In iTerm2.app/Termnial.app, when I hit `Backspace`, then both in the termnial and the composite window, `a` is deleted.
<img width="269" alt="图片" src="https://user-images.githubusercontent.com/1224321/78505444-17745d80-77a6-11ea-9a2e-eb5639524062.png">
But in Alacritty, 
<img width="309" alt="图片" src="https://user-images.githubusercontent.com/1224321/78505558-dc265e80-77a6-11ea-88af-d750d2f0efa0.png">

**Comment by kchibisov** [comment] 2020-04-06 01:43
duplicate of #1606

**Closed by kchibisov** 2020-04-06 01:43 UTC
