### ISSUE TITLE
macOS: 0.4.1 breaks Alfred auto expansion snippets

### ISSUE THREAD

**Issue by brandoniffert** [alacritty/alacritty#3206] opened 2020-01-14 13:52 UTC
### System

OS: macOS 10.15.2
Alacritty Version: 0.4.1
Alfred Version: 4.0.7
Alacritty config: [alacritty.yml](https://github.com/brandoniffert/computer/blob/master/roles/dotfiles/files/.config/alacritty/alacritty.yml)

### Logs

[Alacritty-040.log](https://github.com/alacritty/alacritty/files/4059362/Alacritty-040.log)
[Alacritty-041.log](https://github.com/alacritty/alacritty/files/4059364/Alacritty-041.log)

There's a mac program called Alfred that has a feature for [auto expanding text snippets](https://www.alfredapp.com/help/features/snippets/) that has worked in all previous alacritty versions I've used but now breaks in 0.4.1.

I have a number of snippets setup, in the logs I'm using the snippet `;cl` to expand to `console.log()`.

In 0.4.0:
`;cl` expands to `console.log()`

In 0.4.1:
`;cl` expands to `v`

Alfred is closed source so I don't know exactly what it is doing but when it auto expands I believe it's 

1. Copying the snippet to the clipboard
2. Sending a series of simulated key presses to do a `CMD-v` paste
3. Repositioning the cursor via simulated key presses
4. Clearing the clipboard/restoring what was previously there

So it looks like it is trying to send the `CMD-v` key event but on 0.4.1 something is happening and it only registers the `v` and leaves that in the output.

I don't know if this is an alacritty or Alfred issue but auto expansion works in Terminal.app and iTerm on macOS.

**Comment by chrisduerr** [comment] 2020-01-14 16:02
Could you try the latest master? There have been some changes to key handling that might be relevant.

**Comment by brandoniffert** [comment] 2020-01-14 20:03
@chrisduerr Tried it on `alacritty 0.4.2-dev (c1664b3)` but it still has the same issue

**Comment by kchibisov** [comment] 2020-01-14 20:12
According to your logs the problem is in modifers handling, so I guess  it's a duplicate of https://github.com/alacritty/alacritty/issues/3188 . However it's strange that I don't see modifiers changed event at all, before your `Command + V`.

**Comment by kchibisov** [comment] 2020-01-14 20:35
Oh, actually, there's no losing focus events, so the new modifier tracking should be a bit more complex in winit. and it's likely a separate issue.

**Comment by chrisduerr** [comment] 2020-01-15 11:53
Reported upstream in https://github.com/rust-windowing/winit/issues/1396.

**Comment by mastertinner** [comment] 2020-01-16 12:56
Another implication this has, is that the [Alfred Clipboard History](https://www.alfredapp.com/help/features/clipboard/) isn't working anymore. When I paste something into Alacritty normally using Cmd+V, that works fine. However, when I try to paste something from the clipboard history, it simply pastes `v`.

I'm pretty sure this is related because it also worked before 0.4.1.

**Comment by pstadler** [comment] 2020-02-05 09:00
Not sure whether this is related, but ever since I upgraded to 0.4.1 on MacOS, there are occasions where Alacritty registers `Ctrl` as continuously being pressed after it has gained focus using `Ctrl+Arrow`. `xxd` reports `^L` when pressing `l`.

**Comment by kchibisov** [comment] 2020-02-05 11:57
@pstadler you're experiencing  #3188

Could some one try the following patch? maybe the upstream fix could also solve this issue.

```rust
diff --git a/Cargo.toml b/Cargo.toml
index 415ceb9..19d16e9 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -13,3 +13,4 @@ incremental = false

 [patch.crates-io]
 servo-freetype-sys = { path = "servo-freetype-proxy" }
+winit = { git = "https://github.com/murarth/winit", branch = "modifiers-changed-window-event" }
diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index bfadbae..1d10463 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -585,6 +585,9 @@ impl<N: Notify + OnResize> Processor<N> {
                             processor.ctx.terminal.dirty = true;
                         }
                     },
+                    ModifiersChanged(modifiers) => {
+                        processor.modifiers_input(modifiers);
+                    },
                     KeyboardInput { is_synthetic: true, .. }
                     | TouchpadPressure { .. }
                     | ScaleFactorChanged { .. }
@@ -598,12 +601,7 @@ impl<N: Notify + OnResize> Processor<N> {
                     | Moved(_) => (),
                 }
             },
-            GlutinEvent::DeviceEvent { event, .. } => {
-                use glutin::event::DeviceEvent::*;
-                if let ModifiersChanged(modifiers) = event {
-                    processor.modifiers_input(modifiers);
-                }
-            },
+            GlutinEvent::DeviceEvent { .. } => (),
             GlutinEvent::Suspended { .. }
             | GlutinEvent::NewEvents { .. }
             | GlutinEvent::MainEventsCleared
```

**Comment by toejough** [comment] 2020-03-11 13:49
heh.  I extended the "restore after" setting to max (0.9s) in Alfred->snippets->auto expansion options->tweaking.

This gives me 0.9s after using a snippet to manually hit <cmd-v> and get the contents I wanted.

I still have to go back and erase the "v", but it's the best workaround I've come up with.

**Comment by chrisduerr** [comment] 2020-03-11 17:05
Since there has been no response from the original author, I'm closing this as a duplicate of #3188. Please let me know if the applied patch does not fix this for you.

**Closed by chrisduerr** 2020-03-11 17:05 UTC
Labels: A - deps, C - waiting on author, H - macos, S - keybindings, S - winit/glutin
