### ISSUE TITLE
Increase/Decrease font size with Mouse Wheel

### ISSUE THREAD

**Issue by raphaelfournier** [alacritty/alacritty#5296] opened 2021-07-01 09:08 UTC
I would like to map the `IncreaseFontSize` and `DecreaseFontSize` actions to my mouse wheel up and down movements, with a Shift (or Ctrl) mod (so that the regular scrolling is also preserved). 

This works (obviously):

    mouse_bindings:
      - { mouse: Middle, mods: Shift, action: IncreaseFontSize }

I read in the config comments: "- Numeric identifier such as `5`". But this does not work:

    mouse_bindings:
      - { mouse: 5, mods: Shift, action: IncreaseFontSize }

By "does not work", I mean: in AwesomeWM, "mousewheel up" is bound to 4, and "mousewheel down" to 5. I tried with several other integers, to no avail. 

Is there a simple command to know which are the codes sent by the mouse wheel movements?

I tried with my current MX Master 3 mouse, but also with an old no name usb mouse.

### System
OS: Linux
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: X11, AwesomeWM

**Comment by chrisduerr** [comment] 2021-07-01 16:11
Binding to scrollwheel is not possible. I'm also not entirely sure how useful that is.

**Comment by chrisduerr** [comment] 2021-07-01 16:28
> However, I still wonder: what are the possibilities behind "- Numeric identifier such as 5" in the "mouse binding" section of the config file? What (integers) can we bind and how can we know what codes are sent by our mouse buttons?

It's for extra mouse buttons.

**Comment by chrisduerr** [comment] 2021-07-01 16:31
Just to be clear: I wouldn't be opposed to this in theory, it's just that scrolling is never sent to us as button presses and things like touchpads obviously behave a bit differently when it comes to this. So I believe that implementing this would probably get a bit messy trying to special-case this.

**Comment by nbiederbeck** [comment] 2021-08-05 10:20
Hey there, I will jump on this bandwagon because I think it fits my question and is quite recent.

I was looking for something similar (different fontsize presets) not for different monitors, but for screen sharing. I always increase the fontsize a bit for presentations.

There is a keybinding for `ResetFontSize`, what about introducing `SetFontSize n`? (without looking at the code) I would naively assume that those commands would/could do the same, and `Reset` is just `Set` with a default argument (the standard font size)

**Comment by josephtingiris** [comment] 2023-01-26 14:21
I have the same use case, using ctrl+scroll to increase/decrease font size for screen sharing.  konsole does it & would be great if alacritty could as well.  I'm still using X11, not Wayland.

**Comment by thomjiji** [comment] 2023-12-16 13:52
Hope to add this feature! Konsole has this, use Ctrl + mouse wheel to increase/decrease font size (it feels like zoom in and out, focus on specific part or output of terminal) and it feeling very smooth and free.

**Comment by danielfaust** [comment] 2024-01-26 18:15
Ctrl+scroll to increase/decrease font size is kind of a standard feature. Chrome, Firefox, Cygwin, Konsole, Kate, just to name a few.

**Comment by kchibisov** [comment] 2024-02-23 13:26
duplicate of #2512

**Closed by kchibisov** 2024-02-23 13:26 UTC
Labels: enhancement, S - input, S - keybindings
