### ISSUE TITLE
Vim cursor not changing running bash.exe from Windows

### ISSUE THREAD

**Issue by pmsanford** [alacritty/alacritty#1689] opened 2018-10-20 00:52 UTC
Which operating system does the issue occur on?
Windows

I'm running with the following in `alacritty.yml`:
```yaml
shell:
  program: "C:\\Windows\\sysnative\\bash.exe"
```
on the latest insiders build of Windows (Version 1809, OS Build 18262.1000). I have Ubuntu 18.04 installed as my WSL OS: `Linux <snip> 4.4.0-18262-Microsoft #1000-Microsoft Fri Oct 12 14:14:00 PS T 2018 x86_64 x86_64 x86_64 GNU/Linux`

My `~/.vimrc` contains:
```
 let &t_SI = "\<Esc>[6 q"
 let &t_SR = "\<Esc>[4 q"
 let &t_EI = "\<Esc>[0 q"
```

In the default Ubuntu console vim switches between beam and block during editing. In Alacritty (running in Windows), it does not. It remains a block cursor regardless.

Is this something that will be fixed with #1661? Or is there something I'm missing? Couldn't find anything directly on point while searching issues, but perhaps I couldn't find the right combination of terms.

**Comment by chrisduerr** [comment] 2018-10-20 00:58
This is a duplicate of https://github.com/jwilm/alacritty/issues/1676 and has already been fixed in https://github.com/jwilm/alacritty/pull/1678.

It should be fixed soon.

**Comment by pmsanford** [comment] 2018-10-20 01:29
@chrisduerr I just tried building locally from that PR branch and it doesn't seem to fix this issue, though I can now change `cursor_style` to `Beam` in alacritty.yml and it works where it didn't before. I still might be doing something wrong so I'll wait for the AppVeyor build and test there. Thanks for taking a look so quick!

**Comment by chrisduerr** [comment] 2018-10-20 01:37
@pmsanford Does running `echo -e "\e[6 q"` work?

**Comment by pmsanford** [comment] 2018-10-20 02:18
No, the cursor remains a block.

**Comment by chrisduerr** [comment] 2018-10-20 02:19
@zacps Can you confirm that this still doesn't work?

**Comment by zacps** [comment] 2018-10-20 19:59
Can reproduce.

**Comment by wezm** [comment] 2018-11-22 00:50
I am seeing similar behaviour in Neovim with Arch Linux (Xorg). Both are installed from the Arch package repos.

```
$ alacritty --version
alacritty 0.2.3

$ nvim --version
NVIM v0.3.1
```

Usually changing from normal mode to insert mode the cursor would change from block to beam and vice versa. This no longer happens in Alacritty but does work in other terminals (E.g. Tilix)

I tried downgrading to older versions of the alacritty package I had available:

* alacritty-0.2.1-1-x86_64.pkg.tar.xz (same broken cursor behaviour)
* alacritty-0.2.0-3-x86_64.pkg.tar.xz (cursor changes as expected)

**Comment by chrisduerr** [comment] 2018-11-22 07:21
@wezm Wait for the next neovim version release. It has already been fixed upstream.

**Comment by sheldond** [comment] 2018-12-10 18:23
I was seeing the same issue on MacOS, I was able to fix it by setting `TERM` to something other than `alacritty` inside my alacritty.yml (for example `xterm-256color`).

**Comment by pmsanford** [comment] 2018-12-10 20:18
@sheldond setting TERM in the alacritty conf doesn't have any effect in the configuration mentioned in this issue. Doing so sets the TERM environment variable in its Windows process, but then the terminal invokes bash.exe which starts a bash term in the Windows Subsystem for Linux. The environment variables from the Windows process are not propagated down into the bash shell. 

The TERM used in the bash shell doesn't have any effect on this issue.

**Comment by sheldond** [comment] 2018-12-10 21:05
@pmsanford okay! It sounds like two separate issues then, sorry to take the convo away from yours.

**Comment by pmsanford** [comment] 2019-01-03 18:50
The ConPTY backend from the [0.2.4-conpty prerelease](https://github.com/jwilm/alacritty/releases/tag/v0.2.4-conpty) fixes this issue for me! 🎉 

![moveback](https://user-images.githubusercontent.com/1696007/50655491-3f429900-0f45-11e9-90aa-f1fb8546835b.gif)

**Comment by pwnorbitals** [comment] 2020-10-09 08:48
Can we confirm this is fixed now ? If so, this issue can probably be closed :)

**Comment by kchibisov** [comment] 2020-10-09 09:24
I'd close it, since we can't do anything about Windows bugs anyway.

**Closed by kchibisov** 2020-10-09 09:24 UTC
Labels: B - bug, H - windows, W - WinPTY
