### ISSUE TITLE
Will not open under large resolution

### ISSUE THREAD

**Issue by vanor89** [alacritty/alacritty#2992] opened 2019-11-18 19:08 UTC
Which operating system does the issue occur on?
Lubuntu, X11 using i3 as a wm.
I just changed my monitor to a CRG90 and it seems its not liking it one bit. I thought you should know :)

**Comment by kchibisov** [comment] 2019-11-18 19:17
Could you provide more information about this? Does it crash or not? 
if it crashes what's the output? I'm using 4k screen without any issues on X11/Wayland.

**Comment by chrisduerr** [comment] 2019-11-18 19:18
Could you go into a bit more detail please? If it doesn't start, there's likely a crash dump in stderr, posting that would be very helpful.

Alacritty has been tested at far greater densities than what you'd get on that monitor with a readable font size, so it's unlikely that this would cause it to not start.

**Comment by vanor89** [comment] 2019-11-18 19:22
Well, it kinda opens  but it doesn't, it opens but you cant see anything in it, then after a bit it crashes with this error:
```
thread 'main' panicked at 'assertion failed: line < self.num_lines()', alacritty_terminal/src/grid/mod.rs:393:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
This is my xorg config:
```
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 440.26

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"

    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"

    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Samsung C49RG9x"
    HorizSync       190.0 - 190.0
    VertRefresh     48.0 - 120.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1070"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-5"
    Option         "metamodes" "5120x1440 +0+0; nvidia-auto-select +0+0"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```

**Comment by vanor89** [comment] 2019-11-18 19:24
@chrisduerr That's great news!!!

**Comment by chrisduerr** [comment] 2019-11-18 19:25
Could you provide the same output, but with `RUST_BACKTRACE=1` together with the output of `alacritty --version` to check which exact hash you're running? Sounds like you ran into one of our sanity checks, hopefully should be a simple fix.

**Comment by vanor89** [comment] 2019-11-18 19:25
`alacritty 0.3.3 (e0a2865)`

**Comment by chrisduerr** [comment] 2019-11-18 19:29
@vanor89 Do you have a rust toolchain installed? Getting the backtrace in a debug build on the latest master would be helpful.

**Comment by vanor89** [comment] 2019-11-18 19:30
I sure do, but I don't know how to do what you are suggesting though, I'm by no means a Rust user, just have rustup for building stuff when needed, can you please give me more instruction on how to do that? sorry about that

**Comment by chrisduerr** [comment] 2019-11-18 19:32
No worries, thanks for the cooperation.

Running `RUST_BACKTRACE=1 cargo run` after cloning should be enough, assuming that your rust version is at least `1.36.0` (you can check by running `cargo --version`). If your rust version isn't 1.36.0 or higher, you can update by running `rustup update`.

**Comment by vanor89** [comment] 2019-11-18 19:32
Oh durr, of course that's how. gotcha, its updating right now, will post asap

**Comment by vanor89** [comment] 2019-11-18 19:39
Got a couple warnings and an error!
```
warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:78:21
   |
78 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:78:21
   |
78 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

    Finished dev [unoptimized + debuginfo] target(s) in 1m 31s
     Running `target/debug/alacritty`
Alacritty encountered an unrecoverable error:

        Error creating GL context; Received multiple errors. Errors: `[OsError("eglCreateWindowSurface failed"), OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]`
```

**Comment by chrisduerr** [comment] 2019-11-18 19:42
@vanor89 Do you have vsync disabled in your driver? Which GPU + driver are you using?

**Comment by vanor89** [comment] 2019-11-18 19:50
I'm using `nvidia-driver-440` and judging from the result of glxgears, I have it enabled.
```
➜ glxgears                      
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
602 frames in 5.0 seconds = 120.288 FPS
599 frames in 5.0 seconds = 119.760 FPS
599 frames in 5.0 seconds = 119.761 FPS
598 frames in 5.0 seconds = 119.559 FPS
599 frames in 5.0 seconds = 119.772 FPS
600 frames in 5.0 seconds = 119.964 FPS
600 frames in 5.0 seconds = 119.958 FPS
600 frames in 5.0 seconds = 119.966 FPS
600 frames in 5.0 seconds = 119.933 FPS
600 frames in 5.0 seconds = 119.996 FPS
600 frames in 5.0 seconds = 119.965 FPS
600 frames in 5.0 seconds = 119.963 FPS
600 frames in 5.0 seconds = 119.959 FPS
600 frames in 5.0 seconds = 119.957 FPS
600 frames in 5.0 seconds = 119.980 FPS
```

**Comment by chrisduerr** [comment] 2019-11-18 19:51
Anything like gsync or other driver configuration enabled? This is the first time I've seen the error `Couldn't setup vsync: expected interval '1' but got '0'`.

**Comment by vanor89** [comment] 2019-11-18 19:56
Nope, should they be enabled?

**Comment by chrisduerr** [comment] 2019-11-18 19:57
I mean it's definitely worth a shot to enable it, but generally it should be disabled.

If you're running i3 on X11 and not sway, it shouldn't be a problem either to run nvidia proprietary drivers.

Which GPU are you using?

**Comment by kchibisov** [comment] 2019-11-18 19:57
@vanor89 Could you try running without any Xorg configuration?

**Comment by vanor89** [comment] 2019-11-18 20:00
@kchibisov how can I do that?
@chrisduerr, GTX 1070 Strix, I forgot to mention, it runs with no issue in lower resolutions, if I swap to *any* lower resolution, alacritty runs with no issue.

**Comment by kchibisov** [comment] 2019-11-18 20:01
@vanor89 just temporary remove all `.conf` files from `/etc/X11/` iirc.

**Comment by vanor89** [comment] 2019-11-18 20:05
Yeah it runs fine, I had to relog b/c I dont know how to restart it but it opened in a lower resolution, and in that resolution I can run alacritty just fine, if I toggle to the higher resolution it continues to fail

**Comment by chrisduerr** [comment] 2019-11-18 20:08
> if I toggle to the higher resolution it continues to fail

How are you toggling it? Are you enabling everything again?

Could you try to change *just* the resolution, using `xrandr`? It's important to note that this issue is different from the original problem.

**Comment by vanor89** [comment] 2019-11-18 20:09
Well I was opening the nvidia settings and changing only the there, not using xrandr, let me try that

**Comment by chrisduerr** [comment] 2019-11-18 20:11
Also, just to clarify, when you change *just* the resolution, you get the `vsync` error, not the initial error, right?

**Comment by vanor89** [comment] 2019-11-18 21:06
sry guys I have work to do right now I'll update you guys as soon as possible

**Comment by chrisduerr** [comment] 2019-11-18 21:11
> sry guys I have work to do right now I'll update you guys as soon as possible

No worries, thanks for all the quick feedback. Just let us know if you've got more time to provide additional information. There's usually people available on #alacritty on freenode too if you want more immediate discussions.

**Comment by kchibisov** [comment] 2020-01-16 06:03
I'll close this bug in favor of #3214, since the last one has more detailed information about the cause of a behavior we're seeing here.

**Closed by kchibisov** 2020-01-16 06:03 UTC
