### ISSUE TITLE
Cannot input japanese characters

### ISSUE THREAD

**Issue by gullevek** [alacritty/alacritty#1101] opened 2018-02-07 08:49 UTC
Which operating system does the issue occur on?

macOS 10.12.6

The Kana key to switch to japanese input is not registered, it only prints out a space. Same for the other key called Eiso.

Switching to japanese input manually via the menu bar does not work either

**Comment by francesca64** [comment] 2018-06-03 01:15
Does this still happen on the latest version of Alacritty?

**Comment by Fandekasp** [comment] 2018-07-18 01:14
@francesca64 happens for me on Arch Linux and alacritty-git 0.1.0.794.g96b3d73-1

**Comment by azah** [comment] 2018-09-06 19:36
I get the same issue on Arch Linux with trying to switch to Hangul input. Also running Arch with the latest alacritty compiled from source.

**Comment by crocket** [comment] 2018-10-01 23:54
I use fcitx on Gentoo Linux. I don't have this issue.

![2018-10-01_mon_23 53 52](https://user-images.githubusercontent.com/748856/46321863-cb7cb180-c620-11e8-848e-502607906088.png)

**Comment by Fandekasp** [comment] 2018-10-06 04:12
I was really looking forward to using alacritty, but no japanese input is a deal-breaker. Uninstalling it now, but would love to stay in touch with Alacritty's roadmap for the time when it'll be supported and I can jump onboard @jwilm

**Comment by h-michael** [comment] 2018-10-06 05:03
I use Alacritty on Arch linux with fcitx and macOS 10.13.6.
I don't have this issue now.

**Comment by sawadashota** [comment] 2018-12-25 16:06
I use Alacritty on macOS 10.14.2.
I can type Japanese and see it as result, but I cannot see it before conversion.

screenshot of Alacritty
![image](https://user-images.githubusercontent.com/21254456/50424512-714e5e00-08a8-11e9-8492-de64ecb6e366.png)

screenshot of iTerm
![image](https://user-images.githubusercontent.com/21254456/50424592-f0906180-08a9-11e9-834c-544d9dcb6f02.png)

**Comment by Spirarel** [comment] 2019-01-16 00:44
I'm having the same problem as sawadashota. Same OS as well

**Comment by forestsource** [comment] 2019-03-20 02:42
I have same problem.
Alacritty: 0.2.9, OSX 10.14.3, Japanese input(Google input).

**Comment by MatsLanGoH** [comment] 2019-04-25 23:14
Can confirm the same problem - Japanese text is only rendered after completing conversion inside the IME window.
I've only begun learning Rust, but would like to help figuring out a solution if possible.

**Comment by tyru** [comment] 2019-08-11 19:37
I can't input any characters, but Kana key works so I can switch to japanese input method but I cannot input any japanese characters (typing `aaaaaaaaa<Enter>`. enter should insert preediting string to application textarea).

![Screencast 2019-08-12 04 32 55](https://user-images.githubusercontent.com/48169/62838654-4fc8a800-bcba-11e9-9478-9599b66fc373.gif)


## Enviroinment

* Japanese input method which is installed by default
  * some screenshots in macOS here appear using [Google Input Method](https://www.google.co.jp/ime/) such as @sawadashota's comment but I'm default input method user (I don't know if this is specific problem to default input method though)
* alacritty 0.3.3 (`brew cask ls --versions alacritty`)
* macOS 10.14.6

ref. https://github.com/jwilm/alacritty/issues/1606#issuecomment-520253469

**Comment by AdrienLemaire** [comment] 2020-01-08 09:37
Finally found a solution to input japanese in Alacritty within wayland with ibus+mozc:

```console
$ env WINIT_UNIX_BACKEND=x11 alacritty
```

[related issue](https://github.com/swaywm/sway/issues/4841).
Hence my problem isn't with alacritty or sway, but with mozc not supporting wayland.

**Comment by kchibisov** [comment] 2020-01-08 11:05
FWIW @AdrienLemaire your issue is tracked there https://github.com/jwilm/alacritty/issues/2734

**Comment by pickfire** [comment] 2020-05-19 15:02
Is this still an issue japanese input with fcitx seemed to work for me on arch linux on alacritty 0.4.2. I also tested with chinese input and it worked fine too.

![2020-05-19-225603_1366x768_scrot](https://user-images.githubusercontent.com/4687791/82342826-abcc1400-9a24-11ea-8578-628ff5803511.png)

**Comment by kchibisov** [comment] 2020-05-19 15:03
Yeah, it's an issue, as you can the label is on macOS, however you're on X11 + linux, which should work.

**Comment by gandalf3** [comment] 2020-06-25 23:52
For me "in-place input" isn't working in Linux/X11/ibus either, though it works in termite, as described by crocket above: https://github.com/alacritty/alacritty/issues/1101#issuecomment-426101444. The characters show up in a separate window created by the IME and only appear in alacritty once you confirm in the IME. Not the worst issue, but it'd be nice to see support for in-place editing.

**Comment by garasubo** [comment] 2020-06-26 05:55
"in-place input" won't work since glutin library itself doesn't send pre-edit string information to the application.
There is a tracking issue for it in winit: https://github.com/rust-windowing/winit/issues/1497

**Comment by garasubo** [comment] 2020-06-26 06:01
#1613 may be the better place to discuss "in-place input" problem?

**Comment by sonarypt** [comment] 2021-05-15 07:41
Well, I also have this issue, with fcitx, unicode input. Alacritty does not allow fcitx input?

**Comment by crocket** [comment] 2021-05-15 12:56
Alacritty allows fcitx with x11 backend.

**Comment by komi1230** [comment] 2021-08-11 00:42
This issue has been resolved in https://github.com/rust-windowing/winit/pull/1979.
Wait for a moment to release new version of [Winit](https://github.com/rust-windowing/winit) and [Glutin](https://github.com/rust-windowing/glutin).

**Comment by fgsch** [comment] 2021-12-06 13:45
This is great! Just tried master with Japanese and works as expected 🎉

**Comment by crocket** [comment] 2021-12-06 14:37
How can I make fcitx work in alacritty wayland backend?

**Comment by fgsch** [comment] 2022-01-14 12:01
I just tested `0.10.0-rc4 (6549303)` and is no longer working :(

**Comment by fgsch** [comment] 2022-01-14 12:04
It looks like the change that fixed this issue was reverted in winit (https://github.com/rust-windowing/winit/commit/6b250a74f8dd5343784538c5bc66a9b5a55000a7).

**Comment by komi1230** [comment] 2022-01-14 12:10
That change was just a hacky way to fix make Japanese input work fine. But it was decided to add some new API to work IME fine in all languages.

I added another PR in https://github.com/rust-windowing/winit/pull/2147 for this issue.

Sorry for convenience and wait for a while.

**Comment by fgsch** [comment] 2022-01-14 13:28
@komi1230 No worries. Thank you for your on this. Hopefully we will have proper IME support soon!

**Comment by chrisduerr** [comment] 2022-01-15 03:38
Thanks for your work @komi1230. Hopefully this can be properly resolved with the release after 0.10.0. For 0.10.0 the primary focus of course is not introducing any **new** regressions, so we'll have to wait until a proper fix is available.

**Comment by fgsch** [comment] 2022-07-19 09:37
Hi. Is there anything else that needs to be done here now that https://github.com/rust-windowing/winit/pull/2147 was merged?

**Comment by kchibisov** [comment] 2022-07-19 09:47
A new winit release.

**Comment by adwinying** [comment] 2022-08-05 15:40
Seems like winit released a new version [couple days ago](https://github.com/rust-windowing/winit/releases), could we expect an update with the new winit release anytime soon? 🤞

**Comment by adwinying** [comment] 2022-10-13 06:53
This issue seems to be resolved [in the latest release](https://github.com/alacritty/alacritty/releases/tag/v0.11.0)!


https://user-images.githubusercontent.com/6265936/195523278-9c4a1860-a8d1-4080-bc29-ef676c37920f.mov

**Closed** 2022-10-14 01:08 UTC
Labels: H - macos
