### ISSUE TITLE
Decorations : none "Stays on command"

### ISSUE THREAD

**Issue by Abb1x** [alacritty/alacritty#3944] opened 2020-07-10 15:22 UTC
There seem to be an issue , when I set `decorations: none` and I run a command like `ls` here's what happen : [https://imgur.com/a/mqsScQC](https://imgur.com/a/mqsScQC) the cursor stays on the line until I press a key
### System

OS: Linux
Version: `0.4.1`
Linux/BSD: GNOME(tried on awesomeWM too)

### Logs

Crashes: none
Font/Terminal size: `Fira Code`
Keyboard and bindings: `none`

**Comment by chrisduerr** [comment] 2020-07-10 15:31
How is that related to `decorations: none`? Does it not happen when you have decorations enabled? That doesn't make a lot of sense to me.

Can you try if starting a selection also updates the cursor?

**Comment by Abb1x** [comment] 2020-07-10 16:56
> How is that related to `decorations: none`? Does it not happen when you have decorations enabled? That doesn't make a lot of sense to me.
> 
> Can you try if starting a selection also updates the cursor?
> 
> Also are you running Wayland or X11?

I'm on X11 and when I enable Decorations it works

**Comment by chrisduerr** [comment] 2020-07-10 17:16
That sounds extremely strange. What about other ways to force a redraw like starting a selection?

**Comment by Abb1x** [comment] 2020-07-11 15:21
> That sounds extremely strange. What about other ways to force a redraw like starting a selection?

same thing

**Comment by chrisduerr** [comment] 2020-07-11 19:45
Sounds like a duplicate of #824 then, though the connection to decorations seems strange to me.

Can you reliably reproduce this with every command? If so, which of the decoration options cause this issue for you, just the decorations one?

**Closed** 2020-07-16 17:45 UTC
Labels: A - needs repro
