### ISSUE TITLE
wont start on wayland gnome 3.38.1

### ISSUE THREAD

**Issue by RSWilli** [alacritty/alacritty#4294] opened 2020-10-07 09:31 UTC
When I try to start alacritty from the gnome favorites, nothing happens.

I startet alacritty from terminal and I get the following error message:

```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    10895 abort (core dumped)  alacritty
```

### System

OS: arch linux
Version: alacritty 0.5.0 (a6681e3a)
Linux/BSD: Gnome 3.38.1 on Wayland

### Logs

Crashes: 
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    10895 abort (core dumped)  alacritty
```
Font/Terminal size: `alacritty -vv` no output, same error as above
Keyboard and bindings: `alacritty --print-events` no output, same error as above

**Comment by kchibisov** [comment] 2020-10-07 09:36
duplicate of  #4206

**Closed by kchibisov** 2020-10-07 09:36 UTC
