### ISSUE TITLE
High CPU usage on intensive output

### ISSUE THREAD

**Issue by halturin** [alacritty/alacritty#4528] opened 2020-12-06 19:32 UTC
Im using `rsync --info=progress2` and this command produces intensive output to show the progress like..

```819,739,727,773  48%  214.57MB/s    1:00:43 (xfr#4052060, to-chk=4298036/8350105)```

CPU usage during this process around 80% (inside tmux). URxvt/gnome-terminal - are cold displaying the same tmux session.

### System

OS: Linux (NixOS)
Version: 0.6.0
Linux/BSD: X11/Gnome 3.38.1

### Logs
```

[2020-12-06 20:24:36.475846433] [INFO ] [alacritty] Welcome to Alacritty
Created log file at "/tmp/Alacritty-28665.log"
[2020-12-06 20:24:36.475904034] [INFO ] [alacritty] Configuration files loaded from:
[2020-12-06 20:24:36.475910184] [INFO ] [alacritty]   "/home/taras/.config/alacritty/alacritty.yml"
[2020-12-06 20:24:36.483988330] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2020-12-06 20:24:36.484411843] [DEBUG] [alacritty] Estimated DPR: 1
[2020-12-06 20:24:36.484421393] [DEBUG] [alacritty] Estimated window size: None
[2020-12-06 20:24:36.484424603] [DEBUG] [alacritty] Estimated cell size: 7 x 18
[2020-12-06 20:24:36.619192989] [INFO ] [alacritty] Device pixel ratio: 1
[2020-12-06 20:24:36.622400772] [INFO ] [alacritty] Initializing glyph cache...
[2020-12-06 20:24:36.623795522] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2020-12-06 20:24:36.625333043] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2020-12-06 20:24:36.626907034] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2020-12-06 20:24:36.628531455] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2020-12-06 20:24:36.634027454] [INFO ] [alacritty] ... finished initializing glyph cache in 0.011613362s
[2020-12-06 20:24:36.634058794] [INFO ] [alacritty] Cell size: 7 x 18
[2020-12-06 20:24:36.634065064] [INFO ] [alacritty] Padding: 15 x 15
[2020-12-06 20:24:36.634068274] [INFO ] [alacritty] Width: 800, Height: 600
[2020-12-06 20:24:36.650952433] [INFO ] [alacritty] PTY dimensions: Line(31) x Column(110)
[2020-12-06 20:24:36.654235186] [INFO ] [alacritty] Initialisation complete
[2020-12-06 20:24:36.654555038] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[2020-12-06 20:24:36.654581958] [INFO ] [alacritty] Padding: 15 x 15
[2020-12-06 20:24:36.654587988] [INFO ] [alacritty] Width: 800, Height: 600
```

**Comment by chrisduerr** [comment] 2020-12-06 19:43
I don't see the problem? Are you saying you don't want Alacritty to use CPU when it has to do a lot of processing, but rather limit its resource usage in favor of slowing down?

If so, I'm not sure why you're using Alacritty?

**Comment by halturin** [comment] 2020-12-06 19:49
> If so, I'm not sure why you're using Alacritty?

is this the way of reacting to the bug report? :) I just wanted to let you know that it consumes much higher resources doing the same job compared to other terminals. if it was intended behavior... just close this report then.

PS: the description says "GPU-accelerated terminal emulator", so why it consumes such an amount of CPU?

**Comment by kchibisov** [comment] 2020-12-06 19:59
I can't say much about your issue, but I'll give you an example of something similar

There're a lot of factors here, which could affect the CPU usage, for example vte terminals use 70% of cpu usage when running `yes`, however `yes` itself only uses 50% of the CPU, meaning that it's being throttled on writing to the pty, since `yes` is just a loop that writes. However when I run `yes` in alacritty, alacritty uses 91% of CPU, however the `yes` CPU usage is 99-100%, so it just outputs faster, thus alacritty has more content to process per a unit of time compared to vte here.

**Comment by kchibisov** [comment] 2020-12-06 20:04
>PS: the description says "GPU-accelerated terminal emulator", so why it consumes such an amount of CPU?

Parsing isn't done on GPU, and you have a thread that just reads pty, parses and updates the state, so it can reach 100% of usage on its own if application outputs in a busy loop, since the parser is always running and rendering and input is done on other thread.

**Comment by halturin** [comment] 2020-12-06 20:17
So, why URxvt consumes nothing comparing to alacritty? not sure if it does less amount of work

![image](https://user-images.githubusercontent.com/118860/101291314-25342400-3808-11eb-9434-c108e0534947.png)

left: urxvt
right: alacritty

**Comment by kchibisov** [comment] 2020-12-06 20:22
How are you running alacritty? Are you running it with logging enabled?

**Comment by kchibisov** [comment] 2020-12-06 20:25
Also, please show threads and provide tree view.

**Comment by halturin** [comment] 2020-12-06 20:27
>How are you running alacritty? Are you running it with logging enabled?

do you mean whether I used any extra options to start? as you may notice on the screenshot, there are no options. just started using `alacritty`

**Comment by halturin** [comment] 2020-12-06 20:30
![image](https://user-images.githubusercontent.com/118860/101291588-3bdb7a80-380a-11eb-9222-0830d90375bf.png)

**Comment by kchibisov** [comment] 2020-12-06 20:35
Could you show thread names? And I think there should be more?

**Comment by halturin** [comment] 2020-12-06 20:42
left: urxvt
right: alacritty
![image](https://user-images.githubusercontent.com/118860/101291817-d9837980-380b-11eb-96ba-16721b16431b.png)

**Comment by kchibisov** [comment] 2020-12-06 20:48
If you pause rsync, etc will CPU usage lower? I think it shouldn't since pty reader thread does nothing afaics.

**Comment by halturin** [comment] 2020-12-06 20:54
running rsync
![image](https://user-images.githubusercontent.com/118860/101292055-6a0e8980-380d-11eb-9eb9-a5e8be57af16.png)
stopped
![image](https://user-images.githubusercontent.com/118860/101292070-77c40f00-380d-11eb-80d5-6f46961f99a5.png)

**Comment by kchibisov** [comment] 2020-12-06 20:57
Can you repro outside of tmux?

**Comment by halturin** [comment] 2020-12-06 21:00
outside (htop inside urxvt and tmux)
![image](https://user-images.githubusercontent.com/118860/101292208-67606400-380e-11eb-99f3-03484455d78e.png)

**Comment by halturin** [comment] 2020-12-06 21:04
both urxvt (consumes nothing)
![image](https://user-images.githubusercontent.com/118860/101292299-f79ea900-380e-11eb-87d9-27153162b6fb.png)

**Comment by kchibisov** [comment] 2020-12-06 21:06
If you run 'alacritty --config-file /dev/null' or if you run alacritty on Wayland does it consume the same amount of CPU usage?

**Comment by halturin** [comment] 2020-12-06 21:11
i dont have wayland.
The same behavior 
![image](https://user-images.githubusercontent.com/118860/101292470-eefaa280-380f-11eb-84f9-14b2bd28820c.png)

**Comment by kchibisov** [comment] 2020-12-06 21:16
Could you provide `alacritty --print-evets` output?

**Comment by halturin** [comment] 2020-12-06 21:21
[alac.zip](https://github.com/alacritty/alacritty/files/5649560/alac.zip)

**Comment by kchibisov** [comment] 2020-12-06 21:32
What GPU are you using? Also, what's the output of `glxinfo`?

**Comment by halturin** [comment] 2020-12-06 21:35
Kernel 5.8.18
NVIDIA Driver Version 455.38
[glxinfo.zip](https://github.com/alacritty/alacritty/files/5649581/glxinfo.zip)

**Comment by chrisduerr** [comment] 2020-12-06 21:36
How did you install Alacritty?

**Comment by kchibisov** [comment] 2020-12-06 21:41
Maybe vsync isn't working?

**Comment by chrisduerr** [comment] 2020-12-06 21:42
There's probably some way to overlay FPS on nvidia GPUs, that's probably a really good idea to look into.

**Comment by halturin** [comment] 2020-12-06 21:44
This is NixOS. To install it you just need to specify it in the configuration and the package manager install it automatically 
Here is a script of how it builds on the NixOS side https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/terminal-emulators/alacritty/default.nix

**Comment by kchibisov** [comment] 2020-12-11 00:28
Also, if you have an option to test nouveau, could you please do that? Since it really seems like the issue is either with X11 input stuff or driver.

**Comment by luc65r** [comment] 2020-12-20 16:33
I have the same problem: excessively high cpu usage on programs that write to alacritty a lot.
I'm also on NixOS, kernel 5.9.12, nvidia 455.45.01.
`__GL_SHOW_GRAPHICS_OSD=1 alacritty` with `cava` on it, I get 70% cpu core usage and around 120 fps.

**Comment by chrisduerr** [comment] 2020-12-20 18:40
@luc65r Well have you tested nouveau?

**Comment by luc65r** [comment] 2020-12-23 19:21
@chrisduerr I just tested with nouveau, and running cava uses way less cpu (around 10%).
However I can't get Mesa Vulkan overlay to work, so I have no idea how much fps I am getting.
I'm currently trying to package MangoHud.

**Comment by chrisduerr** [comment] 2020-12-23 19:36
> I can't get Mesa Vulkan overlay to work

Vulkan overlay? Why Vulkan?

I'm not sure if this works with `nouveau`, but mesa has a `GALLIUM_HUD=fps` setting to draw FPS.

**Comment by luc65r** [comment] 2020-12-23 20:13
> Vulkan overlay? Why Vulkan?

As `GALLIUM_HUD` didn't work, I thought alacritty used Vulkan.
`GALLIUM_HUD` doesn't work with glxgears either, I could have checked that earlier.

**Comment by luc65r** [comment] 2020-12-23 21:25
I just go MangoHud to work, it works on glxgears but it doesn't show up on alacritty and it doesn't output anything, exactly like when testing on xterm...

**Comment by luc65r** [comment] 2020-12-23 21:43
I managed to make it work with `MANGOHUD_DLSYM=1`, I get around 120 fps and 10% cpu core usage on cava.
I guess the excessive cpu usage is specific to nvidia proprietary drivers.

**Comment by chrisduerr** [comment] 2020-12-23 23:09
Alacritty uses OpenGL, not Vulkan. `GALLIUM_HUD` is unfortunately not supported by all mesa devices, I'm not entirely sure why or how that works, I just know it works for me.

> I guess the excessive cpu usage is specific to nvidia proprietary drivers.

This seems like the most likely explanation, it would be interesting to see if there's maybe something messed up in the nvidia configuration. This seems like the proprietary nvidia driver might not be blocking on vsync for example. But that's not really something that should be fixed inside of Alacritty.

**Closed by chrisduerr** 2020-12-23 23:09 UTC
Labels: A - needs repro, C - waiting on author

**Comment by hasufell** [comment] 2020-12-24 01:29
Ok, so it seems no one REALLY knows what's going on and the ticket was closed regardless, telling a majority of linux users that they just have bad luck?

**Comment by chrisduerr** [comment] 2020-12-24 02:11
If you get a hand on nvidia's proprietary drivers so someone can take a look at them, please do let me know.

**Comment by halturin** [comment] 2021-01-07 21:56
nvidia 455.45.01
kernel 5.10.3
problem is still here. even MANGOHUD_DLSYM=1 doesn't help. 

but as i see you have fixed the problem by closing this ticket. you guys just awesome :)

**Comment by chrisduerr** [comment] 2021-01-08 06:37
There's nothing to be fixed in Alacritty, since the issue is with the Nvidia drivers.

**Comment by halturin** [comment] 2021-01-08 10:06
can't you please elaborate on your conclusion? not for me, but for the others who experienced the same problem

I'm going back to the gnome-terminal. they finally fixed the annoying bug and now it just works without extra CPU usage. 

I wish you guys to change your approach to work with your users. I believe it's the worst way to react like "If so, I'm not sure why you're using Alacritty?" on a bug report and finally you closed the ticket without a solution just blaming Nvidia driver without having any prooves of it.

**Comment by hasufell** [comment] 2021-01-11 00:49
I wasn't aware gnome-terminal is gpu accelerated? https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/89

If you know of good alacritty terminal alternatives for nvidia users, please share, since the devs clearly don't want (or can't) support it.

**Comment by halturin** [comment] 2021-01-11 12:24
honestly, I don't care whether it uses GPU if it does its job without huge CPU consuming even on intensive output. the reason why I switched to alacritty was an annoying bug which finally has been fixed so now I can switch back. especially after getting "amazing support" from the alacritty developers, which was literally a joke I'm happy to get back on gnome-terminal.

**Comment by halturin** [comment] 2021-01-11 12:47
Just found yet another report with the same problem https://github.com/alacritty/alacritty/issues/4060

and this ticket was tagged 'not a bug' and closed. just can't stop :rofl:

**Comment by jpmorris** [comment] 2023-06-18 14:33
I'm out too.  Clearly these guys cant code and just blame others--they HAVE to be teenagers based on the way they are acting.
