### ISSUE TITLE
Problem with binding mouse buttons

### ISSUE THREAD

**Issue by aleksanderkrauze** [alacritty/alacritty#6197] opened 2022-07-10 21:20 UTC
Hi. I can't seem to bind my scroll up/down button on my mouse. I want to be able to change font size by scrolling whilst holding ctrl modifier (like you can do for instance in web browsers). On X11 these are mouse buttons 4 and 5. I have put following code in my configuration, but it doesn't work. I tried to look at output of --print-events, but I can't see that it is even registered there.

```
mouse_bindings:
  - { mouse: 4, mods: Control, action: IncreaseFontSize }
  - { mouse: 5, mods: Control, action: DecreaseFontSize }
```

Am I doing something wrong or what I am trying to do is impossible? Will be grateful for any help.

**Comment by kchibisov** [comment] 2022-07-10 22:03
Those won't bind mouse wheel. Those buttons are not X11 buttons, but the rest of mouse buttons, in the particular case those should be next/prev(side mouse buttons).

Duplicate of #5296.

**Closed by kchibisov** 2022-07-10 22:03 UTC
