### ISSUE TITLE
Cannot type curly braces in neovim when running it from Alacritty on MacOS

### ISSUE THREAD

**Issue by av-maslov** [alacritty/alacritty#4283] opened 2020-10-03 14:13 UTC
Hello,

Can you help me please to fix this issue?

I can type curly braces in Alacritty itself using Opt Shift 8/9, but when I enter neovim I can't type curly braces (but I can type all other braces). 

When doing the same from iTerm2 - it works in neovim.

**Comment by chrisduerr** [comment] 2020-10-03 16:44
Which Alacritty version and what keyboard layout are you using? Also have you tried just plain vim and neovim without configuration?

**Comment by al31415** [comment] 2020-10-03 18:31
I am using Finnish keyboard.
I open two terminals - iTerm2 and Alacritty.
Then I run `nvim -u NONE` in both terminals.
And after that I use `Option Shift 8` to type curly brace.
It works in iTerm, but not in Alacritty.
In Alacritty it is not clear what happens when I press this key combination - it seems it just exits edit mode.

I also tried to follow instructions from here

- https://github.com/alacritty/alacritty/issues/93

I added this to config file

```
key-bindings:
  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
  - { key: K,        mods: Alt,     chars: "\x1bk"                       }
  - { key: H,        mods: Alt,     chars: "\x1bh"                       }
  - { key: L,        mods: Alt,     chars: "\x1bl"                       }
  - { key: N,        mods: Alt,     chars: "\x1bb"                       }
  - { key: Y,        mods: Alt,     chars: "\x1bf"                       }
  - { key: Key6,     mods: Control, chars: "\x1e"                        }
  - { key: F,  mods: Alt,           chars: "\x1bf"                       }
  - { key: B,  mods: Alt,           chars: "\x1bb"                       }
 #  - { key: V,        mods: Command, action: Paste                        }
 #  - { key: Period,   mods: Command, action: Paste                        }
 #  - { key: C,        mods: Command, action: Copy                         }
 #  - { key: I,        mods: Command, action: Copy                         }
 #  - { key: Q,        mods: Command, action: Quit                         }
 #  - { key: X,        mods: Command, action: Quit                         }
 #  - { key: Equals,        mods: Command, action: IncreaseFontSize        }
 #  - { key: RBracket,      mods: Command, action: IncreaseFontSize        }
 #  - { key: Minus,         mods: Command, action: DecreaseFontSize        }
 #  - { key: Apostrophe,    mods: Command, action: DecreaseFontSize        }

```

I am not sure what exactly it does, I tried to comment/uncomment parts of it.
But it didn't help.


PS: How can I check Alacritty version?

Thanks for reply!

**Comment by chrisduerr** [comment] 2020-10-03 18:49
Does it work when you run Alacritty without any configuration file? Both inside/outside?

Also `key-bindings` is incorrect, it has to be `key_bindings`.

**Comment by al31415** [comment] 2020-10-03 18:57
Now I commented out everything in config file - it doesn't help.

- Both inside/outside?

Sorry, what do you mean?

**Comment by chrisduerr** [comment] 2020-10-03 19:23
I mean that if you have the default configuration file, it should behave the same way both inside and outside of vim.

**Comment by al31415** [comment] 2020-10-04 05:36
No, it is different - outside vim it works, and it doesn't work inside of vim.

**Comment by chrisduerr** [comment] 2020-10-04 15:19
Does it work inside of the vim terminal?

**Comment by al31415** [comment] 2020-10-05 04:11
Got it. Yes, it works inside vim terminal.

**Comment by chrisduerr** [comment] 2020-10-05 08:27
Does it work outside of the terminal once you've run `echo -e "\e[?1h\e[?25h"`?

**Comment by al31415** [comment] 2020-10-06 08:47
Hi,

I have just re-installed , I used versiosn v0.5.0 - didn't help.

> Does it work outside of the terminal once you've run echo -e "\e[?1h\e[?25h"?

I open Alacritty, and run this command. Then I run vim. Is it correct? - If yes, then - no, didn't help.

**Comment by chrisduerr** [comment] 2020-10-06 12:02
> I open Alacritty, and run this command. Then I run vim. Is it correct? - If yes, then - no, didn't help.

No, that's not correct. You're supposed to try inputting your curly braces outside of vim after running this command.

**Comment by al31415** [comment] 2020-10-07 08:46
> Does it work outside of the terminal once you've run echo -e "\e[?1h\e[?25h"?
> You're supposed to try inputting your curly braces outside of vim after running this command.

Sorry, I am confused. 
Now I tried to run this command from vim, like `:command` - but it shows error `E121: Undefined variable : e` and then from terminal launched from vim - nothing changed.

I also noticed that I can type curly braces in Vim when I run search command `/{}`.

Now I don't know myself if it is Alacritty issue, or it is Neovim issue.

**Comment by chrisduerr** [comment] 2020-10-07 14:34
Have you tried `TERM=xterm-256color vim`?

**Comment by nixpulvis** [comment] 2020-10-07 15:48
Strange. I can reproduce this issue with all Shift + Option keys in the number row when set to Finnish on macOS. However in both iTerm and Terminal.app the Shift + Option + 4 combination doesn't correctly render the ¢ glyph. So while it seems Alacritty is not doing something right, so is `vim` perhaps.

**Comment by nixpulvis** [comment] 2020-10-07 15:49
@chrisduerr I can confirm this is still happening with `TERM=xterm-256color`.

**Comment by chrisduerr** [comment] 2020-10-07 22:08
But it works for you outside of vim?

**Comment by nixpulvis** [comment] 2020-10-12 22:11
@chrisduerr correct, everything seems fine outside of `vim` to me.

**Comment by desirelabs** [comment] 2020-11-12 08:54
Hello, I'm having the exact same issue. This prevents me from switching. Moreover, the issue also happens in terminal mode.

**Comment by voxbono** [comment] 2020-11-18 22:42
I can report the same thing. I’m on a Norwegian keyboard (I think it’s the same as the finish layout). Everything works fine in iTerm, bu not in Alacritty. I’m really sad because it made Vim noticeably faster. But without my most important code characters, it’s useless.

**Comment by voxbono** [comment] 2020-11-19 12:18
Here is some additional information that I just found out. This is outside of Vim.
If I click Alt-Shift-8, nothing happens. If I click Alt-8 and then Alt-Shift-8, a starting curly brace pops up. If I click Alt-8 two times, an opening square bracket comes up. If I click Alt-Shift-9, nothing comes up, but if I click Alt-8 and then Alt-Shift-9, a closing curly brace comes up. So it's like Alt-8 behaves like a leader key, to then be able to do my brackets and curly braces.

**Comment by desirelabs** [comment] 2021-02-10 13:20
The issue still exists on Alacritty 0.7.1.
As an additional information to what @voxbono said, on macos 11, curly braces are obtained by : 
* maintaining`Maj` + press `{`, then release`Maj` + press `{`
Brackets are obtained the same way but : 
* maintaining`Maj` + press `[` two times.

**Comment by sam-tries-programming** [comment] 2021-02-21 16:01
The issue still exists on Alacritty 0.7.2 as well.
I'm using a German keyboard and the combination of alt + 8 dosen't do anything.
Also, I'm experiencing the same problems trying to typ [ as well.

**Comment by tfpereira** [comment] 2021-03-03 08:46
> Have you tried setting alt_send_esc: false ?
> Fixed the issue for me !

This worked for me perfectly, I had the exact same issue with a portuguese layout (also couldn't enter visual mode on tmux which now works as well)

**Comment by voxbono** [comment] 2021-03-04 10:29
> Have you tried setting alt_send_esc: false ?
> Fixed the issue for me !

Yup works for me as well! Awesome!

**Comment by SaschaHeyer** [comment] 2021-03-14 09:36
any updates on that topic?

**Comment by R0LA1mRifcF8yAkk** [comment] 2021-03-23 11:08
> any updates on that topic?

@SaschaHeyer try `alt_send_esc: false`. fixed the issue for me as well

**Comment by zingi** [comment] 2021-03-26 05:34
I had the same problem on a **german mac** keyboard.
I could not write any alt+key _(like { } | )_. First I tried #62. 
But what it finally solved: 
* setting `alt_send_esc: false` **AND**
* removing any key bindings from #62

**Comment by R0LA1mRifcF8yAkk** [comment] 2021-03-26 10:55
Maybe @av-maslov can confirm that what @zingi said above fixes the problem? Then this issue can be closed.

**Comment by chrisduerr** [comment] 2021-03-26 11:17
This is precisely what `alt_send_esc` is for.

**Closed by chrisduerr** 2021-03-26 11:17 UTC
