### ISSUE TITLE
Neo keyboard layout on Linux does not work in Vi selection mode

### ISSUE THREAD

**Issue by schoettl** [alacritty/alacritty#6623] opened 2023-01-15 16:10 UTC
On my Linux with the standard Neo keyboard layout, all keys work **except in `mode: Vi`**.

E.g. in Vi select mode, `?` and `$` don't work because they are typed using the Mod3 key (the special Neo modifier key). Keys typed with Mod4 modifier also don't work, e.g. arrow keys.

In normal mode or for search input, all keys work.

### System

OS: NixOS
Version: 0.11
Linux/BSD: X11 and Xmonad

### Logs

Here, I pressed `$` in Vi mode. Looks like the key *is* detected but nothing happens. I'd expect the cursor to jump to end of line.

Keyboard and bindings: `alacritty --print-events`

```
[11.073106789s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 25794, tv_nsec: 747873620 }, requested_resume: None })
[11.073452803s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 43, state: Pressed, virtual_keycode: None, modifiers: (empty) }) }
[11.073844497s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(96468994)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 43, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
[11.074075353s] [INFO ] [alacritty] glutin event: MainEventsCleared
[11.074230355s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[11.225243600s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 25801, tv_nsec: 921947059 }, requested_resume: None })
[11.225732443s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: None, modifiers: (empty) }) }
[11.225948728s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(96468994)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
[11.226062336s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(96468994)), event: ReceivedCharacter('$') }
[11.226139075s] [INFO ] [alacritty] glutin event: MainEventsCleared
[11.226192084s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[11.359735397s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 25802, tv_nsec: 73813455 }, requested_resume: None })
[11.360140819s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 45, state: Released, virtual_keycode: None, modifiers: (empty) }) }
[11.360307995s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(96468994)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 45, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
[11.360394433s] [INFO ] [alacritty] glutin event: MainEventsCleared
[11.360491544s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[11.470525678s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 25802, tv_nsec: 208105071 }, requested_resume: None })
[11.471033125s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 43, state: Released, virtual_keycode: None, modifiers: (empty) }) }
[11.471305169s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(96468994)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 43, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
[11.471547368s] [INFO ] [alacritty] glutin event: MainEventsCleared
[11.471757521s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
```

**Comment by kchibisov** [comment] 2023-01-15 17:20
The layout is unrelated. From what I remember some buttons are not mapped on X11 due to 'reasons'. You could bind by `scancode` for now.

**Comment by kchibisov** [comment] 2023-01-15 17:24
Duplicate of #3460

**Closed by kchibisov** 2023-01-15 17:24 UTC

**Comment by schoettl** [comment] 2023-01-15 23:36
Thank you @kchibisov. Binding to scancodes is a good work-around, so I can at least add my most frequently used keys.

For reference:

```
sudo showkey --scancode  # to get scancode
```

```yml
key_bindings:
  - { key: 35,         mods: None, mode: Vi|~Search,  action: SearchBackward                       } # ?
  - { key: 20,         mods: None, mode: Vi|~Search,  action: First                                } # ^
  - { key: 45,         mods: None, mode: Vi|~Search,  action: Last                                 } # $
  - { key: 16,         mods: None, mode: Vi,          action: ScrollPageUp                         }
  - { key: 20,         mods: None, mode: Vi,          action: ScrollPageDown                       }
```
