### ISSUE TITLE
`startup_mode: Maximized` stopped working recent GNOME Wayland

### ISSUE THREAD

**Issue by gdetrez** [alacritty/alacritty#6184] opened 2022-07-05 19:48 UTC
This stopped working after upgrading from Fedora 35 to 36.  From the log it seems that Alacritty starts in 800x600, switch size to 2560x1408 (which is about the size of my screen) but then goes back to 800x600.

The Alacritty version in Fedora 36 is 0.10.1 whereas in 35 it was 0.9.0. But I tried to run Alacritty from source using the v0.9.0 tag, and I see the same issue, i.e. even 0.9.0 doesn't start maximized on Fedora 36 either. So maybe something else changed in Fedora 36 that interfers with Alacritty?  Anything I can do to investigate further?

### System

OS: Linux (Fedora 36)
Version: 0.10.1
Linux/BSD: Grome on Wayland

### Logs

Font/Terminal size: `alacritty -vv`
```
[0.000007730s] [INFO ] [alacritty] Welcome to Alacritty
[0.000120725s] [INFO ] [alacritty] Version 0.10.1
[0.000163071s] [INFO ] [alacritty] Running on Wayland
[0.001266332s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/perso/.config/alacritty/alacritty.yml"
[0.020854944s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.029044235s] [DEBUG] [alacritty] Estimated DPR: 1
[0.029061996s] [DEBUG] [alacritty] Estimated window size: None
[0.029077550s] [DEBUG] [alacritty] Estimated cell size: 7 x 18
[0.078014143s] [INFO ] [alacritty] Device pixel ratio: 1
[0.089214196s] [INFO ] [alacritty] Initializing glyph cache...
[0.090528233s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.092259742s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.094021178s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.095948744s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.129382298s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.040139218s
[0.129417483s] [INFO ] [alacritty] Cell size: 7 x 18
[0.129423263s] [INFO ] [alacritty] Padding: 1 x 3
[0.129427064s] [INFO ] [alacritty] Width: 800, Height: 600
[0.129817390s] [INFO ] [alacritty] PTY dimensions: 33 x 114
[0.132035798s] [INFO ] [alacritty] Initialisation complete
[0.132228100s] [DEBUG] [alacritty_terminal] New num_cols is 365 and num_lines is 78
[0.135490062s] [INFO ] [alacritty] Padding: 2 x 2
[0.135513191s] [INFO ] [alacritty] Width: 2560, Height: 1408
[0.151158877s] [DEBUG] [alacritty_terminal] New num_cols is 114 and num_lines is 33
[0.152942982s] [INFO ] [alacritty] Padding: 1 x 3
[0.152999777s] [INFO ] [alacritty] Width: 800, Height: 600
```

**Comment by gdetrez** [comment] 2022-07-05 20:29
@kchibisov yes, `Fullscreen` seems to work correctly.

**Comment by georgegach** [comment] 2022-07-11 11:58
Experiencing the same issue. Identical config with `startup_mode: Maximized` fails on Fedora 36 (Gnome 42.2 / Wayland) but works fine on Ubuntu 22.04 (Gnome 42.2 / X11). 

Tried building from source on Fedora to match Ubuntu's `0.11.0-dev` version provided by `apt` (since Fedora's rpm package is at `0.10.1`) but the issue remained. 

Tested on: 
- [alacritty.yml](https://gist.github.com/georgegach/4f2b0491b34384c90e73849f4fd62620)
- Fedora: `alacritty 0.11.0-dev (e09ff0b4)` and `alacritty 0.10.1 from dnf rust-alacritty-0.10.1-1.fc36.src.rpm`
- Ubuntu: `alacritty 0.11.0-dev from apt 0.10.1+1-20220711T020155~jammy-e09ff0b4`

**Comment by georgegach** [comment] 2022-07-11 12:17
Figured out the issue: it is `decorations` for me.
- `decorations: full`: `Maximized` works just fine, with no error messages in `-vv`. 
- `decorations: none`: title and borders removed as intended, but `Maximized` doesn't work anymore and throws 3x `Unsupported modifier` messages with `-vv` as well.

```log
❯ alacritty -vv
Created log file at "/tmp/Alacritty-16660.log"
[0.000004619s] [INFO ] [alacritty] Welcome to Alacritty
[0.000071889s] [INFO ] [alacritty] Version 0.10.1
[0.000111218s] [INFO ] [alacritty] Running on Wayland
[0.000477423s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/george/.config/alacritty/alacritty.yml"
[0.014718763s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.015997819s] [DEBUG] [alacritty] Estimated DPR: 1
[0.016016211s] [DEBUG] [alacritty] Estimated window size: None
[0.016023536s] [DEBUG] [alacritty] Estimated cell size: 10 x 21
Unsupported modifier, resource creation failed.
XXX: resource creation failed
[0.062517551s] [INFO ] [alacritty] Device pixel ratio: 1
[0.073474220s] [INFO ] [alacritty] Initializing glyph cache...
[0.075126122s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.077642256s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.080195598s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.082498795s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.100759284s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.027241395s
[0.100827943s] [INFO ] [alacritty] Cell size: 10 x 21
[0.100838357s] [INFO ] [alacritty] Padding: 30 x 37
[0.100846429s] [INFO ] [alacritty] Width: 800, Height: 600
[0.101465164s] [INFO ] [alacritty] PTY dimensions: 25 x 74
[0.104648228s] [INFO ] [alacritty] Initialisation complete
[0.104843190s] [DEBUG] [alacritty_terminal] New num_cols is 186 and num_lines is 47
[0.109118097s] [INFO ] [alacritty] Padding: 30 x 30
[0.109166916s] [INFO ] [alacritty] Width: 1920, Height: 1048
[0.125072947s] [DEBUG] [alacritty_terminal] New num_cols is 74 and num_lines is 25
[0.125250553s] [INFO ] [alacritty] Padding: 30 x 37
[0.125283312s] [INFO ] [alacritty] Width: 800, Height: 600
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
[1.199675257s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1',],['~',],] at line 949

```

**Comment by georgegach** [comment] 2022-07-11 12:39
The culprit in my case was `decorations: none`. Certainly a Wayland issue. 

Running Alacritty with `WAYLAND_DISPLAY= alacritty` in XWayland temporarily fixes the issue for me. 


```
WAYLAND_DISPLAY= alacritty -o "window.decorations=none" -o "window.startup_mode=Maximized" 
```

**Comment by gnuruzzi** [comment] 2022-08-03 07:54
I'm experiencing the same issue.
```
window:
  startup_mode: Maximized
  decorations: none
```
Having the line `decorations: none` makes the `startup_mode: Maximized` stop working.

**Comment by LeoMeinel** [comment] 2022-08-24 00:15
Same on Arch Linux with Alacritty Version: 0.10.1-2.
See https://github.com/LeoMeinel/dot-files/issues/4 for more details and https://github.com/LeoMeinel/dot-files/commit/0687c5772545dce289e85de87188021c8c25b945 for a way to fix this (that shouldn't be necessary)

**Comment by hexchain** [comment] 2022-09-08 06:01
Not sure if this should be a separate issue, but in Plasma Wayland, Alacritty never started in maximized mode despite no `decorations` option. It looks like it somehow fails to resize, or the compositor refuses to do so.

Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Graphics Platform: Wayland

<details>
<summary><code>alacritty -vv</code></summary>

```
Created log file at "/tmp/Alacritty-362573.log"
[0.000003353s] [INFO ] [alacritty] Welcome to Alacritty
[0.000047773s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000055316s] [INFO ] [alacritty] Running on Wayland
[0.000269875s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/hexchain/.config/alacritty/alacritty.yml"
[0.010618071s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.012440493s] [DEBUG] [alacritty] Estimated DPR: 1
[0.012452017s] [DEBUG] [alacritty] Estimated window size: None
[0.012457814s] [DEBUG] [alacritty] Estimated cell size: 8 x 18
[0.043553250s] [INFO ] [alacritty] Device pixel ratio: 1
[0.047582442s] [INFO ] [alacritty] Initializing glyph cache...
[0.051072652s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.054669933s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.058287677s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.061970097s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.069165775s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.021558051s
[0.069187077s] [INFO ] [alacritty] Cell size: 8 x 18
[0.069191478s] [INFO ] [alacritty] Padding: 0 x 3
[0.069194830s] [INFO ] [alacritty] Width: 800, Height: 600
[0.069486845s] [INFO ] [alacritty] PTY dimensions: 33 x 100
[0.072036056s] [INFO ] [alacritty] Initialisation complete
[0.094545792s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.098920638s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.102999628s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.107728161s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.108959010s] [INFO ] [alacritty] Font size changed to Size(20) with DPR of 2
[0.114154026s] [INFO ] [alacritty] Cell size: 16 x 36
[0.114188598s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.114209063s] [INFO ] [alacritty] Padding: 0 x 6
[0.114216256s] [INFO ] [alacritty] Width: 1600, Height: 1200
[7.989703185s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-362573.log"
```
</details>

**Comment by kchibisov** [comment] 2022-09-13 19:10
That's actually a disaster for us. Since it would mean that on wayland will have a special handling of that. The problem is that.

1. We create a Window
2. We run an event_loop and commit buffers via swap buffers. This will be even more interesting since it'll become on a different thread latter on.

And given that swap buffers and window handling is done by 2 different libraries and we have multiple threads/windows involved it means that we're better off not using the request at all.

I'm not even sure we can solve that for multithreaded apps reliably given that you must create event queues around for that in the current design.

It's always nice that protocols got adjusted over time due and compositors change behavior for a stable protocols in such ways. Since this code was working without issues for like years in multiple compositors and started to break only when realization came.

**Comment by zzag** [comment] 2022-09-13 20:18
@kchibisov While looking at the wayland debug log, I've also noticed that alacritty or its toolkit attaches a buffer of size 800x600 even though it has received a configure event with size 1920x1007

```
[1256223.590] xdg_toplevel@25.configure(1920, 1007, array[20])
...
[1256272.259]  -> xdg_surface@24.set_window_geometry(0, 0, 1920, 1007)
...
[1256275.277]  -> zwp_linux_dmabuf_v1@33.create_params(new id zwp_linux_buffer_params_v1@43)
[1256275.302]  -> zwp_linux_buffer_params_v1@43.add(fd 37, 0, 0, 3584, 33554432, 9878274)
[1256275.309]  -> zwp_linux_buffer_params_v1@43.add(fd 38, 1, 2293760, 1024, 33554432, 9878274)
[1256275.312]  -> zwp_linux_buffer_params_v1@43.create_immed(new id wl_buffer@44, 800, 600, 875713089, 0)
[1256275.315]  -> zwp_linux_buffer_params_v1@43.destroy()
```

This may be culprit too. However, because of that set_window_geometry without attached buffer, you can still have issues when running kwin_wayland. So, there seems to be two issues actually. :(

**Comment by kchibisov** [comment] 2022-09-13 20:28
I mean I understand the issue, I'm just saying that it can't be solved directly in alacritty right now, it'll require changing like 2-3 libraries down the road for that. Think of it like I need to change Qt(just example) to fix that in alacritty.

And some other problem that this "Qt" library is in the middle of updating their "libwayland" wrapper and in beta for "Qt-6" for like 6 month already.

That Qt reference is an example, but you should get an understanding of why this can't be easily solved right now and takes some amount of time...

**Comment by henil** [comment] 2022-12-17 06:40
Having same issue on Arch linux. And from reading comments looks like its related to wayland.

Can title be changed to reflect that its not related to Fedora specifically but wayland, so its easier to find for other people.

Alacritty version: 0.11.0

**Comment by henil** [comment] 2022-12-18 16:33
i upgraded my system, not exactly sure what things got updated which caused this but now hack mentioned in https://github.com/LeoMeinel/dot-files/issues/4 now gives this error

> thread 'main' panicked at 'Failed to set the cursor: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.4/src/platform_impl/linux/x11/util/cursor.rs:126:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

and `startup_mode: Maximized` works as expected.

**Comment by StackOverflowExcept1on** [comment] 2023-02-25 11:25
I have same problem on Ubuntu 22.04.2 LTS
![image](https://user-images.githubusercontent.com/109800286/221354177-6745303b-d6f1-4bf1-9c92-4579e4f9ec7a.png)
```
Created log file at "/tmp/Alacritty-6983.log"
[0.000009080s] [INFO ] [alacritty] Welcome to Alacritty
[0.000131232s] [INFO ] [alacritty] Version 0.11.0
[0.000150997s] [INFO ] [alacritty] Running on Wayland
[0.000857929s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/.../.config/alacritty/alacritty.yml"
[0.001488734s] [DEBUG] [alacritty] Loading "monospace" font
[0.021488165s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.026938987s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.032314381s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.037402169s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.039530019s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.039543708s] [DEBUG] [alacritty] Estimated window size: None
[0.039549924s] [DEBUG] [alacritty] Estimated cell size: 10 x 19
[0.041058003s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.091720561s] [INFO ] [alacritty] Running on RENOIR (renoir, LLVM 15.0.6, DRM 3.47, 5.19.0-32-generic)
[0.091763374s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.096491759s] [INFO ] [alacritty] Display scale factor: 1
[0.096553917s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.106001329s] [INFO ] [alacritty] Cell size: 10 x 19
[0.106045888s] [INFO ] [alacritty] Padding: 0 x 0
[0.106051685s] [INFO ] [alacritty] Width: 800, Height: 600
[0.106630109s] [INFO ] [alacritty] PTY dimensions: 31 x 80
[0.108857413s] [INFO ] [alacritty] Initialisation complete
[0.109387018s] [DEBUG] [alacritty_terminal] New num_cols is 192 and num_lines is 50
[0.110646464s] [INFO ] [alacritty] Padding: 0 x 0
[0.110689486s] [INFO ] [alacritty] Width: 1920, Height: 956
[0.136064450s] [DEBUG] [alacritty_terminal] New num_cols is 192 and num_lines is 31
[0.136188907s] [INFO ] [alacritty] Padding: 0 x 0
[0.136198964s] [INFO ] [alacritty] Width: 1920, Height: 600
[0.629914892s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1'],['~'],] at line 963
[0.658908465s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Medium, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[4.209896239s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-6983.log"
```

**Comment by kchibisov** [comment] 2023-02-25 11:45
@StackOverflowExcept1on your issue is unrelated, alacritty just exits without issues for you, likely your shell program crashed.

**Comment by gdetrez** [comment] 2023-02-25 11:53
I just tried @StackOverflowExcept1on's workaround, and it seems to fix the `Maximized` issue for me :tada:

**Comment by StackOverflowExcept1on** [comment] 2023-02-25 11:57
@kchibisov I opened alacritty with `startup_mode: Maximized` option and manually closed it. Nothing crashed, but the logs show that the window size does not match my monitor: `[alacritty] Width: 1920, Height: 600`

**Comment by kchibisov** [comment] 2023-02-25 12:01
>I just tried @StackOverflowExcept1on's workaround, and it seems to fix the Maximized issue for me tada

That's because you're not running on wayland anymore, so it's not a workaround.

**Closed** 2023-07-11 02:22 UTC
Labels: B - bug, DS - Wayland
