### ISSUE TITLE
100% cpu consumption when cava is running

### ISSUE THREAD

**Issue by ibootstrapper** [alacritty/alacritty#6045] opened 2022-05-07 07:32 UTC
### System

OS: Linux
Version: 0.10.1
Linux/BSD: X11/leftwm

Running `cava` https://github.com/karlstav/cava causes alacritty to consume 100% cpu 

![ArcoLinux_2022-05-07_02-31-28](https://user-images.githubusercontent.com/1440852/167243967-acaeac27-abed-4e52-89d7-1bce0eec3723.png)

**Comment by chrisduerr** [comment] 2022-05-07 07:37
Duplicate of #4060.

**Closed by chrisduerr** 2022-05-07 07:37 UTC

**Comment by ibootstrapper** [comment] 2022-05-07 08:56
this should be reopened ... This is CLEARLY an Alacritty issue. Take a look at the bars, some of them SKIP some lines...This is not due to cava sending data `too fast`. 

my cava config file was reduced framerate to 30 cpu is high (about 80%) and lines are still being lost.

**Comment by chrisduerr** [comment] 2022-05-07 09:19
> this should be reopened ... This is CLEARLY an Alacritty issue. Take a look at the bars, some of them SKIP some lines...This is not due to cava sending data too fast.

So you're suggesting Alacritty is using 100% CPU because cava is… skipping some lines? What?

If you think there's an issue, run `perf` against it and report your findings.

**Comment by ibootstrapper** [comment] 2022-05-07 09:31
cava is not using 100% cpu...look at the above picture.

perf won't be able to replicate what you see via cava. Cava is repositioning the writes and i believe that is where the issue is rather then the rendering

**Comment by ibootstrapper** [comment] 2022-05-07 09:44
you can try and see with the simple command `tree /` and see the spikes to 100% . With all the respect to Alacritty, its now high graphics game and there is way too much cpu consumption compare to gpu given it is opengl based.

**Comment by kchibisov** [comment] 2022-05-07 15:23
Could you detail view of what is using CPU including threads and thread names. htop has config for all of that, also a tree view into process.

**Comment by ibootstrapper** [comment] 2022-05-07 16:19
Will work on it. Might take a few days as I'm sick

**Comment by ibootstrapper** [comment] 2022-05-07 17:48
![ArcoLinux_2022-05-07_12-47-24](https://user-images.githubusercontent.com/1440852/167265848-a8c2c59d-92f0-4542-a3f9-d7e2b322d56f.png)

here you go :) 

cava is configured for 30fps.

**Comment by ibootstrapper** [comment] 2022-05-07 17:54
a few more notes...

comparing to kitty as a reference in the picture below

1. Alacritty seems more "aggressive" but there are flickering and some bars missing lines
2. Kitty is more pleasant to look at (animation is smoother)

![a-v-k](https://user-images.githubusercontent.com/1440852/167266030-02e662f8-33a2-4075-9c88-b94bea96ca6e.png)

**Comment by kchibisov** [comment] 2022-05-07 18:48
Is it happening with default conifg? `alacritty --config-file /dev/null`?

I was afraid that it's software rendering or something like that.

I think the only option is to run `perf` and see where it's spending its time.

>Alacritty seems more "aggressive" but there are flickering and some bars missing lines. Flickering is quite bad...if i knew how to capture a video, I'll post it as well. its like a game flickering when low gfx card and v-sync turned off.

Applications should explicitly sync via escape sequences, we don't delay input.

**Comment by ibootstrapper** [comment] 2022-05-07 19:11
yes, it does happen with default config. 

i'm not too familiar with perf, if you can share a how-to i'll setup something.

**Comment by kchibisov** [comment] 2022-05-07 19:18
it's kind of simple, but you'd need unstripped binary.

`perf record -i alacritty --config-file /dev/null -e cava`
And then do `perf report` from the folder you've run it.

**Comment by ibootstrapper** [comment] 2022-05-07 19:24
thanks, 

here it is
![a](https://user-images.githubusercontent.com/1440852/167268919-7938a6ef-8af3-42c9-afe2-2a5c6a853806.png)

**Comment by ibootstrapper** [comment] 2022-05-07 19:28
what is vsdo? this is what i think can be optimized

**Comment by kchibisov** [comment] 2022-05-08 08:23
>what is vsdo?

That's a linux kernel call to get current time. might be nvidia asking for it? Also the stack clearly shows it's an nvidia issue, since most of the time we spent in their video driver, which doesn't happen with either amd or intel GPU.

**Comment by ibootstrapper** [comment] 2022-05-09 04:06
OK, that make sense. Thank you. 

What about the flickering issue? What can be the cause of that? Is it buffering or something?

**Comment by ibootstrapper** [comment] 2022-05-09 04:21
maybe opening a new issue for the flickering?

**Comment by chrisduerr** [comment] 2022-05-09 04:59
Cava doesn't use synchronized updates, making it so that Alacritty might draw in the middle of cava updates since it doesn't indicate frame changes. So you can request synchronized update support from cava if you want to fix that.
