### ISSUE TITLE
`alacritty -e tmux` segfaults on exit

### ISSUE THREAD

**Issue by oconnor663** [alacritty/alacritty#4721] opened 2021-01-19 15:58 UTC
OS: Arch Linux, Gnome desktop with default settings (Wayland)
Version: `alacritty 0.7.1 (a852eb85)`

The issue comes up when I do this:

```
$ alacritty -e tmux
zsh: segmentation fault (core dumped)  alacritty -e tmux
```

The terminal starts up and works just fine. However, when I Ctrl-D out of tmux and the terminal window closes, that's when the segfault appears (visible in a parent terminal). So maybe this is just a "cosmetic" segfault :)

I can repro the issue on master under gdb. Here's the full stacktrace of the segfault:

```
Thread 6 "smithay-clipboa" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe73fe640 (LWP 4935)]
0x00007ffff7fc07b0 in wl_list_insert () from /usr/lib/libwayland-client.so
(gdb) bt
#0  0x00007ffff7fc07b0 in wl_list_insert () from /usr/lib/libwayland-client.so
#1  0x00007ffff7fbd94b in wl_display_read_events () from /usr/lib/libwayland-client.so
#2  0x00007ffff7fbdecc in wl_display_dispatch_queue () from /usr/lib/libwayland-client.so
#3  0x00007ffff7fbe160 in wl_display_roundtrip_queue () from /usr/lib/libwayland-client.so
#4  0x0000555555aa035e in wayland_client::imp::event_queue::{{impl}}::sync_roundtrip::{{closure}}<closure-5> ()
    at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:85
#5  0x0000555555aa1ec6 in wayland_client::imp::event_queue::with_dispatch_meta::{{closure}}<core::result::Result<u32, std::io::error::Error>,closure-5,closure-0> ()
    at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:24
#6  0x0000555555a7257b in scoped_tls::ScopedKey<core::cell::RefCell<(&mut FnMut<(wayland_client::RawEvent, wayland_client::proxy::Main<wayland_client::anonymous_object::AnonymousObject>, wayland_commons::filter::DispatchData)>, wayland_commons::filter::DispatchData)>>::set<core::cell::RefCell<(&mut FnMut<(wayland_client::RawEvent, wayland_client::proxy::Main<wayland_client::anonymous_object::AnonymousObject>, wayland_commons::filter::DispatchData)>, wayland_commons::filter::DispatchData)>,closure-0,core::result::Result<u32, std::io::error::Error>> (
    self=0x5555566e0c38 <wayland_client::imp::event_queue::DISPATCH_METADATA>, t=0x7fffe73fc948, f=...)
    at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
#7  0x0000555555aa1be4 in wayland_client::imp::event_queue::with_dispatch_meta<core::result::Result<u32, std::io::error::Error>,closure-5,closure-0> (fb=..., data=..., f=...)
    at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:24
#8  0x0000555555aa016f in wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip<closure-5> (self=0x7fffd0000c40, data=..., fallback=...)
    at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:83
#9  0x0000555555a9f9a7 in wayland_client::event_queue::EventQueue::sync_roundtrip<smithay_clipboard::worker::dispatch_data::ClipboardDispatchData,closure-5> (self=0x7fffe73fcc68, 
    data=0x7fffe73fd3a8, fallback=...) at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/event_queue.rs:191
#10 0x0000555555aa5816 in smithay_clipboard::worker::worker_impl (display=..., request_rx=..., reply_tx=...)
    at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.6.2/src/worker/mod.rs:319
#11 0x0000555555aa3d3c in smithay_clipboard::worker::spawn::{{closure}} () at /home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.6.2/src/worker/mod.rs:44
#12 0x0000555555a6a7a2 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,()> (f=...)
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
#13 0x0000555555aa2b81 in std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,()> ()
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464
#14 0x0000555555a71ab1 in std::panic::{{impl}}::call_once<(),closure-0> (self=..., _args=())
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
#15 0x0000555555a783c9 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()> (data=0x7fffe73fda88)
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
#16 0x0000555555a7993d in __rust_try ()
#17 0x0000555555a782f4 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>> (f=...)
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
#18 0x0000555555a781b3 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (f=...)
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
#19 0x0000555555aa296d in std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,()> ()
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:463
#20 0x0000555555a97e3f in core::ops::function::FnOnce::call_once<closure-0,()> ()
    at /home/jacko/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
--Type <RET> for more, q to quit, c to continue without paging--
#21 0x00005555562e265a in alloc::boxed::{{impl}}::call_once<(),FnOnce<()>> () at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
#22 alloc::boxed::{{impl}}::call_once<(),alloc::boxed::Box<FnOnce<()>>> () at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
#23 std::sys::unix::thread::{{impl}}::new::thread_start () at library/std/src/sys/unix/thread.rs:87
#24 0x00007ffff7ae53e9 in start_thread () from /usr/lib/libpthread.so.0
#25 0x00007ffff7d4f293 in clone () from /usr/lib/libc.so.6
```

Let me know if there are any other commands you'd like to see the output of.

**Comment by chrisduerr** [comment] 2021-01-19 16:00
Duplicate of https://github.com/alacritty/alacritty/issues/4702.

**Closed by chrisduerr** 2021-01-19 16:00 UTC
