### ISSUE TITLE
Reload window decorations when config changes

### ISSUE THREAD

**Issue by brunolpsousa** [alacritty/alacritty#7295] opened 2023-10-14 15:23 UTC
When `decorations_theme_variant` is set to `None` Alacritty auto picks the system theme variant. But if the user changes the system theme from dark to light or vice versa and changes Alacritty's color scheme to match it (i.e. via a shell script), the new config will be reloaded correctly, but the window decorations will remain unchanged and the only alternative is to close and reopen Alacritty.

[alacritty_decoration.webm](https://github.com/alacritty/alacritty/assets/39863381/9293193f-9be9-47d9-a8d3-3727c31f9247)

### Steps

- Make sure `decorations_theme_variant` is set to `None`
- Use Wayland client side decorations
- Switch between light and dark themes (you can use `gsettings set org.gnome.desktop.interface color-scheme "default"` and `gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"`) and change anything in Alacritty config just to force reload

### Expected behavior

Alacritty checks if the system theme variant has changed and reloads the window decorations when reloading the config; or just reload the window decorations along with the rest of the configuration

### System

OS: Linux
Version: alacritty 0.12.3 (5efb0690)
Linux/BSD: GNOME 45 Wayland

**Comment by chrisduerr** [comment] 2023-10-15 00:25
Working as intended.

**Comment by kchibisov** [comment] 2023-10-15 00:30
We don't reload decorations at all so it should be fixed.

**Closed** 2023-10-15 01:37 UTC
