### ISSUE TITLE
Switching to an electron app and back + 'w' character quits Alacritty

### ISSUE THREAD

**Issue by kgrz** [alacritty/alacritty#3256] opened 2020-01-27 07:42 UTC
### System

OS: macOS
Version: alacritty 0.4.2-dev (4cc6421)

Steps to reproduce:

1. Open Alacritty.app
1. Switch to some other app, preferably a "heavy" one like a web browser or Slack or Spotify, and click around
1. Using the app switcher, hover over alacritty for a second, and start holding `w` key right after letting go of command key (which should activate alacritty, but not show the `w` characters being  typed). This should close the app.

I've tried out these steps multiple times, and it's *almost* consistent. The weird part is that this doesn't happen (at least reliably) when switching back from some applications. There doesn't seem to be a crash as such, and I noticed a  `UserEvent(ExitEvent)` getting logged before the event loop gets removed. This sounds like some upstream bug in windowing/event-management, but I thought I'd open it here first to rule out any edge cases in the app.

I'm not sure if this is relavant, but I've tried this with both Slack and Spotify, with hardware acceleration turned on and off without any difference in alacritty's behaviour.

Log generated when following the above steps: https://gist.github.com/239954c52d067d8eaecc28a2bd71d61d.

I'll put up a video if I can get the recording uploaded somewhere. The one I took is very rudimentary and didn't have any keycode printout, so I'm not sure how useful it'd be.

**Comment by kchibisov** [comment] 2020-01-27 10:36
duplicate of #3188

**Closed by kchibisov** 2020-01-27 10:36 UTC
