### ISSUE TITLE
Use system unicode width function

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#1295] opened 2018-05-05 15:37 UTC
There are a number of issues that seem caused by having mismatched unicode character width definitions. We use the Rust crate unicode-width which contains its own tables which may differ from system versions.

#1106 #696 #481 #975

**Comment by chrisduerr** [comment] 2018-05-05 15:48
https://github.com/jwilm/alacritty/pull/1049 might be related?

**Comment by aleyan** [comment] 2018-05-07 01:43
Could the issues be because folks are using Unicode 10 characters, but unicode-width crate is only updated to Unicode 9? There is a [PR](https://github.com/unicode-rs/unicode-width/pull/5) outstanding for this.

**Comment by ytang** [comment] 2018-05-31 19:46
Can we make the Unicode version a runtime option? I frequently ssh to a system that still uses Unicode 8 width, so I have to compile alacritty with dependency `unicode-width = "=0.1.3"` as a workaround.

**Comment by aleyan** [comment] 2018-07-28 03:52
I think ytang's comment highlight an important issue. System version of unicode may say one thing, but it is really up to the application to set the expectation of how widely printed its characters should be. I am sure many applications use some non-system library to determine width. More over, if you are connecting over ssh, remote application needs to target unicode width of the local system.

The only way I can see that working is terminal exposing the supported Unicode version via terminfo or something of the like and the application code knowing to look for it. Seems difficult; perhaps the best option is just support the latest Unicode release and hope application is updated or no existing characters have changed their widths.

**Comment by ytang** [comment] 2018-07-28 05:30
As a side note, [iTerm2](https://www.iterm2.com) has an option to [toggle the Unicode width](https://www.iterm2.com/documentation-preferences.html), which is pretty handy for this matter.

**Comment by textshell** [comment] 2019-03-11 21:42
There is currently a discussion how to solve unicode width in a cross terminal and remote login compatible way. See https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9 for details and thoughts from other terminal developers.

**Comment by chrisduerr** [comment] 2019-03-11 22:13
@textshell Thanks for the reference.

**Comment by yofriadi** [comment] 2019-09-07 13:23
So, after a year this issue still open, is there any blockers?
is there any option other than tmux for me to use out there that solve current issue?
thanks in advance.

**Comment by chrisduerr** [comment] 2019-09-07 13:45
> So, after a year this issue still open, is there any blockers?

If this is a high priority for you, we're always happy to try and provide mentoring instructions.

However, this is not a problem on a lot of systems so the priority is pretty low as far as I'm concerned. It's also not a good solution and it will not solve the problem in every case.

A good example for this not easily getting solved by using wcwidth is outlined in https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9.

**Comment by aiotter** [comment] 2020-07-21 08:47
I'm suffering from the problem on this issue for a long time using Alacritty.

As @ytang pointed out, iTerm2 solves the problem by an option to toggle the Unicode width.
Terminal.app on macOS has the same strategy: you can see `Unicode East Asian Ambiguous characters are wide` option in `Preferences -> Profiles -> Advanced`.

I know this problem is hard to solve by using `wcwidth`, so how about going to #1049 like those terminals?
This might not be a perfect solution, but done is better than perfect.
#1049 does not affect the environment unless you set `east_asian_fullwidth: true`, so those who is not suffered from this problem has no problem with the introduction of the PR.
When you find a good way to do with `wcwidth` you can revert the PR and go on it.

**Comment by chrisduerr** [comment] 2020-07-21 11:28
> I know this problem is hard to solve by using wcwidth

Why would it be? That's actually the easiest solution there is. Since that's what most applications use anyways.

> so how about going to #1049 like those terminals?

Because it doesn't really solve anything.

Ambiguous width is also very different than unicode version or other wide characters. That's a completely separate thing.

**Comment by aiotter** [comment] 2020-07-21 13:51
Hmm... it seems I misunderstood the [the issue you mentioned above](https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9).
If relying on the system `wcswidth` until terminal-wg make a standardized one (if they make) is good way to solve this problem, I will take a look on it and see if I can implement it when I have some time.

(I'm not sure I can though. I'm pretty new to rust and GUI applications. If any other developers can commit on this issue please contribute instead of me.)

**Comment by chrisduerr** [comment] 2023-06-12 20:45
Closing this issue because I don't think there's actually any interest in using the system unicode width function at the moment.

**Closed by chrisduerr** 2023-06-12 20:45 UTC
Labels: enhancement

**Comment by jacklsw** [comment] 2023-06-16 11:24
Which comment is the best solution/workaround for this issue? I scroll through the comments and still can't determine which is the solution/workaround.

**Comment by kchibisov** [comment] 2023-06-16 11:32
The issue is that all applications using their own width functions and a way to compute width of the glyphs. Most of the time it matches, but sometimes it's not, when e.g. the libc on your remote is very old, or particular implementation decided to do things a bit differently, using system width function won't solve anything once you ssh into other system, because suddenly it's not working anymore.

Unless there's an escape sequence supported by the majority applications, etc, nothing will move and you'll see missmatches from time to time, that's just how it established.
