### ISSUE TITLE
No transparency in KDE Plasma kwin5

### ISSUE THREAD

**Issue by arijit79** [alacritty/alacritty#4403] opened 2020-11-11 04:07 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System
OS: Linux
Version: 0.5.0-3
DE: KDE Plasma, kwin5 and Xrender

I installed Alacritty and changed the `background_opacity` from *1.0* to *0.5*. Instead of becoming transparent, it became completely dark. I changed it again to *0.0* and still the problem continue

I am using **software rendering** in KDE

**Comment by kchibisov** [comment] 2020-11-11 04:10
Ah, so kde is running without compositor? Then it shouldn't work afaics, since transparency is done by your compositor.

**Comment by arijit79** [comment] 2020-11-11 19:06
I am using Xrendet as a compositor.  Other terminals like kitty and termite work just fine with transparency. Even other elements such as panels and launchpad in KDE with transparency work fine

**Comment by chrisduerr** [comment] 2020-11-11 19:08
`Xrendet`? Do you have a link to that project, because I'm not familiar with it.

**Comment by arijit79** [comment] 2020-11-12 07:05
Can, 't find any repo for `Xrender` but I tried switching to OpenGL 2 and OpenGL 3.1 but still it does not work

**Comment by chrisduerr** [comment] 2020-11-12 22:04
You need at least OpenGL 3.3+ to run Alacritty. Also I'm gonna close that as a duplicate of https://github.com/alacritty/alacritty/issues/4217. I'd expect things to work for both when one is fixed.

**Closed by chrisduerr** 2020-11-12 22:04 UTC
