### ISSUE TITLE
Feature request - resize alacritty by column and line

### ISSUE THREAD

**Issue by shrubbroom** [alacritty/alacritty#4663] opened 2021-01-05 14:11 UTC
I am using tmux, emacs and other stuff in terminal. They have modelines in the bottom. Every time I have to resize alacritty to a proper size (just include n columns and m line) to eliminate the wasted space around modeline.

tmux with ugly wasted space around modeline
![图片](https://user-images.githubusercontent.com/49093544/103655310-03ae8f80-4fa2-11eb-8cb1-6a1b2f9a5906.png)

tmux where the modeline is perfectly aligned with the border of alacritty.
![图片](https://user-images.githubusercontent.com/49093544/103655416-2ccf2000-4fa2-11eb-921d-60a762298b15.png)

Although I can set
```
window:
   dimensions:
    columns: 80
    lines: 30
```
to make alacritty fit tmux at first. However, once I resize it, it will be hard for me to find a proper size, under which all the stuff is aligned. I wonder if an option can be added to make it possible to resize the alacritty by column and line. An example is made as below:

![Peek 2021-01-05 22-09](https://user-images.githubusercontent.com/49093544/103655875-dadaca00-4fa2-11eb-8202-afc08ceff13c.gif)

**Comment by chrisduerr** [comment] 2021-01-05 14:27
Duplicate of https://github.com/alacritty/alacritty/issues/388.

**Closed by chrisduerr** 2021-01-05 14:27 UTC
