### ISSUE TITLE
"@" and "~" not working with Spanish layout on macOS Big Sur.

### ISSUE THREAD

**Issue by ulisesvina** [alacritty/alacritty#4437] opened 2020-11-16 20:02 UTC
### System

OS: macOS 11.0.1 (Big Sur)
Version: 0.5.0 (Latest) (alacritty -version wasn't working)
Aqua DE & Quartz Compositor WM

### Logs

Crashes: N/A
Font/Terminal size: JetBrains Mono (font) 140 col, 38 lines.

I can't use those characters on the terminal, only copy and pasting them, but that's really tedious and I'd like to do it just like with the default Terminal app on macOS.

**Comment by chrisduerr** [comment] 2020-11-16 21:27
Are you certain that it worked before the update to Big Sur? Generally this is a duplicate of https://github.com/alacritty/alacritty/issues/458, at least that's mostly what we've been tracking these issues under.

**Closed by chrisduerr** 2020-11-16 21:27 UTC
