### ISSUE TITLE
Background slightly transparent even though deactivated on Win10

### ISSUE THREAD

**Issue by trallnag** [alacritty/alacritty#4425] opened 2020-11-14 22:22 UTC
No matter what I do, the background of the Alacritty window is always slightly transparent. It's definitely no burn in, I can see things like windows and menus moving "behind" Alacritty. It affects the whole window including the title bar.

![image](https://user-images.githubusercontent.com/24834206/99158163-30e06f00-26d0-11eb-8acd-e74f3b64391d.png)

If you check with a color picker you will see that the colors are all off by exactly one unit.

![image](https://user-images.githubusercontent.com/24834206/99158181-7c931880-26d0-11eb-84b8-e3db5d2758c2.png)

![image](https://user-images.githubusercontent.com/24834206/99158194-9df40480-26d0-11eb-91d5-10f1da5d5943.png)

### System

OS: Windows
Version: 0.5.0
Windows: ConPTY

### Logs

```
[2020-11-14 23:19:17.564905800] [INFO] Welcome to Alacritty
[2020-11-14 23:19:17.569891800] [INFO] Configuration loaded from "C:\Users\GHXCA\AppData\Roaming\alacritty\alacritty.yml"
[2020-11-14 23:19:17.573881700] [DEBUG] Estimated DPR: 1
[2020-11-14 23:19:17.574912000] [DEBUG] Estimated Cell Size: 7 x 15
[2020-11-14 23:19:17.574912000] [DEBUG] Estimated Dimensions: None
[2020-11-14 23:19:17.817007200] [INFO] Device pixel ratio: 1
[2020-11-14 23:19:17.879836200] [INFO] Initializing glyph cache...
[2020-11-14 23:19:17.894795600] [INFO] ... finished initializing glyph cache in 0.0151538s
[2020-11-14 23:19:17.906764900] [INFO] Cell Size: 7 x 15
[2020-11-14 23:19:17.906764900] [INFO] Padding: 2 x 0
[2020-11-14 23:19:17.907762400] [INFO] Width: 1024, Height: 768
[2020-11-14 23:19:17.931201900] [INFO] PTY dimensions: Line(51) x Column(145)
[2020-11-14 23:19:18.012701300] [INFO] Using ConPTY backend
[2020-11-14 23:19:18.013699200] [INFO] Initialisation complete
[2020-11-14 23:19:18.014694700] [DEBUG] Term::resize dimensions unchanged
[2020-11-14 23:19:18.014694700] [INFO] Width: 1024, Height: 768
```

### Config

```yml
env:
  TERM: alacritty
  IS_ALACRITTY: 'true'

window:
  dynamic_title: true
  padding:
    x: 2
    y: 0
  dynamic_padding: false

background_opacity: 1.0

scrolling:
  history: 0

# shell:
#   program: wsl
#   args:
#     - '~'
#     - tmux

font:
  normal:
    family: Consolas
    style: Regular
  bold:
    family: Consolas
    style: Bold
  italic:
    family: Consolas
    style: Italic
  bold_italic:
    family: Consolas
    style: Bold Italic
  size: 10.0

selection:
  save_to_clipboard: true

mouse:
  double_click: {threshold: 300}
  triple_click: {threshold: 300}

live_config_reload: true

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3
```

**Comment by chrisduerr** [comment] 2020-11-14 22:25
Duplicate of https://github.com/alacritty/alacritty/issues/1927.

**Closed by chrisduerr** 2020-11-14 22:25 UTC
