### ISSUE TITLE
Weird behavior of number sign key (#) on Mac OS

### ISSUE THREAD

**Issue by jarandaf** [alacritty/alacritty#693] opened 2017-07-25 09:30 UTC
I have the following binding in my alacritty config file (using Spanish keyboard layout):

```text
  - { key: F3,      mods: Alt,      chars: "\x23"}
```

It appears to do the job since the number sign (#) is displayed in the terminal but I am not sure it is working properly. When I type it within the shell a new endline is somehow introduced:

```bash
$ # (I am pressing Alt + F3 here)
$ (automatically a new line is introduced, the above line can't be continued)
```

Within vim I also get weird errors whenever I try to enter number sign for python commands:
```text
E348: No string under cursor
```
I have observed vim actually exits insert mode and switches back to normal mode whenever typing the number sign key (#). This makes me think the above mentioned binding might be wrong or something else is happening behind the scenes.

**Comment by jarandaf** [comment] 2017-07-25 10:38
As a follow up, I have found that `#` key is inserting actually `^[#` using this [method](https://superuser.com/questions/997593/why-does-zsh-insert-a-when-i-press-the-delete-key). Same happens for other keys such as backslash (`^[\` instead of `\`)

I can fix this within my shell (by using `bindkey` in `zsh`).

`^[` is a literal `ESC` character and this would explain why Vim exits insert mode. A possible solution would be to map this to proper characters, e.g.:

```
inoremap <Esc># #
inoremap <Esc>\ \
```

This is not an optimal solution but it works.

**Comment by simmel** [comment] 2017-11-30 08:51
On master `#` now is 'normal' and is just #. But there are other keys which have escape before them:
Here I type press `§` to `´` (the numeric row) in OS X with a Swedish keyboard layout pressing the opt/Alt modifier:
```
$ cat -v
¶©^[@£^[$∞§^[|^[[^[]≈±´
```
Here I type press `§` to `´` (the numeric row) in OS X with a Swedish keyboard layout pressing the opt/Alt and shift modifier:

```
$ cat -v
•¡”¥¢‰¶^[\^[{^[}≠¿^[`
```

Sorry for hijacking this thread @jarandaf

**Comment by simmel** [comment] 2017-11-30 09:00
This is related to #458

**Comment by chrisduerr** [comment] 2020-04-28 23:24
Closing as duplicate of #458 and https://github.com/alacritty/alacritty/pull/890. I believe those combined should cover the macOS keyboard problems.

Let me know if you think this doesn't fit.

**Closed by chrisduerr** 2020-04-28 23:24 UTC
