### ISSUE TITLE
font anti-aliasing

### ISSUE THREAD

**Issue by zhengkai** [alacritty/alacritty#4135] opened 2020-08-17 10:50 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Ubuntu 20.04 TLS
Version: alacritty 0.5.0 (a6681e3)

### Config

```
font:
  normal:
    family: JetBrains Mono NL
    style: Regular
  size: 13.0
  offset:
    x: 0
    y: 0
```

I'm using character `│` as seperator line, there are some "dot" in line

![a](https://user-images.githubusercontent.com/247015/90387872-84cfbd80-e0b9-11ea-9fb8-3f4793a370ac.png)

In `gnome-terminal` , same config （ [JetBrains Mono NL](https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.6) Regular 13 ）, no dot in seperator line, looks smooth

![b](https://user-images.githubusercontent.com/247015/90387876-8600ea80-e0b9-11ea-8e27-e9bd002ee3dd.png)

**Comment by kchibisov** [comment] 2020-08-17 10:53
gnome is drawing a line on its own(it's artificially homogeneous), we're using the line from your font as you can see. However the issue we have that we blend those characters a bit, and so certain parts of it become brighter, resulting in a visual dot.

**Comment by kchibisov** [comment] 2020-08-17 10:59
duplicate of https://github.com/alacritty/alacritty/issues/118

**Closed by kchibisov** 2020-08-17 10:59 UTC

**Comment by zhengkai** [comment] 2020-11-17 11:01
delete alacritty and install [kitty](https://sw.kovidgoyal.net/kitty/), feel perfect
