### ISSUE TITLE
Upgrading to 0.11 changes behaviour of alt key

### ISSUE THREAD

**Issue by oschrenk** [alacritty/alacritty#6446] opened 2022-10-25 18:29 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS 13.0
Version: 0.11

### Logs

On 0.10.1 the following config allowed me to use `Alt+e` to open the current commandline in $EDITOR via fish shell, in 0.11 it now produces a ``` instead

I tried explicitly setting `alt_send_esc: true` in the root element of the config but it doesn't change the results

```
window:
  padding:
    x: 0
    y: 0
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 20.0
  normal:
    family: "mplus Nerd Font Mono"
    style: light
  bold:
    family: "mplus Nerd Font Mono"
    style: regular
  offset:
    x: 0
    y: 0

colors:
  primary:
    background: '0x262626'
    foreground: '0xeaeaea'

shell:
  program: /usr/local/bin/fish
  args:
    - --login
    - --init-command
    - "tl personal"

key_bindings:
  # Fix Alt as Meta in macOS
  - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  - { key: E,         mods: Alt,       chars: "\x1be"                       }
  - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  - { key: R,         mods: Alt,       chars: "\x1br"                       }
  - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
  - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
  - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
  - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
  - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
  - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
  - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
  - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
  - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
  - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
  - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
  - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
  - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
  - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
  - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
  - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
  - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
  - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
  - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
  - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
  - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
  - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
  - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
  - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
  - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
  - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
  - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
  - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
  - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
  - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
  - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
  - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
  - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
  - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
  - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
  - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
  - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
  - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
  - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
  - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
  - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
  - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
  - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
  - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
  - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
  - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
  - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       }
  - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
  - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |

```

**Comment by deathlyfrantic** [comment] 2022-10-25 20:50
I have this exact same problem and basically the same alt key mappings.

macOS has functionality to type accented characters using a system similar to Vim's digraph input. <kbd>Option-E</kbd> + <kbd>e</kbd> for example results in é. Prior to 0.11.0 this didn't work in Alacritty - instead I'd just get `\x1be` as expected. 

As of 0.11.0 it does work, which means I don't get `\x1be`. Worse yet, it seems to "pollute" the session for all other alt-key combinations. So e.g. <kbd>Option-F</kbd> works fine _until_ I use <kbd>Option-E</kbd>. After that, <kbd>Option-F</kbd>  gives me ƒ instead of `\x1bf`. I have to quit Alacritty entirely to "clear" this state.

On my US keyboard layout, the problematic keys are <kbd>E</kbd>, <kbd>U</kbd>, <kbd>I</kbd>, and <kbd>N</kbd>. <kbd>Option</kbd> + any of those causes this same problem.

For reference I'm on macOS 12.6.

**Comment by chrisduerr** [comment] 2022-10-25 21:58
Duplicate of #62.

**Closed by chrisduerr** 2022-10-25 21:58 UTC

**Comment by deathlyfrantic** [comment] 2022-10-25 22:01
For reference, here's a screen recording:

https://user-images.githubusercontent.com/7629614/197890106-30d0f19c-6625-4a96-885c-00c891364915.mov

To move between words I'm using <kbd>Option+F</kbd> and <kbd>Option+B</kbd>. After I do <kbd>Option+E</kbd> <kbd>E</kbd> those previous keypresses now insert the ƒ and ∫ characters instead of moving between words.

**Comment by deathlyfrantic** [comment] 2022-10-25 22:04
@chrisduerr I do not believe this is a duplicate. This mapping I have in my config worked fine before 0.11.0:

```
- { key: E, mods: Alt, chars: "\x1be" }
```

Now it has the behavior shown in the screen recording above.

**Comment by chrisduerr** [comment] 2022-10-25 22:05
Working before 0.11.0 was mostly a coincidence. You clearly want to change the way your alt modifier behaves, and #62 is the issue tracking that.
