### ISSUE TITLE
Crashes immediately on GNOME/Wayland with the Nvidia driver

### ISSUE THREAD

**Issue by ananthb** [alacritty/alacritty#5473] opened 2021-09-04 14:31 UTC
Alacritty crashes immediately on GNOME/Wayland with the Nvidia 470.63.01-4 driver on Arch Linux.

### System

OS: Linux
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: Wayland, Gnome

### Logs

Crashes: 
```
Created log file at "/tmp/Alacritty-22599.log"
[2021-09-04 19:57:32.034146140] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; eglCreateWindowSurface failed
                                                    
```

Font/Terminal size:
```
Created log file at "/tmp/Alacritty-22274.log"
[2021-09-04 19:57:08.358144319] [INFO ] [alacritty] Welcome to Alacritty
[2021-09-04 19:57:08.358203132] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/ananth/.config/alacritty/alacritty.yml"
[2021-09-04 19:57:08.366203941] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-09-04 19:57:08.367773350] [DEBUG] [alacritty] Estimated DPR: 1
[2021-09-04 19:57:08.367787687] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 880, height: 528 })
[2021-09-04 19:57:08.367796324] [DEBUG] [alacritty] Estimated cell size: 11 x 22
[2021-09-04 19:57:08.402723937] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; eglCreateWindowSurface failed
```

Keyboard and bindings:
```
Created log file at "/tmp/Alacritty-22487.log"
[2021-09-04 19:57:23.957986921] [INFO ] [alacritty] Welcome to Alacritty
[2021-09-04 19:57:23.958052336] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/ananth/.config/alacritty/alacritty.yml"
[2021-09-04 19:57:24.001837878] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; eglCreateWindowSurface failed
```

**Comment by chrisduerr** [comment] 2021-09-04 15:43
Which GPU?

**Comment by ananthb** [comment] 2021-09-06 05:29
@chrisduerr Nvidia RTX 2070 Super

**Comment by chrisduerr** [comment] 2021-09-15 08:42
Duplicate of https://github.com/alacritty/alacritty/issues/1269.

**Closed by chrisduerr** 2021-09-15 08:42 UTC
