### ISSUE TITLE
Crash when resizing terminal window

### ISSUE THREAD

**Issue by r0manarmy** [alacritty/alacritty#6606] opened 2023-01-07 06:45 UTC
I created a new alacritty window, snapped it to take up half of the screen, then resized the window to be smaller, than bigger. On resizing it to be bigger, it crashes. Crash only happens with a release build, I couldn't reproduce it on a debug build. Doesn't reproduce if window isn't snapped to take up half the screen.

### System

OS: Linux (Ubunti 22.10)
Version: 0.12.0-dev (2bd26fbe)
Linux/BSD: Wayland, Gnome 43.1

### Logs
```
RUST_BACKTRACE=full ./target/release/alacritty                
wl_shm_pool@31: error 2: shrinking pool invalid
thread 'main' panicked at 'failed to dispatch wayland event queue: Os { code: 71, kind: Uncategorized, message: "Protocol error" }', alacritty/src/event.rs:1463:30
stack backtrace:
   0:     0x55db49676153 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55db49676153 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55db49676153 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55db49676153 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55db4953f39e - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x55db4964d894 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x55db496786ff - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55db496786ff - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55db496782ff - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x55db49679398 - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x55db49679398 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x55db49678e62 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:     0x55db49678dcc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55db49678da1 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x55db49325832 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x55db49325ad2 - core::result::unwrap_failed::ha17dbf463031a5e1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
  16:     0x55db4940e499 - core::result::Result<T,E>::expect::h25bdfe6076081904
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1070:23
  17:     0x55db4940e499 - alacritty::event::Processor::run::{{closure}}::h0a9c5919286aaa6c
                               at /home/roman/tools/alacritty/alacritty/src/event.rs:1461:25
  18:     0x55db49376284 - winit::platform_impl::platform::sticky_exit_callback::hcb846fe1e3c1b4ea
                               at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:849:9
  19:     0x55db49376284 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h81d4ce2de82a6836
                               at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/wayland/event_loop/mod.rs:539:13
  20:     0x55db4945f405 - winit::platform_impl::platform::EventLoop<T>::run_return::h2bc2969a5b796ff8
                               at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:748:56
  21:     0x55db4945f405 - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::hd5e4de2c319a63b6
                               at /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform/run_return.rs:62:9
  22:     0x55db4945f405 - alacritty::event::Processor::run::h565ed8bd6d1fd0d1
                               at /home/roman/tools/alacritty/alacritty/src/event.rs:1398:25
  23:     0x55db4935c39b - alacritty::alacritty::hde6d4b1536cb6755
                               at /home/roman/tools/alacritty/alacritty/src/main.rs:189:18
  24:     0x55db4935c39b - alacritty::main::h14b0d3469895528e
                               at /home/roman/tools/alacritty/alacritty/src/main.rs:83:17
  25:     0x55db49400053 - core::ops::function::FnOnce::call_once::h0239523e2dbdf72c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  26:     0x55db49400053 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8de9cbaff00c7b68
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  27:     0x55db49366867 - main
  28:     0x7f7c2a823510 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  29:     0x7f7c2a8235c9 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  30:     0x55db4933cfe5 - _start
  31:                0x0 - <unknown>

```
and
```
❯ alacritty -vv                                 
Created log file at "/tmp/Alacritty-21193.log"
[0.000010069s] [INFO ] [alacritty] Welcome to Alacritty
[0.000104152s] [INFO ] [alacritty] Version 0.12.0-dev (2bd26fbe)
[0.000124210s] [INFO ] [alacritty] Running on Wayland
[0.000601479s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/roman/.alacritty.yml"
[0.032195739s] [INFO ] [alacritty] Using EGL 1.5
[0.043451067s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.050575655s] [INFO ] [alacritty] Window scale factor: 1
[0.051430014s] [DEBUG] [alacritty] Loading "Code New Roman" font
[0.054215089s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.057981836s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.061476276s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.064848721s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.069531738s] [INFO ] [alacritty] Running on AMD Radeon RX 5500 XT (navi14, LLVM 15.0.2, DRM 3.47, 5.19.0-28-generic)
[0.069554476s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.075507551s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.081564237s] [INFO ] [alacritty] Cell size: 10 x 20
[0.081587839s] [INFO ] [alacritty] Padding: 0 x 0
[0.081600339s] [INFO ] [alacritty] Width: 800, Height: 600
[0.082261195s] [INFO ] [alacritty] PTY dimensions: 30 x 80
[0.084791029s] [INFO ] [alacritty] Initialisation complete
[0.108468304s] [DEBUG] [alacritty_terminal] New num_cols is 82 and num_lines is 31
[0.109882039s] [INFO ] [alacritty] Padding: 0 x 0
[0.109913094s] [INFO ] [alacritty] Width: 820, Height: 620
[0.236748008s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1'],['.''.''o''l''s''/''a''l''a''c''r''i''t''t''y'],] at line 963
[0.263884970s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.264099170s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[3.883020237s] [DEBUG] [alacritty_terminal] New num_cols is 192 and num_lines is 104
[3.884353233s] [INFO ] [alacritty] Padding: 0 x 0
[3.884370027s] [INFO ] [alacritty] Width: 1920, Height: 2098
[13.358599082s] [DEBUG] [alacritty_terminal] New num_cols is 191 and num_lines is 104
[13.358714403s] [INFO ] [alacritty] Padding: 0 x 0
[13.358725675s] [INFO ] [alacritty] Width: 1919, Height: 2098
[13.398120964s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.398188621s] [INFO ] [alacritty] Padding: 0 x 0
[13.398211981s] [INFO ] [alacritty] Width: 1917, Height: 2098
[13.401981900s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.405458054s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.407191497s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.411181077s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.413275033s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.413334180s] [INFO ] [alacritty] Padding: 0 x 0
[13.413343857s] [INFO ] [alacritty] Width: 1911, Height: 2098
[13.416626339s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.419615910s] [DEBUG] [alacritty_terminal] New num_cols is 190 and num_lines is 104
[13.419817243s] [INFO ] [alacritty] Padding: 0 x 0
[13.419834947s] [INFO ] [alacritty] Width: 1909, Height: 2098

.... a bunch more resizes ....

[17.793412648s] [INFO ] [alacritty] Width: 1629, Height: 2098
[17.795805882s] [DEBUG] [alacritty_terminal] New num_cols is 163 and num_lines is 104
[17.796718993s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.799405081s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.801322633s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.805491780s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.807345400s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.809903454s] [INFO ] [alacritty] Padding: 0 x 0
[17.809957795s] [INFO ] [alacritty] Width: 1637, Height: 2098
[17.813102777s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.813969627s] [DEBUG] [alacritty_terminal] New num_cols is 164 and num_lines is 104
[17.815282007s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.830828833s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.832591651s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[17.832669026s] [INFO ] [alacritty] Padding: 0 x 0
[17.832679275s] [INFO ] [alacritty] Width: 1649, Height: 2098
wl_shm_pool@31: error 2: shrinking pool invalid
thread 'main' panicked at 'failed to dispatch wayland event queue: Os { code: 71, kind: Uncategorized, message: "Protocol error" }', alacritty/src/event.rs:1463:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by kchibisov** [comment] 2023-01-07 08:32
Duplicate of https://github.com/alacritty/alacritty/issues/6455 . For now there's an option to disable decorations.

**Closed by kchibisov** 2023-01-07 08:32 UTC

**Comment by r0manarmy** [comment] 2023-01-07 08:49
It may be a duplicate, but these steps reproduce the issue 100% of the time. That should at least make it easier to debug.

**Comment by kchibisov** [comment] 2023-01-07 09:01
Yeah, for you. For me I can't ever repro this issue under the gnome no matter what I try :- (.
