### ISSUE TITLE
Copy/Paste adding newlines in vim

### ISSUE THREAD

**Issue by sharksforarms** [alacritty/alacritty#4075] opened 2020-08-03 18:49 UTC
This may be a vim issue.. but

I am ssh'ing into a Ubuntu 18.04 VM and opening vim, I'm copy pasting a multi-line file from my windows host and for every new line, it seems to be adding an extra new-line in vim. This does not happen in other editors such as nano

Does anyone else have this issue?

### System

OS: Windows 10
Version: `alacritty 0.5.0 (a6681e3)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: 
```
[2020-08-03 14:45:32.511933200] [INFO] Welcome to Alacritty
[2020-08-03 14:45:32.513885800] [INFO] Configuration loaded from "C:\Users\sharks\AppData\Roaming\alacritty\alacritty.yml"
[2020-08-03 14:45:32.630029100] [INFO] Device pixel ratio: 1
[2020-08-03 14:45:32.742268500] [INFO] Initializing glyph cache...
[2020-08-03 14:45:32.743245700] [INFO] ... finished initializing glyph cache in 0.001297s
[2020-08-03 14:45:32.744220700] [INFO] Cell Size: 8 x 17
[2020-08-03 14:45:32.744220700] [INFO] Padding: 0 x 0
[2020-08-03 14:45:32.744220700] [INFO] Width: 1024, Height: 768
[2020-08-03 14:45:32.768621000] [INFO] PTY dimensions: Line(45) x Column(128)
[2020-08-03 14:45:32.774477800] [INFO] Using ConPTY backend
[2020-08-03 14:45:32.774477800] [INFO] Initialisation complete
[2020-08-03 14:45:32.775453400] [INFO] Width: 1024, Height: 768
```

### Logs

N/A

**Comment by chrisduerr** [comment] 2020-08-03 18:58
This is a duplicate of #2324.

**Closed by chrisduerr** 2020-08-03 18:58 UTC
