### ISSUE TITLE
`window.startup_mode` option as `Fullscreen` doesn't work as expected (tho the same as other terminals, initial fullscreen option)

### ISSUE THREAD

**Issue by Quantenzitrone** [alacritty/alacritty#6941] opened 2023-05-22 07:05 UTC
### Problem Description
When using the command line option `-o window.startup_mode=Fullscreen` and later trying the same from alacritty.yml, 
i found out, that alacritty doesn't start in fullscreen, but rather gets fullscreened instantly on startup.
This can be seen when executing this command: 
```bash
alacritty -o window.startup_mode=Fullscreen -e cbonsai
```
Alacritty exits immediately, because cbonsai, by default exits when the terminal resizes.
(if it doesnt work it may be a race condition, for me it behaves the same every time)

When instead using 
```sh
alacritty -o window.startup_mode=Fullscreen -e cbonsai -l
``` 
cbonsai doesn't exit immediately, but also doesn't refresh the terminal size resulting in, depending on the initial window size, a misaligned bonsai. 
Another example for a program broken by this would be bat (e.g. `alacritty -e sh -c "bat .config/alacritty/alacritty.yml; read"`)

Generally this is a problem for anything that depends on the terminal size, and doesn't refresh when the size changes

### Proposed Solution
- wait with the provided command, until the window is finished resizing
- actually start the window in fullscreen somehow

### System
OS: NixOS GNU/Linux
Version: 1.12.0
WM: i3

**Comment by kchibisov** [comment] 2023-05-22 07:10
Duplicate of https://github.com/alacritty/alacritty/issues/2817

**Closed by kchibisov** 2023-05-22 07:10 UTC

**Comment by kchibisov** [comment] 2023-05-22 07:11
The start fullscreen without resizes will work on Wayland from alacritty `0.13.0` for X11 can't say much, but the issue is the one I've linked.

**Comment by Quantenzitrone** [comment] 2023-05-22 07:20
damn xorg
im having the same race condition for every terminal and even when doing
```
$TERMINAL -e sh -c "wmctrl -r ':ACTIVE:' -b add,fullscreen; cbonsai'"
```
still wmctrl finishes before finishing fullscreening 
seems like i really have to add a delay

**Comment by kchibisov** [comment] 2023-05-22 07:33
I know xterm has a flag to wait for window to map, but I don't remember what it's called.

**Comment by Quantenzitrone** [comment] 2023-05-22 07:37
thanks, searching through the manpage it's `-wf`
