### ISSUE TITLE
Alacritty 0.13.0-3 doesn't start on GNOME Wayland

### ISSUE THREAD

**Issue by kekkoudesu** [alacritty/alacritty#7523] opened 2024-01-01 12:11 UTC
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

When I try to run Alacritty, nothing happens. I recently upgraded from 0.12.3 to 0.13.0 on Arch Linux. I've downgraded to 0.12.3 and it still works.

Edit: Actually, when I alt+tab, I can see several Alacritty windows I can tab to which don't actually seem to exist.

### System

OS: Arch Linux
Version: `alacritty --version` output
`alacritty 0.13.0 (78fa4d6f)`
Linux/BSD: Wayland, GNOME

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`

```
alacritty -vv
Created log file at "/tmp/Alacritty-10694.log"
[0.000002526s] [INFO ] [alacritty] Welcome to Alacritty
[0.000037779s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000042879s] [INFO ] [alacritty] Running on Wayland
[0.000133843s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/kek/.config/alacritty/alacritty.toml"
[0.019057112s] [INFO ] [alacritty] Using EGL 1.5
[0.019095390s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.042704232s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.046793129s] [INFO ] [alacritty] Window scale factor: 1
[0.047700144s] [DEBUG] [alacritty] Loading "monospace" font
[0.049767082s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.052937692s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.056569733s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.060083426s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.064150127s] [INFO ] [alacritty] Running on Mesa Intel(R) Xe Graphics (TGL GT2)
[0.064171984s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.2-arch1.1, shader_version 4.60
[0.064177840s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.069191402s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.069356192s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.078136672s] [INFO ] [alacritty] Cell size: 9 x 22
[0.078164211s] [INFO ] [alacritty] Padding: 0 x 0
[0.078169054s] [INFO ] [alacritty] Width: 1920, Height: 1013
[0.078207586s] [INFO ] [alacritty] PTY dimensions: 46 x 213
[0.080665818s] [INFO ] [alacritty] Initialisation complete
```

Keyboard and bindings: `alacritty --print-events`

```
WAYLAND_DEBUG=1 alacritty --print-events
[ 490876.835]  -> wl_display@1.get_registry(new id wl_registry@2)
[ 490876.861]  -> wl_display@1.sync(new id wl_callback@3)
[ 490877.023] wl_display@1.delete_id(3)
[ 490877.036] wl_registry@2.global(1, "wl_compositor", 5)
[ 490877.051] wl_registry@2.global(2, "wl_drm", 2)
[ 490877.059] wl_registry@2.global(3, "wl_shm", 1)
[ 490877.065] wl_registry@2.global(4, "wl_output", 4)
[ 490877.072] wl_registry@2.global(5, "zxdg_output_manager_v1", 3)
[ 490877.079] wl_registry@2.global(6, "wl_data_device_manager", 3)
[ 490877.086] wl_registry@2.global(7, "zwp_primary_selection_device_manager_v1", 1)
[ 490877.093] wl_registry@2.global(8, "wl_subcompositor", 1)
[ 490877.101] wl_registry@2.global(9, "xdg_wm_base", 6)
[ 490877.108] wl_registry@2.global(10, "gtk_shell1", 5)
[ 490877.116] wl_registry@2.global(11, "wp_viewporter", 1)
[ 490877.123] wl_registry@2.global(12, "wp_fractional_scale_manager_v1", 1)
[ 490877.132] wl_registry@2.global(13, "zwp_pointer_gestures_v1", 3)
[ 490877.139] wl_registry@2.global(14, "zwp_tablet_manager_v2", 1)
[ 490877.146] wl_registry@2.global(15, "wl_seat", 8)
[ 490877.154] wl_registry@2.global(16, "zwp_relative_pointer_manager_v1", 1)
[ 490877.161] wl_registry@2.global(17, "zwp_pointer_constraints_v1", 1)
[ 490877.169] wl_registry@2.global(18, "zxdg_exporter_v2", 1)
[ 490877.176] wl_registry@2.global(19, "zxdg_importer_v2", 1)
[ 490877.183] wl_registry@2.global(20, "zxdg_exporter_v1", 1)
[ 490877.190] wl_registry@2.global(21, "zxdg_importer_v1", 1)
[ 490877.197] wl_registry@2.global(22, "zwp_linux_dmabuf_v1", 4)
[ 490877.205] wl_registry@2.global(23, "wp_single_pixel_buffer_manager_v1", 1)
[ 490877.213] wl_registry@2.global(24, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 490877.220] wl_registry@2.global(25, "zwp_text_input_manager_v3", 1)
[ 490877.226] wl_registry@2.global(26, "wp_presentation", 1)
[ 490877.232] wl_registry@2.global(27, "xdg_activation_v1", 1)
[ 490877.239] wl_registry@2.global(28, "zwp_idle_inhibit_manager_v1", 1)
[ 490877.246] wl_callback@3.done(1294)
[ 490877.361]  -> wl_registry@2.bind(1, "wl_compositor", 5, new id [unknown]@3)
[ 490877.375]  -> wl_registry@2.bind(8, "wl_subcompositor", 1, new id [unknown]@4)
[ 490877.390]  -> wl_registry@2.bind(4, "wl_output", 4, new id [unknown]@5)
[ 490877.399]  -> wl_registry@2.bind(5, "zxdg_output_manager_v1", 3, new id [unknown]@6)
[ 490877.415]  -> zxdg_output_manager_v1@6.get_xdg_output(new id zxdg_output_v1@7, wl_output@5)
[ 490877.428]  -> wl_registry@2.bind(15, "wl_seat", 7, new id [unknown]@8)
[ 490877.457]  -> wl_registry@2.bind(12, "wp_fractional_scale_manager_v1", 1, new id [unknown]@9)
[ 490877.468]  -> wl_registry@2.bind(11, "wp_viewporter", 1, new id [unknown]@10)
[ 490877.481]  -> wl_registry@2.bind(3, "wl_shm", 1, new id [unknown]@11)
[ 490877.490]  -> wl_registry@2.bind(9, "xdg_wm_base", 6, new id [unknown]@12)
[ 490877.499]  -> wl_registry@2.bind(27, "xdg_activation_v1", 1, new id [unknown]@13)
[ 490877.508]  -> wl_registry@2.bind(25, "zwp_text_input_manager_v3", 1, new id [unknown]@14)
[ 490877.516]  -> wl_registry@2.bind(16, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@15)
[ 490877.524]  -> wl_registry@2.bind(17, "zwp_pointer_constraints_v1", 1, new id [unknown]@16)
[ 490877.536]  -> wl_display@1.sync(new id wl_callback@17)
[ 490877.793] wl_display@1.delete_id(17)
[ 490877.801] wl_output@5.geometry(0, 0, 340, 190, 0, "BOE", "0x0a89", 0)
[ 490877.814] wl_output@5.mode(3, 1920, 1080, 59998)
[ 490877.821] wl_output@5.scale(1)
[ 490877.826] wl_output@5.name("eDP-1")
[ 490877.833] wl_output@5.description("Built-in display")
[ 490877.841] wl_output@5.done()
[ 490877.846] zxdg_output_v1@7.logical_position(0, 0)
[ 490877.854] zxdg_output_v1@7.logical_size(1920, 1080)
[ 490877.860] zxdg_output_v1@7.name("eDP-1")
[ 490877.870] zxdg_output_v1@7.description("Built-in display")
[ 490877.876] wl_output@5.done()
[ 490877.882] wl_seat@8.capabilities(3)
[ 490877.889] wl_seat@8.name("seat0")
[ 490877.895] wl_shm@11.format(0)
[ 490877.901] wl_shm@11.format(1)
[ 490877.906] wl_shm@11.format(875708993)
[ 490877.913] wl_shm@11.format(875709016)
[ 490877.922] wl_shm@11.format(909199186)
[ 490877.927] wl_shm@11.format(808669761)
[ 490877.933] wl_shm@11.format(808669784)
[ 490877.938] wl_shm@11.format(808665665)
[ 490877.943] wl_shm@11.format(808665688)
[ 490877.949] wl_shm@11.format(1211388481)
[ 490877.954] wl_shm@11.format(1211388504)
[ 490877.960] wl_shm@11.format(1211384385)
[ 490877.964] wl_shm@11.format(1211384408)
[ 490877.969] wl_callback@17.done(1294)
[ 490878.002]  -> wl_seat@8.get_keyboard(new id wl_keyboard@17)
[ 490883.306]  -> zwp_text_input_manager_v3@14.get_text_input(new id zwp_text_input_v3@18, wl_seat@8)
[ 490883.315]  -> wl_compositor@3.create_surface(new id wl_surface@19)
[ 490883.318]  -> wl_seat@8.get_pointer(new id wl_pointer@20)
[ 490883.323]  -> zwp_relative_pointer_manager_v1@15.get_relative_pointer(new id zwp_relative_pointer_v1@21, wl_pointer@20)
Created log file at "/tmp/Alacritty-8855.log"
[0.000002832s] [INFO ] [alacritty] Welcome to Alacritty
[0.000052821s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000057122s] [INFO ] [alacritty] Running on Wayland
[0.000138669s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/kek/.config/alacritty/alacritty.toml"
[ 490883.956]  -> wl_display@1.get_registry(new id wl_registry@22)
[0.000581408s] [INFO ] [alacritty] winit event: NewEvents(Init)
[ 490883.963]  -> wl_display@1.sync(new id wl_callback@23)
[0.000606154s] [INFO ] [alacritty] winit event: Resumed
[ 490884.079] wl_display@1.delete_id(23)
[ 490884.083] wl_registry@22.global(1, "wl_compositor", 5)
[ 490884.089] wl_registry@22.global(2, "wl_drm", 2)
[ 490884.091] wl_registry@22.global(3, "wl_shm", 1)
[ 490884.094] wl_registry@22.global(4, "wl_output", 4)
[ 490884.096] wl_registry@22.global(5, "zxdg_output_manager_v1", 3)
[ 490884.099] wl_registry@22.global(6, "wl_data_device_manager", 3)
[ 490884.101] wl_registry@22.global(7, "zwp_primary_selection_device_manager_v1", 1)
[ 490884.103] wl_registry@22.global(8, "wl_subcompositor", 1)
[ 490884.105] wl_registry@22.global(9, "xdg_wm_base", 6)
[ 490884.108] wl_registry@22.global(10, "gtk_shell1", 5)
[ 490884.110] wl_registry@22.global(11, "wp_viewporter", 1)
[ 490884.113] wl_registry@22.global(12, "wp_fractional_scale_manager_v1", 1)
[ 490884.116] wl_registry@22.global(13, "zwp_pointer_gestures_v1", 3)
[ 490884.118] wl_registry@22.global(14, "zwp_tablet_manager_v2", 1)
[ 490884.121] wl_registry@22.global(15, "wl_seat", 8)
[ 490884.123] wl_registry@22.global(16, "zwp_relative_pointer_manager_v1", 1)
[ 490884.126] wl_registry@22.global(17, "zwp_pointer_constraints_v1", 1)
[ 490884.130] wl_registry@22.global(18, "zxdg_exporter_v2", 1)
[ 490884.133] wl_registry@22.global(19, "zxdg_importer_v2", 1)
[ 490884.135] wl_registry@22.global(20, "zxdg_exporter_v1", 1)
[ 490884.138] wl_registry@22.global(21, "zxdg_importer_v1", 1)
[ 490884.140] wl_registry@22.global(22, "zwp_linux_dmabuf_v1", 4)
[ 490884.143] wl_registry@22.global(23, "wp_single_pixel_buffer_manager_v1", 1)
[ 490884.145] wl_registry@22.global(24, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 490884.148] wl_registry@22.global(25, "zwp_text_input_manager_v3", 1)
[ 490884.150] wl_registry@22.global(26, "wp_presentation", 1)
[ 490884.153] wl_registry@22.global(27, "xdg_activation_v1", 1)
[ 490884.155] wl_registry@22.global(28, "zwp_idle_inhibit_manager_v1", 1)
[ 490884.157] wl_callback@23.done(1294)
[ 490884.177]  -> wl_registry@22.bind(6, "wl_data_device_manager", 3, new id [unknown]@23)
[ 490884.182]  -> wl_registry@22.bind(7, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@24)
[ 490884.187]  -> wl_registry@22.bind(15, "wl_seat", 7, new id [unknown]@25)
[ 490884.229] wl_seat@25.capabilities(3)
[ 490884.233] wl_seat@25.name("seat0")
[ 490884.239]  -> wl_seat@25.get_keyboard(new id wl_keyboard@26)
[ 490884.245]  -> wl_data_device_manager@23.get_data_device(new id wl_data_device@27, wl_seat@25)
[ 490884.250]  -> zwp_primary_selection_device_manager_v1@24.get_device(new id zwp_primary_selection_device_v1@28, wl_seat@25)
[ 490884.256]  -> wl_seat@25.get_pointer(new id wl_pointer@29)
[ 490884.302] wl_keyboard@26.keymap(1, fd 21, 68422)
[ 490884.309] wl_keyboard@26.repeat_info(40, 186)
[ 490887.151]  -> wl_display@1.get_registry(new id wl_registry@30)
[ 490887.176]  -> wl_display@1.sync(new id wl_callback@31)
[ 490887.512] wl_display@1.delete_id(31)
[ 490887.531] wl_registry@30.global(1, "wl_compositor", 5)
[ 490887.542] wl_registry@30.global(2, "wl_drm", 2)
[ 490887.551] wl_registry@30.global(3, "wl_shm", 1)
[ 490887.560] wl_registry@30.global(4, "wl_output", 4)
[ 490887.569] wl_registry@30.global(5, "zxdg_output_manager_v1", 3)
[ 490887.577] wl_registry@30.global(6, "wl_data_device_manager", 3)
[ 490887.585] wl_registry@30.global(7, "zwp_primary_selection_device_manager_v1", 1)
[ 490887.594] wl_registry@30.global(8, "wl_subcompositor", 1)
[ 490887.603] wl_registry@30.global(9, "xdg_wm_base", 6)
[ 490887.611] wl_registry@30.global(10, "gtk_shell1", 5)
[ 490887.620] wl_registry@30.global(11, "wp_viewporter", 1)
[ 490887.629] wl_registry@30.global(12, "wp_fractional_scale_manager_v1", 1)
[ 490887.638] wl_registry@30.global(13, "zwp_pointer_gestures_v1", 3)
[ 490887.646] wl_registry@30.global(14, "zwp_tablet_manager_v2", 1)
[ 490887.655] wl_registry@30.global(15, "wl_seat", 8)
[ 490887.663] wl_registry@30.global(16, "zwp_relative_pointer_manager_v1", 1)
[ 490887.672] wl_registry@30.global(17, "zwp_pointer_constraints_v1", 1)
[ 490887.680] wl_registry@30.global(18, "zxdg_exporter_v2", 1)
[ 490887.690] wl_registry@30.global(19, "zxdg_importer_v2", 1)
[ 490887.699] wl_registry@30.global(20, "zxdg_exporter_v1", 1)
[ 490887.707] wl_registry@30.global(21, "zxdg_importer_v1", 1)
[ 490887.716] wl_registry@30.global(22, "zwp_linux_dmabuf_v1", 4)
[ 490887.728]  -> wl_registry@30.bind(22, "zwp_linux_dmabuf_v1", 4, new id [unknown]@32)
[ 490887.740] wl_registry@30.global(23, "wp_single_pixel_buffer_manager_v1", 1)
[ 490887.749] wl_registry@30.global(24, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 490887.759] wl_registry@30.global(25, "zwp_text_input_manager_v3", 1)
[ 490887.768] wl_registry@30.global(26, "wp_presentation", 1)
[ 490887.776] wl_registry@30.global(27, "xdg_activation_v1", 1)
[ 490887.785] wl_registry@30.global(28, "zwp_idle_inhibit_manager_v1", 1)
[ 490887.793] wl_callback@31.done(1294)
[ 490887.806]  -> zwp_linux_dmabuf_v1@32.get_default_feedback(new id zwp_linux_dmabuf_feedback_v1@31)
[ 490887.818]  -> wl_display@1.sync(new id wl_callback@33)
[ 490888.073] wl_display@1.delete_id(33)
[ 490888.084] zwp_linux_dmabuf_feedback_v1@31.format_table(fd 21, 1360)
[ 490888.123] zwp_linux_dmabuf_feedback_v1@31.main_device(array[8])
[ 490888.742] zwp_linux_dmabuf_feedback_v1@31.tranche_target_device(array[8])
[ 490888.755] zwp_linux_dmabuf_feedback_v1@31.tranche_flags(0)
[ 490888.766] zwp_linux_dmabuf_feedback_v1@31.tranche_formats(array[170])
[ 490888.790] zwp_linux_dmabuf_feedback_v1@31.tranche_done()
[ 490888.800] zwp_linux_dmabuf_feedback_v1@31.done()
[ 490888.808] wl_callback@33.done(1294)
[ 490888.820]  -> zwp_linux_dmabuf_feedback_v1@31.destroy()
[0.023648339s] [INFO ] [alacritty] Using EGL 1.5
[ 490907.236]  -> wl_compositor@3.create_surface(new id wl_surface@33)
[ 490907.247]  -> xdg_wm_base@12.get_xdg_surface(new id xdg_surface@34, wl_surface@33)
[ 490907.253]  -> xdg_surface@34.get_toplevel(new id xdg_toplevel@35)
[ 490907.260]  -> wp_viewporter@10.get_viewport(new id wp_viewport@36, wl_surface@33)
[ 490907.270]  -> wp_fractional_scale_manager_v1@9.get_fractional_scale(new id wp_fractional_scale_v1@37, wl_surface@33)
[ 490907.277]  -> wl_surface@33.set_opaque_region(nil)
[ 490907.289]  -> xdg_toplevel@35.set_app_id("Alacritty")
[ 490907.293]  -> xdg_toplevel@35.set_title("Alacritty")
[ 490907.297]  -> xdg_toplevel@35.set_min_size(2, 1)
[ 490907.301]  -> xdg_toplevel@35.set_max_size(0, 0)
[ 490907.305]  -> xdg_toplevel@35.set_maximized()
[ 490907.308]  -> wl_surface@33.commit()
[ 490907.315]  -> wl_display@1.sync(new id wl_callback@38)
[ 490907.320] wl_keyboard@17.keymap(1, fd 18, 68422)
[ 490907.326] wl_keyboard@17.repeat_info(40, 186)
[ 490909.735] wl_display@1.delete_id(31)
[ 490909.839] wl_display@1.delete_id(38)
[ 490909.847] xdg_toplevel@35.configure_bounds(1920, 1048)
[ 490909.853] xdg_toplevel@35.wm_capabilities(array[16])
[ 490909.856] xdg_toplevel@35.configure(1920, 1048, array[24])
[ 490909.859] xdg_surface@34.configure(34)
[ 490909.862] wl_callback@38.done(1294)
[ 490909.871]  -> xdg_surface@34.ack_configure(34)
[ 490912.159]  -> wl_shm@11.create_pool(new id wl_shm_pool@38, fd 25, 1)
[ 490912.178]  -> wl_compositor@3.create_surface(new id wl_surface@31)
[ 490912.183]  -> wl_subcompositor@4.get_subsurface(new id wl_subsurface@39, wl_surface@31, wl_surface@33)
[ 490912.188]  -> wl_subsurface@39.set_sync()
[ 490912.191]  -> wl_compositor@3.create_surface(new id wl_surface@40)
[ 490912.195]  -> wl_subcompositor@4.get_subsurface(new id wl_subsurface@41, wl_surface@40, wl_surface@33)
[ 490912.198]  -> wl_subsurface@41.set_sync()
[ 490912.202]  -> wl_compositor@3.create_surface(new id wl_surface@42)
[ 490912.206]  -> wl_subcompositor@4.get_subsurface(new id wl_subsurface@43, wl_surface@42, wl_surface@33)
[ 490912.210]  -> wl_subsurface@43.set_sync()
[ 490912.214]  -> wl_compositor@3.create_surface(new id wl_surface@44)
[ 490912.219]  -> wl_subcompositor@4.get_subsurface(new id wl_subsurface@45, wl_surface@44, wl_surface@33)
[ 490912.223]  -> wl_subsurface@45.set_sync()
[ 490912.226]  -> wl_compositor@3.create_surface(new id wl_surface@46)
[ 490912.230]  -> wl_subcompositor@4.get_subsurface(new id wl_subsurface@47, wl_surface@46, wl_surface@33)
[ 490912.234]  -> wl_subsurface@47.set_sync()
[ 490929.602]  -> wl_surface@33.set_opaque_region(nil)
[ 490929.614]  -> xdg_surface@34.set_window_geometry(0, -35, 1920, 1048)
[ 490929.619]  -> wp_viewport@36.set_destination(1920, 1013)
[ 490929.627]  -> wl_surface@33.set_opaque_region(nil)
[0.046271414s] [INFO ] [alacritty] Window scale factor: 1
[ 490944.235]  -> zwp_linux_dmabuf_v1@32.get_surface_feedback(new id zwp_linux_dmabuf_feedback_v1@48, wl_surface@33)
[ 490944.249]  -> wl_display@1.sync(new id wl_callback@49)
[ 490944.917] wl_display@1.delete_id(49)
[ 490944.936] wl_callback@49.done(1294)
[ 490945.296] zwp_linux_dmabuf_feedback_v1@48.format_table(fd 25, 1360)
[ 490945.305] zwp_linux_dmabuf_feedback_v1@48.main_device(array[8])
[ 490945.307] zwp_linux_dmabuf_feedback_v1@48.tranche_target_device(array[8])
[ 490945.309] zwp_linux_dmabuf_feedback_v1@48.tranche_flags(0)
[ 490945.310] zwp_linux_dmabuf_feedback_v1@48.tranche_formats(array[170])
[ 490945.313] zwp_linux_dmabuf_feedback_v1@48.tranche_done()
[ 490945.317] zwp_linux_dmabuf_feedback_v1@48.done()
[0.063231280s] [INFO ] [alacritty] Running on Mesa Intel(R) Xe Graphics (TGL GT2)
[0.063259960s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.2-arch1.1, shader_version 4.60
[0.063266548s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.077126673s] [INFO ] [alacritty] Cell size: 9 x 22
[0.077150333s] [INFO ] [alacritty] Padding: 0 x 0
[0.077155027s] [INFO ] [alacritty] Width: 1920, Height: 1013
[0.077200866s] [INFO ] [alacritty] PTY dimensions: 46 x 213
[0.079444621s] [INFO ] [alacritty] Initialisation complete
[0.079467172s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(93847349877664)), event: Resized(PhysicalSize { width: 1920, height: 1013 }) }
[0.079478141s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(93847349877664)), event: Occluded(true) }
[ 490962.851]  -> wl_surface@31.attach(nil, 0, 0)
[ 490962.862]  -> wl_surface@31.commit()
[ 490962.865]  -> wl_surface@40.attach(nil, 0, 0)
[ 490962.867]  -> wl_surface@40.commit()
[ 490962.869]  -> wl_surface@42.attach(nil, 0, 0)
[ 490962.872]  -> wl_surface@42.commit()
[ 490962.875]  -> wl_surface@44.attach(nil, 0, 0)
[ 490962.877]  -> wl_surface@44.commit()
[ 490962.884]  -> wl_shm_pool@38.resize(268800)
[ 490962.905]  -> wl_shm_pool@38.create_buffer(new id wl_buffer@49, 0, 1920, 35, 7680, 0)
[ 490963.258]  -> wl_subsurface@47.set_sync()
[ 490963.271]  -> wl_surface@46.set_buffer_scale(1)
[ 490963.275]  -> wl_subsurface@47.set_position(0, -35)
[ 490963.278]  -> wl_surface@46.attach(wl_buffer@49, 0, 0)
[ 490963.285]  -> wl_surface@46.damage_buffer(0, 0, 2147483647, 2147483647)
[ 490963.288]  -> wl_surface@46.commit()
[0.079931403s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(93847349877664)), event: RedrawRequested }
[0.079943379s] [INFO ] [alacritty] winit event: AboutToWait
[0.079989834s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 328, tv_nsec: 2027976 }, requested_resume: None })
[0.080044283s] [INFO ] [alacritty] winit event: AboutToWait
[0.204433436s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 328, tv_nsec: 2153324 }, requested_resume: None })
[0.204469670s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(93847349877664))), payload: Terminal(Wakeup) })
[0.204488331s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(93847349877664)), event: RedrawRequested }
[0.204512366s] [INFO ] [alacritty] winit event: AboutToWait
[0.204527151s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 328, tv_nsec: 126599371 }, requested_resume: None })
[0.204534165s] [INFO ] [alacritty] winit event: AboutToWait
[0.548788890s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 328, tv_nsec: 126620001 }, requested_resume: None })
[0.548816555s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(93847349877664))), payload: Terminal(Title(kek@archbiz:~)) })
[0.548825358s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(93847349877664))), payload: Terminal(Wakeup) })
[0.548832309s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(93847349877664)), event: RedrawRequested }
[ 491432.521]  -> xdg_toplevel@35.set_title("kek@archbiz:~")
[0.549169990s] [INFO ] [alacritty] winit event: AboutToWait
[0.549191505s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 328, tv_nsec: 471257516 }, requested_resume: None })
[0.549198214s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(93847349877664))), payload: Terminal(Wakeup) })
[0.549216333s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(93847349877664))), payload: Terminal(Wakeup) })
[ 491432.583]  -> wl_surface@31.attach(nil, 0, 0)
[ 491432.587]  -> wl_surface@31.commit()
[ 491432.590]  -> wl_surface@40.attach(nil, 0, 0)
[ 491432.592]  -> wl_surface@40.commit()
[ 491432.596]  -> wl_surface@42.attach(nil, 0, 0)
[ 491432.598]  -> wl_surface@42.commit()
[ 491432.600]  -> wl_surface@44.attach(nil, 0, 0)
[ 491432.602]  -> wl_surface@44.commit()
[ 491432.609]  -> wl_shm_pool@38.resize(537600)
[ 491432.629]  -> wl_shm_pool@38.create_buffer(new id wl_buffer@50, 268800, 1920, 35, 7680, 0)
[ 491432.853]  -> wl_subsurface@47.set_desync()
[ 491432.858]  -> wl_surface@46.set_buffer_scale(1)
[ 491432.861]  -> wl_subsurface@47.set_position(0, -35)
[ 491432.865]  -> wl_surface@46.attach(wl_buffer@50, 0, 0)
[ 491432.868]  -> wl_surface@46.damage_buffer(0, 0, 2147483647, 2147483647)
[ 491432.872]  -> wl_surface@46.commit()
[0.549515074s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(93847349877664)), event: RedrawRequested }
[0.549525285s] [INFO ] [alacritty] winit event: AboutToWait
[0.549536869s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 328, tv_nsec: 471609640 }, requested_resume: None })
[0.549542599s] [INFO ] [alacritty] winit event: AboutToWait
[ 491433.292] wl_buffer@49.release()
[ 491433.298]  -> wl_buffer@49.destroy()
[ 491433.301] wl_buffer@50.release()
[ 491433.304]  -> wl_buffer@50.destroy()
```

**Comment by chrisduerr** [comment] 2024-01-01 18:52
@kekkoudesu Try latest master.

**Comment by kchibisov** [comment] 2024-01-01 19:30
Duplicate of #7465 

Fix gnome.

**Closed by kchibisov** 2024-01-01 19:30 UTC

**Comment by kekkoudesu** [comment] 2024-01-02 01:00
I read that issue before filing this one and it didn't click at all that it was the same thing :sweat_smile: 

Sorry. Upgrading and taking `startup_mode = "Maximized"` out of my config file works for now.
