### ISSUE TITLE
very small newlines cause text to overlap

### ISSUE THREAD

**Issue by Cynosure-null** [alacritty/alacritty#6057] opened 2022-05-11 20:22 UTC
Whenever I enter a newline, it is only a couple pixels down from the existing line and causes text to overlap.

### System

OS: OpenSUSE Tumbleweed
Version: 0.10.1
Linux: Wayland, KDE Plasma

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: SauceCodePro Nerd Font 10pt (changing font has no effect), Width: 800, Height: 600

Logs (-vv):
```Created log file at "/tmp/Alacritty-13046.log"
[0.000003663s] [INFO ] [alacritty] Welcome to Alacritty
[0.000052753s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000073112s] [INFO ] [alacritty] Running on Wayland
[0.000482306s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/laptop-main/.alacritty.yml"
[0.043501453s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.077040528s] [DEBUG] [alacritty] Estimated DPR: 1
[0.077095553s] [DEBUG] [alacritty] Estimated window size: None
[0.077101426s] [DEBUG] [alacritty] Estimated cell size: 9 x 1
[0.131612843s] [INFO ] [alacritty] Device pixel ratio: 1
[0.139661134s] [INFO ] [alacritty] Initializing glyph cache...
[0.149780255s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.190128825s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.228556723s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.267397522s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.311019042s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.17132732s
[0.311050839s] [INFO ] [alacritty] Cell size: 9 x 1
[0.311057265s] [INFO ] [alacritty] Padding: 0 x 0
[0.311061772s] [INFO ] [alacritty] Width: 800, Height: 600
[0.311904200s] [INFO ] [alacritty] PTY dimensions: 600 x 88
[0.315283148s] [INFO ] [alacritty] Initialisation complete
[0.330078721s] [DEBUG] [alacritty_terminal] New num_cols is 104 and num_lines is 471
[0.334686545s] [INFO ] [alacritty] Padding: 0 x 0
[0.334756530s] [INFO ] [alacritty] Width: 937, Height: 471
[6.312129934s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='p', params=[0], intermediates=[33]
[6.312266302s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='l', params=[3;4], intermediates=[63]
```
Logs (--print-events):
https://pastebin.mozilla.org/WuZPyC24

**Comment by Studiedlist** [comment] 2022-05-12 07:52
This bug is caused by incorrect cell size calculation for some fonts
Read https://github.com/alacritty/alacritty/issues/6048 for more

**Comment by chrisduerr** [comment] 2022-05-14 14:32
Closing as duplicate.

**Closed by chrisduerr** 2022-05-14 14:32 UTC
