### ISSUE TITLE
font selection and sizing from command line?

### ISSUE THREAD

**Issue by alexyuriev** [alacritty/alacritty#3185] opened 2020-01-11 03:33 UTC
This is really a question rather than a bug report.

Is there a reason why the selection of a font and its size cannot be done as a command line argument?  Granted, it is possible to create several config files that would specify the sizes and pass those, but it sounds so gross.

**Comment by chrisduerr** [comment] 2020-01-11 03:46
I'm going to close this as a duplicate of https://github.com/alacritty/alacritty/issues/1258, which is a bit more general, but does include the font and its size.

Generally if the font can be changed, we'd want everything else to be changeable too. Unfortunately adding flags for every little thing isn't really maintainable, since we'd have to add a new flag every time we modify the config and it would be very prone to breaking and messy code. So the goal is to create an interface that is a bit more general, but that also makes it more complex, which is why this hasn't been implemented yet.

**Closed by chrisduerr** 2020-01-11 03:46 UTC
