### ISSUE TITLE
Error: GLSL 3.30 is not supported 

### ISSUE THREAD

**Issue by gitmac777** [alacritty/alacritty#3624] opened 2020-04-21 20:28 UTC
Hello, use a ROCK64 single-board computer (RK3328 Quad-Core ARM Cortex A53 64-Bit Processor), ARM Mali-450MP2 Dual-core GPU, OpenGL ES 1.1 and 2.0, OpenVG1.1.

Alacritty had only ever worked with swrast driver (including input latency). 

**Now it doesn't work anymore after upgrade kernel to v5.6.2:** 
Alacritty encountered an unrecoverable error:
There was an error initializing the shaders: Failed compiling shader at /home/buildozer/aports/community/alacritty/src/alacritty-0.4.0/alacritty_terminal/../res/text.v.glsl: 0:14(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

**With MESA_GL_VERSION_OVERRIDE=3.3 and MESA_GLSL_VERSION_OVERRIDE=330:**
Alacritty encountered an unrecoverable error:
There was an error initializing the shaders: Failed linking shader: error: output location 0 >= GL_MAX_DUAL_SOURCE_DRAW_BUFFERS with index 1 for alphaMask

**Comment by chrisduerr** [comment] 2020-04-21 20:38
Seems like a duplicate of https://github.com/alacritty/alacritty/issues/128? Alacritty requires a GPU capable of running GLSL 3.30 or higher.

**Comment by gitmac777** [comment] 2020-04-21 21:27
I tested the recommendations from https://github.com/alacritty/alacritty/issues/128 and it didn't work, maybe I missed something? 
I am currently using sway and it does not start with LIBGL_ALWAYS_SOFTWARE=1.

**Comment by kchibisov** [comment] 2020-04-21 21:39
you should start just alacritty with `LIBGL_ALWAYS_SOFTWARE=1 alacritty` (not entire sway), seems to use SW for me. What error does it give to you with mentioned env var?

**Comment by gitmac777** [comment] 2020-04-21 21:48
Yes then it works fine. Shame on me

**Closed** 2020-04-21 21:50 UTC
Labels: A - needs repro, C - waiting on author

**Comment by rabitt88** [comment] 2021-11-29 16:05
How to set LIBGL_ALWAYS_SOFTWARE=1 alacritty as shortcut?

**Comment by scalarwaves** [comment] 2021-12-23 04:07
@rabitt88 In my sway config I have:
`set $term-float LIBGL_ALWAYS_SOFTWARE=1 alacritty`
`bindsym $mod+Return exec $term-float`

Now mod+ENTER loads alacritty

**Comment by dramosgo** [comment] 2021-12-24 05:25
Add it as environmental variable: edit (as root) /etc/environment and add:
LIBGL_ALWAYS_SOFTWARE=true
Save, logout and login back. Now you can run alacritty from everywhere.
Enjoy!

**Comment by SatouKuzuma1** [comment] 2022-05-01 09:39
@dramosgo after doing this: LIBGL_ALWAYS_SOFTWARE=true, and log out, when I boot up again I can-'t open alacritty. I have to run the command again. Is there any solution to this? I have the same problem with kitty.

**Comment by sskras** [comment] 2022-10-16 09:06
@SatouKuzuma1 commented [on May 1](#issuecomment-1114185320):

> @dramosgo after doing this: LIBGL_ALWAYS_SOFTWARE=true, and log out, when I boot up again I can-'t open alacritty. I have to run the command again. 

This is because the variable is lost when you close your current shell (terminal session).

> Is there any solution to this? I have the same problem with kitty.

You could set it from some automatic shell mechanisms (per-user or per-system).
Like one mentioned by @dramosgo [on Dec 24, 2021](#issuecomment-1000662067):

> Add it as environmental variable: **edit (as root) `/etc/environment` and add: `LIBGL_ALWAYS_SOFTWARE=true`** Save, logout and login back. Now you can run alacritty from everywhere. Enjoy!
