### ISSUE TITLE
LoadLibrary failed with error 87: The parameter is incorrect

### ISSUE THREAD

**Issue by prabirshrestha** [alacritty/alacritty#1976] opened 2019-01-06 01:33 UTC
This is what I get when I try to run Alacritty on windows from remote desktop in `Microsoft Windows [Version 10.0.17763.195]`

![image](https://user-images.githubusercontent.com/287744/50731032-d6f3e300-110f-11e9-8bc8-a2e3ebcfefb0.png)

I can try running in actual machine on windows on Monday and see if I still have the issue.

**Comment by zacps** [comment] 2019-01-07 01:40
What Alacrity version?

**Comment by prabirshrestha** [comment] 2019-01-07 02:18
https://github.com/jwilm/alacritty/releases/tag/v0.2.4-conpty I believe it started to happen earlier then that build.

**Comment by prabirshrestha** [comment] 2019-01-07 09:49
I only get this in console nothing else.

```
Configuration loaded from C:\Users\prshrest\alacritty.yml
```

I also tried removing my alacritty.yml and it re-created.

**Comment by prabirshrestha** [comment] 2019-01-25 01:54
So seems like this happens only when I'm opening alacrity from remote desktop.

**Comment by prabirshrestha** [comment] 2019-01-25 05:39
Here is another experiment I tired that works.

* Open alacritty in the main machine. Works.
* Remote in the main machine. I can continue use alacritty. But If i try to start a new alacritty instance it fails with the same error.

Seems like alacritty most likely need to special handle remote desktop cases.

**Comment by zacps** [comment] 2019-01-25 09:14
My guess based on the fact we don't get far into initialisation and some googling ([1](https://forums.adobe.com/thread/2551581)) is that this is an issue with the GL context initialisation.

Might be worth trying to run one of the [glutin examples](https://github.com/tomaka/glutin/tree/master/examples).

**Comment by chrisduerr** [comment] 2019-01-25 14:01
It would definitely be possible that glutin would work here but Alacritty doesn't, since Alacritty does do some additional GL stuff, but I agree with zacps that the best way forward would be to first test if this issue is due to winit or Alacritty.

**Comment by prabirshrestha** [comment] 2019-01-28 09:57
I get the same error when running glutin examples from remote desktop. So most likely glutin bug.

**Comment by zacps** [comment] 2019-01-29 05:46
@prabirshrestha Could you create an issue there? Then this issue can be used to track the fix in glutin.

**Comment by prabirshrestha** [comment] 2019-02-20 08:05
I don't think this is an issue with alacritty. I get the same error when using aminal remote desktop. It is another cross platform terminal emulator written in go with opengl. https://github.com/liamg/aminal/releases/tag/Nightly-2019-02-16-0ac4484

**Comment by rms2176** [comment] 2019-04-07 22:37
I encountered a similar error on a different software (a Windows store application) and it started directly after updating to Windows 10 October 2018 Update. It occurs on RDP only.

Googling around implied that it could be resolved by renaming an ATI driver DLL, or rolling back or uninstalling the display drivers but the problem persisted.

Maybe this isn't what you want to hear but I resolved it by removing the AMD video card from the machine and replacing it with an NVIDIA video card.

**Comment by jcrevier** [comment] 2019-09-06 23:53
I ran across this today. Also only occurs for me when running in an rdp session. Alacritty 0.3.0. Windows build 17763.

**Comment by FrankHeimes** [comment] 2020-03-14 09:05
Just for Googlers:
I just ran into the very same problem. My MFC/C++ application runs just fine on a PC with an ATI Radeon HD 2600 XT when run locally but it fails with the LoadLibrary call in atiglpxx.dll when run in an RDP session.

A TeamViewer session does work, however, even though the very same ati*.dll modules get loaded into the process space as usual.

So a software workaround is to use TeamViewer instead of RDP alpha.
(Yes, I still consider the Remote Desktop Server / Client software to be in an very early alpha state!)

**Comment by akovac35** [comment] 2020-03-16 12:19
On Windows 10: If running this app over a remote desktop and you have an AMD/ATI card, simply disable the real graphics card in Device Manager and restart the application (not the computer).

**Comment by Santos2393** [comment] 2020-03-19 20:31
> On Windows 10: If running this app over a remote desktop and you have an AMD/ATI card, simply disable the real graphics card in Device Manager and restart the application (not the computer).

Worked like magic. Thanks! Was struggling for a long time!

**Comment by axescot** [comment] 2020-08-18 15:20
> On Windows 10: If running this app over a remote desktop and you have an AMD/ATI card, simply disable the real graphics card in Device Manager and restart the application (not the computer).

What is the real graphics card? Does real graphics card = on board graphics card?

**Comment by akovac35** [comment] 2020-08-18 17:31
Remote desktop will create a virtual graphics card. So the real one should be disabled as a workaround for the reported error, which is caused by the real graphics card's drivers. Try updating them as well, if the card is still supported ;)

**Comment by Gr3at** [comment] 2021-09-20 12:48
@akovac35 the question now is: whether disabling the real adapter prevent any on-site user from logging in and using the desktop or will the real adapter be enabled in the absence of the (Microsoft) remote one. 

Do you have any info on this?

**Comment by akovac35** [comment] 2021-09-20 16:53
Real adapter will be disabled for the on site user as well.

**Comment by kchibisov** [comment] 2023-06-12 06:01
This will need a retest and a separate issue if it happens again.

**Closed by kchibisov** 2023-06-12 06:01 UTC
Labels: S - winit/glutin, B - crash, H - windows
