### ISSUE TITLE
link underline jumps to next link on hover while content is scrolling

### ISSUE THREAD

**Issue by 0000xFFFF** [alacritty/alacritty#8174] opened 2024-09-13 23:23 UTC
There is an issue with the link underline behavior during output scrolling. Specifically, when continuously printing 
links (e.g., via a script outputting URLs), and attempting to hover over a link to click it, the underline incorrectly jumps to the next link below. This issue occurs while the terminal content is actively scrolling and makes it difficult to select the desired link accurately.

![peek](https://github.com/user-attachments/assets/5d6f0cca-1f7d-4267-9039-59fd2a5dff9f)

### Steps to Reproduce:
1. Open Alacritty
2. Run a script that continuously outputs clickable links.
```sh
#!/bin/bash

while true; do
        d="$(date +%s)"
        echo "$d -- https://github.com/alacritty/alacritty"
        sleep 0.1
done
```
3. Scroll back up after content starts to scroll the terminal
4. Hover over link

### System
OS: arch linux
Version: alacritty 0.13.2 (bb8ea18e)

**Comment by chrisduerr** [comment] 2024-09-13 23:57
Works correctly at the bottom of the terminal, but not with a display offset. Could be a simple fix, I think this mainly just wasn't tested before. It does seem to open the right link at least.

**Comment by kchibisov** [comment] 2024-09-22 15:07
Duplicate of #7737

**Closed by kchibisov** 2024-09-22 15:07 UTC
Labels: B - bug
