### ISSUE TITLE
Noto Color Emoji just shows behind an opaque overlay

### ISSUE THREAD

**Issue by wimstefan** [alacritty/alacritty#3565] opened 2020-04-06 09:58 UTC
### System
OS: Gentoo Linux ~amd64
Version: alacritty 0.5.0-dev (13eb50d)
Linux/BSD: awesomewm on X11

### Logs
Font/Terminal size: `alacritty -vv`
```log
[2020-04-06 11:53:20.551164995] [INFO] Welcome to Alacritty
[2020-04-06 11:53:20.551213648] [INFO] Configuration loaded from "/home/swimmer/.config/alacritty/alacritty.yml"
[2020-04-06 11:53:20.557712200] [DEBUG] Estimated DPR: 1.875
[2020-04-06 11:53:20.557728373] [DEBUG] Estimated Cell Size: 12 x 34
[2020-04-06 11:53:20.557734091] [DEBUG] Estimated Dimensions: None
[2020-04-06 11:53:20.618619222] [INFO] Device pixel ratio: 1.875
[2020-04-06 11:53:20.621737855] [INFO] Initializing glyph cache...
[2020-04-06 11:53:20.633642627] [INFO] ... finished initializing glyph cache in 0.011891707s
[2020-04-06 11:53:20.633657294] [INFO] Cell Size: 12 x 34
[2020-04-06 11:53:20.633662446] [INFO] Padding: 28 x 28
[2020-04-06 11:53:20.633668996] [INFO] Width: 800, Height: 600
[2020-04-06 11:53:20.633989786] [INFO] PTY Dimensions: Line(16) x Column(62)
[2020-04-06 11:53:20.646243506] [INFO] Initialisation complete
[2020-04-06 11:53:20.695344689] [DEBUG] Term::resize dimensions unchanged
[2020-04-06 11:53:20.695373694] [INFO] Width: 800, Height: 600
[2020-04-06 11:53:36.587761095] [DEBUG] [Unhandled CSI] action='m', args=[4, 2], intermediates=[62]
[2020-04-06 11:53:36.671443186] [DEBUG] [Unhandled CSI] action='c', args=[0], intermediates=[62]
[2020-04-06 11:53:36.674852651] [DEBUG] [unhandled osc_dispatch]: [['1','2',],['%','p','1','%','s',],] at line 759
[2020-04-06 11:53:36.674960292] [DEBUG] [unhandled osc_dispatch]: [['1','2',],['%','p','1','%','s',],] at line 759
[2020-04-06 11:53:36.715060660] [DEBUG] [unhandled osc_dispatch]: [['1','2',],['%','p','1','%','s',],] at line 759
[2020-04-06 11:53:40.055146132] [DEBUG] [Unhandled CSI] action='m', args=[4, 0], intermediates=[62]
[2020-04-06 11:53:41.531375512] [INFO] Goodbye
```

Pictures say more than words in this case ... ;-)
![alacritty-faded-emojis](https://user-images.githubusercontent.com/4605934/78546431-ad87a280-77fd-11ea-9954-438a7cd3b0c6.png)

And this is the fonts.conf I'm using: 
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

    <!-- Add generic family. -->
    <match target="pattern">
        <test qual="any" name="family"><string>emoji</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <!-- This adds Noto Color Emoji as a final fallback font for the default font families. -->
    <match target="pattern">
        <test name="family"><string>sans</string></test>
        <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test name="family"><string>serif</string></test>
        <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test name="family"><string>sans-serif</string></test>
        <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test name="family"><string>monospace</string></test>
        <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test name="family"><string>Iosevka Artesanal</string></test>
        <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
    </match>

    <!-- Block Symbola from the list of fallback fonts. -->
    <selectfont>
        <rejectfont>
            <pattern>
                <patelt name="family">
                    <string>Symbola</string>
                </patelt>
            </pattern>
        </rejectfont>
    </selectfont>

    <!-- Use Noto Color Emoji when other popular fonts are being specifically requested. -->
    <match target="pattern">
        <test qual="any" name="family"><string>Apple Color Emoji</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Segoe UI Emoji</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Segoe UI Symbol</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Android Emoji</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Twitter Color Emoji</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Twemoji</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Twemoji Mozilla</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>TwemojiMozilla</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>EmojiTwo</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Emoji Two</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>EmojiSymbols</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

    <match target="pattern">
        <test qual="any" name="family"><string>Symbola</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
    </match>

</fontconfig>
```

**Comment by chrisduerr** [comment] 2020-04-06 13:33
Duplicate of https://github.com/alacritty/alacritty/issues/1864.

**Closed by chrisduerr** 2020-04-06 13:33 UTC

**Comment by wimstefan** [comment] 2020-04-06 14:54
Even though you closed this issue I might add that this problem only plays with light backgrounds ... using a dark background the emojis are fully shown.

**Comment by kchibisov** [comment] 2020-04-06 15:23
we're aware of that, this is due to blending.
