### ISSUE TITLE
programs run inside alacritty can spy on clipboard

### ISSUE THREAD

**Issue by Maan2003** [alacritty/alacritty#6990] opened 2023-06-11 08:54 UTC
First of all, thanks for Alacritty. It is awesome. 

Alacritty implements OSC 52 completely, which gives clipboard_load access. This is really bad for sandboxing and containers. 
To test this try `printf '\e]52;c;?\a'`

IMO clipboard_load should be disabled by default, And should be gated with config setting.

I have attached a patch that disables clipboard_load completely. 

[deny-clipboard_load.patch.txt](https://github.com/alacritty/alacritty/files/11714223/deny-clipboard_load.patch.txt)

**Comment by kchibisov** [comment] 2023-06-11 08:59
Duplicate of #3386

**Closed by kchibisov** 2023-06-11 08:59 UTC
