### ISSUE TITLE
The ^ character is typed as 6 inside (neo)vim

### ISSUE THREAD

**Issue by bronzehedwick** [alacritty/alacritty#4666] opened 2021-01-06 17:43 UTC
When using vim/neovim, typing <kbd>Ctrl-^</kbd> (which switches to the alternate buffer) does not work in alacritty, instead typing <kbd>Ctrl-6</kbd>. This does work in other terminal emulators (tested in terminal.app, kitty)

### System

OS: macOS
Version: found in `alacritty 0.6.0` and `alacritty  0.7.0-rc1` 

### Logs

Font/Terminal size:
```
Estimated DPR: 2
Estimated window size: Some(PhysicalSize { width: 1920, height: 1440 })
Estimated cell size: 24 x 48
Device pixel ratio: 2
Initializing glyph cache...
... finished initializing glyph cache in 0.040395899s
Estimated DPR correctly, skipping resize
Cell size: 24 x 48
Padding: 0 x 0
Width: 1920, Height: 1440
PTY dimensions: Line(30) x Column(80)
```
Keyboard and bindings: 
```
 glutin event: NewEvents(Init)
 glutin event: UserEvent(TerminalEvent(Title(fish /Users/delucac)))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawRequested(WindowId(Id(140402401619840)))
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689293375483 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Title(fish /Users/delucac)))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: Focused(true) }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689333998800 }, requested_resume: None })
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689338352438 }, requested_resume: None })
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689338547082 }, requested_resume: None })
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689351573825 }, requested_resume: None })
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689351693258 }, requested_resume: None })
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246689448046317 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 14, state: Pressed, virtual_keycode: Some(E), modifiers: (empty) }, is_synthetic: false } }
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: ReceivedCharacter('e') }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690779416125 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690782044742 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690783801929 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 14, state: Released, virtual_keycode: Some(E), modifiers: (empty) }, is_synthetic: false } }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690869095445 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 7, state: Pressed, virtual_keycode: Some(X), modifiers: (empty) }, is_synthetic: false } }
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: ReceivedCharacter('x') }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690974447839 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690974633366 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246690988504905 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691008034361 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 34, state: Pressed, virtual_keycode: Some(I), modifiers: (empty) }, is_synthetic: false } }
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: ReceivedCharacter('i') }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691086733469 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691088732348 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 7, state: Released, virtual_keycode: Some(X), modifiers: (empty) }, is_synthetic: false } }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691108564534 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 34, state: Released, virtual_keycode: Some(I), modifiers: (empty) }, is_synthetic: false } }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691196391568 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 17, state: Pressed, virtual_keycode: Some(T), modifiers: (empty) }, is_synthetic: false } }
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: ReceivedCharacter('t') }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691206135797 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691222749670 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 17, state: Released, virtual_keycode: Some(T), modifiers: (empty) }, is_synthetic: false } }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246691308832361 }, requested_resume: None })
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 36, state: Pressed, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
 glutin event: WindowEvent { window_id: WindowId(Id(140402401619840)), event: ReceivedCharacter('\r') }
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246693296297303 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246693296555406 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246693297992266 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Title(exit /Users/delucac)))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(WaitCancelled { start: Instant { t: 246693299814092 }, requested_resume: None })
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: UserEvent(TerminalEvent(Exit))
 glutin event: UserEvent(TerminalEvent(Wakeup))
 glutin event: MainEventsCleared
 glutin event: RedrawEventsCleared
 glutin event: NewEvents(Poll)
 glutin event: LoopDestroyed
```

**Comment by chrisduerr** [comment] 2021-01-07 03:17
Duplicate of #458.

**Closed by chrisduerr** 2021-01-07 03:17 UTC
