### ISSUE TITLE
feature request: backwards search in vim mode

### ISSUE THREAD

**Issue by sanga** [alacritty/alacritty#3523] opened 2020-03-26 06:59 UTC
Backwards search (bound to `#` in vim by default) would seem to be extremely useful to me - I guess the most common usecase I would have for vim mode would be: A bunch of output was printed to std-out/err that I can't easily get again and I'd like to grep back through it to see or extract some important text. I didn't notice anything about this in current master, so noting it here.

### System

OS: Linux
Version: `alacritty 0.5.0-dev (06c07d3)`
Linux: Wayland, Sway

**Comment by sanga** [comment] 2020-03-26 07:01
A semi related thing (that would solve this problem also) would be to allow opening the scrollback buffer in actual vim. I'm not familiar with the codebase so I don't know how easy/hard that might be but in principle if the scrollback buffer could be dumped out to a file then it should be pretty straight forward to just call vim on that file?

**Comment by kchibisov** [comment] 2020-03-26 07:06
duplicate of  #1017 and  #1615

**Closed by kchibisov** 2020-03-26 07:06 UTC
