### ISSUE TITLE
Opacity 1.0 does not make background completely opaque

### ISSUE THREAD

**Issue by BartXZX** [alacritty/alacritty#1927] opened 2018-12-27 12:30 UTC
Which operating system does the issue occur on?
Windows 10 build 17134.407 (1803).

I tested on 0.2.4 and the latest master (f018043) with the opacity setting on 1.0 and once more with it commented out. If you look to the right side you see a picture of Goku (my windows desktop background).

![opacity-example](https://user-images.githubusercontent.com/5583518/50480203-dace8980-09da-11e9-9f9c-15e288fc0371.png)

**Comment by BartXZX** [comment] 2019-02-27 10:42
Has anyone been able to verify/reproduce this?

**Comment by chrisduerr** [comment] 2019-02-27 11:10
I believe I was able to reproduce this on Windows, however it has been a while since I've used Windows and I never use transparency. I'd definitely consider this confirmed though, I'm just not sure if it's an issue on ALL Windows systems (I ran it on Win 7).

**Comment by BartXZX** [comment] 2019-02-27 12:02
I don't want to use transparancy either. Is there a way besides the opacity setting to completely disable it? That would be a sufficient workaround for me at least.

**Comment by benpye** [comment] 2019-03-28 07:08
I am seeing this too on Windows 10 with 77536e8fac303c1954d40e2db2bd083716b04a29. If I put the Alacritty Window over something dark I can see a "shadow".

**Comment by benpye** [comment] 2019-03-28 07:18
Aha! https://github.com/tomaka/winit/blob/master/src/platform/windows/window.rs#L680 - winit is overriding our full opacity with almost full opacity. Perhaps it would be worth checking for full opacity at start and creating an opaque window if the user has set the opacity to 1.0? This would be a simple change at https://github.com/jwilm/alacritty/blob/master/src/window.rs#L301 but it would mean that changing from opacity = 1.0 to opacity < 1.0 would require a restart, and vice versa.

**Comment by chrisduerr** [comment] 2019-03-28 13:46
> Perhaps it would be worth checking for full opacity at start and creating an opaque window if the user has set the opacity to 1.0?

While this would resolve some issues, I'm really not a fan of making less things auto-reload. I personally use the live reload a ton for testing and it was one of the first things I noticed which are really cool about Alacritty.

In general I'd say the same thing about this that I've already mentioned on other issues. It would be nice to fix this issue rather than building a hack on top of a hack.

> I think the proper change would be to set/unset WS_EX_LAYERED based on the opacity value. This isn't something exposed by winit but can be done with https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowlonga if we can get the HWND. This does break the abstraction offered by winit somewhat, but it would be nice to get this fixed.

We should go through winit and if necessary fixes should be made in winit. Trying to mess with these things in Alacritty is just going to cause trouble and require ugly platform-specific code.

**Comment by stianeklund** [comment] 2019-10-29 07:45
Adding a gif of the issue for reference. `alacritty 0.3.3 (cc3e4d3)`

![2019-10-29_08-43-42](https://user-images.githubusercontent.com/4148195/67747071-39fc9080-fa28-11e9-8384-db6e3e32c916.gif)

**Comment by davidhewitt** [comment] 2020-06-04 07:40
I recently ran across this issue. For me, turning off HDR for the monitor "fixed" the issue. Can anyone else having issues with this confirm if that also resolves it for them?

**Comment by stianeklund** [comment] 2020-06-04 09:37
@davidhewitt  I don't have HDR on my monitor and it's an issue here.

**Comment by jimporter** [comment] 2020-07-09 21:24
For those who are interested, I filed a PR to fix this in winit: https://github.com/rust-windowing/winit/pull/1621. Hopefully my patch is correct and lands/gets released soon so this problem can go away. :)

**Comment by jimporter** [comment] 2020-10-14 19:42
My PR for winit (rust-windowing/winit#1621) just merged, so the next release from them should resolve this issue.

**Closed** 2020-12-11 00:40 UTC
Labels: A - deps, B - bug, H - windows, S - transparency, S - winit/glutin
