### ISSUE TITLE
[feature request] support symbol_map like in kitty

### ISSUE THREAD

**Issue by hronro** [alacritty/alacritty#5128] opened 2021-05-15 12:46 UTC
![CleanShot 2021-05-15 at 20 45 02@2x](https://user-images.githubusercontent.com/15059605/118361532-7ec22b00-b5be-11eb-9191-14019179ee0e.png)

Reference: https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.symbol_map

**Comment by chrisduerr** [comment] 2021-05-15 16:03
Basically a duplicate of #957, though I'm not sure if that's going to get implemented since that's really something that should be provided by your font system, not every single application using it.

**Closed by chrisduerr** 2021-05-15 16:03 UTC

**Comment by hronro** [comment] 2021-05-16 10:32
#957 was opened more than 3 years ago and is still opened, can I understand this as this feature (or anything else about font configuration) will not be implemented soon?
