### ISSUE TITLE
Alacritty 0.7.1 Crashes with segmentation fault (core dumped)

### ISSUE THREAD

**Issue by asahaf** [alacritty/alacritty#4702] opened 2021-01-14 08:51 UTC
Alacritty 0.7.1 Crashes with segmentation fault (core dumped)

### System
OS: Linux (Arch Linux)
Arch Kernel Version: 5.10.5-arch1-1
GPU: Radeon RX 5500 XT
Graphics Driver: mesa/radeonsi (amdgpu)
Version: alacritty 0.7.1 (a852eb85)
Compositor: Wayland
WM: Sway

### Logs

```
[2021-01-14 11:36:45.953454811] [INFO ] [alacritty] Welcome to Alacritty
[2021-01-14 11:36:45.953517510] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/asahaf/.config/alacritty/alacritty.yml"
[2021-01-14 11:36:45.962519957] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:45.965722088] [DEBUG] [alacritty] Estimated DPR: 2
[2021-01-14 11:36:45.965747015] [DEBUG] [alacritty] Estimated window size: None
[2021-01-14 11:36:45.965759809] [DEBUG] [alacritty] Estimated cell size: 18 x 36
[2021-01-14 11:36:46.012668985] [INFO ] [alacritty] Device pixel ratio: 1
[2021-01-14 11:36:46.015379675] [INFO ] [alacritty] Initializing glyph cache...
[2021-01-14 11:36:46.017141238] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.019628786] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.022102768] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.024598881] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.033362818] [INFO ] [alacritty] ... finished initializing glyph cache in 0.017970559s
[2021-01-14 11:36:46.033377155] [INFO ] [alacritty] Cell size: 9 x 18
[2021-01-14 11:36:46.033382044] [INFO ] [alacritty] Padding: 0 x 0
[2021-01-14 11:36:46.033385641] [INFO ] [alacritty] Width: 800, Height: 600
[2021-01-14 11:36:46.035164698] [INFO ] [alacritty] PTY dimensions: Line(33) x Column(88)
[2021-01-14 11:36:46.041024938] [INFO ] [alacritty] Initialisation complete
[2021-01-14 11:36:46.048512499] [DEBUG] [alacritty_terminal] New num_cols is 213 and num_lines is 57
[2021-01-14 11:36:46.049160626] [INFO ] [alacritty] Padding: 0 x 0
[2021-01-14 11:36:46.049166797] [INFO ] [alacritty] Width: 1918, Height: 1030
[2021-01-14 11:36:46.051905039] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.054212967] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.056571781] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.058999104] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[2021-01-14 11:36:46.060019275] [INFO ] [alacritty] Font size changed to Size(22) with DPR of 2
[2021-01-14 11:36:46.063103953] [INFO ] [alacritty] Cell size: 18 x 36
[2021-01-14 11:36:46.063115975] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[2021-01-14 11:36:46.063122007] [INFO ] [alacritty] Padding: 0 x 0
[2021-01-14 11:36:46.063125353] [INFO ] [alacritty] Width: 3836, Height: 2060
[2021-01-14 11:36:46.136044824] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1',],['~',],] at line 813
[2021-01-14 11:36:46.141384209] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[1]    16694 segmentation fault (core dumped)  alacritty -vv
```
 ### Core dump
```
systemd-coredump[3549]: Process 2737 (alacritty) of user 1000 dumped core.
                                             
                                             Stack trace of thread 2772:
                                             #0  0x00007ffbd9b3f7b0 wl_list_insert (libwayland-client.so + 0xa7b0)
                                             #1  0x00007ffbd9b3c94b wl_display_read_events (libwayland-client.so + 0x794b)
                                             #2  0x00007ffbd9b3cecc wl_display_dispatch_queue (libwayland-client.so + 0x7ecc)
                                             #3  0x00007ffbd9b3d160 wl_display_roundtrip_queue (libwayland-client.so + 0x8160)
                                             #4  0x0000559385370f6e n/a (alacritty + 0x330f6e)
                                             #5  0x0000559385354adc n/a (alacritty + 0x314adc)
                                             #6  0x000055938534f68a n/a (alacritty + 0x30f68a)
                                             #7  0x00005593853a8c1a n/a (alacritty + 0x368c1a)
                                             #8  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #9  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2758:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2767:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2769:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2768:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2753:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2756:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2755:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2759:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2761:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2770:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2773:
                                             #0  0x00007ffbd97795de epoll_wait (libc.so.6 + 0x1005de)
                                             #1  0x0000559385289dcf n/a (alacritty + 0x249dcf)
                                             #2  0x0000559385288e27 n/a (alacritty + 0x248e27)
                                             #3  0x0000559385155314 n/a (alacritty + 0x115314)
                                             #4  0x000055938509485a n/a (alacritty + 0x5485a)
                                             #5  0x00005593853a8c1a n/a (alacritty + 0x368c1a)
                                             #6  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #7  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2739:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2742:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2737:
                                             #0  0x00007ffbd99929b7 __pthread_clockjoin_ex (libpthread.so.0 + 0xa9b7)
                                             #1  0x00005593853568c3 n/a (alacritty + 0x3168c3)
                                             #2  0x00005593851928cb n/a (alacritty + 0x1528cb)
                                             #3  0x0000559385097b03 n/a (alacritty + 0x57b03)
                                             #4  0x00005593851eb38c n/a (alacritty + 0x1ab38c)
                                             #5  0x00005593851e93f3 n/a (alacritty + 0x1a93f3)
                                             #6  0x0000559385174eb3 n/a (alacritty + 0x134eb3)
                                             #7  0x00005593851e4035 n/a (alacritty + 0x1a4035)
                                             #8  0x00007ffbd96a1152 __libc_start_main (libc.so.6 + 0x28152)
                                             #9  0x000055938509309e n/a (alacritty + 0x5309e)
                                             
                                             Stack trace of thread 2744:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2754:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2746:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2748:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2745:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2752:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2740:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2750:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2738:
                                             #0  0x00007ffbd9773d5d syscall (libc.so.6 + 0xfad5d)
                                             #1  0x000055938521670a n/a (alacritty + 0x1d670a)
                                             #2  0x0000559385217250 n/a (alacritty + 0x1d7250)
                                             #3  0x00005593853a8c1a n/a (alacritty + 0x368c1a)
                                             #4  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #5  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2741:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2763:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2765:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2747:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2764:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2751:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2762:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2749:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2760:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2757:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2766:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
                                             
                                             Stack trace of thread 2743:
                                             #0  0x00007ffbd99976a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                                             #1  0x00007ffbd2d1e52c n/a (radeonsi_dri.so + 0x4ed52c)
                                             #2  0x00007ffbd2d1ccf8 n/a (radeonsi_dri.so + 0x4ebcf8)
                                             #3  0x00007ffbd99913e9 start_thread (libpthread.so.0 + 0x93e9)
                                             #4  0x00007ffbd9779293 __clone (libc.so.6 + 0x100293)
░░ Subject: Process 2737 (alacritty) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 2737 (alacritty) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
```

**Comment by chrisduerr** [comment] 2021-01-14 08:56
There seem to be a lot of mentions of `radeonsi_dri` in your backtrace. Which means that this looks very much like a driver bug.

Does this crash at startup, or during usage? Also a core dump with debug symbols would probably be more useful.

**Comment by asahaf** [comment] 2021-01-14 08:57
@chrisduerr it crashes when I close it actual, not on startup, not during usage

**Comment by chrisduerr** [comment] 2021-01-14 08:58
Can you reproduce this? Like does Alacritty **always** coredump when closing it?

**Comment by asahaf** [comment] 2021-01-14 08:59
yes, it always happens. it started with version 0.7.1.

**Comment by chrisduerr** [comment] 2021-01-14 09:00
Can you provide the coredump with debug symbols? And if it started with version 0.7.1, can you verify that previous versions worked correctly?

**Comment by asahaf** [comment] 2021-01-14 09:40
I just double checked version 0.6, it works fine. 
I've tried to debug version 0.7.1. please check the attached debug.log file
[debug.log](https://github.com/alacritty/alacritty/files/5813538/debug.log)

**Comment by chrisduerr** [comment] 2021-01-14 14:41
Could you bisect the exact version that broke this?

**Comment by chrisduerr** [comment] 2021-01-14 16:42
See upstream issue: https://github.com/Smithay/smithay-clipboard/issues/32

**Comment by asahaf** [comment] 2021-01-14 17:58
@chrisduerr Thanks

**Comment by asahaf** [comment] 2021-01-16 12:13
@chrisduerr I've included stacktrace, let me if this is useful 
[alacritty_stacktrace.log](https://github.com/alacritty/alacritty/files/5824346/alacritty_stacktrace.log)

**Comment by chrisduerr** [comment] 2021-01-17 09:48
See this patch for a minimal fix:

https://github.com/Smithay/smithay-clipboard/issues/32#issuecomment-761757708

**Comment by aleprovencio** [comment] 2021-01-18 20:15
Yeah, this also happens to me when using `alacritty -t some_window_name` and there's a `for_window` rule defined for `some_window_name` on `sway`'s configuration.

**Comment by chrisduerr** [comment] 2021-01-18 20:48
> Yeah, this also happens to me when using alacritty -t some_window_name and there's a for_window rule defined for some_window_name on sway's configuration.

What exactly do you mean by that? It happens when you *start* Alacritty?

This bug should only occur when Alacritty is closed.

**Comment by aleprovencio** [comment] 2021-01-18 20:54
@chrisduerr yeah, the segmentation fault happens when I close it, if I have started alacritty under my described conditions

**Comment by ne9z** [comment] 2021-01-22 09:52
Also present on a system using Sway WM and Intel Graphics. Downgrading to 0.6 fixed this issue.

[alacritty_0.7.1_coredump.txt](https://github.com/alacritty/alacritty/files/5854959/alacritty_0.7.1_coredump.txt)

**Comment by aleprovencio** [comment] 2021-01-26 19:01
Guys I have some input on this.

I realized that this only happens to me when on a multimonitor setup, i.e. there's no issue when there's just the laptop.

When I plug an external monitor to my laptop, run `sway`, and:
    * change the focus to this external monitor
    * run an `alacritty` instance
    * inside this instance, run another with `alacritty -t window_name`
    * exit this last instance
    * PROFIT - no issues still

Issue only occurs if somewhere in this described test, with focus on the laptop (primary) monitor, I either try to:
    * switch workspaces
    * open an `alacritty` instance

If this happens, it will also affect the external monitor. It won't freeze any display though, as on #4725

**Comment by chrisduerr** [comment] 2021-01-26 20:44
I'm going to lock this issue because the discussion here is completely pointless. The issue has already been identified, please stop posting things unless you actually want to work on it.

**Comment by chrisduerr** [comment] 2021-01-26 23:05
https://github.com/alacritty/alacritty/pull/4742 should fix this. Please let me know if you can still reproduce it.

**Closed** 2021-01-29 22:41 UTC
Labels: B - bug, B - crash, D - easy, help wanted
