### ISSUE TITLE
Noticing Frequent Lack Of UI Update On Activity

### ISSUE THREAD

**Issue by thegranddesign** [alacritty/alacritty#5728] opened 2021-12-28 22:36 UTC
Hey all!  Thank you for such an amazing emulator. :heart: I also love the "anti-feature" list (eg no tabs, etc).

I have been noticing (I migrated from macOS (and iTerm2) to Linux) that since I switched to Alacritty, I'm getting many instances where, when I type something, there's no UI update until I press another keystroke.  Let me explain:

This might mean that typing:

```
> ls -la
```

might result in the screen showing:

```
> ls -l
```

however on the next key press (let's say I type `a` again because I don't see it on screen) results in the screen displaying:

```
> ls -laa
```

I'm assuming this is going to take some debugging on my part but I was curious if you all had any prior knowledge of a bug like this as well as what I can do to track down what needs to happen to help you all resolve it.

Thank you!

### System

OS: Linux
Version: 0.9.0
Linux/BSD: X11?

**Comment by bwot** [comment] 2021-12-29 14:07
Getting the same on macOS lately. alacritty 0.9.0 (fed349a)

**Comment by chrisduerr** [comment] 2021-12-29 22:22
For X11 there's https://github.com/alacritty/alacritty/issues/824, which I have no idea where it comes from and can't reproduce (turning the compositor on/off might help?). On Wayland there's https://github.com/alacritty/alacritty/issues/5174 which seems IME related so it can be fixed by the user (but sounds like you're on X11?).

> Getting the same on macOS lately. alacritty 0.9.0

On macOs I've never heard of this.

**Closed by chrisduerr** 2021-12-29 22:22 UTC

**Comment by thegranddesign** [comment] 2021-12-30 17:20
@chrisduerr while I fully understand the need to triage issues and make sure that things don't get out of hand, please don't be so quick to dismiss this issue.  The issues you linked to are describing a different behavior.

Issue #824 and #2217

These issue are saying that in the _middle_ of a redraw, the screen will hang.  Example: "opening vim" or doing a long directory listing.  That's not what I'm describing and I _never_ see that behavior on my system.  What I am seeing _only_ happens with single key presses.

Issue #5174 

I can confirm that I'm on X11 but this Wayland issue is saying that it's "swallowing" key presses and I don't see that behavior either.  The key press is still present (whether invisible due to a lack of redraw or still in the buffer due to a lack of a buffer flush) and appears once I press another key.

The issue that I'm having is that a specific keypress (at random but frequent intervals) _does not_ cause the screen to redraw.

**Comment by thegranddesign** [comment] 2021-12-30 17:21
@bwot can you confirm the subtle difference here is what you're seeing as well?  Is your issue more like #824, #5174, or what I described above?

**Comment by chrisduerr** [comment] 2021-12-30 17:23
Sounds like the vsync issue some drivers have, should also have an issue on the tracker somewhere. In that case I recommend just using Wayland.

**Comment by thegranddesign** [comment] 2021-12-30 17:28
I'm on PopOS and X11 is the primary supported system as of now.  Additionally there are issue with Wayland and the NVIDIA drivers in general.

**Comment by bwot** [comment] 2021-12-30 18:30
@thegranddesign it is exactly as you describe it. Haven't noticed anything else, it's only my own input.

macOS version 12.0.1 macbook pro 16" 2019 if that matters. Not like I can get rid of it with a switch to wayland anyway.

**Comment by chrisduerr** [comment] 2021-12-30 19:02
You don't get any output in `alacritty --print-events | grep "WindowEvent.*KeyboardInput"` either when this happens, right? I think that was the issue last time?

**Comment by thegranddesign** [comment] 2021-12-31 01:46
I'm currently testing switching to solely NVIDIA drivers (vs Intel integrated graphics) to see if that makes a difference.  So far I have not seen the issue arise but it may just be more intermittent.  I'll post back here in a day or two once I have more data.

**Comment by thegranddesign** [comment] 2022-06-02 04:20
For what it's worth, this is still happening.  It went away for a while when I switched to NVIDIA drivers but now it happens pretty much all the time.  I have absolutely no idea what to do to debug this.

@chrisduerr I am seeing this primarily while in tmux now.  When I use `alacritty --print-events | grep "WindowEvent.*KeyboardInput"` I'm not seeing it happen in the instance that pops up.

**Comment by thegranddesign** [comment] 2022-06-02 04:21
To be clear I don't know if tmux interaction is causing anything but this problem seems to avoid every attempt at tracking it down.

**Comment by ajukraine** [comment] 2022-06-25 11:16
Do we have an existing issue for MacBook environment?

**Comment by Derrekito** [comment] 2024-10-01 15:44
> Do we have an existing issue for MacBook environment?

I'm seeing the same issue in MacBook. I am using tmux, but I'm unsure if that's relevant.
