### ISSUE TITLE
MacOS Command key state isn't updated

### ISSUE THREAD

**Issue by nshahan** [alacritty/alacritty#3452] opened 2020-03-13 19:55 UTC
### System

OS: macOS
Version: alacritty 0.4.1 (4d9253b)

### Issue
Switching away from alacritty and returning using `Command`+`Tab` sometimes causes the alacritty to believe the `Command` key is still depressed. In some ways this is similar to #2475 but I am a daily user of alacritty and I immediately started noticing this issue on my recent update from v0.3.3 to v0.4.1.

The way to trigger this is to "slow" `Command`+`Tab` away from alacritty. By that I mean: 
1) Press `Command`+`Tab` and release `Tab` but keep `Command` pressed. This should open an application switching view.
2) Tap the `Tab` key to cycle between open applications. 
3) Release the `Command` key to switch to the application selected in the switcher (something other than alacritty).
4) Now return to alacritty either with a regular "fast" `Command`+`Tab` (not opening the application switcher view) or by using the mouse.
5) The `Command` key is now in a depressed state in alacritty.

This compounds with another open issue #3426 because now if I press `q` alacritty instantly quits even though my fingers are not touching the `Command` key.

**Comment by kchibisov** [comment] 2020-03-13 19:57
duplicate of #3188 
Fixed on the latest master.

**Closed by kchibisov** 2020-03-13 19:57 UTC
