### ISSUE TITLE
Colors are rendered incorrectly

### ISSUE THREAD

**Issue by simplelife2010** [alacritty/alacritty#4939] opened 2021-04-04 18:08 UTC
### System

OS: macOS
Version: alacritty 0.7.2 (5ac8060)

### Steps to reproduce

- Under System Preferences, choose or check your Color Profile (sRGB)
- Disable True Tone under your Mac's Display options
- Start Alacritty and 1 or 2 other Terminal emulators (Terminal.app, iTerm2)
- Make sure the windows are not overlapped by shadows from other windows
- Use the same color scheme (Solarized Light) in all Terminal Emulators
- If using Terminal.app, make sure the same color profile is selected as for your Display when choosing RGB colors
- Open Color Picker (launch-colorpicker)
- Set the color picker to the same color profile as your display (sRGB)
- Set the color picker to display RGB values
- Choose a color from the color scheme that you want to check (Background color: #fdf6e3)
- Check Alacritty and the other Terminal emulators with the color picker: Is the color rendered correctly?

### Expected result

- Color picker shows same RBG value (#fdf6e3)

### Acutal result

- Alacritty: FEF6E1
- iTerm2: FDF6E3
- Terminal.app: FDF6E3
- MacVim: FDF6E3

Comment: Same problem when checking if foreground colors are correct. Red for example is rendered correctly to DC322F in iTerm2, but to EF0C20 in Alacritty, where the difference is clearly visible. Same problem when using other Color Profiles.

**Comment by simplelife2010** [comment] 2021-04-04 18:33
Correction: When using a P3 Profile, the color values are almost matching in Alacritty. I get the impression that Alacritty color settings is somehow bound to the P3 Profile. Can you confirm that?

In iTerm and Terminal.app the default seems to be sRGB, but can be changed to a different profile if needed.

**Comment by nixpulvis** [comment] 2021-04-04 19:35
Looks like this was requested before, but closed by the author in #1599. There also seems to have been a bit of work around sRGB formats before to appease some systems in 6debc4f33.

> I get the impression that Alacritty color settings is somehow bound to the P3 Profile. Can you confirm that?

I wouldn't say we're mapped to it so much as we just don't do any conversions (assuming `with_srgb(false)` worked) with OpenGL. Since I doubt we would want alacritty having to deal with color spaces itself, I actually wonder if this is the right default. It seems like it could be the simplest default to get _some_ color to be rendered, but it seems to me that it could easily render the wrong colors, as others have mentioned.

I would personally be curious what systems calling `create_gl_window` fails with either sRGB as `true` or `false`, since on my machine it seems to work fine with either. I would also be curious to know what our stance on color profiles is exactly. I would think that if we can serve colors in the same space as other applications without implementing any conversions ourselves, this would be a nice win.

**Comment by simplelife2010** [comment] 2021-04-04 21:11
I agree this would be nice, although I cannot contribute development-wise. Here is an issue in another project dealing with something similar: https://github.com/chriskempson/tomorrow-theme/issues/269

It seems sRGB is considered the default. For the moment, I have converted Solarized like this to ensure it is rendered by Alacritty identically to the other applications on my system using Solarized:

```
# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fcf6e5' # base3
    foreground: '#697a82' # base00

  # Cursor colors
  cursor:
    text:   '#fcf6e5' # base3
    cursor: '#697a82' # base00

  # Normal colors
  normal:
    black:   '#163541' # base02
    red:     '#cb4239' # red
    green:   '#89972d' # green
    yellow:  '#af8a2d' # yellow
    blue:    '#458bcc' # blue
    magenta: '#c34580' # magenta
    cyan:    '#519f98' # cyan
    white:   '#ede8d7' # base2

  # Bright colors
  bright:
    black:   '#002a35' # base03
    red:     '#bd5329' # orange
    green:   '#5c6d74' # base01
    yellow:  '#697a82' # base00
    blue:    '#869496' # base0
    magenta: '#6c73be' # violet
    cyan:    '#96a1a1' # base1
    white:   '#fcf6e5' # base3
```

**Comment by simplelife2010** [comment] 2021-04-05 11:30
This seems to resolve my issues, but no idea if I am breaking anything else:
```
diff --git a/alacritty/src/display/window.rs b/alacritty/src/display/window.rs
index 7302c68..53e2602 100644
--- a/alacritty/src/display/window.rs
+++ b/alacritty/src/display/window.rs
@@ -186,7 +186,7 @@ impl Window {
         let is_wayland = false;
 
         let windowed_context =
-            create_gl_window(window_builder.clone(), &event_loop, false, !is_wayland, size)
+            create_gl_window(window_builder.clone(), &event_loop, true, !is_wayland, size)
                 .or_else(|_| {
                     create_gl_window(window_builder, &event_loop, true, !is_wayland, size)
                 })?;
```

**Comment by marcelbeumer** [comment] 2021-04-25 12:46
Having the same issue on macOS with Alacritty 0.7.2 (5ac8060). I don't know anything about OS color profiles and what to default to, but would also like the colors to match iTerm2, Kitty and MacVim.

**Comment by simplelife2010** [comment] 2021-04-25 14:54
@marcelbeumer Which version of macOS?
I just upgraded to Big Sur and my first impression is that the problem is gone.

**Comment by marcelbeumer** [comment] 2021-04-25 15:10
@simplelife2010 latest, macOS 12.2.3 on a MacBook Pro (16-inch, 2019; no external display)

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/111366/115998780-29ab7e80-a5e9-11eb-8307-955e2ed64539.png">

**Comment by marcomayer** [comment] 2021-08-16 07:31
I guess this explains why colors look the same between iterm2/alacritty on my external display using a color profile (DELL) and not the same on the macbooks retina display (latest mbp 16").

**Comment by PetrusZ** [comment] 2022-02-03 09:06
I think I have same issue, kitty's color is more bright than others.

**Comment by kchibisov** [comment] 2022-03-24 22:32
Could you try the latest master? I think the colors should match on srgb displays now?

**Comment by marcelbeumer** [comment] 2022-03-26 21:03
Sorry, still the same situation, built Alacritty from source (b16fe125). Topleft kitty, bottomleft: iterm2, bottomright: alacritty. Different MacBook and macOS this time: mbp 16" m1pro, macOS 12.3
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/111366/160256895-930fc89b-e158-42be-b76c-ea39e6bd6d13.png">

**Comment by kchibisov** [comment] 2022-03-26 21:09
Do you see any difference before and after that patch? Also, could you compare colors in the config to the ones color picker is showing?

**Comment by marcelbeumer** [comment] 2022-03-26 21:42
Interesting. My neovim color scheme sets `#ff9e64` as the orange. Used both pixelmator and macOS color picker to pick the colors. It's a bit confusing, but it seems as if all software mentioned applies a/the color profile, and alacritty does not?

alacritty: `#FF9E64` (same as colorscheme but different from other terminals and the browser)
kitty: `#F1A26F`
iterm2: `#F1A26F`
github color preview of `#ff9e64` (in this comment): `#F1A26F`
css color `#ff9e64` in safari (changed color github comment button): `#F1A26F`

alacritty-b16fe125.png:
<img width="219" alt="alacritty-b16fe125" src="https://user-images.githubusercontent.com/111366/160257656-9e3e0ae0-a74e-4d44-b479-ccbd3d5feade.png">

alacritty-f4bdf5fb.png:
<img width="202" alt="alacritty-f4bdf5fb" src="https://user-images.githubusercontent.com/111366/160257662-56f77fa1-3402-4560-844e-c3c270a7712a.png">

kitty.png:
<img width="208" alt="kitty" src="https://user-images.githubusercontent.com/111366/160257665-747b3092-13bd-47aa-a9f1-7327edcaa9ec.png">

iterm2.png
<img width="168" alt="iterm2" src="https://user-images.githubusercontent.com/111366/160257779-cb46d737-91cc-4cc5-87a6-322c8571d746.png">

github-color.png
<img width="96" alt="github-color" src="https://user-images.githubusercontent.com/111366/160257818-5c62e0e3-beaa-4451-8719-a5c3beb175e1.png">

safari-css.png:
<img width="142" alt="safari-css" src="https://user-images.githubusercontent.com/111366/160257883-89084cd9-c718-4af6-bc02-4381a664aeea.png">

**Comment by kchibisov** [comment] 2022-03-26 21:46
And you're sure that you're running master binary from e.g. terminal and previous version of alacritty provides the same color?

**Comment by kchibisov** [comment] 2022-03-26 21:47
And I can say for sure that colors of master and `v0.10.1` do differ on macOS builtin laptop displays.

**Comment by marcelbeumer** [comment] 2022-03-26 21:49
Moment, making sure w/ clean checkouts and builds

**Comment by marcelbeumer** [comment] 2022-03-26 21:55
clean git clone, checkout b16fe125
separate git clone, checkout f4bdf5fb
downloaded release 0.10.1
<img width="193" alt="alacritty-f4bdf5fb" src="https://user-images.githubusercontent.com/111366/160258334-600380d7-2d69-4559-88fc-2b476668dbc8.png">

<img width="196" alt="alacritty-0 10 1" src="https://user-images.githubusercontent.com/111366/160258331-e16e4db3-f258-4cf1-8361-52e03df9d0ab.png">
<img width="201" alt="alacritty-b16fe125" src="https://user-images.githubusercontent.com/111366/160258332-f5eaab76-819b-4136-9391-956abf138287.png">

**Comment by Saklad5** [comment] 2022-03-28 21:49
The issue here is that Alacritty is using the native color space, not the P3 color space. For everything short of a reference display (latest MacBook Pro, Pro Display XDR, etc.), those are not identical. Moreover, not everyone is using displays with the same color space.

The solution is quite simple, and iTerm 2 does it already: every color code should specify a color space, with an ill-advised fallback to sRGB if left empty.

**Comment by Saklad5** [comment] 2022-03-28 22:32
> clean git clone, checkout [b16fe12](https://github.com/alacritty/alacritty/commit/b16fe1259cebcd6adb4bc92f7025beb696412b89): separate git clone, checkout [f4bdf5f](https://github.com/alacritty/alacritty/commit/f4bdf5fb36fdf3b329be8253da39050abe7238a5) downloaded release 0.10.1
> 
> <img alt="alacritty-f4bdf5fb" width="193" src="https://user-images.githubusercontent.com/111366/160258334-600380d7-2d69-4559-88fc-2b476668dbc8.png">
> 
> <img alt="alacritty-0 10 1" width="196" src="https://user-images.githubusercontent.com/111366/160258331-e16e4db3-f258-4cf1-8361-52e03df9d0ab.png">
> 
> <img alt="alacritty-b16fe125" width="201" src="https://user-images.githubusercontent.com/111366/160258332-f5eaab76-819b-4136-9391-956abf138287.png">
> 
> EDIT: double checked, all #FF9E64 EDIT: on checkouts, doing a `make app` then `./target/release/alacritty`

In P3, that's #FE9E64. In my laptop's native color space (see above), that's #FF9D64. In sRGB, it doesn't exist.

**Comment by Saklad5** [comment] 2022-03-29 12:15
@kchibisov Is what I described, allowing color spaces to be specified along with each hex code, feasible given Alacritty's current architecture?

I consider color accuracy non-negotiable in anything encouraging me to configure colors. I'm not very familiar with converting between color spaces, but I know most things do it, and iTerm 2 (the original "true color" terminal) implements the exact system I'm asking for.

By the way, every theme that currently exists for Alacritty suffers from this issue. I'm frankly astonished that no one using multiple displays has complained before now.

**Comment by kchibisov** [comment] 2022-03-29 13:17
You can specify color space in escape sequences, it just alacritty ignores it. And the thing is that majority terminal emulators do ignore it, and clients don't ever send color space in escape sequence. However if terminal identifies that display is in p3 it can start converting srgb colors to p3, the problem is that there's no such conversion in alacritty.

>By the way, every theme that currently exists for Alacritty suffers from this issue. I'm frankly astonished that no one using multiple displays has complained before now.

Probably the majority is using Linux/BSD(there's no such issue afaics) or don't really care.

**Comment by chrisduerr** [comment] 2022-03-29 16:54
Honestly having escape sequences add a colorspace just seems like an unnecessarily complicated solution. Not something I'd be interested in at least. Colorspace support generally doesn't seem to have a ton of direct benefits to me for a terminal.

**Comment by Saklad5** [comment] 2022-03-29 16:55
Then at least pin it to a specific colorspace like everything else does.

**Comment by chrisduerr** [comment] 2022-03-29 16:58
Send a PR.

**Comment by kchibisov** [comment] 2022-03-29 17:01
>Then at least pin it to a specific colorspace like everything else does.

Just to make it clear, I'm not sure that any of core contributors have access to macOS hardware to fix macOS specific issues. On a laptop I've used for that I've been able to fix colors, since it's an old mac with srgb coloring, not p3.

**Comment by sforli** [comment] 2022-03-29 22:48
> Probably the majority is using Linux/BSD(there's no such issue afaics) or don't really care.
I came here precisely because of this, Linux user (KDE, Xorg).
To me, it looks even worse than it does on Mac, see here:

ALACRITTY (no color scheme configuration, vanilla YAML file)
![image](https://user-images.githubusercontent.com/16327850/160716513-41176aae-e8fd-4886-933b-1552d3d0a0d2.png)

Konsole
![image](https://user-images.githubusercontent.com/16327850/160716565-d7ba87b2-a019-4c89-bc55-a623e309cfac.png)

I second what @Saklad5 said: for a graphical tool, proper color representation is a non-negotiable feature, and yes, across architectures :)

**Comment by kchibisov** [comment] 2022-03-29 23:13
But your colorscheme and fonts are just different @sforli ? Have you tried comparing colors directly out side of the vim via truecolor escape sequences? I think they will be the same.

**Comment by Saklad5** [comment] 2022-03-29 23:15
And I think that if you use a digital color meter, Alacritty will be in the native color space and Vim will be in sRGB.

**Comment by kchibisov** [comment] 2022-03-29 23:27
The problem on is likely due to miss configuration on Linux, since it looks like alacritty isn't using truecolors at all, and truecolors in vim won't work in alacritty iirc, since vim refuses to do so, only in nvim.

**Comment by sforli** [comment] 2022-03-29 23:28
Funny you say that.
Same color scheme, same font, that's the same Tmux session opened with the two terminals.
The only difference is the font size (9 and 11 pts, if I'm not mistaken).

> Try `echo -e "\e[48;2;160;0;160m\a\e[2K\e[0m"` and compare.
Here's the output, same font size this time.

ALACRITTY
![image](https://user-images.githubusercontent.com/16327850/160722569-cd5ec3f1-ff77-4c0f-832c-3c75d16bd13f.png)

Konsole
![image](https://user-images.githubusercontent.com/16327850/160722511-cabde7f5-8059-43c0-bea5-64ffa83f5d76.png)

**Comment by kchibisov** [comment] 2022-03-29 23:32
Alacritty isn't using 000000 as background color by default... I'm pretty sure if you tell it to use 000000 as background it'll be black, but default color isn't black.

**Comment by Saklad5** [comment] 2022-03-30 00:04
@sforli
> This is just the shell no Vim, and yet not even the background color (#000000) looks the same.

If there's one thing I you *can* be certain of, it's that #000000 is black. You sure it isn't some sort of transparency nonsense fouling it up?

**Comment by sforli** [comment] 2022-03-30 00:07
No transparency, @kchibisov 's comment was the reason. I thought that by using the Alacritty defaults, I would have not messed up with the color schemes, but apparently the default background is not black. If I explicitly define that, then yes, black becomes _black_,

**Comment by marcelbeumer** [comment] 2022-06-04 12:58
I saw this in the Kitty changelog of 0.25.1, probably related to the issue we are looking at here:
https://github.com/kovidgoyal/kitty/issues/4686

**Comment by naruaway** [comment] 2023-01-03 14:59
@marcelbeumer thanks, I was also experiencing this color inconsistency issue and for me I really wanted to make it consistent with colors shown in web browsers. The patch for Kitty you posted just worked for me for Alacritty.
I created https://github.com/alacritty/alacritty/pull/6602

**Closed** 2023-01-07 14:23 UTC
