### ISSUE TITLE
Problems with displaying some unicode font characters on Manjaro

### ISSUE THREAD

**Issue by butla** [alacritty/alacritty#2815] opened 2019-09-22 15:32 UTC
Which operating system does the issue occur on?
Manjaro 18.1.0, XFCE

If on linux, are you using X11 or Wayland?
X11

I use ZSH. I've moved my Alacritty configuration from Kubuntu 18.04 (where everything displays OK) to Manjaro XFCE. I've noticed some characters (used by ZSH bira theme) don't display right with the default monospace font. The characters are pairs  `╭─` and `╰─`.

Alacritty monospace:
![Alacritty monospace](https://user-images.githubusercontent.com/1710591/65390334-add6b980-dd55-11e9-9c5e-53e7722e0253.png)

xfce terminal monospace:
![xfce terminal monospace](https://user-images.githubusercontent.com/1710591/65390367-d8287700-dd55-11e9-8259-fe453ec9b73b.png)
(Polish characters looking off might mean that there's something wrong with the font on the system) 

The only monospace font that I have on the system that looks normally is Noto Sans Mono.
Alacritty:
![Screenshot_2019-09-22_16-07-24](https://user-images.githubusercontent.com/1710591/65390375-e4143900-dd55-11e9-9582-c6c6562e65f2.png)
(even though the characters don't overlap weirdly here, there's a gap between the upped and lower line)

Xfce terminal: 
![Screenshot_2019-09-22_16-09-26](https://user-images.githubusercontent.com/1710591/65390387-1160e700-dd56-11e9-94f8-06b314311607.png)

Any ideas why this is happening or how to debug this?

**Comment by chrisduerr** [comment] 2019-09-22 17:59
You could try modifying the line height to get it to match up, though other glyphs might intersect with each other then.

Usually the best way to do this is just to check which font you want to use for these glyphs and then setting up font fallback to make use of it.

If the fallback is different in Alacritty compared to other applications, there are various reasons that could cause this (Alacritty doesn't use pango for example, while GTK does). Generally problems with fontconfig fallback are tracked in #1560.

Some terminal emulators might also draw certain characters completely on their own (like the box drawing characters for example). In that case there's no way for Alacritty to look the same way, since it's rendering custom glyphs instead of using the font.

**Comment by chrisduerr** [comment] 2020-04-28 20:00
Closing as duplicate of #957 and #118 (see https://github.com/alacritty/alacritty/issues/827#issuecomment-620822975).

**Closed by chrisduerr** 2020-04-28 20:00 UTC
Labels: S - font
