### ISSUE TITLE
"Unused config key: import" warning when using .toml config file for selecting a theme

### ISSUE THREAD

**Issue by torbenf** [alacritty/alacritty#6996] opened 2023-06-13 10:40 UTC
I try to configure my alacritty with an `alacritty.toml` file because otherwise i get a deprication warning for .yml.
This is my file:
```
import = [ "~/.config/alacritty/themes/themes/rose-pine.toml" ]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
opacity = 0.98
decorations = "full"

[font]
size = 11.0

  [font.normal]
  family = "monospace"
  style = "Regular"
```
I migrated the rose-pine.yml file to a .toml file.
Everything works fine. **The theme is selected correctly.**
But whenever I start alacritty I get a warning:
`Unused config key: import`

Why is that and what do I need to do?

The [alacritty-themes](https://github.com/alacritty/alacritty-theme) page suggests using .yml, but I don't want those deprication warnings.

Thank you! :)

### System

```
            .-/+oossssoo+/-.               torben@torben-desktop
        `:+ssssssssssssssssss+:`           ---------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: B550 Pro4
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-43-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3606 (dpkg), 28 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.5
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-blue-dark [GTK2/3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-blue [GTK2/3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: x-terminal-emul
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI Radeon HD 6850
      -+sssssssssssssssssyyyssss+-         Memory: 3894MiB / 15727MiB
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
Version: `alacritty --version` output

`alacritty 0.13.0-dev (bd490672)`

**Comment by chrisduerr** [comment] 2023-06-13 18:51
Fixed in https://github.com/alacritty/alacritty/pull/7000.

**Closed** 2023-06-14 05:41 UTC

**Comment by EmilianoEscobedo** [comment] 2023-12-30 16:25
Hi, I'm having the same issue. I recently migrated yml to toml config file with `alacritty migrate` and I get **[WARN] Unused config key: schemes** when I open a new terminal.

**Comment by anotherglitchinthematrix** [comment] 2023-12-30 18:13
unused key: footer_bar, should I define it? why doesn't it using default value?

**Comment by kchibisov** [comment] 2023-12-30 20:13
>unused key: footer_bar, should I define it? why doesn't it using default value?

it means that you should remove it because it's not used.

**Comment by kchibisov** [comment] 2023-12-30 20:14
>[WARN] Unused config key: schemes

you should also remove it or comment out.

**Comment by anotherglitchinthematrix** [comment] 2023-12-31 10:40
> > [WARN] Unused config key: schemes
> 
> you should also remove it or comment out.

It was defined in the theme, thank you.

**Comment by 100busy** [comment] 2023-12-31 21:58
> Hi, I'm having the same issue. I recently migrated yml to toml config file with `alacritty migrate` and I get **[WARN] Unused config key: schemes** when I open a new terminal.

did you solve this? having the same issue of "unused config key:schemes"

**Comment by EmilianoEscobedo** [comment] 2023-12-31 22:56
> > Hi, I'm having the same issue. I recently migrated yml to toml config file with `alacritty migrate` and I get **[WARN] Unused config key: schemes** when I open a new terminal.
> 
> did you solve this? having the same issue of "unused config key:schemes"

Hi, yes. Just delete or comment the lines starting with [schemes]. I think they are no longer used in the new toml config files. 
Happy new year! :)

**Comment by h3ndry** [comment] 2024-01-02 00:08
Happy New Year ! :)

in my case had to comment this
```
# [colors.cursor]
# cursor = "CellForeground"
# style = "Block"
# text = "CellBackground"


```

**Comment by nicos68** [comment] 2024-01-08 09:16
> > unused key: footer_bar, should I define it? why doesn't it using default value?
> 
> it means that you should remove it because it's not used.

I also had a warning about `footer_bar`, I also removed it and it did fix the warning that was being displayed. But I find this strange, because
 * It is defined in the [official doc](https://alacritty.org/config-alacritty.html)
 * It does have an effect on the theme when I set it to different colors:
 
![image](https://github.com/alacritty/alacritty/assets/1062625/4e780813-0721-4a11-8466-ac74a9f0b9eb)
![image](https://github.com/alacritty/alacritty/assets/1062625/ff09d10e-b61a-4fe3-b29b-86650c96c2fe)

**Comment by kchibisov** [comment] 2024-01-08 09:19
It could be defined in a theme you export.

**Comment by nicos68** [comment] 2024-01-08 09:28
Yes, it is defined in my theme, what I don’t get is why there is a warning saying it’s not used whereas it clearly _is_ used.

**Comment by kchibisov** [comment] 2024-01-08 09:37
You likely have keys duplicated? Like you have one working and other not...

**Comment by nicos68** [comment] 2024-01-08 09:43
Ok I got it, in fact I had a `colors.search.footer_bar` property that is actually unused, but the `colors.footer_bar` one is used. You helped me by talking about duplicates though, thanks !

**Comment by Peipiteir** [comment] 2024-01-08 15:07
I get Unused config key: schemes, but i don't have schemes mentioned in the alacritty.toml file

**Comment by kchibisov** [comment] 2024-01-08 15:08
If something isn't used it should be removed or commented out.

**Comment by Peipiteir** [comment] 2024-01-08 15:22
> If something isn't used it should be removed or commented out.

but It's supposed to only check the alacritty.toml file right? because i don't see anything related to scheme in there.
```
[colors.cursor]
#cursor = "0x528D9C"
#text = "0x474646"

[colors.line_indicator]
background = "None"
foreground = "None"

#[colors.search."colors.footer_bar"]
#background = "None"
#foreground = "None"

[colors.search.focused_match]
background = "CellForeground"
foreground = "CellBackground"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[cursor]
#blinking = "Off"
style = "Beam"

[font]
size = 11

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[scrolling]
history = 20000
#scroll_on_keystroke = true

[window.padding]
x = 8
y = 8
``` I only have this

**Comment by kchibisov** [comment] 2024-01-08 15:31
your config is fine, ensure that it's the one that is loaded with `alacritty -vv`, If I run alacritty on your config with `alacritty --config-file` I don't have warnings.

**Comment by Peipiteir** [comment] 2024-01-08 15:35
> your config is fine, ensure that it's the one that is loaded with `alacritty -vv`, If I run alacritty on your config with `alacritty --config-file` I don't have warnings.
I tried `alacritty -vv` and the warning is still there :<
![alacritty_warning](https://github.com/alacritty/alacritty/assets/80051425/d5db91aa-0520-4f10-8f4e-9c3dcda16ebb)

**Comment by kchibisov** [comment] 2024-01-08 15:42
The `-vv` should log you what config it's reading.

**Comment by Peipiteir** [comment] 2024-01-08 15:45
![image](https://github.com/alacritty/alacritty/assets/80051425/6bbd4ec9-9099-4c7f-9e73-08acfaabc893)

**Comment by kchibisov** [comment] 2024-01-08 15:49
And the only way it can read it if you have `import` in `/home/peep/.config/alacritty/alacritty.toml` pointing to `color`.

**Comment by Peipiteir** [comment] 2024-01-08 16:30
thanks, it's fixed.

**Comment by vdegenne** [comment] 2024-01-14 14:33
Shouldn't the error message be "The property [x] does not exist" or "is unknown".  
What does `Unused config key: copy_on_select` even mean? "Not used" where?

**Comment by Ali-Flt** [comment] 2024-01-17 21:24
Why is this closed? The issue is so not fixed

**Comment by zhnd** [comment] 2024-01-18 09:17
But I still encountered this problem when I used import.

**Comment by fuadsaud** [comment] 2024-01-20 13:03
I can reproduce it when putting `import = ...` at the bottom of the file. Putting it at the top issues no warning.

**Comment by kchibisov** [comment] 2024-01-20 14:59
Global toml keys(GENERAL section in docs), should be at the top. Probably the words "root level of the config" is not really clear.

**Comment by doonoo** [comment] 2024-02-04 16:00
Yeah baby, fixed the config not loading the pywal colors! Thank you

**Comment by Zabardast** [comment] 2024-02-13 07:35
i removed the "size" member from [font.bold_italic] and it pretty much fixed it for my system.

**Comment by Gotoro** [comment] 2024-08-25 21:25
Solution: if you have custom settings in `alacritty.toml` (e.g. [font], [window] etc.), move them down under import so it looks something like this:
```
import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[font]
 size = 14.0
[window]
 startup_mode = "Maximized"

```

**Comment by Hikhuj** [comment] 2024-10-01 14:24
> I can reproduce it when putting `import = ...` at the bottom of the file. Putting it at the top issues no warning.

This did the work for me. I had to move it up on the file to remove the warning.

```
import = [
        "~/.config/alacritty/themes/themes/google.toml"
]

live_config_reload = true
```

**Comment by gatrenat** [comment] 2025-09-10 19:53
I'm in the same situation.

If the configuration looks as:
import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]
live_config_reload = true

I get the message: 
[WARN ] [alacritty_config_derive] Config warning: live_config_reload has been deprecated; use general.live_config_reload instead
                                                   Use `alacritty migrate` to automatically resolve it
`alacritty migrate` does not solve it, by the way

Then, if the configuration is:
general.import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

The warning becomes:
[WARN ] [alacritty_config_derive] Unused config key: general

The same if the conf contains:

[general]
import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]
