### ISSUE TITLE
Segfault on driver update

### ISSUE THREAD

**Issue by bbaserdem** [alacritty/alacritty#2404] opened 2019-05-02 18:11 UTC
* OS: Arch Linux
* GPU:  NVIDIA Corporation G96CGL [Quadro FX 580]
* Driver: nvidia-340-xx
* Version: 0.3.2

Alacritty automatically segfaults on launch after a system update. (Same with kitty) I haven't been able to see any other messages regarding the crash. Here is the output;

```
$ RUST_BACKTRACE=1 alacritty     
[1]    64392 segmentation fault (core dumped)  RUST_BACKTRACE=1 alacritty
```

Checked the other posts on segfaults, but this seems different from what they described.

**Comment by chrisduerr** [comment] 2019-05-02 18:19
Try rebooting.

**Comment by bbaserdem** [comment] 2019-05-03 00:42
I did reboot. (usually my first thing to do when kernel or graphics drivers are updated)

**Comment by chrisduerr** [comment] 2019-05-03 07:28
Have you tried running `cargo clean` and then building from a clean state?

If Kitty is also failing, that does sound like a driver issue though.

**Comment by bbaserdem** [comment] 2019-05-03 13:11
I never compiled a cargo app before. I followed the guide, and now have this error when compiling;

```
$ cargo build --release         
error: process didn't exit successfully: `rustc -vV` (signal: 11, SIGSEGV: invalid memory reference)
--- stdout
rustc 1.34.1 (fc50f328b 2019-04-24)
binary: rustc
commit-hash: fc50f328b0353b285421b8ff5d4100966387a997
commit-date: 2019-04-24
host: x86_64-unknown-linux-gnu
```

But again, I agree that the issue is probably driver side. If anyone is using the old nvidia drivers, maybe they can chime in?

**Comment by chrisduerr** [comment] 2019-05-03 21:38
Has this GPU actually worked before? According to Nvidia's online documentation it only supports OpenGL version 3.0.

**Comment by bbaserdem** [comment] 2019-05-03 22:10
Alacritty was working fine up until the last update. Kitty never worked on this (in case its relevant, since another gpu accelerated terminal)

**Comment by chrisduerr** [comment] 2019-05-03 22:23
It's surprising to me that it worked before because usually Alacritty does not support OpenGL versions below 3.2.

It sounds to me like this might be an Nvidia driver issue with an old GPU though, since it happened after a system update. Archlinux should maintain a nice package cache, could you try downgrading to the previous driver version from there?

**Comment by kchibisov** [comment] 2020-01-19 15:29
since it was stated that GPU doesn't support OpenGL 3.3 officially. this issue is a duplicate of #128.

**Closed by kchibisov** 2020-01-19 15:29 UTC
Labels: F - duplicate
