### ISSUE TITLE
daemon mode

### ISSUE THREAD

**Issue by untoreh** [alacritty/alacritty#241] opened 2017-01-08 23:14 UTC
a daemon mode would be nice, for reference urxvtd uses 20mb + 100kb ram per window

**Comment by aktau** [comment] 2017-01-10 10:40
It'd need to be pretty resistant to crashing though. I stopped using urxvt daemon mode because it crashed (only a few times, not many) and took all of its windows with it. Is current alacritty memory usage that high?

**Comment by untoreh** [comment] 2017-01-10 12:25
I have never experienced a crash on my end with urxvtd, anyway alacritty seems to use roughly 30mb per window? libvte terminals with dbus use <1mb per window

**Comment by mathstuf** [comment] 2017-10-18 15:39
I've seen urxvtd crash a few times (as in maybe 5 in the past 7 years), but `tmux` buffers me against those anyways.

I think the idea, at least with urxvtd, is more about speed of opening new windows rather than memory usage.

**Comment by beta-phenylethylamine** [comment] 2018-03-19 01:34
It's mostly exactly what @mathstuf said. I tend to open and close terminal emulators a lot and have a lot open at the same time at the same time, so client/daemon terminal emulators are a no brainer for me usually. It and scrollback not having arrived in stable yet are the two big reasons I haven't switched to Alacritty even though it runs better and has much cleaner font rendering than xiate (my TE of choice right now) does

**Comment by mpe** [comment] 2018-04-05 09:45
I tried switching to alacritty this week and found the memory usage is a show-stopper for me. Admittedly I do tend to run a lot of terminals.

As a small experiment running 10 alacritty's uses ~135MB each, or ~1.3GB in total. That doesn't change noticeably between just after startup vs with 10,000 lines of scrollback each.
 
Running 10 gnome-terminal windows uses ~50MB in total at startup.
After 10,000 lines of scrollback on each it's up to ~100MB in total.

It's true that daemon mode increases your risk if there's a crash, but honestly I can't remember the last time gnome-terminal crashed on me.

That all sounds a bit negative but is meant to be constructive! What's working so far is awesome :tada:

**Comment by maximbaz** [comment] 2018-04-05 11:30
While I'm curious myself about the daemon mode, I cannot reproduce your results on memory consumption.

If I interpret the output of `htop` correctly, the memory usage is the physical memory used by process (`RES`) minus the memory that is shared by processes (`SHR`). 

> Could someone confirm if this is correct way to measure real memory usage?

Here's my `htop`:

![image](https://user-images.githubusercontent.com/1177900/38363345-9ca41062-38d4-11e8-99e4-cac836d69603.png)

If we look at `RES` alone, it's 30MB per instance or 300MB per 10 instances (way less than 1.3GB).

If we look at `RES` minus `SHR`, it's 10MB per instance or 100MB per 10 instances.

**Comment by mpe** [comment] 2018-04-07 02:44
@maximbaz thanks for looking at it.

Measuring memory usage is complicated, because of shared pages etc. But your measurement using RES - SHR is probably better than mine which was just looking at RSS.

I'm also running with scrollback enabled, and it seems I actually had 20,000 lines configured.

So in that case I see RES ~= 130MB and SHR ~= 20MB for 90MB in total.

**It's the scrollback size which accounts for most of the memory usage.**

If I reduce scrollback to 100 lines, I see numbers that more or less match yours in htop.

So the question is why is scrollback using so much memory? If I compare a few values (all at startup):
```
Lines   RES  SHR
100,000	535M 19M
 20,000	131M 19M
 10,000	 82M 19M
  1,000	 36M 19M
    100	 32M 19M
```

Each extra line of (empty) scrollback is using ~5K of memory?

**Comment by maximbaz** [comment] 2018-04-07 09:41
Because scrollback footprint will not be improved by daemon mode, I create a separate ticket for this.

https://github.com/jwilm/alacritty/issues/1236

**Comment by JimVliet** [comment] 2019-04-11 09:36
> Because scrollback footprint will not be improved by daemon mode, I created a separate ticket for this.
> 
> #1236

So is there any way to get alacritty working like urxvtd/urxvtc? Because for me there is a significant difference between startup time between alacritty and urxvt, because of the deamon.

This is my startup time for urxvt with daemon:
```
real	0m0.017s
user	0m0.006s
sys	0m0.000s
```
For alacritty without daemon:
```
real	0m0.205s
user	0m0.091s
sys	0m0.045s
```

This difference is mainly stopping me from switching. Also I'd like to learn rust, so if there is any way I can start helping out, tell me.

**Comment by chrisduerr** [comment] 2019-04-11 09:58
Only because this will not help with scrollback buffer initialization, does not mean it wouldn't help with startup time.

I'd imagine if we can reduce the GL initialization time (unsure how much needs to be redone for spawning a second window), this could significantly reduce memory usage and startup time. A big chunk of Alacritty's memory usage is due to OpenGL driver initialization right now.

**Comment by chrisduerr** [comment] 2019-04-11 10:05
Just to add some proof to this assumption, running the winit multiwindow example I see a resource usage of around 21.4M, but running the single window example I get a 20.6M resource usage.

So I think it's safe to assume that spawning multiple processes from a single window can still significantly reduce memory usage of Alacritty, though this doesn't say anything about startup time.

**Comment by augustobmoura** [comment] 2020-04-02 20:17
There's any ongoing work on this issue? Or any blockers?

If not, somewhat related, there's any ongoing documentation about the overall architecture of the code relevant to this issue or any tips on understanding it? I could make a stab in making a wrapper to my use case and eventually make a pr upstream

**Comment by kchibisov** [comment] 2020-04-02 21:08
I feel like implementing #607 should be the first step.

**Comment by chrisduerr** [comment] 2020-04-02 21:59
Yes, #607 would be the first step and the approach to resolving that should already be well documented over there. If there are any specific questions, feel free to ask.

**Comment by whirm** [comment] 2020-11-02 08:52
Any news on this? I was already changing my setup from urxvt when I realized how comparatively slow alacritty's startup time is:

```console
# for i in $(seq 1 10); do /usr/bin/time -f "%e" alacritty -e sh -c "sleep 0.0001" ; done
0.23
0.24
0.25
0.24
0.21
0.23
0.22
0.23
0.23
0.21
# for i in $(seq 1 10); do /usr/bin/time -f "%e" urxvt -e sh -c "sleep 0.0001" ; done       
0.08
0.07
0.07
0.10
0.09
0.08
0.09
0.10
0.07
0.07
# for i in $(seq 1 10); do /usr/bin/time -f "%e" urxvtc -e sh -c "sleep 0.0001" ; done 
0.03
0.02
0.03
0.03
0.03
0.03
0.03
0.02
0.01
0.02
```
It's noticeable enough on terminal heavy workflows like mine that it becomes too bothersome to switch.

**Comment by chrisduerr** [comment] 2020-11-02 11:01
> It's noticeable enough on terminal heavy workflows like mine that it becomes too bothersome to switch.

Should note that URxvt's daemon startup time cannot be measured this way. The process just delegates, it doesn't actually do the initialization itself. Thus timing it is pointless.

Also I'm going to lock this issue since people keep asking about updates on this issue when the issue that is blocking it is still not resolved. Until that is the case there are not going to be any updates. It's also completely pointless to ask for updates when there are no PRs to be found anywhere, if nobody is working on it, nobody's working on it.

If you're interested in working on the parent issue, please do let me know there. I'm happy to mentor people through the implementation.

**Comment by kchibisov** [comment] 2022-01-21 04:27
There's IPC window creation now, so it's basically a daemon mode.

**Closed by kchibisov** 2022-01-21 04:27 UTC
Labels: enhancement
