### ISSUE TITLE
Keypress issue in master

### ISSUE THREAD

**Issue by dhasial** [alacritty/alacritty#5911] opened 2022-02-24 20:18 UTC
Multiple keys seem to be changed on `alacritty 0.11.0-dev (13b6248d)`, issue goes away when reverting to `alacritty 0.10.1 (2844606d)`. Both `home` and `end` keys stop doing anything, in addition to `ctrl + backspace` and `ctrl + H` suddenly becoming the same key, both outputting 0008 instead of 0008 and 0007 respectively.

### System

OS: Linux Debian Unstable
Version: `alacritty --version` output
Linux/BSD: Wayland, Kwin, KDE/Plasma

**Comment by chrisduerr** [comment] 2022-02-24 21:53
Which commit specifically caused this issue for you?

**Comment by Dhamma-valence** [comment] 2022-02-24 23:34
I unfortunately don't know the precise commit, but it was definitely within the last 2-3 days that it started. I try to keep it pretty recent. I wish I had more information, but I have no way (that I know of) to pull up a history of the last master/commit version because I only do `git pull origin master`.

**Comment by chrisduerr** [comment] 2022-02-25 13:58
> I unfortunately don't know the precise commit, but it was definitely within the last 2-3 days that it started. I try to keep it pretty recent. I wish I had more information, but I have no way (that I know of) to pull up a history of the last master/commit version because I only do git pull origin master.

You can use git bisect? Or just pull master and then `git reset --hard HEAD~1` until you're at the breakage.

**Comment by kchibisov** [comment] 2023-03-13 16:57
alacritty's default backspace character is `^?` and `ctrl + backspace` is `^H`, that's defined in our terminfo, at least the `^?` is clearly there. zellij being a nested terminal emulator, should take our terminfo into account and remap.

**Comment by imsnif** [comment] 2023-03-30 16:29
Hey @kchibisov - Zellij dev here. Thanks for pointing out the entry in terminfo, but unless I'm misunderstanding very much I think this is not the issue here.

I think Alacritty [like other terminals](https://unix.stackexchange.com/questions/327953/make-ctrl-backspace-different-than-ctrl-h), does not differentiate between ctrl-h and ctrl-backspace. Both of them seem to send `^H` in my tests. Am I missing something? If not, is there a way to configure this somehow for the benefit of @sinux-l5d and other users?

**Comment by kchibisov** [comment] 2023-03-31 04:35
>Both of them seem to send ^H in my tests. Am I missing something? If not, is there a way to configure this somehow for the benefit of @sinux-l5d and other users?

You can define a binding in the config to send whatever you want. Otherwise there's an issue about `CSI u` on our tracker.

**Comment by kchibisov** [comment] 2023-07-01 11:55
Closing as a duplicate of the #6378. (I forget the issue that was earlier for that).

**Closed by kchibisov** 2023-07-01 11:55 UTC
Labels: A - needs repro
