### ISSUE TITLE
Alt+Shift+] keymapping not working in X11

### ISSUE THREAD

**Issue by SV3A** [alacritty/alacritty#3840] opened 2020-06-09 15:30 UTC
I've stumbled on to an odd problem where the following mapping does not work
```
key_bindings:
  # Send space + [] to vim to change buffer
  - { key: LBracket, mods: Alt|Shift, chars: "\x20\x5b" }
  - { key: RBracket, mods: Alt|Shift, chars: "\x20\x5d" }
```
while instead using only alt, with
```
key_bindings:
  - { key: LBracket, mods: Alt, chars: "\x20\x5b" }
  - { key: RBracket, mods: Alt, chars: "\x20\x5d" }
```
seems to work.

Am I doing something wrong, or is X/xfce hijacking something, or is it a bug?

First i suspected that using Shift might invalidate the `L/RBracket` key designation, as Shift normally would *curly* brackets instead of square ones, but as I understand, `L/RBracket` catches both curly and square brackets, right?

*P.S. for the curious: as the comment suggests, I'm using the keymapping to send `"leader"+]` in vim, which in turn triggers `:bn` (next buffer) mapping there.*

### System

OS: Arch Linux
Version: alacritty 0.4.3
Linux/BSD: X11, xfce

### Logs
 `alacritty --print-events`:
```
[2020-06-09 17:16:22.277699094] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33147, tv_nsec: 233421123 }, requested_resume: None })
[2020-06-09 17:16:22.277838146] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: (empty) }) }
[2020-06-09 17:16:22.277884899] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: ModifiersChanged(ALT) }
[2020-06-09 17:16:22.277917390] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.277941562] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.278043968] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 390444409 }, requested_resume: None })
[2020-06-09 17:16:22.278176511] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
[2020-06-09 17:16:22.278262481] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.278312338] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.278790151] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 390838814 }, requested_resume: None })
[2020-06-09 17:16:22.278872634] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: ALT }) }
[2020-06-09 17:16:22.278914161] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: ModifiersChanged(SHIFT | ALT) }
[2020-06-09 17:16:22.278945153] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.278966627] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.279112548] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 391470258 }, requested_resume: None })
[2020-06-09 17:16:22.279229338] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: SHIFT | ALT }, is_synthetic: false } }
[2020-06-09 17:16:22.279340555] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.279385248] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.615301041] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 391900911 }, requested_resume: None })
[2020-06-09 17:16:22.615440903] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 27, state: Pressed, virtual_keycode: Some(RBracket), modifiers: SHIFT | ALT }) }
[2020-06-09 17:16:22.615505984] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.615539564] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.615587634] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 728049567 }, requested_resume: None })
[2020-06-09 17:16:22.615639735] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 27, state: Pressed, virtual_keycode: None, modifiers: SHIFT | ALT }, is_synthetic: false } }
[2020-06-09 17:16:22.615683964] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: ReceivedCharacter('}') }
[2020-06-09 17:16:22.615731550] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.615753777] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.620481220] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 732942044 }, requested_resume: None })
[2020-06-09 17:16:22.620587274] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2020-06-09 17:16:22.620613119] [INFO] glutin event: UserEvent(Urgent)
[2020-06-09 17:16:22.620635048] [INFO] glutin event: UserEvent(Wakeup)
[2020-06-09 17:16:22.620665281] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.620697389] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.637149766] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 749606920 }, requested_resume: None })
[2020-06-09 17:16:22.637266050] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.637310122] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:22.712698079] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 766504321 }, requested_resume: None })
[2020-06-09 17:16:22.712833636] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 27, state: Released, virtual_keycode: Some(RBracket), modifiers: SHIFT | ALT }) }
[2020-06-09 17:16:22.712895168] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 27, state: Released, virtual_keycode: None, modifiers: SHIFT | ALT }, is_synthetic: false } }
[2020-06-09 17:16:22.712950503] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:22.712980454] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:23.031438517] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33159, tv_nsec: 825490569 }, requested_resume: None })
[2020-06-09 17:16:23.031594394] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: SHIFT | ALT }) }
[2020-06-09 17:16:23.031694524] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: ModifiersChanged(SHIFT) }
[2020-06-09 17:16:23.031763755] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: None, modifiers: SHIFT }, is_synthetic: false } }
[2020-06-09 17:16:23.031838698] [INFO] glutin event: MainEventsCleared
[2020-06-09 17:16:23.031872853] [INFO] glutin event: RedrawEventsCleared
[2020-06-09 17:16:23.032185798] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 33160, tv_nsec: 144382237 }, requested_resume: None })
[2020-06-09 17:16:23.032292563] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: SHIFT }) }
[2020-06-09 17:16:23.032347727] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: ModifiersChanged((empty)) }
[2020-06-09 17:16:23.032418515] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: (empty) }, is_synthetic: false } }
```

**Comment by chrisduerr** [comment] 2020-06-09 16:10
Can you try key `7` instead of `RBracket`?

**Comment by SV3A** [comment] 2020-06-09 16:41
Okay tried this:
```
key_bindings:
  - { key: 7, mods: Alt|Shift, chars: "\x20\x5b" }  # Work
  - { key: 8, mods: Alt|Shift, chars: "\x20\x5d" } # Do not work
```
Which is odd, so I tried:
```
key_bindings:
  - { key: K, mods: Alt|Shift, chars: "\x20\x5b" }  # Works
  - { key: L, mods: Alt|Shift, chars: "\x20\x5d" } # Works
```

Testing was done by updating the config file, quitting, and in newly-opened terminal I executed the shortcut and looked for a space + a "]" to be printed in the terminal prompt.

**Comment by SV3A** [comment] 2020-06-09 16:51
Bonus info, just checked on macOS, here 
`- { key: LBracket, mods: Alt|Shift, chars: "\x20\x5b" }`
works.

**Comment by chrisduerr** [comment] 2020-06-10 09:00
You can see which of these magic numbers you need to use in the `alacritty --print-events` output. The value `7` here is your scancode of that specific key. If you look closely at the Alacritty log output, you'll see that while `scancode` is present, the `virtual_keycode` is `None`. That's why `RBracket` doesn't work, since it's not reported as `Some(RBracket)`. This is generally how to find out reliably how to map to things in Alacritty.

Since that output is very verbose though, another option is to use `showkey --scancodes` (requires root permissions). That's also documented in our default configuration file. It will log the scancodes as hexadecimal and you just need to translate them to decimal.

That makes this a duplicate of https://github.com/alacritty/alacritty/issues/3460.

**Closed by chrisduerr** 2020-06-10 09:00 UTC

**Comment by SV3A** [comment] 2020-06-10 11:11
Ahh, I see. I appreciate the help, thanks!
