### ISSUE TITLE
Doesn't render emoji after 0.14 version

### ISSUE THREAD

**Issue by caiopiccirillo** [alacritty/alacritty#8264] opened 2024-10-23 07:30 UTC
The version 0.14 doesn't render the emojis. I'm currently using ZSH with [starship](https://starship.rs/).
version 0.13.2:
![2024-10-23_09-20](https://github.com/user-attachments/assets/bdcfbd38-bdb9-4c23-b291-fd6b6c27b5bd)

version 0.14.0:
![2024-10-23_09-17](https://github.com/user-attachments/assets/0ff3abc3-229d-4b63-a0e2-9259ac514d0f)

### System

OS: Linux Ubuntu 22.04.5
Version: 0.14
Linux/BSD: X11

### Logs

<details>
<summary><i>Font/Terminal size: `alacritty -vv`</i></summary>

```log
Created log file at "/tmp/Alacritty-18631.log"
[0.000001221s] [INFO ] [alacritty] Welcome to Alacritty
[0.000098903s] [INFO ] [alacritty] Version 0.14.0
[0.000106652s] [INFO ] [alacritty] Running on X11
[0.000435580s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/caio/.config/alacritty/alacritty.toml"
[0.002687172s] [INFO ] [alacritty] Using GLX 1.4
[0.051534372s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: false
[0.056096739s] [INFO ] [alacritty] Window scale factor: 1
[0.057150527s] [DEBUG] [alacritty] Loading "JetBrainsMonoNL NF" font
[0.066377967s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Medium, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.070212395s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.073467093s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.076908161s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.079182568s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics (CML GT2)
[0.079195869s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2, shader_version 4.60
[0.079201261s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.087088247s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.087302680s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.098409083s] [INFO ] [alacritty] Cell size: 9 x 21
[0.098437154s] [INFO ] [alacritty] Padding: 0 x 0
[0.098442267s] [INFO ] [alacritty] Width: 800, Height: 600
[0.111059591s] [INFO ] [alacritty] PTY dimensions: 28 x 88
[0.113819656s] [INFO ] [alacritty] Initialisation complete
[0.719332328s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: LoadFlag(MONOCHROME | TARGET_MONO | COLOR), render_mode: "Mono", lcd_filter: 1 }
```
</details>

<details>
<summary><i>Keyboard and bindings: `alacritty --print-events`</i></summary>

```log
Created log file at "/tmp/Alacritty-19525.log"
[0.000001087s] [INFO ] [alacritty] Welcome to Alacritty
[0.000162427s] [INFO ] [alacritty] Version 0.14.0
[0.000171204s] [INFO ] [alacritty] Running on X11
[0.000551371s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/caio/.config/alacritty/alacritty.toml"
[0.002952111s] [INFO ] [alacritty] Using GLX 1.4
[0.056483573s] [INFO ] [alacritty] Window scale factor: 1
[0.077931046s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics (CML GT2)
[0.077953715s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2, shader_version 4.60
[0.077958711s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.099639205s] [INFO ] [alacritty] Cell size: 9 x 21
[0.099671611s] [INFO ] [alacritty] Padding: 0 x 0
[0.099675810s] [INFO ] [alacritty] Width: 800, Height: 600
[0.105168687s] [INFO ] [alacritty] PTY dimensions: 28 x 88
[0.107941227s] [INFO ] [alacritty] Initialisation complete
[0.108011662s] [INFO ] [alacritty_winit_event] Ime(Enabled)
[0.108263154s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(CursorBlinkingChange) }
[0.108286174s] [INFO ] [alacritty_winit_event] About to wait
[0.108307162s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.109252598s] [INFO ] [alacritty_winit_event] About to wait
[0.109353651s] [INFO ] [alacritty_winit_event] Resized(PhysicalSize { width: 800, height: 600 })
[0.109369601s] [INFO ] [alacritty_winit_event] About to wait
[0.109499914s] [INFO ] [alacritty_winit_event] About to wait
[0.117483817s] [INFO ] [alacritty_winit_event] About to wait
[0.119942600s] [INFO ] [alacritty_winit_event] Moved(PhysicalPosition { x: 107, y: 64 })
[0.120060290s] [INFO ] [alacritty_winit_event] Focused(false)
[0.120077564s] [INFO ] [alacritty_winit_event] Occluded(false)
[0.120093613s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.120671271s] [INFO ] [alacritty_winit_event] About to wait
[0.120845069s] [INFO ] [alacritty_winit_event] Focused(true)
[0.121299770s] [INFO ] [alacritty_winit_event] ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) })
[0.121328823s] [INFO ] [alacritty_winit_event] CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 1014.0, y: 801.0 } }
[0.121348596s] [INFO ] [alacritty_winit_event] About to wait
[0.121410777s] [INFO ] [alacritty_winit_event] About to wait
[0.123278504s] [INFO ] [alacritty_winit_event] About to wait
[0.125916041s] [INFO ] [alacritty_winit_event] About to wait
[0.125940053s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.125950287s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.125956021s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.128796257s] [INFO ] [alacritty_winit_event] About to wait
[0.132982741s] [INFO ] [alacritty_winit_event] About to wait
[0.142581696s] [INFO ] [alacritty_winit_event] About to wait
[0.142640131s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.142652416s] [INFO ] [alacritty_winit_event] About to wait
[0.677305010s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[0.677361112s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.678114334s] [INFO ] [alacritty_winit_event] About to wait
[0.678182086s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Title(caio@caio-Aspire-A715-75G:~)) }
[0.678194936s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[0.678202756s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.678211854s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.680660323s] [INFO ] [alacritty_winit_event] About to wait
[0.680759996s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[0.680780997s] [INFO ] [alacritty_winit_event] About to wait
[0.692107033s] [INFO ] [alacritty_winit_event] About to wait
[0.692169439s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.692181549s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.692637857s] [INFO ] [alacritty_winit_event] About to wait
[0.700909453s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[0.700938349s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[0.700944349s] [INFO ] [alacritty_winit_event] About to wait
[0.700955760s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[0.700960737s] [INFO ] [alacritty_winit_event] About to wait
[0.708738401s] [INFO ] [alacritty_winit_event] About to wait
[0.708764880s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.708777441s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.710610026s] [INFO ] [alacritty_winit_event] About to wait
[0.725401118s] [INFO ] [alacritty_winit_event] About to wait
[0.725449776s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.725463380s] [INFO ] [alacritty_winit_event] About to wait
[0.871421739s] [INFO ] [alacritty_winit_event] About to wait
[0.871470219s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: BlinkCursor }
[0.871479762s] [INFO ] [alacritty_winit_event] About to wait
[0.871489239s] [INFO ] [alacritty_winit_event] RedrawRequested
[0.872091425s] [INFO ] [alacritty_winit_event] About to wait
[0.872134664s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[0.872143922s] [INFO ] [alacritty_winit_event] About to wait
[1.433386348s] [INFO ] [alacritty_winit_event] About to wait
[1.434709050s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyC), logical_key: Character("c"), text: Some("c"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("c"), key_without_modifiers: Character("c") } }, is_synthetic: false }
[1.434761429s] [INFO ] [alacritty_winit_event] About to wait
[1.435257728s] [INFO ] [alacritty_winit_event] RedrawRequested
[1.437505938s] [INFO ] [alacritty_winit_event] About to wait
[1.437555510s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[1.437608425s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[1.437641960s] [INFO ] [alacritty_winit_event] RedrawRequested
[1.441783912s] [INFO ] [alacritty_winit_event] About to wait
[1.441813858s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[1.441846903s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[1.441855710s] [INFO ] [alacritty_winit_event] RedrawRequested
[1.444666709s] [INFO ] [alacritty_winit_event] About to wait
[1.458131979s] [INFO ] [alacritty_winit_event] About to wait
[1.458192067s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[1.458224713s] [INFO ] [alacritty_winit_event] About to wait
[1.501032362s] [INFO ] [alacritty_winit_event] About to wait
[1.502160800s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("d"), key_without_modifiers: Character("d") } }, is_synthetic: false }
[1.502204970s] [INFO ] [alacritty_winit_event] About to wait
[1.502713942s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[1.502726766s] [INFO ] [alacritty_winit_event] RedrawRequested
[1.503681842s] [INFO ] [alacritty_winit_event] About to wait
[1.503729868s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[1.503738432s] [INFO ] [alacritty_winit_event] About to wait
[1.544909326s] [INFO ] [alacritty_winit_event] About to wait
[1.549654268s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyC), logical_key: Character("c"), text: Some("c"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("c"), key_without_modifiers: Character("c") } }, is_synthetic: false }
[1.549710757s] [INFO ] [alacritty_winit_event] About to wait
[1.603201131s] [INFO ] [alacritty_winit_event] About to wait
[1.604670025s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("d"), key_without_modifiers: Character("d") } }, is_synthetic: false }
[1.604712310s] [INFO ] [alacritty_winit_event] About to wait
[2.119393323s] [INFO ] [alacritty_winit_event] About to wait
[2.120989766s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Space), logical_key: Named(Space), text: Some(" "), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some(" "), key_without_modifiers: Named(Space) } }, is_synthetic: false }
[2.121022467s] [INFO ] [alacritty_winit_event] About to wait
[2.122268668s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[2.122303356s] [INFO ] [alacritty_winit_event] RedrawRequested
[2.124485250s] [INFO ] [alacritty_winit_event] About to wait
[2.124558792s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[2.124573838s] [INFO ] [alacritty_winit_event] About to wait
[2.124991024s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[2.125005900s] [INFO ] [alacritty_winit_event] RedrawRequested
[2.129079777s] [INFO ] [alacritty_winit_event] About to wait
[2.140838065s] [INFO ] [alacritty_winit_event] About to wait
[2.140867740s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[2.140876384s] [INFO ] [alacritty_winit_event] About to wait
[2.209231050s] [INFO ] [alacritty_winit_event] About to wait
[2.210513800s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Space), logical_key: Named(Space), text: Some(" "), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some(" "), key_without_modifiers: Named(Space) } }, is_synthetic: false }
[2.210557579s] [INFO ] [alacritty_winit_event] About to wait
[2.341294119s] [INFO ] [alacritty_winit_event] About to wait
[2.342887414s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyH), logical_key: Character("h"), text: Some("h"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("h"), key_without_modifiers: Character("h") } }, is_synthetic: false }
[2.342949014s] [INFO ] [alacritty_winit_event] About to wait
[2.343632559s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[2.343683370s] [INFO ] [alacritty_winit_event] RedrawRequested
[2.347253080s] [INFO ] [alacritty_winit_event] About to wait
[2.347331013s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[2.347345393s] [INFO ] [alacritty_winit_event] About to wait
[2.401274391s] [INFO ] [alacritty_winit_event] About to wait
[2.402896767s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyE), logical_key: Character("e"), text: Some("e"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("e"), key_without_modifiers: Character("e") } }, is_synthetic: false }
[2.402927406s] [INFO ] [alacritty_winit_event] About to wait
[2.403458303s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[2.403476519s] [INFO ] [alacritty_winit_event] RedrawRequested
[2.404746507s] [INFO ] [alacritty_winit_event] About to wait
[2.404771709s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[2.404780579s] [INFO ] [alacritty_winit_event] About to wait
[2.436820919s] [INFO ] [alacritty_winit_event] About to wait
[2.438100321s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyH), logical_key: Character("h"), text: Some("h"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("h"), key_without_modifiers: Character("h") } }, is_synthetic: false }
[2.438163232s] [INFO ] [alacritty_winit_event] About to wait
[2.535188756s] [INFO ] [alacritty_winit_event] About to wait
[2.536578210s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyE), logical_key: Character("e"), text: Some("e"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("e"), key_without_modifiers: Character("e") } }, is_synthetic: false }
[2.536614447s] [INFO ] [alacritty_winit_event] About to wait
[2.931399219s] [INFO ] [alacritty_winit_event] About to wait
[2.932751507s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyL), logical_key: Character("l"), text: Some("l"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("l"), key_without_modifiers: Character("l") } }, is_synthetic: false }
[2.932804865s] [INFO ] [alacritty_winit_event] About to wait
[2.933554471s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[2.933573513s] [INFO ] [alacritty_winit_event] RedrawRequested
[2.934622751s] [INFO ] [alacritty_winit_event] About to wait
[2.934653191s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[2.934663773s] [INFO ] [alacritty_winit_event] About to wait
[3.015217329s] [INFO ] [alacritty_winit_event] About to wait
[3.016567090s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyL), logical_key: Character("l"), text: Some("l"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("l"), key_without_modifiers: Character("l") } }, is_synthetic: false }
[3.016601530s] [INFO ] [alacritty_winit_event] About to wait
[3.034946347s] [INFO ] [alacritty_winit_event] About to wait
[3.036391004s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Tab), logical_key: Named(Tab), text: Some("\t"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\t"), key_without_modifiers: Named(Tab) } }, is_synthetic: false }
[3.036414631s] [INFO ] [alacritty_winit_event] About to wait
[3.042609749s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.042671022s] [INFO ] [alacritty_winit_event] RedrawRequested
[3.044628135s] [INFO ] [alacritty_winit_event] About to wait
[3.044697736s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[3.044709346s] [INFO ] [alacritty_winit_event] About to wait
[3.108994793s] [INFO ] [alacritty_winit_event] About to wait
[3.110393582s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Tab), logical_key: Named(Tab), text: Some("\t"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\t"), key_without_modifiers: Named(Tab) } }, is_synthetic: false }
[3.110417986s] [INFO ] [alacritty_winit_event] About to wait
[3.483504577s] [INFO ] [alacritty_winit_event] About to wait
[3.485009992s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Enter), logical_key: Named(Enter), text: Some("\r"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\r"), key_without_modifiers: Named(Enter) } }, is_synthetic: false }
[3.485082888s] [INFO ] [alacritty_winit_event] About to wait
[3.485653848s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.485670454s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.485676723s] [INFO ] [alacritty_winit_event] RedrawRequested
[3.487837174s] [INFO ] [alacritty_winit_event] About to wait
[3.487861113s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Title(cd helix)) }
[3.487871304s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.487878695s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.487883159s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Title(caio@caio-Aspire-A715-75G:~/helix)) }
[3.487889348s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.487893637s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[3.487898857s] [INFO ] [alacritty_winit_event] RedrawRequested
[3.493088127s] [INFO ] [alacritty_winit_event] About to wait
[3.493277491s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.493300346s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[3.493375340s] [INFO ] [alacritty_winit_event] RedrawRequested
[3.496432393s] [INFO ] [alacritty_winit_event] About to wait
[3.506306025s] [INFO ] [alacritty_winit_event] About to wait
[3.506402373s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[3.506421899s] [INFO ] [alacritty_winit_event] About to wait
[3.519043178s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.519122986s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.519130225s] [INFO ] [alacritty_winit_event] RedrawRequested
[3.519796472s] [INFO ] [alacritty_winit_event] About to wait
[3.519821352s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Terminal(Wakeup) }
[3.519832054s] [INFO ] [alacritty_winit_event] About to wait
[3.522922596s] [INFO ] [alacritty_winit_event] About to wait
[3.522941025s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[3.522972235s] [INFO ] [alacritty_winit_event] RedrawRequested
[3.525635052s] [INFO ] [alacritty_winit_event] About to wait
[3.539587044s] [INFO ] [alacritty_winit_event] About to wait
[3.539660429s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[3.539676224s] [INFO ] [alacritty_winit_event] About to wait
[3.550726323s] [INFO ] [alacritty_winit_event] About to wait
[3.551821834s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Enter), logical_key: Named(Enter), text: Some("\r"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\r"), key_without_modifiers: Named(Enter) } }, is_synthetic: false }
[3.551885233s] [INFO ] [alacritty_winit_event] About to wait
[4.235147561s] [INFO ] [alacritty_winit_event] About to wait
[4.235192042s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: BlinkCursor }
[4.235200682s] [INFO ] [alacritty_winit_event] About to wait
[4.235239813s] [INFO ] [alacritty_winit_event] RedrawRequested
[4.235897282s] [INFO ] [alacritty_winit_event] About to wait
[4.235941771s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[4.235972462s] [INFO ] [alacritty_winit_event] About to wait
[4.985469818s] [INFO ] [alacritty_winit_event] About to wait
[4.985513041s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: BlinkCursor }
[4.985521169s] [INFO ] [alacritty_winit_event] About to wait
[4.985557955s] [INFO ] [alacritty_winit_event] RedrawRequested
[4.986394624s] [INFO ] [alacritty_winit_event] About to wait
[4.986420204s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[4.986430193s] [INFO ] [alacritty_winit_event] About to wait
[5.735591397s] [INFO ] [alacritty_winit_event] About to wait
[5.735741605s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: BlinkCursor }
[5.735751513s] [INFO ] [alacritty_winit_event] About to wait
[5.735801786s] [INFO ] [alacritty_winit_event] RedrawRequested
[5.736604357s] [INFO ] [alacritty_winit_event] About to wait
[5.736649089s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[5.736678918s] [INFO ] [alacritty_winit_event] About to wait
[6.155106200s] [INFO ] [alacritty_winit_event] ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) })
[6.155215972s] [INFO ] [alacritty_winit_event] About to wait
[6.156581219s] [INFO ] [alacritty_winit_event] ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) })
[6.157234290s] [INFO ] [alacritty_winit_event] Focused(false)
[6.157306579s] [INFO ] [alacritty_winit_event] About to wait
[6.157341076s] [INFO ] [alacritty_winit_event] RedrawRequested
[6.158947604s] [INFO ] [alacritty_winit_event] About to wait
[6.158980655s] [INFO ] [alacritty_winit_event] Event { window_id: Some(WindowId(58720261)), payload: Frame }
[6.158992531s] [INFO ] [alacritty_winit_event] About to wait
[6.234999737s] [INFO ] [alacritty_winit_event] About to wait
[6.653246178s] [INFO ] [alacritty_winit_event] About to wait
```

</details>

**Comment by kchibisov** [comment] 2024-10-23 07:41
duplicate of #8050

**Closed by kchibisov** 2024-10-23 07:41 UTC
