### ISSUE TITLE
[Windows] ESC key is delayed in vim/neovim

### ISSUE THREAD

**Issue by niklas88** [alacritty/alacritty#1680] opened 2018-10-18 09:01 UTC
First thanks to bringing alacritty to Windows! I'm almost exclusively a Linux user but I sometimes need to use Windows (damn those presentation video dongles). Now with alacritty + WSL Windows becomes an at least somewhat usable OS.

I'm using wsl (via `wslbridge` from wsltty installation 1.9.3)

 In both `vim` and `nvim` in insert mode I'm seeing a delay between pressing `<ESC>` and getting out of insert mode. It feels like almost a second. This doesn't happen with wsltty or the garbage built-in thing they call a terminal.

**Comment by meltinglava** [comment] 2018-10-18 09:03
Think part 2 should be a second issue. Got the same problem with norwegian layout.

**Comment by Bobo1239** [comment] 2018-10-18 09:37
Have you tried this already? https://www.johnhawthorn.com/2012/09/vi-escape-delays/

**Comment by niklas88** [comment] 2018-10-18 12:20
@Bobo1239 I had not until just now. I wasn't using tmux for which I knew about that setting and had it set. Setting the timeouts in vim and zsh sadly had no effect.

**Comment by chrisduerr** [comment] 2018-10-19 22:50
I'm not aware of any way to send escape other than sending escape.

However vim does have a built-in alternative to `<Esc>` which is `<C-[>`. Have you tried that?

**Comment by zacps** [comment] 2018-10-19 22:54
`ctrl-c` also does (almost) the same thing, and is instant. It's definitely an issue with the escape sequence delay.

If there's no way to 'flush' the input processing in winpty then changing the timeout seems reasonable. This doesn't happen in all terminals using winpty though, I'll take a look at how they handle it.

**Comment by zacps** [comment] 2018-12-20 02:21
Changed title because this is caused by winpty, not wslbridge.

**Comment by ubsan** [comment] 2018-12-20 09:39
@chrisduerr it does still happen with `<ctl-[>`

**Comment by zacps** [comment] 2019-01-01 20:46
Relevant mintty docs: https://github.com/mintty/mintty/wiki/CtrlSeqs#escape-keycode

**Comment by niklas88** [comment] 2019-01-09 14:04
I can no longer reproduce this with the newest Alacritty version on Windows, at least not when using ConPTY. Vim and NeoVim work fine both via ssh and on local WSL.

**Comment by chrisduerr** [comment] 2019-01-09 19:32
Great to hear this is resolved by ConPTY, though this issue has already been flagged by @zacps as WinPTY, so he's probably already aware.

**Comment by BatmanAoD** [comment] 2019-03-12 20:18
I'm seeing this issue even in `vi`-mode readline, with Git Bash. It takes about one second to register the escape key.

I have not yet tried installing any additional software.

**Comment by xarthurx** [comment] 2019-03-24 18:29
Same issue here. Need to wait around 1s for ESC or C-[.

**Comment by jayceekay** [comment] 2019-03-31 02:25
i'm also experiencing this

**Comment by seantalts** [comment] 2019-04-04 16:14
Does anyone have a fix for this? i.e. how can get alacritty to use ConPTY?

**Comment by chrisduerr** [comment] 2019-04-04 17:07
If you are up to date with Windows, you just need to set the conpty setting in the config (see default config for docs).

**Comment by BatmanAoD** [comment] 2019-04-04 18:01
@chrisduerr Hadn't seen that because my `.yml` file is apparently from an older version. Thank you!

For anyone else who doesn't have the option in their `.yml` yet:

    enable_experimental_conpty_backend: false

**Comment by jamessewell** [comment] 2019-04-10 01:52
This still doesn't work for me with 
`enable_experimental_conpty_backend: true`

**Comment by chrisduerr** [comment] 2019-04-10 08:10
@jamessewell Make sure you're using at least version 1809 of Windows 10. Previously the ConPTY interface was not supported yet.

**Comment by jamessewell** [comment] 2019-04-10 09:35
That was it! For some reason I was version pinned on 1803

**Comment by chrispitude** [comment] 2019-04-23 01:06
I also found that (1) upgrading to Windows 10 build 1809 and (2) enabling the experimental conpty backend resolved the vim ESC key delay.

**Comment by Peaches491** [comment] 2019-06-18 05:12
For everyone else with the same escape delay problem, I made this simple script to help debug: 
https://gist.github.com/Peaches491/e0017ce55699a485b776107efc87ec21

Run that, and you should see `27` printed out when you hit `ESC`. Hopefully you see it right away, with no delay. 

For me, updating to Window 10 Build 1903, and enabling `enable_experimental_conpty_backend` fixed the delay 👍

**Comment by neelu0** [comment] 2019-08-14 12:45
it seems like after pressing <esc> its waiting for something and goes in a timeout for it, if i immediately press colon key after <esc> it some weird character comes out and when i tried the same thing with other keys some other characters were coming out these are some of it:
`»ºñ´åòôùçæäöãøö
`
but when leaving insert mode with Ctrl-C, vim goes to normal mode like usual.

**Comment by BatmanAoD** [comment] 2019-08-14 14:34
@neelu0 That sounds like the behavior you'd see from remapping `<ctl>-K` to
`<ESC>`, or possibly just from `:set digraph`:
https://vim.fandom.com/wiki/Entering_special_characters

**Comment by jamessewell** [comment] 2020-02-20 00:50
Strangely this has regressed with an updated alacritty and new Laptop on Win 10 1903 

Script above shows delay when pushing escape

**Comment by chrisduerr** [comment] 2021-02-22 21:41
WinPTY support has been removed.

**Closed by chrisduerr** 2021-02-22 21:41 UTC
Labels: A - deps, H - windows, S - I/O and PTY, W - WinPTY
