### ISSUE TITLE
Numpad ENTER interferes with tmux binding for CTRL+J

### ISSUE THREAD

**Issue by mebeim** [alacritty/alacritty#5908] opened 2022-02-23 12:43 UTC
When using `tmux` under Alacritty, if any binding is set for `CTRL+J` through `bind-key -n C-j <command>` (either in `~/.tmux.conf` or from the command line inside a session), then pressing numpad ENTER causes the binding to be executed, as if I had pressed CTRL+J. For example, with `bind-key -n C-j kill-window` the current `tmux` window is killed any time I press numpad ENTER.

It seems that ENTER, numpad ENTER and CTRL+J are all normally interpreted as an enter key: for example, when in a shell session, all of them have the same effect of just printing a newline and a new shell prompt. This is true in Alacritty and in other terminals, like for example KDE's Konsole. 

***However inside `tmux`***, while in KDE's Konsole and Alacritty <= v0.10.0-rc1 I can use numpad ENTER just as a normal enter key, if I do this in Alacritty >= v0.10.0-rc2 then the binding for CTRL+J is executed instead (and no newline is printed on the shell).

Using `git bisect` I was able to identify 7e0636810ed9a1b003cb62f4a0b8a3e632610d96 as the commit that introduced this issue, which apparently only updates the `winit` dependency from `0.26.0` to `0.26.1`. I am not exactly sure this is the right place to open an issue, but I am not familiar enough with Rust to be able to swap the dependency in your `Cargo.lock` and also bisect `winit`, and I am also not sure how Alacritty and `winit` interact with each other.

The keyboard event logs below (only for one numpad ENTER keypress inside `tmux`) show different `KeyboardInput` events for v0.10.0-rc1 vs v0.10.0-rc2, notably `virtual_keycode` is `None` vs `Some(NumpadEnter)`. The output of `alacritty -vv` is identical for both versions so I've omitted it, but I can add it if needed.

---

### System

OS: Linux Debian 11, X11, KDE Plasma 5.20.5
Alacritty version: any version >= v0.10.0-rc2, default config (no config file in `~/.config`).
Tmux version: 3.1c ([package link](http://deb.debian.org/debian/pool/main/t/tmux/tmux_3.1c-1%2bdeb11u1_amd64.deb)), default config (no config file in home or `/etc`).

Tested on:

- v0.9.0, v0.10.0-rc1: problem not present
- v0.10.0-rc2, v0.10.0-rc3, v0.10.0-rc4, v0.10.0, v0.10.1-rc1, v0.10.1: problem present

### Logs for v0.10.0-rc1

```
$ alacritty --print-events
...
[2022-02-23 12:36:17.648689033] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 9789, tv_nsec: 956161678 }, requested_resume: None })
[2022-02-23 12:36:17.648882389] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 96, state: Pressed, virtual_keycode: None, modifiers: (empty) }) }
[2022-02-23 12:36:17.648953456] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:36:17.648987570] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:36:17.649079110] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 9802, tv_nsec: 175532354 }, requested_resume: None })
[2022-02-23 12:36:17.649134699] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 96, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
[2022-02-23 12:36:17.649188619] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: ReceivedCharacter('\r') }
[2022-02-23 12:36:17.649225508] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:36:17.649253720] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:36:17.664733826] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 9802, tv_nsec: 191198202 }, requested_resume: None })
[2022-02-23 12:36:17.664748630] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(MouseCursorDirty) })
[2022-02-23 12:36:17.664756159] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(Wakeup) })
[2022-02-23 12:36:17.664760769] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(Wakeup) })
[2022-02-23 12:36:17.664764917] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(Wakeup) })
[2022-02-23 12:36:17.664768960] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(CursorBlinkingChange) })
[2022-02-23 12:36:17.664773135] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(Wakeup) })
[2022-02-23 12:36:17.664777802] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:36:17.664782504] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:36:17.712549424] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 9802, tv_nsec: 204558555 }, requested_resume: None })
[2022-02-23 12:36:17.712575443] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 96, state: Released, virtual_keycode: None, modifiers: (empty) }) }
[2022-02-23 12:36:17.712586150] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 96, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
[2022-02-23 12:36:17.712599598] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:36:17.712606008] [INFO ] [alacritty] glutin event: RedrawEventsCleared
...
```

### Logs for v0.10.0-rc2

```
$ alacritty --print-events
...
[2022-02-23 12:40:26.979879944] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 10045, tv_nsec: 281318082 }, requested_resume: None })
[2022-02-23 12:40:26.980029871] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 96, state: Pressed, virtual_keycode: Some(NumpadEnter), modifiers: (empty) }) }
[2022-02-23 12:40:26.980107668] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:40:26.980176475] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:40:26.980272365] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 10051, tv_nsec: 506674353 }, requested_resume: None })
[2022-02-23 12:40:26.980349968] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 96, state: Pressed, virtual_keycode: Some(NumpadEnter), modifiers: (empty) }, is_synthetic: false } }
[2022-02-23 12:40:26.980404916] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: ReceivedCharacter('\r') }
[2022-02-23 12:40:26.980451626] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:40:26.980481743] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:40:26.995393438] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 10051, tv_nsec: 521858622 }, requested_resume: None })
[2022-02-23 12:40:26.995422821] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(MouseCursorDirty) })
[2022-02-23 12:40:26.995429740] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(Wakeup) })
[2022-02-23 12:40:26.995434188] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:40:26.995437836] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:40:27.039766457] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 10051, tv_nsec: 536930539 }, requested_resume: None })
[2022-02-23 12:40:27.039788314] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(14))), event: Key(KeyboardInput { scancode: 96, state: Released, virtual_keycode: Some(NumpadEnter), modifiers: (empty) }) }
[2022-02-23 12:40:27.039799091] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(134217730))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 96, state: Released, virtual_keycode: Some(NumpadEnter), modifiers: (empty) }, is_synthetic: false } }
[2022-02-23 12:40:27.039808634] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:40:27.039813782] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2022-02-23 12:40:27.732883608] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 10051, tv_nsec: 566286231 }, requested_resume: None })
[2022-02-23 12:40:27.733000382] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(CursorBlinkingChange) })
[2022-02-23 12:40:27.733073909] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(X(WindowId(134217730)))), payload: Terminal(Wakeup) })
[2022-02-23 12:40:27.733105727] [INFO ] [alacritty] glutin event: MainEventsCleared
[2022-02-23 12:40:27.733135293] [INFO ] [alacritty] glutin event: RedrawEventsCleared
...
```

**Comment by chrisduerr** [comment] 2022-02-23 19:26
Duplicate of https://github.com/alacritty/alacritty/issues/3720.

**Closed by chrisduerr** 2022-02-23 19:26 UTC

**Comment by mebeim** [comment] 2022-10-29 21:13
Hey @chrisduerr is there any way to get this functionality back? I understand this issue being a duplicate of some other one, but in at the end of the day I would only like to know if there is any solution to have Numpad Enter behave normally (i.e. enter a new line) instead of behaving like CTRL+J inside my tmux sessions. 

Before 0.11.0 I was simply able to force `winit` to `0.26.0` to "fix" this, but now I cannot do that anymore as other dependencies need a higher version. I would be fine even editing the source code to be honest, but I don't know why.

I have tried to modify the `event` as the first thing inside the function here:

https://github.com/alacritty/alacritty/blob/578e08486dfcdee0b2cd0e7a66752ff50edc46b8/alacritty/src/event.rs#L1370

by simply turning it into mutable, matching it and doing `virtual_keycode.take()` to turn it into a `None` instead of `Some(NumpadEnter)`, but this does nothing. I guess it's up to `winit` to handle it and when the event gets there it's already been handled? IDK. Any suggestion would be welcome.

**Comment by rascul** [comment] 2023-02-26 00:29
Perhaps this might help in alacritty.yml:

~~~ yaml
key_bindings:
  - { key: NumpadEnter, chars: "\x0d" }
~~~
