### ISSUE TITLE
Slow on macOS with large, dense grids

### ISSUE THREAD

**Issue by splintah** [alacritty/alacritty#897] opened 2017-11-12 16:38 UTC
_Which operating system does the issue occur on?_
macOS 10.12.5

When I set `termguicolors` in my vimrc file (which I really want to) scrolling becomes very slow on larger windows. In windows smaller than 100x80, it works fine, but on bigger windows it becomes slow.
This happens both in neovim (v0.2.1) and in vim (v8.0.1175), and only in alacritty, tested in [kitty](https://github.com/kovidgoyal/kitty), Terminal.app and iTerm. Other programs (like ternimal) run a lot faster in alacritty than in those.
I guess this is a problem with true colours?

**Comment by jwilm** [comment] 2017-11-13 02:06
This is likely an issue with large windows on macOS and has nothing to do with vim, true colors, etc. You can confirm this by running alacritty with `render_timer: true` in the config and seeing that the value is very high when scrolling a large window. You're probably only seeing this with `termguicolors` since vim has to emit extra blank spaces to fill in the background color. Alacritty then does extra work to render those cells.

I've attempted a couple of times to resolve the issue of rendering many cells on macOS, but there were issues with dedicated GPUs on the 15" MacBook Pros. See #643, #652, #648 for additional details.

It's possible you can work around this issue by setting the _background color_ string in your vim color scheme to be an empty string (assuming the value will match your Alacritty config's `colors.primary.background`). This typically results in vim's `termbg` value being cleared, and subsequently, this means vim won't emit empty truecolor cells to "fill in" the background.

One other option we have is for Alacritty to ignore blank truecolor cells when their background matches the default background color, but I'm not sure that would actually be correct.

**Comment by splintah** [comment] 2017-11-13 07:43
Thank you, setting my vim background to `None` made it a lot faster.

**Comment by metalelf0** [comment] 2017-11-13 13:46
@splintah also if the problem is strictly related to scrolling you might have some luck disabling vim relative line numbers, in case you're using them. This is because vim re-calculates syntax highlighting on every changed line - and changing the line number is considered as a change. So, a one line scroll causes all lines on screen to be re-highlighted, and the performance loss is really noticeable on big screens.

**Comment by splintah** [comment] 2017-11-13 15:42
@metalelf0, the problem was related to all kinds of input, but when scrolling the performance loss was most noticeable (and unbearable).

**Comment by jwilm** [comment] 2017-11-13 16:20
> Thank you, setting my vim background to `None` made it a lot faster.

Glad to hear it. Going to keep this open as the canonical issue which #652 attempting to solve.

**Comment by chrisduerr** [comment] 2020-08-14 21:38
The PR for #652 was merged recently, the performance on dense grids on macOS should be significantly improved now.

**Closed by chrisduerr** 2020-08-14 21:38 UTC
Labels: B - performance, H - macos
