### ISSUE TITLE
Exact fit snap window resize

### ISSUE THREAD

**Issue by camsteffen** [alacritty/alacritty#3750] opened 2020-05-18 21:33 UTC
The Alacritty window should "snap-to-grid" so that the window is always exactly big enough to fit a grid of characters. This functionality is available in iTerm2 and Terminal on macOS (and probably others).

**Comment by chrisduerr** [comment] 2020-05-18 23:42
Such an option is available during window creation. Is your request to support that during resize?

While Alacritty might be able to attempt this, it's not possible on all platforms and it probably doesn't play well with those that don't.

**Comment by camsteffen** [comment] 2020-05-18 23:51
Yes, I mean during resize.

**Comment by kchibisov** [comment] 2020-05-18 23:55
In general such thing works only on stacking wms, and also you should be allowed to set size yourself. On tiling wms this code won't work and could lead to glitches and oob rendering, I guess.

**Comment by camsteffen** [comment] 2020-05-19 00:03
@kchibisov I would expect the exact-fit behavior to be disabled in those cases.

**Comment by kchibisov** [comment] 2020-05-19 00:06
The thing is that we don't know about such cases at all. We have no idea that we're on stacking or tiling wm. On macOS that works, but because macOS is stacking by default, I'm not sure that it'll work well if you decide put a tiling wm, like yabai on it. On Wayland/X11 it won't work as well.

**Comment by camsteffen** [comment] 2020-05-19 00:08
Can you detect when the user is resizing the window with the mouse?

**Comment by kchibisov** [comment] 2020-05-19 00:14
I can resize with a mouse in a tiling wm.

**Comment by camsteffen** [comment] 2020-05-19 00:20
Hmm okay. Well that's all I have to offer. 😄

**Comment by mitar** [comment] 2020-09-01 21:57
I think this is related to #1702. It seems tiling managers use information from the app about the grid to resize them. Not that the app has to do anything special about it. I would still like to see resizing by characters when app itself is resizing the app (and not the manager), I opened #4198 for something related.

**Comment by marioroy** [comment] 2020-09-01 22:54
> I can resize with a mouse in a tiling wm.

With regards to resizing, is it possible to expand/shrink the window only when the mouse pointer reach enough pixels to contain the full character width/height? Notice how Gnome Terminal expands/shrinks at character width/height intervals, not pixel.

**Comment by johnmmcgee** [comment] 2020-10-11 05:20
I agree that a snap to column would be a nice feature to be able to enable.  I can understand not having it on by default, but however for those of us that would enjoy the feature that would be great.

I load tmux by default and i found that dynamically resizing windows in gnome gives me an odd border.

**Comment by johnmmcgee** [comment] 2020-10-12 00:32
Just to add to my comment, kitty has a similar option, resize_in_steps.

**Comment by chrisduerr** [comment] 2021-01-05 14:27
Duplicate of https://github.com/alacritty/alacritty/issues/388.

**Closed by chrisduerr** 2021-01-05 14:27 UTC
Labels: enhancement
