### ISSUE TITLE
Residue on resize

### ISSUE THREAD

**Issue by McPatate** [alacritty/alacritty#4627] opened 2020-12-30 10:50 UTC
Hello everyone,

I've been seeing what I call residue on my terminal's background when I resize. It has no impact on usability.

### System

OS: macOS Big Sur 11.1
Version: alacritty 0.6.0 (04cbf76)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
```
mc@mcpotatos-macbook-pro ~/D/mc_config (master)> /Applications/Alacritty.app/Contents/MacOS/alacritty  -vv
[2020-12-30 11:44:04.452352000] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
Created log file at "/var/folders/67/61zkrjjj39d17m_ldy49z7bh0000gn/T/Alacritty-25800.log"
[2020-12-30 11:44:04.453438000] [INFO ] [alacritty] Welcome to Alacritty
[2020-12-30 11:44:04.453470000] [INFO ] [alacritty] Configuration files loaded from:
[2020-12-30 11:44:04.453483000] [INFO ] [alacritty]   "/Users/mc/.config/alacritty/alacritty.yml"
[2020-12-30 11:44:04.497774000] [DEBUG] [alacritty] Estimated DPR: 2
[2020-12-30 11:44:04.498154000] [DEBUG] [alacritty] Estimated window size: None
[2020-12-30 11:44:04.498170000] [DEBUG] [alacritty] Estimated cell size: 13 x 26
[2020-12-30 11:44:04.549010000] [INFO ] [alacritty] Device pixel ratio: 2
[2020-12-30 11:44:04.552488000] [INFO ] [alacritty] Initializing glyph cache...
[2020-12-30 11:44:04.566586000] [INFO ] [alacritty] ... finished initializing glyph cache in 0.014023708s
[2020-12-30 11:44:04.566671000] [INFO ] [alacritty] Cell size: 13 x 26
[2020-12-30 11:44:04.566686000] [INFO ] [alacritty] Padding: 0 x 0
[2020-12-30 11:44:04.566700000] [INFO ] [alacritty] Width: 1600, Height: 1200
[2020-12-30 11:44:04.567101000] [INFO ] [alacritty] PTY dimensions: Line(46) x Column(123)
[2020-12-30 11:44:04.575308000] [INFO ] [alacritty] Initialisation complete
[2020-12-30 11:44:04.603043000] [DEBUG] [alacritty_terminal] unknown device status query: 1337
```

Here's a picture of what I'm talking about :
<img width="498" alt="Screenshot 2020-12-30 at 11 46 09" src="https://user-images.githubusercontent.com/9112841/103346580-afcd1380-4a94-11eb-9a90-fbc4a11e3792.png">

**Comment by chrisduerr** [comment] 2020-12-30 11:24
Duplicate of #889.

**Closed by chrisduerr** 2020-12-30 11:24 UTC
