### ISSUE TITLE
Delay while starting emacs (only xterm-256color?)

### ISSUE THREAD

**Issue by quite** [alacritty/alacritty#3324] opened 2020-02-11 09:28 UTC
I'm seeing a delay when starting up a terminal emacs. TERM is xterm-256color.  `alacritty-terminfo` is not installed. Starting emacs 26.3 (an Arch system) like `emacs -q --no-init -nw`.

A blank `*scratch*` buffer appears immediately, but there is a delay of about 3 seconds before the expected emacs welcome buffer appears (with `Welcome to GNU Emacs [..]`). The same delay is there when emacs is told to open a file, say `/etc/protocols`, on startup (adding it to the command-line).  It takes a few seconds before the actual file-buffer appears.

*But*, moving into tmux with TERM=screen-256color, the delay is gone!

If I install `alacritty-terminfo` TERM becomes alacitty, and there is no delay! (but the terminal only has 8*2 colors!).

There is something fishy with the alacritty and emacs with the xterm terminfo?

### System

OS: Linux
Version: alacritty 0.4.2-dev (3b8ef3a0)
Linux/BSD: X11, i3

**Comment by chrisduerr** [comment] 2020-02-11 14:27
Can you test this with the latest Alacritty terminfo please? xterm-256color is not supported.

This seems like a duplicate of https://github.com/alacritty/alacritty/issues/3091.

**Comment by quite** [comment] 2020-02-11 14:56
Yes, with Alacritty terminfo and the `term-file-aliases` I get 256-color. And with the `xterm-extra-capabilities` the delay is gone. Wow, terminals.

**Closed** 2020-02-11 15:00 UTC
