### ISSUE TITLE
certain characters are not displayed / rendered correctly

### ISSUE THREAD

**Issue by mwallner** [alacritty/alacritty#3751] opened 2020-05-19 18:23 UTC
### Description
Using default [starship](https://starship.rs/) prompt, the `❯` character is not displayed corretly.
I'm currently using `Fira Code`, have tried a couple of other PL fonts - none are working in Alacritty (in Windows) - but everything is displayed corrently in Windows Terminal.
Noteworthy: it works in Alacritty on my Linux/Manjaro box.

![image](https://user-images.githubusercontent.com/5354972/82363194-c5159600-9a0d-11ea-8b61-c62d1a395410.png)

### System

OS: Windows 1909
Version: `alacritty 0.4.2 (f68de37)`
Windows: ConPTY backend

### Logs

Font/Terminal size: `alacritty -vv`
```
[2020-05-19 20:18:43.211823800] [INFO] Welcome to Alacritty
[2020-05-19 20:18:43.214580400] [INFO] Configuration loaded from "C:\Users\susot\AppData\Roaming\alacritty\alacritty.yml
"
[2020-05-19 20:18:43.223589000] [DEBUG] Estimated DPR: 2
[2020-05-19 20:18:43.225606900] [DEBUG] Estimated Cell Size: 19 x 39
[2020-05-19 20:18:43.226633000] [DEBUG] Estimated Dimensions: Some((2280, 1560))

~
❯ [2020-05-19 20:18:43.936311500] [INFO] Device pixel ratio: 2
[2020-05-19 20:18:43.995307900] [INFO] Initializing glyph cache...
[2020-05-19 20:18:44.057253000] [INFO] ... finished initializing glyph cache in 0.0609535s
[2020-05-19 20:18:44.084823400] [INFO] Estimated DPR correctly, skipping resize
[2020-05-19 20:18:44.085819000] [INFO] Cell Size: 19 x 39
[2020-05-19 20:18:44.086835000] [INFO] Padding: 0 x 0
[2020-05-19 20:18:44.087814300] [INFO] Width: 2280, Height: 1560
[2020-05-19 20:18:44.214811200] [INFO] PTY Dimensions: Line(40) x Column(120)
[2020-05-19 20:18:44.251814800] [INFO] Using ConPTY backend
[2020-05-19 20:18:44.272099800] [INFO] Initialisation complete
[2020-05-19 20:18:44.284884700] [DEBUG] Term::resize dimensions unchanged
[2020-05-19 20:18:44.302851400] [INFO] Width: 2280, Height: 1560
```

**Comment by kchibisov** [comment] 2020-05-19 18:25
update to latest master.

**Comment by kchibisov** [comment] 2020-05-19 18:25
Duplicate of #3127

**Closed by kchibisov** 2020-05-19 18:25 UTC
