### ISSUE TITLE
0.10.0 dev (master branch) can not input chinese by apple input method 

### ISSUE THREAD

**Issue by wendajiang** [alacritty/alacritty#5669] opened 2021-12-09 14:39 UTC
### System
OS: macOS (m1 pro silicon)
Version: 0.10.0 dev

problem： 
![image](https://user-images.githubusercontent.com/13445879/145416567-1811c25c-d4f6-4191-9371-3ef159eff1f6.png)

press 1 to choose 你好, but alacritty show ni hao

**Comment by wendajiang** [comment] 2021-12-09 14:40
eg.
release 0.9.0 build on m1 macbook, can input chinese, but press delete can delete alacritty character not only input method pinyin

**Comment by chrisduerr** [comment] 2021-12-10 02:14
Can you bisect which commit introduced this regression? I'd probably start with https://github.com/alacritty/alacritty/commit/4c6a763850a5dec0fa34d15e356dcba19875690a.

**Comment by wendajiang** [comment] 2021-12-13 02:28
Yes, I try to back to 8681f710, representation is equal release 0.9.0

**Comment by chrisduerr** [comment] 2021-12-13 12:26
> Yes, I try to back to 8681f71, representation is equal release 0.9.0

Are you claiming 8681f71 broke it? Because that's difficult to believe.

**Comment by wendajiang** [comment] 2021-12-14 02:51
No, I also think it start with 4c6a763 😂

**Comment by chrisduerr** [comment] 2021-12-14 02:54
You *think*? Are you guessing or have you actually confirmed it?

**Comment by wendajiang** [comment] 2021-12-14 03:01
> back

As I say, I try to git reset 8681f71, and the input is equal to release 0.9.0, and reset 4c6a763, it doesn't work.

**Comment by ArturKovacs** [comment] 2021-12-21 14:20
I have a suspicion that @wendajiang has an incorrect idea of what the expected behavior is.

@wendajiang please do the following steps in Alacritty
1. type "ni hao"
2. press <kbd>1</kbd>
3. press <kbd>return</kbd>

Does Alacritty show "你好" instead of "ni hao"? Because that's the intended behavior as far as I understand.

**Comment by chrisduerr** [comment] 2021-12-21 15:34
@ArturKovacs has the behavior changed? Or was it supposed to? Seems like there certainly seems to be a difference.

**Comment by ArturKovacs** [comment] 2021-12-21 17:10
Yes, it was supposed to change. Although due to my mistake it wasn't noted in winit's changelog.

This is the PR that changed the behavior: https://github.com/rust-windowing/winit/pull/1979

**Comment by wendajiang** [comment] 2021-12-28 08:46
> I have a suspicion that @wendajiang has an incorrect idea of what the expected behavior is.
> 
> @wendajiang please do the following steps in Alacritty
> 
> 1. type "ni hao"
> 2. press 1
> 3. press return
> 
> Does Alacritty show `你好` instead of `ni hao`? Because that's the intended behavior as far as I understand.

Unfortunately, when I do these steps, Alacrity still show `ni hao`, as when press 1, the input is already end, then press return, terminal see `ni hao` as command

**Comment by ArturKovacs** [comment] 2021-12-29 19:14
Thank you for checking.

I made a PR for `winit` that reverts the changes that caused this issue. https://github.com/rust-windowing/winit/pull/2119

**Comment by chrisduerr** [comment] 2021-12-29 20:10
@ArturKovacs Do you plan on releasing a new patch version? Would love to ensure Alacritty's 0.10.0 doesn't introduce a regression.

**Comment by ArturKovacs** [comment] 2021-12-31 07:04
> Do you plan on releasing a new patch version?

Good idea, I'll pursue a quick release.

**Comment by ArturKovacs** [comment] 2022-01-05 14:45
The new winit version, `0.26.1` has been released with the fix

**Comment by chrisduerr** [comment] 2022-01-06 03:32
Fixed in https://github.com/alacritty/alacritty/commit/50c7c2b469095d41a8fdf4c29589f39222a98f71.

**Closed** 2022-01-06 03:32 UTC
Labels: S - input, A - deps, B - regression
