### ISSUE TITLE
Long load time (42 seconds) and blank screen when used on super wide monitor 5120x1440p.

### ISSUE THREAD

**Issue by cwhyoung** [alacritty/alacritty#4205] opened 2020-09-06 11:09 UTC
Hi

I've been using Alacritty just fine on a standard high definition 1920x1080 monitor. I've recently being trying to use Alacritty on my superwide 32:9 monitor with a resolution of 5120x1440 but for some reason Alacritty takes over 40 seconds to load and is completely unusable when it loads. Blank screen and no command prompt. The compositing still works and I can see the background wallpaper.

Also, my superwide monitor has the option to be run as two separate monitors of 2560x1440 - when in this mode Alacritty on the same computer and everything else being the same starts up in under a second and is just fine, no problem. I'm not sure what it is about the superwide 5120 setting that causes the issue? Just wanted to report this, I could'n't see any similar reports or anything in the documentation about this so apologies if I've missed something.
[alacritty.yml.txt](https://github.com/alacritty/alacritty/files/5179525/alacritty.yml.txt)

### System

OS: Linux - Arch Linux x64
Kernel - 5.8.6-arch1-1
CPU - i9900k
RAM 64gb ddr4 
GPU: Nvidia RTX2080TI - Nvidia driver 450.66
Version: `alacritty --version` output
Linux: X11, Picom compositor and Xmonad as the WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

Created log file at "/tmp/Alacritty-26166.log"
[2020-09-06 11:45:57.061840838] [INFO] Welcome to Alacritty
[2020-09-06 11:45:57.061877271] [INFO] Configuration loaded from "/home/w/.config/alacritty/alacritty.yml"
[2020-09-06 11:45:57.319608110] [INFO] Device pixel ratio: 718.4166666666666
[2020-09-06 11:45:57.336047248] [INFO] Initializing glyph cache...
[2020-09-06 11:46:38.551498195] [INFO] ... finished initializing glyph cache in 41.215436738s
[2020-09-06 11:46:38.551530333] [INFO] Cell Size: 5918 x 11834
[2020-09-06 11:46:38.551535046] [INFO] Padding: 4310 x 4310
[2020-09-06 11:46:38.551548221] [INFO] Width: 14538, Height: 20454
[2020-09-06 11:46:38.560036199] [INFO] PTY dimensions: Line(1) x Column(1)
[2020-09-06 11:46:38.758237522] [INFO] Initialisation complete
[2020-09-06 11:46:38.758863914] [INFO] Width: 14539, Height: 20455

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
alacritty -vv
Created log file at "/tmp/Alacritty-27972.log"
[2020-09-06 12:01:01.763370233] [INFO] Welcome to Alacritty
[2020-09-06 12:01:01.763406243] [INFO] Configuration loaded from "/home/w/.config/alacritty/alacritty.yml"
[2020-09-06 12:01:01.913471993] [DEBUG] Estimated DPR: 718.4166666666666
[2020-09-06 12:01:01.913504884] [DEBUG] Estimated Cell Size: 5918 x 11834
[2020-09-06 12:01:01.913510319] [DEBUG] Estimated Dimensions: None
[2020-09-06 12:01:02.023240508] [INFO] Device pixel ratio: 718.4166666666666
[2020-09-06 12:01:02.024525802] [INFO] Initializing glyph cache...
[2020-09-06 12:01:43.389742272] [INFO] ... finished initializing glyph cache in 41.365202856s
[2020-09-06 12:01:43.389776711] [INFO] Cell Size: 5918 x 11834
[2020-09-06 12:01:43.389782587] [INFO] Padding: 4310 x 4310
[2020-09-06 12:01:43.389796755] [INFO] Width: 14538, Height: 20454
[2020-09-06 12:01:43.397538766] [INFO] PTY dimensions: Line(1) x Column(1)
[2020-09-06 12:01:43.503308894] [INFO] Initialisation complete
[2020-09-06 12:01:43.503510031] [DEBUG] New num_cols is 2 and num_lines is 2
[2020-09-06 12:01:43.551670977] [INFO] Width: 14539, Height: 20455
[Alacritty-27972.log](https://github.com/alacritty/alacritty/files/5179522/Alacritty-27972.log)

Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment] 2020-09-06 11:52
duplicate of https://github.com/alacritty/alacritty/issues/3214

try `WINIT_X11_SCALE_FACTOR=1 alacritty` or set `Xft.dpi` in `.Xresources`.

**Closed by kchibisov** 2020-09-06 11:52 UTC

**Comment by cwhyoung** [comment] 2020-09-06 14:31
Thanks. That worked.
