### ISSUE TITLE
macOS: Typing in "@" with "option + L" does not work

### ISSUE THREAD

**Issue by NiklasA95** [alacritty/alacritty#6420] opened 2022-10-18 08:50 UTC
Typing in "@" with "option + L" in macOs does not work.
Interestingly enough sometimes it works if I type "option + L" two times in a row.
My expectation would of course be for it to work with a single "option + L".

Keyboard layout: German - QWERTZ

### System

OS: macOS
Version: 0.11.0

### Logs

Font/Terminal size:

[0.000003750s] [INFO ] [alacritty] Welcome to Alacritty
[0.000285958s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0b)
[0.000984583s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/namann/.config/alacritty/alacritty.yml"
[0.001454500s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.030762958s] [DEBUG] [alacritty] Loading "mononoki Nerd Font" font
[0.076197666s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.076261375s] [DEBUG] [alacritty] Estimated window size: None
[0.076280333s] [DEBUG] [alacritty] Estimated cell size: 10 x 20
[0.116593208s] [INFO ] [alacritty] Running on Apple M1
[0.116630250s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.119479458s] [INFO ] [alacritty] Display scale factor: 2
[0.128357875s] [INFO ] [alacritty] Font size changed to Size(36) with scale factor of 2
[0.128429250s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.137218000s] [INFO ] [alacritty] Cell size: 20 x 40
[0.137260083s] [INFO ] [alacritty] Padding: 0 x 0
[0.137279125s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.137409250s] [INFO ] [alacritty] PTY dimensions: 30 x 80
[0.139560375s] [INFO ] [alacritty] Initialisation complete
[0.164421458s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.188728083s] [INFO ] [alacritty] Padding: 0 x 0
[0.188768250s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.441504166s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1'],['~'],] at line 963

**Comment by chrisduerr** [comment] 2022-10-18 23:56
Did this change in 0.11, or has this never worked before?

**Comment by NiklasA95** [comment] 2022-10-19 06:39
Unfortunately it has not worked for the previous versions either.

**Comment by ccbiozhaw** [comment] 2022-10-19 13:29
hey i had the same issue today:

https://github.com/alacritty/alacritty/issues/6423

i managed to fix it by adding

alt_send_esc: false

to the config

**Comment by chrisduerr** [comment] 2022-10-20 00:50
Sounds like a duplicate of #458.

**Closed by chrisduerr** 2022-10-20 00:50 UTC
