### ISSUE TITLE
Always render emojis with default color

### ISSUE THREAD

**Issue by jsatk** [alacritty/alacritty#1864] opened 2018-12-05 23:19 UTC
<img width="738" alt="screen shot 2018-12-05 at 3 16 44 pm" src="https://user-images.githubusercontent.com/1005550/49550560-e11c8a80-f8a0-11e8-88e9-87fcbf6ba215.png">

I'm on macOS. Here's my ridiculous tmux status bar. I name all my windows emojis because it makes me happy. I tried out Alacritty. But was disheartened when I realized it inverts the color on any window tab with activity. And it's most noticeable if you use colorful emoji as your window titles.

**Comment by chrisduerr** [comment] 2018-12-05 23:34
Your terminal emulator might actually be telling Alacritty to invert the colors. Judging by the black/white mix, I'd assume that's exactly how that is achieved.

Now if emojis should be affected by that is a different question, but that's likely what's going on. So if you would set the manual color codes instead of using the inversion escape, that should resolve the problem.

**Comment by jsatk** [comment] 2018-12-05 23:42
That seems plausible, but this doesn't happen in Terminal or iTerm 2.

**Comment by chrisduerr** [comment] 2018-12-06 14:39
It's hard for me to test this since I do not have any colored emojis installed, but it should be pretty simple to try and reproduce that behavior.

Try running this escape sequence in bash:
`echo -e "\e[7mINVERTED: \U1F600\e[0mNORMAL: \U1F600"`

This should print one inverted emoji and one normal one. In theory both should look the same in iTerm/Terminal.app but look different in Alacritty.

Note that I don't think this works in the version of bash which is installed on macOS by default, so you might need to replace the unicode escapes with emojis yourself or update bash.

**Comment by chrisduerr** [comment] 2018-12-09 16:37
It should be possible to work around this by changing the formatting of the tmux statusline.

A more proper solution would be to prevent emojis from getting inverted though.

**Comment by jsatk** [comment] 2018-12-10 04:15
I'm not sure what you mean by "changing the formatting"?  It's the name of the window.  How do I tell tmux to render them not inverse?

**Comment by jsatk** [comment] 2018-12-13 00:03
@chrisduerr update: I noticed that this affects everything. Not just tmux. You probably already inferred that but I just wanted to make sure it was documented that emoji always invert their colors when highlighted.

**Comment by chrisduerr** [comment] 2019-03-07 20:03
Changed the title to include the following issue: https://github.com/jwilm/alacritty/issues/2160

**Comment by felipesere** [comment] 2019-04-21 16:35
@chrisduerr I'd like to give this issue a try!
Could you point me in the right direction? I wonder how to test that that emojis themselves are unaffected by inversion...

**Comment by chrisduerr** [comment] 2019-04-21 17:17
Cells are inversed [here](https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L286-L292) so any fix would likely be placed there too.

The tougher task would be figuring out what's an emoji and what isn't. I don't know if there's any official way to detect this and there might be, but if there's not we'd likely have to resort to matching the char value against a list of unicode characters to include (like everything in the range of 1F600—1F64F).

**Comment by ston1x** [comment] 2019-05-04 08:10
@chrisduerr I can't reach that file unfortunately. Is there any `mod.rs` in the project at all?
I would like to give this issue a try too.

**Comment by chrisduerr** [comment] 2019-05-04 10:08
Looks like the file has moved and I haven't linked to a fixed commit. This should be the correct path:
https://github.com/jwilm/alacritty/tree/34c54e7e0eb7c28406df112d118b82280be2adee/alacritty_terminal/src/term/mod.rs#L285-L294

**Comment by ston1x** [comment] 2019-05-08 15:53
@felipesere do you see a more appropriate solution? I think it is really possible to check `cell.c` against a list of emoji range in unicode but this way Alacritty would support emojis only manually, hence when new emojis appear, they will be inverted and should be manually added to the range.

**Comment by felipesere** [comment] 2019-05-08 15:55
I was wondering if there is either a crate with emojis or one could be built based on the Unicode lists/tables?

**Comment by ston1x** [comment] 2019-05-08 20:36
I am still confused about what is the root of the problem.

**Comment by ston1x** [comment] 2019-05-08 20:49
I am still confused about finding the root of the problem.
Here I have Solarized theme which renders emoji with wrong colors:
<img width="931" alt="Screen Shot 2019-05-08 at 11 34 43 PM" src="https://user-images.githubusercontent.com/13198813/57406725-2ba48900-71ea-11e9-9ddd-
2ddd16b5314b.png">  

And when I changed my colors to red, emoji have also changed their color so it seems that they depend on colors from the config.

And here I removed my colors from the config. Emoji are now rendered properly:
<img width="931" alt="Screen Shot 2019-05-08 at 11 34 03 PM" src="https://user-images.githubusercontent.com/13198813/57406730-2d6e4c80-71ea-11e9-940c-e5be53593fab.png">
But even with this proper rendering, they render differently in vim where I have custom colors. Their color is not constant as it is in other terminal emulators, it depends on what color scheme you have.

I will try to investigate and test it further, but it seems that emoji should be treated with an appropriate color explicitly (which is also used by default when you don't have any colors set).

**Comment by chrisduerr** [comment] 2019-05-08 21:19
Alacritty will not ignore emojis for coloring. So the same colors that are used for the text, will be used for the emojis, leading to the color weirdness that can be observed in this issue.

As mentioned previously, an exception for the color range of emojis would likely resolve this problem. Alternatively it could be checked if a glyph has more than one color, that would likely be a bit more universal, but probably also less efficient.

**Comment by jsatk** [comment] 2019-05-09 05:07
What is it about Alacritty that is different than every other terminal emulator in the way it handles rendering emoji?

**Comment by sersorrel** [comment] 2020-02-18 21:24
> The tougher task would be figuring out what's an emoji and what isn't.

Honestly, that looks _relatively_ easy; the `unic` crate [has a function for it](https://docs.rs/unic-emoji-char/0.9.0/unic_emoji_char/fn.is_emoji.html), though the crate hasn't been updated in a while (I assume but don't know that this affects what it considers emoji), so it may be better to use the (very large) official list of emoji [here](https://unicode.org/emoji/charts/full-emoji-list.html) instead. The difficulties I'm running into are a) telling when a cell is the second half of an emoji and b) understanding the existing colour-selection code!

**Comment by kchibisov** [comment] 2020-02-18 21:33
We do have proper tracking of whether the glyph is colored or not, we don't need any checks for is_emoji, etc, the comment isn't accurate anymore. This is a purely OpenGL task to render RGBA buffers differently, the main issue is our blending, etc.

**Closed** 2020-05-12 13:23 UTC
Labels: B - bug, S - render, help wanted
