### ISSUE TITLE
macOS: typing dead keys causes keypresses to be ignored shortly after backspace

### ISSUE THREAD

**Issue by pudiva** [alacritty/alacritty#6462] opened 2022-10-31 19:51 UTC
### The issue

~~On macOS (never seen it happen on Linux), a lot of times I open Alacritty I get this glitch in which I have to wait a little after pressing the backspace key, otherwise the keypresses that follow it don't register and are completely ignored.~~

~~I'm not 100% sure how to reproduce it, but it happens a lot on my system and, when it does, the backspace behaviour is very consistent and I can trigger it easily by pressing backspace followed by another key like `a`.~~

~~I tried to capture the glitch with `alacritty --print-events`, but every time I ran it like that, the bug simply didn't happen... I could trigger it quite easily after that by running Alacritty normally through Spotlight (cmd + space), so it's clearly trolling me. :trollface:~~

~~I'm not sure how to further diagnose it and would appreciate directions.~~

On macOS (never seen it happen on Linux), when I open up Alacritty and type a dead key such as `~` or <code>`</code>, it causes a glitch in which whenever I press backspace, it ignores further keypresses for a few moments.

The glitch happens consistently and I can reproduce it easily by quickly pressing backspace followed by another key, like `a`, which doesn't get printed on the screen nor prevents previously typed characters from being deleted (if I had pressed `a` before backspace). I usually stumble on it quite a lot when editing text on the terminal.

I tested the dead keys on other applications like macOS's default terminal, firefox and finder, and had no issues, so this really seems to be related to Alacritty.

### System

OS: macOS 12.6 (21G115)
Version: alacritty 0.11.0 (8dbaa0b)

### My whole ~/.alacritty.yml

```yaml
env:
  TERM: xterm-256color

font:
  size: 18

key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }
```

### Logs

~~No logs, it seems `alacritty --print-events` prevents the bug from happening. 🙁~~

[🪵 Alacritty-60214.log](https://github.com/alacritty/alacritty/files/9904772/Alacritty-60214.log)

### Video

Here's a little video of it happening:

https://user-images.githubusercontent.com/1148648/199110763-8213a18c-f42f-4c81-8917-8371e2df6758.mov

Thanks!!1 ✨✨✨

**Comment by kchibisov** [comment] 2022-10-31 20:02
Maybe the issue with some keyboard software you use? Since when you run it from terminal this software doesn't understand that you run application that way? Can you trigger the issue if you just run normally from CLI(without extra flags)?

**Comment by pudiva** [comment] 2022-10-31 20:18
Hah I just managed to capture it with `--print-events`, I had to run it from macOS standard terminal in order for it to trigger, not from within another Alacritty.

It's a big log, but the last couple keyboard events did trigger the glitch.

[🪵 Alacritty-60214.log](https://github.com/alacritty/alacritty/files/9904772/Alacritty-60214.log)

**Comment by pudiva** [comment] 2022-10-31 20:20
Btw I don't use anything fancy like Karabiner, and the only input magic I use is [Scroll Reverser](https://pilotmoon.com/scrollreverser/).

**Comment by kchibisov** [comment] 2022-10-31 20:25
Thx for the log, I'll try to have a look one I get time on how it could be fixed.

**Comment by pudiva** [comment] 2022-10-31 20:28
One more thing: to trigger the glitch, I had to `cd ~/Desktop`. It wouldn't trigger just from opening the terminal on my home directory. However going back home with `cd ~` didn't fix it... I'm not sure what exactly causes it.

**Comment by pudiva** [comment] 2022-10-31 20:31
Okay okay so it seems that the glitch is triggered by inputting `~`. I just opened a terminal here, tested it was fine and then typed in just `~` and it immediately triggered the glitch.

**Comment by pudiva** [comment] 2022-10-31 20:39
Also probably relevant: `~` is a deadkey on my system and requires two keypresses, the `~` itself and space, as I also use it to type ã, õ and ñ.

**Comment by kchibisov** [comment] 2022-10-31 20:42
Yeah, you need something like that to work with dead keys. You can also confirm by `Enter`.

**Comment by pudiva** [comment] 2022-10-31 21:09
I just updated the issue body and title to reflect the new findings and also added a screen recording of it happening.

**Comment by pstadler** [comment] 2022-11-04 11:57
Same problem here with Ventura / Alacritty 0.11.0, was driving me nuts...

It all works well until I've typed tilde once. From then on typing backslash, quickly followed by another character results in the character not being written most of the time.

**Comment by MarkusZoppelt** [comment] 2022-11-04 17:21
I have the same issue.

This thread helped me understand that it is triggered by typing dead keys since I couldn't reproduce the behaviour.

**Comment by chrisduerr** [comment] 2022-11-05 22:11
Duplicate of #62.

**Closed by chrisduerr** 2022-11-05 22:11 UTC
Labels: B - bug, H - macos
