### ISSUE TITLE
Allow controlling subpixel rendering independent of fontconfig

### ISSUE THREAD

**Issue by 1over137** [alacritty/alacritty#7666] opened 2024-01-26 12:12 UTC
This is mainly about Wayland.

Alacritty supports wp-fractional-scale-v1, meaning it can render text in a pixel perfect way at fractional scales. This allows you to use subpixel rendering without showing weird artifacts. However, many other applications do not, including all GTK3/4 and Qt5 applications, and they rely on rendering at 2x first, then downsampling. This is the same approach as MacOS, but MacOS doesn't use subpixel rendering, likely because even though this approach achieves a somewhat satisfactory effect, it breaks subpixel rendering, forcing you to turn it off in fontconfig. It would be great if we can turn on subpixel rendering independently in alacritty's config.

To see why this is a problem, set your monitor scale to 1.2 or 1.25 with subpixel rendering turned on in fontconfig. You notice strange color fringes in many applications, but not alacritty.

KeepassXC at 1.25x, noticeable color fringing because lcdfilter doesn't work when you downscale the raster:
![image](https://github.com/alacritty/alacritty/assets/22680475/e95d67b4-a380-4cf3-8df3-20dbe45dd1b5)

Firefox at 1.25x (experimental fractional scaling turned off, because it is very buggy).
![image](https://github.com/alacritty/alacritty/assets/22680475/65e1a367-98cf-4f66-aa5e-1fd9cbeef101)

Alacritty at 1.25x, everything rendered pixel-perfect
![20240126-070935](https://github.com/alacritty/alacritty/assets/22680475/662bdaba-c59f-4d85-9d4a-cd35b37ef909)

**Comment by kchibisov** [comment] 2024-01-26 12:23
I think duplicate of #957 

However I think you can set options individually for the apps in fontconfig, though, maybe we need to somehow communicate it...

**Closed by kchibisov** 2024-01-26 12:23 UTC
