### ISSUE TITLE
Option + N key binding sends an extra character?

### ISSUE THREAD

**Issue by siadat** [alacritty/alacritty#6612] opened 2023-01-10 19:16 UTC
### Description

Given the following key binding:
```yaml
- { key: N,        mods: Alt,     chars: "w" }
```

I press option+n and `w` appears, which is fine so far. But when I press `a` after that, I get `ã` instead of `a`.

Another way to describe this is that when I press option+n followed by `b`, I get `w˜b` instead of the desired `wb`.

This issue occurs only for option+n, other keys work as expected, e.g. option+m doesn't have this issue.

### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

### Logs

This is the logs for option+n followed by `a` then I close the window with mouse.

Keyboard and bindings: `alacritty --print-events`
<details>
<summary>logs</summary>

```
Created log file at "/var/folders/l3/bbj54gb56yj23hkr0mfrktcccddf4m/T/Alacritty-32792.log"
[0.000003649s] [INFO ] [alacritty] Welcome to Alacritty
[0.000246700s] [INFO ] [alacritty] Version 0.10.1 (2844606)
[0.000871703s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/sina/.config/alacritty/alacritty.yml"
[0.090866832s] [INFO ] [alacritty] Device pixel ratio: 1
[0.093641584s] [INFO ] [alacritty] Initializing glyph cache...
[0.136826352s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.043137739s
[0.136913098s] [INFO ] [alacritty] Cell size: 10 x 20
[0.136961941s] [INFO ] [alacritty] Padding: 0 x 0
[0.136972620s] [INFO ] [alacritty] Width: 800, Height: 600
[0.137788347s] [INFO ] [alacritty] PTY dimensions: 30 x 80
[0.141623561s] [INFO ] [alacritty] Initialisation complete
[0.158073411s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Id(140174816433168)))
[0.172814062s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.196778135s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(Title(sina@C02G719BML87: ~)) })
[0.196912724s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(Wakeup) })
[0.196942006s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.196963609s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Id(140174816433168)))
[0.196987119s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.215203155s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232299888737 }, requested_resume: None })
[0.234622309s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: Focused(true) }
[0.234719516s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.234742459s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.239771126s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232324467244 }, requested_resume: None })
[0.242130089s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.242220303s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.242252389s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232326953053 }, requested_resume: None })
[0.242303713s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.242331612s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.245717553s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232327051135 }, requested_resume: None })
[0.245861017s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.245912675s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.245936014s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232330635885 }, requested_resume: None })
[0.245961441s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.245977967s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.249103139s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232330696833 }, requested_resume: None })
[0.249216523s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.249243765s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.249264575s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232333964592 }, requested_resume: None })
[0.249287045s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.249301515s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.252430343s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232334021662 }, requested_resume: None })
[0.252562435s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.252597384s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.252628319s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232337325607 }, requested_resume: None })
[0.252665057s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.252686614s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.255987185s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232337415079 }, requested_resume: None })
[0.256157444s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.256189910s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.256215561s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232340913907 }, requested_resume: None })
[0.256245508s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.256263029s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.259421379s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232340983831 }, requested_resume: None })
[0.259512671s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.259537628s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.259560572s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232344259591 }, requested_resume: None })
[0.259582572s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.259600798s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.260576979s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232344318371 }, requested_resume: None })
[0.261087318s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.261128111s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.262925637s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232345852718 }, requested_resume: None })
[0.262993844s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.263050530s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.263074613s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232347773896 }, requested_resume: None })
[0.263103471s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.263151896s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.266458415s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232347873934 }, requested_resume: None })
[0.266574698s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.266671935s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.266695161s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232351394129 }, requested_resume: None })
[0.266720718s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.266735566s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.269619114s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232351454446 }, requested_resume: None })
[0.269727560s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.269752359s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.269793645s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232354491002 }, requested_resume: None })
[0.269830674s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.269856137s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.273686764s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232354580755 }, requested_resume: None })
[0.273810556s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.273828823s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.273854576s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232358553148 }, requested_resume: None })
[0.273890949s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.273908898s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.277617856s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232358625827 }, requested_resume: None })
[0.277693956s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.277710173s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.277727844s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232362428288 }, requested_resume: None })
[0.277748456s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.277760934s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.281068182s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232362500609 }, requested_resume: None })
[0.281189666s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.281212540s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.281235216s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232365934673 }, requested_resume: None })
[0.281262803s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.281278451s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.570455685s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232365996624 }, requested_resume: None })
[0.573308173s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.573435409s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.742394239s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232658202227 }, requested_resume: None })
[0.743155232s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.743291175s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.058859734s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229232828056607 }, requested_resume: None })
[2.061229364s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
[2.061343631s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: ModifiersChanged(ALT) }
[2.061379033s] [INFO ] [alacritty] glutin event: MainEventsCleared
[2.061407046s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.239157571s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229234146155239 }, requested_resume: None })
[2.240189552s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: Some(N), modifiers: ALT }, is_synthetic: false } }
[2.240279926s] [INFO ] [alacritty] glutin event: MainEventsCleared
[2.240317480s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.241344732s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229234326024797 }, requested_resume: None })
[2.241451265s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(MouseCursorDirty) })
[2.241501146s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(Wakeup) })
[2.241532388s] [INFO ] [alacritty] glutin event: MainEventsCleared
[2.241556306s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.328715702s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229234327918456 }, requested_resume: None })
[2.329274105s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 45, state: Released, virtual_keycode: Some(N), modifiers: ALT }, is_synthetic: false } }
[2.329359507s] [INFO ] [alacritty] glutin event: MainEventsCleared
[2.329391958s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.463875477s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229234414126784 }, requested_resume: None })
[2.465453802s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
[2.465585187s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: ModifiersChanged((empty)) }
[2.465635157s] [INFO ] [alacritty] glutin event: MainEventsCleared
[2.465735583s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[3.161780916s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229234550496433 }, requested_resume: None })
[3.174741220s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: (empty) }, is_synthetic: false } }
[3.174817411s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: ReceivedCharacter('ã') }
[3.174842359s] [INFO ] [alacritty] glutin event: MainEventsCleared
[3.174859683s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[3.175470453s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229235260165460 }, requested_resume: None })
[3.175528128s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(MouseCursorDirty) })
[3.175552266s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(Wakeup) })
[3.175572167s] [INFO ] [alacritty] glutin event: MainEventsCleared
[3.175590261s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[3.262394555s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229235261022614 }, requested_resume: None })
[3.262906827s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: (empty) }, is_synthetic: false } }
[3.263007173s] [INFO ] [alacritty] glutin event: MainEventsCleared
[3.263044479s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[5.072237915s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229235347785311 }, requested_resume: None })
[5.073559643s] [INFO ] [alacritty] glutin event: MainEventsCleared
[5.073659765s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[5.939986161s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229237158399181 }, requested_resume: None })
[5.947477330s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(DeviceId), event: Button { button: 0, state: Pressed } }
[5.947595458s] [INFO ] [alacritty] glutin event: MainEventsCleared
[5.947630075s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[6.007057312s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229238032358358 }, requested_resume: None })
[6.007271998s] [INFO ] [alacritty] glutin event: MainEventsCleared
[6.007316893s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[6.007360346s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229238092056491 }, requested_resume: None })
[6.008629287s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140174816433168)), event: CloseRequested }
[6.008711812s] [INFO ] [alacritty] glutin event: MainEventsCleared
[6.008741557s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[6.008789433s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { t: 229238093484289 }, requested_resume: None })
[6.008829145s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(Id(140174816433168))), payload: Terminal(Exit) })
[6.009938728s] [INFO ] [alacritty] glutin event: MainEventsCleared
[6.010017347s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[6.010130686s] [INFO ] [alacritty] glutin event: NewEvents(Poll)
[6.010238698s] [INFO ] [alacritty] glutin event: LoopDestroyed
[6.010337133s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/l3/bbj54gb56yj23hkr0mfrktcccddf4m/T/Alacritty-32792.log"

```
</details>

**Comment by siadat** [comment] 2023-01-10 19:28
Another observation: comparing option+n and option+m, the events differ for `ReceivedCharacter` events. Here's the ReceivedCharacter received after each key:

option+`n`:
```
(no events)
```
then `a`:
```
[2.646885225s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140485813668752)), event: ReceivedCharacter('ã') }
```
option+`m`
```
[11.990064850s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140485813668752)), event: ReceivedCharacter('µ') }
```
then `a`:
```
[14.141029802s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140485813668752)), event: ReceivedCharacter('a') }

```

**Comment by siadat** [comment] 2023-01-10 19:53
I upgraded to alacritty 0.11.0 (8dbaa0b) and it seems like the behaviour has changed. I still haven't figured out the new behaviour.

**Comment by chrisduerr** [comment] 2023-01-12 15:56
Duplicate of #62.

**Closed by chrisduerr** 2023-01-12 15:56 UTC
