### ISSUE TITLE
Crash on startup (macOS): 'A font must have a non-null family name.'

### ISSUE THREAD

**Issue by fhemberger** [alacritty/alacritty#6108] opened 2022-06-03 23:07 UTC
Alacritty crashes on macOS on startup. No custom `alacritty.yml` is defined.

### System

OS: macOS BigSur 11.6.6 (20G624)
Version: alacritty 0.10.1 (2844606)

### Logs

Crashes:
```
$ alacritty 
thread 'main' panicked at 'A font must have a non-null family name.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/core-text-19.2.0/src/font_descriptor.rs:223:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ RUST_BACKTRACE=1 alacritty 
thread 'main' panicked at 'A font must have a non-null family name.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/core-text-19.2.0/src/font_descriptor.rs:223:19
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::option::expect_failed
   4: crossfont::darwin::Descriptor::new
   5: crossfont::darwin::Descriptor::to_font
   6: <crossfont::darwin::Rasterizer as crossfont::Rasterize>::load_font
   7: alacritty::renderer::GlyphCache::load_regular_font
   8: alacritty::display::Display::new
   9: alacritty::event::Processor::create_window
  10: alacritty::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by chrisduerr** [comment] 2022-06-04 04:42
What's the output of `alacritty -v`?

**Comment by fhemberger** [comment] 2022-06-04 09:33
Unfortunately, it doesn't provide more information:

```
[0.000636401s] [INFO ] [alacritty] Welcome to Alacritty
[0.002597571s] [INFO ] [alacritty] Version 0.10.1 (2844606)
[0.006755700s] [INFO ] [alacritty_config_derive] No config file found; using default
thread 'main' panicked at 'A font must have a non-null family name.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/core-text-19.2.0/src/font_descriptor.rs:223:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fhemberger** [comment] 2022-06-04 10:19
Even tried rolling back to v0.10.0 or v0.9.0 … same issue. Haven't used Alacritty for a while on macOS, but it used to run smoothly on my machine.

**Comment by chrisduerr** [comment] 2022-06-04 17:46
Huh, so you're actually not using a config file, that's strange. I'd suggest either updating to Monterey or testing the latest Alacritty development version, though I'd assume the latter wouldn't help.

Is there anything noteworthy about your system and its fonts? Did you uninstall Menlo? What happens when you use the following config:

```yml
font:
  normal:
    family: Menlo
```

**Comment by fhemberger** [comment] 2022-06-04 19:07
> Huh, so you're actually not using a config file, that's strange. I'd suggest either updating to Monterey or testing the latest Alacritty development version, though I'd assume the latter wouldn't help.

Unfortunately, updating is not an option for me: As Apple deems my MBP Late 2013 no longer worthy of OS updates, I'm stuck on Big Sur.

> Is there anything noteworthy about your system and its fonts? Did you uninstall Menlo? What happens when you use the following config

Nothing which comes to mind. Menlo is installed and working. This minimal config doesn't work either. Even tried 'Arial', just to make sure it's not about the font.

**Comment by fhemberger** [comment] 2022-06-05 12:01
Tried that, didn't work.

```
thread 'main' panicked at 'A font must have a non-null family name.',
/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/core-text-19.2.0/src/font_descriptor.rs:223:19
```

Tried replacing the value temporarily:

```diff
    pub fn family_name(&self) -> String {
        unsafe {
+            let value = self.get_string_attribute(kCTFontNameAttribute);
-            let value = self.get_string_attribute(kCTFontFamilyNameAttribute);
            value.expect("A font must have a non-null family name.")
        }
    }
```

But ran into the next issue just a couple of lines below:
```
thread 'main' panicked at 'A font must have a non-null style name.',
/Users/frederic/.cargo/registry/src/github.com-1ecc6299db9ec823/core-text-19.2.0/src/font_descriptor.rs:237:19
```

🤷‍♂️

**Comment by chrisduerr** [comment] 2022-06-05 18:13
Unfortunately only the latest version of macOS is supported and even that I couldn't test myself. So you're on your own here.

With an old OS version, your only chance might be to run old Alacritty software. But realistically running a bunch of old software is not a great idea. Best suggestion I can make is to try and run Linux of your old MBP.

**Comment by sjml** [comment] 2022-06-09 19:59
For whatever it's worth, I'm seeing this same bug on Monterey with a fresh installation from the Homebrew Cask and no existing config file.

**Comment by chrisduerr** [comment] 2022-06-10 04:31
@sjml Have you managed to run it previously?

**Comment by sjml** [comment] 2022-06-10 04:36
> @sjml Have you managed to run it previously?

Yes, I tried it out in December but ended up uninstalling before getting too deep into it. No config files were left over, though.

**Comment by chrisduerr** [comment] 2022-06-10 04:40
Hm I don't actually have access to a macOS machine, but if someone is willing to look into what gets passed to [`<crossfont::darwin::Rasterizer as crossfont::Rasterize>::load_font`](https://github.com/alacritty/crossfont/blob/master/src/darwin/mod.rs#L135) that might already help.

**Comment by sjml** [comment] 2022-06-10 04:55
Happy take a look, but that's in a dependent project, not the central alacritty one, so the source doesn't come with this repository. Is there any dev-setup documentation to get it up and debuggable quickly? (Sorry, I know enough about Rust to write some code and do simple debugging, but haven't done anything with debugging dependencies as of yet.)

**Comment by chrisduerr** [comment] 2022-06-10 05:31
This should do it:

```diff
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index 888c9490..f2554887 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -28,7 +28,7 @@ serde_json = "1"
 glutin = { version = "0.28.0", default-features = false, features = ["serde"] }
 notify = "4"
 parking_lot = "0.11.0"
-crossfont = { version = "0.3.1", features = ["force_system_fontconfig"] }
+crossfont = { path = "/path/to/crossfont/project/root", features = ["force_system_fontconfig"] }
 copypasta = { version = "0.7.0", default-features = false }
 libc = "0.2"
 unicode-width = "0.1"
```

**Comment by kchibisov** [comment] 2022-06-10 05:37
Could someone provide `-vvv` log?

**Comment by sjml** [comment] 2022-06-10 05:39
> Could someone provide `-vvv` log?

Looks like it's still trying to use Menlo... which is installed and working fine in other programs. :-/ 

```
Created log file at "/var/folders/p5/ftgrlhrx2rx51pl63q_g_tnr0000gn/T/Alacritty-85887.log"
[0.000072041s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.000480625s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.000642125s] [TRACE] [crossfont] Family: Menlo
thread 'main' panicked at 'A font must have a non-null family name.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/core-text-19.2.0/src/font_descriptor.rs:223:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Deleted log file at "/var/folders/p5/ftgrlhrx2rx51pl63q_g_tnr0000gn/T/Alacritty-85887.log"
```

**Comment by sjml** [comment] 2022-06-10 05:43
> Hm I don't actually have access to a macOS machine, but if someone is willing to look into what gets passed to [`<crossfont::darwin::Rasterizer as crossfont::Rasterize>::load_font`](https://github.com/alacritty/crossfont/blob/master/src/darwin/mod.rs#L135) that might already help.

Looks like it's correctly trying to use the default... passing "Menlo" and a size of 22. (The `FontDesc` style data is just a binary blob, but let me know if it would be useful.)

**Comment by chrisduerr** [comment] 2022-06-10 06:43
@sjml Which language is your OS in?

**Comment by sjml** [comment] 2022-06-10 06:55
> @sjml Which language is your OS in?

English. Relevant environment variables: 
```
LC_ALL=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LANG=en_US.UTF-8
```

**Comment by chrisduerr** [comment] 2022-06-10 08:14
Pretty sure the issue is that one of the fallback fonts you have installed has a null family name and you hit that here:
https://github.com/alacritty/crossfont/blob/master/src/darwin/mod.rs#L82

Could you try to check for that, just by logging all the descriptions?

**Comment by sjml** [comment] 2022-06-10 11:32
> Pretty sure the issue is that one of the fallback fonts you have installed has a null family name and you hit that here: https://github.com/alacritty/crossfont/blob/master/src/darwin/mod.rs#L82
> 
> Could you try to check for that, just by logging all the descriptions?

I set the logging around the site you pointed to, but note that when I clone the crossfont repo to tag 0.3.1 (to match the dependency in alacritty's cargo file), [that function is very different](https://github.com/alacritty/crossfont/blob/f38f67a428055266592b17533b62a6e998350b9b/src/darwin/mod.rs#L73). If I try and build from master it doesn't compile. 

(Note too at least in 0.3.1 there are warnings about `family_name` and `display_name` being unused in the Descriptor, but that might just be because of the unsafe-ness around CF access?)

In any case, when I add `println!("{}", descriptor.family_name);` at line 83, it only prints "Menlo" before the panic.

**Comment by chrisduerr** [comment] 2022-06-10 12:53
@sjml You're printing it inside the `map` closure, right? Could you show me your diff real quick?

**Comment by chrisduerr** [comment] 2022-06-10 16:27
Yeah that diff doesn't look right, there should be a `map` somewhere below `fallbacks`. You need to check the descriptor in that map.

I don't think it's the primary font that is causing the issue here, I think you both have a fallback font installed on your system that does not have a valid family name.

**Comment by sjml** [comment] 2022-06-10 16:52
> Yeah that diff doesn't look right, there should be a `map` somewhere below `fallbacks`. You need to check the descriptor in that map.

I tried moving it here, but then the panic happens before anything prints. (Please correct my Rust if needed; I am at the high end of "beginner" on this language.)
```diff
diff --git a/src/darwin/mod.rs b/src/darwin/mod.rs
index 84137c7..1cf2288 100644
--- a/src/darwin/mod.rs
+++ b/src/darwin/mod.rs
@@ -81,11 +81,12 @@ impl Descriptor {
                 .map(|descriptor| {
                     let menlo = ct_new_from_descriptor(&descriptor.ct_descriptor, size);
 
+
                     // TODO fixme, hardcoded en for english.
                     let mut fallbacks = cascade_list_for_languages(&menlo, &["en".to_owned()])
                         .into_iter()
                         .filter(|desc| !desc.font_path.as_os_str().is_empty())
-                        .map(|desc| desc.to_font(size, false))
+                        .map(|desc| {println!("{:?}", desc); desc.to_font(size, false)})
                         .collect::<Vec<_>>();
 
                     // TODO, we can't use apple's proposed
```

> I don't think it's the primary font that is causing the issue here, I think you both have a fallback font installed on your system that does not have a valid family name.

Oh, I'm 100% with you that this is likely something screwy on my system, but where would it be getting defined as a fallback, though? There's no alacritty config file, so it wouldn't be from there. And as far as I know there's not a way to change the macOS fallback fonts without disabling SIP, which hasn't been done on this machine.

**Comment by chrisduerr** [comment] 2022-06-10 17:27
> I tried moving it here, but then the panic happens before anything prints.

Huh, okay. Would probably take a little more effort to troubleshoot this then. Looking through the fonts you have installed might still give some clues though, maybe you can find something odd.

**Comment by sjml** [comment] 2022-06-10 19:17
To be sure, I just uninstalled all non-system fonts from both `~/Library/Fonts` and `/Library/Fonts`, leaving only the protected ones in `/System/Library/Fonts`, but am still having the panic, so I'm starting to think maybe it's not a problem with the installed fonts... :-/

**Comment by sjml** [comment] 2022-06-12 07:21
OK I think I have some more information that might be relevant. 

I did some tweaks to the `core-text` crate to investigate what was happening when it couldn't get a family name. Specifically, I added a log [here](https://github.com/servo/core-foundation-rs/blob/e51cf4186de61bcc0a51d3c2d796d1ccfd9e88a9/core-text/src/font_descriptor.rs#L222) to print out the font name attribute if it couldn't get the family name. 

Right before the panic, what I got was `CourierNewPSMT`. That was indeed a font installed on my system, **but** it was disabled in Font Book. 

Once I re-enabled it and ran again, the list got much further, but this time it panicked right after `Kailasa` which, you guessed it, was disabled. 

So this might be an upstream bug in `core-text` where it's not properly able to query fonts that are installed but disabled. I'll investigate if there's anything more clever crossfont can do to not pay attention to disabled fonts.

**Comment by fhemberger** [comment] 2022-06-12 07:39
@sjml Looks like you're on to something. I have disabled fonts on my system as well (all the asian, cyrillic and hebrew fonts that ship with macOS, for example).

**Comment by sjml** [comment] 2022-06-12 07:47
Looks like we could query `kCTFontEnabledAttribute` but core-text doesn't provide an accessor to it. I hacked in an `is_enabled` method and a an associated `get_number_attribute` and can confirm that if I filter the list at the end of `cascade_list_for_languages` with my `is_enabled` check, alacritty starts up just fine. 

So, @chrisduerr, I leave it to you how to proceed -- is this something you'd want bring into crossfont, or file an upstream bug with core-text?

**Comment by sjml** [comment] 2022-06-12 08:04
> @sjml Looks like you're on to something. I have disabled fonts on my system as well (all the asian, cyrillic and hebrew fonts that ship with macOS, for example).

Definitely try re-enabling things and seeing if that gets it running, just to confirm. (I know you're on a resource-constrained system, but just for the sake of testing...)

**Comment by kchibisov** [comment] 2022-06-12 09:02
@sjml I think we can try to patch crossfont, though, patching core-text would also be fine. I think we already do something like that in crossfont.

**Comment by fhemberger** [comment] 2022-06-12 09:15
@sjml Re-enabled all fonts and even cleared the macOS font cache:

```
sudo atsutil databases -remove
atsutil server -shutdown
atsutil server -ping
```

Still the same issue with v0.10.1. 🤷‍♂️  But I'm happy to test any patches you come up with.

**Comment by sjml** [comment] 2022-06-12 11:33
> @sjml I think we can try to patch crossfont, though, patching core-text would also be fine. I think we already do something like that in crossfont.

Should I have a go at a PR? I'm happy to do it, but someone who knows the system better would likely do a quicker job of doing in a way that works well with what's already there...

**Comment by kchibisov** [comment] 2022-06-12 11:41
yeah, go ahead. we can always help you clean it up if something is wrong.

**Comment by chrisduerr** [comment] 2022-06-12 13:30
@sjml Great work, thanks for looking into this. I'm not sure this is something that should be changed in core-text, since core-text is correctly returning a list of all fonts and loading that font is only a slightly related matter.

That said, if they'd be willing to change something about this it would benefit more people than just Alacritty, so it might be worth it to raise the issue upstream at least. But I feel like this is likely going to land in crossfont.

**Comment by sjml** [comment] 2022-06-12 14:14
> I'm not sure this is something that should be changed in core-text

Yeah, that was my instinct, too. The only thing that might be nice to have there is a method to tell if a font is disabled or not; I'm gonna plug a little special function into crossfont that does the same, but it's mostly by copy/pasting from core-text, so feels like that might be the better long term home for it. 

I'll make the PR shortly. Should I base on v0.3.1?

**Comment by chrisnc** [comment] 2022-07-10 04:32
I think the uprev of `crossfont` in #6186 may fix this?

**Closed** 2022-07-15 21:56 UTC
Labels: help wanted, S - font, H - macos

**Comment by fhemberger** [comment] 2022-07-16 06:56
Compiled the main branch, can confirm it works for me. 🎉 
Just wanted to say a big thank you to everyone involved hunting down and fixing this, you are awesome! 💪
