### ISSUE TITLE
Font ligatures doesn't work

### ISSUE THREAD

**Issue by Mdsp9070** [alacritty/alacritty#3700] opened 2020-05-08 14:33 UTC
### System

OS: Manjaro
Version: alacritty 0.4.2
Linux/BSD: X11
### Bug
Font ligatures doesn't seems to work with any font that supports it.

I've tried with Cascadia, Fira Code, Dank Mono, Lilex and others.

![Screenshot from 2020-05-08 11-30-13](https://user-images.githubusercontent.com/44469426/81415838-55ef9600-911f-11ea-89d8-b85baafbee6d.png)

There's a specific configuration to enable it?

**Comment by kchibisov** [comment] 2020-05-08 14:34
duplicate of #50

**Closed by kchibisov** 2020-05-08 14:34 UTC
