### ISSUE TITLE
Signal WINCH not signaled consistently for (n)curses apps

### ISSUE THREAD

**Issue by marioroy** [alacritty/alacritty#4188] opened 2020-08-31 03:38 UTC
I tested Alacritty version 0.5.0 on MacOS, Linux, and Windows.

Testing: Run midnight commander (mc) inside Alacritty. Hold the mouse down and resize the window down and up and right and left multiple times without releasing the mouse. Notice that sometimes, once stopped (mouse released), the application fails to resize fully inside Alacritty. The behavior is not specific to `mc` but also other (n)curses-based applications that resize upon receiving the `WINCH` signal.

Compare with iTerm2 and Gnome Terminal. Midnight commander resizes consistently and fully.

Regards.

**Comment by chrisduerr** [comment] 2020-08-31 04:23
Have you actually verified that this has anything to do with `WINCH` at all?

**Comment by marioroy** [comment] 2020-09-01 20:34
Hi. I tried resizing slower. Cygwin and Gnome terminals resize by font width and/or height steps. Alacritty appears to resize fluidly not accounting for the font width/height. This can leave empty vertical/horizontal gaps if the remaining space is less than the font width/height. I vote for the terminal application to resize by font width and height steps. Otherwise, the user is required additional horizontal/vertical resize adjustments, so to rid of any gap due to less than font width/height.

Gnome Terminal appears to increase the width of the window when the width % font_width = 0. Ditto for height.

**Comment by chrisduerr** [comment] 2020-09-01 20:41
Isn't that a completely different issue?

**Comment by marioroy** [comment] 2020-09-01 21:19
The issue is resizing a (n)curses application may not fill the window fully (i.e. gaps on the right and bottom). It may require extra effort on the users part to resize the window precisely so that the window width and height (mod) font_width and font_height (equals zero) respectively.

**Comment by kchibisov** [comment] 2020-09-01 21:29
>The issue is resizing a (n)curses application may not fill the window fully (i.e. gaps on the right and bottom). It may require extra effort on the users part to resize the window precisely so that the window width and height (mod) font_width and font_height (equals zero) respectively.

So the thing you want is that resizing is done in a way that there's no padding around the window? If that's the case it has nothing to do with `WINCH`. It's not something really possible in some cases tbqh, like on tiling wms, and on Wayland it could lead to very interesting behavior, like drawing out side of window borders.

In a stacking wms it's fine to do so, I guess.

**Comment by marioroy** [comment] 2020-09-01 22:27
Correct, not WINCH related after closer look. Resizing a (n)curses application works fine in Cygwin Terminal, Gnome Terminal, and iTerms2 including Terminal on macos. Notice how the window expands only when the mouse pointer reaches enough pixels (font_width, font_height to accommodate room for another column, row respectively). Ditto for shrinking.

**Comment by chrisduerr** [comment] 2020-09-02 02:55
Duplicate of https://github.com/alacritty/alacritty/issues/3750.

**Closed by chrisduerr** 2020-09-02 02:55 UTC
Labels: A - needs repro
