### ISSUE TITLE
Faded lines appear on maco

### ISSUE THREAD

**Issue by fuzunspm** [alacritty/alacritty#3680] opened 2020-05-04 08:55 UTC
### System

OS: macOS
Version: alacritty 0.4.2 (f68de37)

If i switch focus from alacritty, let new lines appear and switch back focus some lines appear faded and top of each other. It's not visible on screenshots

**Comment by kchibisov** [comment] 2020-05-04 08:58
If something is not visible on screenshots it could be a GPU issue.

**Comment by fuzunspm** [comment] 2020-05-04 10:52
i managed to take a screen shot, i think i couldn't do this because while taking screenshot it focus alacritty window which fixes the display issue

[screenshot](https://send.firefox.com/download/0ee2addb10b9e414/#MHtwmu84ZWsFpQWIW4cmXg)

**Comment by kchibisov** [comment] 2020-05-04 10:57
Was window transparent?

**Comment by fuzunspm** [comment] 2020-05-04 11:10
yes it was

**Comment by chrisduerr** [comment] 2020-05-04 12:21
Sounds like a duplicate of https://github.com/alacritty/alacritty/issues/889?

**Closed** 2020-05-04 12:26 UTC

**Comment by fuzunspm** [comment] 2020-05-04 12:36
> Sounds like a duplicate of #889.

Yes it’s, I searched for this issue but couldn’t find it
