### ISSUE TITLE
Drag & dropping a file into the terminal does not work

### ISSUE THREAD

**Issue by WhyNotHugo** [alacritty/alacritty#5518] opened 2021-09-28 11:42 UTC
### System

OS: ArchLinux
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: [swaywm](https://swaywm.org/)

### Description

Related to #1301 and #1304.

When dragging a file into the terminal, I'd like its path to be inserted. #1304 indicates that this has been implemented, but I don't know how to make this work (or maybe it's not implemented on Linux?).

Running `alacritty -vv` there's absolutely no log when I drag and drop a file into the terminal.

I'm happy to provide additional information that can help debug why it's not working.

**Comment by chrisduerr** [comment] 2021-09-29 00:04
It works on X11, but it might not work on Wayland.

**Comment by WhyNotHugo** [comment] 2021-12-03 14:21
> It works on X11, but it might not work on Wayland.

I'm using Wayland, so maybe the implementation is X11-specific?

**Comment by chrisduerr** [comment] 2021-12-03 19:23
I'd assume so. I think Wayland should support D&D with their data device stuff already, so it's probably a missing feature in winit.

**Comment by chrisduerr** [comment] 2021-12-03 19:28
https://github.com/rust-windowing/winit/issues/2083

**Comment by kchibisov** [comment] 2022-01-20 04:44
Duplicate of  #4010.

**Closed by kchibisov** 2022-01-20 04:44 UTC
Labels: H - linux, S - winit/glutin, A - deps, DS - Wayland, B - missing feature
