### ISSUE TITLE
Startup crash on X11 due to clipboard error

### ISSUE THREAD

**Issue by joona** [alacritty/alacritty#6892] opened 2023-04-28 07:42 UTC
Alacritty crashes on startup, when trying to open 38th alacritty instance.

If I close one instance, alacritty starts up fine. Crash is reproducible whenever there's 37 instances running.

### System

OS: Linux 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Version: alacritty 0.13.0-dev
Linux/BSD: X11, Regolith, i3

### Logs

```
$ RUST_BACKTRACE=full alacritty -vv
Created log file at "/tmp/Alacritty-1488915.log"
[0.000000995s] [INFO ] [alacritty] Welcome to Alacritty
[0.000077644s] [INFO ] [alacritty] Version 0.13.0-dev
[0.000092686s] [INFO ] [alacritty] Running on X11
[0.000694254s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/joona/.config/alacritty/alacritty.yml"
                                     "/home/joona/.config/alacritty/themes/themes/palenight.yaml"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConnect(SetupFailed(SetupFailed { status: 0, protocol_major_version: 11, protocol_minor_version: 0, length: 9, reason: [77, 97, 120, 105, 109, 117, 109, 32, 110, 117, 109, 98, 101, 114, 32, 111, 102, 32, 99, 108, 105, 101, 110, 116, 115, 32, 114, 101, 97, 99, 104, 101, 100] }))', alacritty/src/clipboard.rs:56:57
stack backtrace:
   0:     0x55f8282d1b28 - <unknown>
   1:     0x55f82815177c - <unknown>
   2:     0x55f8282b66e5 - <unknown>
   3:     0x55f8282ba204 - <unknown>
   4:     0x55f8282b9e4d - <unknown>
   5:     0x55f8282ba785 - <unknown>
   6:     0x55f8282d20b4 - <unknown>
   7:     0x55f8282d1c54 - <unknown>
   8:     0x55f8282ba482 - <unknown>
   9:     0x55f827eefee3 - <unknown>
  10:     0x55f827ef0013 - <unknown>
  11:     0x55f827fb0f98 - <unknown>
  12:     0x55f82803c3b9 - <unknown>
  13:     0x55f827ffa670 - <unknown>
  14:     0x55f8280134f3 - <unknown>
  15:     0x55f827f793b9 - <unknown>
  16:     0x55f8282b5c66 - <unknown>
  17:     0x55f8280021ee - <unknown>
  18:     0x7f39caa29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19:     0x7f39caa29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  20:     0x55f827efafd5 - <unknown>
  21:                0x0 - <unknown>
Deleted log file at "/tmp/Alacritty-1488915.log"
```

```
Fri Apr 28 10:40:23 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 3000     Off  | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P0    26W /  80W |   4921MiB /  6144MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7518      G   /usr/lib/xorg/Xorg               2493MiB |
|    0   N/A  N/A     15687      G   /usr/bin/x-terminal-emulator       18MiB |
|    0   N/A  N/A     28991      G   /usr/bin/x-terminal-emulator       24MiB |
|    0   N/A  N/A     29618      G   /usr/bin/x-terminal-emulator       18MiB |
|    0   N/A  N/A     30256      G   ...RendererForSitePerProcess      226MiB |
|    0   N/A  N/A     62712      G   /usr/bin/x-terminal-emulator        9MiB |
|    0   N/A  N/A     66419      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A     67432      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A     70451      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A     79311      G   /usr/bin/x-terminal-emulator       42MiB |
|    0   N/A  N/A     82025      G   /usr/bin/x-terminal-emulator        9MiB |
|    0   N/A  N/A     96305      G   /usr/bin/x-terminal-emulator       42MiB |
|    0   N/A  N/A    115285      G   /usr/bin/x-terminal-emulator       22MiB |
|    0   N/A  N/A    117760      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    119051      G   ...RendererForSitePerProcess      156MiB |
|    0   N/A  N/A    263638      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    271229      G   /usr/bin/x-terminal-emulator      108MiB |
|    0   N/A  N/A    308847      G   /usr/bin/x-terminal-emulator      122MiB |
|    0   N/A  N/A    311389      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    316919      G   /usr/bin/x-terminal-emulator       42MiB |
|    0   N/A  N/A    323764      G   /usr/bin/x-terminal-emulator       42MiB |
|    0   N/A  N/A    538386      G   /usr/bin/x-terminal-emulator      228MiB |
|    0   N/A  N/A    700989      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    701855      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    740386      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    781420      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A    785039      G   /usr/bin/x-terminal-emulator      228MiB |
|    0   N/A  N/A   1036720      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1061753      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1078936      G   /usr/bin/x-terminal-emulator       70MiB |
|    0   N/A  N/A   1084210      G   /usr/bin/x-terminal-emulator       44MiB |
|    0   N/A  N/A   1087325      G   /usr/bin/x-terminal-emulator      119MiB |
|    0   N/A  N/A   1095703      G   /usr/bin/x-terminal-emulator       44MiB |
|    0   N/A  N/A   1108212      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1159366      G   /usr/bin/x-terminal-emulator       67MiB |
|    0   N/A  N/A   1199901      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1233376      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1238656      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1303194      G   /usr/bin/x-terminal-emulator       12MiB |
|    0   N/A  N/A   1332019      G   ...veSuggestionsOnlyOnDemand      116MiB |
|    0   N/A  N/A   1332232    C+G   ...445944328949918404,131072      362MiB |
|    0   N/A  N/A   1343597      G   ...RendererForSitePerProcess       22MiB |
+-----------------------------------------------------------------------------+
```

**Comment by joona** [comment] 2023-04-28 17:10
I just noticed that the error is `maximum number of clients reached`, so this must be coming from the X11. Clipboard library seems to be opening separate connection to X11 for every terminal.

However, after some digging I noticed that for every alacritty process, there will be 5 new connections opened to X11 socket, which doesn't sound right

```
$ sudo lsof -p $(pidof Xorg) | grep X11-unix | wc -l
245
```

After starting two new terminals I hit 255 and after that, further processes crash. This is probably due to the default 256 maxclients setting on X11. This issue seems to be related to https://github.com/alacritty/alacritty/issues/2735

**Comment by chrisduerr** [comment] 2023-04-29 11:50
Yeah this is a duplicate of #2735.

**Comment by chrisduerr** [comment] 2023-04-29 11:51
If you actually need that many windows open, you can use multi-window. That should probably help.

**Closed by chrisduerr** 2023-04-29 11:50 UTC

**Comment by kchibisov** [comment] 2023-04-29 16:31
New window as in using `CreateNewWindow` or `alacritty msg create-window`. If you want dedicated instances, bump the limit inside the Xorg config.

**Comment by joona** [comment] 2023-05-01 13:05
Thanks for the tip. This seems to work around the issue and seems to reuse the connections without spawning new ones.
