### ISSUE TITLE
Crashes immediately because vsync could not be set up

### ISSUE THREAD

**Issue by rodrigolece** [alacritty/alacritty#6023] opened 2022-04-25 01:11 UTC
Alacritty crashes without starting and complains about not being able to set up vsync (see logs below).

Reading other issues in this repo I can see that the vsync error is not a common one. If I manually start vsync using `export vblank_mode=1` alacritty can be started. However, I don't know what I'm dealing with and I do not want to mess up with that variable permanently (i.e. in more than one shell) unless I know it is safe to do.

### System

OS:Ubuntu 20.04.4 LTS, running X11, GNOME Shell 
Version: alacritty 0.10.1

### Logs

$ alacritty -vvv
Created log file at "/tmp/Alacritty-8481.log"
[0.000004826s] [INFO ] [alacritty] Welcome to Alacritty
[0.000235965s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000314752s] [INFO ] [alacritty] Running on X11
[0.001876793s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/user/.config/alacritty/alacritty.yml"
[0.078776655s] [TRACE] [crossfont] Number of fonts is 202
[0.078870701s] [TRACE] [crossfont] Got font path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", index=0
[0.078962138s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.084424862s] [DEBUG] [alacritty] Estimated DPR: 1
[0.084445932s] [DEBUG] [alacritty] Estimated window size: None
[0.084456111s] [DEBUG] [alacritty] Estimated cell size: 9 x 18
Deleted log file at "/tmp/Alacritty-8481.log"
Error: Error creating GL context; Received multiple errors. Errors: `[NoAvailablePixelFormat, OsError("Couldn't setup vsync: expected interval `1` but got `0`")]`

**Comment by chrisduerr** [comment] 2022-04-25 04:30
Never heard of that before. What graphics driver are you running? Did you manually disable vsync in your driver?

**Comment by rodrigolece** [comment] 2022-04-25 16:53
Sorry, I have almost no experience with anything graphical, drivers, cards, windowing...

After a quick google search for how to find my driver here's what I found (please let me know if you need the output of any other commands)

```
lshw -c video
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: HD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:132 memory:eb000000-ebffffff memory:a0000000-afffffff ioport:e000(size=64) memory:c0000-dffff
```

I've never manually disabled vsync, the only time I've manually changed anything is exporting `vblank_mode=1`.

**Comment by chrisduerr** [comment] 2022-04-26 00:32
Ah so Intel integrated graphics then. Out of curiosity are you able to test Wayland?

**Comment by rodrigolece** [comment] 2022-04-26 15:36
Not on my own but do you have a tutorial that you can recommend?

**Comment by rodrigolece** [comment] 2022-04-26 16:50
Actually it was pretty easy. If I switch to Wayland I get a different error: `xkbcommon: ERROR: couldn't find a Compose file for locale "en_GB.UTF8"`

It doesn't crash but it also doesn't open anything. It creates a small rectangle on the top left of my screen which I assume wants to be a new window but right now it's not that.

**Comment by chrisduerr** [comment] 2022-04-26 19:38
That sounds like you messed up generating your locale, which is really something you should fix. Either by generating the `en_GB.UTF-8` locale or by switching to `en_US.UTF-8` which is likely generated already.

**Comment by rodrigolece** [comment] 2022-04-26 21:06
Got it, I fixed the locale issue by generating `en_GB.UTF-8`. I don't get any more errors but I still cannot see the window.

The output of `alacritty -vvv` is now significantly longer so it can be found [here](https://github.com/alacritty/alacritty/files/8566873/alacritty.log).

**Comment by kchibisov** [comment] 2022-04-26 21:22
@rodrigolece if you move that window can you see prompt or something like that? Could also try empty config.

**Comment by rodrigolece** [comment] 2022-04-27 18:02
@kchibisov thanks, that is indeed alacritty's window. I can move it and resize it. the question now is why it's opening with a default size of 0 times 0.

**Comment by rodrigolece** [comment] 2022-04-27 19:45
It does, yes.

**Comment by retrotails** [comment] 2022-04-28 01:32
same issue here with x11+amdgpu after I turned off EnablePageFlip in my xorg.conf

**Comment by sshock** [comment] 2022-04-28 07:12
Related? https://github.com/alacritty/alacritty/issues/4491

**Comment by chrisduerr** [comment] 2022-04-29 01:25
@rodrigolece If you resize it though, it works? And have you tried setting fixed dimensions in Alacritty's config?

**Comment by wizardlink** [comment] 2022-05-02 01:32
> same issue here with x11+amdgpu after I turned off EnablePageFlip in my xorg.conf

I have the same issue, however, I don't have any issues whatsoever in Wayland like the @rodrigolece has, I also have created a `/etc/drirc` file setting `vblank_mode` to `0`:
```
<driconf>
   <device>
       <application name="Default">
           <option name="vblank_mode" value="0" />
       </application>
   </device>
</driconf>
```

Here is my error log:
```
Created log file at "/tmp/Alacritty-7785.log"
[0.000003126s] [INFO ] [alacritty] Welcome to Alacritty
[0.000039924s] [INFO ] [alacritty] Version 0.10.1
[0.000048110s] [INFO ] [alacritty] Running on X11
[0.000226692s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/wizardlink/.config/alacritty/alacritty.yml"
                                     "/home/wizardlink/.config/alacritty/dracula.yml"
[0.008482855s] [TRACE] [crossfont] Number of fonts is 65
[0.008503494s] [TRACE] [crossfont] Got font path="/home/wizardlink/.local/share/fonts/Fantasque Sans Mono Regular Nerd Font Complete Mono Windows Compatible.ttf", index=0
[0.008540252s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.009342827s] [DEBUG] [alacritty] Estimated DPR: 1
[0.009351644s] [DEBUG] [alacritty] Estimated window size: None
[0.009356483s] [DEBUG] [alacritty] Estimated cell size: 8 x 15
Deleted log file at "/tmp/Alacritty-7785.log"
Error: Error creating GL context; Received multiple errors. Errors: `[NoAvailablePixelFormat, OsError("Couldn't setup vsync: expected interval `1` but got `0`")]`
```

**Comment by rodrigolece** [comment] 2022-05-02 23:45
@chrisduerr I can resize normally, but even setting a default size in the config file the window starts as a speckle on the top left corner.

**Comment by chrisduerr** [comment] 2022-05-03 06:56
> @chrisduerr I can resize normally, but even setting a default size in the config file the window starts as a speckle on the top left corner.

I'd assume this is an unrelated issue then, potentially compositor-specific.

@wizardlink Have you created this config to try and fix this issue, or did you create it before? Just to be perfectly clear, if you're manually disabling vsync like @retrotails mentioned then Alacritty will not work and that is expected behavior.

As far as I understood @rodrigolece, he's running an unmodified system as far as GPU config is concerned.

**Comment by wizardlink** [comment] 2022-05-03 07:26
> > @chrisduerr I can resize normally, but even setting a default size in the config file the window starts as a speckle on the top left corner.
> 
> I'd assume this is an unrelated issue then, potentially compositor-specific.
> 
> @wizardlink Have you created this config to try and fix this issue, or did you create it before? Just to be perfectly clear, if you're manually disabling vsync like @retrotails mentioned then Alacritty will not work and that is expected behavior.
> 
> As far as I understood @rodrigolece, he's running an unmodified system as far as GPU config is concerned.
> 

I see, that makes more sense, then my issue is unrelated. I have not made these changes looking to fix the issue, I've made them because of my specific set-up, I have two monitors with different refresh rates so some applications (namely games) would have the incorrect refresh rate data and feel less snappy.

May I ask however, why is it that Alacritty does not works without it? Would it not be possible to implement a way to disable vertical synchronization and instead allow for a hard cap in render?

**Comment by Onyedika221** [comment] 2022-05-03 07:28
Okay, thanks for helping

**Comment by chrisduerr** [comment] 2022-05-03 09:24
> May I ask however, why is it that Alacritty does not works without it? Would it not be possible to implement a way to disable vertical synchronization and instead allow for a hard cap in render?

Because it's not designed to. Vsync is available on pretty much every system and if users choose to break this it's kinda on them. It's just the best scheduling method available on X11 as far as complexity is concerned.

On Wayland, Alacritty uses frame scheduling instead. So if you really don't want vsync, use Wayland.

**Comment by Onyedika221** [comment] 2022-05-03 10:24
What is the best to subscribe so I can make transactions with my trading
account, It’s always say Not Authorizes by Fiat

**Comment by rodrigolece** [comment] 2022-05-03 16:01
@chrisduerr Sorry, just to recap. Then the issue that I was facing running Ubuntu on X11 is expected right? For reasons that I will have trouble figuring out why, my system has vsync turned off but then it is safe for me to manually turn it on, for example in my startup script?

And on Wayland the issue of the default size of 0x0 is unrelated. Should I close this issue?

**Comment by chrisduerr** [comment] 2022-05-04 06:10
> For reasons that I will have trouble figuring out why, my system has vsync turned off but then it is safe for me to manually turn it on, for example in my startup script?

It is expected that Alacritty doesn't work without vsync on X11, yes. I'd assume that it's an issue with your driver if it's disabled without you doing anything, so Alacritty can't help with that.

> And on Wayland the issue of the default size of 0x0 is unrelated. Should I close this issue?

Yeah the Wayland issue should be completely unrelated and might be due to combination of Alacritty version + Compositor used.  I think it makes most sense to close this unless you have additional evidence that this can be fixed in Alacritty in a way other than supporting rendering without vsync.

**Closed by chrisduerr** 2022-05-04 06:10 UTC
