### ISSUE TITLE
opening links using keyboard

### ISSUE THREAD

**Issue by SleepyMario** [alacritty/alacritty#1725] opened 2018-10-30 12:02 UTC
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

Hello, thanks everyone for this fine terminal already. I was just wondering if there's ever going to be a feature where it'll be possible to select&open weblinks using keyboard only. For example in Termite it's possible to use Ctrl+Shift+X to select a link using a number, which will then be opened.
Feel free to burn me down as well :P I just thought it'd be useful, mainly for the rather selfish reason that I use it a lot, and am a beginner at coding.

**Comment by chrisduerr** [comment] 2018-10-30 16:11
https://github.com/jwilm/alacritty/issues/262 is kinda related to this.

I don't think there has been any decision which path will be taken to make it possible to click on links or start a selection. But as a heavy keyboard user myself, I'd like to see some option to do this myself.

**Comment by ubitux** [comment] 2020-01-21 12:02
For the record, here is how urxvt handles this:

![urxvt-url-select](https://user-images.githubusercontent.com/34467/72803281-0065ab00-3c4e-11ea-9b14-ca96d358fdd3.gif)

You can navigate/cycle through links (including the back-buffer) with `alt+u` (multiple times, or arrows), and you can open (`Enter`) or copy them (`y`). The copy is pretty useful.

**Comment by tinywrkb** [comment] 2020-04-28 12:49
In termite, you need first to switch to selection mode (`Ctrl+Shift+Space`) and then you can:

* Press `x` to show a hint for each URL in the currently displayed screen, and type the chosen hint to open it in the browser.  
Termite uses numbers for hints and will filter the hints based on the input from the user.  
There's no need to press `Enter` if the filter found only one hint.
* Or you can press `u` (`U`) to search (reverse search) for URLs in the terminal buffer (so it'll also scrolls back) in a similar fashion to the URXVT example above. The selected URL will be highlighted, and then press `Enter` to open the link in the browser.  
In contrast to the hint method, the URL search exits the selection mode after pressing `Enter` to open the highlighted URL.

The benefit of URXVT's url-select script is that it goes directly into URL selection mode and auto-highlight the last URL so for me in high occurrence rate I just need to press `Alt+u` (the URL selection mode keybinding) and then `Enter`.

![termite_example](https://user-images.githubusercontent.com/44030034/80488897-bb959280-8967-11ea-819c-7bdb5fb7abbb.gif)

**Comment by chrisduerr** [comment] 2020-06-22 12:44
I'm going to close this for now since the essence of the issue is resolved with vi mode.

Further usability optimizations like special link handling might come in the future, but I'll create a separate issue for that once vi and search have been tested for a while.

**Closed by chrisduerr** 2020-06-22 12:44 UTC
Labels: S - input, enhancement

**Comment by tinywrkb** [comment] 2020-08-14 14:09
Now that 0.5 is released, is it possible to have an umbrella bug report for Vi mode improvement that we can subscribe to considering this issue was closed?

**Comment by chrisduerr** [comment] 2020-08-14 19:54
No, but if you have specific suggestions that do not exist already feel free to report those.

**Comment by anlutro** [comment] 2020-09-01 19:53
Is this really something that could *only* be implemented in vi mode? I really don't care for the other features in vi mode - the only thing I need is to open URLs, most commonly the last one that was printed to the terminal.

I was considering writing up an issue on implementing simple URL cursor handling in vi mode, but I feel like there are so many alternative solutions that would be dismissed if I did that:

- A separate mode just for URL selection
- Being able to open URLs with the keyboard from the non-vi mode search functionality
- Being able to open the last URL printed in the terminal with a single keypress, not having to enter any modes

**Comment by goetzc** [comment] 2022-03-21 17:24
I opened #5965 for a way to open links without entering vi-mode and using the keyboard.
