### ISSUE TITLE
macOS Mission Control jank when Alacritty is in foreground

### ISSUE THREAD

**Issue by kashav** [alacritty/alacritty#5727] opened 2021-12-27 21:30 UTC
### System

OS: macOS 11.6, 2017 15-inch Intel i7
Version: v0.9.0 fresh install via dmg 

Also reproduces in a local `target/release/osx/Alacritty.app`, but _not_ in `target/debug/alacritty` / `target/release/alacritty`. Let me know if logs would help (and where I'd find them).

Can post screen recordings if others can't reproduce.

**Comment by chrisduerr** [comment] 2021-12-28 22:24
Could you maybe share *any* information at all on what this bug is actually about?

**Comment by kashav** [comment] 2021-12-28 22:51
oh, sorry, yeah. When alacritty is the foregrounded app on macos, the [mission control](https://support.apple.com/en-us/HT204100) animation stutters. Here's a recording: https://youtu.be/0pLTRybk8d8.

Let me know what other information would help.

**Comment by chrisduerr** [comment] 2021-12-28 23:22
Duplicate of https://github.com/alacritty/alacritty/issues/4474.

**Closed by chrisduerr** 2021-12-28 23:22 UTC
Labels: F - insufficent detail

**Comment by kashav** [comment] 2021-12-29 02:26
Thanks, that fixed it. Don't know why I didn't search first, sorry.
