### ISSUE TITLE
Intermittent Crash

### ISSUE THREAD

**Issue by fluidvanadium** [alacritty/alacritty#6509] opened 2022-11-18 00:39 UTC
### System

OS: Linux Ubuntu 22.04
Version: alacritty 0.11.0

### A Log

```sava@plastique:~$ RUST_BACKTRACE=1 alacritty
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
wl_shm_pool@27: error 2: shrinking pool invalid
thread 'main' panicked at 'failed to dispatch wayland event queue: Os { code: 71, kind: Uncategorized, message: "Protocol error" }', /home/sava/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.11.0/src/event.rs:1438:30
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1785:5
   3: alacritty::event::Processor::run::{{closure}}
   4: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
   5: winit::platform_impl::platform::EventLoop<T>::run_return
   6: alacritty::event::Processor::run
   7: alacritty::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by fluidvanadium** [comment] 2022-11-18 03:44
Another log

```[9788.343116770s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[9788.343148301s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[9788.343166510s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[9788.343198125s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[9788.343228309s] [DEBUG] [alacritty_terminal] Term got unhandled attr: CancelBlink
[9788.343288921s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44997, tv_nsec: 326275013 }, requested_resume: None })
[9788.343329633s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(Title(Zellij (red-sister) - sava@plastique: ~/rust-analyzer)) })
[9788.343357057s] [INFO ] [alacritty] glutin event: MainEventsCleared
[9788.343376028s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[9788.343485089s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44997, tv_nsec: 326472209 }, requested_resume: None })
[9788.343502286s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(CursorBlinkingChange) })
[9788.343517913s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(Title(Zellij (red-sister) - sava@plastique: ~/rust-analyzer)) })
[9788.343532313s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(CursorBlinkingChange) })
[9788.343545079s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(Wakeup) })
[9788.343560862s] [INFO ] [alacritty] glutin event: MainEventsCleared
[9788.344062907s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(94689759771264)))
[9788.344086313s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[9788.344124879s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44997, tv_nsec: 327112050 }, requested_resume: None })
[9788.344141226s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(Title(Zellij (red-sister) - sava@plastique: ~/rust-analyzer)) })
[9788.344156067s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(Bell) })
[9788.344168791s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(CursorBlinkingChange) })
[9788.344181323s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(94689759771264))), payload: Terminal(Wakeup) })
[9788.344194611s] [INFO ] [alacritty] glutin event: MainEventsCleared
[9788.367056590s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(94689759771264)))
[9788.367085299s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[9788.367118342s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44997, tv_nsec: 350105528 }, requested_resume: None })
[9788.367124955s] [INFO ] [alacritty] glutin event: MainEventsCleared
[9788.367348597s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(94689759771264)))
[9788.367355910s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[9788.368063736s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44997, tv_nsec: 351050676 }, requested_resume: None })
[9788.368083787s] [INFO ] [alacritty] glutin event: MainEventsCleared
[9788.368087858s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(94689759771264)))
[9788.368092337s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
wl_shm_pool@27: error 2: shrinking pool invalid
thread 'main' panicked at 'failed to dispatch wayland event queue: Os { code: 71, kind: Uncategorized, message: "Protocol error" }', /home/sava/.cargo/registry/src/github.com-1ecc6299db9ec823/alacritty-0.11.0/src/event.rs:1438:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Deleted log file at "/tmp/Alacritty-37008.log"```

**Comment by ThomasFrans** [comment] 2022-11-18 16:35
I think I experienced this same crash. Alacritty never crashed before, but I switched to Gnome wayland yesterday and today, while scrolling through Neovim, it just crashed. Sadly it wasn't launched from a terminal, so no log or backtrace.

**Comment by kchibisov** [comment] 2022-12-06 08:44
Duplicate of #6455

**Closed** 2022-12-06 08:44 UTC
Labels: F - duplicate, H - linux, B - crash, DS - Wayland
