### ISSUE TITLE
Option key binding on Mac stops working after opt-N

### ISSUE THREAD

**Issue by nevillelyh** [alacritty/alacritty#6405] opened 2022-10-15 03:19 UTC
Hi, I bind alt/option+* for zsh, vim, etc. After upgrading to 0.11.0, they stopped working after I press Opt-N which produces `˜`. After that Opt-B/F/P/N sends `∫ƒπ˜` instead. Git bisect lead to this commit: https://github.com/alacritty/alacritty/commit/7d708d53f7ecb4c64db10ae44e7f4fca47c29a85
Might have something to do with the `Ime` events handling? https://github.com/alacritty/alacritty/commit/7d708d53f7ecb4c64db10ae44e7f4fca47c29a85#diff-c32f38542d52895124f53e3425f4243a05391d1d2bd8640f371ac6e427be5d70R1215-R1221

`alacritty.yml`:
```
key_bindings:
  - { key: B,     mods: Option,    chars: "\x1bb"           }
  - { key: F,     mods: Option,    chars: "\x1bf"           }
  - { key: P,     mods: Option,    chars: "\x1bp"           }
  - { key: N,     mods: Option,    chars: "\x1bn"           }
```

### System

OS: macOS
Version: 0.11.0

### Logs

Keyboard and bindings: `alacritty --print-events`

```
[1.314345208s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
[1.314573875s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ModifiersChanged(ALT) }
[1.820994500s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 11, state: Pressed, virtual_keycode: Some(B), modifiers: ALT }, is_synthetic: false } }
[1.821180291s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ReceivedCharacter('∫') }
[1.937391916s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 11, state: Released, virtual_keycode: Some(B), modifiers: ALT }, is_synthetic: false } }
[2.559451958s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Pressed, virtual_keycode: Some(F), modifiers: ALT }, is_synthetic: false } }
[2.559648458s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ReceivedCharacter('ƒ') }
[2.672917416s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Released, virtual_keycode: Some(F), modifiers: ALT }, is_synthetic: false } }
[3.047486958s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 35, state: Pressed, virtual_keycode: Some(P), modifiers: ALT }, is_synthetic: false } }
[3.047669500s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ReceivedCharacter('π') }
[3.149256916s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 35, state: Released, virtual_keycode: Some(P), modifiers: ALT }, is_synthetic: false } }
[3.531262291s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: Ime(Enabled) }
[3.531402750s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: Ime(Preedit("˜", Some((2, 2)))) }
[3.610608333s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 406.3984375, y: 853.4765625 }, modifiers: ALT } }
[3.745489208s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 408.0, y: 866.359375 }, modifiers: ALT } }
[3.881176708s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
[3.881236500s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ModifiersChanged((empty)) }
[4.394571083s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[4.394736875s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ModifiersChanged(CTRL) }
[4.705918250s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: (empty) }, is_synthetic: false } }
[4.706058291s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ModifiersChanged((empty)) }
[4.854243208s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[4.854321125s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: ModifiersChanged(CTRL) }
[4.960734500s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(5505416896)), event: Ime(Commit("˜")) }
```

And after reverting the commit in question:

```
[8.644726041s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
[8.644920666s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: ModifiersChanged(ALT) }
[9.454727000s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 11, state: Pressed, virtual_keycode: Some(B), modifiers: ALT }, is_synthetic: false } }
[9.454851791s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: ReceivedCharacter('∫') }
[9.582399416s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 11, state: Released, virtual_keycode: Some(B), modifiers: ALT }, is_synthetic: false } }
[10.344857583s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Pressed, virtual_keycode: Some(F), modifiers: ALT }, is_synthetic: false } }
[10.345036875s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: ReceivedCharacter('ƒ') }
[10.520388791s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 3, state: Released, virtual_keycode: Some(F), modifiers: ALT }, is_synthetic: false } }
[11.512546500s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 35, state: Pressed, virtual_keycode: Some(P), modifiers: ALT }, is_synthetic: false } }
[11.512730333s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: ReceivedCharacter('π') }
[11.581976000s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 35, state: Released, virtual_keycode: Some(P), modifiers: ALT }, is_synthetic: false } }
[12.149527291s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: Some(N), modifiers: ALT }, is_synthetic: false } }
[12.225907875s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 45, state: Released, virtual_keycode: Some(N), modifiers: ALT }, is_synthetic: false } }
[12.440392875s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
[12.440566750s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(4926457088)), event: ModifiersChanged((empty)) }
```

**Comment by chrisduerr** [comment] 2022-10-15 16:51
What exactly happens when you press Option + N? You say it sends `∫ƒπ` but in your `--print-events` you press these buttons **before** Option + N, not after it?

**Comment by nevillelyh** [comment] 2022-10-15 17:48
Sorry let me clarify.
On Mac Opt-N is the ˜ (tilde) prefix for ñ, ã, õ, etc.
- So the first time I press Opt-N, it generates  `˜` with underscore waiting for the actual letter to decorate. This correlates with `Ime(Enabled)` & `Ime(Preedit("˜", Some(2, 2))` events.
- If I then press n/a/o without Opt, it produces ñ/ã/õ. `Ime(Preedit("", None))` & `Ime(Commit("ñ/ã/õ")` events.
- If I press Opt-N instead, it produces ˜ alone (the previous ˜ without a letter underneath), then another ˜ with underscore waiting for the letter. `Ime(Preedit("", None))`, `Ime(Commit("˜")` & `Ime("˜", Some(2, 2))`events.

I notice the main difference is that Opt-B/F/P produces ∫/π/ƒ without the `Ime` event, underscore or waiting for the letter. As they are shortcuts for these unicode letters, while Opt-N is the tilde prefix for letters like ñ/ã/õ.

Here's a complete log with Opt-N, a, Opt-N, Opt-N, Ctrl-C, Ctrl-C, Ctrl-D sequence.
[alacritty.log](https://github.com/alacritty/alacritty/files/9792737/alacritty.log)

**Comment by chrisduerr** [comment] 2022-10-15 18:19
@kchibisov Do you see a way to work around this? If macOS starts IME by itself, I think the only chance we have is patching winit to remap the option modifier? (#62)

**Comment by kchibisov** [comment] 2022-10-15 18:38
I guess so? I'm not that experiences with macOS IME.

**Comment by chrisduerr** [comment] 2022-10-15 18:43
Closing as a duplicate of #62. Rebinding all the option keys really is just a hack to work around #62, a proper solution would allow remapping modifiers.

**Closed by chrisduerr** 2022-10-15 18:43 UTC
