### ISSUE TITLE
Doesn't recognise # on UK Mac keyboard (Alt-3)

### ISSUE THREAD

**Issue by thisistherk** [alacritty/alacritty#1073] opened 2018-01-31 21:18 UTC
OSX 10.12.6.  Having problems getting a hash on UK Mac keyboard (done via Alt-3 rather than Shift-3), it seems to be interpreting it as a newline?  Other Alt-key combinations (e.g. the euro symbol on Alt-2) appear to work fine.

Tried adding:

    - { key: 3, mods: Alt, chars: "#" }

to key_bindings in alacritty.yml, but no difference in behaviour.  Works fine in Terminal and iTerm2.  Anything else I can try?   Thanks!

**Comment by okuuva** [comment] 2018-02-01 14:34
Probably related to / duplicate of #458.

**Comment by imjoshholloway** [comment] 2018-03-05 10:20
I've got a similar issue but only from within vim
A work around I've got is to put:
```
- { key: Key3,     mods: Alt,     chars: "\x23"                        }
```

**Comment by thisistherk** [comment] 2018-03-05 18:17
Nice one, that works in vim for me too :)  Still doesn't work in the shell, but I can live without that!

**Comment by sorenmortensen** [comment] 2018-04-04 18:25
I'm having this problem too. If I type <kbd>Alt</kbd> <kbd>3</kbd>, I get a `#` at the beginning of the line (rather than where my cursor was) and what seems like a newline. Does anyone have a workaround that works in the shell itself, rather than just vim? This is making it impossible for me to type the `#` symbol in Alacritty.

**Comment by acornq** [comment] 2018-07-07 09:08
I'm having the same issue with UK Mac keyboard. # inserts a # and newline/return. So effectively I can't use the hash key in vim or at the command prompt. Works fine in Terminal/iTerm2.

**Comment by etiago** [comment] 2018-08-30 19:34
Mixing the solutions from @thisistherk and @imjoshholloway , I managed to get it working both in the shell and in vim:

```
- { key: Key3,     mods: Alt,     chars: "#"                        }
```

@thisistherk 's  was using key `3` and @imjoshholloway 's was using the encoded hash instead of the actual character. Mixing the two does the trick for me 😄

**Comment by pwnorbitals** [comment] 2020-10-18 20:11
Not sure what to do of this issue as a good workaround exists, but we should still consider it a bug. Is the workaround still needed on latest releases ?

**Comment by samhh** [comment] 2020-10-19 10:36
Workaround was needed for me as of last month, not checked without it since.

**Comment by MarioAriasC** [comment] 2021-08-17 10:02
Still needed

**Comment by eggbean** [comment] 2021-09-26 07:53
I don't know if this is the same issue, but I am using Linux on a ThinkPad T480s with UK keyboard and I cannot get the correct code for Alt-Shift-3.

In bash: 
Ctrl-v, Alt-Shift-1 returns `^[!`
Ctril-v, Alt-Shift-2 returns `^["`
..but..
Ctrl-v, Alt-Shift-3 returns `£`, just as though only Shift-3 was pressed.

All the other keys on that row seem to work as expected. This does not happen on gnome-terminal and it still happens with no `alactritty.yml` file, so it's not anything in my settings or dotfiles.

**Comment by fakeharxy** [comment] 2021-11-26 14:03
So this is still an issue, brand new Alacritty user here. For some reason the workaround from the .yml didn't take, I had to add it to my own config, but it works - mostly. Randomly, the # doesn't actually appear in the terminal... but it is there, it works. In vim it works fine.

**Comment by bodazhao** [comment] 2022-01-23 15:56
did not expect typing `#` would require modifying config for it (on alacritty v0.10 + tmux + neovim)...

**Comment by jjant** [comment] 2022-07-28 11:22
Any plans to get this fixed upstream?

**Comment by marcelloromani** [comment] 2022-10-30 11:52
> I'm having the same issue with UK Mac keyboard. # inserts a # and newline/return. So effectively I can't use the hash key in vim or at the command prompt. Works fine in Terminal/iTerm2.

Still an issue with
Version 0.10.1 (1)

**Comment by marcelloromani** [comment] 2022-10-30 12:06
> Mixing the solutions from @thisistherk and @imjoshholloway , I managed to get it working both in the shell and in vim:
> 
> ```
> - { key: Key3,     mods: Alt,     chars: "#"                        }
> ```
> 
> @thisistherk 's was using key `3` and @imjoshholloway 's was using the encoded hash instead of the actual character. Mixing the two does the trick for me 😄

https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L558

Where does that line go? I find it pretty difficult to determine the place in the yaml hierarchy where that key binding list element should be placed by skimming the yaml file in the repo.

**Comment by marcelloromani** [comment] 2022-10-30 12:11
OK, in proper #rubberduck fashion, after writing the above comment I came up with the content of `~/.alacritty.yml` that fixed the issue for me:

```
$ cat ~/.alacritty.yml
```
```
key_bindings:
   - { key: Key3, mods: Alt, chars: "#" }
```

**Comment by marcelloromani** [comment] 2022-10-30 12:12
It doesn't really help that you start reading about Key bindings on line 558 but the actual config value doesn't show up until line 761 https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L761

**Comment by Integralist** [comment] 2022-12-16 21:14
I've had this fixed in the past with...

```
  - { key: Key3,     mods: Alt,     chars: "#"                        }
```

But since updating to the latest Alacritty (0.11.0) and it has suddenly stopped working?

Someone here suggested the following but that doesn't work for me...

```
  - { key: Key3,     mods: Alt,     chars: "\x23"                        }
```

**Comment by Serginho** [comment] 2022-12-17 18:05
Same problem than @Integralist , keys alt+1, alt+2 and alt+3 don't works, but alt+4 from here on out works property.

I'm using Magic keyboard (Spanish lang)

**Comment by kchibisov** [comment] 2023-07-01 12:30
I'm pretty sure with the help of `OptionAsAlt` on macOS you'll be able to type everything and with #6958 it'll allow more granular settings.

**Closed by kchibisov** 2023-07-01 12:30 UTC
Labels: B - bug, S - input
