### ISSUE TITLE
font rendering issue with character like y̆

### ISSUE THREAD

**Issue by kolokd** [alacritty/alacritty#3681] opened 2020-05-04 10:52 UTC
### System
OS: Linux
Version: 0.5.0-dev (7901b45)
Linux/BSD: Fedora 32 Gnome

it renders it inaccurately. mark on separate block

in `let y = "y̆";` mark is rendered with `"`

**Comment by kchibisov** [comment] 2020-05-04 10:56
duplicate of #1420

**Closed by kchibisov** 2020-05-04 10:56 UTC
