### ISSUE TITLE
Fallthrough key codes

### ISSUE THREAD

**Issue by Feresey** [alacritty/alacritty#3261] opened 2020-01-29 15:19 UTC
When I use WM hotkeys with open terminal, character codes that should be intercepted by DE / WM displays as keycodes.

### System

OS: Linux
Version: alacritty 0.4.1
Linux/BSD: X11, i3wm

### Logs

Crashes: no crashes
Font/Terminal size: does not matter
Keyboard and bindings:  [stdout.txt](https://github.com/alacritty/alacritty/files/4128796/stdout.txt), .I'm just tapping F1 (drop-down terminal hotkey)

![after tapping F1 twice](https://user-images.githubusercontent.com/33696249/73369420-a1460d00-42c3-11ea-8358-8a4b9d807e2f.png)

On version 0.4.0 everything worked as it should.

**Comment by kchibisov** [comment] 2020-01-29 15:20
Duplicate of #3109 , fixed on the latest master.

**Closed by kchibisov** 2020-01-29 15:20 UTC
Labels: DS - X11, F - duplicate, S - keybindings
