### ISSUE TITLE
Index out of bounds crash in copy-mode-vi in tmux

### ISSUE THREAD

**Issue by yangliping** [alacritty/alacritty#4109] opened 2020-08-11 07:17 UTC
Run tmux in alacritty, go to copy-mode-vi, and keep pressing `k` key to move cursor up. It will crash.

### System

OS: macOS
Version: alacritty 0.5.0 (a6681e3)
Tmux: tmux 3.1b

### Logs

Crashes: STDERR, STDOUT

```
thread 'main' panicked at 'index out of bounds: the len is 42 but the index is 18446744073709551573', /Users/travis/build/alacritty/alacritty/alacritty_terminal/src/term/search.rs:423:15
stack backtrace:
   0:        0x107d088b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he7a1622e2c1f4ea2
   1:        0x107c7ef6c - core::fmt::write::h45c5005fa193e31b
   2:        0x107d07e3b - std::io::Write::write_fmt::ha9fd5f96fa3bf97e
   3:        0x107d07635 - std::panicking::default_hook::{{closure}}::h994cc97f627cdeb3
   4:        0x107d06c4a - std::panicking::rust_panic_with_hook::h567f6b7892d83334
   5:        0x107d0b35a - rust_begin_unwind
   6:        0x107c7c86f - core::panicking::panic_fmt::h974978fe0384fe38
   7:        0x107c7c706 - core::panicking::panic_bounds_check::h5f5afe389c2a9185
   8:        0x107b140e1 - alacritty_terminal::term::search::<impl alacritty_terminal::term::Term<T>>::line_search_right::h973b112668e0bd95
   9:        0x107c206bd - alacritty::display::Display::draw::hea4554fd00e94d2d
  10:        0x107b40bc6 - alacritty::event::Processor<N>::run::{{closure}}::he2d2e8629bbb142f
  11:        0x107b3d24b - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::hf83fbd335a444a41
  12:        0x107d2fa7d - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::h6bf5fbb7c77d4df8
  13:        0x107d42688 - winit::platform_impl::platform::observer::control_flow_end_handler::hd30e763bb5bb0d83
  14:     0x7fff340e3335 - _ZL12preoptimized
  15:     0x7fff340e3267 - _ZL12preoptimized
  16:     0x7fff340e292c - _ZL12preoptimized
  17:     0x7fff340e1e3e - _ZL12preoptimized
  18:     0x7fff32d0eabd - _ZL12preoptimized
  19:     0x7fff32d0e7d5 - _ZL12preoptimized
  20:     0x7fff32d0e579 - _ZL12preoptimized
  21:     0x7fff31354039 - _ZL12preoptimized
  22:     0x7fff31352880 - _ZL12preoptimized
  23:     0x7fff3134458e - _ZL12preoptimized
  24:        0x107b205a1 - alacritty::event::Processor<N>::run::hd56a90aba0ebab01
  25:        0x107bda86b - alacritty::main::h287f4a4cd137c330
  26:        0x107d18406 - std::sys_common::backtrace::__rust_begin_short_backtrace::h280e92b10d6bfe7e
  27:        0x107bce579 - main
```

**Comment by chrisduerr** [comment] 2020-08-11 16:29
Could you give some more detailed instructions? I cannot reproduce this. If you compile Alacritty from source it should also come with a more useful backtrace, which would help a lot.

**Comment by kchibisov** [comment] 2020-08-11 18:16
Could you also share alacritty and tmux configurations?

**Comment by yangliping** [comment] 2020-08-12 01:37
Here's alacritty configuration

```
window:
  startup_mode: Maximized

font:
  normal:
    family: "DejaVu Sans Mono"

  bold:
    family: "DejaVu Sans Mono"

  italic:
    family: "DejaVu Sans Mono"

  size: 16.0


colors:
  primary:
    background: '0xe5e1ce'
    foreground: '0x4c2f2d'

  normal:
    black:   '0x000000'
    red:     '0xd81e00'
    green:   '0x00a300'
    yellow:  '0xdb7f00'
    blue:    '0x0329d6'
    magenta: '0xd834d6'
    cyan:    '0x009ad6'
    white:   '0xd6d6d6'

  bright:
    black:   '0x929292'
    red:     '0xd81e00'
    green:   '0x00a300'
    yellow:  '0xdb7f00'
    blue:    '0x0329d6'
    magenta: '0xd834d6'
    cyan:    '0x009ad6'
    white:   '0xffffff'

  dim:
    black:   '0x333333'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xdddddd'

shell:
  program: /usr/local/bin/tmux
  args:
    - '-2'
    - 'new-session'
    - '-A'
    - '-s'
    - 'main'
    - '-c'
    - '/Users/yangliping/Desktop'

key_bindings:
  - { key: NumpadEnter,             chars: "\n"                              }
  - { key: T,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["new-window", "-c", "/Users/yangliping/Desktop"] }}
  - { key: W,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["kill-pane"] }}
  - { key: LBracket, mods: Command|Shift, command: { program: "/usr/local/bin/tmux", args: ["previous-window"] }}
  - { key: RBracket, mods: Command|Shift, command: { program: "/usr/local/bin/tmux", args: ["next-window"] }}
  - { key: H,        mods: Command|Shift, command: { program: "/usr/local/bin/tmux", args: ["choose-buffer"] }}
  - { key: Left,     mods: Control, chars: "\x1bb"}
  - { key: Right,    mods: Control, chars: "\x1bf"}
  - { key: Back,     action:  ReceiveChar}
```

And tmux configuration

```
set -g default-shell /usr/local/bin/bash4
set -g mouse on
set -g history-limit 10000
setw -g mode-keys vi
bind-key -n DoubleClick1Pane select-pane \; copy-mode \; send-keys -X select-word \; send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -n TripleClick1Pane select-pane \; copy-mode \; send-keys -X select-line \; send-keys -X copy-pipe-and-cancel "pbcopy"
#bind-key -t vi-copy v begin-selection
#bind-key -t vi-copy y copy-pipe "pbcopy"
#bind-key -n C-n new-window

unbind-key C-b
set -g prefix `
bind-key ` send-prefix

set -g default-terminal "xterm-256color"

#------------
# status bar
#------------
set-option -g status-position top
set -g status-left ''
set -g status-right ''

# Basic status bar colors
#set -g status-fg colour242
#set -g status-bg colour7
set -g status-style fg=colour242
set -g status-style bg=colour7

# Current window status
#set -g window-status-current-bg colour153
#set -g window-status-current-fg colour235
set -g window-status-current-style fg=colour235
set -g window-status-current-style bg=colour153
```

**Comment by yangliping** [comment] 2020-08-12 01:48
More information added. I can not reproduce it locally. I run tmux in alacritty, then ssh into a server, run GNU screen in remote server, press `ctrl+a [` goto copy mode, then keep pressing `k` key, finally it crash. I used the binary version alacritty downloaded from github release page.

**Comment by chrisduerr** [comment] 2020-08-12 02:12
> I used the binary version alacritty downloaded from github release page.

Are you able to compile it from source? That would be very useful.

**Comment by yangliping** [comment] 2020-08-12 02:36
Follow the instruction [here](https://github.com/alacritty/alacritty/blob/master/INSTALL.md), download alacritty-0.5.0 source code, and then run `make app` to compile alacritty. 

Here's the backtrace. Looks like the same as I've provided before. What can I do to produce more useful backtrace?

```
$ export RUST_BACKTRACE=full
$ /tmp/alacritty-0.5.0/target/release/osx/Alacritty.app/Contents/MacOS/alacritty -v
Created log file at "/var/folders/m7/gxj4wq_j14n3nh_qctww_5k80000gn/T/Alacritty-12780.log"
[2020-08-12 10:31:02.642653000] [INFO] Welcome to Alacritty
[2020-08-12 10:31:02.642879000] [INFO] Configuration loaded from "/Users/yangliping/.config/alacritty/alacritty.yml"
[2020-08-12 10:31:02.813286000] [INFO] Device pixel ratio: 2
[2020-08-12 10:31:02.817538000] [INFO] Initializing glyph cache...
[2020-08-12 10:31:02.873689000] [INFO] ... finished initializing glyph cache in 0.056007154s
[2020-08-12 10:31:02.873823000] [INFO] Cell Size: 19 x 37
[2020-08-12 10:31:02.873893000] [INFO] Padding: 0 x 0
[2020-08-12 10:31:02.873938000] [INFO] Width: 1600, Height: 1200
[2020-08-12 10:31:02.874296000] [INFO] PTY dimensions: Line(32) x Column(84)
[2020-08-12 10:31:02.877716000] [INFO] Initialisation complete
[2020-08-12 10:31:03.041409000] [INFO] Width: 2880, Height: 1560
thread 'main' panicked at 'index out of bounds: the len is 42 but the index is 18446744073709551573', /private/tmp/alacritty-0.5.0/alacritty_terminal/src/term/search.rs:423:15
stack backtrace:
   0:        0x10306fb45 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h26e8f1b884bae128
   1:        0x102feb31c - core::fmt::write::ha0b53fc066268c71
   2:        0x10306f0cb - std::io::Write::write_fmt::h410b83a4c70c6549
   3:        0x10306e915 - std::panicking::default_hook::{{closure}}::h70c11ad9e0ccd806
   4:        0x10306df2a - std::panicking::rust_panic_with_hook::h3fc8a110bc9d166f
   5:        0x1030724aa - rust_begin_unwind
   6:        0x1030c074f - core::panicking::panic_fmt::h04439fd445b5f690
   7:        0x1030c0716 - core::panicking::panic_bounds_check::hc263834fbcdcaea9
   8:        0x102e85781 - alacritty_terminal::term::search::<impl alacritty_terminal::term::Term<T>>::line_search_right::h23928a36c01f3652
   9:        0x102f8e38d - alacritty::display::Display::draw::hb04edbe2f28d4f21
  10:        0x102eb1a76 - alacritty::event::Processor<N>::run::{{closure}}::hbbb64fa96e78b8cb
  11:        0x102eae0eb - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::h56c64142c6ef9779
  12:        0x103095b9d - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::hce1ee09e6def395b
  13:        0x1030a8af8 - winit::platform_impl::platform::observer::control_flow_end_handler::ha56174d0e25bbf4f
  14:     0x7fff34300335 - _ZL12preoptimized
  15:     0x7fff34300267 - _ZL12preoptimized
  16:     0x7fff342ff92c - _ZL12preoptimized
  17:     0x7fff342fee3e - _ZL12preoptimized
  18:     0x7fff32f2babd - _ZL12preoptimized
  19:     0x7fff32f2b7d5 - _ZL12preoptimized
  20:     0x7fff32f2b579 - _ZL12preoptimized
  21:     0x7fff31571039 - _ZL12preoptimized
  22:     0x7fff3156f880 - _ZL12preoptimized
  23:     0x7fff3156158e - _ZL12preoptimized
  24:        0x102e91651 - alacritty::event::Processor<N>::run::hb38e8fae0a9143dc
  25:        0x102f4b8bb - alacritty::main::h287f4a4cd137c330
  26:        0x10307f3d6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbd38275ad85298c1
  27:        0x102f3f5c9 - main
```

**Comment by chrisduerr** [comment] 2020-08-12 03:00
You'd want to just run it with `cargo build`, not by making the app.

**Comment by kchibisov** [comment] 2020-08-12 03:41
You may also do `cargo run`, so it'll spawn alacritty.

**Comment by yangliping** [comment] 2020-08-12 04:25
Here's the `cargo run` output

```
$ cargo run
warning: unused import: `std::env`
 --> alacritty_terminal/src/tty/unix.rs:4:5
  |
4 | use std::env;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:75:21
   |
75 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:75:21
   |
75 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.60s
     Running `target/debug/alacritty`
thread 'main' panicked at 'attempt to subtract with overflow', /private/tmp/alacritty-0.5.0/alacritty_terminal/src/term/search.rs:424:13
stack backtrace:
   0:        0x107c4048e - backtrace::backtrace::libunwind::trace::h63c9d7d2ede0b2c8
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:        0x107c4048e - backtrace::backtrace::trace_unsynchronized::h5e4957b6d2953180
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:        0x107c4048e - std::sys_common::backtrace::_print_fmt::h7c198f79ad382973
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x107c4048e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h26e8f1b884bae128
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x107c68a3c - core::fmt::write::ha0b53fc066268c71
                               at src/libcore/fmt/mod.rs:1076
   5:        0x107c3cff7 - std::io::Write::write_fmt::h410b83a4c70c6549
                               at src/libstd/io/mod.rs:1537
   6:        0x107c424e5 - std::sys_common::backtrace::_print::h3f7bc036aeb95759
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x107c424e5 - std::sys_common::backtrace::print::h3ea67c1d14cd9988
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x107c424e5 - std::panicking::default_hook::{{closure}}::h70c11ad9e0ccd806
                               at src/libstd/panicking.rs:198
   9:        0x107c42222 - std::panicking::default_hook::hd9eda5765f18f021
                               at src/libstd/panicking.rs:218
  10:        0x107c42a9d - std::panicking::rust_panic_with_hook::h3fc8a110bc9d166f
                               at src/libstd/panicking.rs:486
  11:        0x107c42672 - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:        0x107c74d5f - core::panicking::panic_fmt::h04439fd445b5f690
  13:        0x107c74cb7 - core::panicking::panic::h2f2a3cb96f8c3d83
  14:        0x10768754c - alacritty_terminal::term::search::<impl alacritty_terminal::term::Term<T>>::line_search_right::h0f12eab3cc59d7dd
                               at /private/tmp/alacritty-0.5.0/alacritty_terminal/src/term/search.rs:424
  15:        0x107684590 - alacritty_terminal::term::RenderableSearch::new::h21df1c28f31bafa6
                               at /private/tmp/alacritty-0.5.0/alacritty_terminal/src/term/mod.rs:77
  16:        0x107685539 - alacritty_terminal::term::RenderableCellsIter<C>::new::ha8a3815e5ad789e2
                               at /private/tmp/alacritty-0.5.0/alacritty_terminal/src/term/mod.rs:181
  17:        0x107680b10 - alacritty_terminal::term::Term<T>::renderable_cells::h92265586e96a7c87
                               at /private/tmp/alacritty-0.5.0/alacritty_terminal/src/term/mod.rs:945
  18:        0x1075fe94d - alacritty::display::Display::draw::h941ce55d707e7e63
                               at alacritty/src/display.rs:457
  19:        0x1075e1843 - alacritty::event::Processor<N>::run::{{closure}}::h7f3c29ce6a8601d1
                               at alacritty/src/event.rs:853
  20:        0x1075aa687 - <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut::h21621feeef55688e
                               at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1083
  21:        0x1075e4a43 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::hfdd61342bfc94ea7
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/app_state.rs:71
  22:        0x107be7b10 - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::h7c70fa3748b7a4b2
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.13/src/error.rs:0
  23:        0x107be9a72 - winit::platform_impl::platform::app_state::AppState::cleared::h80b05c0d24f8f8e0
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.13/src/error.rs:0
  24:        0x107bcfc5e - winit::platform_impl::platform::observer::control_flow_end_handler::h0c6049795d3ca0be
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.13/src/error.rs:0
  25:     0x7fff34300335 - _ZL12preoptimized
  26:     0x7fff34300267 - _ZL12preoptimized
  27:     0x7fff342ff92c - _ZL12preoptimized
  28:     0x7fff342fee3e - _ZL12preoptimized
  29:     0x7fff32f2babd - _ZL12preoptimized
  30:     0x7fff32f2b7d5 - _ZL12preoptimized
  31:     0x7fff32f2b579 - _ZL12preoptimized
  32:     0x7fff31571039 - _ZL12preoptimized
  33:     0x7fff3156f880 - _ZL12preoptimized
  34:     0x7fff3156158e - _ZL12preoptimized
  35:        0x107c11f16 - <() as objc::message::MessageArguments>::invoke::hf110aab1d28e80e9
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  36:        0x107c0e12d - objc::message::platform::send_unverified::h25d77bed30476e4e
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  37:        0x1075db5fc - objc::message::send_message::h4840549dc432ee4b
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  38:        0x1075db5fc - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::h014bea22da101375
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/macros.rs:133
  39:        0x1075cba5c - <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return::h192bc79b43ad45a4
                               at /Users/ping/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform/desktop.rs:51
  40:        0x1075e0bc6 - alacritty::event::Processor<N>::run::h42d6a711febbf70e
                               at alacritty/src/event.rs:752
  41:        0x107666a78 - alacritty::run::h2378760013172799
                               at alacritty/src/main.rs:200
  42:        0x1076657ba - alacritty::main::h287f4a4cd137c330
                               at alacritty/src/main.rs:106
  43:        0x10775b4de - std::rt::lang_start::{{closure}}::h77bc2e0881bc0077
                               at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  44:        0x107c42d69 - std::rt::lang_start_internal::{{closure}}::h2e500782e29a403a
                               at src/libstd/rt.rs:52
  45:        0x107c42d69 - std::panicking::try::do_call::h8313a5ab130d76d7
                               at src/libstd/panicking.rs:297
  46:        0x107c42d69 - std::panicking::try::hae3049de664ee5f7
                               at src/libstd/panicking.rs:274
  47:        0x107c42d69 - std::panic::catch_unwind::hf1c9a8c97b889693
                               at src/libstd/panic.rs:394
  48:        0x107c42d69 - std::rt::lang_start_internal::hbec44ff873a30990
                               at src/libstd/rt.rs:51
  49:        0x10775b4c1 - std::rt::lang_start::h18ed6c13733e2b6d
                               at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  50:        0x107666ea2 - main
```

**Comment by chrisduerr** [comment] 2020-08-12 07:25
Should be fixed with https://github.com/alacritty/alacritty/pull/4115, thanks.

**Closed** 2020-08-12 08:36 UTC
Labels: A - needs repro, B - bug, B - crash
