### ISSUE TITLE
Flickering text while using halo text cursor python package

### ISSUE THREAD

**Issue by GideonWolfe** [alacritty/alacritty#4394] opened 2020-11-09 04:58 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

Version: `alacritty 0.6.0-dev (1bf40a8c)`
Linux/BSD: Arch Linux, X11 on i3-gaps WM

I am trying to use the [halo](https://github.com/manrajgrover/halo) package to add some loading animations to my scripts. However I get the following flickering behavior when viewing in `alacritty`

![1604897660](https://user-images.githubusercontent.com/32942052/98501679-c7122200-2204-11eb-96e9-c9948d2e8b0d.gif)

The same script works fine in `urxvt`.

![1604897754](https://user-images.githubusercontent.com/32942052/98501727-e9a43b00-2204-11eb-8d78-63857b65002a.gif)

**Comment by kchibisov** [comment] 2020-11-09 05:05
Seems like not really optimal drawing approach tbqh, it should only change one char, but what likely happens is that it drawns entire line, clears, redraws, and alacritty just draws its intermediate state, urxvt will likely either draws a bit latter then we or delays screen update until more content filled or some time reached.

Drawing closer to vblank in alacritty could help to help, but in general it can only be fixed (not improved) by  https://github.com/alacritty/alacritty/issues/598 , which will require a patch to the library you're using  anyway...

**Comment by kchibisov** [comment] 2020-11-09 05:05
Closing as duplicate of #598 .

**Closed by kchibisov** 2020-11-09 05:05 UTC
