### ISSUE TITLE
Typing at sign (@) and pipe (|) doesn’t work properly

### ISSUE THREAD

**Issue by smeikx** [alacritty/alacritty#1349] opened 2018-06-03 10:54 UTC
I’m using a German keyboard. 
Usually, in macOS, it works like this:
- `@` is accessed via `alt + L`
- `|` (pipe) is accessed via `alt + 7`

Using zsh with vim mode `alt + L` seems to send an Escape, `alt + 7` also sends an Escape and moves the cursor to the beginning of the line. 

There is a way to type these two characters, however: if I first type `alt + n` (would normally make a `~`) and *then* type the combination for `@` or `|` they appear. 

---

Which operating system does the issue occur on?
macOS

**Comment by chrisduerr** [comment] 2018-06-03 14:14
What exactly is the issue here? Does the second way you've mentioned not work inside of alacritty?

**Comment by jedahan** [comment] 2018-06-03 15:30
I think what @smeikx is describing is that the `alt + n` should be unnecessary. It would be useful to confirm that another terminal behaves that way though.

**Comment by smeikx** [comment] 2018-06-03 15:39
Yes, @jedahan is right. In *every* other application it works with two keystrokes. I edited the description to clarify.

**Comment by chrisduerr** [comment] 2018-06-03 15:45
What do you mean by `every other application` though? A terminal emulator works very differently from other applications, it kinda sounds like this is a zsh thing, but I'm not entirely sure.

Does the same issue occur with different terminal emulators running zsh?

**Comment by smeikx** [comment] 2018-06-03 16:18
It doesn’t have anything to do with zsh. When using bash neither `alt + 7` nor `alt + L` do anything. 
It just seems that Alacritty interprets these keystrokes as something that zsh makes use of but bash doesn’t. 

To further clarify:
`alt + L` ist the standard way to type `@` in macOS. If I want to access that character, doesn’t matter where, I type `alt + L`. It works that way in the built-in Terminal.app and in iTerm2 — as well as in any other context where I can enter text. The same goes for `alt + 7` and `|`.
It’s like `AltGr + Q` in Windows (I guess, as I’m not that familiar with Windows).

**Comment by francesca64** [comment] 2018-06-03 16:39
Did this work before 765949f256aefcc513d0bfb46b64d315f9c2f3d2, or did it never work in Alacritty?

Also, are the results different outside of tmux (assuming you're using tmux)?

**Comment by smeikx** [comment] 2018-06-03 17:48
No, not even when typing `alt + n` before; it never worked in Alacritty.

Also, I didn’t use tmux.

**Comment by johnnynia** [comment] 2018-06-10 09:39
I experienced the same problem with the @ sign using a Swiss German keyboard (where @ is typed via `alt+g`.

I fixed it with this line in the config:
```
  - { key: G,        mods: Alt,           chars: "\x40"                        }
```

**Comment by smeikx** [comment] 2018-06-10 22:07
Thank you, that’s a nice workaround!

**Comment by burknator** [comment] 2018-06-28 13:31
The problem is still there, you can't enter `@` or `|` in Alacritty on a German keyboard (with `alt+l` and `alt+7`). But using `alt+e` to enter the €-symbol works just fine.

---
The workaround mentioned by @johnnynia works. The hex code for `|` is `\x7C`.

This enables you to enter `@` with `alt+l` and `|` with `alt+7`:

```yaml
  - { key: L,        mods: Alt,     chars: "\x40"                        }
  - { key: Key7,     mods: Alt,     chars: "\x7C"                        }
```

**Comment by HendrikPetertje** [comment] 2018-07-09 06:29
any update on this? 

I had to revert back to using iterm (with metal GPU rendering) since Altgr keys and special characters are incredibly wonky (not working or producing US layout based characters) on my Swedish and Icelandic based OSX keyboards. writing pipecharacters and @ signs is pretty handy when programming ;)

**Comment by francesca64** [comment] 2018-07-09 14:45
macOS keyboard support is surprisingly mysterious, and winit/glutin gives me no shortage of other obligations to tend to. This isn't going to be fixed anytime soon unless someone cares enough to work on it.

**Comment by jacoscaz** [comment] 2018-07-30 08:58
Same issue here. I'm on `master` on a MacBook Pro with Mac OS 10.13.6 and an Italian keyboard layout. Many characters/commands that require combinations of `cmd` and/or `ctrl` and/or `alt` do not work. Rust is on my todo list for this year but I still haven't got around to it. I'd be happy to help in any capacity I can!

**Comment by jacoscaz** [comment] 2018-08-06 08:15
Useful mappings for those with an `Italian` layout on MacOS:

```yml
  - { key: LBracket,    mods: Alt|Shift,      chars: "\x7B"              }
  - { key: RBracket,    mods: Alt|Shift,      chars: "\x7D"              }
  - { key: LBracket,    mods: Alt,            chars: "\x5B"              }
  - { key: RBracket,    mods: Alt,            chars: "\x5D"              }
  - { key: Semicolon,   mods: Alt,            chars: "\x40"              }
  - { key: Apostrophe,  mods: Alt,            chars: "\x23"              }
  - { key: Caret,       mods: Alt,            chars: "\x60"              }
```

On MacOS, mappings can be derived by:

1. running `make app` as per the installation guide
2. running Alacritty using `./target/release/osx/Alacritty.app/Contents/MacOS/alacritty --print-events`

At this point, Alacritty should log events pairs like this:

```
glutin event: WindowEvent { window_id: WindowId(Id(140237741461568)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 33, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140237741461568)), event: ReceivedCharacter('[') }
```

We're interested in:

- The value in between the brackets of `Some`, which is the one to use in the `key` property of the mapping
- boolean properties in `ModifiersState`, which indicate which modifiers to add in the `mods` property of the mapping (these can be concatenated using the `|` character)
- hex values for the `chars` properties can be looked up on ASCII tables like the one at [http://www.asciitable.com](http://www.asciitable.com)

In the case of the above log lines, I was looking for a mapping that would make pressing `[` on my keyboard actually result in the desired symbol appearing in Alacritty. The resulting mapping is:

```
  - { key: LBracket,    mods: Alt,            chars: "\x5B"              }
```

**Comment by josex2r** [comment] 2018-09-05 09:15
Hi guys.
Here are the mappings for `Spanish` keyboard in MacOS:

```
  - { key: Caret,    mods: Alt,     chars: "\x5C"                        }
  - { key: Key1,     mods: Alt,     chars: "|"                           }
  - { key: Key2,     mods: Alt,     chars: "@"                           }
  - { key: Key3,     mods: Alt,     chars: "#"                           }
  - { key: Key6,     mods: Alt,     chars: "¬"                           }
  - { key: LBracket, mods: Alt,     chars: "\x5B"                        }
  - { key: RBracket, mods: Alt,     chars: "\x5D"                        }
  - { key: Apostrophe,  mods: Alt,  chars: "\x7B"                        }
  - { key: Backslash,   mods: Alt,  chars: "\x7D"                        }
```

**Comment by jacoscaz** [comment] 2018-09-05 09:42
@francesca64 @jwilm would it be worth collecting these mappings somewhere?

**Comment by nixpulvis** [comment] 2018-09-05 13:15
@jacoscaz make a wiki page! :tada:

**Comment by jacoscaz** [comment] 2018-09-05 13:34
Hey all - new wiki page for keyboard mappings! https://github.com/jwilm/alacritty/wiki/Keyboard-mappings

**Comment by johnnynia** [comment] 2018-09-05 13:44
Thank you for the initiative! I have added key bindings for Swiss German keyboards to the wiki page.

**Comment by guillaumewuip** [comment] 2019-01-01 19:03
For `French` on MacOS : 

Probably some keys still missing

```
  - { key: Equals,    mods: Command,    action: DecreaseFontSize              }
  - { key: Slash,     mods: Command,    action: IncreaseFontSize              }
  - { key: A,         mods: Command,    action: Quit                          }
  - { key: Z,         mods: Command,    action: Quit                          }
  - { key: L,         mods: Alt|Shift,  chars: "|"                            }
  - { key: Key5,      mods: Alt,        chars: "{"                            }
  - { key: Minus,     mods: Alt,        chars: "}"                            }
  - { key: Key5,      mods: Alt|Shift,  chars: "["                            }
  - { key: Minus,     mods: Alt|Shift,  chars: "]"                            }
  - { key: N,         mods: Alt,        chars: "~"                            }
```

**Comment by s7anley** [comment] 2019-01-01 22:52
This issue is the blocker for me since I saw a first article about alacritty months ago and I'm surprised there is no proper solution for it. So it's creating a mapping only option for now? 

I mean, when you open keyboard viewer on MacOS what you see there should be what you get in terminal right? For example:
![screenshot 2019-01-01 at 23 44 14](https://user-images.githubusercontent.com/640131/50577050-3192f380-0e1f-11e9-8169-02fd3806ea6a.png)

Strange part it that most of the time when debugging via `--print-events`, the proper character is received for example `RAlt` + `Key6` should be `^`.

```
[2019-01-01 23:47] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140442987588992)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 61, state: Pressed, virtual_keycode: Some(RAlt), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
[2019-01-01 23:47] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140442987588992)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 22, state: Pressed, virtual_keycode: Some(Key6), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
[2019-01-01 23:47] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140442987588992)), event: ReceivedCharacter('^') }
```

Maybe there is better way how to just print ReceivedCharacter instead of creating mappings?

**Comment by mariomac** [comment] 2019-03-25 08:45
I had the same problem, and I fixed it in the "Profiles --> Keys" configuration tab. I set the Right ⎇ Key to "Normal" and my symbols came back.
![image](https://user-images.githubusercontent.com/939550/54906007-9ae84700-4ee2-11e9-834f-d814356fa6ab.png)

**Comment by HendrikPetertje** [comment] 2019-03-25 14:12
@guillaumewuip, can you add that mapping to the https://github.com/jwilm/alacritty/wiki/Keyboard-mappings? you should be able to edit the wiki.

**Comment by guillaumewuip** [comment] 2019-03-25 15:06
Yep 👍 Done here @HendrikPetertje :)

**Comment by s7anley** [comment] 2019-03-25 17:10
@mariomac where exactly is this configuration?

**Comment by mariomac** [comment] 2019-03-28 08:02
Oh shit! I mixed this repository with the iTerm2 repository. Sorry for the noise

**Comment by brerx** [comment] 2019-05-16 21:36
I'm using a german keyboard, too. But none of those keymappings in the wiki do work for me. Except Alt + 5, Alt + 6, Alt + 8, Alt + 9. Those work out of the box even with default config yml.

Basically, I have the same issue like #2390 , but `alt_send_esc:` is already false. No solution for me...

**Comment by dvergeylen** [comment] 2019-10-08 09:12
Hi,

I am having the same problem under Linux since #2438 has been merged.
Wiki page helped a lot!

**Comment by thisconnect** [comment] 2019-12-16 12:49
> @francesca64 @jwilm would it be worth collecting these mappings somewhere?

Shouldn't there be a module outside of alacritty that solves these keyboard mappings in rust, outside of this project?

**Comment by kaikuehne** [comment] 2020-02-05 01:57
What helped me is to set `alt_send_esc` to false.

**Comment by etienne-k** [comment] 2020-02-29 13:35
> What helped me is to set `alt_send_esc` to false.

This solved all issues I had with a german ISO keyboard on MacOS Catalina, Alacritty version 0.4.1 (4d9253b).
The keybinds in the Wiki did not help.

I'm wondering what the purpose of that option defaulting to true might be... 🤔 Would there be any drawback with defaulting `alt_send_esc` false?

**Comment by chrisduerr** [comment] 2020-02-29 14:42
> Would there be any drawback with defaulting alt_send_esc false?

Yes, you could not send escapes using the alt key anymore.

**Comment by chrisduerr** [comment] 2020-04-28 23:19
The original issue was mostly resolved by `alt_send_esc`, for everything more there's https://github.com/alacritty/alacritty/issues/458.

**Closed by chrisduerr** 2020-04-28 23:19 UTC
Labels: S - input, S - winit/glutin

**Comment by rouflak** [comment] 2020-11-06 19:59
> What helped me is to set `alt_send_esc` to false.

@kaikuehne That helped a lot. No need to add weird bindings. Thank you very much!

**Comment by jerik** [comment] 2021-01-27 21:00
> What helped me is to set `alt_send_esc` to false.

Worked for me as well. On macos 10.13.6 with alacritty 0.6.0 (04cbf76) installion with homebrew.
