### ISSUE TITLE
Runtime Error when launching 0.4.1 embedded in RDM or RoyalTS

### ISSUE THREAD

**Issue by mahomedh** [alacritty/alacritty#3350] opened 2020-02-17 17:37 UTC
### System

OS: Windows 10
Version: `0.4.1`
Windows: WinPTY

### Logs

Crashes: 

```
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', C:\Users\travis\.cargo\git\checkouts\winit-c2fdb27092aba5a7\d1c6506\src\platform_impl\windows\dark_mode.rs:135:13

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------
```

Above error occurs when launching alacritty as an embedded terminal using Devolutions Remote Desktop Manager or RoyalTS. 

Launching `0.4.1` directly works fine.

Launching `0.4.0` from RDM or RoyalTS works fine too.

Please let me know what other info you require and I'll get it for you. Thanks.

**Comment by kchibisov** [comment] 2020-02-17 19:28
Duplicate of #3177.

**Closed by kchibisov** 2020-02-17 19:28 UTC
