### ISSUE TITLE
(macOS) Mission Control's animations are slow when switching from Alacritty.

### ISSUE THREAD

**Issue by ftpd** [alacritty/alacritty#4474] opened 2020-11-24 18:44 UTC
### System

OS: macOS Big Sur 11.0.1
Version: alacritty 0.5.0 (a6681e3)

### The bug:
There is this functionality of macOS called 'Mission Control', which user can invoke (via shortcut, key on Apple keyboard or trackpad gesture) to show all windows from current workspace to quickly switch between them.
When I'm using it to switch to anything from Alacritty (like: Alacritty is the focused app/window while invoking Mission Control), everything is laggy and slow. When I'm invoking it 'from' any different app, it's smooth and fast.

Here is the screencast I recorded to show the issue: https://insomniac.pl/f/alacritty-slow-mission-control.mov (it's Apple QuickTime, I can convert to other format if you need it).

**Comment by chrisduerr** [comment] 2020-11-25 00:55
This is a duplicate of https://github.com/alacritty/alacritty/issues/4410.

As stated there, I don't see how Alacritty could do anything about this? Mission control is completely outside the control of Alacritty and I'm not aware of any "laggy mission control" setting.

How many other OpenGL applications have you tested? What makes you think that this is a bug **inside of Alacritty**, other than the issue showing up with Alacritty?

**Comment by jonleopard** [comment] 2020-11-25 08:14
I don't get the same behavior on my machine. Whenever I switch context with Mission Control all behaves smoothly _most_ of the time. Occasionally, I have noticed some UI lag across multiple applications (specifically when dragging windows from one screen to the other) with Big Sur. I also have two monitors plugged into my machine which causes more rendering work for my already lackluster GPU (I'm using a macbook pro). 

If any lagging is occurring it's likely and issue with macOS Big Sur or your hardware.

**Comment by ftpd** [comment] 2020-11-25 09:13
@chrisduerr thanks for posting out this second issue. I searched before creating this one, but I had to miss it somehow. I don't know any other software with OpenGL (or rather: I'm not aware which apps are using OpenGL and which are not - as an end-user and a person not so much interested what graphical engine (?) is used by the app, I think I can not to care about such details). Sorry for assuming it's Alacritty's fault - the problem occurred after starting using it, so my natural reaction was blaming the software itself. Can you list like two of other OpenGL popular (so: trusted) and free app, so I can install and test?

@jonleopard which version of macOS are you using? I won't blame the hardware, as it always worked smoothly for everything. Just yesterday it stopped, right after I started using Alacritty, but like @chrisduerr said, it might be global OpenGL problem.

**Comment by chrisduerr** [comment] 2020-11-25 17:49
> Can you name like two of other OpenGL popular (so: trusted) and free apps, so I can install and test?

I don't know anything about available applications on macOS, since I do not use it.

**Comment by DivineGod** [comment] 2020-12-05 02:04
On a weird hunch I looked at the Info.plist file for the macos App in `extra/osx/Alacritty.app/Contents/Info.plist` and changed the value of `NSSupportsAutomaticGraphicsSwitching` from `true` to `false`. This solved the issue of stuttering animation in mission control when Alacritty is the active app.

I am not at all sure if this is a proper fix as it's possible the setting is important in other regards.

**Comment by chrisduerr** [comment] 2020-12-05 04:03
That just disables the dGPU for Alacritty and instead uses the iGPU then. So that **really** sounds like it's a macOS issue with having to deal with multiple graphics things at the same time. Or it's your dGPU struggling, but I somewhat doubt that.

**Comment by chrisduerr** [comment] 2020-12-05 04:04
@DivineGod Which exact machine do you use?

**Comment by DivineGod** [comment] 2020-12-05 05:33
> @DivineGod Which exact machine do you use? Specifically which CPU/GPU.

MacBook Pro intel cpu with amd Radeon 5500M gpu. I’ve got an older mbp which only has igpu as well I can test on later.

Definitely a Mac issue in some capacity. Did have a weird fix of running another rust OpenGL app from alacritty which made alacritty not cause the issue.

**Comment by ftpd** [comment] 2020-12-05 09:11
I only have an igpu, so this workaround won't help me.

**Comment by chrisduerr** [comment] 2020-12-05 18:40
I'd definitely give a few different OpenGL applications a shot. Apple's OpenGL drivers are **really** bad.

**Comment by DivineGod** [comment] 2020-12-05 23:40
I cannot replicate the issue on my early 2015 mbp, macOS Catalina v 10.15.7 (19H2) with built-in Intel Iris Graphics 6100. Latest master build of alacritty.

<img width="770" alt="Screen Shot 2020-12-06 at 10 38 11" src="https://user-images.githubusercontent.com/36430/101267663-47e61e80-37af-11eb-8446-210dcb788d99.png">

**Comment by DivineGod** [comment] 2020-12-06 00:25
The machine that does have the issue is MacBook Pro (16 inch, 2019), Big Sur v 11.0.1, w AMD Radeon Pro 5500M dGPU, Intel UHD Graphics 630 iGPU. 32 GB Ram, 2.3 GHz 8-core Intel Core i9 CPU.

**Comment by ric2work** [comment] 2020-12-06 00:26
Hey Guys 

I am so appreciated you guys shared This I found this issues for 9weeks ago , working on days and nights upside down ... so emotional finding the issues why firewall lock ..though that my mistakenly stepped up the macOS  ..

But the way I need some guidelines for worldwide support for this project to make it possible for the biggest new “Apple business account + lovely Apple care service “ .. pls give me a call back 

Richo  T.
spaces zone d. creation 
+60164808297

**Comment by DivineGod** [comment] 2020-12-06 22:11
I've put up a branch with my "fix" for anyone with macos on various systems to test out so we can figure out what exactly is going on:

https://github.com/DivineGod/alacritty/tree/macos-expose-stutter

**Comment by chrisduerr** [comment] 2020-12-06 22:17
Just to be **absolutely clear**: That is not a fix. This will slow down Alacritty significantly.

**Comment by DivineGod** [comment] 2020-12-06 23:20
Yes. Not a proper fix and why I haven't made it a PR. This is purely for investigative purposes.

**Comment by DivineGod** [comment] 2020-12-06 23:47
Did vtebench on my 16-inch mbp with both master and my "fix" first run crashed the system somehow and the bug isn't showing now. Runs were indistinguishable from each other both on the laptop retina display and my external 1080p monitor.

Need to collect a lot more data to make any conclusions on this.

[vte-retina-fix.txt](https://github.com/alacritty/alacritty/files/5649798/vte-retina-fix.txt)
[vte-retina-master.txt](https://github.com/alacritty/alacritty/files/5649799/vte-retina-master.txt)
[vte-non_retina-master.txt](https://github.com/alacritty/alacritty/files/5649800/vte-non_retina-master.txt)
[vte-non_retina-fix.txt](https://github.com/alacritty/alacritty/files/5649801/vte-non_retina-fix.txt)

**Comment by DivineGod** [comment] 2020-12-07 04:41
I've done some benchmarks on battery after triggering the bug in master. I triggered the issue by starting Steam and closing it again.

[vte-retina-master-battery.txt](https://github.com/alacritty/alacritty/files/5650451/vte-retina-master-battery.txt)
[vte-retina-fix-battery.txt](https://github.com/alacritty/alacritty/files/5650452/vte-retina-fix-battery.txt)

The results sort of look like here that the "fix" runs better on battery than master does.

**Comment by heidark** [comment] 2020-12-08 13:44
Reducing transparency will completely eliminate the stutter:
`System Preferences - Accessibility - Display - Reduce transparency`

Changing the `background_opacity` setting doesn't seem to have any effect on the stutter and even with "Reduce transparency" on, the background will still be transparent.

**Comment by bfqrst** [comment] 2020-12-11 23:23
This is definitely something that came or changed with Big Sur! I noticed it on two MacBooks Pro 13" (2017 and 2019) the instant I upgraded from Catalina. Those only have Intel graphics. Also thanks @heidark, that helped. As of today Alacritty is the only app I'm using that suffers from this after the upgrade. Which is not to say that it's Alacrittys fault, I'm just stating my status quo...

**Comment by sdjespersen** [comment] 2020-12-16 05:06
I'm on a 16-inch 2019 MacBook Pro, 2 GPUs, Intel UHD Graphics 630 (built-in) and AMD Radeon Pro 5300M (PCIe).

The automatic GPU switching in Big Sur really seems to be to blame. I ended up disabling automatic graphics switching at a system-wide level by going to `System Preferences > Battery > Battery` and unchecking `Automatic graphics switching`. Pour one out for my battery life 🍺, but my Alacritty experience is back to being speedy and amazing.

**Comment by chrisduerr** [comment] 2020-12-16 09:53
If someone has a suggestion for fixing this, please let me know. But it seems to me like this is just one more instance of macOS' poor OpenGL support. So there's not much Alacritty can do.

**Closed by chrisduerr** 2020-12-16 09:53 UTC
Labels: H - macos

**Comment by ftpd** [comment] 2020-12-19 22:27
Quick update: I've just decided to give alacritty another go and it's 'magically' (as I haven't change any setting) fixed in 0.6.0 running under Big Sur 11.1.

**Comment by chrisduerr** [comment] 2020-12-19 22:38
Might have been fixed in Big Sur 11.1? Otherwise I don't see what could have changed.

**Comment by ftpd** [comment] 2020-12-20 10:31
Yeah, maybe. Big Sur fixes a lot of very old bugs in macOS, silently and without mentioning it in release notes, so maybe now the time has come for OpenGL ;-) I'm not complaining, though.

**Comment by bfqrst** [comment] 2020-12-21 17:24
> Quick update: I've just decided to give alacritty another go and it's 'magically' (as I haven't change any setting) fixed in 0.6.0 running under Big Sur 11.1.

I'm afraid I can't second that! On a MacBookPro15,2 (2019 model 4 TB ports) still choppy when attempting to "mission control" with Alacritty having focus. No issues though, when Alacritty is open but not focused. I was hoping the 11.1 update would fix this but no luck here.

**Comment by DivineGod** [comment] 2020-12-22 02:46
This might be related to compositing in macos since alacritty/alacritty#4605 with opacity set to 0.8 fixes this issue by disabling shadows.

**Comment by npearson72** [comment] 2020-12-23 03:51
I'm having this issue too and @heidark's suggested worked for me. Anyone know if iterm2 is plagued by this?

**Comment by ftpd** [comment] 2020-12-23 08:41
It's not.

**Comment by npearson72** [comment] 2020-12-23 12:20
@ftpd are you by chance brewing coreutils? Might using native MacOS stty help?

**Comment by npearson72** [comment] 2020-12-23 12:23
@ftpd I think I'm seeing a different problem from yours. Pardon.

**Comment by ric2work** [comment] 2021-01-07 19:34
Hi

**Comment by bfqrst** [comment] 2021-01-12 08:08
FWIW, I just upgraded from 0.6.x to 0.7.1 and the stutter in the animation is gone...

**Comment by yennamgiang** [comment] 2021-03-22 10:58
> If someone has a suggestion for fixing this, please let me know. But it seems to me like this is just one more instance of macOS' poor OpenGL support. So there's not much Alacritty can do.

Add background_opacity: 0.999 to alacrity.yml instead of leaving it blank, or set background_opacity: 1.0. This is an error/ bug of macOS’ poor OpenGL support but can be totally fixed by Alacritty by an update version. (In addition, Mission Control’s animations are slow could get worse if you set background_opacity: 2.0, 3.0 ... Just kidding, haha)

**Comment by ftpd** [comment] 2021-03-22 11:30
Confirmed, this worrkaround works.

**Comment by ihsanturk** [comment] 2021-05-12 14:37
Also, this solves the issue as a workaround
```yaml
"window": {
  "decorations": "Buttonless"
}
```

**Comment by f0s3** [comment] 2023-09-06 13:15
> Reducing transparency will completely eliminate the stutter: `System Preferences - Accessibility - Display - Reduce transparency`
> 
> Changing the `background_opacity` setting doesn't seem to have any effect on the stutter and even with "Reduce transparency" on, the background will still be transparent.

It worked for me, but I didn't like how my system looks like. I tried playing around with alacritty config and found out that it stops stuttering when window > opacity is set to something not 1.0. I've set opacity 0.99 and it started working smoothly without issues!

For the lazy ones:

```
window:
  opacity: 0.99
```

**Comment by smashkirk** [comment] 2023-09-30 16:05
My system animations are slow as well, but not related to Alacritty. After a restart it works fine, but then after some time using it, the system animations slow down again. Chrome was a big factor so I stopped using it. I thought it would help, but the problem returns. I think there is some serious software/hardware GPU issue affecting these machines. I have a 2020 M1 Mac which should be blazing fast. Unacceptable.

**Comment by Telmo-Sousa** [comment] 2024-01-29 18:46
> My system animations are slow as well, but not related to Alacritty. After a restart it works fine, but then after some time using it, the system animations slow down again. Chrome was a big factor so I stopped using it. I thought it would help, but the problem returns. I think there is some serious software/hardware GPU issue affecting these machines. I have a 2020 M1 Mac which should be blazing fast. Unacceptable.

i have a mbp m1 and im running alacritty with no issues after the fix with opacity

**Comment by ladusee** [comment] 2024-06-05 12:06
> > Reducing transparency will completely eliminate the stutter: `System Preferences - Accessibility - Display - Reduce transparency`
> > Changing the `background_opacity` setting doesn't seem to have any effect on the stutter and even with "Reduce transparency" on, the background will still be transparent.
> 
> It worked for me, but I didn't like how my system looks like. I tried playing around with alacritty config and found out that it stops stuttering when window > opacity is set to something not 1.0. I've set opacity 0.99 and it started working smoothly without issues!
> 
> For the lazy ones:
> 
> ```
> window:
>   opacity: 0.99
> ```


works like a charm! thanks!

**Comment by nixpulvis** [comment] 2024-06-05 19:41
I can't remember the fix exactly, but I think this should be resolved with the next release without needing to change the opacity.

**Comment by AnhQuanTrl** [comment] 2024-09-17 15:44
Confirm this is still a problem in Alacritty 0.13.2
