### ISSUE TITLE
Per-glyph transparency issue with font Iosevka

### ISSUE THREAD

**Issue by hroemer** [alacritty/alacritty#3843] opened 2020-06-11 11:42 UTC
I am using `Iosevka` font and noticed some visual glitches between glyphs (vertical and horizontal overlaps), which according to the font author is due to missing / incorrect per-glyph transparency (cf. [Iosevka #594](/be5invis/Iosevka/issues/594)). The following screenshots show the small vertical overlaps in `alacritty` for both font variants:

| Iosevka Fixed SS05 12 pt (`v3.1.1`) | Iosevka Term SS05 12 pt (`v3.1.1`) | 
| --- | --- |
| ![iosevka_fixed_ss05_12pt_3 1 0](https://user-images.githubusercontent.com/16097755/84252132-7dff5a00-ab0e-11ea-8250-63102a9550c5.png) | ![iosevka_term_ss05_12pt_3 1 0](https://user-images.githubusercontent.com/16097755/84252134-7e97f080-ab0e-11ea-947e-1b55aab00a1c.png) |

I tried tweaking configuration values for `offset` / `glyph-offset` but this did not have an effect and probably totally unrelated.

### System

OS: Linux
Version: `alacritty 0.4.3`
Linux/BSD: `i3 version 4.18.1`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `Estimated DPR: 1
Estimated Cell Size: 8 x 20
Estimated Dimensions: Some((644, 484))
Device pixel ratio: 1
Estimated DPR correctly, skipping resize
Cell Size: 8 x 20
Padding: 2 x 2
Width: 644, Height: 484
PTY Dimensions: Line(24) x Column(80)
Width: 1920, Height: 1127`

**Comment by kchibisov** [comment] 2020-06-11 11:48
it's a duplicate of https://github.com/alacritty/alacritty/issues/118

**Closed by kchibisov** 2020-06-11 11:48 UTC
