### ISSUE TITLE
0.4.1 new "feature"?

### ISSUE THREAD

**Issue by UnixRonin** [alacritty/alacritty#3212] opened 2020-01-15 21:30 UTC
### System
OS: Gentoo Linux
Version: 0.4.1
Linux/BSD: X11 + fvwm2

I'm experiencing unexpected behavior in console applications when switching virtual screens, since updating to alacritty 0.4.1.  Does 0.4.1 by any chance have a new "feature" in which control+left/right arrow seen by the terminal, even if already acted on by the window manager, is automatically parsed as an action to move the cursor left or right one word?

...If so, is there a way to turn this feature **OFF** in the configuration?  I am finding it more of a liability than a benefit.  It is at best _unexpected_ even when it is not actually harmful.

**Comment by chrisduerr** [comment] 2020-01-15 22:15
Duplicate of https://github.com/alacritty/alacritty/issues/3109 and fixed in the latest master.

**Closed by chrisduerr** 2020-01-15 22:15 UTC
