### ISSUE TITLE
Backticks in vim doesnt work.

### ISSUE THREAD

**Issue by VGDev1** [alacritty/alacritty#4482] opened 2020-11-25 12:01 UTC
When I try to use backticks in vim(shift+opt+tickskey on my keyboard layout) when writing markdown it goes into normal mode and jumps to the start of the file. This does not occur when I do the same in iterm2.

### System

OS: OSX Big Sur
Version: 0.5.0

**Comment by chrisduerr** [comment] 2020-11-25 17:34
Duplicate of https://github.com/alacritty/alacritty/issues/2017.

**Closed by chrisduerr** 2020-11-25 17:34 UTC
