### ISSUE TITLE
How to search in terminal scrollback?

### ISSUE THREAD

**Issue by siyia2** [alacritty/alacritty#3894] opened 2020-06-28 01:22 UTC
How do i search a word in terminal scrollback? In kitty i used ctrl+shift+f with less, i dont want to use tmux with my terminal.

**Comment by chrisduerr** [comment] 2020-06-28 01:30
Duplicate of https://github.com/alacritty/alacritty/issues/1017.

**Closed by chrisduerr** 2020-06-28 01:30 UTC
