### ISSUE TITLE
Copy_or_interrupt

### ISSUE THREAD

**Issue by Bruce-YC** [alacritty/alacritty#3754] opened 2020-05-21 00:25 UTC
It would be really useful to have this feature from Kitty: maps "Ctrl+C" to "copy_or_interrupt". [It will copy only if there is a selection and send an interrupt otherwise.](https://sw.kovidgoyal.net/kitty/conf.html#clipboard) 

It is implemented [here](https://github.com/kovidgoyal/kitty/blob/5e48ae8baca3ad9f4078176440da7228dd0af9ca/kitty/window.py#L743) in kitty.

**Comment by kchibisov** [comment] 2020-05-21 00:27
duplicate of #1919

**Closed by kchibisov** 2020-05-21 00:27 UTC
