### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by wayneashleyberry** [alacritty/alacritty#648] opened 2017-07-02 06:33 UTC
I just did a fresh build of Alacritty on macOS and noticed a massive performance regression. Whereas before everything was [buttery smooth](https://www.youtube.com/watch?v=vlmDm9REV2I) - after getting the latest commits things have [slowed down terribly](https://youtu.be/DwoifCWceGo).

I can confirm that checking out 63787d0bf0bcf18422b97aa7f8dea2024948c176 and re-building fixes the issue, so the regression must've been introduced between [63787d0...HEAD](https://github.com/jwilm/alacritty/compare/63787d0bf0bcf18422b97aa7f8dea2024948c176...HEAD).

These are the steps I used to build

```sh
$ git pull
Updating 63787d0..32dfddb
Fast-forward
 Cargo.lock          |   7 ++++++
 Cargo.toml          |   1 +
 README.md           |  10 ++++++++
 alacritty.yml       |  12 ++++++----
 alacritty_macos.yml |  12 ++++++----
 src/lib.rs          |   1 +
 src/renderer/mod.rs | 115 ++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------
 7 files changed, 100 insertions(+), 58 deletions(-)
```

```sh
cargo build --release
```

```sh
make app
```

---

Here's my system info

```sh
rustc 1.18.0
```

```sh
cargo 0.19.0-dev (28d1d60 2017-05-16)
```

```sh
                -/+:.           wayne@Waynes-MacBook-Pro.local
               :++++.           ------------------------------
              /+++/.            OS: macOS Sierra 10.12.5 16F73 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro13,3
   .:/++++++/::::/++++++/:`     Kernel: 16.6.0
 .:///////////////////////:`    Uptime: 1 day, 8 hours, 24 mins
 ////////////////////////`      Packages: 164
-+++++++++++++++++++++++`       Shell: zsh 5.3.1
/++++++++++++++++++++++/        Resolution: 1920x1200@2x
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal: iTerm2
  `ossssssssssssssssssssss/     Terminal Font: Menlo-Regular 13
    :ooooooooooooooooooo+.      CPU: Intel i7-6700HQ (8) @ 2.60GHz
     `:+oo+/:-..-:/+o+/-        GPU: Intel HD Graphics 530, AMD Radeon Pro 450
                                Memory: 2550MiB / 16384MiB

```

```yaml
# Configuration for Alacritty, the GPU enhanced terminal emulator

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command
  TERM: xterm-256color

# Window dimensions in character columns and lines
# (changes require restart)
dimensions:
  columns: 160
  lines: 48

padding:
  x: 0
  y: 0

# The FreeType rasterizer needs to know the device DPI for best results
# (changes require restart)
dpi:
  x: 96.0
  y: 96.0

# Display tabs using this many cells (changes require restart)
tabspaces: 2

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Meslo LG M DZ
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: Meslo LG M DZ
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Meslo LG M DZ
    # Style can be specified to pick a specific face.
    # style: Italic

  # Point size of the font
  size: 13.0
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0.0
    y: 0.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# Should display the render timer
render_timer: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: false

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action` or `chars` field must be present. `chars` writes the
# specified string every time that binding is activated. These should generally
# be escape sequences, but they can be configured to send arbitrary strings of
# bytes. Possible values of `action` include `Paste` and `PasteSelection`.
key_bindings:
  # Defaults
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[1~",  mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[4~",  mode: ~AppCursor  }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~",  mode: AppKeypad   }
  - { key: Delete,                  chars: "\x1b[P",   mode: ~AppKeypad  }
  # Custom
  - { key: H,        mods: Alt,     chars: "\x1bh"                       }
  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
  - { key: K,        mods: Alt,     chars: "\x1bk"                       }
  - { key: L,        mods: Alt,     chars: "\x1bl"                       }


# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

selection:
  semantic_escape_chars: ",‚îÇ`|:\"' ()[]{}<>"

hide_cursor_when_typing: false

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
shell:
  program: /usr/local/bin/zsh
#  args:
#    - --login
```

**Comment by jwilm** [comment] 2017-07-02 16:14
Thanks for the report!

Strange that you're running into issues; everyone else I've talked to with the recent render patch has experienced the opposite effect.

Would you mind running the new version again with `render_timer: true`?

**Comment by wayneashleyberry** [comment] 2017-07-02 22:09
I'm getting around ~800 usec on 63787d0bf0bcf18422b97aa7f8dea2024948c176, vs ~100,000 on head :( Made [another video](https://youtu.be/P1_YZz2VjNA) if that helps.

**Comment by wincent** [comment] 2017-07-03 16:33
I can confirm this. Was just going to post an issue for it, but found this one first.

Here's a simple `cat` with a small window (fast):

![small](https://user-images.githubusercontent.com/7074/27801265-efabe0dc-5fd1-11e7-801e-c937e00f8b1a.gif)

Here's the same `cat` with a large window (dramatically slower):

![big](https://user-images.githubusercontent.com/7074/27801296-1a5fd130-5fd2-11e7-92a0-78b7971f81e0.gif)

Here's attaching to a tmux session on a large screen (observe the stutter):

![attach](https://user-images.githubusercontent.com/7074/27801405-b1531160-5fd2-11e7-9aad-a0c774d7814a.gif)

**Comment by jwilm** [comment] 2017-07-03 16:45
@wincent do you have a dedicated GPU as well?

Would either of you be able to record callstacks with the affected commits? I need to run for now, but can provide instructions later if needed.

For the time being, it probably makes sense to revert the render patch from master.

**Comment by wincent** [comment] 2017-07-03 16:46
Yep, it's a MacBook Pro with a discrete GPU.

**Comment by wayneashleyberry** [comment] 2017-07-03 23:02
@jwilm if you could provide instructions I'll gladly help :) I'm not familiar with Rust at all :/

**Comment by jwilm** [comment] 2017-07-11 14:56
Here's instructions:

1. Open up `Instruments.app`. I believe this is installed along with Xcode. Once it's open, select _Time Profiler_ and hit the _Choose_ button.

<img width="804" alt="screen shot 2017-07-11 at 7 45 45 am" src="https://user-images.githubusercontent.com/4285147/28074341-2cb2b780-660d-11e7-9905-6441e84f75d8.png">

2. At the top left, hit _All Processes_ and select an Alacritty instance.

<img width="247" alt="screen shot 2017-07-11 at 7 47 54 am" src="https://user-images.githubusercontent.com/4285147/28074526-a6734814-660d-11e7-9f2f-941abde275d5.png">

<img width="265" alt="screen shot 2017-07-11 at 7 48 27 am" src="https://user-images.githubusercontent.com/4285147/28074499-91d029d6-660d-11e7-8f3d-57e050c9f9bd.png">

3. Hit the red record button on the top left. Now switch to Alacritty and do something that triggers the awful performance.

4. Switch back to instruments and hit the same button to stop recording.
5. Now, hold the _Option_ key and click on the _Main Thread_ call stack to fully expand it.
6. At this point, you can just select all and copy. Please upload the result into a gist.

It may also be worth doing a second recording with the _Record Waiting Threads_ option. You should see a checkbox on the right of the Instruments.app to toggle it.

<img width="262" alt="screen shot 2017-07-11 at 7 55 58 am" src="https://user-images.githubusercontent.com/4285147/28074821-6e5724cc-660e-11e7-88a0-0776a35011bd.png">

Thanks for taking the time to do this! Will almost certainly help in getting the issue resolved.

**Comment by wayneashleyberry** [comment] 2017-07-11 17:54
@jwilm how's this look? https://gist.github.com/wayneashleyberry/b9001573f23d89d38a53482307cdd772

**Comment by jwilm** [comment] 2017-07-11 18:24
@wayneashleyberry great! Thank you!

Not so great news, though. Looks like `glDrawElementsInstanced` is just taking an eternity. Seems like something is weird with the macOS OpenGL driver--maybe it doesn't like the vertex attribute layout used in that branch.

**Comment by jwilm** [comment] 2017-07-11 18:24
@wayneashleyberry you were on the branch giving you 100ms frames, right?

**Comment by wayneashleyberry** [comment] 2017-07-11 18:25
Correct, I checked out https://github.com/jwilm/alacritty/commit/32dfddb91d30bd6d0e85512433da98c1bb036093 and did a fresh release.

**Comment by maximbaz** [comment] 2017-07-11 18:42
To add some context, I've just tried https://github.com/jwilm/alacritty/pull/652 on my Linux, and while "raw" alacritty seems to perform `tree /` equally fast as the build from `master`, running the same command in tmux is terribly slower.

**Comment by jwilm** [comment] 2017-07-11 18:49
@maximbaz that's even more puzzling, but sounds like there's a repro on linux :grin:

**Comment by maximbaz** [comment] 2017-07-11 18:56
Wait, sorry, my bad - I built it in `debug` mode, not `release` 🙊 
In fact, `release` build seems to be equally good, with or without tmux. Sorry for confusion 😄

**Comment by jwilm** [comment] 2017-07-11 19:09
@maximbaz no worries :smile:

**Comment by jwilm** [comment] 2017-07-13 16:33
I was able to test [the branch] on a MBP with integrated graphics on a 4k monitor today. Performance with the branch was much better than before. It seems like this problem is limited to devices with a dedicated graphics card.

Given that I'm unable to repro, I'm hoping those affected by this issue would be willing to test some forthcoming patches.

[the branch]: https://github.com/jwilm/alacritty/issues/652

**Comment by wayneashleyberry** [comment] 2017-07-13 17:31
Of course, I'll carry on helping as much as possible @jwilm

**Comment by andrewrech** [comment] 2017-07-13 17:34
I have been following this thread and am experiencing the same issue. I would also love to help test on an `AMD Radeon R9 M370X 2048 MB` and `NVIDIA Titan Xp` (eGPU)

Thank you @jwilm for you interest and effort!

**Comment by hoodie** [comment] 2017-07-21 16:40
just to chime in, I found the same regression, could it have anything todo with the introduction of scrollback? also, another good demo is cacademo

**Comment by brycefisher** [comment] 2017-07-23 03:26
@hoodie scrollback hasn't landed yet, though there is a PR open for that featue -- still a work in progress though at the moment.

**Comment by hoodie** [comment] 2017-07-23 07:37
@Brycefisher sorry, I just assumed. In fact I was on the scroll back branch for testing

**Comment by jwilm** [comment] 2017-12-23 22:13
Hey could one of you folks with a dedicated GPU MacBook Pro test out the latest version #652? I just pushed a commit that removes the half floats.

**Comment by andrewrech** [comment] 2017-12-24 14:12
Mine is not yet working on High Sierra :-/ but will do asap. Thanks so much for your effort to fix this!

Andrew J. Rech
http://rech.io
________________________________

**Comment by wayneashleyberry** [comment] 2017-12-25 17:34
@jwilm it is indeed faster on my 2016 MacBook Pro, going from ~800usec to 30,000usec

However, it seems to have broken my neovim. Normal vim with an empty `.vimrc` is fine.

<img width="1106" alt="screen shot 2017-12-25 at 19 33 57" src="https://user-images.githubusercontent.com/727262/34341923-9082dbb6-e9aa-11e7-9954-d7f0d51a41b7.png">

**Comment by jwilm** [comment] 2017-12-25 18:36
@wayneashleyberry presumably you mean the reverse of those numbers? 30ms to .8ms?

Regarding the screen corruption, can you check that this doesn't happen on current master? We've landed a lot of patches in the last few days.

**Comment by wayneashleyberry** [comment] 2017-12-26 22:57
@jwilm actually, no... just double checked the numbers against the builds and `master` is running significantly faster than `macos-render-optimization`

Check out [this video](https://youtu.be/PihBvUIZVSs).

Left: `macos-render-optimization` running vim with no `.vimrc` running 
Right: `master` running neovim with my regular config (ie. way more features enabled)

**Comment by jwilm** [comment] 2017-12-29 17:23
Thanks @wayneashleyberry! I was hoping that it was just a problem with short floats, but alas...

Rather than continuing to bug people here, I'll see if I can borrow a colleague's MBP for future tests.

**Comment by kchibisov** [comment] 2020-08-05 00:29
Since #652 was reiterated and merged, closing this issue.

**Closed by kchibisov** 2020-08-05 00:29 UTC
Labels: B - bug, B - performance
