### ISSUE TITLE
Support embolden and hinting for fonts on Linux

### ISSUE THREAD

**Issue by mrkajetanp** [alacritty/alacritty#3698] opened 2020-05-07 20:55 UTC
Hello, would it be possible to support font options such as embolden and hinting for Linux fonts? Setting them system-wide with fontconfig has no effect on Alacritty. It'd be great if it were possible because right now the only workaround I found in order to have macOS-like fonts in Alacritty is setting 'Regular' to 'Bold' which is suboptimal for obvious reasons.

**Comment by chrisduerr** [comment] 2020-05-07 23:16
I'm not sure what you mean by this? What kind of font are you talking about, OTF? You want to use a bolder font without setting the font to bold?

**Comment by mrkajetanp** [comment] 2020-05-08 15:12
I think it's best if I just use examples comparing with st. I'm using Hack Nerd Font, it's TTF but it applies to every other font just as much, unless I'm missing something very important.

This is st with the regular version of the font and the aforementioned font options turned off.
![st_regular](https://user-images.githubusercontent.com/25405190/81418729-0d4ad380-9145-11ea-88b9-8511fd645251.png)
Now, if I edit my ~/.fonts.conf to enable embolden and hinting, the same regular font looks like this, you can clearly see the difference.
![st_embolden_hint](https://user-images.githubusercontent.com/25405190/81418727-0d4ad380-9145-11ea-9c01-41ae2671881e.png)
For comparison this is what simply setting st's font to the bold variant gives me.
![st_bold](https://user-images.githubusercontent.com/25405190/81418725-0c19a680-9145-11ea-8db3-1db561ba98d3.png)

In contrast, Alacritty completely ignores ~/.fonts.conf and seems to be managing fonts independently so I can't exactly replicate this functionality.

For additional comparison here's st (regular font with embolden and hinting) and below it Alacritty, also with the regular font and these same options enabled in ~/.fonts.conf.
![comparison_regular](https://user-images.githubusercontent.com/25405190/81419254-e2ad4a80-9145-11ea-8797-fb9442b6131f.png)
Here the same as above but Alacritty's font is just set to always use the bold variant.
![comparison_bold](https://user-images.githubusercontent.com/25405190/81419252-e214b400-9145-11ea-8260-cb93a9e9b958.png)

Do you think there's some way we could achieve that kind of font configuration within Alacritty as well? Instinctively I think it should be feasible, st is about as simple a terminal emulator as they come so if they can do it it's presumably not too complicated. But then I don't really know how font support is implemented in alacritty so I'm just speculating here.

**Comment by kchibisov** [comment] 2020-05-08 15:16
>Hello, would it be possible to support font options such as embolden and hinting for Linux fonts? 

Embolding - yes, hinting - subjective, since I'm not sure what we're doing wrong with freetype here. Embolden is a fontconfig thing, which could be used, however I'm not sure that there's a direct map of fontconfig hinting to freetype options.

**Comment by kchibisov** [comment] 2020-05-09 08:55
Could you check that  #3703 emboldens the way you want?

**Comment by mrkajetanp** [comment] 2020-05-09 14:22
I can confirm that embolden is now working and respecting fontconfig changes, nicely done!
![alacritty_emboldened](https://user-images.githubusercontent.com/25405190/81476149-2072a780-9208-11ea-90fb-88f2b9b19be3.png)
As you can see on the screenshot, the lack of hinting is still a bit of an issue but I can see how it can be less straightforward to implement. I took a look through st's code to see how they're doing it but they're just delegating all of that to the Xft library instead of using freetype directly. If I'm not mistaken that creates a dependency on X so we can't do that here seeing as we want Alacritty to be multi platform. Do you have any ideas as to how hinting could be implemented?

**Comment by kchibisov** [comment] 2020-05-09 14:26
We do have hinting, the problem is that I have no idea how it should be mapped correctly. So I guess the way to go is to look how cairo, Xft is doing it. We're handing it here https://github.com/alacritty/alacritty/blob/2c2104a51776ac826dde35f54423657f2d5150fb/font/src/ft/mod.rs#L464

**Comment by chrisduerr** [comment] 2020-05-09 15:24
This is a duplicate of #1754.

**Closed by chrisduerr** 2020-05-09 15:24 UTC
Labels: S - font, enhancement

**Comment by kchibisov** [comment] 2020-05-09 15:25
And hinting is a duplicate of #3534

**Comment by mrkajetanp** [comment] 2020-05-10 01:23
> This is a duplicate of #1754.

For the record it's not, that issue you referenced talks about getting actual bold and italic versions of a given font to work in Alacritty. Using embolden on a regular typeface and just using a bold typeface are two completely different things.

This issue should still probably be closed now since we got embolden working and hinting is covered in 3534 but it definitely was not a duplicate of 1754.

**Comment by chrisduerr** [comment] 2020-05-10 01:27
> For the record it's not, that issue you referenced talks about getting actual bold and italic versions of a given font to work in Alacritty.

It's not. Picking actual bold/italic versions already works in Alacritty. That issue is about automatic bold/italics.

**Comment by mrkajetanp** [comment] 2020-05-10 01:33
> It's not. Picking actual bold/italic versions already works in Alacritty. That issue is about automatic bold/italics.

Yes, it is, but it's still a completely separate issue from supporting embolden.

Let me quote from that issue's author: "unfortunately the bold and italic typefaces aren’t available yet".

What he wants is to have a bold and an italic typeface. Embolden doesn't relate to that in any way, it just changes the way in which the typefaces are rendered. Emboldening a regular typeface doesn't make it a bold typeface which seem to be the impression you're getting here. Italics don't come into this in any way whatsoever.
