### ISSUE TITLE
Have Action to scale Font+Win dimension at the same time

### ISSUE THREAD

**Issue by mkulke** [alacritty/alacritty#6552] opened 2022-12-06 16:11 UTC
Coming from MacOS' Terminal App, I grew fond of using Cmd +/- to scale both the font size and the window dimension at the same time, while the ratio is being kept. Kind of like zooming the full window. Alacritty doesn't seem to have this Action implemented. It's rather trivial apparently (kudos for writing approachable software!) I have this implemented in a fork, atm. If this feature is desired, I'd spend time polishing it and open a PR.

If not, that's great too. 🖖

**Comment by chrisduerr** [comment] 2022-12-06 22:53
Closing as duplicate of #388. Feel free to open another issue once that is resolved and your issue still isn't fixed.

**Closed by chrisduerr** 2022-12-06 22:53 UTC
