### ISSUE TITLE
Windows: alacritty failed to exit when needs more interaction to exit

### ISSUE THREAD

**Issue by Escapingbug** [alacritty/alacritty#2695] opened 2019-08-02 02:47 UTC
Which operating system does the issue occur on?
Windows 10 1903

To reproduce:
1. `nvim [file]`(vim should work as well, but I haven't tried)
2. `:w` to save it
3. write anything, but don't save
4. close `alacritty` directly

Now it will hang. My guess is that alacritty tring to shutdown but waiting for all subprocess to shutdown, which will never happen because `vim/nvim` is waiting for user's confirmation of whether to save currently unsaved text.

**Comment by chrisduerr** [comment] 2019-08-02 16:50
How exactly are you closing Alacritty? Using the window actions?

What happens if you request the help of the task manager to shoot it down?

Alacritty shouldn't care about the application running inside of it generally.

**Comment by Escapingbug** [comment] 2019-08-03 01:55
By using the window action (the `x` at top-right, it should be window action?). With the task manager it can successfully shutdown.

It is correct that it shouldn't care about the application running inside, but at least there should be a way to solve this situation..

**Comment by chrisduerr** [comment] 2019-08-03 11:39
I'd assume Alacritty might get locked up by a thread not properly shutting down or something similar at shutdown, though I am not sure why. As far as I know this is not a problem anywhere except for Windows, which doesn't make much sense to me.

Can you reproduce this issue with one of Windows' default terminals? Or any other terminal for that matter?

The main difference between Windows and macOS/Linux is that the PTY interface is different with WinPTY and ConPTY being used on Windows. I'd assume that might be the cause of this. Can you check if this happens both in WinPTY **and** in ConPTY?

**Comment by Escapingbug** [comment] 2019-08-04 05:46
I've tried default terminals and windows terminal (preview), all working. Also, winpty is working. Seems only ConPTY is not working yet.

**Comment by Escapingbug** [comment] 2019-08-06 19:38
I have done some further testing myself finding that when I use `-vv` or `-vvv`, everything seems fine, but `-v` or nothing will be impossible to close the window in some situations.

I've done some debugging, but have no idea what is causing this situation. Could use some help on some gussing of what may causing it.

**Comment by nixpulvis** [comment] 2019-08-07 16:13
@Escapingbug I haven't compiled Alacritty on Windows myself yet, but if you could then I'm assuming you can get some more information about the issue by running Alacritty from source and killing it when it hangs with <kbd>ctrl-c</kbd>. Otherwise e may have to wait until someone else digs into this on Windows.

**Comment by chrisduerr** [comment] 2019-08-07 18:23
Would be interesting to see if this can be reproduced with #2438.

**Comment by Escapingbug** [comment] 2019-08-15 06:36
I will try dig a little bit with #2438. Was on some events last week, will be on this later.

**Comment by Escapingbug** [comment] 2019-08-17 11:15
I've tested this using #2438, finding that even `-vv` and `-vvv` leaves me no luck.. Still not working.

**Comment by davidhewitt** [comment] 2019-10-03 12:39
I get a similar problem when I'm running `webpack-dev-server`; have to kill Alacritty through task manager. I'll try to understand my circumstances a bit better next time I see this.

**Comment by davidhewitt** [comment] 2020-03-25 09:00
@Escapingbug is this still a problem for you on recent Alacritty versions? The problem I was experiencing has been resolved.

**Comment by Escapingbug** [comment] 2020-03-27 17:13
Sorry I have already dropped windows and switched back to my Manjaro Linux. :(

**Comment by chrisduerr** [comment] 2020-03-30 17:36
Assuming the problem has been fixed.

**Closed by chrisduerr** 2020-03-30 17:36 UTC
Labels: A - needs repro, H - windows, W - ConPTY
