### ISSUE TITLE
Crashes on Wayland

### ISSUE THREAD

**Issue by ProjectInitiative** [alacritty/alacritty#6589] opened 2022-12-26 23:00 UTC
Using Wayland causes crashes every so often. Ran from the Gnome terminal with full backtrace enabled below.

### System

OS: PopOs 22.04
Version:  alacritty 0.12.0-dev (c5ae05e8)
Linux/BSD: Wayland

Compiled from source after reading through #6551 and #6487

### Logs

```bash 
RUST_BACKTRACE=1 RUST_BACKTRACE=full  alacritty
wl_shm_pool@27: error 2: shrinking pool invalid
thread 'main' panicked at 'failed to dispatch wayland event queue: Os { code: 71, kind: Uncategorized, message: "Protocol error" }', alacritty/src/event.rs:1438:30
stack backtrace:
   0:     0x5616fafce4e1 - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5616fafce4e1 - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5616fafce4e1 - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5616fafce4e1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5616fae8a56c - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x5616fafa55a4 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x5616fafd0846 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5616fafd0846 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5616fafd0846 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x5616fafd18d6 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x5616fafd18d6 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x5616fafd1372 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x5616fafd12e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5616fafd12a2 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x5616fac6fe12 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x5616fac70092 - core::result::unwrap_failed::h995262f85f9c4e2c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
  16:     0x5616fad03170 - core::result::Result<T,E>::expect::hccac37419a12bef1
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1035:23
  17:     0x5616fad03170 - alacritty::event::Processor::run::{{closure}}::h668c72349f803747
                               at ~/alacritty/src/event.rs:1436:25
  18:     0x5616fac8e51c - winit::platform_impl::platform::sticky_exit_callback::hc612eded5c31d724
                               at /home/kpzak/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/platform_impl/linux/mod.rs:849:9
  19:     0x5616fac8e51c - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::hfae61b12fa80f777
                               at /home/kpzak/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/platform_impl/linux/wayland/event_loop/mod.rs:539:13
  20:     0x5616faced00a - winit::platform_impl::platform::EventLoop<T>::run_return::h4b94b998334c4fcc
                               at /home/kpzak/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/platform_impl/linux/mod.rs:748:56
  21:     0x5616faced00a - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::h9684cc0004f4ae32
                               at /home/kpzak/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.3/src/platform/run_return.rs:62:9
  22:     0x5616faced00a - alacritty::event::Processor::run::h3a7fa90d6fb855e3
                               at ~/alacritty/src/event.rs:1370:25
  23:     0x5616faced00a - alacritty::alacritty::he300ea61d1023134
                               at /~/alacritty/src/main.rs:189:18
  24:     0x5616faced00a - alacritty::main::hfa428b52a1968e7c
                               at ~/alacritty/src/main.rs:83:17
  25:     0x5616fad4d543 - core::ops::function::FnOnce::call_once::h2350a26c1d9e1d75
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  26:     0x5616fad4d543 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb9632a073bb3e007
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:122:18
  27:     0x5616face8050 - main
  28:     0x7fd819629d90 - <unknown>
  29:     0x7fd819629e40 - __libc_start_main
  30:     0x5616fac7c0e5 - _start
  31:                0x0 - <unknown>
```

**Comment by kchibisov** [comment] 2022-12-27 07:11
Duplicate of https://github.com/alacritty/alacritty/issues/6455

Please, provide the logs requested on the mentioned issue.

**Closed by kchibisov** 2022-12-27 07:11 UTC

**Comment by ProjectInitiative** [comment] 2022-12-29 19:10
Been waiting for another crash to add logs. So far, hasn't crashed again.
