### ISSUE TITLE
Add optional to imports

### ISSUE THREAD

**Issue by EdenEast** [alacritty/alacritty#4330] opened 2020-10-22 17:12 UTC
First off I would like to say thanks to @chrisduerr for pr #4138 (was very excited for this)

I started to look at converting my configuration in my dotfiles to use this new feature. I would like to have a base
configuration saved in my dotfiles so that all my different machines have a similar configuration. Although trying to
setup machine specific configuration I ran into a little issue.

In my dotfiles I have something like this in my main configuration entry point `alacritty.yml`:

```yaml
import:
  -  ~/.config/alacritty/visual.yml
  -  ~/.config/alacritty/binding.yml
  -  ~/.config/alacritty/operation.yml

  # Source local machine specific configuration if required
  -  ~/.local/share/alacritty/config.yml
```

On some machines this file may not exist causing an error. I would like to mark this import as `optional`. If the import
does not exist and the import is marked as optional then it would skip trying to source it.

An example of what that would look like:

```yaml
import:
  -  ~/.config/alacritty/visual.yml
  -  ~/.config/alacritty/binding.yml
  -  ~/.config/alacritty/operation.yml
  -  path: ~/.local/share/alacritty/config.yml
     opt: true
```

This would allow for two different formats for `import`. If an import is not explicitly marked as `opt: true` then it
will be assumed false and functionality will remain the same.

I have been moking up this feature in a branch and would be interested in contributing a pr for this issue. Please let me
know your thoughts.

**Comment by chrisduerr** [comment] 2020-10-22 17:26
What are your arguments for making certain paths optional, rather than just making them all optional?

Also why should this be fixed inside of Alacritty instead of just touching the file itself to make sure every file is present on all systems?

**Comment by EdenEast** [comment] 2020-10-22 18:07
Being able to distinguish between optional and required imports would declare indent. I am defining what imports I expect
to be imported and others that I have defined as optional and not required. If a required import does not exist I would
like to be informed about it. An example would be I messed up a rebase in my configuration and there are missing files
that I expect to be there.

As for touching a file that would also work. The ability to clone and launch without extra steps would be nice to have.

**Comment by chrisduerr** [comment] 2020-10-22 19:19
> Being able to distinguish between optional and required imports would declare indent. I am defining what imports I expect
to be imported and others that I have defined as optional and not required. If a required import does not exist I would
like to be informed about it.

This makes sense, but it could probably make it significantly harder to understand this configuration. I'd like to see how this nicely documented to make sure people are aware of how it works.

> As for touching a file that would also work. The ability to clone and launch without extra steps would be nice to have.

This would be an argument for making all configuration files optional. Since you won't be able to clone and launch without extra steps unless all imports are optional.

**Comment by EdenEast** [comment] 2020-10-22 19:38
I created a pull request as an example implementation of what this feature would look like. I do agree that clear
documentation on this feature is required to make sure the user understand the behaviour.

**Closed** 2020-11-19 14:52 UTC
Labels: S - config, enhancement

**Comment by zeb139** [comment] 2024-05-22 22:04
Does this still work with .toml config files?  

```
import = [
  "~/.config/alacritty/colortheme.toml",
  { path = "~\\AppData\\Roaming\\alacritty\\colortheme.toml", optional = true }
]
```  

^This throws an error -> `Invalid import element type: expected path string`. Which seems to agree with the documentation, but it would be nice if the above was still an option for managing configurations between multiple machines.

**Comment by chrisduerr** [comment] 2024-05-22 22:13
Imports are always optional, having them marked as optional was never supported.

**Comment by zeb139** [comment] 2024-05-23 02:16
> Imports are always optional, having them marked as optional was never supported.

https://github.com/alacritty/alacritty/pull/4332  
Did this not effectively add support for optional imports? 
Sorry if I'm misunderstanding the intended behavior (I've only just discovered alacritty). I guess what I'm looking for is whether it's possible to handle non-existing files in imports gracefully.  
What do you think?

**Comment by chrisduerr** [comment] 2024-05-23 02:25
There is no error message if an import doesn't exist. Just look at the patch.

**Comment by zeb139** [comment] 2024-05-23 02:39
![image](https://github.com/alacritty/alacritty/assets/37308742/bf709eda-9dc1-4e16-a105-b5c1c8056aeb)

```
[16.594986519s] [ERROR] [alacritty_config_derive] Unable to import config "/home/omitted/.config/alacritty/does_not_exist.toml": Unable to locate config file
```
```
$ alacritty  --version
alacritty 0.14.0-dev (f04b1616)
```  

If I remove the 2nd import (which intentionally doesn't exist for this test), then everything is fine. 
I'm unfamiliar with .toml, but online linters say it checks out.  

I appreciate your help with this

**Comment by chrisduerr** [comment] 2024-05-23 02:50
Huh, seems you did actually find a regression. The code does not work as intended at the moment.

**Comment by chrisduerr** [comment] 2024-05-23 03:03
From my testing https://github.com/alacritty/alacritty/pull/7994 seems to restore it back to the intended behavior. Let me know if you're still running into any issues.

**Comment by zeb139** [comment] 2024-05-23 03:18
Wow that was quick. Can confirm this change resolves the issue on my end too :+1:   
Thank you!!
