### ISSUE TITLE
usstyle when running on macos

### ISSUE THREAD

**Issue by dkuettel** [alacritty/alacritty#6536] opened 2022-11-29 12:44 UTC
I've been using alacritty for a long time, only on linux. I compile it myself and I'm currently using it at tag `v0.11.0` enjoying the new `usstyle` functionality :)

Occasionally I have to connect to my linux machine with a macos machine. To have feature parity I wanted to install alacritty instead of iterm2, because of `usstyle`. I can't seem to get it to work and I'm not sure where to look for the problem:

Client mac os with alacritty installed `v0.11.0`, then ssh to linux machine, `usstyle` doesnt work. When using alacritty directly on the linux machine, then it works. The server has alacritty termcaps installed, macos does not. I'm using it with `TERM=alacritty`. When connecting from macos to linux either with `TERM=alacritty` or the default `TERM=xterm-...` both give the same result, no `usstyle`.

Am I missing something on the way that is breaking it? I'm sure `usstyle` is implemented irrespective of the platform.

**Comment by chrisduerr** [comment] 2022-12-02 00:39
I have absolutely no clue what `usstyle` is supposed to be.

**Comment by dkuettel** [comment] 2022-12-02 15:52
Thanks for replying. I'm talking about the recent addition in version 0.11.0

```Escape sequence for undercurl, dotted and dashed underlines (CSI 4 : [3-5] m)```

I have a text file that contains the relevant escape codes. I use it to test if everything is setup correctly. On linux and on macos with the same commit version of alacritty, in macos I only get:

<img width="263" alt="Screenshot 2022-12-02 at 16 49 14" src="https://user-images.githubusercontent.com/5509042/205332096-ab4eca3d-0090-4460-857f-1a84ae02bb51.png">

You can see that double underline is missing, and the dotted underline as well. I'm not sure where else to look for the problem. Since I `cat` the file with the escape code directly on macos, no ssh or tmux involved, it seems like there is nothing else left but alacritty not interpreting the codes? Even though the same version on linux does it.

Am I wrong in assuming all escape codes are implemented irrespective of the OS? Or does the ability to draw those underlines depend on the font chosen?

**Comment by chrisduerr** [comment] 2022-12-02 17:31
Are you **positive** you're running the correct version? Try running `alacritty --version` and then use that executable to also open Alacritty.

**Comment by dkuettel** [comment] 2022-12-02 18:42
Yes, when doing

```
$ /Applications/Alacritty.app/Contents/MacOS/alacritty --version
alacritty 0.11.0 (8dbaa0b)
$ /Applications/Alacritty.app/Contents/MacOS/alacritty
```

I get the previous picture. Is there value running it with some `verbose` flag?

**Comment by chrisduerr** [comment] 2022-12-02 19:34
If it gives you the previous picture, everything is working as intended.

**Comment by dkuettel** [comment] 2022-12-02 20:15
Can you elaborate? With the same version on linux I see the dotted underlines.

**Comment by chrisduerr** [comment] 2022-12-02 22:18
Double underlines are 4:2, not 21. So that's why they're missing.

Can you try running `echo -e "\e[4:4mTEST"` on macOS?

**Comment by dkuettel** [comment] 2022-12-03 18:46
Ah got it. I've been using 21 forever, but I just realize it only worked because I was inside tmux there and tmux seems to translate it.

`echo -e "\e[4:4mTEST"` on linux shows dotted underlines.
`echo -e "\e[4:4mTEST"` on macos does not. But `:1/2/3` all work..

**Comment by chrisduerr** [comment] 2022-12-03 23:38
Can you try the latest master please?

**Comment by kchibisov** [comment] 2022-12-04 01:45
Try `echo -e "\e[4:3mTEST"`. Dotted was broken on macOS and should be fixed with the next patch release.

**Closed by kchibisov** 2022-12-04 01:45 UTC
