### ISSUE TITLE
When focusing alacritty window with a depressed modifier, it remains in action

### ISSUE THREAD

**Issue by pirj** [alacritty/alacritty#3491] opened 2020-03-19 19:37 UTC
I'm on macOS and use `Cmd-U`/`Cmd-I` to switch between workspaces where I have several browser workspaces and Alacritty open on the leftmost workspace. Sometimes, quite often, especially when I press `Cmd-U` multiple times, I seem to release Cmd before the focus happens.

In addition to that, which makes this quite a corner case, I have Cmd+alphabetic remapped in a way that they act like Ctrl+alphabetic, mostly because I find Cmd more reachable in combinations and use physical Ctrl very rarely if ever:
```
key_bindings:
  - { key: A, mods: Command, chars: "\x01" }
  - { key: B, mods: Command, chars: "\x02" }
  - { key: C, mods: Command, chars: "\x03" }
  - { key: D, mods: Command, chars: "\x04" }
...
```

This results in the following when e.g. typing `e`:
![image](https://user-images.githubusercontent.com/6916/77105151-3ba60f80-6a2e-11ea-8a2b-e1544e72cc7c.png)
i.e. what would normally happen if you press `Cmd-e`.

I've recently switched from kitty, can't reproduce the issue there or in Terminal.app.

A workaround (quite burdensome) is to tap Cmd once I switch to Alacritty.

### System

OS: macOS 10.14.6
Version: 0.4.1 ([from Homebrew](https://github.com/Homebrew/homebrew-cask/blob/dfe8f87fdd1476ed720b5278fb77b8d4c3b71b45/Casks/alacritty.rb))

Additional software: Karabiner elements ([maps Cmd to Caps Lock](https://github.com/pirj/dotfiles/blob/master/.config/Karabiner/assets/complex_modifications/capslock_to_esc_and_command.json#L10))

**Comment by kchibisov** [comment] 2020-03-19 19:40
Fixed in latest Rc.

**Comment by kchibisov** [comment] 2020-03-19 19:41
duplicate of #3188

**Closed by kchibisov** 2020-03-19 19:40 UTC

**Comment by pirj** [comment] 2020-03-19 21:51
Thanks a lot!
