### ISSUE TITLE
Alacritty does not recognize the virtual keycode for Right Alt

### ISSUE THREAD

**Issue by mroavi** [alacritty/alacritty#4781] opened 2021-02-09 18:57 UTC
OS: Manjaro Linux x86_64
Kernel: 5.10.7-3-MANJARO
Version: alacritty 0.7.1 (a852eb85)
Linux: X11

Alacritty does not recognize the <kbd>Right Alt</kbd> scancode. This the log of `alacritty --print-events` corresponding to a <kbd>Right Alt</kbd> press. 
```
[2021-02-09 19:43:28.764468860] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(26))), event: Key(KeyboardInput { scancode: 100, state: Released, virtual_keycode: None, modifiers: (empty) }) }
```
Accorgint to [`Enum glutin::event::VirtualKeyCode`](https://docs.rs/glutin/0.26.0/glutin/event/enum.VirtualKeyCode.html), the `virtual_keycode` should be `RAlt`.

Output of `setxkbmap -query`:
```
> setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,latam
variant:    ,
options:    grp:alts_toggle
```

**Comment by chrisduerr** [comment] 2021-02-09 19:18
Duplicate of https://github.com/alacritty/alacritty/issues/3460.

**Closed by chrisduerr** 2021-02-09 19:18 UTC
