### ISSUE TITLE
Visual bell not working on Windows?

### ISSUE THREAD

**Issue by scy** [alacritty/alacritty#4667] opened 2021-01-06 20:32 UTC
I’ve tried running `alacritty -vvv -e wsl` from a Windows `cmd` terminal. Alacritty starts up, but e.g. hitting <kbd>Backspace</kbd> on my bash prompt or running `printf '\a'` does result neither in an audible, nor in a visual bell.

The log output during the `printf '\a'` (tested using `sleep 3; printf '\a'; sleep 3`) is simply

```
[2021-01-06 21:24:17.888383800] [TRACE] [alacritty_terminal] Unsetting mode: ShowCursor
[2021-01-06 21:24:17.888383800] [TRACE] [alacritty_terminal] Setting mode: ShowCursor
```

My `alacritty.yml` is simply

```yaml
bell:
  duration: 1000
```

I’ve also tried setting `bell.command` to `explorer`, but there’s no Explorer being launched either. (And yes, I’ve tried changing colors in the config to see whether the `alacritty.yml` is being read at all; it is.)

My guess would be that for some reason Alacritty simply doesn’t see the bells at all? Is there anything else I can try? Is this a known issue? I couldn’t find anything about it.

### System

OS: Windows 10
Version: `alacritty 0.6.0 (04cbf76)`

**Comment by chrisduerr** [comment] 2021-01-07 03:24
This sounds like a Windows PTY issue to me, I don't think there's anything Alacritty can do about that. Have you tried the latest master?

**Comment by scy** [comment] 2021-01-07 14:19
> Have you tried the latest master?

I have now.

I’ve built `alacritty 0.8.0-dev (c566f78)` with `stable-x86_64-pc-windows-msvc unchanged - rustc 1.49.0 (e1884a8e3 2020-12-29)`. It displays the same behavior.

> This sounds like a Windows PTY issue to me, I don't think there's anything Alacritty can do about that.

I suspected as much. However, since I found nothing about that issue in the readme, the example `alacritty.yml` or the existing GitHub issues, I at least wanted to report it for others to see.

Thanks anyway for your time!

**Comment by scy** [comment] 2021-01-07 15:01
One more thing: I’ve looked around a bit for what Windows Terminal does about this, and they at least interpret `DECSCNM` (screen mode light/dark, i.e. `CSI ? 5 h` and `CSI ? 5 l`) which can be used for quickly inverting and thus flashing the terminal. It works with `tput flash` or Vim’s `'visualbell'`, and probably also with a corresponding `inputrc` setting.

However, since it’s basically “invert the screen” followed by “don’t invert the screen” in rapid succession, Alacritty can probably not easily interpret it as “do a visual bell”.

**Comment by chrisduerr** [comment] 2021-01-07 16:14
@scy Does proper flashing work in the windows terminal, using the bell?

**Comment by scy** [comment] 2021-01-07 17:27
First of all, just to be clear, when I’m talking about Windows Terminal, I’m talking about [the “new” application of the same name](https://github.com/microsoft/terminal), not a normal `cmd` or PowerShell window.

They’ve [recently incorporated bell support](https://github.com/microsoft/terminal/pull/7679). The current stable version (1.4.3243.0, available from the Windows store) doesn’t have the feature yet. However, the “preview” version (1.5.3242.0, also on the store) comes with it. Note that we’re only talking about _audible_ bell support. Windows Terminal has no visual bell support on its own; one has to rely on the applications (like Vim, readline etc.) for a visual bell implementation.

My tests resulted in:

* The stable version simply ignores `\a` characters. No audible bell.
  * Of course, if you configure your _application_ to use some kind of visual bell instead, e.g. by flashing the terminal using the aforementioned CSI sequences, this works.
* The preview version rings an audible bell on `\a`.
  * If you configure your application to use a visual bell instead, this still works. Again, there is _no_ setting or option inside of Windows Terminal _itself_ to replace all audible bells with visual ones.

The audible bell on `\a` in the preview version worked both in a PowerShell tab (by typing `echo ` followed by <kbd>Ctrl</kbd>+<kbd>G</kbd>, which will be displayed as `echo ^G`, and hitting <kbd>Enter</kbd>) as well as in a WSL1 and WSL2 bash tab (by running `printf '\a'`).

I know too little about Windows Terminal’s inner workings and whether Alacritty could also hook into whatever WT is doing to get bell support as well.

**Comment by chrisduerr** [comment] 2021-01-07 19:04
Hmm, the PR says that the bell was already being forwarded through ConPTY, in which case it should work just fine for Alacritty.

Though the ConPTY shipped by default is **really** old, chances are it's just going to be fixed with an update at some point.

Since I see no indication that this would be an error with Alacritty, I'm going to close this issue for now. If someone can reproduce this with the latest ConPTY version, please let me know and I can re-open.

**Closed by chrisduerr** 2021-01-07 19:04 UTC
