### ISSUE TITLE
Alacritty Doesn't Open on MacOS Big Sur

### ISSUE THREAD

**Issue by Exr0n** [alacritty/alacritty#3880] opened 2020-06-23 21:41 UTC
MacOS: 11.0 Beta (20A4299v)
Alacritty Version: fresh 0.4.3 from the Releases page.

## Issue:

Clicking on the application icon and launching from Spotlight does nothing.

`open -a Alacritty`: `LSOpenURLsWithRole() failed for the application /Applications/Alacritty.app with error -1.`

I am able to Show Package Contents and launch the binary directly, so creating a dock shortcut works for now. Most of my other apps work so I wonder if there's something that needs to be updated here?

This is a very low priority issue since this is such an early beta but I'm just creating it to track the progress. Thanks!

Similar to #943

**Comment by chrisduerr** [comment] 2020-06-23 22:42
Have you confirmed the execution of Alacritty as an unauthorized application?

If that is done, you could check if the folder structure of Alacritty is different than other applications, it shouldn't be but if it is that might be a hint on what could be wrong.

If neither of those two help, deleting the application from /Applications and trying to reinstall them might also be worth a shot. Alternatively you can try to `touch` the Info.plist.

If none of these suggestion fix or change the error message, please let me know.

**Comment by imjma** [comment] 2020-06-24 01:39
I deleted the application `rm -rf /Applications/Alacritty.app` , and `make clean app` to rebuild the app, then copy to the Applications. Same errors given `LSOpenURLsWithRole() failed for the application /Applications/Alacritty.app with error -1.`

**Comment by Exr0n** [comment] 2020-06-24 01:50
1. Alacritty was authorized to run with System Preferences > Security & Privacy > Open Anyways
2. The folder structure of Alacritty (Contents/MacOS/executable_name) is the same as other apps (Amphetimene, AnyLogic, PikoPixel) that open properly.
3. The app was a clean install when I first created the issue. (I had 0.4.2 before but that was also broken, with a different error.)
4. `touch info.plist` does not change the error message from `open -a Alacritty` or the behavior when double-clicked from Finder.

Thanks for your help!

**Comment by chrisduerr** [comment] 2020-06-24 02:03
Can you try to recompile from source, editing the `Makefile` in the Alacritty root and replacing the variable `MACOSX_DEPLOYMENT_TARGET` with `11.0`?

**Comment by imjma** [comment] 2020-06-24 02:14
`note: clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'` or note: clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11.0'

**Comment by chrisduerr** [comment] 2020-06-24 02:40
@imjma Could you try `10.15`?

**Comment by imjma** [comment] 2020-06-24 03:18
> @imjma Could you try `10.15`?

build passed, but get same error `LSOpenURLsWithRole() failed for the application /Applications/Alacritty.app with error 1.`

**Comment by chrisduerr** [comment] 2020-06-24 12:49
Since macOS 11 is still so fresh, the best bet is probably to give it some time and see if that helps with things. Hopefully they'll figure it out.

**Comment by mcansh** [comment] 2020-06-24 17:29
for whatever reason, most things on Big Sur report the version as 10.16 (e.g `sw_vers -productVersion`), changing `MACOSX_DEPLOYMENT_TARGET` to 10.16 and building made it work for me. 

```sh
make binary
make app
open ./target/release/osx/Alacritty.app
```

**Comment by kchibisov** [comment] 2020-06-24 18:00
Thanks for finding that out. In general, I'd like to wait for apple to release their new macOS, so we can update `MACOSX_DEPLOYMENT_TARGET` to a proper version based off the system we're compiling to. I feel like it's a bit related to their new ARM support to some point, so that's why different deployment target should be used?

**Comment by fernandoalex** [comment] 2020-06-24 18:05
> ```diff
> - MACOSX_DEPLOYMENT_TARGET="10.11" cargo build --release
> + MACOSX_DEPLOYMENT_TARGET="10.16" cargo build --release
> ```
> 
> ```shell
> make binary
> make app
> open ./target/release/osx/Alacritty.app
> ```

@mcansh workaround worked for me 👍

**Comment by mcansh** [comment] 2020-06-24 18:12
@kchibisov yeah gotta be something around ARM. side note, changing the deployment target back to 10.11 and rebuilding also opens on Big Sur for me lol.. 🙃

**Comment by imjma** [comment] 2020-06-24 18:38
Thanks @mcansh , I usually build by `make clean app`, I missed the `binary`! Will try later, cheers

**Comment by imjma** [comment] 2020-06-24 23:42
@mcansh 

It looks like not working on mine

`open ./target/release/osx/Alacritty.app
LSOpenURLsWithRole() failed with error 1 for the file /Users/jma/repos/alacritty/target/release/osx/Alacritty.app.`

**Comment by mcansh** [comment] 2020-06-25 00:08
weeeeeeird, worked for me on a fresh clone. Did you do a normal upgrade to Big Sur or fresh install it?
https://www.youtube.com/watch?v=d3mf_G_w190&feature=youtu.be

**Comment by imjma** [comment] 2020-06-25 00:33
@mcansh I did a normal upgrade, also installed Xcode, tried both `10.11` and `10.16` with fresh clone, and still not working...

![Screen Shot 2020-06-25 at 10 21 09](https://user-images.githubusercontent.com/115142/85640444-2694e880-b6cf-11ea-8962-f748c89e1cc7.jpg)

**Comment by mcansh** [comment] 2020-06-25 00:38
interesting did you upgrade your command line tools also? I had to do it manually to fix brew https://developer.apple.com/download/more

[Alacritty.dmg.zip](https://github.com/alacritty/alacritty/files/4828525/Alacritty.dmg.zip)

**Comment by imjma** [comment] 2020-06-25 01:21
@mcansh I installed xcode beta that includes command line tools. Thanks for the dmg file.

**Comment by mcansh** [comment] 2020-06-25 01:23
@imjma yeah so did I, but I still had to manually update my CLTs for brew (and compiling alacritty) to work

**Comment by imjma** [comment] 2020-06-25 01:33
@mcansh ahh. yes, it works after I fixed brew by `sudo xcode-select --switch /Applications/Xcode-beta.app` 👍

**Comment by 4cm4k1** [comment] 2020-07-25 02:39
Hi, just want to drop a note saying that Alacritty appears to work properly on the third macOS Big Sur Developer Beta - 11.0 Beta (20A5323l), in case the workarounds posted above do not work for other users. 😄

**Comment by chrisduerr** [comment] 2020-07-25 03:11
@4cm4k1 Did you have issues on previous versions, or have you tested just the latest beta?

**Comment by 4cm4k1** [comment] 2020-07-25 03:13
@chrisduerr Alacritty would not launch for me as described in this issue with beta 2. This evening I installed beta 3 and now Alacritty launches with no issue.

**Comment by chrisduerr** [comment] 2020-07-25 03:41
Thanks for the report, I'm going to close this issue for now then. If anyone else can still reproduce this, please let me know.

**Closed by chrisduerr** 2020-07-25 03:41 UTC
Labels: A - deps, C - waiting on dependency, H - macos, S - packaging

**Comment by semanser** [comment] 2020-11-13 09:43
@imjma Sorry for the offtopic, but how did you center your tmux windows list?
<img width="403" alt="Screenshot 2020-11-13 at 11 42 58" src="https://user-images.githubusercontent.com/4020045/99058140-72c0c680-25a5-11eb-95cd-69bcce51cb3b.png">

**Comment by imjma** [comment] 2020-11-13 10:17
> @imjma Sorry for the offtopic, but how did you center your tmux windows list?
> <img alt="Screenshot 2020-11-13 at 11 42 58" width="403" src="https://user-images.githubusercontent.com/4020045/99058140-72c0c680-25a5-11eb-95cd-69bcce51cb3b.png">

you can check my conf of tmux
https://github.com/imjma/dotfiles/blob/master/tmux.conf#L126

**Comment by facetheheat** [comment] 2021-05-23 20:55
I've the same issue on Big Sur 11.3.1
This `sudo xattr -r -d com.apple.quarantine ./target/release/osx/Alacritty.app` solved an issue.

**Comment by mauricioklein** [comment] 2021-06-28 21:52
I'm having problems with Alacritty on MacOS as well (MacOS Catalina 10.15.7).

```
$ open ./target/release/osx/Alacritty.app # works!
$ open -a Alacritty # works

$ cp -r target/release/osx/Alacritty.app /Applications/

$ (Try to open Alacritty by using the icon on Applications) # fails
```

Alacritty compiled locally as described in the docs

Any suggestion?

Thanks in advance! 🙂

**Comment by 4cm4k1** [comment] 2021-06-28 22:00
@mauricioklein I install Alacritty through Homebrew `brew install --cask alacritty`, but here are two options that might help you:
1. `sudo codesign -f -s - "/Applications/Alacritty.app/Contents/MacOS/alacritty"` (ad-hoc signs the executable with your user, `-f` = force-replaces any bad signature, `-s -` = ad-hoc signs)

and/or

2. `xattr -d com.apple.quarantine /Applications/Alacritty.app` (tells macOS not to warn you about lack of signature, etc.)

**Comment by mauricioklein** [comment] 2021-06-28 22:10
Thanks @4cm4k1 !

I had Alacritty installed via Homebrew before and was having the same problem as now.

Both commands above, unfortunately, haven't work 😕
