### ISSUE TITLE
Block-characters have gaps

### ISSUE THREAD

**Issue by Purtl** [alacritty/alacritty#8101] opened 2024-07-23 11:13 UTC
### System

OS: Linux NixOS 
Version: 13.1
Linux/BSD: SwayWM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
```

[0.017760484s] [INFO ] [alacritty] Using EGL 1.5
[0.017788029s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.020109392s] [INFO ] [alacritty] Window scale factor: 1
[0.020807587s] [DEBUG] [alacritty] Loading "RobotoMono Nerd Font Propo" font
[0.028838680s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.031687633s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.034451107s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.037008322s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.038306994s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics (TGL GT1)
[0.038316977s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 24.0.1, shader_version 4.60
[0.038321168s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.042340236s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.042456608s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
```

So, basically everywhere I use block characters 
 or  and want to "paint" over multiple lines I get a lot of gaps:
![1721732917-527](https://github.com/user-attachments/assets/6e5888a6-5c33-427b-9849-c36467fec09c)

I already tried to fiddle with /etc/fonts/local.conf but things got only worse. I don't even know where to look. What am I missing?

**Comment by kchibisov** [comment] 2024-07-23 11:23
Generally this is because it doesn't align properly and we can not use this character in builtin font since this character is in private area meaning that it could be something else depending on the font.

The only things we can add is from https://www.unicode.org/charts/PDF/U1FB00.pdf and you can see that it has references to lower left/right triangles, etc.

duplicate of #7422. Should be simple to add 4 triangles though if you really want them. it's in builtin_font.rs.

**Closed by kchibisov** 2024-07-23 11:23 UTC
