### ISSUE TITLE
Escape control sequence not passed from tmux to alacritty

### ISSUE THREAD

**Issue by Sh4d1** [alacritty/alacritty#2589] opened 2019-06-24 20:45 UTC
Which operating system does the issue occur on?
Archlinux

If on linux, are you using X11 or Wayland?
X11

Hey,

I'm using [pywal](https://github.com/dylanaraps/pywal) and echoing bash control sequences [like that](https://gist.github.com/Sh4d1/699f2e9697293647af1c89ce9e179909).

When I cat these characheters in alacritty it works but when I start alacritty with tmux: `alacritty -e tmux` it does not work (but works with other terminal emulators and tmux)

**Comment by chrisduerr** [comment] 2019-06-24 21:18
What terminfo do you have set? Can you reproduce this when changing the terminfo in tmux?

This might not necessarily be an Alacritty problem, but rather due to how tmux sits in between the shell and Alacritty.

**Comment by Sh4d1** [comment] 2019-06-25 07:25
@chrisduerr In my `.zshrc` I have `TERM=xterm-256color` and in tmux I have `set -g default-terminal "tmux-256color"`. I tried with different combination without success.

**Comment by Sh4d1** [comment] 2019-06-25 07:51
@chrisduerr here are the [log](https://gist.github.com/Sh4d1/abb9147a36e5953020a1b7e54331cd16) of `alacritty -vvv` and the [ones](https://gist.github.com/Sh4d1/4b99b44d823f0fa7f507057f1c11e4cf) of `alacritty -vvv -e tmux`

**Comment by kchibisov** [comment] 2019-06-25 17:15
@Sh4d1 Could you set your `TERM` variable in `alacritty.yml` ( and remove entry from `.zshrc`) to `xterm-256color` (`alacritty`) and add the following line to `.tmux.conf`  `set -g terminal-overrides ",xterm-256color:RGB"` (`set -g terminal-overrides ",alacritty:RGB"`) and retest?

**Comment by Sh4d1** [comment] 2019-06-25 21:08
@kchibisov same results, nothing changes. (But when setting `TERM` to `alacritty` in the alacritty config file, `alacritty -e tmux` opens and the closes immediatly :(

**Comment by kchibisov** [comment] 2019-06-25 21:11
@Sh4d1 Do you have `alacritty` terminfo installed (`alacritty-terminfo` package on Arch or check out `INSTALL.md`)? tmux setting that I'm suggesting here is very important, since without it your `tmux` can be broken.

**Comment by Sh4d1** [comment] 2019-06-25 21:15
@kchibisov pretty sure it's not installed, will install it tomorrow and keep you posted :)

**Comment by Sh4d1** [comment] 2019-06-26 06:57
@kchibisov tried with `alacritty-terminfo` installed, same result :(

**Comment by chrisduerr** [comment] 2019-06-26 18:24
Can you reproduce this in any other terminal emulator?

**Comment by Sh4d1** [comment] 2019-06-26 18:29
Tried with kitty and urxvt and it works with both!

**Comment by chrisduerr** [comment] 2019-06-26 18:35
Are you sure? When I run URxvt with tmux (both an empty config), it doesn't work either. It seems to me like this must be a tmux issue.

**Comment by Sh4d1** [comment] 2019-06-26 18:37
Maybe I tweaked it.. Gonna try with a fresh urxvt/tmux combo tomorrow then!

**Comment by martinffx** [comment] 2019-11-01 15:10
I'm experiencing this on MacOS

**Comment by ecly** [comment] 2020-08-16 10:14
@chrisduerr @kchibisov - I believe my current experience on Arch Linux may be related to this. 
Specifically, I'm experiencing different behavior with how colors are applied from `pywal` escape sequences when running `alacritty -e tmux` and running `alacritty` and manually entering `tmux`. 
It seems as though all colors are just slightly thrown off when using `alacritty -e tmux`.
It works as expected in `urxvt`.

My relevant lines from `.tmux.conf`:
```ini
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"
```

and I have the following in `alacritty.yml`:
```ini
env:
    TERM: alacritty
```

alacritty version: 0.5.0
tmux version: 3.1b

Colors  when running `alacritty` and manually calling `tmux`:
![right](https://user-images.githubusercontent.com/8410422/90332050-169bd580-dfa9-11ea-98ed-e485977824d4.png)

Colors when running `alacritty -e tmux`:
![wrong](https://user-images.githubusercontent.com/8410422/90332043-0683f600-dfa9-11ea-8e65-3aa2d696c663.png)

**Comment by chrisduerr** [comment] 2020-11-28 15:06
Closing this issue due to lack of a follow-up. If this still doesn't work, please let me know.

**Closed by chrisduerr** 2020-11-28 15:06 UTC
Labels: A - needs repro, C - waiting on author
