### ISSUE TITLE
Binding to "Grave" key stopped working

### ISSUE THREAD

**Issue by bugeats** [alacritty/alacritty#1336] opened 2018-05-29 23:02 UTC
Just updated Alacritty here on macOS 10.13.4 and one of my critical keybindings stopped working.

This doesn't work anymore:

https://github.com/bugeats/dotfiles/blob/master/src/config/alacritty/alacritty.yml#L200

But this does still work:

https://github.com/bugeats/dotfiles/blob/master/src/config/alacritty/alacritty.yml#L188

Both are configured to send the same character. My only guess is that `Grave` is no longer identified.

**Comment by francesca64** [comment] 2018-05-31 16:13
1. This originates in winit, specifically a result of tomaka/winit#518.
2. When reporting issues about keyboard handling, always include the input method + layout. For instance, grave will be interpreted rather differently on the US international layout, which is something winit was oblivious to before.
3. I recommend that someone other than me looks into fixing this, since A) it's probably not too hard, and B) I already have a lot on my plate, so I wouldn't be able to get to this for a while.

**Comment by jwilm** [comment] 2018-05-31 16:15
@bugeats you can run alacritty with `--print-events` to see what key name is being detected and update your config with that.

**Comment by bugeats** [comment] 2018-05-31 16:36
When I press **Command + A** I see something like this in the events:

    glutin event: WindowEvent { window_id: WindowId(Id(140724590965728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 54, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
    glutin event: WindowEvent { window_id: WindowId(Id(140724590965728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
    glutin event: WindowEvent { window_id: WindowId(Id(140724590965728)), event: ReceivedCharacter('a') }

When I press **Command + `** (Grave) I see this:

    glutin event: WindowEvent { window_id: WindowId(Id(140724590965728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 54, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true  }  }  }  }
    glutin event: WindowEvent { window_id: WindowId(Id(140724590965728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 54, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false  }  }  }  }

I appears to me that the Grave character is not even being sent/recognized.

**Comment by bugeats** [comment] 2018-05-31 16:39
Input method: both native MacBook Pro keyboard, and external USB keyboard in US English.

**Comment by jwilm** [comment] 2018-05-31 16:39
Given that Command + Grave is a system keybinding, I wonder if the underlying change to winit basically prevents that from being forwarded to the application.

**Comment by francesca64** [comment] 2018-06-04 12:12
Is it really considered necessary for winit to handle system keybindings? I've put together a fun hack that makes this work again (https://github.com/francesca64/winit/tree/macos-grave) but it feels *unclean*. Besides that, it results in everyone getting a grave character when using the system shortcut.

The reason this used to work was because winit's macOS keyboard handling was formerly quite naïve. Do other apps allow you to use this shortcut?

**Comment by bugeats** [comment] 2018-06-04 18:16
> Do other apps allow you to use this shortcut?

Not in my experience. Alacritty has a very raw keybinding experience on macOS and everything must be specified. I personally like it this way, and I've used it to my advantage. The *Command + Grave* combo is the system-wide convention for flipping between windows, scoped by application. In my case, I use it to navigate tmux sessions.

**Comment by francesca64** [comment] 2018-06-04 20:17
Well, if someone comes up with a fix that doesn't cause issues elsewhere, I'll gladly merge it.

**Comment by francesca64** [comment] 2018-06-05 20:22
So, the reason that hack results in receiving a grave character is because of the `doCommandBySelector` handler, which is implemented to just return the characters associated with the most recent key down event. This is was done so that Ctrl+C/etc. would generate characters, since those don't trigger `insertText` and instead trigger `doCommandBySelector:noop`. Cmd+Grave also triggers `doCommandBySelector:noop`, but no other `NSTextInputClient` handlers.

So, new more sophisticated hack idea:
- General key down/up handing would still be done through the responder chain, setting a flag to indicate it's being received the normal way
- The event loop would forward key down/up events to custom `WinitView` methods that place `KeyboardInput` events into a queue
- Every call to `insertText` or `doCommandBySelector` would reset the flag and queue; normally the queue is just discarded
- If `doCommandBySelector` is triggered and the flag isn't set, then the key events in the queue are sent to the user, instead of the regular `ReceivedCharacter` event generation behavior

I know I insinuated I didn't want to work on this, but I'm unfortunately addicted to problem solving. I'll try to implement this tomorrow.

**Comment by francesca64** [comment] 2018-06-06 18:08
Well, it's messy, but it seems to work: https://github.com/francesca64/winit/tree/macos-grave

@bugeats let me know if this works for you. It would also be good if other people tested this, in case of regressions.

**Comment by snoblenet** [comment] 2018-06-24 23:39
is there a branch of Alacritty that uses your branch of macos-grave @francesca64 ?

I'd be keen to test it

**Comment by francesca64** [comment] 2018-06-25 00:18
Here, I just threw one together: https://github.com/francesca64/alacritty/tree/macos-grave

**Comment by unphased** [comment] 2018-06-26 19:29
I've encountered this problem, with Grave, but also with Ctrl+Tab. @francesca64 Do you think that is also plausibly caused by the same issue? I'll test the branch.

**Comment by unphased** [comment] 2018-06-26 19:40
log from print events: 

```
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: Focused(true) }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: ReceivedCharacter('\u{1}') }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 48, state: Released, virtual_keycode: Some(Tab), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140551206796576)), event: Focused(false) }
```

This is me focusing the window, pressing Ctrl, pressing and releasing A, pressing and releasing Tab, releasing Ctrl, and pressing Cmd (to focus to another window)...

**Comment by moon-stripe** [comment] 2018-07-03 20:04
i think i'm seeing the same thing with `<C-space>`

```bash
➤ cargo run -- --print-events | grep -v Awakened
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/alacritty --print-events`
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: Resized(610, 414) }
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: Moved(208, 611) }
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: Focused(true) }
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 8, state: Pressed, virtual_keycode: Some(C), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140245736983792)), event: ReceivedCharacter('\u{3}') }
^C
```

that's just hitting `<C-Space>` and then `<C-c>`. The `Space` doesn't appear at all.

**Comment by sodiumjoe** [comment] 2018-08-13 22:14
Did a bit of investigation here: https://github.com/tomaka/winit/issues/625

I think this can be closed as wontfix. @bugeats I've had good results with remapping `<C-tab>` using [BetterTouchTool](https://folivora.ai/) to do something very similar.

**Comment by sodiumjoe** [comment] 2018-08-17 05:28
@unphased the <C-Tab> issue was fixed in winit in https://github.com/tomaka/winit/pull/629, which should get into https://github.com/jwilm/alacritty/pull/1403, hopefully pretty soon

**Comment by sodiumjoe** [comment] 2018-08-21 20:35
@unphased sorry i meant <C-Tab>. I think <Cmd-grave> is a wontfix https://github.com/tomaka/winit/issues/625#issuecomment-412404754

<Cmd-grave> works correctly for winit's multiwindow example, so i think [once alacritty supports multiple windows](https://github.com/jwilm/alacritty/issues/607#issuecomment-373772190), it should start working correctly for alacritty.

**Comment by unphased** [comment] 2018-08-21 20:44
Yes that would be the true solution. I will use a BetterTouchTool key bind hack to trigger my AppleScript which toggles the windows in the meantime!

**Comment by sodiumjoe** [comment] 2018-08-21 20:49
in any case i don't think `<Cmd-grave>` will be bindable to another key, so I think this issue should be closed

**Comment by chrisduerr** [comment] 2018-08-21 20:49
Thanks for the clarification. I've updated the #1403 PR and removed this issue from the list of problems solved by it.

**Comment by lucat1** [comment] 2020-06-14 19:07
Sorry to bring up this old issue, but I think I could be facing the same issue when trying to bind `ctrl+grave`. I have tested it with `alt+grave` and it seems to be working fine.

Here are my keybinds:
```yaml
  - { key: Grave,     mods: Control,    chars: 'testtesttest'         }
  - { key: Grave,     mods: Alt,        chars: 'testtesttest'         }
```

**Comment by danillos** [comment] 2023-03-01 13:51
To `Grave` works with `Command` I had to change on MacOS the Keyboard Shortcuts `Move Focus to Next Window` to another one, I used  ```Alt + ` ```

**Closed** 2023-07-11 02:22 UTC
