### ISSUE TITLE
Alacritty pastes double newlines from a multiline clipboard

### ISSUE THREAD

**Issue by aprowe** [alacritty/alacritty#5258] opened 2021-06-18 20:31 UTC
### System

OS: Windows (WSL)
Version: 0.8.0

Hello, when I paste multiple lines into alacritty, whether its straight into terminal or vim, it puts two newlines for every newline.
I confirmed that this behavior does not happen in other terminal emulators with the same content and context. 

I though perhaps it was pasting `/r/n`, but by the time it gets to vim it is `/n/n`
Any ideas on this?
Thanks

**Comment by chrisduerr** [comment] 2021-06-18 20:33
Duplicate of https://github.com/alacritty/alacritty/issues/2324.

**Closed by chrisduerr** 2021-06-18 20:33 UTC
