### ISSUE TITLE
Alacritty freezes permanently if resize below terminal prompt On x11 `username@My-Ubuntu:~$`

### ISSUE THREAD

**Issue by cratolabs** [alacritty/alacritty#6794] opened 2023-03-17 14:58 UTC
I am resizing window to small portion and it freezes permanently after multiple retries for resizing below `terminal prompt`.
Also it is not wrapping the `terinal prompt` well if I resize window to length less than length of `terminal prompt`.
It prints the terminal prompt again and again if I resize below length of `terminal prompt` and than increase size , like `username@My-Ubuntu:~$username@My-Ubuntu:~$username@My-Ubuntu:~$username@My-Ubuntu:~`<br>
Such repetition of `terminal prompt` I also saw on gnome-terminal but not crashes but it also limits the minimum size of terminal.<br>
So the issue is that alacrity crashes in such instances . 

### System

OS: Linux
Version: alacritty 0.13.0-dev (d0078ffc)
Linux: X11

### Logs

Font/Terminal size:"monospace" font / Width: 238, Height: 238
`alacritty --print-events`<br>
                    `[14.679103157s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(73400324)))<br>
                    [14.679135696s] [INFO ] [alacritty] winit event: RedrawEventsCleared<br>
                    [14.680087809s] [INFO ] [alacritty] Padding: 6 x 6<br>
                    [14.680183149s] [INFO ] [alacritty] Width: 238, Height: 238`

**Comment by kchibisov** [comment] 2023-03-17 15:02
Please, provide a backtrace if something is crashing. From what I can see, nothing is crashing in what you've provided.

**Comment by cratolabs** [comment] 2023-03-17 15:47
I checked again, it is an issue on X11. On Wayland, it is working fine for me and not freezing on Wayland. <br>
But the repetition of the terminal prompt is there on both
![Screenshot from 2023-03-17 21-07-55](https://user-images.githubusercontent.com/127831631/225952843-1d57fa73-b0f8-427e-aa96-b91e6df7d0fa.png)

**Comment by chrisduerr** [comment] 2023-03-17 17:59
>  But the repetition of the terminal prompt is there on both

That is working as intended (or expected I guess).

Is it actually Alacritty that is freezing on X11, so does it stop redrawing? Or is it your shell?

**Comment by cratolabs** [comment] 2023-03-18 12:45
Alacritty freezing for me on X11 , i teried with changing shells. alacritty --print-events , alacrity -vvv also stops printing after it freezes and no error is printed , everything normal.<br>
How to generate more logs , if possible?

**Comment by kchibisov** [comment] 2023-03-18 15:23
You could try to run under debugger and show back traces per thread when the freeze happens.

**Comment by cratolabs** [comment] 2023-03-18 19:01
i enabled debug options as follows :<br>
debug:
  render_timer: true
  persistent_logging: true
  log_level: Trace
  print_events: true
  ref_test: true

journalctl-log:
[Alacritty-journalctl.log](https://github.com/alacritty/alacritty/files/11009333/Alacritty-journalctl.log)
alacritty-log:
[Alacritty-16872.log](https://github.com/alacritty/alacritty/files/11009325/Alacritty-16872.log)

**Comment by kchibisov** [comment] 2023-03-18 19:09
But from the logs alacritty keeps running with `low` sizes? Could you normally close it with the window manager hotkey? I don't really see any freeze and to get a backtrace in the moment of freeze you should use `gdb`.

**Comment by cratolabs** [comment] 2023-03-22 14:35
I don't know how to use gdb. I need to dig deeper for that I think..<br>
I cannot close alacrity with any key when it freezes, using ubuntu's force stop popup (saying alacrity is not responding)to exit.<br>
Ya it occurs at low sizes.<br>
It won't freeze until you resize below  terminal prompt `username@My-Ubuntu:~`.<br>
After that `username@My-Ubuntu:~` start repeating and then it freezes.

**Comment by chrisduerr** [comment] 2023-03-24 19:37
> saying alacrity is not responding

This is specifically saying Alacritty? I'd assume with `ps` it is also saying that Alacritty is hung?

**Comment by cratolabs** [comment] 2023-03-28 12:34
ya . 
![Screenshot from 2023-03-28 18-03-57](https://user-images.githubusercontent.com/127831631/228237476-6ef0a74a-e04a-4694-9528-d510eb9ce982.png)

**Comment by chrisduerr** [comment] 2023-03-29 13:44
Yeah a `gdb` backtrace is probably the only helpful thing in that case.

**Comment by kchibisov** [comment] 2023-07-01 11:45
I think that was due to glutin bug, which we fixed and include in latest `rc` release or master branch.

Open a new issue if you still can repro that with the recent most commit.

**Closed by kchibisov** 2023-07-01 11:45 UTC
Labels: B - bug, A - needs repro
