### ISSUE TITLE
Resize causes stuttering

### ISSUE THREAD

**Issue by luizfelipefb** [alacritty/alacritty#4927] opened 2021-03-29 20:39 UTC
When resizing to fullscreen, or even other sizes, there's a stutter to perform the action.

In the video, I'm double clicking the tittle bar.

https://user-images.githubusercontent.com/3042811/112897111-96e4f600-90b5-11eb-8a41-3b6bea4b456d.mov

### System

OS: macOS 11.2.3 (MacBook Pro (16-inch, 2019) - 2,6 GHz 6-Core Intel Core i7 - 16 GB 2667 MHz DDR4)
Version: alacritty 0.7.2 (5ac8060)

### Logs

N/A

**Comment by chrisduerr** [comment] 2021-03-29 20:49
Duplicate of https://github.com/alacritty/alacritty/issues/3645.

**Closed by chrisduerr** 2021-03-29 20:49 UTC
