### ISSUE TITLE
Alacritty frequently doesn't launch on macOS after upgrading to 0.14.0

### ISSUE THREAD

**Issue by mikemykhaylov** [alacritty/alacritty#8265] opened 2024-10-24 05:25 UTC
After updating to 0.14.0, the application fails to open about every 10th-15th launch. Upon launching the app, window doesn't show up, app quietly sits in the Dock. Right clicking pops up "Application not responding menu", force quitting fixes the issue. Wasn't able to reproduce consistently, but open to suggestions

### System

OS: macOS 15.0.1 (24A348)
Version: alacritty 0.14.0 (22a4475)

### Logs

Crashes: no stdout/stderr as the app doesn't launch

**Comment by chrisduerr** [comment] 2024-10-24 14:22
Does downgrading fix the issue?

**Comment by mikemykhaylov** [comment] 2024-10-24 17:05
Downgraded, no issues so far, will give an update by eod

**Comment by amalchuk** [comment] 2024-10-24 20:49
I have the same issue after upgrading macOS to 15 (Sequoia), Alacritty version 0.14.0 and 0.13.2.

**Comment by chrisduerr** [comment] 2024-10-24 21:58
> I have the same issue after upgrading macOS to 15 (Sequoia), Alacritty version 0.14.0 and 0.13.2.

Loads of bugs being reported with Sequoia, should be easily fixed by not using macos.

**Closed by chrisduerr** 2024-10-24 21:58 UTC
Labels: C - waiting on author

**Comment by nixpulvis** [comment] 2024-10-24 22:01
Fucking hell chris

**Comment by nixpulvis** [comment] 2024-10-24 22:02
Why close this. It seems like an issue.

**Comment by chrisduerr** [comment] 2024-10-24 22:11
> Why close this. It seems like an issue.

Yeah, a macos issue. Which is very much not an Alacritty issue.

**Comment by kchibisov** [comment] 2024-10-24 22:14
@nixpulvis point is that 0.13.2 is also affected for some users, which suggests it's not a regression likely.

One can enable persistent logging in the config and try to catch what fails exactly, I guess.

**Comment by nixpulvis** [comment] 2024-10-24 22:15
Thank you.

**Comment by mikemykhaylov** [comment] 2024-10-25 07:40
Confirmed, don't have this issue on 0.13.2

**Comment by amalchuk** [comment] 2024-10-25 08:02
> > I have the same issue after upgrading macOS to 15 (Sequoia), Alacritty version 0.14.0 and 0.13.2.
> 
> Loads of bugs being reported with Sequoia, should be easily fixed by not using macos.

It is not macOS specific issue, because [kitty](https://github.com/kovidgoyal/kitty) terminal works fine on all OS versions.

If you just hate macOS and troll macOS users, just remove any support features for this platform, lol. Contributors and other good people can help to solve this issue, but you just close without any reason.

**Comment by OJFord** [comment] 2024-10-25 11:38
@chrisduerr I very much prefer using Linux too, but I'm stuck on macOS for work and want the same terminal emulator everywhere; so if macOS is not a supported platform this will have to (unfortunately) be 'easily fixed by not using' _Alacritty_, for me.

Can you please clarify if macOS is a supported platform or not? The readme currently says that it is.

**Comment by kchibisov** [comment] 2024-10-25 11:45
The problem is macOS 15.0 specifically and not macOS in general here. The amount of issues that was reported after update to 15.0 is a lot. For some users if you can see here the issue was as well for 0.13.2, which is why the issue got closed in the first place.

I've also provided instructions to do to make this issue reopen, but I'm pretty sure that it's just some assert inside the appkit that is now being triggered.

None of alacritty maintainers have access to macOS 15(I'm stuck at 12, because apple decided that my machine can not go higher), so unless some user figures out on how to provide an _actionable report_  (which is not provided) the status of _random macOS 15 bug_ won't really change.

**Comment by OJFord** [comment] 2024-10-25 18:43
I don't think `persistent_logging = true` helps, because macOS refuses to start it at all.

With the 'App Store and known developers' option selected in System Settings > Privacy & Security, I could see Alacritty pop up there as refused when I tried to open it with macOS's warning, but clicking 'open anyway' just switched to the already open instance - which I dared not close to test. (Indeed, seems like a macOS bug at the very least that this 'forgets' the `--new` option to `open`.)

I've worked around it for now with:
```
#spctl --global-disable
```

(NB I actually used `--master-disable`, but now I notice that's undocumented in the man page at least, and the above is described with the intended effect.)

which adds an additional option to the aforementioned settings menu: allow apps from 'Anywhere'. Up to you of course what's the right trade-off here; I see there's also self-signing instructions in the wiki.

**Comment by kchibisov** [comment] 2024-10-25 19:25
There could be also logs in the `Console.app` when it fails telling _some_ reason.

but if it's again the signing issue then ...

**Comment by MrsLong** [comment] 2024-11-18 02:12
> There could be also logs in the `Console.app` when it fails telling _some_ reason.
> 
> but if it's again the signing issue then ...

I recorded the console as Alacritty failed to launch from dock. This is my first time exporting logs from the macOS console, so please let me know if these were helpful. https://cephalopaste.bouncyoctopus.com/files/alacritty-log.txt

I am running Alacritty 0.14.0 (22a4475) on macOS Version 15.1 (24B2082).
