### ISSUE TITLE
How do I add key bindings using the "AltGr" key mod?

### ISSUE THREAD

**Issue by Hubro** [alacritty/alacritty#5637] opened 2021-11-26 13:15 UTC
I want to map the "Last" action in Vi mode to jump to the last character of a line. On my keyboard, that's `AltGr+4`. However, I can't find a way to use the AltGr key as a modifier. The documentation says:

```
# - `mods`: Key modifiers to filter binding actions
#
#    - Command
#    - Control
#    - Option
#    - Super
#    - Shift
#    - Alt
```

AltGr is not mentioned. I have tried using `Alt`, `Control`, `Control|Alt`, `Option` and `Command`, but none of these appear to correspond to the AltGr key.

Is there any way to make key bindings using the AltGr key in Alacritty?

**Comment by chrisduerr** [comment] 2021-11-26 14:49
Alt and AltGr are the same key. Both should respond to the alt modifier. I don't see much reason to treat the AltGr key any differently, at that point one would have to also implement LShift/RShift, L/RControl and that really just seems like a waste of time. Why do you need AltGr specifically?

**Comment by Hubro** [comment] 2021-11-26 14:53
> Alt and AltGr are the same key. Both should respond to the alt modifier. I don't see much reason to treat the AltGr key any differently, at that point one would have to also implement LShift/RShift, L/RControl and that really just seems like a waste of time. Why do you need AltGr specifically?

I have set up this key binding now:

```
  - { key: Key4, mods: Alt, mode: Vi, action: Last }
```

Now Alt+4 works, but AltGr+4 does not :thinking: 

I need this because `AltGr+4` is how you type `$` on a Norwegian keyboard, which is the default key bind for jumping to the end of the line in Vim. Jumping to the end of the line by typing `Alt+4` instead feels deeply unnatural.

**Comment by chrisduerr** [comment] 2021-11-26 14:59
> I need this because AltGr+4 is how you type $ on a Norwegian keyboard, which is the default key bind for jumping to the end of the line in Vim. Jumping to the end of the line by typing Alt+4 instead feels deeply unnatural.

Ah, so the issue is not with wanting an AltGr binding. Currently Alacritty has issues when it comes to binding to these modified keys, patches for that are in the works upstream but at the moment your best chance is to map by scancode. Ideally in the future users would have options to set bindings by generated character.

I have to use the following to get my `$` to work in vi mode for example:
```
  - { key: 5,      mods: Shift,         mode: Vi|~Search, action: Last           }
```

Note the `5` here is not the key `5`, but the scancode 5. You'll likely have to do the same at which point both your alt keys would likely be usable for moving to the end. The scancodes are visible when running Alacritty through alacritty --print-events | grep "WindowEvent.*KeyboardInput"`, generally that is very useful for creating keybindings.

**Closed by chrisduerr** 2021-11-26 14:59 UTC

**Comment by Hubro** [comment] 2021-11-26 16:28
That all made a lot of sense, and it gave me hope, but unfortunately this still doesn't make AltGr+4 work :sweat_smile: 

```
  - { key: 5, mods: Alt, mode: Vi, action: Last }
```

However, Alt+4 still works.

These are the entries produced when I press AltGr+4:

```
// AltGr down
[2021-11-26 17:24:55.448863704] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 100, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }

// 4 down
[2021-11-26 17:24:55.838843631] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 5, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }

// 4 up
[2021-11-26 17:24:56.004813228] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 5, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }

// AltGr up
[2021-11-26 17:24:56.228837877] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 100, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
```

These are the log entries produced when pressing Alt+4:

```
// Alt down
[2021-11-26 17:26:41.474605708] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }

// 4 down
[2021-11-26 17:26:41.730583881] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 5, state: Pressed, virtual_keycode: Some(Key4), modifiers: ALT }, is_synthetic: false } }

// 4 up
[2021-11-26 17:26:41.842562647] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 5, state: Released, virtual_keycode: Some(Key4), modifiers: ALT }, is_synthetic: false } }

// Alt up
[2021-11-26 17:26:42.035579274] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94326363872448))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
```

Seems that `modifiers: ALT` is logged when pressing 4 with the Alt key, but not with the AltGr key... So as far as Alacritty is concerned, I'm just pressing 4? :thinking: 

Anything else I can try in order to get AltGr+4 to work?

**Comment by chrisduerr** [comment] 2021-11-26 21:42
> Seems that modifiers: ALT is logged when pressing 4 with the Alt key, but not with the AltGr key... So as far as Alacritty is concerned, I'm just pressing 4? thinking

Yeah, so just using scancode 5 without any modifiers should work, right?

**Comment by Hubro** [comment] 2021-11-26 21:45
> > Seems that modifiers: ALT is logged when pressing 4 with the Alt key, but not with the AltGr key... So as far as Alacritty is concerned, I'm just pressing 4? thinking
> 
> Yeah, so just using scancode 5 without any modifiers should work, right?

Depends what you mean by "work". If I just bind to scancode 5, then pressing plain "4" will trigger the action, with or without AltGR. Isn't that equivalent to using `key: Key4`?

**Comment by chrisduerr** [comment] 2021-11-27 02:55
> Depends what you mean by "work". If I just bind to scancode 5, then pressing plain "4" will trigger the action, with or without AltGR. Isn't that equivalent to using key: Key4?

Kinda, yeah. But that's what Alacritty seems to receive. So you're SoL until the upstream rework is done.
