### ISSUE TITLE
Mouse movement causes cpu usage in alacritty when in background

### ISSUE THREAD

**Issue by MikeOnTea** [alacritty/alacritty#5977] opened 2022-03-27 10:39 UTC
It seems alacritty receives mouse events and reacts to them even when another app like Explorer or Notepad is focussed. Does _not_ happen if windows task manager is in focus, that might prevent other apps receiving events, not sure. CPU usage is around 0.5 % - 2 % per alacritty process (when doing a lot of fast movements):
![alacrittyCpuUsageMouseMovement](https://user-images.githubusercontent.com/11480934/160277409-a4dd8008-f342-4a4b-84ae-6fd00809ae9f.png)
This doesn't sound like a big problem, however, it is: Starting from around 4 open alacritty terminals, i notice stuttering while moving the mouse during gaming (tested with war thunder), with 6 open alacritty windows, my in game fps drops below 10 (from ~100) during quick mouse movements and thus makes the game basically unplayable. This is how i noticed the problem in the first place, took me some time to figure out alacritty was causing it.

### System
OS: Windows 10 21H1
Version: 0.10.1, happened in 0.10.0 and 0.9 as well
Graphics card: nvidia geforce gtx 1060 (driver 511.79)

**Comment by chrisduerr** [comment] 2022-03-27 15:03
Duplicate of https://github.com/alacritty/alacritty/issues/4484.

**Closed by chrisduerr** 2022-03-27 15:03 UTC
