### ISSUE TITLE
Ctrl+Shift+C has stopped working with non-latin layouts

### ISSUE THREAD

**Issue by skiiddie** [alacritty/alacritty#7751] opened 2024-02-19 19:16 UTC
Starting from version 0.13.0 the terminal treats the keyboard shortcut `Ctrl+Shift+C` as `^C` (SIGINT).
Was tested on multiple layouts: English, Russian, Armenian, Uzbek, Kazakh, French, Czech.
It works as it should only on latin layouts (of the above, these are English, French, Czech).

### System
OS: Linux, X11, KDE
Version: alacritty 0.13.1 (fe2a3c56)

### Logs
English:
```
[2.273420999s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ControlLeft), logical_key: Named(Control), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.354442960s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ShiftLeft), logical_key: Named(Shift), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Shift), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.429179044s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyC), logical_key: Character("C"), text: Some("C"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("c"), text_with_all_modifiers: Some("\u{3}") } }, is_synthetic: false } }
[2.519998110s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ShiftLeft), logical_key: Named(Shift), text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Shift), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.529145171s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ControlLeft), logical_key: Named(Control), text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.538499774s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyC), logical_key: Character("c"), text: Some("c"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("c"), text_with_all_modifiers: Some("c") } }, is_synthetic: false } }
```
Armenian:
```
[2.108399503s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ControlLeft), logical_key: Named(Control), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.171896270s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ShiftLeft), logical_key: Named(Shift), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Shift), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.246609328s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyC), logical_key: Character("Չ"), text: Some("Չ"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("չ"), text_with_all_modifiers: Some("\u{3}") } }, is_synthetic: false } }
[2.358749439s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ShiftLeft), logical_key: Named(Shift), text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Shift), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.368216536s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(ControlLeft), logical_key: Named(Control), text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, is_synthetic: false } }
[2.377297749s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(71303171)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyC), logical_key: Character("չ"), text: Some("չ"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("չ"), text_with_all_modifiers: Some("չ") } }, is_synthetic: false } }
```

**Comment by kchibisov** [comment] 2024-02-19 21:08
duplicate of #7688

**Closed by kchibisov** 2024-02-19 21:08 UTC
