### ISSUE TITLE
Alacritty transparency not working, instead the background is black

### ISSUE THREAD

**Issue by mueller** [alacritty/alacritty#5859] opened 2022-02-05 10:39 UTC
When trying to make `alacritty` transparent via `window.opacity` (see config below), the terminal background gets black instead of transparent.  

### System

OS: Kali Linux inside VirtualBox (`Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux`)
Version: `alacritty 0.10.0 ()`
Linux/BSD: i3 / picom / X11 

`picom` is started automatically inside the i3 config file with `exec --no-startup-id picom -b`. And is actually running:

```
~ $ ps aux | grep picom
kali        1058  0.0  0.9 751792 39376 ?        Ssl  10:48   0:00 picom -b
```

### Logs

Starting `alacritty`:

```
~ $ alacritty -vvv
Created log file at "/tmp/Alacritty-1397.log"
[0.000215928s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/kali/.config/alacritty/alacritty.yml"
[0.012877320s] [TRACE] [crossfont] Number of fonts is 31
[0.012915199s] [TRACE] [crossfont] Got font path="/usr/share/fonts/nerd-fonts/Iosevka Nerd Font Complete.ttf", index=0
[0.013255700s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.013614900s] [DEBUG] [alacritty] Estimated DPR: 1
[0.013624104s] [DEBUG] [alacritty] Estimated window size: None
[0.013627676s] [DEBUG] [alacritty] Estimated cell size: 8 x 21
libEGL warning: DRI2: failed to authenticate
[0.062906421s] [WARN ] [glutin] Glutin could not a find fb config with an alpha mask. Transparency may be broken.
[0.070278404s] [INFO ] [alacritty] Device pixel ratio: 1
[0.077760672s] [INFO ] [alacritty] Initializing glyph cache...
[0.079288777s] [TRACE] [crossfont] Number of fonts is 31
[0.079348227s] [TRACE] [crossfont] Got font path="/usr/share/fonts/nerd-fonts/Iosevka Nerd Font Complete.ttf", index=0
[0.079428607s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.080664586s] [TRACE] [crossfont] Number of fonts is 31
[0.080706437s] [TRACE] [crossfont] Got font path="/usr/share/fonts/nerd-fonts/Iosevka Bold Nerd Font Complete.ttf", index=0
[0.080758423s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.081925298s] [TRACE] [crossfont] Number of fonts is 32
[0.081958684s] [TRACE] [crossfont] Got font path="/usr/share/fonts/nerd-fonts/Iosevka Italic Nerd Font Complete.ttf", index=0
[0.082009560s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.083140376s] [TRACE] [crossfont] Number of fonts is 33
[0.083168130s] [TRACE] [crossfont] Got font path="/usr/share/fonts/nerd-fonts/Iosevka Bold Italic Nerd Font Complete.ttf", index=0
[0.083218746s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.089400323s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.011532567s
[0.089495971s] [INFO ] [alacritty] Cell size: 8 x 21
[0.089521193s] [INFO ] [alacritty] Padding: 12 x 12
[0.089539022s] [INFO ] [alacritty] Width: 800, Height: 600
[0.099350347s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 197, g: 200, b: 198 } to Rgb { r: 130, g: 132, b: 130 }
[0.099587005s] [TRACE] [alacritty] Deriving dim colors from normal colors
[0.099609786s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 29, g: 31, b: 33 } to Rgb { r: 19, g: 20, b: 21 }
[0.099625734s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 204, g: 102, b: 102 } to Rgb { r: 134, g: 67, b: 67 }
[0.099639191s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 181, g: 189, b: 104 } to Rgb { r: 119, g: 124, b: 68 }
[0.099674299s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 240, g: 198, b: 116 } to Rgb { r: 158, g: 130, b: 76 }
[0.099702863s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 129, g: 162, b: 190 } to Rgb { r: 85, g: 106, b: 125 }
[0.099778821s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 178, g: 148, b: 187 } to Rgb { r: 117, g: 97, b: 123 }
[0.099862513s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 138, g: 190, b: 183 } to Rgb { r: 91, g: 125, b: 120 }
[0.099879301s] [TRACE] [alacritty_terminal] Scaling RGB by 0.66 from Rgb { r: 197, g: 200, b: 198 } to Rgb { r: 130, g: 132, b: 130 }
[0.099898701s] [INFO ] [alacritty] PTY dimensions: 27 x 97
[0.101870729s] [INFO ] [alacritty] Initialisation complete
[0.104933644s] [DEBUG] [alacritty_terminal] New num_cols is 154 and num_lines is 63
[0.105935726s] [INFO ] [alacritty] Padding: 12 x 12
[0.105962369s] [INFO ] [alacritty] Width: 1263, Height: 1394
[0.140523151s] [TRACE] [alacritty_terminal] Carriage return
[0.140580520s] [TRACE] [alacritty_terminal] Carriage return
[0.154674189s] [TRACE] [alacritty_terminal] Carriage return
[0.154726165s] [TRACE] [alacritty_terminal] Setting attribute: Reset
[0.154744595s] [TRACE] [alacritty_terminal] Setting attribute: CancelReverse
[0.154758351s] [TRACE] [alacritty_terminal] Setting attribute: CancelUnderline
[0.154770618s] [TRACE] [alacritty_terminal] Clearing screen: Below
[0.154786455s] [TRACE] [alacritty_terminal] Setting attribute: Foreground(Named(Blue))
[0.154800032s] [TRACE] [alacritty_terminal] Setting attribute: Bold
[0.154816050s] [TRACE] [alacritty_terminal] Setting attribute: Foreground(Named(Blue))
[0.154828647s] [TRACE] [alacritty_terminal] Setting attribute: Foreground(Named(Foreground))
[0.154845305s] [TRACE] [alacritty_terminal] Setting attribute: Reset
[0.157721716s] [TRACE] [alacritty_terminal] Setting color[0] = Rgb { r: 24, g: 28, b: 33 }
[0.157758004s] [TRACE] [alacritty_terminal] Setting color[1] = Rgb { r: 37, g: 125, b: 255 }
[0.157772842s] [TRACE] [alacritty_terminal] Setting color[2] = Rgb { r: 69, g: 107, b: 255 }
[0.157785938s] [TRACE] [alacritty_terminal] Setting color[3] = Rgb { r: 255, g: 133, b: 254 }
[0.157802597s] [TRACE] [alacritty_terminal] Setting color[4] = Rgb { r: 255, g: 37, b: 144 }
[0.157815803s] [TRACE] [alacritty_terminal] Setting color[5] = Rgb { r: 229, g: 0, b: 80 }
[0.157828209s] [TRACE] [alacritty_terminal] Setting color[6] = Rgb { r: 242, g: 0, b: 70 }
[0.157840536s] [TRACE] [alacritty_terminal] Setting color[7] = Rgb { r: 197, g: 198, b: 199 }
[0.158743648s] [TRACE] [alacritty_terminal] Setting color[8] = Rgb { r: 81, g: 84, b: 88 }
[0.158753553s] [TRACE] [alacritty_terminal] Setting color[9] = Rgb { r: 37, g: 125, b: 255 }
[0.158758976s] [TRACE] [alacritty_terminal] Setting color[10] = Rgb { r: 69, g: 107, b: 255 }
[0.158763908s] [TRACE] [alacritty_terminal] Setting color[11] = Rgb { r: 255, g: 133, b: 254 }
[0.158768811s] [TRACE] [alacritty_terminal] Setting color[12] = Rgb { r: 255, g: 37, b: 144 }
[0.158777735s] [TRACE] [alacritty_terminal] Setting color[13] = Rgb { r: 229, g: 0, b: 80 }
[0.158782968s] [TRACE] [alacritty_terminal] Setting color[14] = Rgb { r: 242, g: 0, b: 70 }
[0.158787790s] [TRACE] [alacritty_terminal] Setting color[15] = Rgb { r: 197, g: 198, b: 199 }
[0.158792743s] [TRACE] [alacritty_terminal] Setting color[256] = Rgb { r: 197, g: 198, b: 199 }
[0.158797725s] [TRACE] [alacritty_terminal] Setting color[257] = Rgb { r: 24, g: 28, b: 33 }
[0.158802488s] [TRACE] [alacritty_terminal] Setting color[258] = Rgb { r: 197, g: 198, b: 199 }
[0.158809481s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','3',],['#','c','5','c','6','c','7',],] at line 949
[0.158816114s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','7',],['#','c','5','c','6','c','7',],] at line 949
[0.158821607s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','9',],['#','1','8','1','c','2','1',],] at line 949
[0.158826740s] [TRACE] [alacritty_terminal] Setting color[232] = Rgb { r: 24, g: 28, b: 33 }
[0.158835654s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['4',],['2','5','6',],['#','c','5','c','6','c','7',],] at line 949
[0.158841687s] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['7','0','8',],['#','1','8','1','c','2','1',],] at line 949
[0.162275168s] [TRACE] [alacritty_terminal] Clearing line: Right
[0.165635420s] [TRACE] [alacritty_terminal] Setting mode: CursorKeys
[0.165728297s] [TRACE] [alacritty_terminal] Setting keypad application mode
[0.168517223s] [TRACE] [alacritty_terminal] Setting mode: BracketedPaste
```

Starting `alacritty` this way displays the following warning which might explain the problem?

![image](https://user-images.githubusercontent.com/29411434/152636967-c08a64aa-c3b9-4623-8310-3c1fda6be5ba.png)

### Config files

`~/.config/picom.conf` is empty

`~/.config/alacritty/alacritty.yml`:

```
# Font configuration (changes require restart)
font:
  normal:
    family: Iosevka Nerd Font
    style: Regular

  bold:
    family: Iosevka Nerd Font

  italic:
    family: Iosevka Nerd Font

  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false
  
cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Beam

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  opacity: 0.5

  dimensions:
    columns: 0
    lines: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 12
    y: 12
    
scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number of lines the terminal
  # should scroll when the alternate screen buffer is active. This is used
  # to allow mouse scrolling for applications like `man`.
  #
  # Specifying `0` will disable faux scrolling.
  faux_multiplier: 3

  # Scroll to the bottom when new text is written to the terminal.
  auto_scroll: false

# Spaces per Tab (changes require restart)
#
# This setting defines the width of a tab in cells.
#
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
tabspaces: 4

key_bindings:
  #- { key: Paste,                                       action: Paste          }
  #- { key: Copy,                                        action: Copy           }
  #- { key: L,         mods: Control,                    action: ClearLogNotice }
  #- { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
  - { key: PageUp,       mode: ~Alt,        action: ScrollPageUp,  }
  - { key: PageDown,     mode: ~Alt,        action: ScrollPageDown }
  #- { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  #- { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }
```

At this point I am pretty much clueless and would appreciate any help ;)

**Comment by mcnuggetsx20** [comment] 2022-02-05 22:56
I had the same issue and I fixed it just a second ago with a full system upgrade and a reboot. Maybe that will help.

**Comment by amitbha** [comment] 2022-02-06 03:30
The same issue. I think that's because the format of config file is changed.
My solution: 
1. copy out /usr/share/doc/alacritty/alacritty.yml
2. sync the old config

**Comment by mueller** [comment] 2022-02-06 07:27
Thanks for your recommendations. 

After updating (`apt update` and `apt upgrade`) and rebooting the system, everything stays the same. 

Then I tried to use the latest config from the repo, and only commented out a few lines, i.e. `padding` and `opacity`:

```
# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty

window:
  # Window dimensions (changes require restart)
  #
  # Number of lines/columns (not pixels) in the terminal. The number of columns
  # must be at least `2`, while using a value of `0` for columns and lines will
  # fall back to the window manager's recommended size.
  #dimensions:
  #  columns: 0
  #  lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 20
    y: 20

  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background and no title bar buttons
  #decorations: full

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.5
```

Here, too, everything remains the same after a restart.

**Comment by amitbha** [comment] 2022-02-06 16:49
If the indent of these lines(two space ahead) is right, u can comment them one by one again to check the cause.
`--config-file` can be used to specify the config file for test.

**Comment by mueller** [comment] 2022-02-06 16:57
Sorry, I think my answer was misleading.

After upgrading and rebooting and changing the config, the problem that the `alacritty` background is black instead of transparent remains.
The config file is working as intend (besides the transparency problem). I tested it by changing the padding to see if that changes accordingly.

So the config file is loaded successfully, however the original problem remains. Upgrading and changing to the new config file didn't do the trick.

**Comment by chrisduerr** [comment] 2022-02-06 21:38
> Kali Linux inside VirtualBox

Duplicate of #4217.

**Closed by chrisduerr** 2022-02-06 21:38 UTC

**Comment by xbr01** [comment] 2024-02-10 17:31
making the correct indentation made it work for me

```
window:
    opacity : 0.8
```
 
 https://imgur.com/a/reDxrv6
