### ISSUE TITLE
"Control+]" ("^]") not working on Italian keyboard, macOs

### ISSUE THREAD

**Issue by LorenzoBettini** [alacritty/alacritty#8327] opened 2024-11-25 20:25 UTC
At least on macOs (did not test yet on Linux), Control+] does not work, e.g., for navigating in Neovim help (the sequence for navigating to a link). The problem is for the Italian layout because `]` is not available directly: to get `]` you have to press "Option" and `+`. If I also press "Control" (`^` on mac) the "Option" does not have any effect and `]` just "does not happen", I seem to understand. Note that if I switch to English layout, where `]` is available directly, without needing "Option", everything works correctly.

I tried to add this in the configuration file

```toml
[[keyboard.bindings]]
chars = "^]"
key = "]"
mods = "Control"
```

but it has no effect... maybe I'm missing something.

### System

OS: macOS
Version: `0.14.0`

**Comment by chrisduerr** [comment] 2024-11-26 00:43
What do you expect `^]` to do? If you want to create a custom binding, please share the `alacritty --print-events` output. That should show exactly which keys you need to map.

**Comment by chrisduerr** [comment] 2024-11-26 23:27
```
[20.135215158s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(BracketRight), logical_key: Character("]"), text: Some("]"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\u{1d}"), key_without_modifiers: Character("+") } }, is_synthetic: false }
```

This looks like everything is working as it should. Can you record a video of what Ctrl+V -> Ctrl+] looks like in bash?

**Comment by LorenzoBettini** [comment] 2024-11-27 11:26
Without recording a video, I can tell you that it shows `^]` (of course, the keys I pressed are "Ctrl V -> Ctrl Alt +" )... so it also looks valid... maybe something wrong happens in the context of Neovim... In Neovim, if I type `:` and then press `Ctrl Alt +` I get `+`

**Comment by kchibisov** [comment] 2024-11-27 11:38
Duplicate of #8308

**Closed by kchibisov** 2024-11-27 11:38 UTC
Labels: F - insufficent detail

**Comment by kchibisov** [comment] 2024-11-27 11:39
Your binding in config should still work regardless though. Though, you should send a unicode sequence corresponding to `^[` and not, `^[` chars like you wrote.

**Comment by LorenzoBettini** [comment] 2024-11-27 11:42
Note that the last information was with a config without explicit binding.

So you're suggesting adding an explicit binding?

Something like (untested at the moment)?

```toml
[[keyboard.bindings]]
chars = "\u{1d}"
key = "]"
mods = "Control"
```

**Comment by LorenzoBettini** [comment] 2024-11-29 16:08
some follow-up:

```toml
[[keyboard.bindings]]
chars = "\u001d"
key = "]"
mods = "Control"
```

fixes the problem in Linux, but NOT in macOs...
