### ISSUE TITLE
mouse shape remains `hand` after click the link

### ISSUE THREAD

**Issue by cattyhouse** [alacritty/alacritty#7596] opened 2024-01-09 15:49 UTC
### System

OS: macOS
Version: alacritty 0.13.1 (fe2a3c5)

### steps to reproduce

1. open a window
1. `echo http://example.com`
1. move mouse on top of the link, when mouse shape becomes a `hand` , click the link, browser opens the link
1. command + tab go back to alacritty, mouse shape **remains** `hand` if the mouse position is not on the link.

1. if you can't reproduce this behavior, repeat more than 3 times
1. same issue in tmux pane/window, use `shift+click` instead of click in step 3

### work around:

- in alacritty window: move the mouse on top of the link, and then move away, the `hand` shape is gone
- in tmux pane/window : press shift once, the `hand` shape is gone

**Comment by chrisduerr** [comment] 2024-01-09 23:41
Closing as duplicate of https://github.com/alacritty/alacritty/issues/6947.

**Closed by chrisduerr** 2024-01-09 23:41 UTC
