### ISSUE TITLE
[Bug] no text is showing up

### ISSUE THREAD

**Issue by creeper451** [alacritty/alacritty#6914] opened 2023-05-08 18:39 UTC
When launching the terminal emulator text doesn't show up

screenshot:
![Capture](https://user-images.githubusercontent.com/92668459/236904706-77acd200-8b7d-4d3b-9967-aba4ba00df48.PNG)

### System

OS: Windows 10 1809 LTSC 2019
Version: alacritty 0.12.0 (5a728195)

**Comment by kchibisov** [comment] 2023-05-08 18:48
Have you build the application yourself? Are you using nvidia driver or anything like that? Could you show the `alacritty -vv` log?

**Comment by creeper451** [comment] 2023-05-08 18:51
sure
![Capture4](https://user-images.githubusercontent.com/92668459/236907634-68d58faf-e409-49ad-8d10-7ab80d8902a9.PNG)

**Comment by creeper451** [comment] 2023-05-08 18:52
No I didn't build it myself I downloaded the binary from the releases page

**Comment by creeper451** [comment] 2023-05-08 18:54
here is the dxdiag It might be useful...
Its a really old laptop but I'm pretty sure it support opengl
![Capture2](https://user-images.githubusercontent.com/92668459/236908062-fe230f82-1a11-42bc-a263-87fb72103f98.PNG)

**Comment by kchibisov** [comment] 2023-05-08 19:35
In general it should work(and it'll work on Linux), but maybe we're facing some edge case on Windows when it comes to texture uploading. At least it seems like we're using the correct render now, but it's hard to say without adding extra log to the binary what is happening.

**Comment by tktunix** [comment] 2023-05-15 14:41
I also hit this bug on a Win10 laptop with v0.12.0, but my another win11 work machine is working fine. And I am sure v0.11.0 worked alright on that win10 laptop.

I just did a git bisect and found commit 0e418bc2 was to blame, but my rust skill is not good enough to know why.

**Comment by kchibisov** [comment] 2023-05-15 14:48
Could you post the `-vv` logs before and after that commit?

**Comment by kchibisov** [comment] 2023-05-16 00:03
>I just did a git bisect and found commit 0e418bc was to blame, but my rust skill is not good enough to know why.

Likely some issue with the context creation. That has nothing to do with `rust` though, it's a pure https://learn.microsoft.com/en-us/windows/win32/opengl/wgl-and-windows-reference type of issues.

I don't see what we could do different now and I have no clue how to debug such things on Windows.

You could building the latest master, maybe it got fixed somehow.

**Comment by kchibisov** [comment] 2023-05-16 01:04
@tktunix could you try running https://github.com/alacritty/alacritty/pull/6927 with `-vv` and post the log here?

**Comment by tktunix** [comment] 2023-05-16 03:18
Absolutely.

Will do it when I have access to the affected win10 laptop.

**Comment by kchibisov** [comment] 2023-05-16 15:29
That looks like a driver bug if it matters.

Could you try asking for higher version of the OpenGL context? Could you try changing this version https://github.com/alacritty/alacritty/blob/a6488a3e5edf1ac25c522e037c75b9d17e6bc3c6/alacritty/src/renderer/platform.rs#L86  to `(4, 5)`? Or tweaking other settings  here.

**Comment by tktunix** [comment] 2023-05-17 13:09
I tested several versions on current master HEAD 6e7f466:
(4, 5)
(4, 0)
(3, 0)
(2, 0)

Only (2, 0) fixed the issue.

**Comment by chrisduerr** [comment] 2023-05-17 13:50
Sounds like `alacritty -o debug.renderer=gles2` should work for you?

**Comment by chrisduerr** [comment] 2023-05-17 13:50
Closing as a driver bug.

**Closed by chrisduerr** 2023-05-17 13:50 UTC
Labels: S - render, H - windows

**Comment by tktunix** [comment] 2023-05-17 14:01
unfortunately "-o debug.renderer=gles2" didn't work.
It is even worse, alacritty won't even start.

PS C:\Users\dgdun\alacritty> .\target\debug\alacritty.exe -vv -o debug.renderer=gles2
PS C:\Users\dgdun\alacritty> Created log file at "C:\Users\dgdun\AppData\Local\Temp\Alacritty-13280.log"
[0.000040400s] [INFO ] [alacritty] Welcome to Alacritty
[0.001037300s] [INFO ] [alacritty] Version 0.13.0-dev (6e7f466c)
[0.006612800s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\dgdun\\AppData\\Roaming\\alacritty\\alacritty.yml"
[0.029574500s] [INFO ] [alacritty] Window scale factor: 1.25
[0.082447000s] [INFO ] [alacritty] Using WGL
[0.098689200s] [DEBUG] [alacritty] Loading "Consolas" font
[0.152785200s] [INFO ] [alacritty] Running on Intel(R) Iris(R) Graphics 540
[0.153285000s] [INFO ] [alacritty] Using OpenGL ES 2.0 renderer
[0.157445700s] [INFO ] [alacritty] Using dual source blending
Error: There was an error initializing the shaders: Failed compiling shader: ERROR: 1:4: '#extension' :  'GL_EXT_blend_func_extended' is not supported
ERROR: 1:45: 'gl_SecondaryFragColorEXT' : undeclared identifier
ERROR: 1:45: 'assign' :  cannot convert from 'const 4-component vector of float' to 'float'
ERROR: 1:59: 'gl_SecondaryFragColorEXT' : undeclared identifier
ERROR: 1:59: 'assign' :  cannot convert from '4-component vector of mediump float' to 'mediump float'
ERROR: 1:70: 'gl_SecondaryFragColorEXT' : undeclared identifier
ERROR: 1:70: 'assign' :  cannot convert from '4-component vector of mediump float' to 'mediump float'

**Comment by kchibisov** [comment] 2023-05-17 14:17
try `gles2_pure`.

**Comment by tktunix** [comment] 2023-05-18 07:09
tried "-o debug.renderer=gles2_pure" and the issue remains.

Since that gl-debuggability commit somehow makes the problem go away,
Is it possible to merge that into v0.12.1?

**Comment by kchibisov** [comment] 2023-05-18 09:44
@tktunix 

if you apply

```diff
diff --git a/alacritty/src/renderer/text/atlas.rs b/alacritty/src/renderer/text/atlas.rs
index 9d4cb401..db63c87b 100644
--- a/alacritty/src/renderer/text/atlas.rs
+++ b/alacritty/src/renderer/text/atlas.rs
@@ -160,7 +160,7 @@ impl Atlas {
                     multicolor = false;
                     // Gles context doesn't allow uploading RGB data into RGBA texture, so need
                     // explicit copy.
-                    if self.is_gles_context {
+                    if true {
                         let mut new_buffer = Vec::with_capacity(buffer.len() / 3 * 4);
                         for rgb in buffer.chunks_exact(3) {
                             new_buffer.push(rgb[0]);

```


On the current master is it fixing the issue.

**Comment by tktunix** [comment] 2023-05-18 12:12
Current master HEAD with above change the issue remains.

PS C:\Users\xxx\alacritty> .\target\debug\alacritty.exe -vv
PS C:\Users\xxx\alacritty> Created log file at "C:\Users\xxx\AppData\Local\Temp\Alacritty-12992.log"
[0.000065500s] [INFO ] [alacritty] Welcome to Alacritty
[0.001269000s] [INFO ] [alacritty] Version 0.13.0-dev (6e7f466c)
[0.007280900s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\xxx\\AppData\\Roaming\\alacritty\\alacritty.yml"
[0.029441100s] [INFO ] [alacritty] Window scale factor: 1.25
[0.111819300s] [INFO ] [alacritty] Using WGL
[0.127002600s] [DEBUG] [alacritty] Loading "Consolas" font
[0.180709000s] [INFO ] [alacritty] Running on Intel(R) Iris(R) Graphics 540
[0.181140300s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.258801000s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.312053200s] [INFO ] [alacritty] Cell size: 10 x 21
[0.312402700s] [INFO ] [alacritty] Padding: 0 x 0
[0.312693900s] [INFO ] [alacritty] Width: 1600, Height: 1008
[0.335573200s] [INFO ] [alacritty] PTY dimensions: 48 x 160
[0.360120900s] [INFO ] [alacritty] Initialisation complete
[0.369063100s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged

**Comment by kchibisov** [comment] 2023-05-18 13:22
I mean, you clearly have a broken driver. Is your driver having some settings to tweak AA(MSAA or some other craft) or anything like that? Maybe disable various things per application. I know that nvidia had such issues.

So the only thing for you that works is if you create `OpenGL 2.0` context?

**Comment by nyawox** [comment] 2023-10-01 00:36
Just for record
Having same issue on alacritty from latest nixpkgs on NixOS RockPro64 aarch64,
gles2_pure fixes

**Comment by kchibisov** [comment] 2023-10-01 00:39
@nyawox your issue is known mesa bug.

**Comment by nyawox** [comment] 2023-10-03 02:15
> @nyawox your issue is known mesa bug.

That helped me get into #128 to see the root cause
thanks a lot

**Comment by kchibisov** [comment] 2023-10-03 02:17
@nyawox #128 has nothing to do with that, see https://gitlab.freedesktop.org/mesa/mesa/-/issues/9487 . Just a bug in driver.

**Comment by nyawox** [comment] 2023-10-03 02:27
Oh sorry for the trouble I thought it was that panfrost still didn't support something because the gl3 debug flag fixes it

**Comment by kchibisov** [comment] 2023-10-03 02:34
no, `gles2_pure` is a renderer meant to be run on basically any hardware that can OpenGL, so it works with GPUs from 2004. It just panfrost sometimes is bugged, in this case it tells us the extension to make text rendering faster, but in reality it's broken.

Basically `gles2_pure` is the pure(on extra extensions, etc) renderer, `gles2` is what is being advertised along the gles2, and glsl3 is the original opengl renderer. The perf increases the newer version of renderer is.
