### ISSUE TITLE
double movement for arrow keys

### ISSUE THREAD

**Issue by fefe17** [alacritty/alacritty#3774] opened 2020-05-27 08:05 UTC
OS: Linux
Version: alacritty 0.5.0-dev (88d87cf)
Linux/BSD: X11

Issue: When I press any of the arrow keys, I get a movement of two (not one as expected) in the curses app.  An strace on a vim in an alacritty shows:

```
read(0, "\33OB\33OB", 4096)             = 6
```

So alacritty really sends the keycode twice.

Here's the key section regarding the Down arrow key from my alacritty.yml:

```
579   - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                       }
580   - { key: Down,     mods: Control, chars: "\x1b[1;5B"                       }
581   - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                       }
582   - { key: Down,                    chars: "\x1b[B",        mode: ~AppCursor }
583   - { key: Down,                    chars: "\x1bOB",        mode: AppCursor  }
```

I have been having this issue for a few weeks now.

What is going on here?

**Comment by kchibisov** [comment] 2020-05-27 08:10
duplicate of https://github.com/alacritty/alacritty/issues/3476

**Closed by kchibisov** 2020-05-27 08:10 UTC
