### ISSUE TITLE
Ncurses characters blurry/aliased

### ISSUE THREAD

**Issue by dustboxednorth** [alacritty/alacritty#3940] opened 2020-07-10 12:47 UTC
This morning, I installed Alacritty, as it seems to run quite nicely on my system. However, one nitpick: I use a font called November, as it reminds me of older text-based systems. As such, I like the ncurses characters to be crisp as well, as this is how it was in Terminator (upper-most image). These anti-aliased ncurses characters are ugly and I'd like to know what to do to make them aliased and pixel-perfect again :-)

![image](https://user-images.githubusercontent.com/56094177/87155909-663c0280-c281-11ea-9894-e70103d14d07.png)

![image](https://user-images.githubusercontent.com/56094177/87155618-ddbd6200-c280-11ea-9f87-8924a9ae33c0.png)

### System

OS: Debian 10 "Buster"
Alacritty Version: 0.4.3
Linux/BSD: X11, i3

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: November, 8 pt. (8 pt. makes the font crisp and aliased, as November looks like crap under other sizes)

Thanks in advance,
DBN

**Comment by kchibisov** [comment] 2020-07-10 14:16
Duplicate of https://github.com/alacritty/alacritty/issues/118

**Closed by kchibisov** 2020-07-10 14:16 UTC
