### ISSUE TITLE
Vi mode: "Last" action seems to have no effect

### ISSUE THREAD

**Issue by pappasam** [alacritty/alacritty#3490] opened 2020-03-19 16:55 UTC
### System

OS: Linux (ubuntu 18.04)
Version: alacritty 0.5.0-dev (3d7a789)
Linux/BSD: X11

### Issue

The "Last" action in Vi mode doesn't seem to do anything in my terminal. I press "$' in Vi mode an the cursor doesn't seem to go anywhere.

### Logs

There's lots of noise, but my press of Key4 takes place just about at the start of the logs.

```
[2020-03-19 12:52:21.697618626] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11157, tv_nsec: 291214229 }, requested_resume: None })
[2020-03-19 12:52:21.697885436] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(KeyboardInput { scancode: 5, state: Pressed, virtual_keycode: Some(Key4), modifiers: SHIFT }) }
[2020-03-19 12:52:21.697982948] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:21.698022329] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:21.698079328] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11162, tv_nsec: 243003296 }, requested_resume: None })
[2020-03-19 12:52:21.698140985] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 5, state: Pressed, virtual_keycode: None, modifiers: SHIFT }, is_synthetic: false } }
[2020-03-19 12:52:21.698199671] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: ReceivedCharacter('$') }
[2020-03-19 12:52:21.698278476] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:21.698306093] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:21.769528956] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11162, tv_nsec: 243287753 }, requested_resume: None })
[2020-03-19 12:52:21.769796107] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(KeyboardInput { scancode: 5, state: Released, virtual_keycode: Some(Key4), modifiers: SHIFT }) }
[2020-03-19 12:52:21.769889186] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 5, state: Released, virtual_keycode: None, modifiers: SHIFT }, is_synthetic: false } }
[2020-03-19 12:52:21.769959458] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:21.769995173] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:22.249446069] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11162, tv_nsec: 314973936 }, requested_resume: None })
[2020-03-19 12:52:22.249719998] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(KeyboardInput { scancode: 54, state: Released, virtual_keycode: Some(RShift), modifiers: SHIFT }) }
[2020-03-19 12:52:22.249855942] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: ModifiersChanged((empty)) }
[2020-03-19 12:52:22.250037750] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 54, state: Released, virtual_keycode: Some(RShift), modifiers: (empty) }, is_synthetic: false } }
[2020-03-19 12:52:22.250170020] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:22.250235949] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:46.713252216] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11162, tv_nsec: 795278971 }, requested_resume: None })
[2020-03-19 12:52:46.713491220] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: (empty) }) }
[2020-03-19 12:52:46.713564540] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: ModifiersChanged(CTRL) }
[2020-03-19 12:52:46.713624030] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:46.713661461] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:46.713720813] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11187, tv_nsec: 258643792 }, requested_resume: None })
[2020-03-19 12:52:46.713796398] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: CTRL }, is_synthetic: false } }
[2020-03-19 12:52:46.714058932] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:46.714141083] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:46.729032574] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11187, tv_nsec: 259241616 }, requested_resume: None })
[2020-03-19 12:52:46.729255717] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(15))), event: Key(KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: CTRL }) }
[2020-03-19 12:52:46.729284118] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: ModifiersChanged(CTRL | ALT) }
[2020-03-19 12:52:46.729312308] [INFO] glutin event: MainEventsCleared
[2020-03-19 12:52:46.729330346] [INFO] glutin event: RedrawEventsCleared
[2020-03-19 12:52:46.729354173] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 11187, tv_nsec: 274291445 }, requested_resume: None })
[2020-03-19 12:52:46.729396077] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(130023426))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LAlt), modifiers: CTRL | ALT }, is_synthetic: false } }
```

**Comment by kchibisov** [comment] 2020-03-19 17:02
You should bind by scancode for now on X11, due to this bug https://github.com/rust-windowing/winit/issues/1443

**Comment by chrisduerr** [comment] 2020-03-19 20:16
Duplicate of #3460.

**Closed by chrisduerr** 2020-03-19 20:16 UTC
Labels: A - deps, B - bug, DS - Wayland, DS - X11, S - keybindings, S - winit/glutin

**Comment by pappasam** [comment] 2020-03-19 20:40
The fix for me, thanks for the above advice:

```- { key: 05, mods: Shift, mode: Vi, action: Last }```

See: https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html

**Comment by nixpulvis** [comment] 2020-03-21 14:32
@pappasam thanks for looking this up :tada:. For the time being I've fixed all the defaults in my configuration with:

```yaml
- { key: 05, mods: Shift, mode: Vi, action: Last }
- { key: 06, mods: Shift, mode: Vi, action: Bracket }
- { key: 07, mods: Shift, mode: Vi, action: FirstOccupied }
```
