### ISSUE TITLE
support switch tabs using ⌘ + 1 ~ 9 on macOS

### ISSUE THREAD

**Issue by hronro** [alacritty/alacritty#5991] opened 2022-04-08 03:38 UTC
<details>
<summary>System</summary>
OS: macOS

Version: 0.10.0
</details>

Currently on macOS I can use <kbd>⌘</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> and <kbd>⌘</kbd> + <kbd>Shift</kbd> + <kbd>]</kbd> to switch prev tab and next tab. But I would also like to use <kbd>⌘</kbd> + <kbd>1</kbd> to switch to the 1st tab and <kbd>⌘</kbd> + <kbd>2</kbd> to switch to the 2nd tab and so on.

**Comment by chrisduerr** [comment] 2022-04-08 04:06
Duplicate of https://github.com/alacritty/alacritty/issues/5786.

**Closed by chrisduerr** 2022-04-08 04:06 UTC
