### ISSUE TITLE
Doesn't display italic font

### ISSUE THREAD

**Issue by foisonocean** [alacritty/alacritty#1977] opened 2019-01-06 05:20 UTC
OS: macOS 10.14.2

I'm using a `Fantasque Sans` patched by [nerd fonts](https://github.com/ryanoasis/nerd-fonts), and here is my alacritty config:

```yaml
# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: FantasqueSansMono Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    family: FantasqueSansMono Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    family: FantasqueSansMono Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Italic
```

In alacritty I can't see any italic fonts (iTerm2 can display italic fonts correctly), and here are two screenshots of alacritty and iTerm2 opening a same file using vim:

Alacritty:
![Alacritty screenshot](https://user-images.githubusercontent.com/15059605/50732395-6e5f4180-11b5-11e9-8425-7df86b6860e1.png)

iTerm2:
![iTerm2 screenshot](https://user-images.githubusercontent.com/15059605/50732400-92bb1e00-11b5-11e9-9f9d-871ab85d6497.png)

**Comment by chrisduerr** [comment] 2019-01-06 12:13
This is a duplicate of https://github.com/jwilm/alacritty/issues/1754 if the font does not provide its own italics version (which is the likely cause).

Otherwise this would be a duplicate of https://github.com/jwilm/alacritty/issues/1560, but that seems a lot less likely.

**Comment by chrisduerr** [comment] 2019-01-06 12:43
@foisonocean Does the bold font work correctly?

**Comment by foisonocean** [comment] 2019-01-06 13:33
@chrisduerr 
yes, bold fonts work correctly

**Comment by chrisduerr** [comment] 2019-01-06 13:48
To make sure that this is not a feature detection issue, does running `echo -e "\e[3mItalic"` render like normal text or does that work?

**Comment by foisonocean** [comment] 2019-01-06 13:55
@chrisduerr 
the output of `echo -e "\e[3mItalic"` is italic. That' weird, I don't know why it doesn't works in vim.

**Comment by chrisduerr** [comment] 2019-01-06 13:57
@foisonocean Does running vim with `TERM=xterm-256color vim` resolve the problem? Also just to make sure, this is 'vim', not 'neovim', right?

**Comment by foisonocean** [comment] 2019-01-06 13:59
@chrisduerr 
Sorry my bad, it's actually neovim.

And running neovim with `TERM=xterm-256color` doesn't fix the problem.

**Comment by chrisduerr** [comment] 2019-01-06 14:05
When you do `echo $TERM` in iTerm, what do you get? Does setting it to this in Alacritty make it so neovim actually displays the text in italic?

**Comment by foisonocean** [comment] 2019-01-07 02:16
@chrisduerr
The outputs of `echo $TERM` in iTerm and Alacritty are same(`xterm-256color`)

**Comment by chrisduerr** [comment] 2019-01-07 07:56
This will probably have to be addressed with `neovim`, since I'm not sure exactly what is done to check if text should be rendered with italics or not.

**Comment by chrisduerr** [comment] 2019-01-07 14:48
@foisonocean You could try setting **both** `XTERM_VERSION=9999` and `TERM=xterm-256color` and see if launching neovim then allows for you to see italics.

**Comment by chrisduerr** [comment] 2019-01-07 15:09
Another idea would be running a different third party terminal emulator like kitty, to make sure that this isn't *only* working on iTerm.

**Comment by foisonocean** [comment] 2019-01-08 10:46
@chrisduerr 

I tried `nvim -V3log` in both Alacritty and iTerm2: in the log of Alacritty, `enter_italics_mode` doesn't appeared, and in the log of iTerm2, `enter_italics_mode` appeared and equal to `<Esc>[3m`.

I also tried Kitty, Kitty can display italic in vim correctly.

**Comment by chrisduerr** [comment] 2019-01-08 13:06
@foisonocean Have you tried exporting both `XTERM_version=9999` and `TERM=xterm-256color` before running nvim? It seems like neovim is indeed not detecting the escape sequence for italics correctly.

**Comment by chrisduerr** [comment] 2019-01-08 13:44
@foisonocean would you mind creating an issue on the neovim tracker, linking to this one? The people there are probably more capable at resolving this quickly and it seems that neovim is at least slightly involved.

**Comment by superobertking** [comment] 2019-04-09 12:40
This seems to be a [common issue for many terminal emulators](https://www.reddit.com/r/linux/comments/6nuwt1/enabling_italics_in_vim_and_virtual_terminals/). I found this [workaround](https://hobo.house/2017/07/17/using-italics-with-vim-in-your-terminal/) which adds `sitm=\E[3m, ritm=\E[23m` to a custom terminfo file. I had the same issue before and this worked for me. One thing worths notice is that you may need to set `TERM` back when you `ssh` to another machine (e.g. `TERM=xterm-256color ssh host`).

**Comment by chrisduerr** [comment] 2020-05-09 14:48
Alacritty's terminfo should already set these correctly, other terminfos are not supported. So I don't think there's any issue here left to fix.

**Closed by chrisduerr** 2020-05-09 14:48 UTC
Labels: H - macos, S - font

**Comment by thornjad** [comment] 2020-10-08 14:55
I am experiencing this same issue, and there doesn't appear to be a solution here. In Vim and Emacs, italics don't appear in Alacritty. 

- Italics appear normally when using iTerm and Kitty
- This occurs in every font I try, Victor Mono, Source Code Pro, Fira Code, Menlo
- My config looks like this:

```
 font:
   normal:
     family: Victor Mono
     style: Regular
   bold:
     family: Victor Mono
     style: SemiBold
   italic:
     family: Victor Mono
     style: Italic
   bold_italic:
     family: Victor Mono
     style: SemiBold Italic
```

- `echo -e "\e[3mItalic"` _does_ output italic text
- running `TERM=xterm-256color` before a command does not fix it
- running `XTERM_version=9999 TERM=xterm-256color` before a command does not fix it
- Same output from `nvim -V3log`, no `enter_italics_mode` appears in Alacritty
- I've tried the hacky terminfo file "workaround" but it doesn't work

**Comment by kchibisov** [comment] 2020-10-08 14:57
Try using `alacritty` terminfo, it should have italics on macOS.

**Comment by thornjad** [comment] 2020-10-08 15:09
If I try to use `alacritty`, nothing works. Neovim has no syntax coloring, tmux and emacs won't even open, complaining that they `cannot open terminfo database file`. Even programs like `man` won't start. Is there something I can do to get programs to recognize that alacritty is a real terminal?

**Comment by kchibisov** [comment] 2020-10-08 15:11
it means that you should install our terminfo file, consult INSTALL.md on how to do that.

**Comment by thornjad** [comment] 2020-10-08 15:14
I've done that, this is the output from infocmp, does it look correct?

```
#	Reconstructed via infocmp from file: /opt/local/share/terminfo/61/alacritty
alacritty|alacritty terminal emulator,
	am, bce, ccc, hs, km, mc5i, mir, msgr, npc, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, dsl=\E]2;\007, ech=\E[%p1%dX,
	ed=\E[J, el=\E[K, el1=\E[1K, flash=\E[?5h$<100/>\E[?5l,
	fsl=^G, home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH,
	ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=\n,
	indn=\E[%p1%dS,
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
	invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
	kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
	kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^?,
	kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, oc=\E]104\007, op=\E[39;49m, rc=\E8,
	rep=%p1%c\E[%p2%{1}%-%db, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
	rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l, rmkx=\E[?1l\E>,
	rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
	rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	setb@, setf@,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
	smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
	smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
	tsl=\E]2;, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?%[;0123456789]c, u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by thornjad** [comment] 2020-10-08 15:34
I have also already tried completely wiping out my alacritty build (including the terminfo entries) and recompiling from a fresh clone of the repo

**Comment by kchibisov** [comment] 2020-10-08 15:43
Could you try running `tic` from a regular user?

**Comment by thornjad** [comment] 2020-10-08 16:19
_That worked!_ Oh my gosh I've been living without italics in alacritty for years now. What's the difference between using `tic` with sudo vs normal? I really know nothing about `tic`. Should we add to INSTALL.md that dropping the `sudo` might work better in a case like mine?

**Comment by haringsrob** [comment] 2020-11-02 20:13
In case anyone else is still having issues. In your config `italic:` should be `italics:`

**Comment by kchibisov** [comment] 2020-11-02 20:20
it's not, it's `italic`. https://github.com/alacritty/alacritty/blob/9028fb451a967d69a9e258a083ba64b052a9a5dd/alacritty.yml#L128 . And always was 'italic', providing `italics`, will make it ignore that section entirely, thus it'll fallback to using your normal font family and setting slant for a font that corresponds to italic.

**Comment by lijunzh** [comment] 2020-11-30 22:07
> _That worked!_ Oh my gosh I've been living without italics in alacritty for years now. What's the difference between using `tic` with sudo vs normal? I really know nothing about `tic`. Should we add to INSTALL.md that dropping the `sudo` might work better in a case like mine?

I tried running both with and without `sudo`, neither worked for me. I am still missing italic font. My `infocomp alacritty` results are as below. Again, the italic font displays correctly on both iTerm2 and Terminal.app


```
 infocmp alacritty
#       Reconstructed via infocmp from file: /Users/lijun/.terminfo/61/alacritty
alacritty|alacritty terminal emulator,
        am, bce, ccc, hs, km, mc5i, mir, msgr, npc, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, dsl=\E]2;\007, ech=\E[%p1%dX,
        ed=\E[J, el=\E[K, el1=\E[1K, flash=\E[?5h$<100/>\E[?5l,
        fsl=^G, home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH,
        ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=\n,
        indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^?,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
        memu=\Em, oc=\E]104\007, op=\E[39;49m, rc=\E8,
        rep=%p1%c\E[%p2%{1}%-%db, rev=\E[7m, ri=\EM,
        rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
        rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l, rmkx=\E[?1l\E>,
        rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        setb@, setf@,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
        smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        tsl=\E]2;, u6=\E[%i%d;%dR, u7=\E[6n,
        u8=\E[?%[;0123456789]c, u9=\E[c, vpa=\E[%i%p1%dd,
```

**Comment by foisonocean** [comment] 2020-12-01 06:46
For me, this bug was fixed serval versions ago, but now it can be reproduced again, and even worse than before.
Previously only `nvim` doesn't  display italics, but for now, both `echo -e "\e[3mItalic"` and `nvim` doesn't display italics.

**Comment by kchibisov** [comment] 2020-12-01 06:49
@foisonocean what font are you using?

**Comment by foisonocean** [comment] 2020-12-01 07:02
@kchibisov 
It's weird, the default font works.
I'm using self patched [MonoLisa](https://monolisa.dev), patched by [nerd-fonts](https://github.com/ryanoasis/nerd-fonts).
I tried the same font in Terminal.app, it can display italics properly.

**Comment by kchibisov** [comment] 2020-12-01 07:09
Terminal.app can do fake italics, which we don't support on macOS. Could you specify only `normal` section in the font settings, maybe you've misspelled 'style' for italics or something? Though if you have 0.5.0 around and it works with the exact same config it could help to understand why something got changed.

**Comment by foisonocean** [comment] 2020-12-01 07:11
it works after removing the `style: *` line in alacritty config.

![CleanShot 2020-12-01 at 15 07 12](https://user-images.githubusercontent.com/15059605/100708383-29ff6f00-33e7-11eb-85cd-f1f46953ab20.png)

**Comment by kchibisov** [comment] 2020-12-01 07:17
Maybe the style isn't called `Italic` in the end? Like some fonts name it differently, check font book app on how the style is named.

**Comment by foisonocean** [comment] 2020-12-01 07:18
@kchibisov 
Turned out the italic style for MonoLisa font is actually called `Regular Italic` instead of `Italic`, Alacritty finally works when I change `style: Italic` to `style: Regular Italic` in alacritty.yml`. Thanks for your reply.

**Comment by foisonocean** [comment] 2020-12-01 07:22
@kchibisov BTW, do I have to specify style names for regulars, italics and others? It seems alacritty still works properly when I remove those lines.

**Comment by kchibisov** [comment] 2020-12-01 07:27
you don't, alacritty will request proper weight and slant for everything if you omit them, so having something like.

```yaml
font:
  normal:
    family: MonoLisa Nerd Font
```

will work for you just fine.

**Comment by lijunzh** [comment] 2020-12-01 14:32
Both solutions from @foisonocean and @kchibisov worked for me. Thank you very much.

I was using SF Mono, whose italic font is called "Regular italic" too.

**Comment by DrGo** [comment] 2021-01-11 23:11
If you are running tmux, try adding to your .tmux.conf
```
set -g default-terminal "alacritty"
```

**Comment by lonelykid** [comment] 2021-02-23 21:51
> If you are running tmux, try adding to your .tmux.conf
> 
> ```
> set -g default-terminal "alacritty"
> ```

This is working. But I'm afraid setting a TERM other than screen-256color/tmux-256color breaks other things.

**Comment by h0adp0re** [comment] 2021-06-02 21:34
I've tried everything suggested here, nothing has worked for me. I suppose I can live without italics, not a dealbreaker. Strange how nothing helped tho, with some settings italics actually rendered as reverse video...

**Comment by kahnc** [comment] 2021-06-04 11:52
> it works after removing the `style: *` line in alacritty config.
> 
> ![CleanShot 2020-12-01 at 15 07 12](https://user-images.githubusercontent.com/15059605/100708383-29ff6f00-33e7-11eb-85cd-f1f46953ab20.png)

This solved the issue for me! Removing those lines fixed it.

**Comment by wasifekbal** [comment] 2022-10-14 17:42
> you don't, alacritty will request proper weight and slant for everything if you omit them, so having something like.
> 
> ```yaml
> font:
>   normal:
>     family: MonoLisa Nerd Font
> ```
> 
> will work for you just fine.

This actually worked for me. thanks @kchibisov and @hronro

**Comment by snOm3ad** [comment] 2023-09-01 13:50
> > If you are running tmux, try adding to your .tmux.conf
> > ```
> > set -g default-terminal "alacritty"
> > ```
> 
> This is working. But I'm afraid setting a TERM other than screen-256color/tmux-256color breaks other things.

For anyone down this rabbit hole, this [comment](https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6?permalink_comment_id=4253659#gistcomment-4253659) helped put everything into perspective.

There is also this [guide](https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/) that though a bit outdated provides some useful information as to why this process is so chaotic in macOS. The opening sentence:

> macOS ships with an old and very out-of-date version of ncurses (5.7). This version does not contain a terminfo entry for tmux-256color, the preferred TERM value when using tmux.

The solution part of the guide is a bit outdated (does not apply to Apple Silicon), so if you want to fix it properly you might want to follow [this](https://gist.github.com/joshuarli/247018f8617e6715e1e0b5fd2d39bb6c) instead.
