### ISSUE TITLE
allow binding right opt to ctrl

### ISSUE THREAD

**Issue by unphased** [alacritty/alacritty#1019] opened 2018-01-11 17:18 UTC
Requesting this use of this feature from iTerm. 

![image](https://user-images.githubusercontent.com/1542910/34837584-3d8a6268-f6c9-11e7-852e-17dbfa0b5e60.png)

It seems like in order to replicate this functionality I would need to manually repeat all of my ctrl binds with opt binds. Which brings me to the next point:

I wonder if it is even possible to differentiate the two opt modifier keys yet.

**Comment by chrisduerr** [comment] 2018-09-28 08:52
This is slightly related to #62.

**Comment by pwnorbitals** [comment] 2020-11-14 16:46
Interesting feature request, issue bump to bring it some attention :)

**Comment by chrisduerr** [comment] 2020-11-14 17:52
Closing as duplicate of #62.

**Closed by chrisduerr** 2020-11-14 17:52 UTC
Labels: H - macos

**Comment by unphased** [comment] 2020-11-14 18:01
For readers out there (wow, 99 thumbs up in the linked feature request), what I've done was just perform this map globally on macOS using karabiner. It works for me and might be an even better approach than doing it only for a terminal emulator.
