### ISSUE TITLE
Memory leaks when idle

### ISSUE THREAD

**Issue by i404788** [alacritty/alacritty#6210] opened 2022-07-16 17:11 UTC
I've recently had memory leaks from alacritty which were bad enough to give me OOM issues so I thought I'd report it despite other different threads (https://github.com/alacritty/alacritty/issues/2528, https://github.com/alacritty/alacritty/issues/4806, https://github.com/alacritty/alacritty/issues/5438). Interestingly enough I didn't have this issue with 0.10.1 initially, but after upgrading to a larger high-refresh rate display (2560x1440, 120fps) I started getting very quickly increasing memory consumption even when idle. I tried upgrading to the latest version but doesn't seem to have changed much.

Before closing a mostly empty and idle (fish shell if that matters) alacritty instance:
![image1](https://user-images.githubusercontent.com/50617709/179365002-feea7672-f3f1-40fc-ac58-b49ec74341f6.png)

After closing & re-opining alacritty to the same state:
![image2](https://user-images.githubusercontent.com/50617709/179365030-9fc16cc2-6123-4e3b-9acb-3f4903d5d6d1.png)

### System

OS: Linux
Version: alacritty 0.11.0-dev (2a676dfa), but also 0.10.1-dev
Linux/BSD: X11, i3wm

**Comment by chrisduerr** [comment] 2022-07-16 19:24
I don't understand, the RAM usage before is 3.5G, while reopening it had a memory usage of 3.5G. Where is the leak? That's the exact same memory usage.

**Comment by nixpulvis** [comment] 2022-07-16 21:59
Considering I never see alacritty anywhere near even 1GB (unless I'm just not paying enough attention), this does surprise me. Calling it a continuous leak might not be accurate, but wouldn't you expect the usage to be lower @chrisduerr?

**Comment by chrisduerr** [comment] 2022-07-17 04:18
I mean if you have some random massive terminal and increase the scrollback history you'll certainly sip a good chunk of memory.

**Comment by i404788** [comment] 2022-07-17 05:39
@chrisduerr the issue is there is no history these are pretty much fresh instances of alacritty, for this issue I opened a new instance at the time of posting (12 hours ago) which is currently at 3.4% usage (1072MB RES).

**Comment by kchibisov** [comment] 2022-07-17 10:31
Given that you know how to trigger it, I'd suggest to compile a version with debug symbols and run it under memory profiler. In general you should look for buffer sizes, etc.

**Comment by i404788** [comment] 2022-07-17 10:46
> Given that you know how to trigger it, I'd suggest to compile a version with debug symbols and run it under memory profiler. In general you should look for buffer sizes, etc.

I've started a heaptrack instance now, I'll see if I get anything from it. If you have a better tool for testing this let me know.

**Comment by kchibisov** [comment] 2022-07-17 11:34
I'm not sure. I usually use either `valgrind` with `dhat` or `bytehound`. The later is harder to setup, but it's a bit more useful iirc.

**Comment by i404788** [comment] 2022-07-17 22:09
I looked at the heaptrack log and it seems fairly extensive so I though it should be enough be let me know if more info is needed.

[heaptrack.alacritty.4862.log](https://github.com/alacritty/alacritty/files/9128652/heaptrack.alacritty.4862.log)

**Comment by kchibisov** [comment] 2022-07-17 22:28
This function is being called like once on resize and loads a font. Do you have like 3 GBs of fonts installed. Also I'm not sure you can trigger it until you actually resize, that likely happened on the initial call to that function.

**Comment by i404788** [comment] 2022-07-17 22:33
Well if you check the bottom of the logs it does say:
```
total runtime: 40967.98s.
calls to allocation functions: 28602490 (698/s)
temporary memory allocations: 9724699 (237/s)
peak heap memory consumption: 429.76M
peak RSS (including heaptrack overhead): 581.26M
total memory leaked: 422.94M
suppressed leaks: 30.25K
```
The logs above show is repeated a few times (minus the first 4 lines), so I think it's leaked in the font config. 
For reference I have `220M` of fonts available although only 3 of them are configured to be used (4.4M according to the disk cache):
```
$ du -hd0 /usr/share/fonts/                                                                                                                                                                                                                                 
220M	/usr/share/fonts

$ du -hd0 /var/cache/fontconfig/                                                                                                                                                                                                                             (base)  master
4.4M	/var/cache/fontconfig/
```

**Comment by i404788** [comment] 2022-07-17 22:39
> Also I'm not sure you can trigger it until you actually resize, that likely happened on the initial call to that function

Hmm I never resized it myself but it did go into sleep mode several times, then again iirc it also leaked a few times without going into sleep mode.

**Comment by i404788** [comment] 2022-07-17 22:48
To test I've just started a new instance which is 45.2M, and after repeatedly changing the font size (`Ctrl+` & `Ctrl-`) I've gotten it to 404M in about a minute

**Comment by kchibisov** [comment] 2022-07-17 23:28
Could you post `-vv` log from idle instance you get that usage?

**Comment by i404788** [comment] 2022-07-17 23:46
Here is using the font size trick that went to 980M, the true idle will take a while longer. Note that the memory increase is fairly continuous/linear, only an initial jump to 200M (i'm guessing around the load font face messages).

[alacritty.log](https://github.com/alacritty/alacritty/files/9128772/alacritty.log)

**Comment by chrisduerr** [comment] 2022-07-18 03:20
In your initial report you clearly stated that after restarting Alacritty still consumes multiple gigabytes of memory. Is this accurate or not? Did you shut down all instances of the process or did you just close a window in a multi-window process just to open another one?

**Comment by i404788** [comment] 2022-07-18 07:36
Hmm no that was never an issue, the issue was that it consumes increasingly more memory even when I haven't done **anything** with the instance. Closing & re-opening clears the memory as shown in the initial screenshot where I did that with 1 instance and freed 2.2G, I suppose my broad filter may have been confusing.

**Comment by chrisduerr** [comment] 2022-07-18 17:31
> when I haven't done anything with the instance

You just said that the memory increases when you change the font size. Does that count as not doing anything with the instance or did you actually do "something"?

If you claim that you haven't done *anything*, that means you've just opened a completely new, fresh Alacritty process. Everything else is **something**. So please describe your issue properly.

**Comment by i404788** [comment] 2022-07-18 18:02
> after upgrading to a larger high-refresh rate display (2560x1440, 120fps) I started getting very quickly increasing memory consumption even when idle

In the bug report I was able to recreate a similar situation (large memory usage) by resizing the font, after seeing the logs from the memory leak test (https://github.com/alacritty/alacritty/issues/6210#issuecomment-1186615995) which was an idle instance (where I haven't done anything in it).

> If you claim that you haven't done anything, that means you've just opened a completely new, fresh Alacritty process. Everything else is something.

The issue is a memory leak; the cause is (likely) the font cache; it occurs both when doing nothing and doing something, but can be 'simulated faster' by repeatedly changing the font size.

**Comment by chrisduerr** [comment] 2022-07-18 18:22
Duplicate of #5438, I'd assume your "idle instance" was moved across monitors and similar operations which cause a font size change.

**Closed by chrisduerr** 2022-07-18 18:22 UTC
Labels: A - needs repro

**Comment by i404788** [comment] 2022-07-18 18:26
I guess I'll switch to kitty for now

**Comment by chrisduerr** [comment] 2022-07-18 22:25
Sleep will remove and reconnect the monitor, so it's the same, yes.
