### ISSUE TITLE
No action to mimic PowerShell's CopyPaste action.

### ISSUE THREAD

**Issue by loligans** [alacritty/alacritty#3629] opened 2020-04-22 21:04 UTC
When using PowerShell there is a useful action I think is called: CopyPaste

When data is `selected` and the mouse right clicks, the selected data is copied onto the clipboard. 

When no data is `selected` and the mouse right clicks, any data on the clipboard is pasted into the terminal.

### System

OS: Linux
Version: `0.4.2`
Linux/BSD: Wayland, Sway `1.4`

**Comment by chrisduerr** [comment] 2020-04-22 22:02
Duplicate of https://github.com/alacritty/alacritty/issues/3577.

**Closed by chrisduerr** 2020-04-22 22:02 UTC
