### ISSUE TITLE
Some emojis missing on macOS

### ISSUE THREAD

**Issue by maxcountryman** [alacritty/alacritty#3579] opened 2020-04-11 22:15 UTC
I seem to be running into a strange issue where a handful of emoji aren't rendering properly in Alacritty. The same emoji render in Terminal, however. (This seems to happen regardless of font and is consistently broken in Alacritty.)

## Alacritty
<img width="832" alt="Screen Shot 2020-04-11 at 3 10 38 PM" src="https://user-images.githubusercontent.com/74351/79056040-23797880-7c07-11ea-8e95-d3a0b00b0e24.png">

## Terminal
<img width="682" alt="Screen Shot 2020-04-11 at 3 13 07 PM" src="https://user-images.githubusercontent.com/74351/79056044-2ecca400-7c07-11ea-956d-1236b2c462dc.png">

Any pointers on what could be going on here would be appreciated! 🙂 

### System

OS: macOS 10.15.4 (19E287)
Version: alacritty 0.4.2 (f68de37)

**Comment by kchibisov** [comment] 2020-04-11 22:22
They are not missing, they are from your primary font. We'll add option to override curtain glyphs in #957

**Comment by maxcountryman** [comment] 2020-04-11 22:30
@kchibisov I'm not sure that's what's going on here. For instance, if I change my Alacritty font to match Terminal's (SF Mono), I still see the same issue.

<img width="832" alt="Screen Shot 2020-04-11 at 3 28 54 PM" src="https://user-images.githubusercontent.com/74351/79056240-2a08ef80-7c09-11ea-86dc-3099539f92d7.png">

```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: SF Mono
```

Are you referring to something else?

**Comment by kchibisov** [comment] 2020-04-11 22:36
That means that SF Mono has the characters you're testing, since they are not really emojis according to history, macOS can just use emojis when it finds out that glyph is actually an emoji according to their heuristics, a lot of apps are doing the same thing. However I don't like the solution to use special font for special glyphs, based on some strange heuristics(e.g. hardcoding). Could you try some font that doesn't have any emoji chars + special chars at all? e.g. https://github.com/JetBrains/JetBrainsMono

**Comment by maxcountryman** [comment] 2020-04-11 22:39
No dice:

<img width="832" alt="Screen Shot 2020-04-11 at 3 39 04 PM" src="https://user-images.githubusercontent.com/74351/79056367-9c2e0400-7c0a-11ea-9c3e-906444fe1306.png">

```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: JetBrains Mono
```

**Comment by kchibisov** [comment] 2020-04-11 22:41
Could you post this glyph to me, it seems pretty strange, since I see this glyph correct with the same font, but I'm not on macOS.

**Comment by kchibisov** [comment] 2020-04-11 22:42
I mean the character you've used.

**Comment by maxcountryman** [comment] 2020-04-11 22:43
@kchibisov it's copied [from here](https://emojipedia.org/high-voltage/). Please note it works as excepted in Terminal.

**Comment by kchibisov** [comment] 2020-04-11 22:47
>Please note it works as excepted in Terminal.

This information is kind of useless to me.

>@kchibisov it's copied from here.

Ok, the copied glyph renders as expected for me and knowing how our linux font backend works, it seems like the glyph is being picked from a font which is neither your emoji font nor your primary font. Are you fine with applying patches to our code and testing it?

**Comment by kchibisov** [comment] 2020-04-11 22:49
I've reopened since just looking at macOS backend it should pickup emoji font right after primary font most of the time, however if it's not doing so, and the primary font doesn't have emoijs(the font I've linked doesn't have them), so it could be picking some other font for whatever reason.

**Comment by maxcountryman** [comment] 2020-04-11 22:51
> > Please note it works as excepted in Terminal.
> 
> This information is kind of useless to me.

Okay. Here's how I see it being useful: it may be evidence of something strange going on here and possibly a bug or issue isolated to Alacritty specifically...

**Comment by kchibisov** [comment] 2020-04-11 22:53
>macOS can just use emojis when it finds out that glyph is actually an emoji according to their heuristics, a lot of apps are doing the same thing. However I don't like the solution to use special font for special glyphs, based on some strange heuristics(e.g. hardcoding).

If it does that the information is purely useless, since I can do `if emoji use font X` too, but it's not a solution.

**Comment by maxcountryman** [comment] 2020-04-11 22:55
> > macOS can just use emojis when it finds out that glyph is actually an emoji according to their heuristics, a lot of apps are doing the same thing. However I don't like the solution to use special font for special glyphs, based on some strange heuristics(e.g. hardcoding).
> 
> If it does that the information is purely useless, since I can do `if emoji use font X` too, but it's not a solution.

🤷‍♂️

**Comment by chrisduerr** [comment] 2020-04-16 02:19
Could you check from which font the different Emojis are served? So which font macOS' built in terminal is using and which one Alacritty renders?

**Comment by maxcountryman** [comment] 2020-04-16 03:39
> Could you check from which font the different Emojis are served? So which font macOS' built in terminal is using and which one Alacritty renders?

Are you asking me to set them both to the same font?

**Comment by kchibisov** [comment] 2020-04-16 04:38
Thunderbolt character is from AppleColorEmoji font, however it's rendered in black and white for whatever reason, so likely rasterizer is doing something odd or AppleColorEmoji has a bit broken character and it should be from some other font, but I feel like it's rasterizer.

**Comment by maxcountryman** [comment] 2020-04-16 18:24
I'm happy to test anything on my end if it's helpful.

**Comment by chrisduerr** [comment] 2020-04-16 18:52
> Thunderbolt character is from AppleColorEmoji font

Since it's not rendered remotely the same, I'd assume these are from a different font.

> Are you asking me to set them both to the same font?

No, though that would obviously be the basis of any useful test. The glyphs are rendered differently, so my assumption is that they're being retrieved from different fonts. So I'm curious what fonts they are from. It should be possible to easily check that on macOS, at least that's what a quick search lead me to believe.

**Comment by maxcountryman** [comment] 2020-04-16 19:03
> No, though that would obviously be the basis of any useful test. The glyphs are rendered differently, so my assumption is that they're being retrieved from different fonts. So I'm curious what fonts they are from. It should be possible to easily check that on macOS, at least that's what a quick search lead me to believe.

If you refer to my original issue, I’ve done just that. Happy to post additional screenshots if that’s helpful, but to recap using the same fonts in both Terminal and Alacritty produces the issue in Alacritty but not in Terminal (also recently tested with iTerm 2, which works the same as Terminal).

**Comment by chrisduerr** [comment] 2020-04-16 20:21
> If you refer to my original issue, I’ve done just that.

If you have done so, I don't see it. I'm not talking about configured fonts in Alacritty or Terminal, since that just configures the primary font and nothing else. I'm specifically curious which exact font these symbols are actually loaded from. Not which is the primary font that should be checked before others.

**Comment by maxcountryman** [comment] 2020-04-16 20:28
> > If you refer to my original issue, I’ve done just that.
> 
> If you have done so, I don't see it. I'm not talking about configured fonts in Alacritty or Terminal, since that just configures the primary font and nothing else. I'm specifically curious which exact font these symbols are actually loaded from. Not which is the primary font that should be checked before others.

Have I set the fonts to match? Yes, insofar as they can be configured in the respective clients. If this isn’t what you meant, please be specific about what you’d like to test and how.

**Comment by chrisduerr** [comment] 2020-04-16 20:32
> Have I set the fonts to match? Yes, insofar as they can be configured in the respective clients. If this isn’t what you meant, please be specific about what you’d like to test and how.

I'm just asking you to verify which exact fonts the two different versions of the glyphs are being loaded from. I really don't see how I could be any more specific here.

**Comment by chrisduerr** [comment] 2020-05-17 21:56
Closing as duplicate of #2800, the issue is slightly different but it's likely for similar reasons.

**Closed by chrisduerr** 2020-05-17 21:56 UTC
Labels: B - bug, H - macos, S - font
