### ISSUE TITLE
inconsistent behavior of closing windows and quitting the app on macOS

### ISSUE THREAD

**Issue by gabroo** [alacritty/alacritty#6019] opened 2022-04-23 21:35 UTC
### System

OS: macOS 12.3.1 (Monterey)
Version: 0.10.1

### Description

When I close an alacritty window, I expect the instance of the app to quit. This seems to be the default behavior.

This behavior works in windowed mode. When I exit the shell or close the window (⌘ W), the app correctly quits.

This behavior doesn't work in fullscreen mode. When I exit the shell or close the window (⌘ W), the app stays open (icon visible in dock with a dot underneath) and I have to manually quit (⌘ Q) in order to quit the app.

**Comment by chrisduerr** [comment] 2022-04-24 07:16
Duplicate of https://github.com/alacritty/alacritty/issues/5975.

**Closed by chrisduerr** 2022-04-24 07:16 UTC
