### ISSUE TITLE
Feature request: multiple font family support

### ISSUE THREAD

**Issue by PetrusZ** [alacritty/alacritty#3412] opened 2020-03-03 10:02 UTC
### System

OS: Linux
Version: alacritty 0.4.1
Linux/BSD: X11, compton and i3

Add multiple font family support, or use fallback font family and style according to fontconfig.

For example:

If I set font family as monospace a.k.a Hack which only have English font and set style as regular, set Source Han Sans CN as CJK font in fontconfig, alacritty works fine at normal situation. But when CJK font mixed with English in alacritty, the CJK font can't be bold because of Hack don't have CJK bold/italic/etc font. It has limited by alacritty.

But, if alacritty support multiple font family, those problems could be solved.
e.g.:
```
font:
    family: Hack
    family: Source Han Sans CN
```

When alacritty can't find bold CJK font in Hack, it will fall back to Source Han Sans CN and find the bold CJK font.

**Comment by chrisduerr** [comment] 2020-03-03 10:07
Duplicate of #957.

**Comment by chrisduerr** [comment] 2020-03-03 10:08
> Add multiple font family support, **or use fallback font family and style according to fontconfig**.

Note that this is already the case.

**Closed by chrisduerr** 2020-03-03 10:07 UTC

**Comment by kchibisov** [comment] 2020-03-03 10:11
>Note that this is already the case.

On latest master.

**Comment by PetrusZ** [comment] 2020-03-03 10:13
> On latest master.

Does 0.4.1 have this feature?

**Comment by kchibisov** [comment] 2020-03-03 10:17
v0.4.1 isn't a latest master, so it doesn't have it.

**Comment by PetrusZ** [comment] 2020-03-03 10:19
Thank you. I will try latest immediately.

**Comment by PetrusZ** [comment] 2020-03-03 10:27
Thanks again. The latest works perfect on CJK font.

**Comment by ajr-dev** [comment] 2021-07-13 21:06
The preferred font goes last?

**Comment by WS-Na** [comment] 2022-04-01 10:58
How to setup multiple font family under the one proposal ,like this
family: Recursive Mono , 行楷 , nerd font

**Comment by 8ullyMaguire** [comment] 2023-11-12 21:23
It uses the last font first.
```
font:
  normal:
    family: SauceCodePro Nerd Font
    family: Hack Nerd Font
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
```

**Comment by chrisduerr** [comment] 2023-11-12 21:41
> It uses the last font first.

It only uses one font. You're just overriding your fields.

**Comment by 8ullyMaguire** [comment] 2023-11-12 21:48
Then why do you close the issue without mentioning that? You make people believe that this is actually supported.

> > or use fallback font family and style according to fontconfig
> 
> Note that this is already the case.

This is totally misleading, you are saying there is fallback font family and style and now you say there isn't, it just overrides it.

**Comment by kchibisov** [comment] 2023-11-12 22:42
fontconfig is not alacritty's font configuration, it's a https://wiki.archlinux.org/title/Font_configuration .

>This is totally misleading, you said there was fallback font family and style and now you are saying there isn't, it just overrides it.

It was said in _fontcofig_, not in alacritty itself. In alacritty you just override fields.

**Comment by chrisduerr** [comment] 2023-11-13 10:25
> You make people believe that this is actually supported.

Only people with zero reading comprehension.
