### ISSUE TITLE
Characters randomly prefixed with command key

### ISSUE THREAD

**Issue by n0ibe** [alacritty/alacritty#3305] opened 2020-02-07 01:27 UTC
OS: macOS
Version: alacritty 0.4.1 (4d9253b)

I don't have a predictable way to reproduce this, but when I'm switching focus between spaces or other apps and then go back to alacritty, every character I input is interpreted as a `cmd + <char>` combination, so for example if I go back to alacritty and type the character `q`, it is registered as `cmd + q`, which closes the current window. Needless to say this is extremely annoying.

The only way I found to stop this behaviour when it happens is pressing one of the modifier keys (`ctrl`, `option` (macos's alt) and `cmd` (macos's super)).

Is this a known issue?

**Comment by kchibisov** [comment] 2020-02-07 01:37
duplicate of #3188

**Closed by kchibisov** 2020-02-07 01:37 UTC
