### ISSUE TITLE
Backspace not working with tmux on macOS

### ISSUE THREAD

**Issue by okuuva** [alacritty/alacritty#3317] opened 2020-02-10 07:54 UTC
Backspace isn't correctly working with tmux on macOS with the latest master. Outside tmux it works just fine but immediately after connecting to tmux it starts acting up: single strokes don't work at all and holding down the button does erase text but is super hard to control since there's a longer-than-normal delay before it starts doing that. `alacritty --print-events` attached, first part is my normal usage and the second part is me just starting alacritty, typing nonsense to fresh terminal, then opening a new tmux session to check if backspace stopped working correctly which it did.

### System

OS: macOS Mojave 10.14.6 (same thing on Catalina, can't remember the version number string from the top of my head and can't check currently since I'm at work)
Version: alacritty 0.4.2-dev (5cd13f8)

### Logs

Keyboard and bindings: `alacritty --print-events`:
[alacritty.log](https://github.com/alacritty/alacritty/files/4179548/alacritty.log)

**Comment by okuuva** [comment] 2020-02-10 08:02
@kchibisov suggested on IRC that I'd map backspace to the backspace character but it only made things worse or I'm doing something wrong. On plain terminal it works just fine but in tmux backspace stopped working altogether. No more delayed erasing of characters with holding it down, nothing. Here's the bind I used:

`  - { key: Back, chars: "\x08"}`

**Comment by chrisduerr** [comment] 2020-02-10 10:22
The IRC suggestion was actually incorrect, it should be `\x7f`, not `\x08`, since this was caused by https://github.com/alacritty/alacritty/pull/3264.

Could you try that to confirm this is the issue you're talking about?

**Comment by okuuva** [comment] 2020-02-10 10:57
Well, suggestion was correct, it just didn't mention the char code which I dug up myself 😅 Will try that later today when I get back to my mac.

**Comment by okuuva** [comment] 2020-02-10 11:27
@chrisduerr ok, tried head with that correct binding and can confirm it works both inside and outside of tmux. Attached new --print-events log in case you need it.
[alacritty-print-events-backspace-bind.log](https://github.com/alacritty/alacritty/files/4180512/alacritty-print-events-backspace-bind.log)

**Comment by chrisduerr** [comment] 2020-02-10 22:11
Fixed in https://github.com/alacritty/alacritty/pull/3320.

**Closed** 2020-02-10 23:41 UTC
Labels: H - macos, S - keybindings

**Comment by Peachy74** [comment] 2022-06-09 08:47
Hi okuuva, 
I have the same problem. backspace doesn't work in tmux.
But where do I have to enter - { key: Back, chars: "\x08"} or (\x7f)?

Many greetings
Alex

**Comment by okuuva** [comment] 2022-06-10 11:21
> Hi okuuva, I have the same problem. backspace doesn't work in tmux. But where do I have to enter - { key: Back, chars: "\x08"} or (\x7f)?

@Peachy74 I doubt the problem is related since backspace has been working in alacritty+tmux+macOS combo straight out of the box for over two years now, unless some recent commit in `master` broke it (I'm running 0.10.1 from homebrew).

If you want to test the custom binding out then add the following line under `key_bindings` in your config file. If you haven't created one yet, copy the [example config](https://github.com/alacritty/alacritty/blob/master/alacritty.yml) to the right place (see [README.md](https://github.com/alacritty/alacritty/blob/1880522b64d9a5276acea428705c011cbbf8c04c/README.md#configuration)) and uncomment `key_bindings` before adding the line:

` - { key: Back, chars: "\x7f}`

**Comment by Peachy74** [comment] 2022-06-12 13:38
Hi okuuva, 
new insight. Deleting with the backspace key works. However, the cursor does not move to the left but to the right.
Only with Enter you can see that the line has been edited

**Comment by okuuva** [comment] 2022-06-13 08:18
@Peachy74 I suggest you open a new issue and describe the behavior and your setup in detail there. From the sound of it it isn't related to this issue and plenty has changed between current HEAD and the version I was running at the time.

**Comment by kornerr** [comment] 2022-06-13 21:18
I face the same problem and eventually found the missing command:

```
$(brew --prefix)/opt/ncurses/bin/infocmp tmux-256color > ~/tmux-256color.info
tic -xe tmux-256color ~/tmux-256color.info
```

https://superuser.com/a/1726134

**Comment by Peachy74** [comment] 2022-06-14 05:31
@kornerr , that was absolutely what was missing.
It works!
Thank you and have a nice day
