### ISSUE TITLE
Disappearing cursor until a window is changed on Sway

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#4780] opened 2021-02-09 18:25 UTC
cpu is Ivy Bridge, no dgpu, igpu HD Graphics 4000 driver i915.
linux void glibc, Sway, no elogind, no seatd, sway SUID.

On Sway the cursor sometimes turns invisible. Only alacritty is afflicted : https://github.com/swaywm/sway/issues/6008

Aside from reproducing with fullscreen MPV as stated in the linked issue, it can also be reproduced with: hide_when_typing: true
After typing in the terminal the cursor disappears and doesn't come back until the invisible cursor is moved out of the window to somewhere else.

sway log: [sway/input/cursor.c:865] denying request to set cursor from unfocused client

**Comment by chrisduerr** [comment] 2021-02-09 19:11
Does this only happen with `hide_when_typing` enabled in the config?

**Comment by tarkov2213** [comment] 2021-02-09 19:22
No.
It also happens when an adjacent window is closed but not always.
It can be made to trigger with 100% reliability by having a fullscreen MPV playing in one workspace and after MPV has made the cursor disappear (as intended) you switch to the workspace containing alacritty (such that the cursor is located on top of it) and the cursor does not appear - this behavior seems identical to when hide_when_typing: true. But done with hide_when_typing: false.

**Comment by chrisduerr** [comment] 2021-02-09 19:34
Oh, you mean `mpv` makes the cursor disappear?

Is the cursor invisible in sway too at that point? We could of course always unhide the cursor when the window is focused, but that seems like a somewhat strange scenario.

**Comment by tarkov2213** [comment] 2021-02-09 19:37
mpv makes the cursor disappear when idle, by design.

when switching workspace such that the invisible cursor is now over an alacritty window, the cursor stays invisible. it becomes visible for every other window in the same scenario.

this is merely the most reliable way to reproduce it, it also happens when a window adjacent to alacrity is closed and now the cursor is supposed to be in the alacritty window (and it was visible before) but is invisible.

invisible cursor is fully functional, just can't see it.

**Comment by chrisduerr** [comment] 2021-02-09 19:43
My main problem with this is that force unhiding the cursor when entering the Alacritty window would prevent applications from hiding the cursor intentionally. But I suppose it should be fine.

**Comment by tarkov2213** [comment] 2021-02-09 19:49
> Is the cursor invisible in sway too at that point?

So I made a floating alacritty window surrounded by blank sway background, the moment the invisible cursor leaves the floating window and enter sway background it becomes visible.

**Comment by Xyene** [comment] 2021-02-10 07:55
> force unhiding the cursor when entering the Alacritty window would prevent applications from hiding the cursor intentionally

Applications should only be able to hide cursors locally to their surfaces, not globally.

Alacritty should unconditionally be sending `wl_pointer.set_cursor` upon receiving `wl_pointer.enter`. But, Alacritty sends the appropriate `wl_pointer.set_cursor` calls already. I would check `WAYLAND_DEBUG=1 unbuffer alacritty |& grep -E 'wl_pointer@.*(set_cursor|enter)'` when reproducing to ensure that's the case. (I assume, but haven't checked, that Alacritty doesn't just send a fully transparent cursor image...)

If Alacritty is sending `wl_pointer.set_cursor` (with a serial matching `wl_pointer.enter` &mdash; this is the first number within the parameter lists of the events) and the cursor doesn't appear, that's probably a Sway bug. We've had similar ones before.

However, I can't reproduce this with Alacritty ba05e50 (both X and Wayland backends), Sway master, and mpv 27e41c6 (both X and Wayland backends).

@tarkov2213: if you are not on Sway master, try that since it might've been fixed there (I think https://github.com/swaywm/sway/commit/60d95414d4a7ff163099c9e551ec435cb0cb7eca is possibly relevant). If that doesn't fix things, please add a link to the _full_ debug log of a session reproducing the issue over on Sway's side &mdash; please don't try to guess what information is useful or not.

**Comment by tarkov2213** [comment] 2021-02-11 00:20
I have seen been able to find other applications afflicted by this. imv is one. the foot terminal is another. GTK, QT and xwayland apps are not afflicted.

wl_pointer@*.enter get printed when the invisible cursor enters the alacritty window and remains invisible.

interestingly enough, the wl_pointer@*.enter also keep on getting printed even as I move the invisible cursor between the two terminals (the debug alacritty and the alacritty that launched it) and it remains invisible until at some point it randomly becomes visible - my hypothesis is that as it crosses the small gap between the windows sway eventually claims the cursor for itself.

This hypothesis is likely true since it happens much faster and often immediately if the mouse is moved slowly.

Unfortunately this issue is not worth the hassle of compiling master and juggling two versions of sway for me, I have the kitty terminal on another bind and it works fine.

If it is a sway bug it is curious that so many other frameworks and apps don't trigger it. perhaps the wayland spec each choose to follow slightly differs.

**Comment by m1027** [comment] 2021-06-03 05:52
I believe I have the same issue here but with alacritty in gnome 40/wayland on
gentoo. I can use mpv too to trigger the situation:

- alacritty running, fullscreen in my case here
- start mpv via keys, not mouse: hit super, type mpv, enter
- use mpv to make cursor disappear (desired behaviour): double click into mpv
  to maximize/fullscreen it, wait a second to make cursor disappear
- close mpv via keyboard: ctrl-w, so then you are back in alacritty

Expected behaviour:

- mouse cursor visible when moving in the alacritty window

Actual behaviour:

- no mouse cursor when the mouse is over the alacritty window
- mouse cursor appears temporarily when e.g. on gnome taskbar
- mouse cursor still invisible when moving from taskbar to alacritty

Workaround to get the mouse cursor back:

- 2x alt tab

What did not help so far:

- updating from alacritty 7.2 to 8.0
- alacritty.yml: hide_when_typing: false

Thanks

**Comment by bronvic** [comment] 2021-06-08 13:37
I can not reproduce it on sway 1.6 with alacritty 0.8.0

As was mentioned above by @Xyene:
> it might've been fixed there (I think swaywm/sway@60d9541 is possibly relevant)

@m1027, what's your sway version?

**Comment by m1027** [comment] 2021-06-08 14:20
> I can not reproduce it on sway 1.6 with alacritty 0.8.0
> 
> As was mentioned above by @Xyene:
> 
> > it might've been fixed there (I think [swaywm/sway@60d9541](https://github.com/swaywm/sway/commit/60d9541) is possibly relevant)
> 
> @m1027, what's your sway version?

Plain tagged sway-1.6.

**Comment by m1027** [comment] 2021-06-08 15:59
> I can not reproduce it on sway 1.6 with alacritty 0.8.0
> 
> As was mentioned above by @Xyene:
> 
> > it might've been fixed there (I think [swaywm/sway@60d9541](https://github.com/swaywm/sway/commit/60d9541) is possibly relevant)
> 
> @m1027, what's your sway version?

Me again, I should express my case clearer as I am referring to *Gnome* as
mentioned above.

So:

When I use greetd + wayfire + sway-1.6 (sway just for the screen lock feautre)
I do not have this issue.

When I use gdm + gnome/wayland I am facing the issue.

**Comment by m1027** [comment] 2021-06-09 11:14
> I can not reproduce it on sway 1.6 with alacritty 0.8.0

I've found a simpler way to reproduce, at least for my case:

- Start sesson of Gnome on Wayland (Gnome 40 in my case)
- Run alacritty (fullscreen in my case)
- Run firefox (mouse cursor visible in firefox)
- Close firefox with Ctrl-W (mouse cursor disappers in firefox), so:
- alacritty window now visible (mouse cursor remains invisible)

Thanks

**Comment by ilkecan** [comment] 2021-06-09 14:52
I can reproduce this problem using sway 1.6 and alacritty 0.8.0, both from the nixos-21.05 channel.

To reproduce:
1. open an alacritty window
2. open a vlc window next to it
3. close the window opened in the the second step using a keyboard shortcut, while having the cursor over an area that will be used by the alacritty window opened in the first step.

Which application the window used in the second step belongs to seems to be important. So far, I can reproduce this reliably using `vlc` (X11), `nautilus` (Wayland) or `signal` (X11), can sometimes reproduce this using `fractal` (Wayland) while can't reroduce this using `alacritty` (Wayland) in the second step. 

https://user-images.githubusercontent.com/40234257/121373725-fd08b780-c947-11eb-8ab9-36a53a995458.mp4

Note that I have these 2 lines in my sway/config
```
seat * hide_cursor 5000
seat * hide_cursor when-typing enable
```

**Comment by kchibisov** [comment] 2021-06-09 22:05
Could you provide `strace alacritty` output just from starting it?

**Comment by ilkecan** [comment] 2021-06-09 23:01
Hi, [this](https://gist.githubusercontent.com/ilkecan/1796ba630b9f7dbf5aaf2682c04efb60/raw/18fd1ac0469f4f8339f4804cc7f4c1ef96813d01/output.txt) is the output I get when I run `strace alacritty` and kill the process a couple of seconds later.

**Comment by kchibisov** [comment] 2021-06-09 23:28
From what I can see it fails to find any cursor theme on your system, so install some and point to it, otherwise you wont see any cursor when it fails to load some, since you don't have anything to load the cursor from.


```
statx(AT_FDCWD, "/home/ilkecan/.icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.local/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.nix-profile/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.nix-profile/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/profiles/per-user/ilkecan/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/profiles/per-user/ilkecan/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/nix/var/nix/profiles/default/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/nix/var/nix/profiles/default/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/run/current-system/sw/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/run/current-system/sw/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.local/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.nix-profile/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/ilkecan/.nix-profile/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/profiles/per-user/ilkecan/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/profiles/per-user/ilkecan/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/nix/var/nix/profiles/default/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/nix/var/nix/profiles/default/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/run/current-system/sw/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/run/current-system/sw/share/pixmaps/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffdb7d24580) = -1 ENOENT (No such file or directory)
```

**Comment by ilkecan** [comment] 2021-06-09 23:54
Thank you @kchibisov, adding
```
seat * xcursor_theme Adwaita
```
to the sway configuration fixed the problem for me.

**Comment by tinywrkb** [comment] 2021-06-10 11:32
@ilkecan the `sway-input.5` man page states that the `xcursor_theme` is XWayland related setting. Consider trying instead to set a default cursor theme by creating `index.theme`, see the [Configuration section in the Cursor themes Arch Wiki page](https://wiki.archlinux.org/title/Cursor_themes)

**Comment by dnkl** [comment] 2021-06-10 13:20
@tinywrkb @ilkecan if things haven't changed since last I looked; `xcursor_theme` in Sway does two things: a) it set's the default cursor theme in XWayland, and b) exports the environment variables `XCURSOR_THEME` and `XCURSOR_SIZE`.

Some applications choose to loook at `XCURSOR_THEME`´`XCURSOR_SIZE`, while others let `libwayland-cursor` choose for them.

As far as I know, `libwayland-cursor` does **not** look at the `XCURSOR_*` variables. Instead, it loads the default theme from `/usr/share/icons/default/index.theme` (or the corresponding directories under `~/`).

**Comment by kchibisov** [comment] 2021-06-10 15:01
>As far as I know, libwayland-cursor does not look at the XCURSOR_* variables. Instead, it loads the default theme from /usr/share/icons/default/index.theme (or the corresponding directories under ~/).

I think it doesn't look, however we look at those variables for sure, since we don't use libwayland-cursor (we use some rust impl of what libwayland-cursor does).

**Comment by m1027** [comment] 2021-06-11 09:25
> Thank you @kchibisov, adding
> 
> ```
> seat * xcursor_theme Adwaita
> ```
> 
> to the sway configuration fixed the problem for me.

As I am hit using Gnome (not sway) I'd be curious how to apply such thing in
this case.

**Comment by ilkecan** [comment] 2021-06-11 10:29
@m1027 You can try
```
gsettings set org.gnome.desktop.interface cursor-theme Adwaita
```
for GNOME. As previously mentioned, ArchWiki has [a detailed page](https://wiki.archlinux.org/title/Cursor_themes#Configuration) on this topic.

**Comment by m1027** [comment] 2021-06-12 08:27
> @m1027 You can try
> 
> ```
> gsettings set org.gnome.desktop.interface cursor-theme Adwaita
> ```
> 
> for GNOME. As previously mentioned, ArchWiki has [a detailed page](https://wiki.archlinux.org/title/Cursor_themes#Configuration) on this topic.

Thanks, that was the case already. So, not fixed by this here under Gnome.

**Comment by sbosnick** [comment] 2021-07-31 22:00
I can reproduce this problem with Gnome 40/wayland and alacritty both from NixOS 21.05. I believe this is ultimately the NixOS problem described in this issue: NixOS/nixpkgs#22652. Specifically, NixOS does not set a "default" cursor theme even when it does install a cursor theme.

I can also reproduce the same problem with the [glutin](https://github.com/rust-windowing/glutin) `window` example as follows:

`cargo run --package glutin_examples --example window`

In both cases I can fix the problem by setting the `XCURSOR_THEME` environment variable:

`XCURSOR_THEME=Adwaita cargo run --package glutin_examples --example window`

or

`XCURSOR_THEME=Adwaita alacritty`

This same issue would likely occur on any Rust program that uses the [`winit`](https://crates.io/crates/winit) crate (Alacritty does so indirectly through the [`glutin`](https://crates.io/crates/glutin) crate) when running on NixOS using a Wayland compositor.

`winit` on Wayland uses the "system" cursor theme support in the [`smithay-client-toolkit`](https://crates.io/crates/smithay-client-toolkit/0.12.3) crate. This latter crate implements the "system" cursor theme as the theme named in the `XCURSOR_THEME` environment variable or the theme with the literal name `default`. 

As described in the NixOS issue linked above, currently NixOS does not set a theme with the literal name `default`. If `XCURSOR_THEME` is also not set then `winit` will silently fail when it tries to set any particular cursor because it will be looking in the non-existent `default` theme for that cursor.

Setting the `xcursor_theme` configuration option for Sway likely fixed the problem because it also set the `XCURSOR_THEME` environment variable. Setting the `org.gnome.desktop.interface cursor-theme` setting for Gnome likely did not fix the problem because it does not change or set the `XCURSOR_THEME` environment variable that `winit` is looking for.

A workaround for Gnome 40/wayland on NixOS 21.05 would be to set the `XCURSOR_THEME` environment variable through some other means.

I will be addressing this issue in `winit` (to not be silent when this issue occurs) and in NixOS (to provide a mechanism to configure the cursor theme named `default`).

If anyone has any information that would contradict what I have outlined here I would very much appreciate hearing about it so that I am not spinning my wheels on unnecessary upstream changes.

**Comment by m1027** [comment] 2021-08-16 19:58
> In both cases I can fix the problem by setting the `XCURSOR_THEME`
> environment variable:

[...]

> `XCURSOR_THEME=Adwaita alacritty`

WFM. Thanks!

And of course, setting this env var globally fixes the issue for any alacritty
run from a graphical laucher.

Note that while this bug report talks about Sway, I have (had) this issue under
Gnome/Wayland.

**Closed** 2022-01-02 14:29 UTC
Labels: help wanted, D - easy, H - linux, S - input, DS - Wayland

**Comment by D3vil0per** [comment] 2022-06-16 11:57
> talks

I'm having the same issue in GNOME 42/Wayland (I'm not using Sway) and I cannot solve with XCURSOR_THEME env variable. Is there another path to solve this issue?

**Comment by D3vil0per** [comment] 2022-06-16 12:16
> > talks
> 
> @m1027 I'm having the same issue in GNOME 42/Wayland (I'm not using Sway) and I cannot solve with XCURSOR_THEME env variable. Is there another path to solve this issue?

I report my solution in case someone has the same issue but not caused by Sway. It was also reported above. I `strace alacritty` and when I closed the terminal I got these logs:
```
statx(AT_FDCWD, "/home/athena/.local/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffea6d8aeb0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/athena/.icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffea6d8aeb0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/athena/.local/share/flatpak/exports/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffea6d8aeb0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/var/lib/flatpak/exports/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffea6d8aeb0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/local/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffea6d8aeb0) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/share/icons/default", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=22, ...}) = 0
openat(AT_FDCWD, "/usr/share/icons/default/index.theme", O_RDONLY|O_CLOEXEC) = 30
statx(30, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=40, ...}) = 0
lseek(30, 0, SEEK_CUR)                  = 0
read(30, "[Icon Theme]\nInherits=Bibata-Mod"..., 40) = 40
read(30, "", 32)                        = 0
close(30)                               = 0
```
In particular, it referred to `/usr/share/icons/default/index.theme"` that contained a Cursor Theme not installed on my system. I solved by deleting `index.theme` file or set it with my theme.

**Comment by akhiljalagam** [comment] 2022-08-05 18:20
fixed it on swaywm with
1. install `breeze-icons`
2. add this to sway config `exec_always swaymsg seat seat0 xcursor_theme breeze 30`
3. restart swaywm
alacritty now shows cursor.

**Comment by stevenroose** [comment] 2024-07-16 16:07
I have the same issue and none of the proposed fixes here work for me.

**Comment by k1gen** [comment] 2024-07-24 21:33
I am on NixOS as well, although on Gnome - same issue
