### ISSUE TITLE
Panic on screen unlock

### ISSUE THREAD

**Issue by blitz** [alacritty/alacritty#2156] opened 2019-03-06 16:50 UTC
Sometimes when I resume/unlock my laptop, alacritty crashes with the panic below.

Which operating system does the issue occur on?
Fedora 29 x86_64
I've built alacritty from version 9ba7c4fae4d927e109c7981f7e11ca7acdc14eb3.

If on linux, are you using X11 or Wayland?
Wayland (Gnome 3.30.2)

```
wl_registry@2: error 0: invalid global wl_output (39)
thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::expect
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:825
  10: winit::platform::platform::wayland::event_loop::EventsLoop::poll_events
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/wayland/event_loop.rs:169
  11: winit::platform::platform::EventsLoop::poll_events
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/mod.rs:504
  12: winit::EventsLoop::poll_events
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/lib.rs:273
  13: alacritty::window::Window::poll_events
             at ./src/3rd-party/alacritty/src/window.rs:208
  14: <alacritty::event::Processor<N>>::process_events
             at ./src/3rd-party/alacritty/src/event.rs:536
  15: alacritty::run
             at src/main.rs:221
  16: alacritty::main
             at src/main.rs:102
  17: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  21: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  22: main
  23: __libc_start_main
  24: _start
```

**Comment by chrisduerr** [comment] 2019-03-06 19:20
Can you reproduce this when running an example from https://github.com/tomaka/glutin? You should be able to run one simply by executing `cargo run --example window`.

**Comment by blitz** [comment] 2019-03-07 10:10
It does. See relevant part of the log plus stack trace below.

```
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: CursorLeft { device_id: DeviceId(Wayland(DeviceId)) } }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Focused(false) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Resized(LogicalSize { width: 1024.0, height: 738.0 }) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Refresh }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Resized(LogicalSize { width: 1024.0, height: 738.0 }) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Refresh }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Resized(LogicalSize { width: 1024.0, height: 738.0 }) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Refresh }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Resized(LogicalSize { width: 960.0, height: 482.0 }) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: HiDpiFactorChanged(1.0) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94488474405168))), event: Refresh }
wl_registry@2: error 0: invalid global wl_output (25)
thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::expect
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:825
  10: winit::platform::platform::wayland::event_loop::EventsLoop::poll_events
             at /home/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/wayland/event_loop.rs:169
  11: winit::platform::platform::EventsLoop::poll_events
             at /home/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/mod.rs:504
  12: winit::EventsLoop::poll_events
             at /home/julian/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/lib.rs:273
  13: window::main
             at examples/window.rs:23
  14: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by chrisduerr** [comment] 2019-03-07 21:08
Upstream issue: https://github.com/tomaka/winit/issues/705

**Comment by vberger** [comment] 2019-03-07 21:44
Could you reproduce this while running the winit example with the env variable `WAYLAND_DEBUG=1` and provide the log here?

**Comment by blitz** [comment] 2019-03-08 12:42
The relevant parts look like this. The full log is attached.

```
[1928178.111] xdg_surface@26.configure(81035)
[1928178.119]  -> xdg_surface@26.ack_configure(81035)
[1928178.124] wl_registry@2.global(78, "wl_output", 2)
[1928178.137]  -> wl_registry@2.bind(78, "wl_output", 2, new id [unknown]@34)
[1928178.162]  -> xdg_surface@26.set_window_geometry(0, -30, 960, 512)
[1928183.948]  -> wl_shm_pool@23.create_buffer(new id wl_buffer@35, 0, 960, 30, 3840, 0)
[1928183.983]  -> wl_subsurface@14.set_position(0, -30)
[1928183.992]  -> wl_surface@13.attach(wl_buffer@35, 0, 0)
[1928184.000]  -> wl_surface@13.damage_buffer(0, 0, 960, 30)
[1928184.009]  -> wl_surface@13.commit()
[1928184.013]  -> wl_shm_pool@23.create_buffer(new id wl_buffer@36, 115200, 984, 12, 3936, 0)
[1928184.027]  -> wl_subsurface@16.set_position(-12, -42)
[1928184.033]  -> wl_surface@15.attach(wl_buffer@36, 0, 0)
[1928184.040]  -> wl_surface@15.damage_buffer(0, 0, 984, 12)
[1928184.048]  -> wl_surface@15.commit()
[1928184.052]  -> wl_shm_pool@23.create_buffer(new id wl_buffer@43, 115200, 984, 12, 3936, 0)
[1928184.066]  -> wl_subsurface@18.set_position(-12, 482)
[1928184.071]  -> wl_surface@17.attach(wl_buffer@43, 0, 0)
[1928184.078]  -> wl_surface@17.damage_buffer(0, 0, 984, 12)
[1928184.087]  -> wl_surface@17.commit()
[1928184.090]  -> wl_shm_pool@23.create_buffer(new id wl_buffer@42, 115200, 12, 512, 48, 0)
[1928184.104]  -> wl_subsurface@20.set_position(-12, -30)
[1928184.109]  -> wl_surface@19.attach(wl_buffer@42, 0, 0)
[1928184.116]  -> wl_surface@19.damage_buffer(0, 0, 12, 512)
[1928184.125]  -> wl_surface@19.commit()
[1928184.128]  -> wl_shm_pool@23.create_buffer(new id wl_buffer@41, 115200, 12, 512, 48, 0)
[1928184.142]  -> wl_subsurface@22.set_position(960, -30)
[1928184.147]  -> wl_surface@21.attach(wl_buffer@41, 0, 0)
[1928184.154]  -> wl_surface@21.damage_buffer(0, 0, 12, 512)
[1928184.163]  -> wl_surface@21.commit()
WindowEvent { window_id: WindowId(Wayland(WindowId(94291192082416))), event: Resized(LogicalSize { width: 960.0, height: 482.0 }) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94291192082416))), event: HiDpiFactorChanged(1.0) }
WindowEvent { window_id: WindowId(Wayland(WindowId(94291192082416))), event: Refresh }
[1928184.207]  -> wl_buffer@47.destroy()
[1928201.973] wl_display@1.error(wl_registry@2, 0, "invalid global wl_output (75)")
wl_registry@2: error 0: invalid global wl_output (75)
thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:997:5
```

[wayland.log.gz](https://github.com/jwilm/alacritty/files/2945812/wayland.log.gz)

**Comment by vberger** [comment] 2019-03-08 13:36
Okay, as I feared, you're hitting https://github.com/Smithay/wayland-rs/issues/203 :(

**Comment by vberger** [comment] 2019-03-08 13:40
According to the exchanges that occured upstream about this issue ( see https://gitlab.freedesktop.org/wayland/wayland/issues/10 ), there is no good solution currently, except notifying Gnome about this issue so that they stop creating then deleting `wl_ouput` globals in a short timespan.

**Comment by blitz** [comment] 2019-03-16 00:15
Is there a way to work around this issue? Maybe ignoring the error? I hit the issue at least once a day.

**Comment by chrisduerr** [comment] 2019-03-16 00:41
This is a hard program crash, so there's no way to just ignore it.

However you might have some success trying to launch it using XWayland, you can do that by running Alacritty with `WAYLAND_DISPLAY= alacritty`.

**Comment by chrisduerr** [comment] 2019-11-21 22:10
@blitz Can you verify if this is still broken? It should be fixed with both the latest master and the RCs.

**Comment by hypergig** [comment] 2020-02-21 20:53
I can confirm this is still happening... or some part if it is

sway started crashing on me this week while coming out of lock/sleep, with the following in the sway logs

```
Segmentation fault (core dumped)
Releasing sleep lock 11
Got sleep lock: 12
thread 'main' panicked at 'Wayland connection lost.: Os { code: 32, kind: BrokenPipe
, message: "Broken pipe" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2020-02-21 15:28:30.647] [error] Window: Unable to receive IPC header
```

At first I believed it to be my i3status-rust bar, because that is rust, after switching out the bar for Waybar (C++) I observed the crash once again which sparked further investigation and lead me to this issue.

I didn't realize alacritty was written in rust.

**Comment by kchibisov** [comment] 2020-02-21 22:08
If sway crashing for you, it’s a sway bug.

**Comment by nixpulvis** [comment] 2020-02-22 21:36
@kchibisov `thread 'main' panicked at 'Wayland connection lost.` doesn't look like a sway crash to me. So while sway shouldn't crash, it's seemingly caused by a crash in alacritty, which also shouldn't happen.

**Comment by kchibisov** [comment] 2020-02-22 21:41
>sway started crashing on me this week while coming out of lock/sleep

@nixpulvis I read this sentence as sway crashing. If we also crashed during its crash I don't mind this crash. As you can see an issue that connection to sway was lost.

If we crash after screen unlock but everything else continues to run, then it's our issue.

**Comment by vberger** [comment] 2020-02-22 21:47
> @kchibisov `thread 'main' panicked at 'Wayland connection lost.` doesn't look like a sway crash to me. So while sway shouldn't crash, it's seemingly caused by a crash in alacritty, which also shouldn't happen.

I interpret this as alacritty crashing as a consequence of sway crashing, rather than the other way around.

In any case, if sway crashes, then there is a sway bug worth reporting to them. An ill-behaving wayland client should not be able to crash the compositor.

**Comment by primeos** [comment] 2020-04-13 14:39
Some (but not all) of my Alacritty instances are crashing on Sway from time to time when I focus them (they basically crash instantly after I switch to them). Unfortunately I didn't find a way to reproduce these crashes yet :o

Example console outputs from my last few Alacritty crashes:
```
Mar 18 20:31:00 jarvis sway[1338]: thread 'main' panicked at 'Wayland connection lost.: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1188:5
Mar 18 20:31:00 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Mar 18 20:31:01 jarvis sway[1338]: wl_registry@2: error 0: invalid global wl_output (35)
Mar 18 20:31:01 jarvis sway[1338]: thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
Mar 18 20:31:01 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Mar 18 20:31:01 jarvis sway[1338]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
[...]
Apr 06 15:56:30 jarvis sway[1338]: wl_registry@2: error 0: invalid global wl_output (40)
Apr 06 15:56:30 jarvis sway[1338]: thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
Apr 06 15:56:30 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Apr 06 15:56:30 jarvis sway[1338]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
Apr 06 15:57:48 jarvis sway[1338]: wl_registry@2: error 0: invalid global wl_output (40)
Apr 06 15:57:48 jarvis sway[1338]: thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
Apr 06 15:57:48 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Apr 06 15:57:48 jarvis sway[1338]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
[...]
Apr 09 13:03:51 jarvis sway[1338]: wl_registry@2: error 0: invalid global wl_output (42)
Apr 09 13:03:51 jarvis sway[1338]: thread 'mainthread '' panicked at '<unnamed>Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }' panicked at '', called `Result::unwrap()` on an `>
Apr 09 13:03:51 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[...]
Apr 13 15:41:16 jarvis sway[1338]: wl_registry@2: error 0: invalid global wl_output (45)
Apr 13 15:41:16 jarvis sway[1338]: thread 'main' panicked at 'Wayland connection lost.: Os { code: 71, kind: Other, message: "Protocol error" }', src/libcore/result.rs:1188:5
Apr 13 15:41:16 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Apr 13 15:41:42 jarvis sway[1338]: Deleted log file at "/tmp/Alacritty-15978.log"
Apr 13 15:41:42 jarvis sway[1338]: wl_registry@2: error 0: invalid global wl_output (45)
Apr 13 15:41:42 jarvis sway[1338]: thread 'main' panicked at 'failed to dispatch wayland events: Os { code: 71, kind: Other, message: "Protocol error" }', /build/alacritty-0.4.2-vendor.tar.gz/winit/src/platform_>
Apr 13 15:41:42 jarvis sway[1338]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Unfortunately I didn't use `WAYLAND_DEBUG` and `RUST_BACKTRACE` when those crashes occurred.

Regarding my setup: At least the last crash was with Alacritty 0.4.2, Sway 1.4, Wayland 1.18, and `wayland-protocols` 1.20.

**Comment by ocehugo** [comment] 2020-07-02 08:37
This is still happening in 0.4.2 and I got a slightly different behaviour - full lock on the wm (sway) - and no way to get out.

I will probably turn on RUST_BACKTRACE and see if I'm unlucky again!

Useful log part from sway:
```
2020-07-02 18:11:56 - [sway/tree/arrange.c:263] Usable area for ws: 1920x1060@0,0
2020-07-02 18:11:56 - [sway/tree/arrange.c:293] Arranging workspace '10' at 3845.000000, 1085.000000
2020-07-02 18:11:56 - [sway/desktop/transaction.c:411] Transaction 0x55c9bb5e6030 committing with 8 instructions
2020-07-02 18:11:56 - [sway/desktop/transaction.c:489] Transaction 0x55c9bb5e6030 is ready
2020-07-02 18:11:56 - [sway/desktop/transaction.c:280] Applying transaction 0x55c9bb5e6030
thread 'main' panicked at 'failed to read wayland events: Broken pipe (os error 32)', /var/tmp/portage/x11-terms/alacritty-0.4.2/work/cargo_home/gentoo/winit-0.22.0/src/platform_impl/linux/wayland/event_loop.rs:486:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
/usr/bin/remmina-file-wrapper.sh: line 24: 13202 Terminated              /usr/bin/remmina "${@}"
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
thread 'main' panicked at 'Wayland connection lost.: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'failed to read wayland events: Broken pipe (os error 32)', /var/tmp/portage/x11-terms/alacritty-0.4.2/work/cargo_home/gentoo/winit-0.22.0/src/platform_impl/linux/wayland/event_loop.rs:486:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Exiting due to channel error.
Exiting due to channel error.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1188:5
Exiting due to channel error.
thread 'thread 'mainmain' panicked at '' panicked at 'Wayland connection lost.: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }Wayland connection lost.: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', ', src/libcore/result.rssrc/libcore/result.rs::wl_display_dispatch: Broken pipe
11881188::55

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'failed to read wayland events: Broken pipe (os error 32)', /var/tmp/portage/x11-terms/alacritty-0.4.2/work/cargo_home/gentoo/winit-0.22.0/src/platform_impl/linux/wayland/event_loop.rs:486:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', src/libcore/result.rs:1188:5
wl_display_dispatch: Broken pipe
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1188:5
```

**Comment by kchibisov** [comment] 2020-07-02 09:04
Are you running sway master + wlroots master? If not , please, try to repro on them.

**Comment by Arnavion** [comment] 2020-07-25 22:32
I'm hitting this with alacritty 0.4.3 in sway 1.5 + wlroots 0.11.0. Here's a relevant snippet of the crash and preceding events with `WAYLAND_DEBUG=1`:

```
# monitor turned off here

wl_registry@42.global_remove(67)

...

# monitor turned on here

main.c:299] Found config DP-2 for output DP-2 (Dell

...

wl_registry@2.global(67, "wl_output", 3)
 -> wl_registry@2.bind(67, "wl_output", 3,
wl_registry@2.global_remove(67)
wl_display@1.error(wl_registry@2, 0, "invalid global wl_output (67)")
wl_registry@2: error 0: invalid global wl_output (67)
```

Given sway 1.5 and wlroots 0.11.0 are pretty recent, I assume sway master / wlroots master would not help either.

---

With alacritty master (9a4d847d897016ac3f1662fec45d372b879072cd) I've been trying to repro for some time and have been unable to. It was random originally so I can't be completely sure it's fixed, but it took fewer attempts to repro it with 0.4.3 than I've made unsuccessfully with master.

**Comment by Arnavion** [comment] 2020-08-16 07:24
I've not seen this any more with alacritty 0.5.0

**Comment by chrisduerr** [comment] 2020-08-16 16:02
Can someone confirm that this is still happening?

**Comment by kchibisov** [comment] 2020-11-09 08:31
If someone will have similar issue, please open a new one. Closing this one due to inactivity.

**Closed by kchibisov** 2020-11-09 08:31 UTC
Labels: A - deps, B - crash, DS - Wayland
