### ISSUE TITLE
Better unicode box drawing unicode characters rendering

### ISSUE THREAD

**Issue by Bekaboo** [alacritty/alacritty#7067] opened 2023-07-10 05:18 UTC
### System

OS: Linux
Version: alacritty 0.12.2 (9d9982df)
Linux/BSD: X11, KDE

Hi, first of all thanks for making this terminal, I've used it in the past year and it has always the fastest and most responsive terminal I've ever used.

However, I find that the rendering of these two box-drawing unicodes is not ideal comparing to other terminals:

- Box Drawings Light Diagonal Upper Left to Lower Right:  ╲
- Box Drawings Light Diagonal Upper Right to Lower Left:  ╱

How it looks like in Alacritty:

![image](https://github.com/alacritty/alacritty/assets/76579810/093c84e5-5288-4b90-be14-2840294c8bd4)

In Kitty:

![image](https://github.com/alacritty/alacritty/assets/76579810/893c5d4e-e79f-4bdb-99b4-a084b9092581)

In Wezterm:

![image](https://github.com/alacritty/alacritty/assets/76579810/8bef1752-1eb3-4f82-91f5-111440208a50)

In Konsole:

![image](https://github.com/alacritty/alacritty/assets/76579810/806ff226-4690-476a-9a81-65b55c10aacf)

In my opinion the rendering in Kitty and Wezterm looks the best (the slash is too bold in Konsole). Can alacritty draw these two unicodes in a way that looks like Kitty & Wezterm? Thanks!

**Comment by kchibisov** [comment] 2023-07-10 05:23
Duplicate of #6529.

**Closed by kchibisov** 2023-07-10 05:23 UTC

**Comment by Bekaboo** [comment] 2023-07-10 05:28
@kchibisov Thanks for quick response. I read the #6529 and noticed that `font.builtin_box_drawing` is enabled by default, so from my understanding there's something alacritty can do to align these characters, is that true?

**Comment by kchibisov** [comment] 2023-07-10 10:11
@Bekaboo correct, it could be possible to do that just fine.
