### ISSUE TITLE
Minor powerline font rendering issues

### ISSUE THREAD

**Issue by MichaelAquilina** [alacritty/alacritty#2693] opened 2019-08-01 15:16 UTC
Which operating system does the issue occur on? Linux

If on linux, are you using X11 or Wayland? Wayland (But also occurs when I run `env WINIT_UNIX_BACKEND=x11 alacritty`)

I found a very minor font rendering issues with powerline fonts. If you look closely enough you'll see that each found is sorrounded by very thin lines - almost like the glyph is missaligned in some way. Hopefully the screenshot makes this issue clear enough:

![2019-08-01_16-10-15](https://user-images.githubusercontent.com/2650040/62305094-2799a780-b477-11e9-926d-2e0af9de23b4.png)

Take a look at the beginning and end of each powerline segment, you should be able to see a very thin vertical line. You should also notice that the end segment (> part) is slightly missaligned with the previous segments.

Update: found an example where it looks more obvious:
![2019-08-01_17-31-17](https://user-images.githubusercontent.com/2650040/62310816-3d609a00-b482-11e9-8363-9b3d41a17100.png)

**Comment by kchibisov** [comment] 2019-08-01 15:36
I kinda can reproduce this, the small lines has exactly the same colors, as on your picture. This issue can be reproduce by posting block cursor over `` or to the left of this char. However it's worth testing this issue on other platforms (macOs/windows) first.

**Comment by chrisduerr** [comment] 2019-08-01 15:38
If you're using a separate font for powerline symbols, this is to be expected. Most powerline setups have slight missalignments due to the hacky nature of how the arrows are drawn.

**Comment by kchibisov** [comment] 2019-08-01 16:00
@chrisduerr I've tested with multiple fonts and with font that have this glyph natively(`Fira Code`). The problems are identical across all of them.

On my system if the font doesn't have this glyph it won't be rendered at all, so I'm sure, that glyph is presented in fonts I'm testing.

Also it doesn't happen in other terminal emulators with `freetype` (kitty) and gnome-terminal(which links to freetype, but I'm not sure about this one).

**Comment by MichaelAquilina** [comment] 2019-08-01 16:17
@chrisduerr as mentioedn by @kchibisov, I've not noticed these issues in other terminals. For example:

*Termite*
![2019-08-01_17-14-14](https://user-images.githubusercontent.com/2650040/62309688-e78af280-b47f-11e9-8924-af2e210170d8.png)

*Tilix*
![2019-08-01_17-16-10](https://user-images.githubusercontent.com/2650040/62309808-1608cd80-b480-11e9-8cc8-d945fafa2629.png)

**Comment by chrisduerr** [comment] 2019-08-01 17:11
> @chrisduerr as mentioned by @kchibisov, I've not noticed these issues in other terminals.

Powerline glyphs are extremely dependent on the exact way things are rendered, including font size and other rendering parameters.

Something you can try though is setting the x glyph offset to -1.

**Comment by kchibisov** [comment] 2019-08-01 17:16
> Something you can try though is setting the x glyph offset to -1.

This fixes the problem.

> Powerline glyphs are extremely dependent on the exact way things are rendered, including font

FYI, I've tried different font sizes/rendering options(hinting) and the issue was the same.

**Comment by MichaelAquilina** [comment] 2019-08-01 17:19
`x: -1` solves most of the issue for me (but the (>) still looks slightly misaligned. I tried different values of y (1 and -1) but this seemed to make the issue worse which makes me think the font is just not aligned correctly (even though this doesnt present itself in other terminals).

fwiw, it currently looks like this:

![2019-08-01_18-18-36](https://user-images.githubusercontent.com/2650040/62313489-ce3a7400-b488-11e9-9115-784071553d00.png)

You can see a pixel offset at the top and bottom of the > character (beginning and end of the prompt)

**Comment by chrisduerr** [comment] 2019-08-01 18:32
Which fonts are you using for powerline symbols and monospace text?

**Comment by kchibisov** [comment] 2019-08-01 18:36
Fira Code for both (from arch repo).

**Comment by MichaelAquilina** [comment] 2019-08-01 18:53
I'm using monospace fonts. I *thought* I had the `powerline` package from opensuse installed so it seems like this font has these builtin? (I'm finding this hard to believe myself)

**Comment by spaun2002** [comment] 2019-09-06 21:38
Setting the glyph_offset x: -1 helps with the right arrows, but does not help with the left ones:
![image](https://user-images.githubusercontent.com/980965/64461862-54169400-d0b3-11e9-95b3-311321d8b221.png)
But setting the offset x: -1 surprisingly helped:
![image](https://user-images.githubusercontent.com/980965/64462024-e880f680-d0b3-11e9-8116-0817efbf7322.png)
But you may see the text becomes more condensed (obviously)

**Comment by chrisduerr** [comment] 2019-09-08 18:04
Since Alacritty does not handle proportional fonts and every glyph is rendered at the same width, it will cause problems if you try to use a glyph which does not have the same width as the monospace font you're primarily using.

I'd assume that's what is going on here, which is one of the reasons why this way of rendering powerlines is such a troublesome idea. As soon as a mismatch between two fonts exists in regards to font size vs glyph bounding box, there will be inconsistencies.

The difference in height in your glyphs @MichaelAquilina seems to indicate that the powerline font is not the same font as your primary font, so that's probably causing the issue.

The best bet is to use a monospace font which has powerline symbols included, however even then success isn't guaranteed. But it should help a bit.

**Comment by Mr-Figs** [comment] 2019-09-09 02:38
I solved this issue on my machine by setting font anti-aliasing to grayscale (as opposed to RGBA/subpixel rendering). No anti-aliasing also works, but looks awful. I'm running Linux Mint, X11, gnome-terminal, Source Code Pro. Fontconfig, not patched fonts.

Top to bottom: no anti-aliasing, grayscale, RGBA.
![anti-aliasing](https://user-images.githubusercontent.com/8206263/64499621-c8a22c00-d287-11e9-8ffc-d27997a8cf2c.png)

Changing the subpixel order alters the pattern as well. Top to bottom: RGB, BGR, vertical RGB, vertical BGR:
![subpixel order](https://user-images.githubusercontent.com/8206263/64499820-9e9d3980-d288-11e9-919d-6f38196a21de.png)

The tip of the arrow appears vertically misaligned in all configurations, but it is hard to notice (especially with grayscale AA). The lines only appear in one case, RGB subpixel AA (shown twice).

I'm content to use grayscale rendering (I can't tell the difference) but others might want to experiment with different colors possibly. I didn't notice any effect from turning hinting on or off. Either way, it seems like subpixel rendering is "moving" some of the glyphs off to the side slightly.

**Comment by Sherulez** [comment] 2020-02-11 11:16
I tried on `Tilix`, `GnomeT`, `Termite`, `Konsole`, `Alacritty `and `Kitty`, each terminal has a different way of rendering its content. And so, each terminal has different problems with Powerline. 

For me, only Kitty manages without error any Nerd Font at any size.
![Capture](https://user-images.githubusercontent.com/25638207/74231992-27048800-4cc8-11ea-87b9-45c6083f94c8.PNG)


_Taking inspiration from how Kitty achieves this could be interesting, I guess._

**Comment by chrisduerr** [comment] 2020-02-11 14:22
> Taking inspiration from how Kitty achieves this could be interesting, I guess.

I'm not sure about powerline glyphs, but iirc Kitty draws its own emojis for example which definitely doesn't sound like a good idea. It's possible it does the same for powerline symbols.

I know that VTE (gnome-terminal, Termite, Tilix) also draws some characters itself rather than relying on the font, though probably not powerline symbols.

So with a lot of terminals that perform surprisingly well here, it's possible that they're just cheating. I personally don't think there's any point in implementing a workaround like this and it would only cause troubles.

**Comment by Sherulez** [comment] 2020-02-11 15:41
> I personally don't think there's any point in implementing a workaround like this and it would only cause troubles.

True :)
Indeed some terminal emulator must "cheat" to hide font errors.

Fonts play a very important role in this kind of problem.
Take for example the arrow (\ue0b0), 

1. not all fonts from "Nerd Fonts" have exactly the same.
2. almost none of them are "powerline ready"


Take for example 

"DroidSansMono Nerd Font Mono" 
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DroidSansMono
**vs** 
"Droid Sans Mono for Powerline" 
https://github.com/powerline/fonts/tree/master/DroidSansMono

![Capture3](https://user-images.githubusercontent.com/25638207/74251548-97250500-4cec-11ea-9c7f-8585b60beab0.PNG)
![Capture2](https://user-images.githubusercontent.com/25638207/74251551-97bd9b80-4cec-11ea-82a2-4f58a85e6bdd.PNG)
![Capture](https://user-images.githubusercontent.com/25638207/74251553-98563200-4cec-11ea-848e-010402663ff4.PNG)


the "for Powerline" version still need some tweaking at the bottom level but we can already see that the sub pixel line has disappeared. I will end up patching these arrows myself via fontforge <_>

**Comment by rubiin** [comment] 2020-02-16 09:15
i cannot use powerline fonts too, here is my config :
```
# Configuration for Alacritty, the GPU enhanced terminal emulator

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color-italic

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels. If both are zero this
  # setting is ignored.
  dimensions:
    columns: 100
    lines: 75

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is not scaled by
  # DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations: full

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Windowed

scrolling:
  # maximum number of lines in the scrollback buffer. Specifying '0' will
  # disable scrolling.
  history: 0

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Scroll to the bottom when new text is written to the terminal.
  auto_scroll: false

# Display tabs using this many cells (changes require restart)
#
# Some applications, like Emacs, rely on knowing about the width of a tab. To
# prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
#
tabspaces: 8

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: "Droid Sans Mono Slashed for Powerline"
    # family: "Fira Code"
    # family: "Source Code Pro"
    # style: Retina

  # The bold font face
  #bold:
    #family: Inconsolata for Powerline
    # family: "Fira Code"
    # family: "Source Code Pro"

  # The italic font face
  #italic:
    #family: Inconsolata for Powerline
    # family: "Fira Code"
    # family: "Source Code Pro"
    # style: "Medium Italic"

  # Point size of the font
  size: 12.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina you
  # probably want this set to false.
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: true

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
# custom_cursor_colors: false

# Colors
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xffffff'

  # Colors that should be used to draw the terminal cursor. If these are unset,
  # the cursor colour will be the inverse of the cell colour.
  # cursor:
  #   text: '0x2e2e2d'
  #   # text: '0x000000'
  #   cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xc62828'
    green:   '0x558b2f'
    yellow:  '0xf9a825'
    blue:    '0x1565c0'
    magenta: '0x6a1e9a'
    cyan:    '0x00838f'
    white:   '0xf2f2f2'

  # Bright colors
  bright:
    black:   '0x545454'
    red:     '0xef5350'
    green:   '0x8bc34a'
    yellow:  '0xffeb3b'
    blue:    '0x64b5f6'
    magenta: '0xba68c8'
    cyan:    '0x26c6da'
    white:   '0xe0e0e0'

  # Dim colors (Optional)
  dim:
    black:   '0x333333'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xdddddd'

  # Tomorrow Night Bright
  # primary:
  #   background: '0x000000'
  #   foreground: '0xeaeaea'
  #
  # cursor:
  #   text: '0x000000'
  #   cursor: '0xffffff'
  #
  # normal:
  #   black:   '0x000000'
  #   red:     '0xd54e53'
  #   green:   '0xb9ca4a'
  #   yellow:  '0xe6c547'
  #   blue:    '0x7aa6da'
  #   magenta: '0xc397d8'
  #   cyan:    '0x70c0ba'
  #   white:   '0xffffff'
  #
  # bright:
  #   black:   '0x666666'
  #   red:     '0xff3334'
  #   green:   '0x9ec400'
  #   yellow:  '0xe7c547'
  #   blue:    '0x7aa6da'
  #   magenta: '0xb77ee0'
  #   cyan:    '0x54ced6'
  #   white:   '0xffffff'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  indexed_colors: []

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0

# Background opacity
background_opacity: 1.0

# Key bindings
#
# Key bindings are specified as a list of objects. Each binding will specify a
# key and modifiers required to trigger it, terminal modes where the binding is
# applicable, and what should be done when the key binding fires. It can either
# send a byte sequence to the running application (`chars`), execute a
# predefined action (`action`) or fork and execute a specified command plus
# arguments (`command`).
#
# Bindings are always filled by default, but will be replaced when a new binding
# with the same triggers is defined. To unset a default binding, it can be
# mapped to the `None` action.
#
# Example:
#   `- { key: V, mods: Control|Shift, action: Paste }`
#
# Available fields:
#   - key
#   - mods (optional)
#   - chars | action | command (exactly one required)
#   - mode (optional)
#
# Values for `key`:
#   - `A` -> `Z`
#   - `F1` -> `F12`
#   - `Key1` -> `Key0`
#
#   A full list with available key codes can be found here:
#   https://docs.rs/glutin/*/glutin/enum.VirtualKeyCode.html#variants
#
#   Instead of using the name of the keys, the `key` field also supports using
#   the scancode of the desired key. Scancodes have to be specified as a
#   decimal number.
#   This command will allow you to display the hex scancodes for certain keys:
#     `showkey --scancodes`
#
# Values for `mods`:
#   - Command
#   - Control
#   - Option
#   - Super
#   - Shift
#   - Alt
#
#   Multiple `mods` can be combined using `|` like this: `mods: Control|Shift`.
#   Whitespace and capitalization is relevant and must match the example.
#
# Values for `chars`:
#   The `chars` field writes the specified string to the terminal. This makes
#   it possible to pass escape sequences.
#   To find escape codes for bindings like `PageUp` ("\x1b[5~"), you can run
#   the command `showkey -a` outside of tmux.
#   Note that applications use terminfo to map escape sequences back to
#   keys. It is therefore required to update the terminfo when
#   changing an escape sequence.
#
# Values for `action`:
#   - Paste
#   - PasteSelection
#   - Copy
#   - IncreaseFontSize
#   - DecreaseFontSize
#   - ResetFontSize
#   - ScrollPageUp
#   - ScrollPageDown
#   - ScrollLineUp
#   - ScrollLineDown
#   - ScrollToTop
#   - ScrollToBottom
#   - ClearHistory
#   - Hide
#   - Quit
#   - ClearLogNotice
#   - SpawnNewInstance
#   - ToggleFullscreen
#   - None
#
# Values for `action` (macOS only):
#   - ToggleSimpleFullscreen: Enters fullscreen without occupying another space
#
# Values for `command`:
#   The `command` field must be a map containing a `program` string and
#   an `args` array of command line parameter strings.
#
#   Example:
#       `command: { program: "alacritty", args: ["-e", "vttest"] }`
#
# Values for `mode`:
#   - ~AppCursor
#   - AppCursor
#   - ~AppKeypad
#   - AppKeypad
#
key_bindings:
  - { key: V,        mods: Command,       action: Paste                        }
  - { key: C,        mods: Command,       action: Copy                         }
  - { key: Q,        mods: Command,       action: Quit                         }
  - { key: N,        mods: Command,       action: SpawnNewInstance             }
  - { key: Return,   mods: Command,       action: ToggleFullscreen             }

  - { key: Home,                          chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                          chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                           chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                           chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: Equals,   mods: Command,       action: IncreaseFontSize             }
  - { key: Minus,    mods: Command,       action: DecreaseFontSize             }
  - { key: Minus,    mods: Command|Shift, action: ResetFontSize                }
  - { key: PageUp,   mods: Shift,         chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control,       chars: "\x1b[5;5~"                   }
  - { key: PageUp,                        chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,         chars: "\x1b[6;2~"                   }
  - { key: PageDown, mods: Control,       chars: "\x1b[6;5~"                   }
  - { key: PageDown,                      chars: "\x1b[6~"                     }
  - { key: Left,     mods: Shift,         chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control,       chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,           chars: "\x1b[1;3D"                   }
  - { key: Left,                          chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                          chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,         chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control,       chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,           chars: "\x1b[1;3C"                   }
  - { key: Right,                         chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                         chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,         chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control,       chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,           chars: "\x1b[1;3A"                   }
  - { key: Up,                            chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                            chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,         chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control,       chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,           chars: "\x1b[1;3B"                   }
  - { key: Down,                          chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                          chars: "\x1bOB",   mode: AppCursor   }
  - { key: Tab,      mods: Shift,         chars: "\x1b[Z"                      }
  - { key: F1,                            chars: "\x1bOP"                      }
  - { key: F2,                            chars: "\x1bOQ"                      }
  - { key: F3,                            chars: "\x1bOR"                      }
  - { key: F4,                            chars: "\x1bOS"                      }
  - { key: F5,                            chars: "\x1b[15~"                    }
  - { key: F6,                            chars: "\x1b[17~"                    }
  - { key: F7,                            chars: "\x1b[18~"                    }
  - { key: F8,                            chars: "\x1b[19~"                    }
  - { key: F9,                            chars: "\x1b[20~"                    }
  - { key: F10,                           chars: "\x1b[21~"                    }
  - { key: F11,                           chars: "\x1b[23~"                    }
  - { key: F12,                           chars: "\x1b[24~"                    }
  - { key: Back,                          chars: "\x7f"                        }
  - { key: Back,     mods: Alt,           chars: "\x1b\x7f"                    }
  - { key: Insert,                        chars: "\x1b[2~"                     }
  - { key: Delete,                        chars: "\x1b[3~"                     }

    # shortcuts for tmux. the leader key is control-b (0x02)
  - { key: W,        mods: Command,       chars: "\x02&"                       }  # close tab (kill)
  - { key: T,        mods: Command,       chars: "\x02c"                       }  # new tab
  - { key: RBracket, mods: Command|Shift, chars: "\x02n"                       }  # select next tab
  - { key: LBracket, mods: Command|Shift, chars: "\x02p"                       }  # select previous tab
  - { key: RBracket, mods: Command,       chars: "\x02o"                       }  # select next pane
  - { key: LBracket, mods: Command,       chars: "\x02;"                       }  # select last (previously used) pane
  - { key: F,        mods: Command,       chars: "\x02/"                       }  # search (upwards) (see tmux.conf)

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  # URL launcher
  #url:
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    #
    # When set to `None`, URL launching will be disabled completely.
    #
    # Default:
    #   - (macOS) open
    #   - (Linux) xdg-open
    #   - (Windows) explorer
    # launcher:
    #   program: xdg-open
    #   args: []

    # These are the modifiers that need to be held down for opening URLs when clicking
    # on them. The available modifiers are documented in the key binding section.
    # modifiers: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

# Mouse bindings
#
# Available fields:
# - mouse
# - action
# - mods (optional)
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# dynamic_title: false

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#shell:
  #program: /bin/zsh
  # args:
  #   - --command=tmux

debug:
  # Should display the render timer
  render_timer: false

  # Keep the log file after quitting Alacritty.
  persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  log_level: None

  # Print all received window events.
  print_events: false

  # Record all characters and escape sequences as test data.
  ref_test: false

# vim: nospell

```

**Comment by nixpulvis** [comment] 2020-02-22 20:26
> Indeed some terminal emulator must "cheat" to hide font errors.

FWIW, not cheating has a strong motivation aside from just the work involved maintaining these workarounds. If we coverup font errors, they'll never be discovered and fixed. I'm not sure exactly what's wrong with powerline fonts (I don't use them), so this is more of a general statement.

**Comment by kchibisov** [comment] 2020-02-22 20:42
Agree with @nixpulvis here, we should do whatever fonts tell us to do, since font file is a source of truth, not Z's app rendering engine, etc.

**Comment by Thorhian** [comment] 2020-03-02 22:57
Is there a way I could help? I currently use Alacritty on my laptop but it forces me to keep my font size at a relatively large size in order to avoid these issues. I use ZSH with PowerLevel10K with their recommended font at the moment. I use a similar setup on my desktop but I use Konsole instead and I have managed to get a smaller font size to render properly on there lol, so I haven't switched yet. I'd like to, and I'd like to help if I can. I'm just not sure how.

**Comment by iamjamestl** [comment] 2020-08-17 23:41
Hi folks.  If you use a well-designed powerline-compatible font like DejaVu, Menlo, Fantasque, Terminus, or Hack, please consider trying my patch from https://github.com/alacritty/crossfont/pull/6.  Other fonts may [require redesign](https://github.com/source-foundry/Hack/pull/234) work to be completely seamless horizontally.  I hope you will find the powerline separators render correctly at all sizes without any offsets configured, just like every other major terminal.  Just add

```
[patch.crates-io]
crossfont = { git = "https://github.com/iamjamestl/crossfont.git", branch = "fix-ft-glyph-height" }
```

to your alacritty clone's top level `Cargo.toml` and run `cargo build`.  I would be interested to know how it goes, though it looks like it may be an uphill battle on the code review front.

**Comment by chrisduerr** [comment] 2020-08-17 23:48
Feel free to leave feedback even if you do not use a well-designed powerline font. Since that PR changes around metrics for everyone.

**Comment by Congee** [comment] 2021-02-19 19:56
FWIW, there isn't a perfect solution for Cascadia Code 2102.3 that has powerline symbols included. Setting `glyph_offset` does not help; setting `offset.y` works but it causes a spacing too big problem to me.

 https://github.com/microsoft/cascadia-code/releases/tag/v2102.03

**Comment by Amparose** [comment] 2021-04-13 12:14
> Is there a way I could help? I currently use Alacritty on my laptop but it forces me to keep my font size at a relatively large size in order to avoid these issues. I use ZSH with PowerLevel10K with their recommended font at the moment. I use a similar setup on my desktop but I use Konsole instead and I have managed to get a smaller font size to render properly on there lol, so I haven't switched yet. I'd like to, and I'd like to help if I can. I'm just not sure how.

I am in this boat too; did you ever work out how to fix it for p10k and the recommended MesloLGS NF font? It seems to render perfectly in iTerm2, which doesn't mean much other than "it can work somehow".

**Comment by chrisduerr** [comment] 2021-04-13 12:16
Many other terminals render glyphs by themselves, Alacritty doesn't. You can try to mess with glyph metrics but this isn't exactly how fonts are designed to be used.

**Closed by chrisduerr** 2021-04-13 12:16 UTC
Labels: H - linux, S - font

**Comment by g6ai** [comment] 2021-04-13 14:19
@chrisduerr Are you saying Alacritty is onto a more revolutionary path, that the fonts should be designed with better metrics, but the terminal emulator should not deal with the compatility of most existent fonts? If that's the case, I think it could be helpful to recommend a well-patched MesloLGS NF font in the Alacritty homepage.

**Comment by chrisduerr** [comment] 2021-04-13 20:23
I'd expect monospace fonts to provide the correct metrics, correct. Which fonts you use I don't care about. Powerline will never work perfectly for everyone anyways though if you're just using fonts, simply because the whole idea is broken.
