### ISSUE TITLE
fzf border is ugly.

### ISSUE THREAD

**Issue by Rintse** [alacritty/alacritty#5679] opened 2021-12-11 23:06 UTC
The fzf.vim plugin border is not rendered as I am used to for some reason.

On konsole, it looks like:
![konsole](https://user-images.githubusercontent.com/22935110/145694172-67b11d5a-e566-41fa-a82b-e81080bf1357.png)

While on alacritty it looks like:
![alacritty](https://user-images.githubusercontent.com/22935110/145694176-6a70047a-fbd4-4dbb-ae5b-d379b384bfe5.png)

Both consoles are using the same Ubuntu Mono Nerd Font. In the screenshot, the font sizes are slightly different, but this does not change the issue.

Obviously not a terrible bug, but it makes me wonder whether I have configured something wrong.

### System
OS: KDE Neon 5.23
Version: alacritty 0.10.0-dev
Linux/BSD: X11, KDE

**Comment by chrisduerr** [comment] 2021-12-12 01:19
Duplicate of https://github.com/alacritty/alacritty/issues/5485.

**Closed by chrisduerr** 2021-12-12 01:19 UTC
