### ISSUE TITLE
Resizing vim with split window under WSL causes color for terminal to become permanently broken

### ISSUE THREAD

**Issue by vlovich** [alacritty/alacritty#2852] opened 2019-10-05 00:52 UTC
Which operating system does the issue occur on? Windows 10 Build 17763 WSL 1 with Ubuntu 18.10 with bash.exe

Have tried both native vim.exe & Ubuntu native vim. When launched from bash.exe:
1. Launch vim
2. Ctrl-w v or Ctrl-w S to split
3. Resize alacritty

Expected: Vim redrawn correctly. Upon exit default bash window drawn.
Actual: Alacritty makes the whole background white (or yellow or blue - depends on the contents of what Vim drew). On exit the color scheme retains. Additionally scrolling back in the backbuffer results in seeing weird intermediary states of Vim instead of the previous commands.

**Comment by chrisduerr** [comment] 2019-10-05 01:10
Are you using WinPTY or ConPTY? And which terminfo have you set?

**Comment by vlovich** [comment] 2019-10-05 01:17
Both WinPTY & ConPTY are impacted. TERM is set to xterm-256color but otherwise not sure what you mean by "which terminfo have you set".

**Comment by chrisduerr** [comment] 2019-10-05 01:18
Could you share a screenshot of the issue? If you can see vim after leaving it when scrolling up, that would indicate that the alt screen isn't entered, which likely means there could be some terminfo querying issues.

**Comment by chrisduerr** [comment] 2019-10-05 01:20
Just fyi, I'm asking about `TERM` since it sounds a bit like https://github.com/jwilm/alacritty/issues/2766. So setting the `TERM` to `cygwin` would be worth a shot.

**Comment by vlovich** [comment] 2019-10-05 01:20
Attached a video recording of the issue. Sometimes can see it when scrolling up sometimes not.

[alacritty2852.zip](https://github.com/jwilm/alacritty/files/3692744/alacritty2852.zip)

**Comment by vlovich** [comment] 2019-10-05 01:21
Same problem with TERM=cygwin.

**Comment by vlovich** [comment] 2019-10-05 01:27
NOTE: I'm unable to get alacritty to launch bash.exe with anything other than xterm-256color even though alacritty is setting it to cygwin (i.e. I launch alacritty with cmd.exe as the shell & then launch bash manually).

**Comment by vlovich** [comment] 2019-10-05 01:29
Even if I set TERM to garbage & vim launches without colors alacritty still fails in the same way.

**Comment by vlovich** [comment] 2019-10-05 01:30
I'm using the last release of alacritty (not from source).

**Comment by vlovich** [comment] 2019-10-05 01:42
Oh & this can be easily reproduced even without VIM. Set the PS1 to have colors:

`
PS1='\[\033[01;31m\]\[\033[00m\]\[\033[01;34m\]\w\[\033[00m\] \[\033[01;30m\][\[\033[01;32m\]this is a very long PS1 string blah blah blah blah\[\033[01;30m\]]\[\033[00m\]\$'
`

Then type the character `a` (don't hit enter) and resize the window to be very small & then very large. Notice that the "a" is now grey & all user input remains grey although PS1 is fine.

**Comment by tactlessfish** [comment] 2020-10-26 03:17
Can reproduce (Windows 10 Build 19041.450 / WSL2 Ubuntu 20.04 LTS). Setting TERM to cygwin fixes the colors, but not the scrolling back issue.

**Comment by tactlessfish** [comment] 2020-10-27 00:11
Looks like this affects the Windows Terminal as well.
[Weird blue selection after closing neovim (WSL)](https://github.com/microsoft/terminal/issues/3848)

**Comment by chrisduerr** [comment] 2020-10-27 20:58
Thanks for checking. This means that this is a ConPTY issue and not an Alacritty bug. Thus there's nothing we can do about it here.

**Closed by chrisduerr** 2020-10-27 20:58 UTC
Labels: A - needs repro, H - windows
