### ISSUE TITLE
Alacritty Freeses on Wayland

### ISSUE THREAD

**Issue by zeyadtamimi** [alacritty/alacritty#7490] opened 2023-12-29 00:27 UTC
Hey,

After a recent upgrade I am starting to notice that Alacrity constantly freezes on my system, It happens somewhat randomly but I have been able to reproduce it by interacting with electron apps such as discord.

I am running Arch Linux with Hyprland and running the latest version of alacritty using the `alacrity-git` AUR package: `alacritty 0.14.0-dev (81df32af)`

I have noticed this happen a couple of days ago before the current release.

I can't really provide you with any logs because nothing really crashes. Instead, when this condition hits ( I really have no idea what exactly triggers it ) all spawned alacritty terminals will freeze and no longer update any of their renders

The bellow screenshot shows me trying to resize the window:
![2023-12-28_16-19](https://github.com/alacritty/alacritty/assets/14227029/03a951fe-f6a8-4b36-b5ab-2ccd1924de07)

Notice the background which shows what the text should be, the `htop` window appears to no longer re-render.

Opening a new terminal after the freeze I can see that the process spawned by the terminal is still alive:
```
> ps -a | grep htop
132689 pts/0    00:00:08 htop
 ```

If I press `q` on the frozen terminal to quit alacritty then as expected nothing happens as the terminal render appears to be frozen, but `htop` actually quits:
```
> ps -a | grep htop
>
```

The above tests indicate to me that this is a render issue rather than an actual freeze issue as somehow even though the terminal is completely frozen and does not re-render I can still interact with the active program by typing `q` and it actually quitting that program.

Any help would be much appreciated!

**Comment by kchibisov** [comment] 2023-12-29 00:30
duplicate of https://github.com/alacritty/alacritty/issues/7485

update hyprland.

**Comment by zeyadtamimi** [comment] 2023-12-29 00:31
Thanks for the blazing fast response, apologies for the noise.

**Closed by kchibisov** 2023-12-29 00:30 UTC
