### ISSUE TITLE
Must enable and disable vi-mode before entering any character

### ISSUE THREAD

**Issue by smsimone** [alacritty/alacritty#6890] opened 2023-04-26 21:24 UTC
Everytime I switch focus from another window to alacritty I have to enable and disable vi-mode by pressing `shift+ctrl+space` in order to be able to write something, otherwise the only keyboard events that the terminal listens to are `ctrl+c`, `tab` and `return`.

I tried to get the logs using `alacritty --print-events` but when I try to use the new window it generates the problem vanishes.

https://user-images.githubusercontent.com/64575218/234705755-627f0eaa-1d3b-4210-a2ba-944f07e59b90.mov

### Other
I'm using tmux 3.3a, but I have the same problem both with tmux on and off

### System

OS: macOS
Version: 0.12.0

### Logs
```
[0.000496469s] [INFO ] [alacritty] Welcome to Alacritty
[0.001183942s] [INFO ] [alacritty] Version 0.12.0 (5a72819)
[0.003010411s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/smaso/.config/alacritty/alacritty.yml"
                                     "/Users/smaso/.config/alacritty/themes/themes/mountain.yaml"
[0.004239859s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.061914724s] [INFO ] [alacritty] Using Apple CGL
[0.128609988s] [INFO ] [alacritty] Window scale factor: 2
[0.133626978s] [DEBUG] [alacritty] Loading "Iosevka Nerd Font Mono" font
[0.246963990s] [INFO ] [alacritty] Running on Intel(R) Iris(TM) Plus Graphics 645
[0.247020566s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.254646264s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.278307958s] [INFO ] [alacritty] Cell size: 12 x 30
[0.278372386s] [INFO ] [alacritty] Padding: 12 x 20
[0.278397712s] [INFO ] [alacritty] Width: 3360, Height: 2050
[0.279955547s] [INFO ] [alacritty] PTY dimensions: 67 x 278
[0.284844502s] [INFO ] [alacritty] Initialisation complete
[0.368722300s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.442675876s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='q', params=[0], intermediates=[62]
[0.535915077s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='h', params=[7727], intermediates=[63]
```

**Comment by chrisduerr** [comment] 2023-04-29 15:41
Duplicate of https://github.com/alacritty/alacritty/issues/6817.

**Closed by chrisduerr** 2023-04-29 15:41 UTC
