### ISSUE TITLE
Feature Request: use font size as the smallest unit for resizing windows

### ISSUE THREAD

**Issue by leaxoy** [alacritty/alacritty#6379] opened 2022-10-05 15:06 UTC
If already exist an issue, feel free to close this. (I searched the issue list, and not found)

Other terminal app resize window use font size as the smallest unit, like iterm2, wezterm(https://github.com/wez/wezterm/search?q=use_resize_increments&type=code).

For alacritty, I can't find such option control this. Use pixel as resize unit is flexible, but in sometimes, use font size will make ui looks consistent.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/8556349/194094995-9c91fdc7-8e27-4e01-9d41-bc7520d152c4.png">
<img width="279" alt="image" src="https://user-images.githubusercontent.com/8556349/194096447-3a4d94ab-70f3-4b5b-a146-51b62da13620.png">

the left one is alacritty, and the right one is iterm2

### System
OS: macOS
Version: alacritty 0.10.1 (2844606)

**Comment by chrisduerr** [comment] 2022-10-06 02:53
Duplicate of https://github.com/alacritty/alacritty/issues/388.

**Closed by chrisduerr** 2022-10-06 02:53 UTC
Labels: enhancement
