### ISSUE TITLE
Composite hangul characters aren't rendered properly

### ISSUE THREAD

**Issue by koterpillar** [alacritty/alacritty#4235] opened 2020-09-16 11:51 UTC
Alacritty does not render composite Hangul jamo (letters) correctly.

Crash course on Hangul:
* Ordinary Hangul characters look like 한 (and they have their own code points)
* However, there are three jamo (letters) in the above character: ㅎ ㅏㄴ (and these have their own code points)
* And there are _separate_ code points that combine together: ᄒ + ᅡ  + ᆫ becomes 한.

However, printing 한 (three code points) in Alacritty looks like this (jamo arranged roughly left-to-right):

![alacritty-hangul](https://user-images.githubusercontent.com/140276/93333084-263b6200-f866-11ea-8bae-9aea1b932c4c.png)

Expected behaviour from gnome-terminal:

![gnome-terminal-hangul](https://user-images.githubusercontent.com/140276/93333192-49661180-f866-11ea-97fa-6a47bf054824.png)

### System

OS: Linux (Fedora 32)
Version: alacritty 0.5.0
Linux/BSD: Wayland, Gnome

**Comment by kchibisov** [comment] 2020-09-16 12:09
Seems like duplicate of #3830 to me.

**Comment by chrisduerr** [comment] 2020-09-16 17:06
Might also be #3731 (or font layout in general).

**Comment by koterpillar** [comment] 2020-09-16 22:18
Thank you for triaging! I was afraid it'd be a duplicate but at least now it can be a pointer to people searching for Hangul issues specifically.

**Comment by nixpulvis** [comment] 2020-09-28 03:02
FWIW, 한 renders fine for me in Alacritty. Perhaps it's a font issue for you...

**Comment by kchibisov** [comment] 2020-09-28 03:05
>FWIW, 한 renders fine for me in Alacritty. Perhaps it's a font issue for you...

It's not a font issue. You've likely used a dedicated char, but there's a compose version of it. Try `한`

**Comment by koterpillar** [comment] 2020-09-28 03:15
If you want an easy way to reproduce:

```shell
echo -e '\u1112\u1161\u11ab'
```

**Comment by chrisduerr** [comment] 2020-09-28 11:08
@kchibisov Why have you re-opened this issue?

**Comment by kchibisov** [comment] 2020-09-28 14:19
>@kchibisov Why have you re-opened this issue?

Oh, I thought @nixpulvis closed that issue, but it was initially closed as a duplicate. sorry.

**Closed by kchibisov** 2020-09-28 14:19 UTC
Labels: S - font

**Comment by nixpulvis** [comment] 2020-09-28 14:28
Ah interesting. I wasn't aware that Firefox was rendering a dedicated character for this. I'm still learning how all these combining characters work in general.

**Comment by chrisduerr** [comment] 2020-09-28 22:54
Yeah generally most applications try to perform unicode normalization whenever possible, to avoid various problem areas.
