### ISSUE TITLE
Please add support for blinking text !!

### ISSUE THREAD

**Issue by budheswarbaghel** [alacritty/alacritty#3300] opened 2020-02-06 12:21 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

Doesn't have support for blinking text:
echo  -e "\033[33;5mTitle of the Program\033[0m"

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment] 2020-02-06 12:28
duplicate of #2365

**Closed by kchibisov** 2020-02-06 12:28 UTC
