### ISSUE TITLE
macOS - mod keys are sticky for SpawnNewInstance

### ISSUE THREAD

**Issue by K-JBoon** [alacritty/alacritty#3413] opened 2020-03-03 15:01 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: macOS
Version: alacritty 0.4.2-dev (f83d55f)

### Bug
When using the following keybind on macOS:

```
key_bindings:
     - { key: N, mods: Command, action: SpawnNewInstance }
```

the Command key stays in the pressed state when you focus back on the old terminal you spawned the new one from. This means that if you type for example 'ssh' it will hide when you hit the h, etc.

I fixed this in my own build in input.rs:671 with

```rust
                if binding.action == Action::SpawnNewInstance {
                    self.modifiers_input(mods - binding.mods);
                }
```

but I'm not sure what the clean way to do this is.

**Comment by chrisduerr** [comment] 2020-03-03 15:26
Duplicate of https://github.com/alacritty/alacritty/issues/3188.

**Closed by chrisduerr** 2020-03-03 15:26 UTC
