### ISSUE TITLE
feature: path expansion on config imports

### ISSUE THREAD

**Issue by MatrixManAtYrService** [alacritty/alacritty#4399] opened 2020-11-10 17:38 UTC
First of all, thank you.  I'm really enjoying alacritty.

My alacritty.yml looks like this:

```yaml
import:
        - /home/matt/.config/alacritty/colors.yml
        - /home/matt/.config/alacritty/config.yml
```

I'd like to be able to use strings like `~/.config/alacrity/config.yml` instead of absolute paths so that when I use git to sync this config to a different machine (with a different username), it all works out.

**Comment by chrisduerr** [comment] 2020-11-10 19:35
Duplicate of https://github.com/alacritty/alacritty/issues/4157.

**Closed by chrisduerr** 2020-11-10 19:35 UTC
