### ISSUE TITLE
If nvidia drivers are installed, Alacritty wakes up the dGPU despite not using it

### ISSUE THREAD

**Issue by chris-morgan** [alacritty/alacritty#6366] opened 2022-09-27 13:48 UTC
I use a laptop (ASUS Zephyrus G15 (2021), GA503QM) with AMD integrated graphics (from the Ryzen 5800HS) and an NVIDIA dedicated GPU. Normally I don’t have a driver installed for the NVIDIA GPU. `supergfxctl --get` reports `hybrid`, and `supergfxctl --status` will report `suspended`.

But recently I’ve taken to sometimes having the `nvidia-dkms` package installed.

**Observation:** When it is installed, starting Alacritty loads the `nvidia` kernel module, spins up the dGPU if it is suspended (which it almost certainly is), which makes startup take 2–5 seconds instead of a couple of hundred milliseconds, and consumes a bunch of extra power, even though Alacritty doesn’t end up *using* the dGPU, according to `nvtop` and the observation that the dGPU goes back to sleep after ten seconds or something (`supergfxctl --status` goes from reporting `active` back to reporting `suspended`, and power consumption drops significantly), after just having shortened my battery life by a minute or so each time. Alacritty also prevents me from unloading the nvidia kernel module. (`lsof` tells me it’s keeping /dev/nvidia0 and /dev/nvidiactl open).

**Expectation:** If Alacritty isn’t going to use the dGPU, I expect it to not wake it up or load its kernel module. And given a dual-GPU configuration like mine, I expect it to stick with the iGPU and not touch the dGPU.

### System

Arch Linux, Sway (Wayland). Alacritty 0.10.1.

**Comment by chrisduerr** [comment] 2022-09-28 12:59
Can you try 0.11.0, just to be sure it's still broken with the latest version?

**Comment by Quaqqer** [comment] 2022-12-14 20:43
I am having the same problem with the same symptoms, on version 0.11.0.

It takes about 1.3s to start when the nvidia card is sleeping. It's even slow to startup for me when the dGPU is disabled in bios but I still have the nvidia driver installed. If I remove the nvidia drivers the startup time is ~130ms as expected.

These are the options i use in NixOS:
```nix
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;

    powerManagement = {
      enable = true;
      finegrained = true;
    };

    prime = {
      offload.enable = true;
      nvidiaBusId = "PCI:1:00:0";
      amdgpuBusId = "PCI:4:00:0";
    };
  };
```

**Comment by kchibisov** [comment] 2022-12-15 01:39
I'd suggest to try latest master. Also the issue is not related to alacritty, but `libglvnd` issue. It's likely even if you have disabled nvidia card everywhere you still have a config in libglvnd to use it, so it tries to open it.

Would suggest to try disabling nvidia config in libglvnd, but not sure how to do that on nixos...

**Comment by D0ot** [comment] 2023-03-23 18:54
same issue met here, 

alacritty would try loading nvidia modules on launch though the nvidia card is already using vfio-pci driver

it slows down the launching

**Comment by D0ot** [comment] 2023-03-23 19:28
It seems that the libnvidia-glsi.so in nvidia-utils causes the problem.

**Comment by D0ot** [comment] 2023-03-23 19:34
To address slow lunch time issue a possible workaround could be to rename the file /usr/bin/nvidia-modprobe.

**Comment by kchibisov** [comment] 2023-03-23 19:39
You might try latest master, it might do something better. But if you want to solve it, the solution is to address it on `libglvnd` level, because that's what is responsible for resolving between nvidia and mesa...

On systems with only mesa or only nvidia that won't be an issue(or if you keep only mesa/nvidia in libglvnd).

**Comment by D0ot** [comment] 2023-03-24 14:40
Yes, renaming the bin is just a temporary and dirty workaround...

I have just found another solution, just set env variable `__EGL_VENDOR_LIBRARY_FILENAMES` like these:
```
export __EGL_VENDOR_LIBRARY_FILENAMES="/usr/share/glvnd/egl_vendor.d/50_mesa.json"
```
or
```
export __EGL_VENDOR_LIBRARY_FILENAMES="/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
```
to choose a vendor.

The environment variable is used in libglvnd

![image](https://user-images.githubusercontent.com/49939375/227555060-176c7ae3-d137-45c8-b0de-61b253330188.png)

**Comment by dm17** [comment] 2023-04-10 10:54
Any updates? The temporary solution would be to uninstall the dGPU drivers entirely and just use the integrated GPU, it seems.

**Comment by kchibisov** [comment] 2023-04-10 11:33
Setup `libglvnd` variable for alacritty to always pick the integrated GPU? Alacritty have zero control what GPU it'll pick, because you don't have control over it with OpenGL.

The variable was already suggest here.

**Comment by peterzky** [comment] 2023-04-21 13:35
NixOS
```nix
environment.sessionVariables = {
  "__EGL_VENDOR_LIBRARY_FILENAMES" = "/run/opengl-driver/share/glvnd/egl_vendor.d/50_mesa.json";
};
```

**Comment by moreka** [comment] 2024-01-08 12:39
With setting `"__EGL_VENDOR_LIBRARY_FILENAMES"` to only mesa, still the lag is there and the nvidia card turns on for a while. In `alacritty -vv`, I see that after a lag, `mesa` driver is chosen (`Intel UHD Graphics`). This makes me wonder if the problem is really with `libglvnd`. I tested with kitty, and the lag (and turning on of the nvidia card) did not happen. Glxgears, for example, does not have a lag when opening and does not turn the nvidia card on. Is there a way to dig into this issue deeper? Are there more verbose debug options to see why the lag is there?

**Comment by moreka** [comment] 2024-01-08 16:38
it is fixed completely, without needing to set `__EGL_VENDOR_LIBRARY_FILENAMES`. Thanks a lot!

**Closed** 2024-01-09 01:05 UTC
