### ISSUE TITLE
Windows 10: Alacritty v0.5.0 does not start

### ISSUE THREAD

**Issue by karanj798** [alacritty/alacritty#4102] opened 2020-08-10 02:55 UTC
Tried to open alacritty from Windows' command line, it fails to open because of syntax error.

### System

OS: Windows 10
Version: `alacritty --version` alacritty 0.5.0 (a6681e3)
Windows: WinPTY(see `alacritty -v` output)

### Logs
```
C:\Users\XXX\Downloads\Alacritty-v0.5.0-windows-portable>alacritty.exe -v

C:\Users\XXX\Downloads\Alacritty-v0.5.0-windows-portable>Created log file at "C:\Users\XXX\AppData\Local\Temp\Alacritty-3916.log"
[2020-08-09 22:45:38.625018100] [INFO] Welcome to Alacritty
[2020-08-09 22:45:38.625018100] [INFO] No configuration file found
[2020-08-09 22:45:38.687517100] [INFO] Device pixel ratio: 1
[2020-08-09 22:45:38.750018300] [ERROR] Alacritty encountered an unrecoverable error:

        There was an error initializing the shaders: Failed compiling shader at C:\Users\travis\build\alacritty\alacritty\alacritty/../res/text.v.glsl: ERROR: 0:16: 'location' : syntax error parse error
```

**Comment by chrisduerr** [comment] 2020-08-10 08:34
What GPU do you have? Looks like it doesn't support OpenGL 3.3+.

**Comment by kchibisov** [comment] 2020-08-10 08:37
Does 0.4.3 start?

**Comment by karanj798** [comment] 2020-08-10 13:49
@chrisduerr seems to be correct, my GPU doesn't support OpenGL 3.3+.

**Comment by chrisduerr** [comment] 2020-08-10 14:04
Duplicate of #128.

**Closed by chrisduerr** 2020-08-10 14:04 UTC
Labels: A - needs repro, H - windows
