### ISSUE TITLE
Mouse Wheel In No Mode Always Enters A Kind Of Scrollback Mode

### ISSUE THREAD

**Issue by alex-courtis** [alacritty/alacritty#7588] opened 2024-01-09 00:40 UTC
I am an alacritty enthusiast since its first versions - I really appreciate this fantastic tool!

Mouse wheel in Vi or Search mode scrolls up and down as expected.

When `scrolling.history = 0` mouse wheel up does nothing when no mode.

When `scrolling.history > 0` mouse wheel up always enters a kind of history mode that may be navigated with the scroll wheel only. Any key inputs result in the terminal immediately scrolling down and passed to the shell.

Please:
1. Allow disabling of this feature.

Nice to haves:
1. Wheel up in no mode enters Vi mode.
1. Allow mapping of wheel via `mouse.bindings`

### System

OS: Linux 6.6.10-arch1
Version: 0.13.0 and 415be940
Linux/BSD: Wayland River

### Logs

Font/Terminal size: `alacritty -vv`

```
[0.000010823s] [INFO ] [alacritty] Welcome to Alacritty
[0.000055598s] [INFO ] [alacritty] Version 0.14.0-dev (415be940)
[0.000064392s] [INFO ] [alacritty] Running on Wayland
[0.001694846s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/alex/.config/alacritty/alacritty.toml"
                                     "/home/alex/.config/alacritty/appearance.toml"
                                     "/home/alex/.config/alacritty/bindings.toml"
[0.002064320s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.002075310s] [INFO ] [alacritty] winit event: Resumed
[0.019672615s] [INFO ] [alacritty] Using EGL 1.5
[0.019715174s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.022671815s] [INFO ] [alacritty] Window scale factor: 1
[0.023345085s] [DEBUG] [alacritty] Loading "monospace" font
[0.030440112s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.033182770s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.035725486s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.038291007s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.040506740s] [INFO ] [alacritty] Running on AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 16.0.6, DRM 3.54, 6.6.10-arch1-1)
[0.040517269s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.2-arch1.2, shader_version 4.60
[0.040523916s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.044905951s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.045667378s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.049252063s] [INFO ] [alacritty] Cell size: 10 x 19
[0.049264044s] [INFO ] [alacritty] Padding: 0 x 0
[0.049268426s] [INFO ] [alacritty] Width: 800, Height: 600
[0.049309613s] [INFO ] [alacritty] PTY dimensions: 31 x 80
```

Keyboard and bindings: `alacritty --print-events`
Wheel up only

```
[16.016724119s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 12383, tv_nsec: 937862988 }, requested_resume: None })
[16.016780119s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732694286496)), event: MouseWheel { device_id: DeviceId(Wayland(DeviceId)), delta: LineDelta(0.0, 1.0), phase: Moved } }
[16.016803659s] [INFO ] [alacritty] winit event: AboutToWait
[16.017116181s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 12387, tv_nsec: 543351039 }, requested_resume: None })
[16.017121710s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732694286496))), payload: Terminal(MouseCursorDirty) })
[16.017129455s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732694286496)), event: RedrawRequested }
[16.018580280s] [INFO ] [alacritty] winit event: AboutToWait
```

**Comment by alex-courtis** [comment] 2024-01-09 00:53
I'm not a Rust programmer however am happy to submit a PR for the chosen course of action.

**Comment by chrisduerr** [comment] 2024-01-09 14:24
I'm confused by this request. Do you want to disable scroll history?

**Comment by alex-courtis** [comment] 2024-01-10 06:36
Scroll history on please.

Disable scroll wheel up to start history scrolling OR
Scroll wheel up can be configured to enter ViMode

I suspect there is some fundamental misunderstanding I am making. Please do advise if I can make this clearer, perhaps via a video.

**Comment by chrisduerr** [comment] 2024-01-17 02:14
So you want scroll history as usual in vi mode, but no way to scroll with the mouse? Can't you just… not scroll if you don't want to?

**Comment by alex-courtis** [comment] 2024-01-20 03:00
> So you want scroll history as usual in vi mode, but no way to scroll with the mouse? Can't you just… not scroll if you don't want to?

Mouse scrolling in vi mode is expected and desirable behaviour:
![00-ctrl-space-vimode](https://github.com/alacritty/alacritty/assets/1505378/db8b6205-2310-4f98-97fa-1af0b02dec09)

The undesirable behaviour is on wheel up in no mode, which enters a scrolling mode that is not vi mode. I do not know the name of that mode.
![01-wheel-up-unknown-mode](https://github.com/alacritty/alacritty/assets/1505378/25abd6aa-e779-4dbe-a583-af483b5fc618)

In the above case, it is desirable to enter vi mode on wheel up, rather than the above mode.

What am I looking for? Something like this, to bind mouse wheel up to vi mode similar to default C-S-Space
```toml
[mouse]
action = "ToggleViMode"
mouse = "WheelUp"
mode = "~Alt|~Vi|~Search"
```

**Comment by alex-courtis** [comment] 2024-01-20 03:00
Above screen captures used the following configuration, for clarity:

```toml
[cursor]
vi_mode_style = "Block"

[font]
size = 14

[colors.vi_mode_cursor]
cursor = "0x00FF00"
text =   "0xFF00FF"

[colors.line_indicator]
background = "0x0000FF"
foreground = "0xFFFF00"
```

**Comment by chrisduerr** [comment] 2024-01-21 00:44
What is wrong with your text? Are you using panfrost?

**Comment by alex-courtis** [comment] 2024-01-21 00:45
I used `clear ; print "\n\n\n\n\n\n"; toilet -w 100 -f mono9 -F metal "I find        Alacritty a   great pleasureto use"` to show a banner to make it a bit easier to show scrolling of history.

**Comment by kchibisov** [comment] 2024-02-23 13:25
I guess it's a duplicate of #5296

**Closed by kchibisov** 2024-02-23 13:25 UTC
Labels: F - insufficent detail

**Comment by alex-courtis** [comment] 2024-02-24 02:15
> I guess it's a duplicate of #5296 . The end resolution to add up/down wheel events.

That will be a great solution, thank you.
