### ISSUE TITLE
Sometimes cjk character can only see the left half

### ISSUE THREAD

**Issue by flw-cn** [alacritty/alacritty#4038] opened 2020-07-27 00:57 UTC
Sometimes the cjk character and the spacer after it are assigned to a different texture atlas, resulting in only the left half of the character being drawn.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/5546718/88493741-5d6b6080-cfe5-11ea-9773-9228a8602a9c.png">

The chinese character <img width="28" alt="image" src="https://user-images.githubusercontent.com/5546718/88494117-18482e00-cfe7-11ea-8da9-514a1bdc4f3e.png"> is drawn as <img width="35" alt="image" src="https://user-images.githubusercontent.com/5546718/88494059-d61eec80-cfe6-11ea-93a2-710d8365e0f2.png">

### System

OS: macOS
Version: alacritty 0.6.0-dev (dd32447)

### Logs

```
[2020-07-27 08:41:02.638338000] [DEBUG] Using environment locale: en_US.UTF-8/UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.U
TF-8
[2020-07-27 08:41:02.646170000] [INFO] Welcome to Alacritty
[2020-07-27 08:41:02.646357000] [INFO] Configuration loaded from "/Users/flw/.config/alacritty/alacritty.yml"
[2020-07-27 08:41:02.767907000] [DEBUG] Estimated DPR: 2
[2020-07-27 08:41:02.767989000] [DEBUG] Estimated Cell Size: 21 x 45
[2020-07-27 08:41:02.768034000] [DEBUG] Estimated Dimensions: None
[2020-07-27 08:41:02.958046000] [INFO] Device pixel ratio: 2
[2020-07-27 08:41:02.961405000] [INFO] Initializing glyph cache...
[2020-07-27 08:41:03.041121000] [INFO] ... finished initializing glyph cache in 0.079594508s
[2020-07-27 08:41:03.041218000] [INFO] Cell Size: 21 x 45
[2020-07-27 08:41:03.041248000] [INFO] Padding: 0 x 0
[2020-07-27 08:41:03.041280000] [INFO] Width: 1600, Height: 1200
[2020-07-27 08:41:03.043164000] [INFO] PTY dimensions: Line(26) x Column(76)
[2020-07-27 08:41:03.055212000] [INFO] Initialisation complete
[2020-07-27 08:41:03.557021000] [DEBUG] New num_cols is 121 and num_lines is 35
[2020-07-27 08:41:03.573908000] [INFO] Width: 2560, Height: 1600
```

**Comment by kchibisov** [comment] 2020-07-27 07:10
duplicate of https://github.com/alacritty/alacritty/issues/791

**Closed by kchibisov** 2020-07-27 07:10 UTC
