### ISSUE TITLE
When using an input method, the first character following an arrow key is lost.

### ISSUE THREAD

**Issue by hexchain** [alacritty/alacritty#4588] opened 2020-12-17 16:38 UTC
Using input method immediately following an arrow key press causes the first character to be lost.

Here is a video clip to demonstrate this problem: https://fars.ee/Perq.webm. In this clip, I tried to type "ceshi" (which should result in "测试"), space (to commit the text), left key, "ceshi", space; the second "ceshi" only types in the second character "试".

### System

OS: Linux
Version: 0.6.0 (04cbf767) (also happens on 116faba7)
Linux/BSD: X11 Plasma

### Logs
Keyboard and bindings: 
[events.log](https://github.com/alacritty/alacritty/files/5710839/events.log)

**Comment by chrisduerr** [comment] 2020-12-17 22:02
Can you reproduce this in a different shell like `bash`?

**Comment by hexchain** [comment] 2020-12-17 22:06
Yes.

**Comment by chrisduerr** [comment] 2020-12-17 22:07
Could you share the output of `alacritty --print-events | grep "ReceivedCharacter"`.

**Comment by hexchain** [comment] 2020-12-17 22:39
Here is it:
```
[2020-12-17 23:38:21.693703154] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(100663300))), event: ReceivedCharacter('测') }
[2020-12-17 23:38:21.693753651] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(100663300))), event: ReceivedCharacter('试') }
[2020-12-17 23:38:24.649382324] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(100663300))), event: ReceivedCharacter('测') }
[2020-12-17 23:38:24.649443366] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(100663300))), event: ReceivedCharacter('试') }
```

**Comment by chrisduerr** [comment] 2020-12-17 22:42
Hmm interesting, looks like this might actually be an issue with Alacritty, but I'm having trouble reproducing it.

Can you reproduce this by copy/pasting these two symbols, or does this only happen when inserting them using IME? And do other terminals show similar behavior or do things right?

**Comment by hexchain** [comment] 2020-12-17 22:46
I can't reproduce by copying and pasting.

Other terminals do things right. I've tested `termite` with `GTK_IM_MODULE=xim`, and `konsole`.

**Comment by chrisduerr** [comment] 2020-12-19 05:36
Do you have your IME setup for single cell width characters too? I'd be curious if this only happens with fullwidth characters or also with half width.

**Comment by hexchain** [comment] 2020-12-19 11:18
Not sure I fully understand your questions, but here's what I have done:

I tried to type "ceshi", enter (to commit the pre-edit string, not the text), down arrow key, "ceshi", enter. The result is "ceshieshi", which means the "c" in the second "ceshi" is also lost. `--print-events` output looks normal.

**Comment by chrisduerr** [comment] 2020-12-19 18:09
Interesting, I thought it would have been the fullwidth character creating the issue. But it seems like halfwidth also cause troubles.

I'm surprised this was never reported by anyone before though, since this seems like something people should quite commonly run into. You're not in insert mode though, right? So when you go left and start typing normally without IME, you don't delete any characters?

I'll have to see if I can reproduce this myself, but I'll have to setup IME first.

**Comment by chrisduerr** [comment] 2020-12-19 18:47
I've been able to reproduce this, I'll take a look, thanks.

**Comment by chrisduerr** [comment] 2020-12-19 19:54
Hm, while someone else was able to reproduce this issue, I am not able to reproduce it myself using fcitx.

Which IME do you use?

**Comment by hexchain** [comment] 2020-12-19 20:01
I'm using fcitx5.

**Comment by chrisduerr** [comment] 2020-12-19 20:17
I'd assume this would be fairly easy to fix when able to reproduce it, but unfortunately it seems difficult to troubleshoot without it.

**Comment by wengxt** [comment] 2020-12-21 01:25
Hi, I could easily produce this with fcitx so I don't think it's related to the fcitx5 using a new xim implmentation via xcb-imdkit. 
1. Type something in the terminal
2. Press Ctrlt +Alt +H to trigger the spell check in fcitx (normally you should see a notification on desktop)
3. Press left
4. type "app"
5. Use mouse to select the candidate, only "pp" got typed into alacritty.

So I think the tricky part to reproduce it is that you can't press any modifier key between step 3. 4. 5, otherwise the bug could not be triggered.

I actually suggest you try this:
https://github.com/fcitx/xcb-imdkit/

compile it with standard cmake procedure (need xcb, xcb-util, xcb-util-keysyms, should be generally available on any distribution), no need to make install it.
```
mkdir build
cmake ..
make # or possibly ninja if cmake decide to use ninja instead.
```

After compile it you should be able to find test_server under build/test directory.

First run ./test_server

Then start alacritty with
XMODIFIERS=@im=test_server alacritty

Then press "Ctrl+Space" in alacritty, check if press "t" will produce "hello world你好世界켐ㅇㄹ貴方元気？☺".
If so, then it's working, then you can reproduce it with
1. Press Left
2. Press "t'
3. only "ello world你好世界켐ㅇㄹ貴方元気？☺" is committed to the alacritty.

**Comment by zerovip** [comment] 2020-12-29 16:29
I ran into the same problem, with ibus + rime. Downgrading to version alacritty-0.5.0 solved this problem.

**Comment by zerovip** [comment] 2020-12-29 16:30
I ran into the same problem, with ibus + rime. Downgrading to version alacritty-0.5.0 solved this.

**Comment by chrisduerr** [comment] 2020-12-29 19:09
> I ran into the same problem, with ibus + rime. Downgrading to version alacritty-0.5.0 solved this.

That sounds very helpful. Could someone bisect the exact commit that broke this?

**Comment by wengxt** [comment] 2020-12-30 03:45
1d00883f10500675bbe2bb62916d6a16499972ee is the bad commit.

I don't understand the code but the commit message looks quite related.

**Comment by chrisduerr** [comment] 2020-12-30 08:04
Very, very interesting. Could someone share their full `alacritty --print-events` log with me? Suppress chars should only ever go to `true` when there's a key binding triggered, so this doesn't make a ton of sense to me.

Also could one of you try the latest master?

**Comment by zerovip** [comment] 2020-12-30 08:55
```
$ ./target/release/alacritty --version
alacritty 0.7.0-dev (65f6e22)

$ ./target/release/alacritty --config-file=/dev/null --print-events > ~/alacritty_log
```
alacritty_log: <https://pastebin.com/XjxnVmt2>

Notes:
- 16:38:58.280292610-16:38:58.443140558    I opened alacritty;
- 16:39:10.370873621-16:39:11.476050654    I typed “测试” normally
- 16:39:24.425510975-16:39:24.579286081    I hit right arrow key
- 16:39:34.972854135-16:39:37.034641535    I typed “测试” but only “试” showed up
- 16:39:52.516228851-end    I closed this window

**Comment by chrisduerr** [comment] 2020-12-30 09:10
> I hit right arrow key

Oooooh, right. Now I finally understand it. That's what is triggering the key binding and that's exactly what is causing the problem. Arrow keys are implemented using keybindings, but since they don't generate any `ReceivedCharacter` events the suppression for the binding is never released. So then when the IME text shows up the first character releases the key suppression.

Thanks a bunch for that, fix should be trivial now.

**Comment by zerovip** [comment] 2020-12-30 09:17
Very glad that we made progress! Thank you for maintaining this excellent project! Happy new year~

**Comment by chrisduerr** [comment] 2020-12-31 01:34
Can someone verify that https://github.com/alacritty/alacritty/pull/4632 does indeed fix this?

**Comment by zerovip** [comment] 2020-12-31 04:29
Verified: #4632 does indeed fix this. Thank you!

**Closed** 2020-12-31 05:06 UTC
Labels: B - bug, D - easy, S - input
