### ISSUE TITLE
Don't use rounded corners for window decoration on maximized windows on the whole screen or part of it

### ISSUE THREAD

**Issue by Porkepix** [alacritty/alacritty#6398] opened 2022-10-14 07:31 UTC
Since release 0.11.0, on Gnome Wayland window decorations seems to be back to something more usual (it was pretty broken in 0.10.1, but I also know window decoration is some disputed topic due to upstream responsibility for some things, so I don't know if the issue here will be considered as an Alacritty issue or not) and looking much better, as opposed to what I shown in https://github.com/alacritty/alacritty/issues/5829
See 
![Screenshot from 2022-10-14 09-26-17](https://user-images.githubusercontent.com/709500/195787715-e270913d-9da5-4794-8b70-8ea49d310f9a.png)

When I wanted to show this screenshot I also realized that doing a screenshot targeted on the window doesn't captured the window decorations at all (I had to use selection), so I don't know if that's normal, but guess it's somehow related.

As for the issue itself, minor, but the window decoration use rounded corners which is fine on non-maximized windows, but doesn't looks fine on maximized or partially-maximized windows (ie. maximized on half the screen when pushing against one side) where it would be better to have squared corners filling the whole screen corner without leaving there a little gap, which is the behavior in other programs.
Here again I know this can be considered as an upstream issue but can't tell for myself what can be upstream's or Alacritty's choice or work here.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Wayland

### Logs

```$ alacritty -vv
Created log file at "/tmp/Alacritty-1481489.log"
[0.000003659s] [INFO ] [alacritty] Welcome to Alacritty
[0.000451191s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000552679s] [INFO ] [alacritty] Running on Wayland
[0.006323637s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/clement/.config/alacritty/alacritty.yml"
[0.008678269s] [DEBUG] [alacritty] Loading "Deja Vu Sans Mono" font
[0.045552357s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.055255922s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.064578277s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.074162543s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.076997716s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.077028508s] [DEBUG] [alacritty] Estimated window size: None
[0.077045916s] [DEBUG] [alacritty] Estimated cell size: 6 x 13
[0.083977259s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.160106736s] [INFO ] [alacritty] Running on Mesa Intel(R) HD Graphics 520 (SKL GT2)
[0.160168855s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.172451144s] [INFO ] [alacritty] Display scale factor: 1
[0.172486868s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.190532053s] [INFO ] [alacritty] Cell size: 6 x 13
[0.190588839s] [INFO ] [alacritty] Padding: 0 x 0
[0.190600787s] [INFO ] [alacritty] Width: 800, Height: 600
[0.191691412s] [INFO ] [alacritty] PTY dimensions: 46 x 133
[0.195551436s] [INFO ] [alacritty] Initialisation complete
[0.197231599s] [DEBUG] [alacritty_terminal] New num_cols is 320 and num_lines is 77
[0.202646189s] [INFO ] [alacritty] Padding: 0 x 0
[0.202706719s] [INFO ] [alacritty] Width: 1920, Height: 1013
[0.223974488s] [DEBUG] [alacritty_terminal] New num_cols is 320 and num_lines is 46
[0.224036097s] [INFO ] [alacritty] Padding: 0 x 0
[0.224057400s] [INFO ] [alacritty] Width: 1920, Height: 600
[3.451812956s] [DEBUG] [alacritty_terminal] New num_cols is 320 and num_lines is 77
[3.459509384s] [INFO ] [alacritty] Padding: 0 x 0
[3.459577671s] [INFO ] [alacritty] Width: 1920, Height: 1013
[3.480475556s] [DEBUG] [alacritty_terminal] New num_cols is 133 and num_lines is 46
[3.492609985s] [INFO ] [alacritty] Padding: 0 x 0
[3.492721301s] [INFO ] [alacritty] Width: 800, Height: 600
```

**Comment by PolyMeilex** [comment] 2022-10-14 09:36
Corresponding issue in upstream decorations library: https://github.com/PolyMeilex/sctk-adwaita/issues/14
Potentially duplicate of: #6338

**Closed** 2022-10-14 14:04 UTC
