### ISSUE TITLE
Incomplete support for running background process in subshell

### ISSUE THREAD

**Issue by foreverbell** [alacritty/alacritty#833] opened 2017-10-12 05:11 UTC
(I use Ubuntu 16.04 with X11, and I can't find a similar issue so I am opening a new one)

`(cmd)&` is an idiom for running a background process in a subshell. The subprocess should still be running even after the host terminal is closed.

For example, in `gnome-terminal`, you can execute `(gnome-terminal)&` in terminal A, which spawns a new terminal B. After terminal A is closed, terminal B is still alive.

Right now, in `alacritty`, the behavior is inconsistent with this syntax's semantics. After terminal A is closed, terminal B is also closed automatically.

**Comment by jwilm** [comment] 2017-10-12 14:57
I thought this was expected behavior. Isn't the typical solution to use `nohup` with the command so that when the shell closes it keeps running?

**Comment by foreverbell** [comment] 2017-10-12 16:41
Aha, `nohup cmd >/dev/null 2>&1 &` should be identical to `(cmd)&` for me.

`alacritty` is fine for the former command. But for latter command, `alacritty` does behave differently from other commonly used terminals like `gnome-terminal`, `xfce4-terminal` and `xterm`.

Feel free to close this issue if you think this is expected behavior, so we can use the former one as a workaround if user finds the latter one does not work.

**Comment by jwilm** [comment] 2017-10-12 17:29
Are you perhaps using a different shell in Alacritty than those other terminals? Seems strange that you'd have different behavior in that case.

**Comment by foreverbell** [comment] 2017-10-13 02:28
Nope, all use `/bin/bash` reported from `$SHELL$`.

**Comment by maximbaz** [comment] 2017-10-15 12:48
I thought that closing both terminals is an expected behavior too, surprisingly I see now that I don't reproduce the bug, in other words closing alacritty A does not close alacritty B for me.

I'm using `zsh`, and in `zsh` I believe if alacritty B was started as `alacritty &`, closing alacritty A should close both terminals, but if alacritty B was started as `alacritty &!` (which is doing something with `nohup` or `disown`), then closing alacritty A should not affect alacritty B.

**Comment by foreverbell** [comment] 2017-10-15 13:32
@maximbaz For `alacritty &`, closing both is expected, but things will get different if parentheses is added, i.e. `(alacritty)&` should not close the newly spawned terminal (if this is what behavior that semantics define).

In `zsh`,  my behavior of `alacritty &!` is same as you.

Here I summarize all these commands' behaviors after closing the old terminal A.

* `(alacritty)&`, terminal B is closed (this is what I think is strange, which is different from other terminals).
* `alacritty &`, terminal B is closed (this should be absolutely expected).
* `nohup alacritty >/dev/null 2>&1 &`, terminal B is not closed.
* In `zsh`, `alacritty &!`, terminal B is not closed.

**Comment by maximbaz** [comment] 2017-10-15 14:36
That's interesting to know, thanks.

My own experiments show that `alacritty` and `sakura` terminals show exactly the same results in the following experiments:

##### 1. Use `zsh` and empty `.zshrc` (no custom config at all)

```
// I used `sakura` in sakura terminal and `alacritty` in alacritty terminal in commands below
```

1. `(sakura)&` - closing A closes both A and B
2. `sakura &` - closing A closes both A and B
3. `nohup sakura >/dev/null 2>&1 &` - closing A closes only A
4. `sakura &!` - closing A closes only A

##### 2. Using my own config

Neither of the 4 actions close terminal B, only A is closed.

##### What's happening?

Further inspection showed that I use prezto and it has the following line below, which prevents closing terminal B after terminal A is closed:

```
unsetopt HUP              # Don't kill jobs on shell exit.
```

**Comment by Ongy** [comment] 2017-10-17 09:11
I've just found someting, that may be relevant to this issue.

[This SO answer](https://unix.stackexchange.com/questions/333539/lxterminal-in-the-netstat-output/333578#333578) which is essentially unrelated, mentions that 
> The visible effect of this is that the first lxterminal program that you invoke (and leave running) operates synchronously, whereas the second and subsequent ones do not. 

So if you have your terminal started from another terminal keep running, after the first terminal exits, it could be caused by a server/client architecture of the terminal.

Could you check whether that's the case with the terminals you are reporting working like that?

**Comment by foreverbell** [comment] 2017-10-17 12:12
After digging more, I find something interesting which may help understand this problem a bit.

I start a `xfce4-terminal`, and run these commands sequentially,

* `(xfce4-terminal)&`
* `(gnome-terminal)&`
* `(alacritty)&`
* `(xterm)&`

Then I close the old `xfce4-terminal`, and I find `alacritty` is dead, other three terminals are still alive.

**Comment by jrabbit** [comment] 2022-08-18 16:09
is there no way to have nohup do what I expect? Seems broken by design, unless I'm having a separate issue? commands run w/ nohup get killed, is alacritty sending bogus (extra) signals?

**Comment by chrisduerr** [comment] 2022-08-18 16:17
Nohup works just fine and isn't related to Alacritty. This issue generally doesn't seem like it should be much of Alacritty's concern.

**Closed by chrisduerr** 2022-08-18 16:17 UTC
